### ISSUE TITLE
API Management Service Identity Assignment

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10019]
I have updated api management service identity type from "`SystemAssigned, UserAssigned`" to "`SystemAssigned`"m the response is success. But when I get the api management service, it shows that the identity type is still "`SystemAssigned, UserAssigned`". I would like to ask if it is a normal action? 
Another case is that if I update an api management service identity type from "`SystemAssigned, UserAssigned`" to "`UserAssigned`". It could be updated successfully.

My request is:

PUT /subscriptions/XX/resourceGroups/XX/providers/Microsoft.ApiManagement/service/XX?api-version=2019-12-01 HTTP/1.1
{"identity":{"type":"SystemAssigned"},"location":"westeurope","properties":{"certificates":[],"customProperties":{"Microsoft.WindowsAzure.ApiManagement.Gateway.Protocols.Server.Http2":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false"},"hostnameConfigurations":[],"notificationSenderEmail":"apimgmt-noreply@mail.windowsazure.com","publisherEmail":"pub1@email.com","publisherName":"pub1","virtualNetworkType":"None"},"sku":{"name":"Developer","capacity":1},"tags":{}}

then I get the apim service:
Response:
{"id":"/subscriptions/XX/resourceGroups/XX/providers/Microsoft.ApiManagement/service/XX","name":"XX","type":"Microsoft.ApiManagement/service","tags":{},"location":"West Europe","etag":"AAAAAAAayDY=","properties":{"publisherEmail":"pub1@email.com","publisherName":"pub1","notificationSenderEmail":"apimgmt-noreply@mail.windowsazure.com","provisioningState":"Succeeded","targetProvisioningState":"","createdAtUtc":"2020-07-02T02:41:52.471015Z","gatewayUrl":"https://acctestam-200702104145.azure-api.net","gatewayRegionalUrl":"https://acctestam-200702104145-westeurope-01.regional.azure-api.net","portalUrl":"https://acctestam-200702104145.portal.azure-api.net","developerPortalUrl":"https://acctestam-200702104145.developer.azure-api.net","managementApiUrl":"https://acctestam-200702104145.management.azure-api.net","scmUrl":"https://acctestam-200702104145.scm.azure-api.net","hostnameConfigurations":[{"type":"Proxy","hostName":"acctestam-200702104145.azure-api.net","encodedCertificate":null,"keyVaultId":null,"certificatePassword":null,"negotiateClientCertificate":false,"certificate":null,"defaultSslBinding":true}],"publicIPAddresses":["52.178.28.94"],"privateIPAddresses":null,"additionalLocations":null,"virtualNetworkConfiguration":null,"customProperties":{"Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Protocols.Server.Http2":"False"},"virtualNetworkType":"None","certificates":[],"disableGateway":false,"apiVersionConstraint":{"minApiVersion":null}},"sku":{"name":"Developer","capacity":1},"**identity":{"type":"SystemAssigned, UserAssigned",**"principalId":"XX","tenantId":"XX","userAssignedIdentities":{"/subscriptions/XX/resourcegroups/acctestRG-200702104118102245/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acctestUAI-200702104118102245":{"principalId":"XX","clientId":"XX"}}}}

**Comment by solankisamir** [comment]
@yupwei68 yes, this is bug. We have made a fix and it is in the current release train. Expected to complete in 2 weeks.
