### ISSUE TITLE
The ID of `ProximityPlacementGroup` assigned in VMSS will be returned with the resource group in UPPER CASES

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#10016]
When creating the VMSS using compute api-version 2019-12-01 with the following body:
```
{
  "properties": {
     // other attribute omitted
     "proximityPlacementGroup": {
      "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/proximityPlacementGroups/ppg1"
    }
  }
}
```
After the successful creation, when getting the VMSS, in the response, the ID of the PPG will be converted to have a UPPER CASED resource group name, like this:
```
{
  "properties": {
     // other attribute omitted
     "proximityPlacementGroup": {
      "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/GROUP1/proximityPlacementGroups/ppg1"
    }
  }
}
```

**Comment by Drewm3** [comment]
This is the expected behavior for the Microsoft.compute resource provider. Resource group names are not case sensitive (i.e. "myGroup" and "mygroup" are the same resource group) so in most cases the resource group name in a response from Microsoft.compute will be in all upper case.
