### ISSUE TITLE
monitor, autoscale, MetricTrigger misses metricNamespace

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-rest-api-specs#10023]
azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\stable\2015-04-01\autoscale_API.json

A customer reports an issue in Azure CLI, https://github.com/Azure/azure-cli/issues/13908. After investigation, I find MetricTrigger misses metricNamespace.

**Comment by shilpasharmaAM** [comment]
This has been fixed, updated and now available. Closing this item, please open a new issue if there are additional problems.
