### ISSUE TITLE
Question about Storage.Blob that why changeFeed is designed to a nest block

### ISSUE THREAD

**Issue by lrxtom2** [Azure/azure-rest-api-specs#10035]
As the button on the portal. Shall we move the `changeFeed` to the top level as a single field?

**Comment by blueww** [comment]
@lrxtom2 
As this issue if for portal UI, not for swagger, would you like to raise it in Portal, and close this one.
![image](https://user-images.githubusercontent.com/6926193/86561375-0f89ac80-bf93-11ea-8ce7-2a0babd0428b.png)

**Comment by blueww** [comment]
@lrxtom2
I will close this as this issue is for portal, please raise you request on portal.
If you need further assistance, feel free to contact us again.
