### ISSUE TITLE
$expand not working in /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/resources, when $filter is provided

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-rest-api-specs#10051]
Spec
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L2295-L2301

If the request does not have `$filter`, `$expand` works perfectly (we use `$expand=provisioningState` to get `provisioningState` property).

But if `$filter` is used in query as well, `$expand` appears not working any more. The `provisioningState` property disappear in response, if e.g. `$filter=tagName eq 'vm'` is added to query.

**Comment by tim-nguyen-cs** [comment]
Hi @weidongxu-microsoft - this issue only occurs when filtering by tags. We are actively working on a solution set to rollout shortly. In the meantime, our REST API documentation has been updated with the appropriate `$expand` behavior - thanks!
