### ISSUE TITLE
API Management Custom Domain in different environment

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10065]
In creating API management Service, there'll always be a default custom domain to be returned.  Here for example in public cloud, the hostName is "apim-service-name.azure-api.net". But in Different cloud environment, like USGovCloud, ChinaCloud, GermanCloud, the hostName might differ. May I ask the hostName Suffix in different cloud environment?
For example:
{
    "id": "...",
    "name": "apim-yup",
    "type": "Microsoft.ApiManagement/service",
    "tags": {},
    "location": "East US",
    "etag": "AAAAAAAPO9k=",
    "properties": {
       ...
        "hostnameConfigurations": [
            {
                "type": "Proxy",
                "hostName": "apim-yup.azure-api.net",
                "encodedCertificate": null,
                "keyVaultId": null,
                "certificatePassword": null,
                "negotiateClientCertificate": false,
                "certificate": null,
                "defaultSslBinding": false
            }
        ],
       ...
    },
    "sku": {
        "name": "Developer",
        "capacity": 1
    },
    "identity": {
        "type": "SystemAssigned",
        ...
    }
}

**Comment by solankisamir** [comment]
USGov  - `azure-api.us`
China Cloud - `azure-api.cn`
BlackForest - `Not Supported`
