### ISSUE TITLE
[Monitor] Required parameters missing in logProfiles CreateOrUpdate operations

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#1006]
While creating new profile if 

1. I do not supply `categories ` then server throws `400: BadRequest `
```
"message": "'properties.categories' can't be null in diagnosticSettings."
```
2. I do not supply `retentionPolicy` then server throws `400: BadRequest `
```
"message": "'properties.retentionPolicy' can't be null in diagnosticSettings."
```

`LogProfileProperties` model in the swagger must include `categories` & `retentionPolicy` in the required list [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/2016-03-01/swagger/logProfiles_API.json#L234)

**Comment by gucalder** [comment]
Verified, both must be marked as required, since that is what the server expects.
