### ISSUE TITLE
Link to swagger spec broken

### ISSUE THREAD

**Issue by stdas** [Azure/azure-rest-api-specs#101]
Hey guys,

This page supposedly giving the link to the Swagger 2.0 spec is linked to in [this doc](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md), but appears to 404:

https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/Swagger-spec2.0

Thanks,

Steven

**Comment by amarzavery** [comment]
@stdas - The link has been fixed in this doc: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md
