### ISSUE TITLE
`elasticPoolName` is null for the results returned from `restorableDroppedDatabases`

### ISSUE THREAD

**Issue by bosh-ms** [Azure/azure-rest-api-specs#10112]
Imagine a database that was in an elastic pool was deleted.
When issuing a request to perform a PIT restore for the database with an Elastic Pool as a target, it's required to specify the Elastic Pool ID:
```
{
  "location": "westeurope",
  "properties": {
    "createMode": "Restore",
    "restorableDroppedDatabaseId": "/subscriptions/{subscriptionid}/resourceGroups/{resourcegroup}/providers/Microsoft.Sql/servers/{server}/restorableDroppedDatabases/{restorableDbId}",
    "restorePointInTime": "2020-07-13T14:50:31.503Z",
    "elasticPoolId": "/subscriptions/{subscriptionid}/resourceGroups/{resourcegroup}/providers/Microsoft.Sql/servers/{server}/elasticPools/{poolname}"
  }
```

However, the results of `restorableDroppedDatabases` call always have `null` as the value of `elasticPoolName` property, even for the databases that were in a pool. The API version is `api-version=2014-04-01`, which is the latest available.
```
{
            "id": "/subscriptions/{subscriptionid}/resourceGroups/{resourcegroup}/providers/Microsoft.Sql/servers/{server}/restorableDroppedDatabases/pooldb2,132391256405870000",
            "name": "pooldb2,132391256405870000",
            "type": "Microsoft.Sql/servers/restorableDroppedDatabases",
            "location": "West Europe",
            "properties": {
                "databaseName": "pooldb2",
                "edition": "Basic",
                "maxSizeBytes": "2147483648",
                "serviceLevelObjective": "ElasticPool",
                "elasticPoolName": null,
                "creationDate": "2020-07-13T14:34:04.987Z",
                "deletionDate": "2020-07-13T14:54:00.587Z",
                "earliestRestoreDate": "2020-07-13T14:43:40Z"
            }
        }
```

I understand that it should be possible to restore the database to a different pool/to standalone db, so it makes sense that this field is `null` in a case the original pool no longer exists. However, the field is always `null`, even if the original pool still exists.
If that's the case and the field is always `null`, maybe it makes sense to remove the field from the model of `RestorableDroppedDatabase` and update the documentation accordingly? Or am I missing something?

**Comment by ericshape** [comment]
Hi @bosh-ms, Thanks for your feedback!
are you an internal MSFT user? If so, can you raise sev 3 CRI to unblock you from any Azure SQL DB issue? Github issues are not monitored for a long time. 
I will close this issue 'cause it is raised 7 months ago.
