### ISSUE TITLE
VMSS created by specialized image should return proper `OSProfile`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#10166]
When creating a VMSS using a specialized image, `OSProfile` must be `null`. But after VMSS is created, in a response of a GET API, the `OSProfile` is also `null`. This is not so reasonable for instance the user may need to know the admin username, provisionVMAgent, etc. And leaving them empty may give the user misleading information

Related discussion: https://github.com/terraform-providers/terraform-provider-azurerm/pull/7524#pullrequestreview-448692793

**Comment by tombuildsstuff** [comment]
For context: this information not being returned leads to unknowns/false assumptions (for example, the API documentation states that "provisionVMAgent" defaults to "true" but this isn't necessarily correct) and so could lead to an unexpected security issue

Whilst this information doesn't need to be specified during creation - the API should be able to determine this information from the source image, which can be returned - solving this security issue

**Comment by avirishuv** [comment]
@ArcturusZhang - This behavior is by design for specialized images. This documentation provides related information for specialized images and OSProfile: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/shared-image-galleries#generalized-and-specialized-images

**Comment by Drewm3** [comment]
I am closing this issue because is by design as Avi mentioned.
