### ISSUE TITLE
SQL Server list restorable databases and recoverable databases fails

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10162]
I have requests to list restorable and recoverable databases. The resource group and the sql server always exist. Sometimes it returns success, sometimes it returns "resource group not found", sometimes it returns "sql server not found".

Would you mind taking a look?

1. get recoverable databases
Get https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/acctestRG-mssql-yup/providers/Microsoft.Sql/servers/acctestsqlserveryup/recoverableDatabases?api-version=2014-04-01

{
    "error": {
        "code": "ResourceGroupNotFound",
        "message": "Resource group 'acctestRG-mssql-yup' could not be found."
    }
}

2. get restorable databases
Get https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/acctestRG-mssql-yup/providers/Microsoft.Sql/servers/acctestsqlserveryup/restorableDroppedDatabases?api-version=2014-04-01
{
    "error": {
        "code": "ResourceGroupNotFound",
        "message": "Resource group 'acctestRG-mssql-yup' could not be found."
    }
}

**Comment by xccc-msft** [comment]
@yupwei68 I just add label for the issue you are facing. We will need help from sql service team. Thanks.

**Comment by yupwei68** [comment]
And the go sdk raises error: StatusCode=404 -- Original Error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}

**Comment by yupwei68** [comment]
Currently I can reproduce this error only on sql server listing recovery databases. After you have created a sql server, and you list the recovery databases. It shows error: 
```
{
    "code": "40647",
    "message": "Subscription '...' does not have the server 'yupsql3'.",
    "target": null,
    "details": [
        {
            "code": "40647",
            "message": "Subscription '.... does not have the server 'yupsql3'.",
            "target": null,
            "severity": "16"
        }
    ],
    "innererror": []
}
```

**Comment by yupwei68** [comment]
Tilak has helped to investigate the recoverable databases api. It appears it's one feature of the recoverable databases, which get data from the secondary region. Thus, it might takes couple of minutes or couple of hours to synchronize the data to the recoverable databases api.
