### ISSUE TITLE
[Azure Automation] validations (size, range, regexes) on properties and parameters missing

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/azure-rest-api-specs#1020]
Mentioned in PR https://github.com/Azure/azure-rest-api-specs/pull/950
Validations need to be added for user inputs for all Azure Automation resources

Example
        "parameters": [
          {
            "name": "automationAccount",
            "in": "path",
            "required": true,
            "type": "string",
			"minLength": minLength goes here,
			"maxLength": maxLength goes here,
			"pattern": "regex string goes here"
            "description": "The automation account name."
          },
---
[Garrett] You should have some validations (size, range, regexes) on properties and parameters when they are coming from the user.
---

**Comment by andyw248** [comment]
Validation is implemented in the controller. I don't think there's any additional validation required here.
