### ISSUE TITLE
Various Search model properties need to be authored as x-nullable: true

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#10226]
We're finding in the Azure Cognitive Search SDK for .NET that quite a few model properties need to be authored as x-nullable because the service implementation may return them as null.

See https://github.com/Azure/azure-sdk-for-net/blob/80ff0d075221715e3eb8e8645eac2cef203e7c8f/sdk/search/Azure.Search.Documents/src/autorest.md#add-nullable-annotations for a current list. Should we add more, we can open a new issue with the difference. If possible, it would be great if the service team could validate the swagger authoring against the service implementation.

This should be fixed in 2020-06-30 and any current preview being updated.

- [x] SynonymMap
  - [x] encryptionKey
- [x] SearchField
  - [x] indexAnalyzer
  - [x] searchAnalyzer
  - [x] analyzer
- [x] ScoringProfile
  - [x] text
- [x] SearchIndex
  - [x] encryptionKey
  - [x] corsOptions
- [x] BM25Similarity
  - [x] k1
  - [x] b
- [x] SearchIndexerDataSource
  - [x] dataChangeDetectionPolicy
  - [x] dataDeletionDetectionPolicy
- [x] SearchIndexer
  - [x] disabled
  - [x] schedule
  - [x] parameters
- [x] TextTranslationSkill
  - [x] suggestedFrom
- [x] IndexingParameters
  - [x] batchSize
  - [x] maxFailedItems
  - [x] maxFailedItemsPerBatch
- [x] FieldMapping
  - [x] mappingFunction
- [x] IndexerExecutionResult
  - [x] endTime

**Comment by brjohnstmsft** [comment]
Thanks for reporting this @heaths. If I had to guess how we got into this state, it might be because we incorrectly assumed that `x-nullable` is true by default (or at least, treated that way for .NET reference types in C# codegen).

I'll fix all the core Search instances of this. @bleroy, can you please fix the indexer- and skillset-related instances?

**Comment by bleroy** [comment]
@brjohnstmsft Sure.

**Comment by bleroy** [comment]
PR #10245

**Comment by heaths** [comment]
This isn't complete. When referencing in commits, make sure a word separates keywords like "fixed", "resolves", etc. until complete so it doesn't get auto-closed.
