### ISSUE TITLE
cosmo mongodb collection how to get TTL

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10248]
1. We have updated mongodb collection by request:
PUT /subscriptions/.../resourceGroups/acctestRG-cosmos-200724154914252534/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-200724154914252534/mongodbDatabases/acctest-200724154914252534/collections/acctest-200724154914252534?api-version=2020-04-01 HTTP/1.1
{"properties":{"resource":{"id":"acctest-200724154914252534","indexes":[{"key":{"keys":["_ts"]},"options":{"expireAfterSeconds":707}}],"shardKey":{"seven":"Hash"}},"options":{}}}

2. Then we get the mongodb collection by request:
GET /subscriptions/.../resourceGroups/acctestRG-cosmos-200724154914252534/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-200724154914252534/mongodbDatabases/acctest-200724154914252534/collections/acctest-200724154914252534?api-version=2020-04-01 HTTP/1.1

Response:
{"id":"/subscriptions/.../resourceGroups/acctestRG-cosmos-200724154914252534/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-200724154914252534/mongodbDatabases/acctest-200724154914252534/collections/acctest-200724154914252534","type":"Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections","name":"acctest-200724154914252534","properties":{"resource":{"id":"acctest-200724154914252534","_rid":"A1xBAL6n3OM=","_etag":"\"0000d14e-0000-0d00-0000-5f1a95ec0000\"","_ts":1595577836,"shardKey":{"seven":"Hash"},"indexes":[{"key":{"keys":["DocumentDBDefaultIndex"]},"options":{}}]}}}

How do we get TTL by api of getting mongodb collection? Is `AnalyticalStorageTTL` the TTL?
![image](https://user-images.githubusercontent.com/56525716/88372855-4ea86200-cdc9-11ea-8547-87aa6fdda693.png)

**Comment by yupwei68** [comment]
Related to issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/6894

**Comment by MehaKaushik** [comment]
Hey, we noticed this was an issue at the Service side, the fix for the same should be deployed by the end of the month. Thanks for reporting the issue.

**Comment by yupwei68** [comment]
@MehaKaushik Thanks for your response.

**Comment by yupwei68** [comment]
issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7825

**Comment by MehaKaushik** [comment]
Hey, just to update, we are expecting the fix to be deployed sometime this week.

**Comment by yupwei68** [comment]
@MehaKaushik Thanks for notification

**Comment by MehaKaushik** [comment]
Hey, @yupwei68 the fix was deployed last week, please validate that  you are able to see the _ts index now.

**Comment by yupwei68** [comment]
@MehaKaushik Thanks. It works now.
