### ISSUE TITLE
webapp:Setting date in App Service app setting converts date to different format

### ISSUE THREAD

**Issue by bradcavanagh-ffs** [Azure/azure-rest-api-specs#10250]
When using the `az webapp config appsettings set` command to set an App Service app setting to an ISO-8601 date string (YYYY-MM-DDTHH:mm:ssZ), the date string gets converted into a date that loses time zone information and introduces uncertainty into day and month ordering.

## To reproduce:
1) Create App Service.
2) Run the following command: `az webapp config appsettings set --name <app-service-name> --resource-group <resource-group> --settings=BUILD_DATE=2019-12-09T19:42:25Z`

## Observed behaviour:

Output from above command:

```
[
  {
    "name": "BUILD_DATE",
    "slotSetting": false,
    "value": "12/09/2019 19:42:25"
  }
]
```

When observing the app setting via the portal, the date is also in the incorrect format.

## Expected behaviour:

```
[
  {
    "name": "BUILD_DATE",
    "slotSetting": false,
    "value": "2019-12-09T19:42:25Z"
  }
]
```

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.76 *

Extensions:
front-door 1.0.2
storage-preview 0.2.9

```

**Comment by akning-ms** [comment]
Hi @panchagnula , Confirm with @yonzhan, Looks it is not about swagger change. not sure why you transfered to swagger repo. can we change it back azure-cli repo for easy track?

**Comment by raych1** [comment]
As @panchagnula confirmed, this is service API issue.

**Comment by jiasli** [comment]
Why does the bot @azure-sdk replaced https://github.com/Azure/azure-cli/issues/10250 with this issue? Something definitely went wrong.

**Comment by lilyjma** [comment]
Will look into this @jiashou

**Comment by benwarfield-usds** [comment]
Is there an open issue in some repository somewhere that tracks this (still very much live) bug?

**Comment by Shaddix** [comment]
@lilyjma why this got closed?

**Comment by mav10** [comment]
We've met this issue again in 2023
Is there any updates?
