### ISSUE TITLE
Support Forced Tunneling for Azure Firewall in rest api

### ISSUE THREAD

**Issue by lrxtom2** [Azure/azure-rest-api-specs#10257]
[Forced Tunneling](https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling)

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/azureFirewall.json

**Comment by andreycpp** [comment]
@lrxtom2 could you explain what this issue is about?

P.S. Force Tunneling is configured by supplying subnet and Public IP reference via the managementIpConfiguration property of Firewall. There is no property that says "Force Tunneling" as such. Force Tunneling is a concept, not a property name.
