### ISSUE TITLE
Sql Server security altert policy to a storage account behind firewall returns error

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10258]
Issue related to : https://github.com/terraform-providers/terraform-provider-azurerm/issues/7887
I tried to create a sql server security alert policy to a storage account behind firewall, and it returns an internal error, which has blocked our users.

request:
PUT /subscriptions/.../resourceGroups/yupsql/providers/Microsoft.Sql/servers/yupsql/securityAlertPolicies/Default?api-version=2017-03-01-preview HTTP/1.1
{"properties":{"state":"Enabled","emailAddresses":["yup@cc.com"],"storageEndpoint":"https://sqlstr.blob.core.windows.net/","storageAccountAccessKey":"...","retentionDays":180}}

response:
{"name":"9a3ffa00-1ab6-458b-9062-d5928c2e5ad7","status":"Failed","startTime":"2020-07-27T05:26:09.833Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: 'ec3b4bbc-ac1d-4ea4-848c-c99d67778dbf'"}}

**Comment by yupwei68** [comment]
I have tried to assign the sql server in scope storage account 'Storage Blob Data Contributor' as what we do in sql auditing to a storage account behind firewall. It doesn't work either.

**Comment by jmeadowcroft** [comment]
I am also having this issue.

**Comment by ayeletshpigelman** [comment]
Hi,

We don't support enabling threat detection using storage behind firewall. We are working on adding a notification for the user to explain the failure cause in such a case.
We don't recommend enabling Threat Detection using a storage account since all the alerts are visible in the security center dashboard.

**Comment by yupwei68** [comment]
Thanks for your support.
