### ISSUE TITLE
[AppGateway] Poor error message when SSL cert file is bad

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1027]
See: https://github.com/Azure/azure-cli/issues/2462 

The service returns a Server 500 error, resulting in the SDK throwing:
```
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/1ef6f67e-7981-498c-8349-b67109d0fd0f/resourceGroups/cat-e2e-es/providers/Microsoft.Network/applicationGateways/app_gateway?api-version=2016-09-01 (Caused by ResponseError('too many 500 error responses',))
```

The service should validate the certificate and raise an actionable exception when it is invalid.

**Comment by liumichelle** [comment]
@DeepakRajendranMsft to assign to @amitsriva

**Comment by akshaysngupta** [comment]
Looking at log, Client tried multiple times and got internal server error:
https://management.azure.com:443 "PUT /subscriptions/1ef6f67e-7981-498c-8349-b67109d0fd0f/resourceGroups/cat-e2e-es/providers/Microsoft.Network/applicationGateways/app_gateway?api-version=2016-09-01 HTTP/1.1" 500 115
Trying to create/update certificate with a pfx with junk data now gives following error message-
Data or Password for certificate /subscriptions/....../sslCertificates/cert1 is invalid.

**Comment by tjprescott** [comment]
Perfect! Thanks @akshaysngupta !
