### ISSUE TITLE
Data Disk Encryption not Available in Swagger

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#1035]
As mentioned by @AdallomRoy in Azure/azure-sdk-for-go#566, the [current swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L3642) for creating and updating VMs allows for encryption of the OS disk, but not the data disk. As of January 2017, that operation is supported.

Documentation for the new Data Disk encryption functionality can be found here:
https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption
The existing REST Documentation can be found here:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update

**Comment by anuchandy** [comment]
Encryption of a data disks and OS disk are done by installing 'encryption extension' in the VM, so if current swagger supports specifying extension for VM then encryption can be done. Regarding [this section](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L3657), this is something that needs to be updated by the user after the installation of the extension. I found that making encryption work correctly is not straight forward, for more info take a look at https://github.com/Azure/azure-sdk-for-java/pull/1466

**Comment by marstr** [comment]
I'm closing this issue out, because after spending a couple of weeks digging into this, it has become clear that this is not a deficiency with the swagger. The Service Team really does not accept encrypted data disks as they come across the wire here. Rather, the only way to accomplish this is the Azure Disk Encryption Extension that @anuchandy mentions above. As he says, it is not straight forward to get this working.
