### ISSUE TITLE
Add support for PATCH operation for the entities Queue, Topic, Subscription and SharedautorizationRule.

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#1037]
This https://github.com/Azure/azure-rest-api-specs/pull/1036 PR contains PATCH for namespace entity, ARM required this operation to be enabled for all top level resources.

**Comment by jfggdl** [comment]
Thank you for bringing this to our attention. We are acknowledging the request for this feature. We have added it to our backlog and it should be addressed in a future release (date TBD). I am closing this issue, but feel free to reopen it if you have any additional questions about this feature.
