### ISSUE TITLE
Update on the image reference of VMSS erases all the data disks

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#10373]
Original reported: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6286

This issue has already been tracking internally, I just open this issue to let the customers outside MSFT could track the progress.

**Comment by axayjo** [comment]
@avirishuv - this feature request is already being tracked. Assigning this to you to help answer any questions from external customers/users.

**Comment by avirishuv** [comment]
@ArcturusZhang the fix for this issue has been rolled out. If not other open questions, can we close the issue?

**Comment by ArcturusZhang** [comment]
Hi @avirishuv I just had a try of updating SKU, and the data disks are properly retained. Thank you!
