### ISSUE TITLE
Subnet previously used by deleted api management service cannot be deleted

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#10395]
Steps to reproduce

1.	Create a apim service
`{"location":"westeurope","properties":{"certificates":[],"customProperties":{"Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false"},"hostnameConfigurations":[],"publisherEmail":"pub1@email.com","publisherName":"pub1","virtualNetworkType":"None"},"sku":{"name":"Developer","capacity":1},"tags":{}}`
2020/08/10 11:59:51 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/.../resourceGroups/acctestRG-200810115925124829/providers/Microsoft.ApiManagement/service/acctestAM-200810115925124829?api-version=2019-12-01: 
HTTP/2.0 201 Created

2.	Update the apim service with VN Subnet, change to `Internal` virtualNetworkType
PUT /subscriptions/.../resourceGroups/acctestRG-200810120050691536/providers/Microsoft.ApiManagement/service/acctestAM-200810120050691536?api-version=2019-12-01 HTTP/1.1
`{"location":"westeurope","properties":{"certificates":[],"customProperties":{"Microsoft.WindowsAzure.ApiManagement.Gateway.Protocols.Server.Http2":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false"},"hostnameConfigurations":[],"notificationSenderEmail":"apimgmt-noreply@mail.windowsazure.com","publisherEmail":"pub1@email.com","publisherName":"pub1","virtualNetworkConfiguration":{"subnetResourceId":"/subscriptions/.../resourceGroups/acctestRG-200810120050691536/providers/Microsoft.Network/virtualNetworks/acctestVNET-200810120050691536/subnets/acctestSNET-200810120050691536"},**"virtualNetworkType":"Internal"**},"sku":{"name":"Developer","capacity":1},"tags":{}}`

3.	Update the apim service, remove Subnet setting, change to `None` virtualNetworkType
PUT /subscriptions/.../resourceGroups/acctestRG-200810120050691536/providers/Microsoft.ApiManagement/service/acctestAM-200810120050691536?api-version=2019-12-01 HTTP/1.1
`{"location":"westeurope","properties":{"certificates":[],"customProperties":{"Microsoft.WindowsAzure.ApiManagement.Gateway.Protocols.Server.Http2":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Backend.Protocols.Tls11":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10":"false","Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11":"false"},"hostnameConfigurations":[],"notificationSenderEmail":"apimgmt-noreply@mail.windowsazure.com","publisherEmail":"pub1@email.com","publisherName":"pub1","**virtualNetworkType":"None"**},"sku":{"name":"Developer","capacity":1},"tags":{}}`

4.	Delete them all, all has been deleted, except the VN, SN and the resource group. And the SN deletion returns error:  StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet acctestSNET-200810094556761168 is in use by /subscriptions/…/providers/Microsoft.ApiManagement/service?vnetResourceGuid=d1f6670d-d8a4-48e9-9226-94ae9e5dd63e&subnet=acctestSNET-200810094556761168&api-version=2016-07-07 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
2020/08/10 13:52:06 [DEBUG] AzureRM Request: 
DELETE /subscriptions/.../resourceGroups/acctestRG-200810120050691536/providers/Microsoft.ApiManagement/service/acctestAM-200810120050691536?api-version=2019-12-01 HTTP/1.1
{
  "status": "Succeeded"
}

2020/08/10 13:52:08 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/.../providers/Microsoft.Network/locations/westeurope/operations/b8d84514-9520-4617-9ad3-ea2327d6ac7b?api-version=2020-05-01: 

DELETE /subscriptions/.../resourceGroups/acctestRG-200810120050691536/providers/Microsoft.Network/virtualNetworks/acctestVNET-200810120050691536/subnets/acctestSNET-200810120050691536?api-version=2020-05-01 HTTP/1.1
{
  "error": {
    "code": "InUseSubnetCannotBeDeleted",
    "message": "Subnet acctestSNET-200810120050691536 is in use by /subscriptions/.../providers/Microsoft.ApiManagement/service?vnetResourceGuid=a5bc5d2b-a9b3-477b-90bf-7dc2146149b8&subnet=acctestSNET-200810120050691536&api-version=2016-07-07 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.",
    "details": []
  }
}
5.	On portal, we could not delete the SN either 
![image](https://user-images.githubusercontent.com/56525716/89755666-c806bb00-db12-11ea-9cb1-ddfe217aa915.png)

**Comment by solankisamir** [comment]
The scenario where we move the service out of Virtual Network does not remove the link to subnet immediately.
This is to avoid downtime for customer Apps, as the DNS refresh can take some time. When the service is moved out of the Virtual network, the IP Address changes. For more details refer [here](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-ip-addresses#changes-to-the-ip-addresses)

On Update, the link is removed within 3 hours. In this case, the Link was removed at 2020-08-10 08:01 UTC. The service was moved out of VNET at 2020-08-10 05:50 UTC.

This is BY DESIGN!
