### ISSUE TITLE
[Monitor] Make the name attribute in AutoscaleSetting optional since it is already in the request

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-rest-api-specs#1043]

**Comment by gucalder** [comment]
This issue is already done, name attribute in AutoscaleSetting is already optional in the spec and the backend.

**Comment by kirthik** [comment]
@gucalder  - Could you please provide the commit link here? I can close it then.

**Comment by gucalder** [comment]
I think the change was done before the folders were reorganized into data-plane and resource-manager. I cannot find any reference in the history about the change, but the spec if like this:

    "AutoscaleSetting": {
      "required":[
        "profiles"
      ],

Name is not a required property.
