### ISSUE TITLE
Please reopen #8435

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#10459]
As mentioned in the issue - this is not a breaking change - this value is supported by the service but is missing from the Swagger, ergo the Swagger does not correctly represent the service behaviour

cc @JeffreyRichter - this is an example like we discussed yesterday

**Comment by yungezz** [comment]
hi @tombuildsstuff do you mean this PR https://github.com/Azure/azure-rest-api-specs/pull/8435? add original assignee @lirenhe .

**Comment by lirenhe** [comment]
I reopened this PR. @tombuildsstuff, could resolve the conflict for your original PR?

**Comment by lirenhe** [comment]
Reopened. Please use #8435 for discussion.
Close this item.
