### ISSUE TITLE
azure key vault secret should set a limit for expiration date

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-rest-api-specs#10473]
Currently, we could set the expiration date to a far future date, such as "9999-12-31T00:00:00Z".  however, it does not make sense. 

particularly with secret/sensitive values, it's recommended to have a short-lifetime.

So could the backend service add a limitation for the expiration date？

**Comment by sebansal** [comment]
It is by design to not restrict customer's use case. It will allow you to create short lived secrets.

**Comment by tombuildsstuff** [comment]
@sebansal if the API is going to allow resources with an expiry date in ~8000 years time, is that a guarantee the service will be available? If not that seems misleading that the API allows this data?

The [original issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8056#issuecomment-673427503) proposed a maximum expiry-date, which could always be updated at a later date - but it seems optimistic to assume that the Key Vault Service will be still be still serving requests in 100 years, let alone 8000.

If the API wishes to support secrets with an indefinite lifetime shouldn't the API instead allow the ExpiryDate to be `null` as per other Azure API's?

**Comment by tombuildsstuff** [comment]
ping @sebansal

**Comment by jlichwa** [comment]
@tombuildsstuff if you don't provide expiration date it is infinite (this field is optional), so providing any limits to it does not have sense at this point. It will also be breaking change. There are customers who are using it as configuration store, for let's say service name.

**Comment by tombuildsstuff** [comment]
@jlichwa which comes back to the original point, if this field can be null - surely there should be sane validation value for the EndDate (e.g. 10 years, 100 years)? It seems optimistic to allow this to be set ~8000 years in the future, given the rate of churn in technology.

Whilst this may sound like a hypothetical scenario - the issue for client libraries is it's possible for them to overflow during parsing these dates (as [seen in this issue with the Azure SDK](https://github.com/Azure/go-autorest/issues/549)) - meaning the date `9999-12-31T00:00:00Z` gets parsed as `1816-03-29T05:56:08Z` - which leads to diff's on our side: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8056 (and whilst we've found this issue, other clients may not be aware)

---

With regards to if this is a breaking change or not, that's very much down to the implementation - it's unfortunate the Key Vault Data Plane API is unversioned - but future versions of the Key Vault API could transform dates over (say) 100 years from now (for new/when updating existing secrets) to `null` - assuming these are indefinite instead?

**Comment by jlichwa** [comment]
@tombuildsstuff if it can be indefinite, why not 100 years and if we do 100, why not 101? It can be considered as an issue, but it is really low priority and it would require to change on REST API and all SDKs and potentially break a lot of current customers code which could set it to 1000 years or 9999 for whatever reason. So it is something which would require updates across all clients. We will consider the update in next planning for upcoming year.
