### ISSUE TITLE
FOG updates/deletes don't get propagated to secondoary server

### ISSUE THREAD

**Issue by erniebilling** [Azure/azure-rest-api-specs#10511]
Related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/8040 and https://github.com/terraform-providers/terraform-provider-azurerm/issues/7938

When https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2015-05-01-preview/failoverGroups.json#L19 is used to update the sku on a failover group (according to the azure terraform provider authors) the sku on the primary database is updated, but the sku on the database is not.

Also, when a failover group is deleted, the secondary database is not deleted, even though the secondary database is automatically created when the failover group is created on a primary server/database.

See the related issues for steps to repro and actual and expected results.

**Comment by NullMDR** [comment]
@ArcturusZhang for help

**Comment by BustosMSFT** [comment]
Hi @erniebilling these are by design, but we'll take into consideration the suggestions.
Regards
#please-close

**Comment by BustosMSFT** [comment]
#please-close
