### ISSUE TITLE
Common-Types v2 ErrorResponse confusion

### ISSUE THREAD

**Issue by jviau** [Azure/azure-rest-api-specs#10558]
I am looking at the v2 definition for `ErrorResponse` [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v2/types.json#L272) and I think the `details` property may be incorrect? It points back to itself, but when I look at all examples - `CloudError` and its json converter, and the new Azure management SDKs, the nested `details` object should be the flattened form (ie: `ErrorResponseError`), and not the `ErrorResponse`.

Expected format:
```json
{
  "error": {
    "code": "ErrorCode",
    "message": "error message",
    "details":
    [
      {
        "code": "SubCode",
        "message": "sub message"
      }  
    ]
  }
}
```

v2 format:
```json
{
  "error": {
    "code": "ErrorCode",
    "message": "error message",
    "details":
    [
      {
        "error": { <-- issue
          "code": "SubCode",
          "message": "sub message"
        }
      }  
    ]
  }
}
```

The difference being that extra `"error"` level in the `"details"` object. If you look at [Azure.ResourceManager.Compute.Models.CloudError](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/CloudError.cs) and [Azure.ResourceManager.Compute.Models.ApiError](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/ApiError.cs) you can see it follows the expected format I listed above.

**Comment by ruowan** [comment]
Hi, Could you give some examples about CloudError swagger example? Because [v1 ](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L272) and v2 have the similar definition. So does this issue related to SDK generation?

**Comment by jviau** [comment]
The [CloudError](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/CommonModels/CloudError.cs) type used in the existing management SDKs represents the structure from v1. However, it has a [custom JSON converter](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/CloudErrorJsonConverter.cs) which will read it from a nested `"error"` property, mean its expected JSON format lines up with the expected format I showed in this issue, and **not** with the format from v2.

**Comment by akning-ms** [comment]
v2 add error as top property name to comply ARM guideline.
latest is like below which should not have extra error in sub error
    "ErrorResponse": {
      "title": "Error response",
      "description": "Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).",
      "properties": {
        "error": {
          "description": "The error object.",
          "$ref": "#/definitions/ErrorDetail"
        }
      }
    },
