### ISSUE TITLE
OpenAPI specs for Microsoft.Automation do not match information returned by /providers API

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-rest-api-specs#10662]
Based on the information returned by the AZ CLI (`az providers list`), resource provider `Microsoft.Automation` should expose resource type `automationAccounts` with the following API versions:
- 2020-01-13-preview
- 2019-06-01
- 2018-06-30
- 2018-01-15
- 2017-05-15-preview
- 2015-10-31
- 2015-01-01-preview

The OpenAPI specs only defines resource type `automationAccounts` with the API version `2015-10-31`

As a result, the auto-generated ARM template schema does not include the correct API versions and there is a conflict between the warnings reported by the `arm-ttk` and VS Code's ARM template schema validation ... as reported here Azure/arm-ttk#184

The OpenAPI spec definition is also not up to date for resource types:
- `automationAccounts/configurations`
- `automationAccounts/webhooks`
- `automationAccounts/softwareUpdateConfigurations`
- `automationAccounts/jobs`

**Comment by msvijayn** [comment]
Assigning to @vikram-m for addressing OpenAPI compliance across Microsoft.Automation RP

**Comment by jaspkaur28** [comment]
We've got this triaged and added it to the Automation backlog. We plan to pick this up towards end of Q4 CY20 , if resourcing allows.

**Comment by jaspkaur28** [comment]
We plan to pick this up in CY21-Q1. Already tracked internally . 
Closing the thread.
