### ISSUE TITLE
Log Analytics - ignores casing

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#10689]
I'm running into an issue where the names in the id of any Log Analytics resources ignores the casing of what I requested

For example, I send the following:
/subscriptions/0000-0000-00000/resourcegroups/thisIsMyResourceGroup/providers/Microsoft.OperationalInsights/workspaces/WorkSpace1/...

And then I receive the following:
/subscriptions/0000-0000-00000/resourcegroups/thisismyresourcegroup/providers/Microsoft.OperationalInsights/workspaces/workspace1/...

**Comment by shemers** [comment]
Hi @mbfrahry,
Thanks for reaching out on this issue, 
May I ask for more details? 
What is the operation that you are trying to run?
From the issue details, it actually seems not to be Log Analytics specific issue, rather Azure Resource Manager issue.
Please review [this article](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) "Resource names are case-insensitive unless specifically noted in the valid characters column."

Looking forward to get your feedback.
