### ISSUE TITLE
Rename KeyReleaseConditionCondition

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#10696]
https://github.com/Azure/azure-rest-api-specs/blob/9c65009b45ad8a23625aab711eb78d15c0371c1d/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/keys.json#L1053

This will cause some issues in some of our generators (e.g. Go) that will cause conflicts. Could this be renamed to something like `KeyReleaseClaimCondition` intead?

/cc @herveyw

**Comment by vickm** [comment]
We are investigating this now. @vasanthrajams can you check with @herveyw ? I think this may be a OneApi-only change and would require no server side changes

**Comment by vasanthrajams** [comment]
We already have made the required changes for marking LRO  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/backuprestore.json

Verified this with heaths.

**Comment by Lusitanian** [comment]
@heaths  this is closed out in https://github.com/Azure/azure-rest-api-specs/pull/10916 - is anything blocking merge of that PR?

**Comment by heaths** [comment]
We're discussing if this is the right change. It should be merged soon. For now, please don't work on secure key release until that is merged.

**Comment by sebansal** [comment]
Hi @heaths 
I was triaging this list, can you share if it has been resolved and can be closed? 
Thanks

**Comment by heaths** [comment]
I'm not driving this change. Please ask @herveyw-msft or @Lusitanian. I believe, however, that this is no longer relevant as the models have been flattened to a simple model that takes an optional content type and arbitrary blob.

**Comment by Lusitanian** [comment]
This issue is no longer relevant, for the reasons @heaths stated. Closing it out.
