### ISSUE TITLE
KeyVault swagger file needs to be updated with secret backup permissions.

### ISSUE THREAD

**Issue by RandalliLama** [Azure/azure-rest-api-specs#1069]
Azure/azure-cli#2587

Some keyvault SDKs choke on the new secret backup and restore permission as it does not appear in the swagger file.

**Comment by schaabs** [comment]
This permission is already in the swagger def https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L310.  The linked issue appears to be due to an out of date version of the azure-cli.
