### ISSUE TITLE
Change Error Output for Microsoft.Compute/galleries/images/versions

### ISSUE THREAD

**Issue by jontreynes** [Azure/azure-rest-api-specs#10707]
I see here that the schema for naming on the version requires digits that are 32 bit integers

https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-03-01/galleries/images/versions?source=docs#microsoftcomputegalleriesimagesversions-object

2 suggestions:
The portal input parameter should check if the version abides by the 32 bit integer requirement
The REST response currently says
_{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidParameter\",\r\n \"message\": \"The image version name is invalid. The image version name should follow Major(int).Minor(int).Patch(int) format, for e.g: 1.0.0, 2018.12.1 etc.\",\r\n \"target\": \"galleryImageVersionName\"\r\n }\r\n}"}]}_

The message should also say "...follow Major(int).Minor(int).Patch(int) format, where int is a 32 bit integer"

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
Assigned to Akshay.

**Comment by axayjo** [comment]
Looking into this.

**Comment by axayjo** [comment]
We'll fix the error output to indicate the type of int. Tracking this as a bug.

**Comment by olayemio** [comment]
We are working on making the bug fix and should be reflected in the API by second week of February

**Comment by olayemio** [comment]
The API now shows the following error message: "The version name should follow Major(int).Minor(int).Patch(int) format, where int is between 0 and 2,147,483,647 (inclusive)"

We are working with the Portal team on the portal input parameter to highlight when a customer enters a value outside the range. Current ETA to accomplish this is end of March.

**Comment by olayemio** [comment]
The portal now checks and shows if the integer is outside the allowable range.
