### ISSUE TITLE
MS Sql database API doesn't return LicenseType value

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#10715]
After tested, I found ms sql database api doesn't return LicenseType value. BTW, I am using [go sdk client](https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/sql/mgmt/v3.0/sql).

Http request:
```
PUT https://management.azure.com/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-mssql-test03/providers/Microsoft.Sql/servers/acctest-sqlserver-test03/databases/acctest-db-test03

{
	"location": "eastus2",
	"properties": {
		"collation": "SQL_Latin1_General_CP1_CI_AS",
		"maxSizeBytes": 1073741824,
		"elasticPoolId": "",
		"zoneRedundant": false,
		"licenseType": "LicenseIncluded",
		"readScale": "Disabled",
		"readReplicaCount": 0,
		"autoPauseDelay": 0,
		"minCapacity": 0
	},
	"sku": {
		"name": "Basic"
	},
	"tags": {}
}
```

API doesn't return LicenseType value:
![image](https://user-images.githubusercontent.com/19754191/92359741-55432c80-f11e-11ea-991c-66ce758e87a5.png)

**Comment by ericshape** [comment]
@neil-yechenwei 
thanks for the feedback! 
I have fixed this issue in Azure SQL DB internal codebase in September 2020. It should be deployed. Please try again to see whether it works! if it cannot work, please reopen this issue and tag me. I will debug and resolve it. 
Thanks!
