### ISSUE TITLE
[Compute] Dedicated host group, platformFaultDomainCount maximum value

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-rest-api-specs#10714]
https://github.com/Azure/azure-cli/issues/15054
A customer said the maximum value should be relaxed.
> Host group creation with FDCount =5 is a supported scenario for zonla host group (created within an availability zone).

azure-rest-api-specs\specification\compute\resource-manager\Microsoft.Compute\stable\2020-06-01\compute.json
```
    "DedicatedHostGroupProperties": {
      "properties": {
        "platformFaultDomainCount": {
          "type": "integer",
          "format": "int32",
          "minimum": 1,
          "maximum": 3,
          "description": "Number of fault domains that the host group can span."
        },
```

**Comment by amjads1** [comment]
Looking into this issue.

**Comment by amjads1** [comment]
Assigned to Ziv.

**Comment by Drewm3** [comment]
This has been confirmed to be a bug. The correct values of 1-5 will be published in the next version update for the API. The currently released version cannot be updated without causing a breaking change.

**Comment by qwordy** [comment]
It is fixed. Swagger and service is updated now.
https://github.com/Azure/azure-cli/pull/15316
