### ISSUE TITLE
KeyVault: No compatible signing algorithm for curve SECP256K1

### ISSUE THREAD

**Issue by vdamle** [Azure/azure-rest-api-specs#10769]
### Bug Report

- import path:
```
github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault
```
- SDK version e.g. `master`, `latest`, `18.1.0`
```
github.com/Azure/azure-sdk-for-go  v39.0.0+incompatible
```
- output of `go version`
```
go version go1.13.4 darwin/amd64
```

## Problem Description

* `azure-sdk-for-go` does not support a compatible `JSONWebKeySignatureAlgorithm` for key created with curve `SECP256K1`, using the Azure KeyVault Portal.

```
 error: keyvault.BaseClient#Sign: Failure responding to request: StatusCode=400
-- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" 
Message="Key and signing algorithm are incompatible. Key https://foo.vault.azure.net/keys/key-4/973daeb9df5848638c0238be5bd94d37 uses curve 'SECP256K1', and algorithm 'ES256K' can only be used with curve 'P-256K'."
```

* It appears that signing using `azure-sdk-for-go` can only work if the key was also created using the SDK, because the `JSONWebKeyCurveName` in the SDK which corresponds to `SECP256K1` is `P256K` - https://github.com/Azure/azure-sdk-for-go/blob/0aac01c260f21d958b4cf0b67e7dd231212e7a56/services/keyvault/v7.0/keyvault/models.go#L73-L74

* But the option `P256K` is not supported when creating a key in Azure KeyVault Portal. For KeyType `EC`, the possible options are `{ P256, P384, P521, SECP256K1 }`

See https://github.com/Azure/azure-sdk-for-node/issues/4603 for support in corresponding `azure-sdk-for-node`

- What did you expect or want to happen?

Allow signing via SDK API for a key of type `SECP256K1` created in Azure KeyVault portal. Alternatively, the portal should be updated with the curve name `P-256K` since all Azure SDKs expect that as the key type.

**Comment by sebansal** [comment]
@vickm Can you have your team to triage this issue?

**Comment by vdamle** [comment]
> Can you share more business context

**Comment by sebansal** [comment]
Hi @vdamle 

In the portal, the secp256k1 was incorrectly named and it has been fixed in the portal now
![image](https://user-images.githubusercontent.com/62565144/94979236-76f1c280-04d6-11eb-9b67-e8a9d1131a22.png)
