### ISSUE TITLE
KeyReleasePolicy is missing a description (and other swagger issues)

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#10800]
The KeyReleasePolicy, KeyReleaseAuthority, and KeyRelease conditions do not have a description. It's also unclear if `KeyReleasePolicy.anyOf` or `KeyReleaseAuthority.allOf` requires values. You can use `minLength` to indicate this. By default, `x-nullable` is `false`, to that implies these properties must exist, but as authored they can be empty.

I also recommend adding `x-ms-client-name` to `KeyReleasePolicy.anyOf` of `authorities` and to `KeyReleaseAuthority.allOf` of `conditions` since that's what they actually represent.

And is `KeyReleaseAuthority.authorityURL` required? It's `minLength` is 1, but that still doesn't mean it's required. Required, nullable, and non-empty are all separate in OpenAPI. Any properties that are required should be listed in the `required` array property of the type definition.

Also, is this a type or name? I recommend an `x-ms-client-name` of "name":
```json
        "claim": {
          "x-ms-client-name": "claimType",
          "type": "string",
          "minLength": 1,
          "description": "claim type name"
        },
```

If this is a type, what values can a user supply? And, again, is it required? This an other properties, if required, need to be listed in the `required` swagger definition property.

Is the `version` parameter required in the "export" method? The description merely reads,
>         "description": "Adding the version parameter retrieves a specific version of a key."

Other version parameter descriptions are explicit that it's optional, despite the parameter being authored as `required`. I should assume it is, because otherwise the canonical path without a version becomes "/keys/{key-name}/export" (previous tests against Key Vault show that consecutive slashes are normalized to a single slash).

**Comment by vickm** [comment]
@jlichwa would you please assign this to @Lusitanian ? I still can't modify or assign issues.

**Comment by Lusitanian** [comment]
Please see https://github.com/Azure/azure-rest-api-specs/pull/10916
