### ISSUE TITLE
[Key Vault] Get the current key vault object version

### ISSUE THREAD

**Issue by aramase** [Azure/azure-rest-api-specs#10825]
There is currently no version filed in the json metadata returned for `az keyvault secret show`. The only way to retrieve the version is by parsing the id. It would be good to have key vault return the the current version of the secret/key/certificate in a separate field which can be surfaced by the SDKs. 

**Alternative**

This could also be accomplished at the SDK level by parsing the id and splitting to get the version, but that would be based on an assumption that the id format will always be the same. Instead relying on a version field returned by Key Vault will be more deterministic and can be used by all the consumers.

**Notes**

Current parsing logic in the clients -
```golang
func getObjectVersion(id string) string {
	splitID := strings.Split(id, "/")
	return splitID[len(splitID)-1]
```

**Comment by sebansal** [comment]
We identify this as a feature request and would be putting product backlog @aramase

**Comment by jlichwa** [comment]
Secret id (with version) it is standardized format (required by REST API) and used by 200+ partners.
Also all our SDKs have specific field for version without need for parsing:

https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretproperties.version?view=azure-dotnet#azure-security-keyvault-secrets-secretproperties-version
