### ISSUE TITLE
[Swagger validation] CI script runs validation on json files that are not swagger specs

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#1084]
Some services would like to separate definitions of models in additional files, and then refer to those from the swagger file. CI is currently running on these definition files, applying the rules, model and semantic validation and reporting the failures.
I believe we want this type of "definition" files to exist, if so, our CI script should not run for those files. I'd expect the content of the files to be validated, if the definitions are referenced from a swagger spec, since validation should follow the reference.

**Comment by akning-ms** [comment]
this should already fixed in latest CI pipeline
