### ISSUE TITLE
GetNetworkRuleSet API should return subnet id with camel case 

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#10855]
After tested, I found the subnet id which is returned by [GetNetworkRuleSet](https://github.com/Azure/azure-rest-api-specs/blob/0585f3ed2ee1b3fa6b38bf6751b61117222c0b01/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/networkrulessets-preview.json#L96) API is lower case. I think it should be camel case per api doc. It should reutrn `/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-test01/providers/Microsoft.Network/virtualNetworks/acctvn2-test02/subnets/acctsub2-test02` not `/subscriptions/xx-xx-xx-xx/resourcegroups/acctestrg-test02/providers/Microsoft.Network/virtualNetworks/acctvn2-test02/subnets/acctsub2-test02`. BTW, I am using azure go sdk as client.

**Comment by Saglodha** [comment]
@neil-yechenwei , I reviewed the functionality and could notice that we have been returning camel case as the resource ID with latest api-version. Could you please confirm if you're still facing this issue?
