### ISSUE TITLE
Search: Some Swagger specs are not linter-compliant or complete

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-rest-api-specs#1085]
## Summary

Currently Azure Search has three Swagger specs per API version:

- **arm-search/.../search.json**: This is the spec for the Azure Search Management REST API (a.k.a. -- control plane), exposed through ARM.
- **search/.../searchservice.json**: This is one of the specs for the Azure Search Service REST API (a.k.a. -- data plane), exposed as a distinct endpoint with its own DNS name for each Search service provisioned by a customer via the control plane. This spec covers the top-level resources, all of which have model types that are fully known at design-time (i.e. -- they are part of the API and do not vary per customer).
- **search/../searchindex.json**: This is the other spec for the Azure Search data plane. It covers the `docs` resource that exists for every (customer-defined) search index.

The intent of this issue is to capture and track all known issues with these specs, as of the following API versions:
- *Control plane*: 2015-08-19
- *Data plane*: 2016-09-01-Preview

## Issues with search.json

1. Currently the spec uses the standard Swagger `examples` property instead of `x-ms-examples`. This needs to be changed the next time we touch this spec.
1. The last time we ran this spec against the linter was in November 2016. Likely the rules have changed since then, so we will need to re-run the linter and address any errors or warnings.

## Issues with searchservice.json

We need to:
1. Add `x-ms-examples` to all operations.
1. Add descriptions to all operation responses.
1. Add a `default` response to all operations.
1. Re-run the linter and address any remaining errors or warnings.

## Issues with searchindex.json

Same as the issues for `searchservice.json`, plus:

1. Most of the API surface of the `docs` resource is not captured in this Swagger spec. This is because we haven't yet done the engineering work to figure out how to get AutoRest to generate acceptable code for the dynamically-typed data plane part of our API (something the old Hyak generator wasn't designed to do). This is a non-trivial amount of work for us, and is currently on hold pending higher business priorities.

**Comment by brjohnstmsft** [comment]
FYI @vishrutshah

At this time we have no ETA for the above changes.

**Comment by brjohnstmsft** [comment]
Update: The issues mentioned above for the management plane (search.json) have been resolved. The issues with the data plane specs remain.

**Comment by brjohnstmsft** [comment]
Update: All issues around validation and examples have been addressed. However, `searchindex.json` is still incomplete. We are currently working on this. I'm re-assigning this issue to @mhko since he is working on this.

**Comment by brjohnstmsft** [comment]
Update: `searchindex.json` now completely covers the Azure Search data plane for versions 2017-11-11-Preview and 2019-05-06. Keeping this open as we still need to fill in some descriptions for responses and fix some validation issues.

**Comment by akning-ms** [comment]
Hi @brjohnstmsft can we close this issue now?

**Comment by brjohnstmsft** [comment]
@akning-ms Yes, the specs are now complete.
