### ISSUE TITLE
Whether Service Bus Subscription API has deprecated deadLetteringOnFilterEvaluationExceptions property or not

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#10857]
Hi,
Seems many documents in lots of community forms are talking about whether the `deadLetteringOnFilterEvaluationExceptions` property is deprecated and many sdk clients have removed this property from their client code. Despite this, but seems this property is still available in [azure rest api spec](https://github.com/Azure/azure-rest-api-specs/blob/9ab0b5d07464e0235fb66832c24f31f1602f21b7/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2017-04-01/servicebus.json#L3991). So I am confused. May I ask is this property deprecated? If it’s deprecated, is there any other property to replace it?

**Comment by xccc-msft** [comment]
@neil-yechenwei Thanks for reporting this. Routing this question to service bus team.

**Comment by OskarKlintrot** [comment]
@xseeseesee How did it go?

**Comment by EldertGrootenboer** [comment]
This has not been deprecated, and is still supported, f.e. see [here](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.createsubscriptionoptions.enabledeadletteringonfilterevaluationexceptions?view=azure-dotnet).
