### ISSUE TITLE
LintDiff Failure: duplicate x-ms-enum name "operatorType"

### ISSUE THREAD

**Issue by paornela** [Azure/azure-rest-api-specs#10898]
The swaggers do not pass LintDiff validation, because of this error: _Must not have duplicate name of x-ms-enum extension , make sure every x-ms-enum name unique. The duplicate x-ms-enum name is operatortype._

Here are the duplicate values:

https://github.com/Azure/azure-rest-api-specs/blob/39466d240538fb7d679e23b180b79d6e9ed80627/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L2726

https://github.com/Azure/azure-rest-api-specs/blob/39466d240538fb7d679e23b180b79d6e9ed80627/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1722

Submitting an issue so that this will get routed to the appropriate person.

**Comment by ramaganesan-rg** [comment]
Team is investigating. For this issue, the swagger needs to be updated.

**Comment by jochav** [comment]
Swagger update is in process. ETA is Jan 2021.
