### ISSUE TITLE
Generate VPN Client Package

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1093]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2017-03-01/swagger/virtualNetworkGateway.json#L262

According to the Swagger, this should return the URL to a client VPN package. However, at least in Python, the autorest generated SDK call simply returns an array of four bytes. It has been suggested that this entry is missing "x-ms-long-running-operation" metadata.

**Comment by tjprescott** [comment]
cc/ @lmazuel fyi

**Comment by salameer** [comment]
@DeepakRajendranMsft  Kindly take a look or assign it to the right owner to review

**Comment by DeepakRajendranMsft** [comment]
@Nilambari

**Comment by liumichelle** [comment]
@DeepakRajendranMsft to assign to @amitsriva or @Nilambari @lamchester

**Comment by liumichelle** [comment]
The fix for this should be in https://github.com/Azure/azure-rest-api-specs/pull/1336 - contact @ritwikbasu to follow up

@salameer can this be closed out?

**Comment by Nilambari** [comment]
This issue has already been fixed in 2017-06-01 swagger.
