### ISSUE TITLE
Virtual Machine Scale Set - enum should have default values

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#10971]
Original reported: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8454

The [`priority`](https://github.com/Azure/azure-rest-api-specs/blob/5b8e4157c807c8874edc850079751ac83b5e2de0/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L8598) in virtual machine scale set resource is an enum, but this resource is not returned when not specified and default value is not specified in the swagger which is confusing for the customers.

**Comment by axayjo** [comment]
@avirishuv can you take a look at this issue?

**Comment by avirishuv** [comment]
@ArcturusZhang could you please clarify that when is the 'priority' property not returned - during a Get vmss call, or something else ? Any steps you can share and expected behavior will be helpful.

**Comment by ArcturusZhang** [comment]
You could try the config in the original issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8454
It is using terraform but it is quite straightforward to convert it to REST API call. The key is no `priority` set in the request, and thus no priority in the response.

**Comment by avirishuv** [comment]
@ArcturusZhang the default value of 'priority' is Regular. Once the VMSS is created, the value of priority cannot be changed. 
Also, if priority is not specified during the creation, then its value is not returned, because returning would break the get-put semantics.

**Comment by avirishuv** [comment]
hi @ArcturusZhang do you have any other questions on this topic? If not, should we close the issue?

**Comment by ArcturusZhang** [comment]
Well, I do not have more questions and your answer sounds reasonable. We might need find some workaround for the issues in terraform. Thanks @avirishuv
