### ISSUE TITLE
Monitor Metric Alert API would return 404 while creating multiple Monitor Metric Alerts in parallel

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#10973]
After tested, Monitor Metric Alert API would return 404 while creating multiple Monitor Metric Alerts and get each resource immediately once it's created successfully in parallel. BTW, I am using the azure go sdk as client.

**Comment by yashmuel** [comment]
> After tested, Monitor Metric Alert API would return 404 while creating multiple Monitor Metric Alerts and get each resource immediately once it's created successfully in parallel. BTW, I am using the azure go sdk as client.

Can you provide more details on this issue? steps to reproduce?
my alias is yashmuel, you can also try me on teams. thanks!

**Comment by yashmuel** [comment]
> After tested, Monitor Metric Alert API would return 404 while creating multiple Monitor Metric Alerts and get each resource immediately once it's created successfully in parallel. BTW, I am using the azure go sdk as client.

@neil-yechenwei  Can you provide more details on this issue? steps to reproduce?
my alias is yashmuel, you can also try me on teams. thanks!

**Comment by neil-yechenwei** [comment]
Thanks yashmuel. After verified, seems the issue has been fixed. So I intend to close this task. If the issue occurs again, I will reopen it.
