### ISSUE TITLE
Cosmos DB - Database - Options shouldn't be required

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#11082]
The [options](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L6379) property in `SqlResources_CreateUpdateSqlDatabase` is marked as required, even though none of its sub-properties is required. @markjbrown [confirmed](https://github.com/pulumi/pulumi-azure-nextgen/issues/26#issuecomment-700756367) that this is a mistake, so I'm opening this issue to track.

**Comment by markjbrown** [comment]
Thanks @mikhailshilkov, I talked to @MehaKaushik last week and she is taking a look at this.

btw, why is @anfeldma-ms getting added to new issues on this repo? I see him getting added by the bot here and also in the az cli repo too. Who manages that bot?  --thanks.

**Comment by MehaKaushik** [comment]
I am hoping to include this change in the upcoming apiVersion.

**Comment by MehaKaushik** [comment]
This change was made in apiVersion 2020-09-01
