### ISSUE TITLE
Storage Share Directory can not delete the resource when it's not empty

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11161]
Related to customer issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/7834

storage api version: 2018-11-09

**Comment by blueww** [comment]
@yupwei68 
Would you please give the the network trace of the issue?
I see the request ID, but it's too longtime ago, can't find the log now.

From the error, it looks like try to delete a not empty File directory, and this is not allowed.
See https://docs.microsoft.com/en-us/rest/api/storageservices/delete-directory:
> Attempting to delete directories that are not empty will fail with status code 409 (DirectoryNotEmpty).

If you try to delete a share, please make sure the request Uri looks like "https://myaccount.file.core.windows.net/myshare?restype=share"

**Comment by blueww** [comment]
@raych1 This is for dataplane. Please add "Client" tag to dataplane issue to differ it from SRP issue.

**Comment by raych1** [comment]
> @raych1 This is for dataplane. Please add "Client" tag to dataplane issue to differ it from SRP issue.

Thanks @blueww for the information. I will add it in the future case.
