### ISSUE TITLE
Storage Object Replication Policy could not be deleted 

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11181]
1. delete a policy:
delete https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/yupstr/providers/Microsoft.Storage/storageAccounts/yupdst/objectReplicationPolicies/c9b56c58-a0e1-424d-8590-fc71aebac5ff?api-version=2019-06-01

204 No Content(because it has been deleted for several times)

2. list polices:
get https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/yupstr/providers/Microsoft.Storage/storageAccounts/yupstr/objectReplicationPolicies?api-version=2019-06-01
{
    "value": [
        {
            "properties": {
                "policyId": "c9b56c58-a0e1-424d-8590-fc71aebac5ff",
                "sourceAccount": "yupstr",
                "destinationAccount": "yupdst",
                "rules": [
                    {
                        "ruleId": "8202e33c-0321-4811-aec7-fcf7a06b11b3",
                        "sourceContainer": "yupc",
                        "destinationContainer": "yupd",
                        "filters": {
                            "minCreationTime": "1601-01-01T00:00:00Z"
                        }
                    }
                ]
            }
        }
    ]
}

**Comment by xccc-msft** [comment]
Thanks for reporting this. Routing to Storage service team. Thanks.

**Comment by blueww** [comment]
@yupwei68

As we discussed in mail:
From server side, the rules in source and destination account are stored separately, so you need to delete both of them.
Delete source account policy/rule, won’t delete the policy/rule on dest account, and vise verse.

So once we create a policy from source account to a destination account, we need to delete the policy in both sides.

**Comment by yupwei68** [comment]
THanks
