### ISSUE TITLE
Storage Encrption Scope Internal Error

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11188]
I've tried to create a "keyVault" encryption scope, but it returns an internal error.

I've granted the access policy of "get","list","wrapkey,"unwrapkey" to the storage account

PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/yupstr/providers/Microsoft.Storage/storageAccounts/yupstr/encryptionScopes/enscope4?api-version=2019-06-01&monitor=true

{
    "properties": {
        "source": "Microsoft.KeyVault",
        "keyVaultProperties": {
          "keyUri": "https://yupstrkv.vault.azure.net/keys/key/..."
        }
      }
}

Response:

Date : Wed, 14 Oct 2020 07:42:25 GMT

{
    "error": {
        "code": "InternalServerError",
        "message": "Internal server error."
    }
}

**Comment by xccc-msft** [comment]
Thanks for reporting this. Routing to Storage service team. Thanks.

**Comment by blueww** [comment]
@tonykjose 
Would you please help to look at the Encryption Scope "InternalServerError"?
