### ISSUE TITLE
Storage Object Replication Policy can not be recreated

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11189]
I've deleted the policy for the source storage account side and the destination storage account side.
I've listed the policies to check that there is no policy in both accounts.

Then I recreate the policy with a new uuid policy id.
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/yupstr/providers/Microsoft.Storage/storageAccounts/yupstr/objectReplicationPolicies/8173ea1f-2ff8-4970-909f-878e0953475b?api-version=2019-06-01
{
    "properties": {
        "sourceAccount": "yupstr",
        "destinationAccount": "yupdst",
        "rules": [
            {
                "ruleId": "f321ad87-b575-4894-bbff-b221f35820c7",
                "sourceContainer": "yupc",
                "destinationContainer": "yupd",
                "filters": {}
            }
        ]
    }
}

Response:
Wed, 14 Oct 2020 05:04:15 GMT
{
    "error": {
        "code": "ServiceUnavailable",
        "message": "The service is unavailable now. Please retry the request later."
    }
}

**Comment by blueww** [comment]
@zfchen95 
Would you please help to look? 
This looks like a server issue.

**Comment by yupwei68** [comment]
Thanks @blueww @zfchen95 . @zfchen95 has replied me that the policy need to be created first on destination account with name "default", then create it on source account side. So as update and delete, they need to be done on both sides. I'll try it later.

**Comment by blueww** [comment]
@yupwei68 
Not sure if it works in your retry?
If so, would you please close this issue?
thanks!
