### ISSUE TITLE
Windows VM name can be longer than 15 chars in Azure Portal but not via API

### ISSUE THREAD

**Issue by pipoe2h** [Azure/azure-rest-api-specs#11225]
Hi,

When creating a Windows virtual machine via the portal it is allowed to give a name longer than 15 chars. When trying the same via Azure CLI or using the APIs, it is not possible. 

Why this mismatch between the UI and the API? If I do an `az vm get`, I can see the key name with the 16 chars value.

**Comment by xccc-msft** [comment]
Thanks for reporting this. Routing to Compute service team.

**Comment by amjads1** [comment]
@avirishuv - Can you please look into this issue?

**Comment by Drewm3** [comment]
@pipoe2h, can you confirm that the actual compute name that resulted from your portal deployment was truncated to 15 characters? It looks like the portal is just taking the first 15 characters and dropping the rest. That is why the command is successful in the portal. 

I am not sure if this is a bug or a "feature" in the portal, but it would at least explain what you are seeing. If you confirm that the portal was dropping the extra characters in your situation, then we will move this over to the portal team to comment on this as a bug or a feature.

**Comment by pipoe2h** [comment]
@Drewm3 the hostname for Windows machine is truncated to 15 for sure, but the VM object in the portal is able to accept more than 15 characters. This is possible only via the portal and not via the API. It seems a portal feature that it's not aligned with the API charset limit.

**Comment by Drewm3** [comment]
In this scenario the portal is using the REST APIs. So the functionality is in the APIs. Specifically on the PUT request you can set the vmName property in the URL to a name that is longer than 15 characters, and then use the 15 character name for **computerName** in the OSProfile section of the API.

It does appear that the ability to do the above scenario is not exposed in PowerShell, but it is available in the REST API. Please let me know if you have any other questions.
