### ISSUE TITLE
ARM Template Options for Adding Key to KeyVault is not documented

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-rest-api-specs#11229]
Official documentation for ARM Template Reference Guide doesn't have Keys resource details. However for achieving the same I found there is a 101 template. 

ARM Template Documentation: https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2019-09-01/vaults/secrets
Adding KV Key 101 Template : https://github.com/Azure/azure-quickstart-templates/blob/master/201-machine-learning-encrypted-workspace/prereqs/prereq.azuredeploy.json

**Comment by weidongxu-microsoft** [comment]
I think you should report issue to https://github.com/MicrosoftDocs/feedback/issues

**Comment by mvvsubbu** [comment]
No ARM manifest reference pages are generated based on swagger, so this is the correct place. KV team should update their swagger spec

**Comment by sebansal** [comment]
Are you looking for this doc ?
https://docs.microsoft.com/en-us/azure/key-vault/keys/quick-create-template?tabs=CLI

**Comment by mvvsubbu** [comment]
I am looking for official ARM template resource documentation containing this "Microsoft.KeyVault/vaults/keys" resource documented

**Comment by mvvsubbu** [comment]
This link https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2019-09-01/vaults/secrets should have keys resource mentioned as well.

**Comment by sebansal** [comment]
Hey @msmbaldwin, did you get a chance to add the template to that repo? Is there a PR to follow?

**Comment by sebansal** [comment]
@msmbaldwin can you look into this request

**Comment by sebansal** [comment]
@jlichwa can you help review this?

**Comment by jlichwa** [comment]
@mvvsubbu documentation is generated based on swagger (stable version) since it is still in preview there will not be documentation till GA.

**Comment by mvvsubbu** [comment]
Ok thanks for updating.

**Comment by sebansal** [comment]
#please-close
