### ISSUE TITLE
[Network] Weird use for status code 429

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1124]
Related to https://github.com/Azure/azure-sdk-for-go/issues/588
When creating or updating subnets, it can happen that the API return status code 429 and a message clarifying that this is a retryable error, (unlike the normal use of 429 which means to many requests).
My guess is that doing the very same request later, it will succeed.
Still, it would be weird to include status code 429 as a valid code to retry for in the SDKs. Is it possible to include this status code with this message in the swagger to indicate it is safe to continue retrying?
@amarzavery @whiskeyjay @marstr @jhendrixMSFT

**Comment by mcardosos** [comment]
@ritwikbasu What do you think?

**Comment by mcardosos** [comment]
@jobatzil what do you think?

**Comment by jhendrixMSFT** [comment]
Any update here?  This resulted in a real customer issue in the Go SDK .  We were able to prescribe a workaround however we'd like to understand if this is a best practice.

**Comment by mcardosos** [comment]
poke @amarzavery

**Comment by kirthik** [comment]
@DeepakRajendranMsft - Could you please take a look at this issue?

**Comment by tombuildsstuff** [comment]
👋 @DeepakRajendranMsft @kirthik is there any update/expected timeline to fix this? :)

**Comment by liumichelle** [comment]
The fix for this in progress - TBD ETA

**Comment by DeepakRajendranMsft** [comment]
We are still working on this, sorry. we are evaluating that if we have 429 as a retryable error, it may break clients out there that have a special treatment for 429 since they might expect an exception from SDKs generated by us

**Comment by jhendrixMSFT** [comment]
Even with a Retry-After header in the response?

**Comment by mcardosos** [comment]
[Little documentation on 429 usage](https://httpstatuses.com/429). With this as context, I think 429 usage is not something that has to do with this repository. 429 needs a different treatment than other status codes when we are talking about retry strategies. Retry strategies live on each language SDK client runtime. This has been fixed on the go SDK runtime [here](https://github.com/Azure/go-autorest/pull/155).

**Comment by mcardosos** [comment]
Fixed for go here https://github.com/Azure/go-autorest/pull/155
