### ISSUE TITLE
KeyVault: Microsoft.KeyVault/vaults/keys API is not published

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#11250]
ARM Templates now support KeyVault keys: https://docs.microsoft.com/en-us/azure/key-vault/keys/quick-create-template?tabs=CLI

However, the API definition doesn't contain these endpoints https://github.com/Azure/azure-rest-api-specs/tree/d0e81d229be92e34b443b666f7672cbab0806556/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01.

Why is that?

**Comment by sebansal** [comment]
The PR is in flight for the update.
https://github.com/Azure/azure-rest-api-specs/pull/10643

**Comment by sebansal** [comment]
Closing as PR is merged
