### ISSUE TITLE
Storage Account azureFilesIdentityBasedAuthentication Update fails

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11272]
1. create a storage account successfully
Put /subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/unlikely23exst2acct3p9ij?api-version=2019-06-01 HTTP/1.1
{"kind":"StorageV2","location":"westeurope","properties":{"networkAcls":{"defaultAction":"Allow"},"accessTier":"Hot","supportsHttpsTrafficOnly":true,"isHnsEnabled":false,"allowBlobPublicAccess":false,"minimumTlsVersion":"TLS1_0"},"sku":{"name":"Standard_LRS"},"tags":{"environment":"production"}}
X-Ms-Request-Id: d8a055fe-be7c-484f-8b87-8b271df60137

2. Update azureFilesIdentityBasedAuthentication  AADDS successfully
PATCH /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/acctestRG-storage-201019114226160064/providers/Microsoft.Storage/storageAccounts/unlikely23exst2acct3p9ij?api-version=2019-06-01 HTTP/1.1
{"properties":{"azureFilesIdentityBasedAuthentication":{"directoryServiceOptions":"AADDS"}}}
X-Ms-Request-Id: edafdf62-e345-4527-8343-8323bce5091c

Response:
{"sku":{"name":"Standard_LRS","tier":"Standard"},"kind":"StorageV2","id":"/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/unlikely23exst2acct3p9ij","name":"unlikely23exst2acct3p9ij","type":"Microsoft.Storage/storageAccounts","location":"westeurope","tags":{"environment":"production"},"properties":{"privateEndpointConnections":[],"azureFilesIdentityBasedAuthentication":{"directoryServiceOptions":"AADDS"},"minimumTlsVersion":"TLS1_0","allowBlobPublicAccess":false,"isHnsEnabled":false,"networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[],"ipRules":[],"defaultAction":"Allow"},"supportsHttpsTrafficOnly":true,"encryption":{"services":{"file":{"keyType":"Account","enabled":true,"lastEnabledTime":"2020-10-19T03:42:45.0703501Z"},"blob":{"keyType":"Account","enabled":true,"lastEnabledTime":"2020-10-19T03:42:45.0703501Z"}},"keySource":"Microsoft.Storage"},"accessTier":"Hot","provisioningState":"Succeeded","creationTime":"2020-10-19T03:42:44.9765874Z","primaryEndpoints":{"dfs":"https://unlikely23exst2acct3p9ij.dfs.core.windows.net/","web":"https://unlikely23exst2acct3p9ij.z6.web.core.windows.net/","blob":"https://unlikely23exst2acct3p9ij.blob.core.windows.net/","queue":"https://unlikely23exst2acct3p9ij.queue.core.windows.net/","table":"https://unlikely23exst2acct3p9ij.table.core.windows.net/","file":"https://unlikely23exst2acct3p9ij.file.core.windows.net/"},"primaryLocation":"westeurope","statusOfPrimary":"available"}}

3. Update other configuration
PATCH /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/acctestRG-storage-201019114226160064/providers/Microsoft.Storage/storageAccounts/unlikely23exst2acct3p9ij?api-version=2019-06-01 HTTP/1.1
{"properties":{"networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[],"ipRules":[],"defaultAction":"Allow"}}}

Response: 
HTTP/2.0 409 Conflict
X-Ms-Request-Id: 3837711c-4c42-4f54-ad01-0337e718f841
{"error":{"code":"StorageAccountOperationInProgress","message":"An operation is currently performing on this storage account that requires exclusive access."}}

**Comment by xccc-msft** [comment]
Routing to Storage service team. Thanks.

**Comment by blueww** [comment]
@zfchen95 
Would you please help to look at the SRP server issue?

**Comment by yupwei68** [comment]
Storage Service has replied it's by design

**Comment by yupwei68** [comment]
Here's the reply:

> In some cases, the update operation may take longer. Server will return 202 accepted in the response. Client will pull the status until the update operation completes. It is commonly seen in create storage account when we will create account on stamp and create service update in AAD DS after returning response. If you are seeing 409 constantly, e.g. longer than 1 day, we may need to investigate to clear the blocker.
