### ISSUE TITLE
Linter errors in arm-sql spec that needs to be fixed

### ISSUE THREAD

**Issue by balajikris** [Azure/azure-rest-api-specs#1128]
See https://github.com/Azure/azure-rest-api-specs/pull/1107#issuecomment-294552722

1.  _ERROR: Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for operations.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/paths_

1.  _ERROR: The tracked resource, 'Database', must have a list by resource group operation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database
ERROR: The tracked resource, 'ElasticPool', must have a list by resource group operation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool
ERROR: The tracked resource, 'Database', must have a list by subscriptions operation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database_

1.  _ERROR: The tracked resource, 'ElasticPool', must have a list by subscriptions operation.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool
ERROR: Tracked resource 'Database' must have patch operation that at least supports the update of tags.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database
ERROR: Tracked resource 'Server' must have patch operation that at least supports the update of tags.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Server
ERROR: Tracked resource 'ElasticPool' must have patch operation that at least supports the update of tags.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool_

1. _ERROR: Model definition 'FirewallRule' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/FirewallRule_

**Comment by jaredmoo** [comment]
Fixed PATCH errors with #1384

 1. ERROR: Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for operations.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/paths

2. ERROR: The tracked resource, 'Database', must have a list by resource group operation.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database
    ERROR: The tracked resource, 'ElasticPool', must have a list by resource group operation.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool
    ERROR: The tracked resource, 'Database', must have a list by subscriptions operation.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database
    ERROR: The tracked resource, 'ElasticPool', must have a list by subscriptions operation.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool
    
3.   ~~ERROR: Tracked resource 'Database' must have patch operation that at least supports the update of tags.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Database
    ERROR: Tracked resource 'Server' must have patch operation that at least supports the update of tags.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/Server
    ERROR: Tracked resource 'ElasticPool' must have patch operation that at least supports the update of tags.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/ElasticPool~~

4. ERROR: Model definition 'FirewallRule' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.
    Path: file:///C:/workspace/azure-rest-api-specs/arm-sql/compositeSql.json#/definitions/FirewallRule

**Comment by jaredmoo** [comment]
Fixed 4. in list above with #1441

**Comment by jaredmoo** [comment]
And 2. in list above are warnings now.

**Comment by jaredmoo** [comment]
1. in list above are fixed by #1471

**Comment by jaredmoo** [comment]
All errors are now fixed. Proof: https://github.com/Azure/azure-rest-api-specs/pull/1471#issuecomment-318170774

@balajikris can you close?

**Comment by jaredmoo** [comment]
Thanks Kirthi!
