### ISSUE TITLE
$top query parameter in /subscriptions/{id}/providers doesn't seem to be respected

### ISSUE THREAD

**Issue by brywang-msft** [Azure/azure-rest-api-specs#1129]
GET https://management.azure.com/subscriptions/{id}/providers?api-version=2015-11-01

and

GET https://management.azure.com/subscriptions/{id}/providers?$top=10&api-version=2015-11-01

appear to return the same results.

Spec appears to support the $top parameter. Not sure if this is expected behavior or not.

**Comment by vishrutshah** [comment]
@brywang-msft Please add the link to the spec and operation your are using for infomration. Thanks

**Comment by brywang-msft** [comment]
Spec is this one: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-resources/resources/2015-11-01/swagger/resources.json

Path is: /subscriptions/{subscriptionId}/providers

Additional headers in request:
"Content-Type": "application/json"
"Authorization": {usual stuff}
"x-ms-client-request-id": "61409ee5-c14c-418d-9dcb-af9617f4db81"
"accept-language": "en-US"

**Comment by vishrutshah** [comment]
**cc:** @TianoMS

**Comment by sergey-shandar** [comment]
@TianoMS do you know much about how the service should behave?

**Comment by TianoMS** [comment]
Seems the service doesn't support $top. We should either fix the swagger spec or the service.

**Comment by tim-nguyen-cs** [comment]
Because the `$top` parameter of this REST API endpoint is not supported, the documentation has been updated. Thanks!
