### ISSUE TITLE
Compute: Image Builder Template Does Not Honor the `version` input in terms of api Idempotence

### ISSUE THREAD

**Issue by mybayern1974** [Azure/azure-rest-api-specs#11313]
As for the `version` field defined in Image Builder Template swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/imagebuilder/resource-manager/Microsoft.VirtualMachineImages/stable/2020-02-14/imagebuilder.json#L599, when the input is "Latest" in PUT, the output in GET is `latest (specific version)`

There are two issues:
1. Case sensitivity is not honored;
2. Extra value is added from PUT to GET

When doing the same experiment on VM Image swagger, INPUT are respected:
1. Case sensitivity is honored;
2. There is a specific version returned in GET but in a new field named `exactVersion` is returned rather than changing the original field.

**Comment by Drewm3** [comment]
@danielsollondon, could you please look into this issue.

**Comment by danielsollondon** [comment]
@sumit-kalra - can you review please?

**Comment by Drewm3** [comment]
Updating this to be a bug. I am also following up with Sumit to check on the investigation status.

**Comment by sumit-kalra** [comment]
@mybayern1974 

What you point out is correct - the GET request should return the same value for 'version' as was used in PUT so that a subsequent PUT containing the same data as was obtained in the GET request can be idempotent. We will fix this in the next API revision.

That said, given that Image Builder does not allow PUTs on a pre-existing resource, I would need to know if any specific scenario or client implementation is broken due to this behavior. Could you please clarify?

**Comment by mybayern1974** [comment]
@sumit-kalra thank you for your reply. The being "blocked" implementation is Terraform that relies on service rest api idempotency to reach the resource state management. I understand in rest api, repeatedly executing PUT with the same payload may incur reasonable error messages, while in Terraform, the expectation is nothing will happen with Terraform detecting user unchanged input and service backend having the same state so Terraform doing nothing.

While given now PUT != GET, the unchanged user input is still `latest` while the remote backend is `latest (version...)`, then Terraform assumes users made changes then start to PUT again which get an reasonable error response, while users would be confused since the user assumes things should be silent since he/she did nothing.

While by saying quoted "blocked", I can add a hack in Terraform coding to specifically handle this case, which means this is not a hard blocking to Terraform. While per Terraform development practices, I'll link this rest api / swagger issue in the Terraform code to track this.

Hope the above clarifies.

**Comment by sumit-kalra** [comment]
Thanks @mybayern1974 for sharing your scenario.
We have taken a note of this discrepancy and will revisit it when creating the next API version.

**Comment by sumit-kalra** [comment]
Quick update - the issue with `latest ` has been fixed but will be released in the next API version since it a change in behavior. That should happen sometime later this year.

**Comment by sumit-kalra** [comment]
Update: The next API version is on track to be released this year and will have the fix for <latest>.

**Comment by jaylabell** [comment]
@sumit-kalra any updates?

**Comment by rezmicrosoft** [comment]
Update: we have fixed the issue in API version 2021-10-01 (and later versions).
