### ISSUE TITLE
Storage Container 409 error 

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11331]
Storage Container returns 409 error on second updating

Region: West Europe, Storage Account Name:acctestacclph8h ContainerName: vhds
HTTP/2.0 409 Conflict
Content-Length: 196
Cache-Control: no-cache
Content-Type: application/json
**Date: Thu, 22 Oct 2020 07:23:43 GMT**
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 2cb09337-8692-90b7-f661-fb3c00234d44
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1176
X-Ms-Request-Id: 41ab4f31-8d17-4588-a67e-8f363102b94b
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201022T072344Z:2db39721-e35a-4214-96cc-3e6f7599403a

{"error":{"code":"PublicAccessNotPermitted","message":"Public access is not permitted on this storage account.\nRequestId:f341ec27-b01e-00bc-6544-a83027000000\nTime:2020-10-22T07:23:43.8986076Z"}}

**Comment by blueww** [comment]
@yupwei68 
The account "acctestacclph8h" no exist now, so can't check the account properties.

But the issue might caused by the storage account "allowBlobPublicAccess" is set to false. Please make sure it's true (or null for new created account), and try again.

**Comment by yupwei68** [comment]
@blueww Thanks. `allow_blob_public_access = true` works.
