### ISSUE TITLE
Storage Container Immutability Policy 500 Internal Error

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11348]
1. create Container
PUT /subscriptions/.../resourceGroups/acctestRG-201023101755997328/providers/Microsoft.Storage/storageAccounts/acctestaccs6jio/blobServices/default/containers/vhds?api-version=2019-06-01 HTTP/1.1
{"properties":{"metadata":{},"publicAccess":"None"}}
HTTP/2.0 201 Created
Content-Length: 427
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 23 Oct 2020 02:18:41 GMT
Etag: "0x8D876F9F5C3C805"
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 628afdaa-4357-37e2-92e0-120e90a39a48
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
X-Ms-Request-Id: fea25a0e-9d36-4707-9066-6d212c8f89d4
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201023T021841Z:06061e66-74c1-4c47-bc06-85c9c195649b

{"id":"/subscriptions/.../resourceGroups/acctestRG-201023101755997328/providers/Microsoft.Storage/storageAccounts/acctestaccs6jio/blobServices/default/containers/vhds","name":"vhds","type":"Microsoft.Storage/storageAccounts/blobServices/containers","properties":{"deleted":false,"remainingRetentionDays":0,"metadata":{},"publicAccess":"None","hasImmutabilityPolicy":false,"hasLegalHold":false}}

2. Update extended Immutability Policy
POST /subscriptions/.../resourceGroups/acctestRG-201023101755997328/providers/Microsoft.Storage/storageAccounts/acctestaccs6jio/blobServices/default/containers/vhds/immutabilityPolicies/default/extend?api-version=2019-06-01 HTTP/1.1
{"properties":{"allowProtectedAppendWrites":true,"immutabilityPeriodSinceCreationInDays":7}}
HTTP/2.0 500 Internal Server Error
Content-Length: 100
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 23 Oct 2020 02:19:26 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 628afdaa-4357-37e2-92e0-120e90a39a48
X-Ms-Failure-Cause: service
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
X-Ms-Request-Id: 276aadbb-4d5b-4e34-8839-c8bf0ec45f00
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201023T021926Z:d3f47a7c-47e9-46f1-a8bd-70c95c3631fe

{"error":{"code":"UnexpectedException","message":"The server was unable to complete your request."}}

**Comment by blueww** [comment]
@zfchen95, @Himanshu Chhabra
It seems a server issue, would you please help to look?

**Comment by yupwei68** [comment]
Solved by @HimanshuChhabra . Thanks! Here we need set immutability policy -> lock the policy -> set extend immutability policy. It would be nicer to have a complete error message.
