### ISSUE TITLE
Microsoft.Consumption UsageDetails_List missing "skiptokenver" and "id" parameters

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#11351]
For operation [UsageDetails_List](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-01-01/consumption.json#L42), there is param `$skiptoken` however this seems to be insufficient.  When looking at a `nextLink` URL returned from the service it also contains a `skiptokenver` and `id` query params.  This was discovered by a customer when they were trying to manually page, not using the value in `nextLink`.

**Comment by rahulpandit85** [comment]
Thanks @jhendrixMSFT, I am trying to understand the ask here. 
I understand the need fix the swagger and have id and skiptoken ver as a parameter in the swagger as well. 
Please let me know if there is something more to this.

**Comment by jhendrixMSFT** [comment]
Correct, the ask is to add `skiptokenver` and `id` query params to all applicable operations.

**Comment by ramaganesan-rg** [comment]
we have a backlog item to update the documentation. please feel free to check back with us if you don't see an update in the coming months.  thank you for your feedback.
