### ISSUE TITLE
After clearing Storage container LegalHold, delete storage account returns 409 Error

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11350]
1. create storage account
2. create container
3. set legal holds
4. update legal holds
5. clear legal holds 
6. destroy all
6.1 get container:
GET /subscriptions/.../resourceGroups/acctestRG-201023143421224156/providers/Microsoft.Storage/storageAccounts/acctestacc88429/blobServices/default/containers/vhds?api-version=2019-06-01 HTTP/1.1

Response:
{"id":"/subscriptions/.../resourceGroups/acctestRG-201023143421224156/providers/Microsoft.Storage/storageAccounts/acctestacc88429/blobServices/default/containers/vhds","name":"vhds","type":"Microsoft.Storage/storageAccounts/blobServices/containers","etag":"\"0x8D8771E1940016B\"","properties":{"deleted":false,"remainingRetentionDays":0,"defaultEncryptionScope":"$account-encryption-key","denyEncryptionScopeOverride":false,"publicAccess":"None","leaseStatus":"Unlocked","leaseState":"Available","lastModifiedTime":"2020-10-23T06:37:22.0000000Z","legalHold":{"hasLegalHold":false,"tags":[]},"hasImmutabilityPolicy":false,"hasLegalHold":false}}

Date: Fri, 23 Oct 2020 06:37:55 GMT
Etag: "0x8D8771E1940016B"
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 9c17c7ce-af00-032b-8ba0-307aa9a5f31d
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11976
X-Ms-Request-Id: c0ed5a57-21ae-48da-92ef-228f20ed0e58
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201023T063755Z:bf0f604d-9cb1-44e3-baf2-5418c8627fc5

6.2 container deleted successfully

DELETE /subscriptions/.../resourceGroups/acctestRG-201023143421224156/providers/Microsoft.Storage/storageAccounts/acctestacc88429/blobServices/default/containers/vhds?api-version=2019-06-01 HTTP/1.1

Response:
HTTP/2.0 200 OK
Date: Fri, 23 Oct 2020 06:38:00 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 9c17c7ce-af00-032b-8ba0-307aa9a5f31d
X-Ms-Ratelimit-Remaining-Subscription-Deletes: 14999
X-Ms-Request-Id: df503eb9-7d57-49bd-9e26-df9a61c3f125
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201023T063800Z:dc201919-ed23-4dc2-8ac3-db79f5490f91
Content-Length: 0

6.3 account delete return 409 Error
DELETE /subscriptions/.../resourceGroups/acctestRG-201023143421224156/providers/Microsoft.Storage/storageAccounts/acctestacc88429?api-version=2019-06-01 HTTP/1.1

Response:
Date: Fri, 23 Oct 2020 06:38:01 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 9c17c7ce-af00-032b-8ba0-307aa9a5f31d
X-Ms-Ratelimit-Remaining-Subscription-Deletes: 14999
X-Ms-Request-Id: 2d91e345-718a-48ba-8962-bedd998021b8
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201023T063802Z:a49c09e8-a612-417b-baf2-b98eddd774ee

{"error":{"code":"AccountProtectedFromDeletion","message":"Account acctestacc88429 Containers vhds have legal hold."}}

**Comment by blueww** [comment]
@zfchen95, @Himanshu Chhabra
It seems a server issue, would you please help to look?

**Comment by HimanshuChhabra** [comment]
Fixed: https://msazure.visualstudio.com/One/_git/Storage-SRP/pullrequest/3714293

**Comment by yupwei68** [comment]
Thanks @HimanshuChhabra
