### ISSUE TITLE
Storage Object Replication Policy List Api Id is missing

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11376]
GET /subscriptions/.../resourceGroups/acctest-storage-dst-201026162127644153/providers/Microsoft.Storage/storageAccounts/stracctdstcab6t/objectReplicationPolicies?api-version=2019-06-01 HTTP/1.1

Response:
Date: Mon, 26 Oct 2020 08:23:08 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: c2b08fb5-d80c-a475-5d96-28973595cc34
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11992
X-Ms-Request-Id: 9011c64b-fe70-4035-84bc-05a6a6806735
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201026T082308Z:ac1597d4-ff39-4683-993c-aad4ae8d8d55

{"value":[{"properties":{"policyId":"e171d597-e391-4832-9046-a1cdc3d9a397","sourceAccount":"stracctsrccab6t","destinationAccount":"stracctdstcab6t","rules":[{"ruleId":"1d2c844c-83be-4526-af8e-ccf98cfe6a9e","sourceContainer":"strcsrccab6t","destinationContainer":"strcdstcab6t","filters":{"prefixMatch":[]}}]}}]}

ID for the orp is missing.

**Comment by blueww** [comment]
@yupwei68 
As I see, the policy ID and rule ID are both returned.
What's the ID you expected to return?

**Comment by yupwei68** [comment]
@blueww Resource Id, normally resource id is returned in listing.

**Comment by blueww** [comment]
@zfchen95 
Would you please confirm if ORS policy has resource ID?

**Comment by yupwei68** [comment]
Hi @blueww , @zfchen95 has replied in email that they will add the resource id.

**Comment by blueww** [comment]
@yupwei68 
Thanks for the update!

**Comment by zfchen95** [comment]
This should be fixed now.

**Comment by yupwei68** [comment]
Thanks
