### ISSUE TITLE
Quota API Fails with 404 on every requests

### ISSUE THREAD

**Issue by JaDevGuy** [Azure/azure-rest-api-specs#11380]
The Quota API fails on all requests with a 404 when testing in a Pay-As-You-Go account or Free Trial. 
https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi

At minimum the LIST method should work however this returns a 404 as well:
GET https://management.azure.com/subscriptions/<subscription_id>/providers/Microsoft.Capacity/resourceProviders/Microsoft.Compute/locations/eastus/serviceLimits?api-version=2019-07-19-preview
Response Code: 404

Trying to use any other method has the same result. The documentation on what exactly is the "resourceName" for Create/Update Quota API calls is also of no help.

Can anyone review this to ensure this API works and the documentation is properly updated?

**Comment by rahuls-microsoft** [comment]
Please refer to the section of registring the subscription with Capacity RP -
https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi 
 Important

Prerequisite: Resource Provider (Microsoft.Capacity) needs to be registered for the Subscriptions. If the Resource provider haven't previously used in your subscriptions, follow the article Resolve errors for resource provider registration to trouble shoot and register Resource Provider with PowerShell or Azure CLI or through Azure Portal.

Did we register the subscription with the Microsoft.Capacity Resource Provider, as mentioned above?

**Comment by JaDevGuy** [comment]
Thanks @rahuls-microsoft . The Microsoft.Capacity resource provider was registered but still gave the 404 errors. I finally figured this out through trial and error. 
The resource name mentioned the CREATE Quota API documentation is the resource provided by the resource provider (mentioned in the LIST API documentation instead). The Create Quota API call does not take the response from the GET method as mentioned in the docs. Instead it takes only the "properties" element, excluding the "properties.resourceType" element as well if present, else it will give a "Bad Request" response. Hope this helps to try and update the documentation to be clearer.
