### ISSUE TITLE
allow_trusted_microsoft_services_bypass_firewall is not supported by eventhub

### ISSUE THREAD

**Issue by kvendingoldo** [Azure/azure-rest-api-specs#11425]
using api-version: 2018-01-01-preview

preview spec 2018 (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/namespaces-preview.json) does not support `allow_trusted_microsoft_services_bypass_firewall` option.

**Comment by yungezz** [comment]
service swagger issue, route to appropriate team

**Comment by gd-asharov** [comment]
@yungezz any updates here?

**Comment by yungezz** [comment]
> @yungezz any updates here?

add issue assignee, hi @JamesBirdsall @serkantkaraca could you pls update on the issue

**Comment by gd-asharov** [comment]
@yungezz any updates? :)

**Comment by kvendingoldo** [comment]
It's not stale.

**Comment by aangelisc** [comment]
Has there been any progress on getting this in?
@valkyrieuk @otaiga - for reference

**Comment by Saglodha** [comment]
Closing issue since property is supported in latest api-version: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/networkrulessets-preview.json , please feel free to reach out in case of additional queries.
