### ISSUE TITLE
Operationalinsights/2019-08-01-preview paginated model without nextLink defined

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#11420]
In operationalinsights/2019-08-01-preview, the operation `DataExport_ListByWorkspace` is defined a paginated operation ([here](https://github.com/Azure/azure-rest-api-specs/blob/c174d654d4cd9f45e929a31480e19ada7baa6924/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2019-08-01-preview/OperationalInsights.json#L78)), but the corresponding [model returned](https://github.com/Azure/azure-rest-api-specs/blob/c174d654d4cd9f45e929a31480e19ada7baa6924/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2019-08-01-preview/OperationalInsights.json#L442) does not specify a field of `nextLink`.

This issue blocks the generated SDK.

**Comment by shemers** [comment]
@ArcturusZhang is this still an issue?

**Comment by ArcturusZhang** [comment]
Hi @shemers yes this is only resolved when the nextlink was added to [this model](https://github.com/Azure/azure-rest-api-specs/blob/c174d654d4cd9f45e929a31480e19ada7baa6924/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2019-08-01-preview/OperationalInsights.json#L442)

**Comment by ArcturusZhang** [comment]
Hi any updates?

**Comment by yossi-y** [comment]
We have fixed this in the new version (2020-08-01) and working to publish it.
We recommend that you move to the newer version to get this change affected.

**Comment by ArcturusZhang** [comment]
> We have fixed this in the new version (2020-08-01) and working to publish it.
> We recommend that you move to the newer version to get this change affected.

It is fine, but please notice that the issue in 2019-08-01-preview is still unresolved and no SDK will release for this api-version. All release request on this api-version for go sdk will be rejected.

still, fixing it is as simple as adding a new readonly property in the swagger which certainly will not trigger the breaking change alarm.
