### ISSUE TITLE
Endpoint to delete an instance from an azure app service

### ISSUE THREAD

**Issue by LiquoriChris** [Azure/azure-rest-api-specs#11533]
**Endpoint to delete an Azure App Service instance**

Would it possible to add an endpoint to be able to remove an instance from a scaled out Azure App Service? Currently, there are endpoint to delete instance processes, but given an unhealthy instance, should be able to remove the instance from the app service and create a new instance.

This would be helpful for DevOps and engineering to isolate the unhealthy instance and remove it from the App Service without interrupting operations. Understood that Health Checks are now GA and can be implemented, but this also would be helpful for quick remediation. 

Thanks for your help and feedback.

**Comment by LiquoriChris** [comment]
Any update on this would be appreciated. Thanks

**Comment by rmgalante** [comment]
I agree. This api request is useful and required. We have no way to stop a running instance after it's been started. The tools to stop an App Service instance do not work reliably (i.e., scaling down to 1 instance). Meanwhile, it continues to bill hours unnecessarily, requiring support from cost management.

**Comment by Bouke** [comment]
> Any update on this would be appreciated. Thanks

Same!

**Comment by davidbIQ** [comment]
plus 1

**Comment by aaronschendel** [comment]
Adding interest for this - would really appreciate the functionality.
