### ISSUE TITLE
The description is wrong for R4018 OperationsApiResponseSchema

### ISSUE THREAD

**Issue by aim-for-better** [Azure/azure-rest-api-specs#11651]
The description for [R4018 OperationsApiResponseSchema](https://github.com/Azure/azure-rest-api-specs/blob/fbe9266483321792bcb4b3cce511b17cf685a123/documentation/openapi-authoring-automated-guidelines.md#r4018-operationsapiresponseschema)
is 
```
Description : The operations API should have a response body schema consistent with the contract spec. The required properties such as isDataAction,display.description **or** display.resource,must be included.
```

But in fact it should be "and", display.description **and** display.resource must be included or the error can't be fixed.

**Comment by aim-for-better** [comment]
Either the autorest tool is wrong or the document is wrong.

**Comment by raych1** [comment]
@jianyexi , can you have a look at this lint rule document?

**Comment by jianyexi** [comment]
@aim-for-better Thanks, this is a good suggestion, the document is confusing , I will fix it ASAP.
The operation API should follow the schema in https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/proxy-api-reference.md#exposing-available-operations
