### ISSUE TITLE
compute: spec missing for virtualmachines/{vm}/InstanceView

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-rest-api-specs#117]
folks we're missing spec for 

```
.../providers/Microsoft.Compute/virtualMachines/{vm}/InstanceView
```

as far as I can tell. Can someone verify? @huangpf

**Comment by huangpf** [comment]
Do you mean the operation of getting a VM's instance view? If so, then it's on the VM get operation by using ```expand=instanceView```.

**Comment by ahmetalpbalkan** [comment]
@huangpf okay this may solve my problem. Thanks. Do you know if this `?$expand` is documented anywhere? I can't seem to find it.

I think `/InstanceView` is still a valid endpoint. https://msdn.microsoft.com/en-us/library/azure/mt163682.aspx so it probably should be part of the spec, right?

**Comment by huangpf** [comment]
@ahmetalpbalkan Yes, if this endpoint and operation are indeed available, then it shall be included. Let's confirm it with the CRP team who manages the service API. 

Not sure about the documentation. It's unlikely acceptable to let users read through the code to figure out this:
https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Compute/ComputeManagement/Generated/VirtualMachineOperations.cs#L5441

**Comment by ahmetalpbalkan** [comment]
@huangpf I confirmed that it is not documented, but it should be. Just seeing `?$expand=instanceView` in the code does not mean that's the only value it can take, it simply means that's one of the values it can take.

**Comment by huangpf** [comment]
I agree with you. Please sync up with @singhkay & @sauryadas for the documentation issue.

**Comment by ahmetalpbalkan** [comment]
still an issue..

**Comment by huangpf** [comment]
+ @hyonholee

**Comment by JamieCressey** [comment]
+1 just ran into this

**Comment by devigned** [comment]
@huangpf or @hyonholee please resolve the issue.

**Comment by gkapagunta** [comment]
@huangpf @hyonholee What is he status of this issue? Has this been documented yet?

**Comment by singhkays** [comment]
Adding @stephbaron for visibility on this missing API from Compute RP swagger spec

**Comment by salameer** [comment]
Hi @huangpf and @hyonholee, what's the ETA for resolving this?

Thanks,

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
