### ISSUE TITLE
Resources: 2020-10-01 is published but not deployed yet?

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#11711]
The new API version 2020-10-01 has been published for Microsoft.Resources. However, it doesn't seem to work yet:

```
Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2020-10-01' is invalid.
The supported versions are '2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

Why is that? Does it mean this API version isn't "published" yet, and how can I see that from API definitions?

**Comment by mikhailshilkov** [comment]
This is not a PR and it shouldn't be closed

**Comment by vladimirjoanovic** [comment]
2020-10-01 should be working for deployments and deploymentScripts which resource type were you trying to create?

**Comment by mikhailshilkov** [comment]
I was trying to create resource groups. I believe this has been fixed since November.

**Comment by mikhailshilkov** [comment]
It's been a while since I reported this and the version has been deployed since then. Although this fact isn't nice, there's nothing to be done here specifically.
