### ISSUE TITLE
[Container Service]: Support for Clusters on the Internal Network

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1172]
👋 hey folks

An [issue's been raised on the Terraform repo to add support for Container Service instances on an Internal Network](https://github.com/hashicorp/terraform/issues/14062).

I've taken a look and I can't see this functionality exposed in the Azure SDK for Go, which is generated from API version `2017-01-31` - would it be possible to update the Swagger to add support for this?

Thanks! :)

**Comment by tombuildsstuff** [comment]
👋 hey @kirthik / @balajikris

So that I can manage expectations at our end - is there any idea of when support for this is likely to land?

Thanks! :)

**Comment by brendandburns** [comment]
I don't believe this is currently supported in the ACS API...  (but when it is, it will be added to our swagger too)

**Comment by codyja** [comment]
We could use this as well. I looked through the Azure API and docs and it didn't appear to be supported, but I see in Azure's ACS-Engine that there is the ability to generate ARM templates that allow ACS to be deployed into existing VNETs and subnets. I haven't been able to figure out what vlabs is. 

```
// MasterProfile represents the definition of the master cluster
type MasterProfile struct {
	Count                    int    `json:"count"`
	DNSPrefix                string `json:"dnsPrefix"`
	VMSize                   string `json:"vmSize"`
	OSDiskSizeGB             int    `json:"osDiskSizeGB,omitempty"`
	VnetSubnetID             string `json:"vnetSubnetID,omitempty"`
	FirstConsecutiveStaticIP string `json:"firstConsecutiveStaticIP,omitempty"`
	IPAddressCount           int    `json:"ipAddressCount,omitempty"`
	StorageProfile           string `json:"storageProfile,omitempty"`

	// subnet is internal
	subnet string

	// Master LB public endpoint/FQDN with port
	// The format will be FQDN:2376
	// Not used during PUT, returned as part of GET
	FQDN string `json:"fqdn,omitempty"`
}
```

https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/types.go

**Comment by MarkHerhold** [comment]
@brendandburns is there a public issue tracking private network support for the container service?

**Comment by kirthik** [comment]
closing this since @brendandburns said this is not supported by service yet.
