### ISSUE TITLE
autorest.azureresourceschema is unable to locate Microsoft.AlertsManagement/resourceHealthAlerts

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#11766]
The following PR moved the "resourceHealthAlerts" resource type into its own file:
https://github.com/Azure/azure-rest-api-specs/pull/11164

However it failed to update the following `readme` with the reference to the new file:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/alertsmanagement/resource-manager/readme.azureresourceschema.md#tag-schema-alertsmanagement-2020-08-04-preview-and-azureresourceschema

This resulted in the ARM template schemas for this resource type being removed:
https://github.com/Azure/azure-resource-manager-schemas/commit/387daca6f8e166b7d8be9b5d723fdd9c5e80c8d2

**Comment by yairgil** [comment]
@anthony-c-martin Thank you for reaching out. Internal bug 9225428 is opened against this ticket, will update once it's fixed.

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin Thank you for reaching out. Internal bug 9225428 is opened against this ticket, will update once it's fixed.

Sure. I've opened https://github.com/Azure/azure-resource-manager-schemas/issues/1480 to track the impact on ARM schemas.
