### ISSUE TITLE
"Orchestrator" misspelled in "ContainerServiceOchestratorTypes"

### ISSUE THREAD

**Issue by v-iam** [Azure/azure-rest-api-specs#1178]
As mentioned in the title, `ContainerServiceOchestratorTypes` has a misspelling: the first "r" is missing in `Orchestrator`.

The offending line:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2017-01-31/swagger/containerService.json#L298

**Comment by hyonholee** [comment]
Resolved: https://github.com/Azure/azure-rest-api-specs/pull/1238

**Comment by brendandburns** [comment]
This can be closed...
