### ISSUE TITLE
SecurityInsights: multiple usages of same-named discriminator

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#11803]
The discriminator `Scheduled` is both used in [`ScheduledAlertRule`](https://github.com/Azure/azure-rest-api-specs/blob/d50ea7233b80f662cb9e19883fb0083e653339ca/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L8705) and [`ScheduledAlertRuleTemplate`](https://github.com/Azure/azure-rest-api-specs/blob/d50ea7233b80f662cb9e19883fb0083e653339ca/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L8847).

The same problem exists for `MicrosoftSecurityIncidentCreation` and `Fusion`. The issue exists in both 2019-01-01 and 2020-01-01.

**Comment by laithhisham** [comment]
@magodo Can you please elaborate on why does having the same discriminator value on 2 separate object causes a problem?

**Comment by weidongxu-microsoft** [comment]
Seems not an issue for me. Their base type is "AlertRule" and "AlertRuleTemplate". They do not share a same polymorphism.

**Comment by magodo** [comment]
@weidongxu-microsoft, where can I find the definition of `x-ms-discriminator-value`. My understanding is that when looking for variant from base schema, we should check each schema defined in current spec and the one whose `x-ms-discriminator-value` matches the enum value defined in the `discriminator` of the base schema is the variant schema.

But it turns out in this service, we should additionally check whether there is a `oneOf` reference in the variant schema matches the base schema?

**Comment by weidongxu-microsoft** [comment]
>  we should check each schema defined in current spec and the one whose x-ms-discriminator-value matches the enum value defined in the discriminator of the base schema is the variant schema

My understanding is a bit different. Instead of `check each schema defined in current spec`, I take that we check only derivative schema (those have `allOf` directly or indirectly) to the base class. All `discriminator` and `x-ms-discriminator-value` only apply to the polymorphism hierarchy it resides in, nothing out of it.

**Comment by laithhisham** [comment]
Exactly as @weidongxu-microsoft said. I don't think that having the same discriminator value for 2 different types should cause any problem.
