### ISSUE TITLE
SaaS: a possible typo in Saa_GetResource

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-rest-api-specs#11816]
There appears to be a typo here https://github.com/Azure/azure-rest-api-specs/blob/master/specification/saas/resource-manager/Microsoft.SaaS/preview/2018-03-01-beta/saas.json#L209

From context, it seems should be `SaaS_GetResource`, not `Saa_GetResoruce` (and there is `SaaS_Delete` above).

**Comment by weidongxu-microsoft** [comment]
@diyakobo
Could you check whether this is intended or a typo of the `operationId`?

**Comment by diyakobo** [comment]
the fixing PR:
https://github.com/Azure/azure-rest-api-specs/pull/11818
