### ISSUE TITLE
Is Cosmo DB Mongo Collection compound index sorting supported?

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#11824]
Related to customer issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/9045.

@MehaKaushik May I ask the compound index sorting is supported or not ? Related to feature https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-indexing#compound-indexes-mongodb-server-version-36.

**Comment by MehaKaushik** [comment]
Hi @yupwei68, compound indexes is supported via Mongo shell but not by Resource Provider (ARM based clients - Management SDKs, REST APIs defined in azure-rest-api-specs or Azure Powershell and CLI. 

But the good news is we plan to extend the support in the near future. We should have it out in the next 4-5 months.

**Comment by yupwei68** [comment]
Thanks!
