### ISSUE TITLE
[Synapse] Duplicate definition names

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#11856]
In https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/data-plane/Microsoft.Synapse/preview/2019-06-01-preview/entityTypes/Trigger.json#L338

```json
    "BlobEventTypes": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Microsoft.Storage.BlobCreated",
          "Microsoft.Storage.BlobDeleted"
        ],
        "x-ms-enum": {
          "name": "BlobEventTypes",
          "modelAsString": true
        }
      },
      "description": "Blob event types."
    },
```

The Enum name is defined as `BlobEventTypes`, but the top level schema name is also defined as `BlobEventTypes`. We need to rename either one to resolve the conflict in AutoRest.

**Comment by yungezz** [comment]
hi @idear1203 could you pls have a look at the issue?

**Comment by idear1203** [comment]
Fixed in https://github.com/Azure/azure-rest-api-specs/pull/11864
