### ISSUE TITLE
Key Vault: Internal Server Error while creating a key

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#11893]
I am trying to create Azure Key Vault Keys via ARM API. Unfortunately, all our requests to that endpoint fail with 
Error code ServerError
Message
[ServerError (InternalServerError)] ActivityId: dc1db68d-3fe3-48ee-a8d8-f1502461cfd8, ActivityName: KeyCreate

Path: /subscriptions/(subid)/resourceGroups/(rgname)/providers/Microsoft.KeyVault/vaults/(vaultname)/keys/mykey'

A similar call to Azure KeyVault secrets succeeds.

Could you please check the mentioned activity ID and diagnose the error.

Here is a simple ARM template to repro:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
      {
        "type": "Microsoft.KeyVault/vaults/keys",
        "apiVersion": "2019-09-01",
        "name": "mykeyvault/armkey",
        "properties": {
          "kty": "RSA",
          "keyOps": ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"],
          "keySize": 2048
        }
      }
    ]
  }
```

I also opened a support ticket and will link this issue from there.

**Comment by MWL88** [comment]
I am experiencing the same issue with an almost identical ARM template:

[ServerError (InternalServerError)] ActivityId: cef1d0a9-393f-4717-8ac2-e20e03039e6c, ActivityName: KeyCreate

**Comment by adarce** [comment]
@mikhailshilkov and @MWL88 : The Azure Key Vault team recently deployed a fix for this issue. Could you try this again to see if this repros?

**Comment by mikhailshilkov** [comment]
I can confirm it worked for me today

**Comment by MWL88** [comment]
@adarce Thank you for the update, my deployments now work again.
