### ISSUE TITLE
Microsoft.KeyVault/vaults/secrets declares support for 2020-04-01-preview, but the service does not allow it

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#11929]
ARM returns the following message when attempting to PUT a `Microsoft.KeyVault/vaults/secrets` resource at version `2020-04-01-preview`:

> No registered resource provider found for location 'uksouth' and API version '2020-04-01-preview' for type 'vaults/secrets'. The supported api-versions are '2014-12-19-preview, 2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'. The supported locations are 'northcentralus, eastus, northeurope, westeurope, eastasia, southeastasia, eastus2, centralus, southcentralus, westus, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, centralindia, southindia, westindia, canadacentral, canadaeast, uksouth, ukwest, westcentralus, westus2, koreacentral, koreasouth, 
francecentral, australiacentral, uaenorth, southafricanorth, switzerlandnorth, germanywestcentral, norwayeast, eastus2euap, centraluseuap'

This version is not supported in the RP manifest. Either the Microsoft.KeyVault service should add support for it, or remove the declarations for any unsupported APIs at this version.

**Comment by anthony-c-martin** [comment]
> Hi, anthony-c-martin. Your PR has no update for 14 days and it is marked as stale PR. If no further update for over 14 days, the bot will close the PR. If you want to refresh the PR, please remove `no-recent-activity` label.

@markcowl - looks like something is up with the bot as this isn't a PR! Would you mind taking a look?

**Comment by ruowan** [comment]
> > Hi, anthony-c-martin. Your PR has no update for 14 days and it is marked as stale PR. If no further update for over 14 days, the bot will close the PR. If you want to refresh the PR, please remove `no-recent-activity` label.
> 
> @markcowl Mark Cowlishaw FTE - looks like something is up with the bot as this isn't a PR! Would you mind taking a look?

Thanks for feedback. It's a bot issues. We have fixed it.

**Comment by sebansal** [comment]
@jlichwa to help with triaging

**Comment by jlichwa** [comment]
@anthony-c-martin can you clarify. ARM returns the following message when attempting to PUT a Microsoft.KeyVault/vaults/secrets is a call to data plane with available versions: 7.0, 7.1. https://docs.microsoft.com/en-us/rest/api/keyvault/setsecret/setsecret

2020-04-01 is management plane version. With available for secrets only through ARM.

Is that makes sense?

**Comment by anthony-c-martin** [comment]
@jlichwa - this issue report is concerning management plane (ARM), not data plane.

Here the KeyVault swagger spec declares support for operations on secrets through the ARM control plane with API version 2020-04-01-preview:
https://github.com/Azure/azure-rest-api-specs/blob/220b0b884fe180430cb65069bc439c8ed1d8ec0f/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview/secrets.json#L13

The ARM control plane does not actually support this API with the declared API version.

**Comment by jlichwa** [comment]
@anthony but ARM using separate API. API you mentioned is calling data plane: PUT a Microsoft.KeyVault/vaults/secrets

**Comment by tyeth** [comment]
Hey @jlichwa any progress on this? 

Is there a running list of incomplete api versions, or should we just not use any preview API versions until they make it out of preview?

**Comment by jlichwa** [comment]
@anthony-c-martin  it seems like this issue is fixed.

**Comment by anthony-c-martin** [comment]
@jlichwa, thanks for confirming! Closing this issue.
