### ISSUE TITLE
Access AzureIaaSVMJobExtendedInfo

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-rest-api-specs#11928]
The documentation of the [API](https://docs.microsoft.com/en-us/rest/api/backup/jobdetails/get#azureiaasvmjobextendedinfo) does not describe, how how the details described under Definitions is accessed via the API.

In particular I would like to get progressPercentage, which should be accessible in AzureIaaSVMJobExtendedInfo.

Is there any way i can decorate "https://management.azure.com/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/backupJobs/{jobName}?api-version=2019-05-13" to get processProcentage or is therre another call I can use to get this information?

**Comment by pvrk** [comment]
@Agazoth : The progress percentage is currently available only for restore tasks and not to any other job type. Once you trigger a restore and track it, the percentage will be present in the API response.

**Comment by pvrk** [comment]
@Agazoth : From a documentation perspective, the API documentation framework has no "mandatory/required" column for definitions. What we can do is to update the definition of the field to clearly mention when this can be expected. Is this OK with you?

**Comment by pvrk** [comment]
@Agazoth: A gentle reminder to respond

**Comment by mepand** [comment]
@Agazoth Could you please confirm if updating the definition of the field as Kartik mentioned above would help?

**Comment by adityabalaji-msft** [comment]
Closing issue since the updated text will appear in the upcoming API release
