### ISSUE TITLE
Provide REST API for VMSS to use health probe from Application Gateway during creation

### ISSUE THREAD

**Issue by tonytangau** [Azure/azure-rest-api-specs#11969]
Due to the current API only supports LB health probes for VMSS (Rolling upgrade policy), there is no way to use Terraform to create a Rolling upgrade VMSS with Application Gateway as the frontend. See [Issue in terraform-provider-azurerm](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3190).

We would like to create VMSS with Rolling upgrade with application gateway using terraform, for example:

```terraform

resource "azurerm_application_gateway" "agw" {
  ...
  probe {
      interval            = 5
      name                = local.probe_name
      host                = "127.0.0.1"
      protocol            = "Http"
      path                = "/"
      timeout             = 20
      unhealthy_threshold = 3
  }
  ...
}

resource "azurerm_linux_virtual_machine_scale_set" "vmss" {
  ...
  upgrade_mode        = "Rolling"
  health_probe_id     = azurerm_application_gateway.agw.probe[0].id
  ...
}

```

**Comment by Drewm3** [comment]
@avirishuv, can you please work with the VMSS team to see if this feature request is already available (and just missing in documentation), or if a new addition to VMSS is needed to support the health probes from AppGateway.

Also, if a new feature is needed, then is it possible for people to use the AppHealth Extension in the interim to do rolling upgrades with an AppGateway?

**Comment by avirishuv** [comment]
Allowing customers to use Application Gateway health probe for VMSS features based on application health monitoring (including rolling upgrade) is part of our feature backlog. We do not have a specific timeframe for when this will be supported. However, in the meantime, application health extension can be used for VMSS with AppGW for application health monitoring.

**Comment by avirishuv** [comment]
hi @tonytangau As I mentioned, this feature is in the backlog for VMSS. I am moving this feature ask to user voice and closing this issue. Feel free to add any comments in user voice and/or add a vote: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/42627139-provide-rest-api-for-vmss-to-use-health-probe-from 

Thanks again for bringing this up. If you have additional questions, please reopen the issue and we'll be happy to answer.
