### ISSUE TITLE
Microsoft.KeyVault - secrets & keys missing from readme.azureresourceschema.md

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#11963]
The following file is used to generate ARM template schemas for Microsoft.KeyVault: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/readme.azureresourceschema.md

The service supports the following API versions for vaults/secrets:
* 2015-06-01
* 2016-10-01
* 2018-02-14-preview
* 2018-02-14
* 2019-09-01

The service supports the following API version for vaults/keys:
* 2019-09-01

This should unblock the following PR:
https://github.com/Azure/azure-resource-manager-schemas/pull/999

This should also address the following issue:
https://github.com/Azure/bicep/issues/1077

This is somewhat related to:
https://github.com/Azure/azure-rest-api-specs/issues/11929

**Comment by erich-wang** [comment]
@anthony-c-martin, are you from KV or ARM team? To which team I should assign this issue?

**Comment by anthony-c-martin** [comment]
I'm on the ARM team. This issue should be assigned to the KV team.
