### ISSUE TITLE
Service: Consumption. Filter parameter does not work for Grain

### ISSUE THREAD

**Issue by Jeroenvos** [Azure/azure-rest-api-specs#11982]
I am using the consumption API version 2019-10-01.
My goal is to get yearly forecast data which I can use in a custom Power BI report.
When I add $filter = Grain eq 'Yearly' both in the example as well as in ADF, it only returns Daily grain. Same when providing Monthly in the filter.

I used amongst others:
https://docs.microsoft.com/en-us/rest/api/consumption/forecasts/list

![image](https://user-images.githubusercontent.com/8928030/101345418-48ea7f00-3887-11eb-8763-9e76a7e2698e.png)
![image](https://user-images.githubusercontent.com/8928030/101345526-6fa8b580-3887-11eb-9e2f-5c0c353194e9.png)

Also, when using other filters, like usagedate, it does'nt seem to work

**Comment by Jeroenvos** [comment]
Thanks, @ms-premp! 
And the best wishes for 2021 :)

Using /providers/Microsoft.Consumption/forecasts?$filter=properties/grain eq 'Yearly'&api-version=2019-10-01 
I got a return with grain "Yearly" 
However, this number exactly equals Monthly grain. 

So it seems that when I request Yearly grain, I get Monthly grain only the text monthly replaced with yearly.
When I multiply it by 12 I also geta whole other number than in the portal UI. so it seems incorrect.

Is there something I am doing wrong?

Best regards,
Jeroen

**Comment by theelderwand** [comment]
Hi @Jeroenvos this is an older version of our API that the portal has moved away. If you are looking for the API that the portal talks to, might I point you to the forecast API that has the filtering and aggregation capabilities, you can find more details of the API here
https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage

**Comment by ramaganesan-rg** [comment]
hello @jeroenvos please let us know if there is anything that you need, in addition to the above response our team has provided.

**Comment by ramaganesan-rg** [comment]
Closing this issue  please feel free to reopen as needed.
