### ISSUE TITLE
Consumption/Forecast API (2019-10-01) $Filter not working 

### ISSUE THREAD

**Issue by Jeroenvos** [Azure/azure-rest-api-specs#12007]
I am using the consumption API version 2019-10-01.
My goal is to get yearly forecast data which I can use in a custom Power BI report.
When I add $filter = Grain eq 'Yearly' both in the example as well as in ADF, it only returns Daily grain. Same when providing Monthly in the filter.

I used amongst others:
https://docs.microsoft.com/en-us/rest/api/consumption/forecasts/list

![image](https://user-images.githubusercontent.com/8928030/101345418-48ea7f00-3887-11eb-8763-9e76a7e2698e.png)
![image](https://user-images.githubusercontent.com/8928030/101345526-6fa8b580-3887-11eb-9e2f-5c0c353194e9.png)

Also, when using other filters, like usagedate, it does'nt seem to work

**Comment by Jeroenvos** [comment]
Thanks, @akning-ms 
And the best wishes for 2021 :)

Using /providers/Microsoft.Consumption/forecasts?$filter=properties/grain eq 'Yearly'&api-version=2019-10-01 
I got a return with grain "Yearly" 
However, this number exactly equals Monthly grain. 

So it seems that when I request Yearly grain, I get Monthly grain only the text monthly replaced with yearly.
When I multiply it by 12 I also geta whole other number than in the portal UI. so it seems incorrect.

Is there something I am doing wrong?

Best regards,
Jeroen

**Comment by JaikishanRupani** [comment]
@Jeroenvos Can you share the x-ms-request-id value from the response headers?

While we look into this issue, I strongly encourage you to use the newer API that is currently being used by Azure Portal UI - https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage. 
This is being actively worked on and supports more scopes. The underlying prediction algorithms are also different for both APIs.

**Comment by Jeroenvos** [comment]
Hi, and thank you for you quick reply.
I got this version to work, that's why I used it. But I'll definitely try making the newer API work.

Here is a sample that I tried just now
date: Thu, 07 Jan 2021 11:14:15 GMT
x-ms-request-id: c351f126-732e-4314-804a-4e67897c8dfe

**Comment by JaikishanRupani** [comment]
@Jeroenvos I looked at the service logs for your request as well as the API implementation. The API actually does not support Yearly grain but has it incorrectly added it to the documentation. We apologize for confusion. We are working on fixing the documentation to accurately reflect this.

Please note that the API you are using is no longer actively under development. We have a new Forecast API that I would recommend moving onto that supports all 3 grains: https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage . Can you please try this one instead?

**Comment by Jeroenvos** [comment]
@JaikishanRupani Thanks. I'll start using the new forecast api. I see there's only daily grain there. Would there be another way to get the yearly forecast other than through the UI in the azure portal?
For example some scheduled export or something like that?

**Comment by JaikishanRupani** [comment]
@Jeroenvos Actually it does support Daily, Monthly and Yearly. Looks like another documentation bug. We will get this fixed.
For example, I tried this -
{
    "type": "ActualCost",
    "dataSet": {
        "granularity": "**Monthly**",
        "aggregation": {
            "totalCost": {
                "name": "Cost",
                "function": "Sum"
            }
        },
        "sorting": [
            {
                "direction": "ascending",
                "name": "BillingMonth"
            }
        ]
    },
    "timeframe": "Custom",
    "timePeriod": {
        "from": "2021-01-01T00:00:00+00:00",
        "to": "2021-01-31T23:59:59+00:00"
    },
    "includeActualCost": false,
    "includeFreshPartialCost": false
}

Yearly should work too

**Comment by ShilpiGautam** [comment]
I hope we answered your concern @Jeroenvos. We will be closing this now. Please let us know if you have any further questions and we will be glad to help.
