### ISSUE TITLE
Monitor Action Group Error `AadWebhookResourceNotOwnedByCaller`

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#12003]
I try to update a monitor action group by adding a secure webhook by api. It fails with error "AadWebhookResourceNotOwnedByCaller".

I could directly create an action group with a secure webhook, but the update returns error message.

1. create an action group
PUT /subscriptions/.../resourceGroups/acctestRG-201208142027443621/providers/microsoft.insights/actionGroups/acctestActionGroup-201208142027443621?api-version=2019-06-01 HTTP/1.1
{"location":"global","properties":{"groupShortName":"acctestag","enabled":true,"emailReceivers":[],"smsReceivers":[],"webhookReceivers":[{"name":"callmyapiaswell","serviceUri":"http://example.com/alert","useCommonAlertSchema":true,"useAadAuth":false,"objectId":"","identifierUri":"","tenantId":""}],"itsmReceivers":[],"azureAppPushReceivers":[],"automationRunbookReceivers":[],"voiceReceivers":[],"logicAppReceivers":[],"azureFunctionReceivers":[],"armRoleReceivers":[]},"tags":{}}

Response: 201 Created

2. Create an AAD application
POST /54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/applications?api-version=1.6 HTTP/1.1
{"displayName":"acctestspa-201208142027443621","identifierUris":["https://uri"],"availableToOtherTenants":false,"homepage":"https://acctestspa-201208142027443621","replyUrls":[],"requiredResourceAccess":[]}

Response: 200 OK

3. Update the action group by adding a secure webhook
PUT /subscriptions/.../resourceGroups/acctestRG-201208142027443621/providers/microsoft.insights/actionGroups/acctestActionGroup-201208142027443621?api-version=2019-06-01 HTTP/1.1
{"location":"global","properties":{"groupShortName":"acctestag","enabled":true,"emailReceivers":[],"smsReceivers":[],"webhookReceivers":[{"name":"callmyapiaswell","serviceUri":"http://example.com/alert","useCommonAlertSchema":true,"useAadAuth":false,"objectId":"","identifierUri":"","tenantId":""},{"name":"secureWebhook","serviceUri":"http://secureWebhook.com/alert","useCommonAlertSchema":false,"useAadAuth":true,"objectId":"282d2a01-8a36-4558-a01c-7d7e8e36f3ec","identifierUri":"https://uri","tenantId":""}],"itsmReceivers":[],"azureAppPushReceivers":[],"automationRunbookReceivers":[],"voiceReceivers":[],"logicAppReceivers":[],"azureFunctionReceivers":[],"armRoleReceivers":[]},"tags":{}}

Response:
HTTP/2.0 400 Bad Request
Content-Length: 92
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 08 Dec 2020 06:21:56 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: eb1501b9-83fd-dc77-1941-0a01d0eca0d5
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1198
X-Ms-Request-Id: 10a3ce0b-3a60-4123-a561-b3b0631d8ca8
X-Ms-Routing-Request-Id: SOUTHEASTASIA:20201208T062157Z:ed1feffa-9bfc-4f2a-b3ee-3e617041198c

{"code":"AadWebhookResourceNotOwnedByCaller","message":"AadWebhookResourceNotOwnedByCaller"}

**Comment by yupwei68** [comment]
Service team has replied me, it's because I've missed the permission assignment. Please refer details in https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups#secure-webhook

**Comment by MichaelParkerTAL** [comment]
> Service team has replied me, it's because I've missed the permission assignment. Please refer details in https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups#secure-webhook

@yupwei68 Are you able to elaborate as to how you resolved this? 
I'm having this same issue and I can't find any resources on how to resolve.

**Comment by OliPeter** [comment]
## ErrorMessage : 'AadWebhookResourceNotOwnedByCaller'

If you want to create a new ActionGroup with the Action Secure Webhook, the creator of the ActionGroup must be stored as the **Owner** of the app.

## Solution:

```powershell
# .Add ServicePrincipal as Application Owner
$payload = @{
    "@odata.id" =  "https://graph.microsoft.com/v1.0/servicePrincipals/{SPNID}  # ID of the ServicePrincipal
} | ConvertTo-Json

Invoke-AzRestMethod -Method POST -uri "https://graph.microsoft.com/v1.0/applications/{IdentityProviderID}/owners/`$ref" -Payload $payload

```
