### ISSUE TITLE
Virtual Machine Size Model (concern for few properties)

### ISSUE THREAD

**Issue by JatinKinraAis** [Azure/azure-rest-api-specs#1204]
Hi,

The current API does not provide few properties for VM Size.
Currently, 'name', 'number_of_cores', 'os_disk_size_in_mb', 'resource_disk_size_in_mb', 'memory_in_mb', 'max_data_disk_count' is being provided.

Required properties -
1 - Id
2 - Family / Class
3 - size of root disk
4 - Something similar to "size_ephemeral_disks" and "num_ephemeral_disks" in AWS.

Can you please provide us with a way to map these properties ?

Thanks - Jatin

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
