### ISSUE TITLE
Add ability to query search service statistics without

### ISSUE THREAD

**Issue by SamGRosen** [Azure/azure-rest-api-specs#12105]
Background: We are evaluating ways collect additional metrics for the azure search services.

Request: We'd like to able to query the `https://[service name].search.windows.net/servicestats` [endpoint](https://docs.microsoft.com/en-us/rest/api/searchservice/get-service-statistics) without the `api-key` for a "monitoring reader" user as the key required is admin level. Another possible solution would be giving the default permissions the action `Microsoft.Search/searchServices/listAdminKeys/action` but the former is preferable.

**Comment by brjohnstmsft** [comment]
@SamGRosen We're working on enhancing the flexibility of our security mechanism for Azure Cognitive Search, but I don't have specifics to share at this time, other than that it will address your scenario (among others).

For future service feature requests, please use [User Voice](https://feedback.azure.com/forums/263029-azure-search/suggestions/6328646-support-for-enhanced-security-including-security). The GitHub repos are mostly for client libraries, documentation, etc. and not for the service itself. We'll provide an update on that User Voice item once we have more details to share about feature scope and timing.
