### ISSUE TITLE
CostManagement - grouping by Tag not working

### ISSUE THREAD

**Issue by railton-matthew-by** [Azure/azure-rest-api-specs#12158]
According to the documentation grouping can be performed by Dimension or by Tag.  Dimension works fine but if I change to Tag then I get an error.  Am I missing anything?  Thanks,

This is my query.

```
**URL**
https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/rg1/providers/Microsoft.CostManagement/query?api-version=2019-11-01

**Body**
{
  "type": "Usage",
  "timeframe": "MonthToDate",
  "configuration": ["ResourceId"],
  "dataset": {
    "granularity": "Daily",
    "aggregation": { "totalCost": {"name": "CostUSD","function": "Sum"}},
    "grouping": [{"type": "Tag","name": "Customer"}]}
}
```

This is the error returned.

```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid query definition: Invalid dataset grouping: 'Customer'; valid values: 'ResourceGroup','ResourceGroupName','ResourceLocation','ConsumedService','ResourceType','ResourceId','MeterId','BillingMonth','MeterCategory','MeterSubcategory','Meter','AccountName','DepartmentName','SubscriptionId','SubscriptionName','ServiceName','ServiceTier','EnrollmentAccountName','BillingAccountId','ResourceGuid','BillingPeriod','InvoiceNumber','ChargeType','PublisherType','ReservationId','ReservationName','Frequency','PartNumber','CostAllocationRuleName','MarkupRuleName','PricingModel',''.\r\n\r\n (Request ID: bb6d7bb3-a109-4ed9-a97d-bb9c5c2c1f54)"
    }
}
```

**Comment by mrlepat** [comment]
Hello @railton-matthew-by 

Try changing Tag to TagKey

{
  "type": "Usage",
  "timeframe": "MonthToDate",
  "configuration": ["ResourceId"],
  "dataset": {
    "granularity": "Daily",
    "aggregation": { "totalCost": {"name": "CostUSD","function": "Sum"}},
    "grouping": [{"type": "**TagKey**","name": "Customer"}]}
}

When providing Tag, you shouldn't provide name.

{
  "type": "Usage",
  "timeframe": "MonthToDate",
  "configuration": ["ResourceId"],
  "dataset": {
    "granularity": "Daily",
    "aggregation": { "totalCost": {"name": "CostUSD","function": "Sum"}},
    "grouping": [{"type": "**Tag**"}]}
}

**Comment by railton-matthew-by** [comment]
Great! These examples work.  Thanks for the feedback.

I did not see any referent to TagKey in the API reference documentation.

**Comment by ramaganesan-rg** [comment]
yes, we will be updating the documentation. Thank you for the feedback.
