### ISSUE TITLE
Cosmos REST API

### ISSUE THREAD

**Issue by nVitius** [Azure/azure-rest-api-specs#12200]
Is there a spec that we can download for the Cosmos REST api?

I'm referring to this one: https://docs.microsoft.com/en-us/rest/api/cosmos-db/
I've started working with it recently, and it would be really useful to have a JSON spec that I could import into Postman.

**Comment by leni-msft** [comment]
yes, you can download it from this right repo: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-09-01/cosmos-db.json

**Comment by nVitius** [comment]
@leni-msft Thanks for the reply. I saw that earlier, but it doesn't seem to be the same API. The paths in the one I linked to don't seem to exist in that spec. Also, the API versions are completely different.

**Comment by nVitius** [comment]
@leni-msft Following up on this. Do you know who might have an answer for this question?

**Comment by leni-msft** [comment]
Hi @shellygms,  are you able to answer @nVitius 's question?

**Comment by MehaKaushik** [comment]
The apis listed in https://docs.microsoft.com/en-us/rest/api/cosmos-db/ are not recommended. These are the older APIs. The latest and recommended ones are listed under Resource Provider. I recommend you to use them.

**Comment by MehaKaushik** [comment]
@nVitus please reopen this issue if you have more questions.
