### ISSUE TITLE
Please provided a Swagger for Azure Data Factories

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-rest-api-specs#1221]
If the spec (swagger.json) existed for the Data Factories API, we could regenerate the .net NuGet Package and remove the old Build.Bcl and Hyak references
https://github.com/Azure/azure-sdk-for-net/issues/3031

**Comment by kirthik** [comment]
@jackmagic313 - Could you please provide an ETA on when you provide a swagger in this repo?

**Comment by hvermis** [comment]
@mikeblakeuk ADF swagger has been added to github for a while now:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datafactory/resource-manager
And we regularly release our nuget packages:
https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory.
Please note that the swagger and nuget are for ADF V2. We do not plan to add ADF V1.
