### ISSUE TITLE
REST API Doc - Microsoft.Compute "Images - Create Or Update" API requires HyperVGeneration parameter since 2019-03-01

### ISSUE THREAD

**Issue by thiruma0203** [Azure/azure-rest-api-specs#12247]
HyperVGeneration parameter was introduced since apiversion 2019-03-01.
https://github.com/Azure/azure-rest-api-specs/commit/5711e644986f30111f19a3bf51a74d25f50916ac#diff-affc8b1c36d4dad4d470903c224fb2bee3bfceaeb81f0595763410ff6d8069ce

With apiversion 2019-03-01 or newer, "Images - Create or Update API" fails with error "Required parameter 'hyperVGeneration' is missing (null).'" , when API is called without HyperVGeneration parameter. Samples in REST API reference should reflect this change.

https://docs.microsoft.com/en-us/rest/api/compute/images/createorupdate

**Comment by axayjo** [comment]
@Vaibhav-Agar can you look into this issue?

**Comment by Vaibhav-Agar** [comment]
Hi @thiruma0203,

Thanks for bringing this to our notice. The 'HyperVGenerationType' is a required filed in certain instances. The API documentation update will be published shortly to something like the below to provide clarity: 

'_Specifies the HyperVGenerationType of the VirtualMachine created from the image. If the image source is a blob, then we need the user to specify the value. If the source is managed resource like disk or snapshot, the user may need to specify the property if we can't deduce it from the source managed resource. See https://docs.microsoft.com/en-us/azure/virtual-machines/image-version-snapshot-cli for details._'

Please let us know if this helps and if you have any other questions.

**Comment by Vaibhav-Agar** [comment]
A PR has been created and just waiting for a sign-off before the changes can be published.

**Comment by PhoenixHe-msft** [comment]
@Vaibhav-Agar Please send PR targeting this repo (not your own repo)

**Comment by Vaibhav-Agar** [comment]
The desciption of the field was updated and published so closing this now. https://github.com/srvar/azure-rest-api-specs/commit/be8340e4cb44354af61869b7acd8208b389134d4
