### ISSUE TITLE
Wrong link in PR comment

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-rest-api-specs#12272]
wrong link in https://github.com/Azure/azure-rest-api-specs/pull/12265#issuecomment-752996233

```
https://aka.ma/swaggerfeedback.
```

should be `https://aka.ms/swaggerfeedback.`

**Comment by yungezz** [comment]
hi @ruowan could you pls have a look? thanks

**Comment by ruowan** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/12273

**Comment by ruowan** [comment]
Thanks for feedback. Link the PR to fix it.
