### ISSUE TITLE
SQL VM: Cannot enable auto backup

### ISSUE THREAD

**Issue by manicminer** [Azure/azure-rest-api-specs#12352]
Trying to create a SQL VM with auto backup enabled, but getting a 400 error with code `BackupScheduleTypeNotSet`, despite `backupScheduleType` being specified in the request.

## Request

PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-mssql-210108235644463787/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctest-VM-210108235644463787?api-version=2017-03-01-preview
```json
{
	"location": "westeurope",
	"properties": {
		"autoBackupSettings": {
			"enable": true,
			"enableEncryption": false,
			"retentionPeriod": 21,
			"storageAccountUrl": "https://unlikely23exst2acctpiakc.blob.core.windows.net/",
			"storageAccessKey": "mDCN2IFsCkM250yvHFRJv4UZEPJ+CPAM8q/mWDNiENdXarhuSBRD8QoDhkBVZIhUDIDEv61LQtD8oi75D4Uwng==",
			"password": "",
			"backupSystemDbs": false,
			"backupScheduleType": "Automated",
			"fullBackupFrequency": "Weekly",
			"fullBackupStartTime": 0,
			"fullBackupWindowHours": 0,
			"logBackupFrequency": 0
		},
		"serverConfigurationsManagementSettings": {
			"sqlConnectivityUpdateSettings": {
				"connectivityType": "PRIVATE",
				"port": 1433,
				"sqlAuthUpdateUserName": "",
				"sqlAuthUpdatePassword": ""
			},
			"additionalFeaturesServerConfigurations": {
				"isRServicesEnabled": false
			}
		},
		"sqlManagement": "Full",
		"sqlServerLicenseType": "PAYG",
		"virtualMachineResourceId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-mssql-210108235644463787/providers/Microsoft.Compute/virtualMachines/acctest-VM-210108235644463787"
	},
	"tags": {}
}
```

## Response

400 Bad Request
```json
{
	"error": {
		"code": "BackupScheduleTypeNotSet",
		"message": "Backup schedule type needs to be set."
	}
}
```

**Comment by NivedhaChellam** [comment]
@manicminer [Backupscheduletype ](https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/update#backupscheduletype)needs to be **manual**. Here you are configuring the automated back up with the storage account, back up frequency, schedule, backup start time and with other possible parameters, it needs to be **manual**, its not **automated**.
I noticed that you have used **Weekly** as the backup frequency, you need to pass the **daysOfWeek** parameter.  The public docs are not updated on this, we would do that shortly.  
Sample Json
     ```"autoBackupSettings": {
          "enable": true,
          "retentionPeriod": 17,
          "enableEncryption": true,
          "password": "<Password>",
          "backupScheduleType": "Manual",
          "backupSystemDbs": true,
          "storageAccountUrl": "https://teststorage.blob.core.windows.net/",
          "storageAccessKey": "<primary storage access key>",
          "fullBackupFrequency": "Weekly",
          "daysOfWeek": ["Monday","Friday"],
          "fullBackupStartTime": 6,
          "fullBackupWindowHours": 11,
          "logBackupFrequency": 10
        }```

Sample Screenshot from the portal for automate back up configuration

<img width="611" alt="Capture" src="https://user-images.githubusercontent.com/53238750/105882286-546e4280-5fba-11eb-9173-428287b4c3d3.PNG">

**Comment by manicminer** [comment]
@NivedhaChellam Thanks, from what I remember, if I specified `backupScheduleType: "Automated"` and omitted the other scheduling parameters, I got a 400 error. Is it not possible to use the Automated schedule type? I'll test this out again shortly just to make sure.

**Comment by NivedhaChellam** [comment]
@manicminer you can use automated as well, in that case you should not set the configuration parameters. with automated configuration ([Automated Backup](https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/backup-restore#automated)) all databases are backed  up to the specified storage account
**Sample json**
          ```"AutoBackupSettings": {
                "Enable": true,
                "RetentionPeriod": "30",
                "EnableEncryption": false,
                "BackupSystemDbs": "false",
                "BackupScheduleType": "Automated"
            }```

**Comment by manicminer** [comment]
@NivedhaChellam Thanks for the guidance! With trial and error I've been able to enable auto backups, although occasionally it fails to be configured. I'll close this issue as I've opened up a new issue #12818 for that.
