### ISSUE TITLE
Sql Auditing Storage account falsely returns "Enabled" when auditing with log analytics 

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#12471]
Related to customer incidents. 

1. I've created a sql server with sql auditing enabled with log analytics.
![image](https://user-images.githubusercontent.com/56525716/104871764-e6f15f00-5986-11eb-959a-8d8cca983f0a.png)

2. Then I get the sql auditing:
GET /subscriptions/.../resourceGroups/yupsql/providers/Microsoft.Sql/servers/yupsql/extendedAuditingSettings/default?api-version=2017-03-01-preview HTTP/1.1
{"properties":{"isDevopsAuditEnabled":false,"predicateExpression":"","retentionDays":0,"auditActionsAndGroups":["SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP","FAILED_DATABASE_AUTHENTICATION_GROUP","BATCH_COMPLETED_GROUP"],"isAzureMonitorTargetEnabled":true,"state":"Enabled","storageEndpoint":"","storageAccountSubscriptionId":"00000000-0000-0000-0000-000000000000"},"id":"/subscriptions/.../resourceGroups/yupsql/providers/Microsoft.Sql/servers/yupsql/extendedAuditingSettings/Default","name":"Default","type":"Microsoft.Sql/servers/extendedAuditingSettings"}

3. Then I update the sql auditing with the same payload as the previous "get" response, it returns error:
PUT /subscriptions/.../resourceGroups/yupsql/providers/Microsoft.Sql/servers/yupsql/extendedAuditingSettings/default?api-version=2017-03-01-preview HTTP/1.1

{"properties":{"state":"Enabled","storageEndpoint":"","storageAccountAccessKey":"","retentionDays":0,"isStorageSecondaryKeyInUse":false}}

Response:
{"error":{"code":"DataSecurityInvalidUserSuppliedParameter","message":"Invalid parameter 'storageEndpoint'. Value should be a blob storage endpoint (e.g. https://MyAccount.blob.core.windows.net)."}}

swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/blobAuditing.json#L63
Since this API is just for sql auditing with storage account, it should not return "Enabled" when it's not auditing with storage account.

**Comment by ericshape** [comment]
@yupwei68 Thanks for your feedback!
As an internal MSFT user, please raise one Sev 3 CRI to unblock Azure SQL DB issues. The github issues are monitored in a low freq. 
This one is from the blob auditing component. You can assign your CRI to Azure SQL DB: Data Classification, Auditing & DDM. 
@eswatad @bashahee might helps on it.

**Comment by yupwei68** [comment]
Thanks @ericshape ,I've got replies from service team, "state" means sql auditing is enabled with storage account or Azure Monitor. And "isAzureMonitorTargetEnabled" means sql auditing is enabled with Azure Monitor. We've solve it by the enhancement of sql auditing to Azure Monitor.
