### ISSUE TITLE
EdgeOrder doesn't follow the directory structure

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#12481]
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/edgeorder/resource-manager/Microsoft.EdgeOrder/2020-12-01-preview should be placed inside the `preview` folder, as are other specs in this repository

**Comment by ruowan** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/12510/files

**Comment by ruowan** [comment]
Thanks for feedback. We create a PR to fix it. For this case, we will create a valdiation rule to auto detect this case.
