### ISSUE TITLE
Microsoft.RecoveryServices is missing azureresourceschema configuration for API version 2020-02-02

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#12550]
API version 2020-02-02 was added here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.md

But is missing here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.azureresourceschema.md

**Comment by amchandn** [comment]
@jianyexi - I can see version 2020-02-02 present at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.azureresourceschema.md
but not 2020-10-01...
Can you please help me understand the issue here (is it really 2020-02-02)?

**Comment by amchandn** [comment]
@anthony-c-martin - I can see version 2020-02-02 present at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.azureresourceschema.md
but not 2020-10-01...
Can you please help me understand the issue here (is it really 2020-02-02)?

**Comment by anthony-c-martin** [comment]
Looks like this was fixed with #12853 - closing.

**Comment by amchandn** [comment]
@anthony-c-martin , I have 1 concern though -
API version 2020-10-01 was added here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.md

But is missing here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservices/resource-manager/readme.azureresourceschema.md

Should I add 2020-10-01 in readme.azureresourceschema.md?
Are we required to add new versions in both readme.md and readme.azureresourceschema.md?

**Comment by anthony-c-martin** [comment]
@amchandn - yes, maintaining both `readme.md` and `readme.azureresourceschema.md` is required going forwards.

I see 2020-10-01 was added after @leni-msft's commit. Let me know if you'd like me to raise a separate issue for that.

**Comment by amchandn** [comment]
Yeah, could you please raise an issue for adding 2020-10-01? Meanwhile, I'll start working on the fix for the same

**Comment by anthony-c-martin** [comment]
> Yeah, could you please raise an issue for adding 2020-10-01? Meanwhile, I'll start working on the fix for the same

Thanks! I've raised #13093
