### ISSUE TITLE
[arm-storage] Add /operations api into storage swagger before api-version 2017-06-01

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#1256]
All non-breaking changes are required to be backported into older version of swagger for the Azure Stack and it's compatibility. 

Please back-port non-breaking changes of https://github.com/Azure/azure-rest-api-specs/pull/1249 into previous arm-storage swaggers. 
- [ ] Adding /operation api
- [ ] Adding descriptions

Thanks

**Comment by zhusijia26** [comment]
Closed due to idle time. Please reopen if there is still question.
