### ISSUE TITLE
typo: ArmTokenParamter should be ArmTokenParameter

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#12601]
https://github.com/Azure/azure-rest-api-specs/blob/44ec11c74634f1afa5bbe0d3f2678b7f819ebf8e/specification/cognitiveservices/data-plane/LUIS/Authoring/preview/v3.0/LUIS-Authoring.json#L10751

Proposing a temporary suppression in https://github.com/Azure/azure-rest-api-specs/pull/12580, but probably good to fix before it leaves preview

**Comment by ruowan** [comment]
Thanks for your contribution. Service team will take a look.

**Comment by MahmoudYounes** [comment]
Bug is resolved. please use authoring sdk v3.2.0-preview4

**Comment by nschonni** [comment]
Thanks, rebased the suppression out of #12580
