### ISSUE TITLE
typo: LocationNameParamter should be LocationNameParameter

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#12600]
https://github.com/Azure/azure-rest-api-specs/blob/028312222e05fbca114068577aeba11cc93d99a1/specification/compute/resource-manager/Microsoft.Compute/preview/2020-09-30/sharedGallery.json#L49

Proposing a temporary suppression in https://github.com/Azure/azure-rest-api-specs/pull/12580, but probably good to fix before it leaves preview

**Comment by amjads1** [comment]
@olayemio Can you please look into this issue?

**Comment by olayemio** [comment]
This is a typo that will be fixed by the team. Changes should be reflected by Feb 26.

**Comment by nschonni** [comment]
👍 if the suppression PR lands before you fix, you can clean out the entry when it's fixed 😉

**Comment by olayemio** [comment]
There is a [PR](https://github.com/Azure/azure-rest-api-specs/pull/12442) out to fix this typo. Waiting for a sign-off for it to be published.

**Comment by olayemio** [comment]
@nschonni The PR has now completed and the typo has been fixed

**Comment by nschonni** [comment]
Awesome! Looks like it's still in the old preview version, so I'll leave the suppression just for that file
