### ISSUE TITLE
Microsoft.Network is missing azureresourceschema configuration for API versions 2020-07-01 & 2020-08-01

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#12679]
API versions 2020-07-01 & 2020-08-01 was added here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/readme.md

But is missing here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/readme.azureresourceschema.md

**Comment by leni-msft** [comment]
Hi Anthony, I created PR to update all schema files: https://github.com/Azure/azure-rest-api-specs/pull/12853

**Comment by akning-ms** [comment]
issue fixed in above PR #12853, so closed this issue
