### ISSUE TITLE
Azure VMware Solution: Missing provisioningState enum for Addon resource

### ISSUE THREAD

**Issue by sigmer** [Azure/azure-rest-api-specs#12735]
The vmware.json swagger spec for the vmware resource provider seems to have incorrect or incomplete enum values for provisioningState for the Addon resource in the `2020-07-17-preview` version.

Immediately after creating a new addon, the `provisioningState` returned from the api is `Building` but that is not a valid state according to the spec:
```json
        "provisioningState": {
          "description": "The state of the addon provisioning",
          "type": "string",
          "readOnly": true,
          "enum": [
            "Succeeded",
            "Failed",
            "Cancelled",
            "Deleting",
            "Updating"
          ],
          "x-ms-enum": {
            "name": "AddonProvisioningState",
            "modelAsString": true
          }
        }
```
cc @ctaggart

**Comment by ctaggart** [comment]
I added it to the 2021-01-01-preview API in #12762.
