### ISSUE TITLE
[Azure DNS] Batch update of record sets in DNS zone

### ISSUE THREAD

**Issue by ideahitme** [Azure/azure-rest-api-specs#1281]
Hello,

From what I found RecordSet can be updated/deleted only individually (at least using go-sdk). Is there a way to create a batch request for multiple RecordSets within a DNS zone, i.e. so that a batch request will succeed, only if change for each of the RecordSet succeeds. Otherwise no changes are applied.

Thanks,

Yerken

Initially created here: https://github.com/Azure/azure-sdk-for-go/issues/640

**Comment by salameer** [comment]
Hi @DeepakRajendranMsft,

Kindly take a look and assign to the right folks

**Comment by jtuliani** [comment]
This is not currently supported. It would have to be implemented deep at the service level. The best way to have this prioritized would be to gain community support for the idea. To do that, you should submit to [our feedback site](https://feedback.azure.com/forums/217313-networking/category/77466-domain-name-service-dns-traffic-manager).

**Comment by liumichelle** [comment]
@DeepakRajendranMsft to close this issue

**Comment by salameer** [comment]
Closing this, @ideahitme kindly submit your request to the feedback site as suggested above, and we would Love to hear more feedback from you there :)
