### ISSUE TITLE
[GraphRbac] Missing givenName / surname in the Swagger

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1282]
We got a customer question about accessing to this information using GraphRBAC (missing ins the Swagger for the `User` definition): https://github.com/Azure/azure-sdk-for-python/issues/1202#issuecomment-306008453

The customer finds out that the RestAPI actually have givenName / surname in the JSON received from ARM, but this is not defined in the Swagger (and then not available at the SDK level).

Is this possible to get someone from the GraphRBAC team to review this and PR the missing information?

Thanks!!

**Comment by olydis** [comment]
@darshanhs90 could you please review the above issue? Seems like https://github.com/Azure/azure-rest-api-specs/blob/master/arm-graphrbac/1.6/swagger/graphrbac.json#L2339 is missing two properties.

**Comment by olydis** [comment]
@darshanhs90 PING

**Comment by darshanhs90** [comment]
@olydis Are you suggesting we replace the display name with two fields first and last name?

**Comment by lmazuel** [comment]
The suggestion is to make the [User object in the Swagger](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/graphrbac/data-plane/1.6/graphrbac.json#L2468-L2503) closer to the RestAPI :). The customer found two string in the JSON that are not exposed in the Swagger: `givenName` and `surname`. Just adding these two as strings is enough, the point is not to replace anything.
But we need the GraphRBAC team to do it, we don't own GraphRBAC JSON syntax.

**Comment by lmazuel** [comment]
This is what I see when I do a GET on user:
```json
{
	"odata.metadata": "https://graph.windows.net/myaddomain.onmicrosoft.com/$metadata#directoryObjects/Microsoft.DirectoryServices.User/@Element",
	"odata.type": "Microsoft.DirectoryServices.User",
	"objectType": "User",
	"objectId": "63a1ebd5-b6a3-4aa9-a341-8da31557bd29",
	"deletionTimestamp": null,
	"accountEnabled": false,
	"signInNames": [],
	"assignedLicenses": [],
	"assignedPlans": [],
	"city": null,
	"companyName": null,
	"country": null,
	"creationType": null,
	"department": null,
	"dirSyncEnabled": null,
	"displayName": "Test  Buddy",
	"facsimileTelephoneNumber": null,
	"givenName": null,
	"immutableId": null,
	"isCompromised": null,
	"jobTitle": null,
	"lastDirSyncTime": null,
	"mail": null,
	"mailNickname": "testbuddy",
	"mobile": null,
	"onPremisesSecurityIdentifier": null,
	"otherMails": [],
	"passwordPolicies": null,
	"passwordProfile": {
		"password": null,
		"forceChangePasswordNextLogin": true,
		"enforceChangePasswordPolicy": false
	},
	"physicalDeliveryOfficeName": null,
	"postalCode": null,
	"preferredLanguage": null,
	"provisionedPlans": [],
	"provisioningErrors": [],
	"proxyAddresses": [],
	"refreshTokensValidFromDateTime": "2016-06-22T17:59:49.4889161Z",
	"sipProxyAddress": null,
	"state": null,
	"streetAddress": null,
	"surname": null,
	"telephoneNumber": null,
	"usageLocation": null,
	"userPrincipalName": "testbuddy@myaddomain.onmicrosoft.com",
	"userType": "Member"
}
```

I see indeed `givenName` and `surname`

**Comment by lmazuel** [comment]
@olydis, just talked to @amarzavery  I will take care of this myself and do a PR
