### ISSUE TITLE
Web Apps - List Function Keys Version: 2019-08-01 definition inconsistent with response

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-rest-api-specs#12889]
Testing the REST API with:

`az rest --method post --url https://management.azure.com/subscriptions/subId/resourceGroups/resourcegroupname/providers/Microsoft.Web/sites/sitename/functions/functionname/listkeys?api-version=2019-08-01`

returns the following JSON:

```json
{
  "default": "KEY"
}
```

seems to be inconsistent with the definition in this repository (and the documentation on docs.microsoft.com) as it should return a "StringDictionary" with several properties (id, kind, etc...)

Thank you

**Comment by mikhailshilkov** [comment]
I think this is the same as https://github.com/Azure/azure-rest-api-specs/issues/11401

**Comment by raych1** [comment]
Closed this issue as it's duplicated to [#11401](https://github.com/Azure/azure-rest-api-specs/issues/11401)
