### ISSUE TITLE
ARM template schema needs to be updated with Key Vault control plane swaggers

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#12880]
The ARM template used by the VSCode extension for authoring templates (as well as used by the Portal's "Export template" functionality) has very old Key Vault schemas from 2016: 2016-10-01. Please see <https://github.com/Azure/azure-resource-manager-schemas#authoring-schemas-and-submitting-a-pr> for how to update them so we get schema-based assistance for authoring templates, as well as validation.

**Comment by jlichwa** [comment]
It seems like @anthony-c-martin was faster than me. Done
