### ISSUE TITLE
models with both `allOf` and `properties` do not generate correctly

### ISSUE THREAD

**Issue by tanmaykm** [Azure/azure-rest-api-specs#1290]
Trying to generate code from the spec here: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2017-03-30/swagger/compute.json

I find that the [VirtualMachine model](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2017-03-30/swagger/compute.json#L4568-L4597) does not generate correctly for me (and few others too). It appears as though `allOf` is overwriting `properties`. When I used the tools at `editor.swagger.io` to verify, that too shows something similar.

![azurespec1](https://user-images.githubusercontent.com/1010989/26931413-19b63ff6-4c7e-11e7-8ace-104936bb808b.png)

Should `properties` be placed inside `allOf` like this?

![azurespec2](https://user-images.githubusercontent.com/1010989/26931430-24f1031a-4c7e-11e7-939a-f064587eef2f.png)

Making that change seems to get the code generator to generate code correctly for me. I am using a [custom built plugin using swagger-codegen](https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules) to generate Julia clients.

Do the specifications need a change?

I am not fully aware of the Swagger specs and could be missing something. Happy to be corrected in that case.

**Comment by olydis** [comment]
The Swagger you reference is perfectly valid and according to spec, I can not comment on what swagger-codegen or the custom built plugin does. The tools we use for code generation handle the Swagger correctly 🙂
