### ISSUE TITLE
[TA] Fix pretty check and resolve spell check for swagger version v3.1-preview.4

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#12902]
The swagger specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.1-preview.4/TextAnalytics.json reported by PrettyCheck and SpellCheck. 

Follow the steps documented below to resolve them:

https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#prettier-check
https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#spell-check

**Comment by ctufts** [comment]
This PR is not necessary. We have resolved all of these in the dev branch PR against master.

**Comment by JackTn** [comment]
@anuchandy this issue seems to have been solved and i will close it. You can reopen this if you have any problem~
