### ISSUE TITLE
Rest API Spec PR pipeline seeing Nuget Security Analysis failures

### ISSUE THREAD

**Issue by brrusino** [Azure/azure-rest-api-specs#12955]
We have an[ active PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/2906) that was previously passing all pipeline checks which, after changing a single maxLength value, is now failing in the pipeline with Nuget Security Analysis failures that seem to be blocking the checks from running:
[Pipeline Logs](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=731945&view=results)

![image](https://user-images.githubusercontent.com/44413020/107670334-7c5ed680-6c47-11eb-8d8b-a602294e0d65.png)

Can someone please advise?

**Comment by akning-ms** [comment]
Looks some bug for unified pipeline. @zhenglaizhang

**Comment by brrusino** [comment]
@zhenglaizhang Are there any updates on this? I tried kicking off another build this morning and it results in this same issue.

**Comment by zhenglaizhang** [comment]
@brrusino we have fix this in master branch, please rebase from master to update your pipeline definition.

**Comment by zhenglaizhang** [comment]
Hi @brrusino it looks like your issue is resolved and the PR is merged, I will close this PR.
