### ISSUE TITLE
"Microsoft.DBforMariaDB/servers" invalid ServerVersion enum definition

### ISSUE THREAD

**Issue by matthieume** [Azure/azure-rest-api-specs#12953]
Hello,

On all version of the specification file :
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
The server version definition use "5.6" and "5.7" as enum valid options (this is the case for Mysql), but for MariaDB server version option in Azure are : "10.3" or "10.2".

    "ServerVersion": {
      "type": "string",
      "description": "The version of a server.",
      "enum": [
        "5.6",
        "5.7"
      ],

I am not sure of how to update the specification files. But willing to help if needed.
Thanks,

**Comment by savjani** [comment]
Thanks @matthieume for reporting this. It is a bug in our end and we will fix it in next iteration (ETA for fix < 1 month)

**Comment by akning-ms** [comment]
fixed in PR13031.
