### ISSUE TITLE
ARM: Document the api to get the status of long running operation (Azure-AsyncOperation)

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-rest-api-specs#1308]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations#azure-asyncoperation-request-and-response

Add it to resources swagger.

**Comment by ravbhatnagar** [comment]
API not needed since clients will not use this. This is part of the header.

**Comment by TimLovellSmith** [comment]
@ravbhatnagar It is a header... why can't clients use it?
