### ISSUE TITLE
[MySQL] swagger plans?

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1309]
Hello!
In the Go SDK repo we received an [issue](https://github.com/Azure/azure-sdk-for-go/issues/654) for supporting MySQL. Is there a plan to get a swagger for this service?

**Comment by lmazuel** [comment]
@suna-ms to help

**Comment by Suna-MS** [comment]
The swagger is already in private repo: azure-rest-api-specs-pr/arm-rdbms. We will copy it to this public repo asap.

**Comment by tombuildsstuff** [comment]
@Suna-MS sorry to bundle on this, but could I request the `Azure DB for Postgres` Swagger gets migrated over too? Thanks :)

**Comment by tombuildsstuff** [comment]
Support for MySql has been merged in PR #1338 - I've opened PR #1391 to fix an issue with the PostgreSQL Swagger, and I'll take a look into the MySQL code next :)

**Comment by Suna-MS** [comment]
@tombuildsstuff, please use "ServerPropertiesForDefaultCreate" instead of ServerPropertiesForCreate when create a server, and don't add administratorLogin / administratorLoginPassword into "ServerPropertiesForCreate" in PR https://github.com/Azure/azure-rest-api-specs/pull/1391, it is a Abstract Class, will also be inherited by "ServerPropertiesForRestore".

**Comment by tombuildsstuff** [comment]
@Suna-MS in that case, [from the output](https://github.com/mcardosos/azure-sdk-for-go/blob/v10.2/arm/postgresql/models.go#L237) it appears the AutoRest generator doesn't support the custom Swagger method used to represent abstract classes when generating Go code?

As the classes aren't inherited, when trying that approach currently it returns a compiler error - so unfortunately that's not possible at this time :(

**Comment by Suna-MS** [comment]
@tombuildsstuff, if add the fields to ServerPropertiesForCreate as "Required" itmes, it will have impact to other SDKs such as C#, python(used for Azure CLI 2.0).  And "discriminator" is also used in many other services specs, do you know how it work for their GO SDKs? Can we ask help from autorest team to find a workaround?

**Comment by mcardosos** [comment]
Currently, the Go generator does not support `x-ms-discriminator-value`. The best way to solve this is fixing the generator.

**Comment by kirthik** [comment]
Closing this issue since mysql swagger is now merged. 
@mcardosos - Could you please open an issue on Autorest Go generator to support `x-ms-discriminator-value`. 
@tombuildsstuff - Could you please open a new issue if you run into problems with mysql swagger spec?
