### ISSUE TITLE
'restorePointInTime' in 'sqlPool' should have 'format: date-time' property

### ISSUE THREAD

**Issue by SLRXXX** [Azure/azure-rest-api-specs#13108]
I remember we have it before, so in generated SDK type for 'restorePointInTime' is` Date` in `js`.
Somehow 'format' information got lost, now in some SDK it's type goes to `string`.

**Comment by zhenglaizhang** [comment]
Hi @SLRXXX could you help give more info about which version and which RP has this issue? 
I need locate the spec, and check if its service or sdk gen issue, so that I can route to correct owner

**Comment by SLRXXX** [comment]
@zhenglaizhang 
Files are 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/resource-manager/Microsoft.Synapse/preview/2019-06-01-preview/sqlPool.json
and 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/synapse/resource-manager/Microsoft.Synapse/stable/2020-12-01/sqlPool.json

For SDK as '@azure/arm-synapse', before version 3.0.0, typeof `restorePointInTime` is `Date`. Since 3.0.0, it got `string`.
It's not a SDK gen issue because we lost the {"format": "date-time"} property for `restorePointInTime` in swagger file.
It's a little hard for me to find in which PR this property got lost.

**Comment by zhenglaizhang** [comment]
@SLRXXX thanks for the detailed info, its quite helpful, I will try to route this to synapse service team

**Comment by zhenglaizhang** [comment]
@amoghnatu can you help take a look at this or help route to the correct owner for the issue? thanks in advance!

**Comment by amoghnatu** [comment]
@zhenglaizhang Ack. 

@srinuthati can you take a look at this and fix this as part of your current swagger changes?

**Comment by srinuthati** [comment]
done added to my swagger changes here.

https://github.com/Azure/azure-rest-api-specs/pull/13070

Regards
Srinivas T

**Comment by SLRXXX** [comment]
I see it in the latest version.
Thank you for help! @srinuthati @zhenglaizhang
