### ISSUE TITLE
Microsoft.Storage is missing azureresourceschema configuration for API version 2021-01-01

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#13112]
It has been configured here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.md

But is missing here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.azureresourceschema.md

**Comment by leni-msft** [comment]
Resolved
