### ISSUE TITLE
Resource group name doesn't satisfy the constraint pattern /^[-\w\._\(\)]+$/

### ISSUE THREAD

**Issue by SumitPopat** [Azure/azure-rest-api-specs#13136]
We have created an Azure resource group from the portal, named `Instruktører` (notice the special character `ø`). When we try and perform a `GET` call using `azure-sdk-for-js` (https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/resources/arm-resources/src/operations/resourceGroups.ts#L115) on this resource group, it throws an error: 
```
(node:57737) UnhandledPromiseRejectionWarning: Error: "resourceGroupName" with value "Instruktører" should satisfy the constraint "Pattern": /^[-\w\._\(\)]+$/.
    at failValidation (/Azure/node_modules/@azure/arm-resources/node_modules/@azure/ms-rest-js/dist/msRest.node.js:461:19)
```
**Expected behaviour:**
Since the portal accepts the resource group name `Instruktører`, we'd expect the SDK to accept it as well and not throw the above error. 

Please check if the swagger definitions needs to be updated: https://github.com/Azure/azure-rest-api-specs/blob/0cc5a06b6712e644fc5d4fec5005a3c945d18a7a/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L2545

**Comment by SumitPopat** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-js/issues/13247

**Comment by zhenglaizhang** [comment]
@snaheth can you help check this or point to correct owner to help fix this? thanks!

**Comment by tjegbejimba** [comment]
Fized here https://github.com/Azure/azure-rest-api-specs/pull/13492
