### ISSUE TITLE
[EventGrid] Default value is invalid for sku

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#13167]
In the latest `2020-10-15-preview` API version, the `sku` property defines a default value "Basic": https://github.com/Azure/azure-rest-api-specs/blob/35bd110090a51263b61dd0c9f18cf512e17e8742/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-10-15-preview/EventGrid.json#L5926

This is wrong because `sku` is an object of type `ResourceSku` with a property `name`. It's the property that should have the default value.

**Comment by raych1** [comment]
@ahamad-MS , I saw you update the spec recently. Can you have a look at this issue? Thanks.

**Comment by ahamad-MS** [comment]
Thanks for reaching out and opening this issue. We will take a look and respond back.

thanks

**Comment by ahamad-MS** [comment]
The issue seems to be valid. We will track this for a quick fix. thanks for reporting this @mikhailshilkov  .. Somehow, this was not caught in swagger check tools.

**Comment by ahamad-MS** [comment]
This bug is part of the latest swagger update here: https://github.com/Azure/azure-rest-api-specs/pull/13397#pullrequestreview-612536477 .. Closing this issue as being addressed.

Thanks

**Comment by mikhailshilkov** [comment]
This issue is still present in an older API version:

- https://github.com/Azure/azure-rest-api-specs/blob/2807478a8b8f6251a031aa3f3d2f14b3325c721a/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-04-01-preview/EventGrid.json#L5751
- https://github.com/Azure/azure-rest-api-specs/blob/2807478a8b8f6251a031aa3f3d2f14b3325c721a/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2020-04-01-preview/EventGrid.json#L7726

Could you please fix it everywhere?

**Comment by raych1** [comment]
@ahamad-MS , can you please take care of fixes for other versions?

**Comment by ahamad-MS** [comment]
Yes.. We will take care of it separately. thanks

**Comment by mikhailshilkov** [comment]
What's the status here? The problem is still there... Could you please reopen the issue?
