### ISSUE TITLE
[VirtualMachineScaleSet] OSDisk changed unexpected after a PATCH on `imageReference.id`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#13164]
Original reported: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10626

PATCH /subscriptions/**REDACTED**/resourceGroups/group1/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1?api-version=2020-06-01 HTTP/1.1
Body:
```
{
  "properties": {
    "upgradePolicy": { "mode": "Manual" },
    "virtualMachineProfile": {
      "storageProfile": {
        "imageReference": {
          "id": "/subscriptions/**REDACTED/resourceGroups/group2/providers/Microsoft.Compute/images/bugimgstd2" // this is only actual change
        }
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "bugnic",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": false,
              "networkSecurityGroup": {
                "id": "/subscriptions/**REDACTED**/resourceGroups/group1/providers/Microsoft.Network/networkSecurityGroups/nsg"
              },
              "dnsSettings": { "dnsServers": [] },
              "ipConfigurations": [
                {
                  "name": "internal",
                  "properties": {
                    "subnet": {
                      "id": "/subscriptions/**REDACTED**/resourceGroups/group1/providers/Microsoft.Network/virtualNetworks/vnet/subnets/internal"
                    },
                    "primary": true,
                    "privateIPAddressVersion": "IPv4",
                    "applicationGatewayBackendAddressPools": [],
                    "applicationSecurityGroups": [],
                    "loadBalancerBackendAddressPools": [],
                    "loadBalancerInboundNatPools": []
                  }
                }
              ],
              "enableIPForwarding": false
            }
          }
        ]
      }
    }
  }
}
```
But we get an unexpected change in the osDisk:
```
"storageProfile": {
  "osDisk": {
    "osType": "Linux",
    "createOption": "FromImage",
    "caching": "None", // this changed
    "writeAcceleratorEnabled": false,
    "managedDisk": {
      "storageAccountType": "Standard_LRS" // this also changed
    },
    "diskSizeGB": 30
  },
  "imageReference": {
    "id": "/subscriptions/**REDACTED**/resourceGroups/group2/providers/Microsoft.Compute/images/bugimgstd2"
  }
}
```

**Comment by ssemyan** [comment]
I have additional repro details if needed.

**Comment by Drewm3** [comment]
@avirishuv, could you take a look at this issue. It looks like the OS disk for an existing instance should not have been updated since the upgrade mode was manual.

**Comment by avirishuv** [comment]
@ssemyan if you can share additional repro steps, that would help.
@Drewm3 based on information shared so far, it doesn't look like existing instances are impacted. It looks like other storage profile properties in the model are getting updated, even though the only change that was in the PATCH request was for image ref id. Need to investigate this further.

**Comment by ssemyan** [comment]
@avirishuv the repro steps are in the original Terraform bug: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10626

**Comment by avirishuv** [comment]
quick update: the fix is targeted for Q3 2021 for this issue. cc @jw-msft

**Comment by avirishuv** [comment]
update: the fix for this is a bit delayed, and targeted for Q4 2021.

**Comment by avirishuv** [comment]
Apologies for the delay, the fix is still in the backlog due to other priorities, will provide an update once it gets picked up.

**Comment by avirishuv** [comment]
@ArcturusZhang the fix for this issue has been rolled out. Please let us know if you have any follow up questions.

If not, could we close the issue?

**Comment by avirishuv** [comment]
Closing the issue, please feel free to reopen if you have any other questions on this topic.
