### ISSUE TITLE
Sentinel RP: empty etag should be accepted for "update" APIs

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#13203]
Currently, `etag` is required for updating most sentinel related resources. This violates the practice followed by ARM that `etag` should be optional.

Confirmed with Sentinel service team that this is currently under implementation. This issue is for the sake of tracking the progress.

**Comment by tombuildsstuff** [comment]
@magodo any news on this one?

**Comment by tombuildsstuff** [comment]
ping @[akning-ms](https://github.com/akning-ms)

**Comment by tombuildsstuff** [comment]
ping @akning-ms

**Comment by magodo** [comment]
@tombuildsstuff I just locally tested again, it appears the `etag` is now (at least for 2021-09-01-preview) optional.

**Comment by dosegal** [comment]
@magodo as far as I'm aware, `etag` is now optional for updating in all available API versions (and it's true that this wasn't the case when the issue was opened).

**Comment by magodo** [comment]
Closing this issue per @dosegal's reply.
