### ISSUE TITLE
[CosmosDB/DocumentDB] Accounts - Swagger/Validation Bug

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1324]
:wave:

When creating a ~DocumentDB~ CosmosDB Account with the Go SDK - the `maxStalenessPrefix` and `maxIntervalInSeconds` properties are required (due to property validation) but only used when the `defaultConsistencyLevel` is set to `BoundedStaleness`.

This means when creating an Account with any other consistency level, for example `Eventual`, the `maxIntervalInSeconds` and `maxStalenessPrefix` fields can be set but are ignored and instead return default values:

Here's the create request:
```
PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev/providers/Microsoft.DocumentDB/databaseAccounts/tharvey-cosmosdb?api-version=2015-04-08

{
	"location": "westeurope",
	"tags": {},
	"properties": {
		"consistencyPolicy": {
			"defaultConsistencyLevel": "Eventual",
			"maxStalenessPrefix": 200,
			"maxIntervalInSeconds": 10
		},
		"locations": [{
			"id": "tharvey-cosmosdb-westeurope",
			"locationName": "westeurope",
			"failoverPriority": 0
		}],
		"databaseAccountOfferType": "Standard",
		"ipRangeFilter": ""
	}
}
```

Which returns a 200 OK - a GET query for the Account then returns:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev/providers/Microsoft.DocumentDB/databaseAccounts/tharvey-cosmosdb?api-version=2015-04-08 HTTP/1.1

HTTP/1.1 200 Ok

{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev/providers/Microsoft.DocumentDB/databaseAccounts/tharvey-cosmosdb",
	"name": "tharvey-cosmosdb",
	"location": "West Europe",
	"type": "Microsoft.DocumentDB/databaseAccounts",
	"kind": "GlobalDocumentDB",
	"tags": {},
	"properties": {
		"provisioningState": "Succeeded",
		"documentEndpoint": "https://tharvey-cosmosdb.documents.azure.com:443/",
		"ipRangeFilter": "",
		"enableAutomaticFailover": false,
		"databaseAccountOfferType": "Standard",
		"consistencyPolicy": {
			"defaultConsistencyLevel": "Eventual",
			"maxIntervalInSeconds": 5,
			"maxStalenessPrefix": 100
		},
		"configurationOverrides": {},
		"writeLocations": [{
			"id": "tharvey-cosmosdb-westeurope",
			"locationName": "West Europe",
			"documentEndpoint": "https://tharvey-cosmosdb-westeurope.documents.azure.com:443/",
			"provisioningState": "Succeeded",
			"failoverPriority": 0
		}],
		"readLocations": [{
			"id": "tharvey-cosmosdb-westeurope",
			"locationName": "West Europe",
			"documentEndpoint": "https://tharvey-cosmosdb-westeurope.documents.azure.com:443/",
			"provisioningState": "Succeeded",
			"failoverPriority": 0
		}],
		"failoverPolicies": [{
			"id": "tharvey-cosmosdb-westeurope",
			"locationName": "West Europe",
			"failoverPriority": 0
		}]
	}
}
```

Unfortunately the validation on these fields means these fields have to be specified (as such we can't just not set them and read the default value).

Would it be possible to investigate updating the validation to allow these fields to be optional?

Thanks!

**Comment by tombuildsstuff** [comment]
@marstr @mcardosos I'm assuming this is Swagger related, and not SDK/Generator related?

**Comment by marstr** [comment]
Looking at the swagger [here](https://github.com/Azure/azure-rest-api-specs/blob/68c601d4a1fcc45f81f6bb5d2160ade962012ddf/arm-documentdb/2015-04-08/swagger/documentdb.json#L578), it seems that it's pretty clear that the validation in the Go SDK shouldn't be requiring maxStalenessPrefix or maxIntervalInSeconds at all. I'll move this issue to our repository for now.

**Comment by tombuildsstuff** [comment]
Awesome, thanks @marstr :)

**Comment by marstr** [comment]
Closing in favor of the issue above
