### ISSUE TITLE
Links on homepage doesn't work

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-rest-api-specs#13364]
Below 2 links are listed on home README.md of this repo but their target pages are showing 404.

https://github.com/Azure/adx-documentation-pr
https://github.com/Azure/adx-documentation-pr/wiki

**Comment by akning-ms** [comment]
Thanks Dingmeng, adx-documentation-pr is deprecated, the new link is: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki
we will update the readme.md.  @josefree to confirm correct link to replace

**Comment by josefree** [comment]
fixed in this pr https://github.com/Azure/azure-rest-api-specs/pull/13475
