### ISSUE TITLE
Forced Resource Group Collocation of SQL Server and SQL Databases

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#1339]
> In Azure/azure-sdk-for-go#663 @zsims says:
> The DatabasesClient supports creating databases via CreateOrUpdate however, it assumes the given resource group name is both the target resource group and the resource group where the server can be found.
> 
>As a result, it's not possible to create databases in different resource groups from the server.

As this issue is not related to Go directly, but rather a limitation of how the service can be communicated with, I'm transferring the bug to this repository. Some relevant documentation can be found here: [Cross Resource Group Deployment](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-cross-resource-group-deployment) which suggests that forcing folks to deploy all related resources into a single resource group is an anti-pattern in ARM.

**Comment by jaredmoo** [comment]
Thanks for logging this issue. The resource group contains the server, which contains the database. Therefore a database cannot be in a different resource group than its server.

**Comment by marstr** [comment]
Alright, fair enough. It may be worth documenting that somewhere. :)

Thanks for getting back to us on this. @zsims, you okay with this resolution?

**Comment by salameer** [comment]
I hope this helps on your side @zsims please reopen if required and thanks again for reaching out to us!!

**Comment by zsims** [comment]
Sorry for the delay. Thanks for the prompt follow up. Helps on our side, just rather unfortunate given SQL database pools with hundreds of databases in them.

Thanks again for the explanation everyone, especially @marstr for the cross project follow up.
