### ISSUE TITLE
Unable to deploy a Linux ElasticPremium App Service Plan in the West Europe region

### ISSUE THREAD

**Issue by MilheiroSantos** [Azure/azure-rest-api-specs#13393]
Hi!

I'm unable to deploy a Linux ElasticPremium App Service Plan in the West Europe region.

Request URL: `PUT: https://management.azure.com/subscriptions/00-000-000-00/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/test-premium-linux?api-version=2019-08-01`

Request Body:
```
{
  location: "West Europe",
  kind: "elastic",
  properties: {
    reserved: true
  },
  "sku": {
    "name": "EP1",
    "tier": "ElasticPremium",
    "size": "EP1",
    "family": "EP",
    "capacity": 1
  }
}
```

Response code: `409` 

Response body:
```
{
  "error": {
    "code": "InvalidResourceLocation",
    "message": "The resource 'test-premium-linux' already exists in location 'eastus' in resource group 'test-rg'. A resource with the same name cannot be created in location 'West Europe'. Please select a new resource name."
  }
}
```

Replacing the location field with `North Europe` (for example) works without a problem.

According to the docs, this functionality should be available on the `West Europe` region
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=functions&regions=non-regional,europe-north,europe-west

**Comment by zhenglaizhang** [comment]
Hi @MilheiroSantos based on the service response, the resource looks like already exists, please help double check it

```
The resource 'test-premium-linux' already exists in location 'eastus' in resource group 'test-rg'. A resource with the same name cannot be created in location 'West Europe'. Please select a new resource name.
```

**Comment by MilheiroSantos** [comment]
Gosh, pasted the wrong error message! 
The error I got initially was something like: `Requested features are not supported in region. Please try another region. `

I tried to recreate the error I got initially, and it seems it's working fine now. 
Thank you! Closing this issue.
