### ISSUE TITLE
ContainerServiceOSDisk maximum is incorrect

### ISSUE THREAD

**Issue by lenardchristopher** [Azure/azure-rest-api-specs#13413]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-02-01/managedClusters.json#L1829

The above link shows the incorrect value. It is listed as 1023GB, but it should actually be 2048GB.

**Comment by mikhailshilkov** [comment]
@lenardchristopher Do you have a link to the docs or anything showing the correct size?

**Comment by lenardchristopher** [comment]
@mikhailshilkov I looked through Microsoft documentation, but couldn't find anything explicitly listing disk size constraints. However, you can see the error message Azure returns in the [linked issue](https://github.com/pulumi/pulumi-azure-native/issues/663) description. Also, I personally know you can set disk size to 2048GB because I have been successfully creating node pools through Terraform and Azure CLI for over a year with that size.

**Comment by lenardchristopher** [comment]
@qike-ms @jwilder @thomas1206  @seanmck Is there a timetable for addressing this? This is soon going to be a big issue for us. Today, I created a new new pool via Azure CLI with 2048GB disk space.

**Comment by lenardchristopher** [comment]
I looked at the latest version and realized it is fixed. I'll close this bug as fixed.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-03-01/managedClusters.json#L2002
