### ISSUE TITLE
Policy assignment delete does not accept 204

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1351]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/policy/2016-12-01/swagger/policy.json#L67

Says the only valid response is 200. However, when I call this from the Python SDK, I get a 204 response (No content, which makes sense for delete) and this results in a CloudError being raised.

**Comment by ravbhatnagar** [comment]
@tfitzmac - Can you please add a 204 response to this? @TianoMS to help if needed.

**Comment by dsgouda** [comment]
@tfitzmac can you close this if its merged

**Comment by tfitzmac** [comment]
@dsgouda - I do not seem to have the option for closing this issue. Maybe @tjprescott 

204 has been added - https://docs.microsoft.com/en-us/rest/api/resources/policyassignments#PolicyAssignments_Delete

**Comment by tjprescott** [comment]
Ah, will do.
