### ISSUE TITLE
Recent composite Network spec seems to be missing a Swagger

### ISSUE THREAD

**Issue by olydis** [Azure/azure-rest-api-specs#1352]
@akshaysngupta

Was `vmssPublicIpAddress.json` dropped from https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/compositeNetworkClient.json on purpose? Looks suspicious since vmssPublicIpAddress.json was copied to the new API version folder.

See https://github.com/Azure/azure-rest-api-specs/pull/1285

**Comment by akshaysngupta** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/1353
This pull request should fix this.

**Comment by olydis** [comment]
ah perfect, thanks!

**Comment by salameer** [comment]
Resolving this as the PR has been approved
