### ISSUE TITLE
Managed Disk 

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#1361]
> As mentioned by @andyzhangx in Azure/azure-sdk-for-go#675
> I could find "diskState" in get managed disk REST api, which is used to tell whether a disk is attached or not, it's useful in the disk attach/detach scenario. Would you add this field in arm/disk-model-Properties sturc, thanks.
Below is the api spec:
https://docs.microsoft.com/en-us/rest/api/manageddisks/disks/disks-get

I double checked that the diskState property is not represented in [the relevant swagger](https://github.com/Azure/azure-rest-api-specs/blob/59f8a4ac0dd42544e08a81da7a8d0da6d259b82e/arm-compute/2017-03-30/swagger/disk.json).

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
