### ISSUE TITLE
Make Code for InstanceViewStatus an enum

### ISSUE THREAD

**Issue by charliedmcb** [Azure/azure-rest-api-specs#13617]
I am using the vmss API, and working with the PowerState codes. In order to deal with this I have created my own consts that map to all of the PowerState codes here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.powerstate?view=azure-dotnet

However, it would be nice if I could use a list of values from the API instead of defining my own.

Code location for current API:
https://github.com/Azure/azure-rest-api-specs/blob/961799e77f5e9b81208384a1c6ce3a6bc9e84a93/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L6995

On a side note: it would be nice to actually have the PowerState as a member variable inside of the following:
https://github.com/Azure/azure-rest-api-specs/blob/961799e77f5e9b81208384a1c6ce3a6bc9e84a93/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L11970
This would prevent the need to dig through the list each time to find if it is there, hunting for a match on the prefix. However, I understand if that is beyond changing at this time. Unless things were refactored in this way, it would require the enum to add codes for all of the other types of statuses as well beyond just the PowerStates.

**Comment by Vaibhav-Agar** [comment]
Hi @avirishuv can you please take a look here?

**Comment by Drewm3** [comment]
@avirishuv, could you look into this request?

**Comment by avirishuv** [comment]
hi @charliedmcb, this documentation page provides the possible values for power states of VM: https://docs.microsoft.com/en-us/azure/virtual-machines/states-billing

also, the power state is already part of the VMSS VM Instance View, it can be found under Status: https://github.com/Azure/azure-rest-api-specs/blob/961799e77f5e9b81208384a1c6ce3a6bc9e84a93/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L12017

**Comment by charliedmcb** [comment]
I was aware of this similar list here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.powerstate?view=azure-dotnet
My issue was that I needed to implement a list of values within my own code, where I was hoping there would be enums within the API, so I could simply use those values directly instead of my own that were formed by additional information. For example an issue with the documentation approach is the conflicting information: in my list the value PowerState/unknown exists, but in the documentation you sent it does not exist.

I also was aware of where to find the PowerState within the VMSS VM Instance View. From my perspective it simply seems useful to have the PowerStatus at its own field not in the statuses if you always have one, so you don't have to go digging through the values in statuses each time in order to find the PowerStatus, and preform string matching to make sure you are grabbing the PowerStatus and not one of the other statuses.

I understand if the latter change would be too much of a breaking change for the api to implement, but that would be my desired implementation where its had an enum to identify which PowerState it was. If it was not its own member variable than every other status would also need its type have an enum value as well as they share the same InstanceViewStatus struct definition. I understand if there are reasons why this would not be desired from the API implementation side, but I wanted to raise these desired changes of mine as this is the implementation that I would prefer to use.

**Comment by charliedmcb** [comment]
I added two feature requests via uservoice for this change.

Make Code for InstanceViewStatus an enum in the API:
https://feedback.azure.com/forums/216843-virtual-machines/suggestions/43092795-make-code-for-instanceviewstatus-an-enum-in-the-ap

Make PowerStatus its own member variable in VirtualMachineScaleSetVMInstanceView for the API:
https://feedback.azure.com/forums/216843-virtual-machines/suggestions/43092702-make-powerstatus-its-own-member-variable-in-virtua
