### ISSUE TITLE
arm-network/2017-06-01/swagger/vmssPublicIpAddress.json file should contain one and only one ApiVersion

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-rest-api-specs#1368]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2017-06-01/swagger/vmssPublicIpAddress.json#L219 still contains different api-version

**Comment by DeepakRajendranMsft** [comment]
Please check with @amarzavery on how to fix this, he has the context on why we did this - this way. this was the recommendation given to us. If there is a better solution than please do let us know.

**Comment by salameer** [comment]
@DeepakRajendranMsft is right, this belongs to compute and thats what it has a different version

Closing this
