### ISSUE TITLE
[Compute] API returns incorrect Status Code on Failure

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1372]
👋 

We run nightly acceptance tests against the Azure API's (via the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go)) - and this morning we had a temporary test failure coming from the CreateOrUpdate method within the Compute API's:

> * azurerm_virtual_machine.test: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="InternalDiskManagementError" Message="An internal disk management error occurred."

This call returns a `200 OK` status code - but within the body explains that the downstream request returned a `500 Internal Server Error`. This means that we need to inspect the response to be able to work out that it's safe to retry - rather than having the Azure SDK for Go automatically retry the request (via the Swagger definition).

Given this, would it not make more sense to return a `500 Internal Server Error` - and allow clients to retry automatically? If that's not desirable, would it not make more sense for Azure to retry this call internally, before exposing that to consumers?

Thanks!

**Comment by gatneil** [comment]
I'm a bit confused why I've been assigned :)

**Comment by olydis** [comment]
@gatneil Whoops missed your comment. I always assign whoever I see active in the corresponding part of this repo - since this is an issue with compute, I probably saw you ;) Always feel free to reassign to someone you think is more appropriate to deal with service related issues.

**Comment by tombuildsstuff** [comment]
ping @olydis @hyonholee - is there any update available here? :)

**Comment by tombuildsstuff** [comment]
ping @olydis @hyonholee - is there any update available here? :)

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
