### ISSUE TITLE
[Bug] Python package azure-mgmt-compute 19.0.0 misses Disks

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-rest-api-specs#13740]
azure-mgmt-compute 19.0.0 does not contain Disks resources.

https://pypi.org/project/azure-mgmt-compute/
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/disk.json

**Comment by zhenglaizhang** [comment]
@msyyc could you help take a look?

**Comment by qwordy** [comment]
@zhenglaizhang We have found the cause. Is it allowed that an API version is published and is then updated later?

**Comment by zhenglaizhang** [comment]
As discussed offline, this needs another sdk release for python to ingest in the feature update, and @qwordy will help address this.
