### ISSUE TITLE
Azure Storage Account Rest APIs not working as expected

### ISSUE THREAD

**Issue by mdurini** [Azure/azure-rest-api-specs#13754]
Hi, i'm following the [documented](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/listkeys#examples) url to get the storage keys without success

`{
    "error": {
        "code": "HttpResourceNotFound",
        "message": "The request url http://10.0.14.206:30019/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/YYYYYYYYYYYYYYYYYY/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/subscriptions/<subscriptionId>/resourceGroups/<rgName>/providers/Microsoft.Storage/storageAccounts/<storageName>/listKeys?api-version=2021-02-01 is not found."
    }
}`

Also changing the storage account or the API version i'm getting the same error. it seems that only the listkeys functionality is affected

**Comment by blueww** [comment]
@mdurini 

the [documented](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/listkeys#examples) has Uri start with "https://management.azure.com/", but I see you Uri start with "http://10.0.14.206:30019/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/YYYYYYYYYYYYYYYYYY/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/". 
Which server do you target on? Is the Uri prefix correct? Does the server you target support listKeys?

@zfchen95  ， @HimanshuChhabra 
Do you have any idea on the server issue?

**Comment by mdurini** [comment]
hello, the weird address is in the response, I used the correct address to do the request. The service principal used has enough permissions in the subscriptions, including the listkeys.

**Comment by mdurini** [comment]
hello, as I was suspecting, it was a service issue because now the same call is working as expected. You can close the issue Best regards

**Comment by ruowan** [comment]
Close this issue.

**Comment by rick20** [comment]
Hi @mdurini I have exact same issue and same response, only the ```listKeys``` that responding with resource not found. May I know what you did to fix the issue?
