### ISSUE TITLE
[Service Bus] Swagger for Service Bus Subscription Rule

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1376]
👋 

[We've had a request to add support for setting Service Bus Subscription Rule's](https://github.com/terraform-providers/terraform-provider-azurerm/issues/145). From what I can see there's currently no SDK support for this and reportedly there's no support within the AzureRM portal?

Is this functionality supported going forward, or is it deprecated? If not, is it on the roadmap to be added to the Swagger so that we're able to support this feature?

Thanks!

**Comment by tombuildsstuff** [comment]
👋🏻 @fearthecowboy @kirthik is there any update on this issue? Thanks! :)

**Comment by sacdpathade** [comment]
Please update whether this functionality is going to be added in near future or not.

**Comment by sacdpathade** [comment]
@tombuildsstuff : Please let me know if you received any other updates apart from [Azure request](https://github.com/terraform-providers/terraform-provider-azurerm/issues/145) you already mentioned.

**Comment by tombuildsstuff** [comment]
ping @fearthecowboy - is there any update available here? :)

**Comment by fearthecowboy** [comment]
Assigning to spec owner (@v-Ajnava )

**Comment by v-Ajnava** [comment]
@tombuildsstuff, Subscription Rules is added in the Swagger. and its available in the .Net SDK

**Comment by tombuildsstuff** [comment]
Confirmed this is also in the Go SDK - https://github.com/Azure/azure-sdk-for-go/blob/master/arm/servicebus/rules.go

Thanks for confirming that @v-Ajnava - closing this issue :)
