### ISSUE TITLE
Microsoft.Sql is missing azureresourceschema configuration for API version 2020-11-01-preview

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#13845]
The following file is missing configuration for API version 2020-11-01-preview:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/readme.azureresourceschema.md

It has been defined here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/readme.md

**Comment by leni-msft** [comment]
Resolved with #13862

**Comment by anthony-c-martin** [comment]
Thanks @leni-msft!
