### ISSUE TITLE
Microsoft.Compute/virtualMachines returns incorrect skipToken which results in HTTP 502 bad gateway error

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-rest-api-specs#13843]
I have around 1200+ VMs in subscription. Polling ` https://management.azure.com/subscriptions/XXXXXXX/providers/Microsoft.Compute/virtualMachines?api-version=2020-06-01` returns results in paginated view with next page provided as `nextLink` property to response. This works for first 9 qurieres where each query returns following number of results. Nine's query returns 48 results which I assume the last VMs but still provides `nextLink` which upon query returns `HTTP 502 Bad Gateway` error 
`https://management.azure.com/subscriptions/xxxxxxx/providers/Microsoft.Compute/virtualMachines?api-version=2020-06-01&%24skiptoken=DczNCoIwAADgd9l9bhNtTIiI6mBkHQo6z23mqP2wH4nEd8%2f7xzcDq77pou07gmYG5%2fbWXo%2ft%2fnm6P0ADxpR8bBAy3PKXMsqmgv9yUIVwBsXcRxG0T9rZiOqhFnWvGOSllLBigsF%2b4ARSKivZU4YJJcgHN2mpQkSdFsFFN6Ti4IzPSaFJh5T5p%2bNi1FbFHfcaTitd922JSwzxBmICluUP`
```
{
    "error": {
        "code": "ProviderError",
        "message": "Resource provider 'Microsoft.Compute' failed to return collection response for type 'virtualMachines'."
    }
}
```
Number of results each iteration returned
```
299
250
211
116
81
50
50
50
50
48
```

**Comment by avirishuv** [comment]
hi @artisticcheese , I'll look into this issue. Could you provide a couple of inputs: 
How many total VMs were there in the subscription? The above numbers add upto 1205, was that the total #of VMs, or were there more than that? 
During the polling, were there any on-going deletion operations on some of those VMs ?

**Comment by artisticcheese** [comment]
Total number of Vms are always changing due to databricks operation, so yes some Vms are being deleted all the time and it's impossible to know for sure if last operation retuned last VM or not

**Comment by artisticcheese** [comment]
This has been confirmed a bug by Microsoft and requires reregistration via `Register-AzResourceProvider -ProviderNamespace Microsoft.Compute`
