### ISSUE TITLE
[Container Service]: Add Swagger for `2017-07-01`

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1386]
👋 hey y'all

The [Azure Container Service recently announced support for the `2017-07-01` API](https://github.com/Azure/ACS/blob/master/announcements/2017-06-28-acs-uk-public-preview.md) - which solves a ton of issues we've raised previously, including:
 - #833 - Windows support
 - #1172 - Internal Clusters
 - https://github.com/terraform-providers/terraform-provider-azurerm/issues/79 - Tearing down Azure ACS resource does not tear down resource group
 - https://github.com/terraform-providers/terraform-provider-azurerm/issues/45 - Multiple Agent Pools

Would it be possible to add the Swagger file associated with this API version?

Thanks!

**Comment by jhendrixMSFT** [comment]
@colemickens can you please follow up on this (I believe this is your team, let me know if I got it wrong)?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT @kirthik 👋🏻 given that @colemickens no longer works at Microsoft, would it be possible to re-assign this to someone else on the Container Service team? Thanks! :)

**Comment by kirthik** [comment]
@rjtsdl - Could you please provide an ETA?

**Comment by rjtsdl** [comment]
@Krithik and all,

The swagger change for 2017-07-01 version is in, but not used to build client sdk yet.
The reason is, ACS is migrating to a new code base. The timeline should be around 2 months from now. We should be able to open this api version 2017-07-01 globally right after that.

Btw, there is really no 2017-06-28, it is 2017-07-01. :) @kirthik, could you help to update the issue title?

**Comment by tombuildsstuff** [comment]
@rjtsdl sorry I missed this; thanks for clarifying that - I've updated the title :)


In Terraform we use the API to provision Container Service clusters, as such we're unable to make use of the CLI suggestion - but thanks anyway!

As such - I'll set a reminder to check this in mid-November - but would it be possible to also post here if it's deployed before then? :)

Thanks!

**Comment by rjtsdl** [comment]
@tombuilsstuff sure.

Once it is deployed, I would definitely want to resolve this. I will post here.

**Comment by tombuildsstuff** [comment]
Hey @rjtsdl 

Just checking back in here - I've taken a look in the Swagger repository but [I can't see the updated Swagger Spec in Master](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/compute/resource-manager/Microsoft.ContainerService)? Is there an updated timeline for resolving this?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @rjtsdl - is there any update available here? :)

**Comment by rjtsdl** [comment]
@anhowe see if there is something we can share about migration plan. Thx

**Comment by mboersma** [comment]
I think this issue will be closed by #1956.
