### ISSUE TITLE
API definition update for VM Custom Image

### ISSUE THREAD

**Issue by HarshitaSingh-MSFT** [Azure/azure-rest-api-specs#13934]
It is regarding [Windows VM ARM deployment cannot use Shared Image Gallery and version 'latest'](https://docs.microsoft.com/en-us/answers/questions/308419/index.html). For custom images, `version `value `latest `does not work , instead the Id should be as follows:

`"/subscriptions/subID/resourceGroups/rgName/providers/Microsoft.Compute/galleries/galleryName/images/imageName/versions/versionNumber"`

**Comment by HarshitaSingh-MSFT** [comment]
@zhenglaizhang , any updates on this?

**Comment by axayjo** [comment]
@olayemio can you please take a look at this issue?

**Comment by HarshitaSingh-MSFT** [comment]
Any updates on this please?

**Comment by olayemio** [comment]
@HarshitaSingh-MSFT I am following up on this. We plan to change the _Value_ of the `id` field to: 
```This property allows you to specify the id of a custom image from the Shared Image Gallery. 
The ARM resource ID is in the form: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{imageName}/versions/{versionNumber}

To always use the ‘latest’ version, use the ARM resource ID in the form: 
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{imageName}````

**Comment by HarshitaSingh-MSFT** [comment]
Please keep me posted. Thanks!

**Comment by HarshitaSingh-MSFT** [comment]
@olayemio , can you please share a work item created for this resolution please?

**Comment by olayemio** [comment]
Here is the work item: https://msazure.visualstudio.com/One/_workitems/edit/9798968

**Comment by olayemio** [comment]
We are targeting to have this roll out by end of August

**Comment by olayemio** [comment]
We have had to push the rollout of the fix to November

**Comment by Drewm3** [comment]
This is still tracking for availability at the end of November.

**Comment by Drewm3** [comment]
This has been deployed. To use latest follow the documentation from [Create or Update VMs:](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update)

`Please do not use field 'version' for gallery image deployment, gallery image should always use 'id' field for deployment, to use 'latest' version of gallery image, just set /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{imageName}' in the 'id' field without version input.`
