### ISSUE TITLE
[KeyVault] Managment API Version 2016-10-01 removes "all" from valid list of permissions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1394]
In API version 2015-06-01, these each had "all" as a valid option:

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L298

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L310

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L322

In the latest, these values have been removed:

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2016-10-01/swagger/keyvault.json#L405

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2016-10-01/swagger/keyvault.json#L417

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2016-10-01/swagger/keyvault.json#L429

This has resulted in breaking changes in downstream tools.  See: https://github.com/Azure/azure-cli/issues/3970

Is this value no longer accepted by the server in the new API version or is this simply an oversight?

**Comment by schaabs** [comment]
@tjprescott The "all" permission was intentionally removed in this API version when we added the purge permission.  This was to avoid users unintentionally assigning the purge permission to users, and force them to be explicit.

**Comment by tjprescott** [comment]
Sounds reasonable.
