### ISSUE TITLE
define two same parameters and one of them is not used

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#14020]
In Swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azuredata/resource-manager/Microsoft.AzureData/preview/2019-07-24-preview/azuredata.json#L1171-L1177 and https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azuredata/resource-manager/Microsoft.AzureData/preview/2019-07-24-preview/azuredata.json#L1201-L1208, `subscriptionId` is defined twice and one of them is not used, and the unused one should be removed. 
There are also other parameters having the same issue.

**Comment by jianyexi** [comment]
@rajmusuku  who changed this swagger last time

**Comment by ilayrn** [comment]
Adding @rajmusuku, @jorgbaca who edited the swagger file recently.
