### ISSUE TITLE
Web: SiteAuthSettingsV2 subtypes have invalid shape

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#14034]
For example, the definition of `AuthPlatform` has an extra `properties` property under `properties`: https://github.com/Azure/azure-rest-api-specs/blob/5047dfdf585969892ac035ffdfbc57623f0bf1c5/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L21065-L21089

```json
"AuthPlatform": {
      "type": "object",
      "properties": {
        "properties": {
          "description": "AuthPlatform resource specific properties",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "runtimeVersion": {
              "type": "string"
            },
            "configFilePath": {
              "type": "string"
            }
          },
          "x-ms-client-flatten": true
        }
      }
    },
```

Note three layers of `properties` above. The same applies to [`GlobalValidation`](https://github.com/Azure/azure-rest-api-specs/blob/5047dfdf585969892ac035ffdfbc57623f0bf1c5/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L22616-L22656), [`IdentityProviders`](https://github.com/Azure/azure-rest-api-specs/blob/5047dfdf585969892ac035ffdfbc57623f0bf1c5/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L22907-L22917), etc.

As a result, the specification suggests the request should be something like

```
{
  "properties": {
    "globalValidation":{
      "properties":{
        "requireAuthentication":true,
        "unauthenticatedClientAction":"Return401"
      }
    },
    "identityProviders":{
      "properties":{
        "azureActiveDirectory":{
          "properties":{
            "enabled":true,
            "registration":{
               "properties":{
                 "clientId":"88",
                 "clientSecretSettingName":"MICROSOFT_PROVIDER_AUTHENTICATION_SECRET",
                 "openIdIssuer":"https://sts.windows.net/-f20a--bc84-/v2.0"
                }
              }
            }
          }
       }
     },
     "login":{
       "properties":{
         "tokenStore":{
           "properties":{
             "enabled":true,
             "tokenRefreshExtensionHours":72
          }
        }
      }
    }
  }
}
```

which is wrong. Based on an example of an ARM template it should be:

![image](https://user-images.githubusercontent.com/1454008/115423216-ec687a80-a1fd-11eb-867f-939d1bac4211.png)

**Comment by jkonecki-techfabric** [comment]
Hi @leni-msft , is anyone looking into this issue? I'm yet another user that run into this very problem - we cannot configure Identity integration for a dozen websites.

**Comment by leni-msft** [comment]
hi @petrpod, would you be able to take a look at this issue or route to correct person? 

BTW, the issue is also detected in Swagger KPIs: https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=17644B59-D1E5-4D35-B7A1-6DA69FB4378B
cc. @josefree @akning-ms

**Comment by Petersen-E** [comment]
Hey everyone, are there any updates on this issue?

**Comment by dviry** [comment]
any news? This affects other downstream products (Pulumi)...

**Comment by leni-msft** [comment]
@Azure/cxp any chance to help route to service team?

**Comment by navba-MSFT** [comment]
Removing the CXP attention label and adding Service team to look into this and provide an update.

**Comment by dviry** [comment]
Any updates from the Service team?

**Comment by mikhailshilkov** [comment]
I believe this was fixed by https://github.com/Azure/azure-rest-api-specs/pull/15283 see https://github.com/Azure/azure-rest-api-specs/blob/0c4762d037f0d00d4e384add4e3d7200a2993b2c/specification/web/resource-manager/Microsoft.Web/stable/2020-12-01/WebApps.json#L21082-L21099
