### ISSUE TITLE
Cosmosdb enum type case changes from 2020-04-01 to 2021-01-15

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#14051]
1. "indexMode" in 2020-04-01 is 
"enum": [
            "Consistent",
            "Lazy",
            "None"
          ],
in 2021-01-15 becomes:
"enum": [
            "consistent",
            "lazy",
            "none"
          ],
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L6934 

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-01-15/cosmos-db.json#L7108

2. "order" in 2020-04-01 is:
 "enum": [
            "Ascending",
            "Descending"
          ],

in 2021-01-15 becomes:
 "enum": [
            "ascending",
            "descending"
          ],
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L7059 

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-01-15/cosmos-db.json#L7233

**Comment by MehaKaushik** [comment]
Thanks for bringing this up. This change was made to match what our service actually returns. Unfortunately, our swagger documented it incorrectly earlier and now we have fixed it. 
The original issue which brought this into light is here https://github.com/Azure/azure-rest-api-specs/issues/11222
