### ISSUE TITLE
AVS needs to disable correlation-id in Terraform acctest

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#14086]
In terraform acctest, the create and the delete operations shares the same correlation-id in their request headers. In this scenario, the delete polling will return the response of the create (which shows succeeded), but on fact, the delete operation will not triggered.

**Comment by cataggar** [comment]
Requests with the same `x-ms-correlation-request-id` were incorrectly handled. A fix will begin rolling out soon. ([internal pull request](https://msazure.visualstudio.com/One/_git/Azure-Dedicated-AVS/pullrequest/6946227)).

**Comment by tombuildsstuff** [comment]
@catagger is there a timeline for when the rollout is complete?
