### ISSUE TITLE
Microsoft.Subscription/aliases: subscription in the Enrollment Account is not created using the latest API - User is not authorized to create subscriptions on this enrollment account

### ISSUE THREAD

**Issue by ewakost** [Azure/azure-rest-api-specs#14093]
I want to create a subscription using API in the Enrollment Account as a service principal with Owner permission on the Enrollment Account. When using the latest API there is an error "User is not authorized to create subscriptions on this enrollment account". 

### Steps
1. You need to have an Enrollment Account in Enterprise Agreement. 
2. Create a service principal.
3. As a user with Owner permission on the Enrollment Account and grant to the service principal Owner permission on the Enrollment Account
```
PUT https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/<enrollmentAccountObjectId>/providers/Microsoft.Authorization/roleAssignments/<roleAssignmentGuid>?api-version=2015-07-01
```
```
{
  "properties": {
    "roleDefinitionId": "/providers/Microsoft.Billing/enrollmentAccounts/providers/Microsoft.Authorization/roleDefinitions/<ownerRoleDefinitionId>",
    "principalId": "<userObjectId>"
  }
}
```
4. Use the [latest api](https://docs.microsoft.com/pl-pl/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest) to create a subscription
```
PUT  https://management.azure.com/providers/Microsoft.Subscription/aliases/sampleAlias?api-version=2020-09-01 
```
with body:
```json
{
  "properties": {
        "billingScope": "/providers/Microsoft.Billing/BillingAccounts/<billingAccount>/enrollmentAccounts/<enrollmentAccount>",
        "DisplayName": "", 
        "Workload": "Production"
  }
}
```

### Expected behaviors
Subscription is created. 

### Actual behavior
```json
{
    "error": {
        "code": "UserNotAuthorized",
        "message": "User is not authorized to create subscriptions on this enrollment account"
    },
    "code": "UserNotAuthorized",
    "message": "User is not authorized to create subscriptions on this enrollment account"
}
```

### Using preview API
When using [preview API](https://docs.microsoft.com/pl-pl/azure/cost-management-billing/manage/programmatically-create-subscription-preview?tabs=rest) using the same service principal subscription is created. 
```
POST https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/<enrollmentAccountObjectId>/providers/Microsoft.Subscription/createSubscription?api-version=2018-03-01-preview
```

```json
{
  "displayName": "Dev Team Subscription",
  "offerType": "MS-AZR-0017P",
  "owners": [
    {
      "objectId": "<userObjectId>"
    },
    {
      "objectId": "<servicePrincipalObjectId>"
    }
  ]
}
```

**Comment by ewakost** [comment]
Here is similar issue: https://github.com/Azure/azure-powershell/issues/13405

**Comment by jonashoye** [comment]
We are facing the excact same issue (using terraform and the powershell/Azure CLI commands).
How do we get around this? Everytime we try to deploy a new subscription we get a: "User is not authorized to create subscriptions on this enrollment account" even though the user/SPN is owner on the enrollment account.

**Comment by jonashoye** [comment]
@ewakost you need to grant your service principal SubscriptionCreator permissions in order to get this to work. This needs to be done from an account with EA admin permissions. I followed these guides to do it (has to be done directly to the API, no GUI or PS/CLI modules available for doing it.
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/assign-roles-azure-service-principals#find-your-spn-and-tenant-id
https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put

**Comment by ramaganesan-rg** [comment]
Summary:  Microsoft.Subscription api is checking on the scope supplied on the request. However, the user assigned the permissions on different scope. Then, clearly this is user error.

Right documentation link to provide permissions at right scope: 
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/assign-roles-azure-service-principals#find-your-spn-and-tenant-id
https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put

**Comment by ewakost** [comment]
The issue was solved by Microsoft support, there was a problem in missing rights on the Enrollment Account by Account Owners.
