### ISSUE TITLE
id is missed in response

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#14126]
in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/extensions.json#L393-L405 and , property `id` is missed in response, which should be required in every resource.

**Comment by aim-for-better** [comment]
Checking

**Comment by aim-for-better** [comment]
@dw511214992  Our backend does not return the property `id`, the swagger spec is correct.
