### ISSUE TITLE
Update available SKUs for CognitiveServices->Text Analytics

### ISSUE THREAD

**Issue by jongio** [Azure/azure-rest-api-specs#14180]
According to https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-call-api?tabs=synchronous#change-your-pricing-tier we now only have `S` sku.

The REST API specs need to be updated.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/examples/CheckSkuAvailability.json

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/examples/GetSkus.json

azsdke2e
azsdke2e2

**Comment by zhenglaizhang** [comment]
@yangyuan could you help take a look or help route to the correct people to help on this? thanks in advance!

**Comment by assafi** [comment]
Service team here - ACK

**Comment by suhas92** [comment]
This issue is resolved now, the PR fixing the SKU is now merged.
