### ISSUE TITLE
Resource group name fails common-types pattern when creating resources

### ISSUE THREAD

**Issue by arwong** [Azure/azure-rest-api-specs#14208]
Creating a Microsoft.Bing resource fails for existing resource groups with special characters in the name, such as Japanese 西日本, due to pattern validation on the resource group name.

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Pattern","message":"String does not match pattern ^[-\\w\\._\\(\\)]+$: 西日本. Paths in payload: '.path.resourceGroupName'"}]}
```

It is using the common ResourceGroupNameParameter which has that pattern:
https://github.com/Azure/azure-rest-api-specs/blob/c2ea3a3ccd14293b4bd1d17e684ef9129f0dc604/specification/common-types/resource-management/v1/types.json#L553

Note that this is the same problematic regex as in #13136 but in a different file.

**Comment by tjegbejimba** [comment]
Fix has been merged
