### ISSUE TITLE
CI for linter validation would run on the wrong files, if default tag in readme.md does not include the files changed in the PR

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#1424]
If there's no default tag in readme.md file, CI doesn't run linter on files in PR.
Here's a case https://travis-ci.org/Azure/azure-rest-api-specs/jobs/253710677#L1311
Executing: autorest --azure-validator specification/datalake-analytics/data-plane/readme.md --message-format=json
**Error: No input files provided.**

Or if the file that's changed is not included in the default tag, the validation would not run on the files that are being changed. 
How would CI know which tag to pass to autorest in order to cover the files changed in the PR?
@vishrutshah, @salameer @olydis @fearthecowboy
FYI - @dsgouda 

Extract of readme.md file (for the case mentioned above):

# DataLakeAnalytics
    
> see https://aka.ms/autorest

This is the AutoRest configuration file for DataLakeAnalytics.

---
## Getting Started 
To build the SDK for DataLakeAnalytics, simply [Install AutoRest](https://aka.ms/autorest/install) and in this folder, run:

> `autorest`

To see additional help and options, run:

> `autorest --help`
---

### Basic Information 
These are the global settings for the DataLakeAnalytics API.

``` yaml
openapi-type: data-plane
```

``` yaml $(package-catalog)
tag: package-catalog-2016-11
```

``` yaml $(package-job)
tag: package-job-2016-11
```

### Tag: package-catalog-2016-11

These settings apply only when `--tag=package-catalog-2016-11` is specified on the command line.

``` yaml $(tag) == 'package-catalog-2016-11'
input-file:
- Microsoft.DataLakeAnalytics/2016-11-01/catalog.json
```

**Comment by vishrutshah** [comment]
This is interesting...looks like somehow we need to know which files are being changed and then map them to the tag inside the config. @olydis Do you have any thoughts around this?

**Comment by dsgouda** [comment]
Talked to @Garrett Serack<mailto:garretts@microsoft.com> and @Johannes Bader<mailto:jobader@microsoft.com> about this and we may have to modify the CI scripts so that they pick up all the tags within a .md file when running the validation rules. This would ensure we have run the validation rules against all possible combinations.
-Deepak

**Comment by veronicagg** [comment]
Running on all tags may take time and cause confusion, if we were ok with the time it takes, we may need to filter some output in a good way, so there's not a lot of noise for authors and reviewers. I haven't come up with a good solution, but it would be good to brainstorm some options.

**Comment by vishrutshah** [comment]
@fearthecowboy @olydis I was thinking in the direction where we can extract the part of autorest that understand the README.md file. If we can extract hat part then i think for CI we can leverage it to ask "File X belong to which tag?" and then run only that tag because otherwise I am bit worries about the noise. 

Moreover, that module can help in many other places in CI as well. 

Thoughts?

**Comment by fearthecowboy** [comment]
@vishrutshah that's coming -- we'll be building a package for that soon. 

@veronicagg -- the messages are scoped to the file that they are in, so it should be a trivial operation to filter to just the files that are actually in the changed list.

**Comment by veronicagg** [comment]
@fearthecowboy ok, @dsgouda is there a way we can extract all the tags within the .md file to try this out?

**Comment by dsgouda** [comment]
Yes, discussed this with @fearthecowboy, we may be able to extract all the tags within a Readme.md, I can start looking into it if it is high pri

**Comment by veronicagg** [comment]
@dsgouda that it'd be great, yes, it's high pri, as it provides potentially wrong results for CI validation.

**Comment by dsgouda** [comment]
Addressed in the merged PR
