### ISSUE TITLE
[Compute] securityType has only one enum value and modelAsString is false

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-rest-api-specs#14305]
**Problem**
I got a problem when invoking get method of VMSS in Python SDK. It also applies to VM.
`securityType` has only one enum value in swagger definition.
```
        "securityType": {
          "type": "string",
          "description": "Specifies the SecurityType of the virtual machine. It is set as TrustedLaunch to enable UefiSettings. <br><br> Default: UefiSettings will not be enabled unless this property is set as TrustedLaunch.",
          "enum": [
            "TrustedLaunch"
          ],
          "x-ms-enum": {
            "name": "SecurityTypes",
            "modelAsString": false
          }
        }
```
Python code
```
vmss = client.virtual_machine_scale_sets.get(resource_group_name, name)
```
The value of securityProfile in HTTP response according to logs is
```
      "securityProfile": {
        "encryptionAtHost": true
      }
```
However, vmss.virtual_machine_profile.security_profile.security_type evaluates to 'TrustedLaunch'. Then it causes an error in subsequent statements.

`security_type` is a constant in Python SDK.
https://github.com/Azure/azure-sdk-for-python/blob/b5cb735efec7525bc3e2f83ee7094ea4626ac686/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_12_01/models/_models_py3.py#L5706
```
security_type = "TrustedLaunch"
```

**Expected behavior**
Set ModelAsString=True so that Python SDK will not always set it to `TrustedLaunch`.

My requirement is that Python SDK can work. I read the swagger and relevant document again. I don't think the current swagger definition is wrong. Setting it to true should be able to fix the Python SDK issue. But even it is false, Python SDK should not treat it as a constant since it is not marked required in swagger. Either updating swagger or fixing Python SDK can solve customer's issue in Azure CLI.

**Comment by amjads1** [comment]
Looking into the issue

**Comment by avirishuv** [comment]
checking this, will provide update here after investigation.

**Comment by yungezz** [comment]
there're IcM related to it https://portal.microsofticm.com/imp/v3/incidents/details/238804462/home

**Comment by avirishuv** [comment]
quick update: a fix is currently in progress, will provide an update here once it gets rolled out.

**Comment by Sandido** [comment]
The fix has been rolled out to: https://pypi.org/project/azure-mgmt-compute/22.1.0/

**Comment by zhoxing-ms** [comment]
This issue has been solved by PR https://github.com/Azure/azure-cli/pull/18788, so I close it
