### ISSUE TITLE
[Event Hubs] Event Hubs Operations - List 2021-01-01-preview API returns 404

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-rest-api-specs#14324]
[Event Hubs Operations - List 2021-01-01-preview](https://docs.microsoft.com/en-us/rest/api/eventhub/preview/operations/list) API returns 404:

```http
GET https://management.azure.com/providers/Microsoft.EventHub/operations?api-version=2021-01-01-preview

{"error":{"code":"InvalidResourceType","message":"The resource type 'operations' could not be found in the namespace 'Microsoft.EventHub' for api version '2021-01-01-preview'. The supported api-versions are '2014-09-01,2015-08-01,2017-04-01'."}}
```

**Comment by Saglodha** [comment]
@jiash, closing this issue since Operations is supported in latest api-version : https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2021-11-01/operations.json , please feel free to reach out in case of additional queries
