### ISSUE TITLE
App Platform: Default value is invalid for temporaryDisk

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#14432]
In the latest `2020-07-01` API version, the `temporaryDisk` property defines a default value "/tmp": 

https://github.com/Azure/azure-rest-api-specs/blob/f15b4f3299df66c755156aaea2c3f0c64f1840bb/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2020-07-01/appplatform.json#L3420-L3423

This is wrong because `temporaryDisk` is an object of type `TemporaryDisk` with a property `mountPath`. It's the property that should have the default value.

The issue is introduced in https://github.com/Azure/azure-rest-api-specs/pull/13927

**Comment by ruowan** [comment]
Thanks for feedback. @gavinfish has fixed the issue.
