### ISSUE TITLE
compute VirtualMachines_ListAll OBJECT_MISSING_REQUIRED_PROPERTY

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-rest-api-specs#14459]
The latest specs for compute #14223 #12334 have Swagger correctness bugs that break deserialization with the Azure SDK for Rust https://github.com/Azure/azure-sdk-for-rust/issues/54. In this case, it looks to be a bug in the Swagger spec. The API does not send back the [required location.](https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=55599149-e6d9-4f23-b316-1835b2c385f4). The definition should probably be `SubResourceReadOnly` instead of `Resource`. See #14458.

**Comment by Vaibhav-Agar** [comment]
@avirishuv can you please have a look?

**Comment by avirishuv** [comment]
Following up to investigate this.

**Comment by avirishuv** [comment]
quick update: this is added to the backlog for bugfix, will provide an update here when it gets picked up.

**Comment by avirishuv** [comment]
fix rollout is yet to be completed for this issue.

**Comment by cataggar** [comment]
I'm able to reproduce the api-version 2021-11-01. I'll try to break down the problem a bit more.  The operation `VirtualMachines_ListAll` returns a list of `VirtualMachine` definitions.

https://github.com/Azure/azure-rest-api-specs/blob/f635d0ffb31308098993e02cc1ab1a83db6bb585/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json#L13880-L13897

Each `VirtualMachine` has a `resources` element that contains an array of `VirtualMachineExtensionImage`:
https://github.com/Azure/azure-rest-api-specs/blob/f635d0ffb31308098993e02cc1ab1a83db6bb585/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json#L11089-L11106

Use your favorite tool or SDK to list VMs. An example request is
GET /subscriptions/7f1fae41-7708-4fa4-89b3-f6552cad2fc1/providers/Microsoft.Compute/virtualMachines?api-version=2021-11-01

One of the `resources` starts off like this:
``` json
      "resources": [
        {
          "id": "/subscriptions/7f1fae41-7708-4fa4-89b3-f6552cad2fc1/resourceGroups/AAGILLCS/providers/Microsoft.Compute/virtualMachines/tnt42-mgmt-p01-eastus2-incumbentVm/extensions/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent"
        },
        {
          "id": "/subscriptions/7f1fae41-7708-4fa4-89b3-f6552cad2fc1/resourceGroups/AAGILLCS/providers/Microsoft.Compute/virtualMachines/tnt42-mgmt-p01-eastus2-incumbentVm/extensions/Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent"
        }
```

Notice that it only includes the `id` field. That does not match this definition:

``` json
    "Resource": {
      "description": "The Resource model definition.",
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Resource Id"
        },
        "name": {
          "readOnly": true,
          "type": "string",
          "description": "Resource name"
        },
        "type": {
          "readOnly": true,
          "type": "string",
          "description": "Resource type"
        },
        "location": {
          "type": "string",
          "description": "Resource location"
        },
        "tags": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Resource tags"
        }
      },
      "required": [
        "location"
      ],
      "x-ms-azure-resource": true
    },
```

A `location` field is required for a `Resource`. I think the implementation actually matches a `SubResourceReadOnly`:

``` json
    "SubResourceReadOnly": {
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Resource Id"
        }
      },
      "x-ms-azure-resource": true
    },
```

**Comment by grizzlytheodore** [comment]
Assigned myself this, as I am taking ownership of this issue

**Comment by grizzlytheodore** [comment]
@cataggar  thank you for the comment and attention.

Changing from Resource to SubResourceReadOnly will remove name, type, location, and tags property. 
However, a VMExtension object has those properties inherently from the backend. 
Utilizing PowerShell cmdlet, if I do:

`PS C:\Users\thchan> Get-AzVMExtension -ResourceGroupName theo_test -VMName vmsdk

ResourceGroupName       : theo_test
VMName                  : vmsdk
Name                    : Microsoft.Azure.Geneva.GenevaMonitoring
Location                : eastus2
Etag                    : null
Publisher               : Microsoft.Azure.Geneva
ExtensionType           : GenevaMonitoring
TypeHandlerVersion      : 2.0
Id                      : /subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_test/providers/Micros
                          oft.Compute/virtualMachines/VmSdk/extensions/Microsoft.Azure.Geneva.GenevaMonitoring
PublicSettings          : {}
ProtectedSettings       :
ProvisioningState       : Succeeded
Statuses                :
SubStatuses             :
AutoUpgradeMinorVersion : True
ForceUpdateTag          :
EnableAutomaticUpgrade  : True

ResourceGroupName       : theo_test
VMName                  : vmsdk
Name                    : Microsoft.Azure.Security.AntimalwareSignature.AntimalwareConfiguration
Location                : eastus2
Etag                    : null
Publisher               : Microsoft.Azure.Security.AntimalwareSignature
ExtensionType           : AntimalwareConfiguration
TypeHandlerVersion      : 2.0
Id                      : /subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_test/providers/Micros
                          oft.Compute/virtualMachines/VmSdk/extensions/Microsoft.Azure.Security.AntimalwareSignature.An
                          timalwareConfiguration
PublicSettings          : {}
ProtectedSettings       :
ProvisioningState       : Succeeded
Statuses                :
SubStatuses             :
AutoUpgradeMinorVersion : True
ForceUpdateTag          :
EnableAutomaticUpgrade  : True`

You can see them present. 


I am exploring another solution:  creating a new object called "ResouceWithOptionalLocation" which has the same properties but without having location tagged as 'required'. You can see my change '[here](https://github.com/Azure/azure-rest-api-specs/compare/feature/cplat-fixExtensionVM-2)' I am working with the Swagger team for this changes impact on SDKs (track 2 and 1). I will keep you updated.

**Comment by cataggar** [comment]
I see. That makes sense. Thanks @grizzlytheodore.

**Comment by grizzlytheodore** [comment]
PR made to resolve: https://github.com/Azure/azure-rest-api-specs/pull/18487
it will be released with CRP 2022-03-01 version
