### ISSUE TITLE
Microsoft.DataFactory API version 2017-09-01-preview contains an enum with type "object"

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#14555]
This causes Autorest.Bicep to throw a FATAL error as it's unable to process the enum field:
```
2021-05-26T14:56:31.1457134Z FATAL: Error: Enum types of 'object' and format 'undefined' are not supported. Correct your input (StoredProcedureParameterType).
2021-05-26T14:56:31.1472861Z Failure during batch task - {"tag":"microsoft.datafactory-2017-09-01-preview"} -- Error: Plugin modelerfour reported failure..
2021-05-26T14:56:31.1477521Z   Error: Plugin modelerfour reported failure.
```

This looks like an accidental authoring error:
https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json#L1149-L1165

In the stable version, it has been corrected to "string":
https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L3822-L3838

**Comment by shawnxzq** [comment]
@anthony-c-martin Stable version is the one we are currently using, and we don't invest in the old version any more.

**Comment by shawnxzq** [comment]
Answered question and close it for now since no more response.

**Comment by anthony-c-martin** [comment]
Reopening - this hasn't been fixed.

**Comment by anthony-c-martin** [comment]
@shawnxzq I've started a PR (#15578) to fix this - would you be able to help get it merged?

@alex-frankel FYI.

**Comment by shawnxzq** [comment]
@anthony-c-martin I don't have permission to merge as I am not part of the swagger reviewer team, @leni-msft help on this, thx!

**Comment by leni-msft** [comment]
@shawnxzq Sure, will do.
