### ISSUE TITLE
Suggestion: CustomerInsights - Renaming models

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#1460]
Reference https://github.com/Azure/azure-rest-api-specs/pull/1438

There are a bunch of models with name ending `ResourceFormat`, for example currently usage of method to retrieve a prediction looks like:

```C#
PredictionResourceFormat p = Predictions.Get(...);
```

If we rename this to `Prediction` for instance, it looks clean

```C#
Prediction p = Predictions.Get(..);
```

As part of future swagger update (that contains other breaking changes), consider renaming the models.

**Comment by salameer** [comment]
Hello,

I chatted with Anu on this. @tjlvtao  please make sure to avoid using such naming in the future and using whats suggested here. But we agree that fixing this will introduce breaking changes.

THanks,

Samer
