### ISSUE TITLE
Operations API needs to be implemented in the service side and described in swagger

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#1462]
Linter reported for this PR https://github.com/Azure/azure-rest-api-specs/pull/1438 that operations API is not implemented. Service team confirmed that RP don't have this API implemented, it is in their backlog.

**Comment by tjlvtao** [comment]
@anuchandy we have added operation API the the swagger with this commit:
https://github.com/Azure/azure-rest-api-specs/commit/9b499ac14b22b844ea1c0ef88f452f8b3b89a497

Please help to close this issue. Thanks.
