### ISSUE TITLE
CheckSkuAvailability.json has old SKU

### ISSUE THREAD

**Issue by jongio** [Azure/azure-rest-api-specs#14669]
This line:

https://github.com/Azure/azure-rest-api-specs/blob/333cc9e7a6afe3509f4411c9846510a9fdc32eec/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/examples/CheckSkuAvailability.json#L21

            "skuName": "S0",

Should be

"skuName": "S"

azsdke2e
azsdke2e2

**Comment by yangyuan** [comment]
S0 is a available SKU for Face.
Note for Cognitive Services, different API Kinds have different available SKUs.
