### ISSUE TITLE
Folder structure change for FarmBeats

### ISSUE THREAD

**Issue by RGKarthik** [Azure/azure-rest-api-specs#14679]
Can the folder structure for FarmBeats REST APIs be changed from 'azure-rest-api-specs/specification/agfood' to 'azure-rest-api-specs/specification/agrifood'.

We are using agrifood in all the public SDK repos. Hence for the sake of consistency, agrifood would be preferred.

**Comment by RGKarthik** [comment]
cc: @ramya-rao-a

**Comment by lmazuel** [comment]
Done in https://github.com/Azure/azure-rest-api-specs/pull/14735
