### ISSUE TITLE
Add new Cognitive Services SKUs to 2021-04-30

### ISSUE THREAD

**Issue by jongio** [Azure/azure-rest-api-specs#14670]
Version 2021-04-30 needs to be updated with new SKUs
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2021-04-30

azsdke2e
azsdke2e2

**Comment by yangyuan** [comment]
As explained via Team, due to the nature of Cognitive Services accounts. We dont define Sku and Kind as Emun.
