### ISSUE TITLE
List protectionContainers doesn't work

### ISSUE THREAD

**Issue by chihhaohuang** [Azure/azure-rest-api-specs#14715]
I've tried the API on https://docs.microsoft.com/en-us/rest/api/backup/2021-02-10/backup-protection-containers/list and got 400 error. There is an issue with this API.

{
  "error": {
    "code": "BMSUserErrorInvalidInput",
    "message": "Input provided for the call is invalid\r\nPlease check the required inputs",
    "target": null,
    "details": null,
    "innerError": null
  }
}

**Comment by adityabalaji-msft** [comment]
Thank you for reaching out. Adding @pratimaupadhyay02 to investigate

**Comment by pvrk** [comment]
@chihhaohuang : We have tried to reproduce multiple times but it is working from our end. Can you please share the request URL? Also, please share the client request ID in request and/or response header. That will help us debug more specifically.

**Comment by chihhaohuang** [comment]
https://management.azure.com/subscriptions/de3624a8-30bf-42c3-8672-58c196d799fc/resourceGroups/bac-rg-devuksouthmca/providers/Microsoft.RecoveryServices/vaults/bac-rg-devuksouthmca-recovery/backupProtectionContainers?api-version=2021-02-10

Response Header:

cache-control: no-cache
content-length: 177
content-type: application/json
date: Tue, 27 Jul 2021 09:38:34 GMT
pragma: no-cache
server: Microsoft-IIS/10.0
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-client-request-id: a35e848d-7baf-4c82-ad28-25fd4f073521, a35e848d-7baf-4c82-ad28-25fd4f073521
x-ms-correlation-request-id: 291e06c3-b3ef-4755-a1dc-f7264526bac4
x-ms-ratelimit-remaining-subscription-resource-requests: 149
x-ms-request-id: 291e06c3-b3ef-4755-a1dc-f7264526bac4
x-ms-routing-request-id: WESTEUROPE:20210727T093834Z:291e06c3-b3ef-4755-a1dc-f7264526bac4
x-powered-by: ASP.NET


Response Body:
{
  "error": {
    "code": "BMSUserErrorInvalidInput",
    "message": "Input provided for the call is invalid. Please check the required inputs",
    "target": null,
    "details": null,
    "innerError": null
  }
}

**Comment by adityabalaji-msft** [comment]
Hi @chihhaohuang - you will need to pass BackupManagementType as a filter to the request, to get all containers of a particular type. Here is an example: https://docs.microsoft.com/rest/api/backup/backup-protection-containers/list#list-backup-protection-containers

**Comment by chihhaohuang** [comment]
According to this document, filter is an optional parameter.
Also tried this again on the document page, added backupManagementType, but still the same.

Add a new parameter: filter => backupManagementType eq 'AzureStorage'

GET https://management.azure.com/subscriptions/de3624a8-30bf-42c3-8672-58c196d799fc/resourceGroups/bac-rg-devuksouthmca/providers/Microsoft.RecoveryServices/vaults/bac-rg-devuksouthmca-recovery/backupProtectionContainers?api-version=2021-02-10&filter=backupManagementType%20eq%20%27AzureStorage%27

cache-control: no-cache
content-length: 177
content-type: application/json
date: Tue, 27 Jul 2021 13:27:09 GMT
pragma: no-cache
server: Microsoft-IIS/10.0
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-ms-client-request-id: 5abd6583-ba52-403b-ad03-c52cb88573da, 5abd6583-ba52-403b-ad03-c52cb88573da
x-ms-correlation-request-id: 3a176a84-2b11-4168-a7f1-7e3fbf3aa1f7
x-ms-ratelimit-remaining-subscription-resource-requests: 143
x-ms-request-id: 3a176a84-2b11-4168-a7f1-7e3fbf3aa1f7
x-ms-routing-request-id: WESTEUROPE:20210727T132710Z:3a176a84-2b11-4168-a7f1-7e3fbf3aa1f7
x-powered-by: ASP.NET

{
  "error": {
    "code": "BMSUserErrorInvalidInput",
    "message": "Input provided for the call is invalid. Please check the required inputs",
    "target": null,
    "details": null,
    "innerError": null
  }
}

**Comment by adityabalaji-msft** [comment]
@chihhaohuang - thanks for the details. The filter is currently a required filter (we will update the documentation). In the above request, you will need to add a '$' before 'filter': 

eg. GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/SwaggerTestRg/providers/Microsoft.RecoveryServices/vaults/NetSDKTestRsVault/backupProtectedItems?api-version=2021-02-10**&$filter**=backupManagementType eq 'AzureIaasVM' and itemType eq 'VM'

**Comment by adityabalaji-msft** [comment]
closing this issue, feel free to re-open in case of any other questions
