### ISSUE TITLE
compute: spec "Resource" shouldn't require location

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-rest-api-specs#148]
In the spec for arm-compute, the "Resource" object specifies "location" as a required property when I believe it shouldn't.

See [https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2015-06-15/swagger/compute.json#L4581](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2015-06-15/swagger/compute.json#L4581)

The ["VirtualMachineExtension" object](VirtualMachineExtension) extends "Resource". However, "VirtualMachineExtension" does not always have "location" defined.

This is evident with an API call to
https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Compute/virtualMachines?api-version=2015-06-15
where the "resources" object in the JSON response contains an array of VM Extensions and each object in this array only has an id (i.e. no "location").

**Comment by devigned** [comment]
I believe the vm extensions should be sub resources, right?

**Comment by hyonholee** [comment]
VM extension contains id, name, type, location and tags.   Note that "required" in the spec is only applied when the object is in a request body.  For response body, it does not mean anything.  So even though "location" is set to "required" and the response body does not contain "location", it does not cause an issue.  For "PUT" operation of VM extension, this location value is required.

**Comment by kirthik** [comment]
Talked to @derekbekoe. He mentioned there have been later API versions where this is resolved. @derekbekoe - please feel free to add more details
