### ISSUE TITLE
[Resources] Rest Api Defined in Swagger Returns 404 by Service

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#14807]
This issue originates from https://github.com/Azure/azure-sdk-for-js/issues/15460.
The swagger defines a rest [api](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/resources.json#L37-L67), however, the service returns 404 error when call this api:
```
{
    "error": {
        "code": "InvalidResourceType",
        "message": "The resource type 'operations' could not be found in the namespace 'Microsoft.Resources' for api version '2021-01-01'. The supported api-versions are '2015-01-01'."
    }
}
```

**Comment by zhenglaizhang** [comment]
@shenglol pls help take a look at the issue

**Comment by shenglol** [comment]
Will take a look.

**Comment by qiaozha** [comment]
@shenglol  Any updates on this issue? I can see from your manifest. Microsoft.Resources/operations still only support 2015-01-01 https://armmanifest.visualstudio.com/One/_git/Manifest?path=%2FMICROSOFT.RESOURCES%2FPROD%2FMANIFEST.JSON&version=GBmaster&line=2402&lineEnd=2402&lineStartColumn=2&lineEndColumn=28&lineStyle=plain&_a=contents and we have another customer complains about this issue again https://github.com/Azure/azure-sdk-for-js/issues/15460#issuecomment-891522699.
