### ISSUE TITLE
Classification confusion (add more categories than resource-manager and data-plane?)

### ISSUE THREAD

**Issue by olydis** [Azure/azure-rest-api-specs#1482]
There are some OpenAPI definitions that don't really fit the current binary classification between "resource-manager" and "data-plane", e.g.
- https://github.com/Azure/azure-rest-api-specs/blob/current/specification/graphrbac/data-plane/1.6/graphrbac.json, thanks @mcardosos. It is more of a management API, simply not ARM (you can create users and stuff)
- https://github.com/Azure/azure-rest-api-specs/tree/current/specification/servicefabric/data-plane, thanks @VipulM-MSFT. ServiceFabric has *actual* data-plane APIs that are different from this! They consistently market this API here as "client", so why not reflect this here to avoid customer and our own confusion (and make potential room for the actual data-plane API flying in here, who knows).

**Comment by VipulM-MSFT** [comment]
@olydis - thank you for opening the issue.
