### ISSUE TITLE
Query: Azure Storage failover for a RA-GRS account

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-rest-api-specs#14878]
We are working on creating scripts to failover our storage accounts (RA-GRS configuration). The failover documentation mentions that after failover the account is configured as LRS and needs to be re-enabled as RA-GRS. We use the Set-AzStorageAccount cmd (after failing over the account to the secondary region) to covert the account back from LRS to RA-GRS. Few questions about this flow:
1) When the primary region is in an outage, will the Set-AzStorageAccount cmd succeed in converting the storage account from LRS to RA-GRS?

- If yes, what happens to the replication while primary region is under outage?

- If no, what is the correct process to follow to convert the account back to RA-GRS?

**Comment by blueww** [comment]
@asgoe
As we already follow up this issue with issue https://github.com/Azure/azure-powershell/issues/15290 and mail, I will close this one.
Next time if you face the server issue, you can raise it in portal or here, instead of Powershell repo.
