### ISSUE TITLE
Retrieve more than 1000 records from Azure Usage APIs

### ISSUE THREAD

**Issue by sabrishami** [Azure/azure-rest-api-specs#14895]
Hi,

I'm trying to retrieve usage data using rest API in the Azure data factory.

However, I've defined  AbsoluteUrl=$.value.nextLink (for pagination rule) in the source section. but still,  just 1000 records have been returned. 

Could anyone help me?

**Comment by shawnxzq** [comment]
@sabrishami This forum is for api/SDK related issues, your issue is more related to the rest connector area, is it possible for you to open a support case? In this way, we will have more experts in different area to help with committed SLA, thanks!

**Comment by shawnxzq** [comment]
Provided the right channel for customer solve the issue, close it for now since no more response from customer.
