### ISSUE TITLE
Virtual Machines: "Basic Metrics" API / VM Extension

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1490]
👋🏻 Hey folks

I'm unsure of the correct place to file a bug for this - but I'm assuming here's as good as any, please re-route me if not and I can move this :)

We've had a request come [in to support "Basic Metrics" on Virtual Machines](https://github.com/terraform-providers/terraform-provider-azurerm/issues/199). After looking into this I found [this page of documentation which indicates that this is a VM Extension](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-diagnostics-template?toc=%2fazure%2fvirtual-machines%2fwindows%2ftoc.json) - and I've verified this assumption in the Portal by enabling it manually and viewing the exported ARM Template.

Would it be possible to confirm if this assumption is correct about it being a VM Extension?

I've converted this over to Terraform syntax, which calls the VM Extensions API - however I'm seeing the VM Extension timeout after 1.5h - even when using the values exported from the ARM Template via selecting "Automation Script" in the Portal.

I've [uploaded the configuration I've pieced together](https://gist.github.com/tombuildsstuff/4418f5c58516affed5bd5a6c3cadf4ff) - which has been translated from the "Automation Script" tab in the Portal against a machine made manually. Would its be possible to confirm if I'm missing something when configuring this VM Extension? In addition - given it's a checkbox in the portal, is this likely to be exposed via the Virtual Machine API in the future?

Thanks!

**Comment by anuchandy** [comment]
@tombuildsstuff, `IaaSDiagnostics` extension is for enabling diagnostics on Windows virtual machine, for Linux it is `LinuxDiagnostic`. See this code that shows configuring diagnostics on Linux VM https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineExtensionOperationsTests.java#L69.

The configuration `ladCfg` for linux looks like: https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/resources/linux_diagnostics_public_config.json

**Comment by anuchandy** [comment]
For windows, please refer the discussion here https://github.com/Azure/azure-sdk-for-java/issues/1836

**Comment by tombuildsstuff** [comment]
Thanks for confirming @anuchandy I can confirm the Linux specific version works - I'll double-check the Windows version tomorrow

Are there any plans to combine these into a single extension? It seems odd to have multiple extensions doing the same thing?

**Comment by anuchandy** [comment]
Great to know it's working!

Regarding merging extensions, it's a question for the service team, you can open issue here https://github.com/Azure/azure-linux-extensions. The diagnostics extension for Linux is maintained [here](https://github.com/Azure/azure-linux-extensions/tree/master/Diagnostic)

**Comment by tombuildsstuff** [comment]
@anuchandy I can confirm the Windows version works too - as such I'm going to close this issue for the moment.

I've opened issue #1534 about adding a field to the Compute API for Basic Metrics, to improve the UX of deploying Azure Monitoring through the API to match the Portal

Thanks!
