### ISSUE TITLE
SignalR Service API returns additional type `Trace` but it doesn't include in type list

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#14923]
After checked, seems SignalR Service API returns additional type `Trace` in the response but it isn't involved in [signalr request type list](https://github.com/Azure/azure-rest-api-specs/blob/c059fb47f87a35ce5a90631883dfba8f01a41d8e/specification/signalr/resource-manager/Microsoft.SignalRService/stable/2020-05-01/signalr.json#L1418). Maybe service team have to make a fix to add this additional type `Trace` in rest api spec.

**Comment by juniwang** [comment]
`2020-05-01` is a very old version. The new type is included in newer api versions: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/signalr/resource-manager/Microsoft.SignalRService/preview/2021-06-01-preview/signalr.json#L1960.

A new stable version is planning to be ready in Sept/Oct which will contain all new properties/APIs

**Comment by tombuildsstuff** [comment]
@juniwang 2020-05-01 is just over a year old, so it's not old relative to other API specs (2015) in this repository - if the API spec is in this repository it should contain all of the supported values in the API.

Is there a timeframe for when this value will get added to this API?

**Comment by juniwang** [comment]
Adding new enum values is considered as breaking change which requires new api-version anyway. So, we don't have a plan to update `2020-05-01`. `Trace` is incorrectly returned by accident.   A new stable api-version is on the way with correct values.

**Comment by tombuildsstuff** [comment]
@juniwang adding new enum values is **not a breaking change** - changing (for example the casing of) or removing enum values **is a breaking change**, however

cc @JeffreyRichter to confirm that?

**Comment by JeffreyRichter** [comment]
Adding a new enum value to an enum that is modeled as string is OK (because it is just a new string value); adding a new enum value that to an enum that is not modeled as string is NOT OK (because returning it to an old client will cause the deserializer to throw an exception).

**Comment by tombuildsstuff** [comment]
PR to fix that here: https://github.com/Azure/azure-rest-api-specs/pull/15455
