### ISSUE TITLE
Add typed definitions to LanguageConstants.CreateResourceProperties()

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#14941]
We should be able to do slightly better validation on types for missing resources by exposing a common set of base types.

Some of these base types are defined here (note - not fully complete): https://github.com/Azure/azure-rest-api-specs/blob/78c2a3fb24bfd4cd3372520bb9df203561c71487/specification/common-types/resource-management/v2/types.json#L50-L84

**Comment by leni-msft** [comment]
Hi @anthony-c-martin, at which phase do you expect the "validation on types for missing resources" happen? static validation(like linting) or dynamic validation(like [LiveValidation](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/288/Swagger-Completeness-and-Correctness?anchor=introduction-to-live-validation-service)) ?
