### ISSUE TITLE
cosmos-db duplicate package-2021-06

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-rest-api-specs#14996]
There are duplicate tags in the readme. There shouldn't be. Both created on June 14th in #14627 by @kavskalyan.

https://github.com/Azure/azure-rest-api-specs/blob/8dff86df71bee429af84ea4713288ef3cdd1db2f/specification/cosmos-db/resource-manager/readme.md#L34-L46

https://github.com/Azure/azure-rest-api-specs/blob/8dff86df71bee429af84ea4713288ef3cdd1db2f/specification/cosmos-db/resource-manager/readme.md#L63-L75

**Comment by MehaKaushik** [comment]
Thanks for pointing this out. We will fix it right away,

**Comment by kavskalyan** [comment]
This has been fixed in this PR:
https://github.com/Azure/azure-rest-api-specs/pull/15183
