### ISSUE TITLE
databricks duplicate package-2021-04-01-preview

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-rest-api-specs#14995]
There are duplicate tags in the readme. There shouldn't be.

On June 9th, #13736 from @mvvsubbu added:

https://github.com/Azure/azure-rest-api-specs/blob/8dff86df71bee429af84ea4713288ef3cdd1db2f/specification/databricks/resource-manager/readme.md#L89-L97

On June 11th, #14745 from @bhmohant added:

https://github.com/Azure/azure-rest-api-specs/blob/8dff86df71bee429af84ea4713288ef3cdd1db2f/specification/databricks/resource-manager/readme.md#L70-L77

**Comment by zhenglaizhang** [comment]
@msaranga or @@mvvsubbu could you help take a look?

**Comment by msaranga** [comment]
@zhenglaizhang : Can you approve PR https://github.com/Azure/azure-rest-api-specs/pull/15090

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang : Can you approve PR #15090

PR merged
