### ISSUE TITLE
Cognitive Services Mgmt: incorrect global location parameter

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1508]
We found an issue with "location" definition in Cognitive Services Mgmt. I quote @amarzavery that describes this better than Ican do:

> W.r.t swagger specs, this was not reviewed correctly. “location” is defined as a global parameter along with subscriptionId and api-version. That is the reason this ends up being a property on the client.
> It is ok to define parameters that are being referenced in multiple operations to define it once in the global parameters section and then reference them everywhere. However, one needs to add an extension named `“x-ms-parameter-location”: “method”` to the parameter. This indicates Autorest to generate it as a method parameter and not as a client property. 
> 
> It is a terrible experience for customers using the SDK to provide “location” while instantiating the client. IMHO, a PR needs to be sent to rectify this error to the azure-rest-api-specs repo before more sdks ship with this bug.

**Comment by jhendrixMSFT** [comment]
Hello @felixwa I've seen you made changes to this swagger in the past, are you the correct owner to follow up on this issue?

**Comment by felixwa** [comment]
@jhendrixMSFT , @lmazuel , I will look into this.

**Comment by felixwa** [comment]
Fixed by PR #1532 . Please close this one.
