### ISSUE TITLE
avocado check should add 'arm-compute' to --excludePaths

### ISSUE THREAD

**Issue by jamesc** [Azure/azure-rest-api-specs#15109]
avocado was failing on a change to the JSON in the arm-compute directory (e.g. in PR #14796).

The pipeline needs to be updated to add `--excludePaths arm-compute`

**Comment by zhenglaizhang** [comment]
Thanks @jamesc We will update the pipeline to exclude the path in next pipeline deployment, early next week.

**Comment by zhenglaizhang** [comment]
We have already released the fix.
