### ISSUE TITLE
BotService.Connection API failed to create when the `parameters` property is []

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#15104]
After tested, I found [BotService.Connection API](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/botservice/resource-manager/Microsoft.BotService/stable) failed to create and threw below error message while creating Bot connection and the `parameters` property is set as `[]`. I assume api shouldn't return error when this property is set as `[]`. Please have a look. Thanks.

Http request body:
```
PUT https://management.azure.com/subscriptions/xx-xx-xx-xx/resourceGroups/xxxxxxx/providers/Microsoft.BotService/botServices/xxxxxxxx/Connections/xxxxxxx

{
    "kind": "bot",
    "location": "global",
    "properties": {
        "clientId": "test",
        "clientSecret": "secret",
        "parameters": [],
        "scopes": "",
        "serviceProviderId": "xx-xxx-xxx-xxx"
    },
    "tags": {}
}
```

Http Response:
```
botservice.BotConnectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidBotData" Message="message: connection resource with id xxxxxxx is not found"
```

**Comment by sgellock** [comment]
I've routed this to the service DRI team to drive.  updates will be posted here as that team has them

**Comment by swagatmishra2007** [comment]
The parameters property is actually needed and you would need to specify a list of properties such as clientid, clientSecret and others depending on the service provider id in the parameters so as to properly configure an oauth connection. To find out the list of properties needed, you can create a connection in the portal and use the ARM api to do a get against it and see what parameters were configured.
