### ISSUE TITLE
Microsoft.DataFactory Dataset.json DatasetCompression.properties.type problem

### ISSUE THREAD

**Issue by VyacheslavShilov** [Azure/azure-rest-api-specs#15168]
DatasetCompression.properties.type has the type " string".
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Dataset.json#L454

however, I get answers with both the "object" type and the "string" type.

GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{factoryName}/datasets?api-version=2018-06-01

In the first object, properties.typeProperties.compression.type is an "object".
In the second object, properties.typeProperties.compression.type is a "string".

```
{
	"value": [
		{
			"id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.DataFactory/factories/.../datasets/AzureBlob_External_Compressed",
			"name": "AzureBlob_External_Compressed",
			"type": "Microsoft.DataFactory/factories/datasets",
			"properties": {
				"linkedServiceName": {
					"referenceName": "AzureBlobStorage_External_LinkedService",
					"type": "LinkedServiceReference"
				},
				"parameters": {
					"file_name": {
						"type": "string"
					},
					"file_container": {
						"type": "string"
					},
					"compression_type": {
						"type": "string"
					}
				},
				"annotations": [],
				"type": "Binary",
				"typeProperties": {
					"location": {
						"type": "AzureBlobStorageLocation",
						"fileName": {
							"value": "@dataset().file_name",
							"type": "Expression"
						},
						"container": {
							"value": "@dataset().file_container",
							"type": "Expression"
						}
					},
					"compression": {
						"type": {
							"value": "@dataset().compression_type",
							"type": "Expression"
						}
					}
				}
			},
			"etag": "..."
		},
		{
			"id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.DataFactory/factories/.../datasets/AzureBlob_Compressed_ZIP",
			"name": "AzureBlob_Compressed_ZIP",
			"type": "Microsoft.DataFactory/factories/datasets",
			"properties": {
				"linkedServiceName": {
					"referenceName": "AzureStorage_LinkedService",
					"type": "LinkedServiceReference"
				},
				"parameters": {
					"file_name": {
						"type": "String"
					},
					"container_name": {
						"type": "String"
					}
				},
				"annotations": [],
				"type": "AzureBlob",
				"typeProperties": {
					"compression": {
						"type": "ZipDeflate"
					},
					"fileName": {
						"value": "@dataset().file_name",
						"type": "Expression"
					},
					"folderPath": {
						"value": "@dataset().container_name",
						"type": "Expression"
					}
				}
			},
			"etag": "..."
		}
	]
}
```
When deserializing the first object in Java, I get an error: 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "value" (class com.gigware.cloudmine.azure.client.datafactory.model.DatasetCompression), not marked as ignorable (one known property: "type"])

**Comment by shawnxzq** [comment]
@VyacheslavShilov Yes, it's defined as string, however, ADF current doesn't do validation when you create the dataset, so if you create it as an object, you will get it as an object, same thing for string.

To avoid the serialization/deserialization issue, please use string value only, thanks!

**Comment by VyacheslavShilov** [comment]
@shawnxzq
But this is a legal situation. This is created through the "Azure Portal". This "compression.type" is obtained when "dynamic content" is used"
![image](https://user-images.githubusercontent.com/36583786/125780684-b889f035-95f9-4719-af58-a225daef3228.png)
![image](https://user-images.githubusercontent.com/36583786/125780786-aa219b6c-fae7-4675-b2ea-6da19202510f.png)

**Comment by shawnxzq** [comment]
@VyacheslavShilov Yes, you are correct and this is known issue, the fix is being worked on.  I mean before the fix take effective, you can workaround by not parameterizing it, thanks!

**Comment by shawnxzq** [comment]
Swagger is already fixed, it will be fixed in next version java client.

**Comment by shawnxzq** [comment]
New jave client is released, it should already fix the issue, thanks!
