### ISSUE TITLE
The description for KeyReleaseResult appears copied for something returning a KeyBundle and is confusing

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#15258]
https://github.com/Azure/azure-rest-api-specs/blob/e7682aa897902920f3a95b2f358b6f7729d18666/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.3-preview/keys.json#L950

/cc @herveyw-msft

**Comment by herveyw-msft** [comment]
Is the concern that this is really a compact JWS object that contains the key bundle?

**Comment by heaths** [comment]
Describing that would be better, yeah. I see how this probably wasn't copied then, but describing that the result is actually a JWS containing the key bundle would at least steer people down the path of parsing the JWS at least. Maybe even describing the payload within. The structure is a little different (but otherwise similar) to a `KeyBundle`.
