### ISSUE TITLE
Databricks:  The return result of vnetpeering list is different from the definition of swagger

### ISSUE THREAD

**Issue by PARADISSEEKR** [Azure/azure-rest-api-specs#15301]
**Describe the bug**

When I run the `az databricks workspace vnet-peering list` command, I get the wrong result:
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\code\benv\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\code\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "d:\code\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\code\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 704, in _run_job
    result = list(result)
  File "D:\code\benv\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "D:\code\benv\lib\site-packages\azure\core\paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "d:\code\azure-cli-extensions\src\databricks\azext_databricks\vendored_sdks\databricks\operations\_vnet_peering_operations.py", line 429, in extract_data
    return deserialized.next_link or None, iter(list_of_elem)
TypeError: 'NoneType' object is not iterable

**Through debug I found that the service should return {"vaule":[]}, but it returns {}**

swagger info: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/vnetpeering.json

debuginfo: 

cli.knack.cli: Command arguments: ['databricks', 'workspace', 'vnet-peering', 'list', '--workspace-name', 'ws1', '-g', 'detest', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001D03A0900D0>, <function OutputProducer.on_global_arguments at 0x000001D03A359280>, <function CLIQuery.on_global_arguments at 0x000001D03A380820>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'databricks': ['azext_databricks']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: databricks                0.004         3        12  D:\code\azure-cli-extensions\src\databricks
cli.azure.cli.core: Total (1)                 0.004         3        12
cli.azure.cli.core: Loaded 3 groups, 12 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : databricks workspace vnet-peering list
cli.azure.cli.core: Command table: databricks workspace vnet-peering list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001D03C4C5670>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\v-jingszhang\.azure\commands\2021-07-22.10-30-27.databricks_workspace_vnet-peering_list.19148.log'.
az_command_data_logger: command args: databricks workspace vnet-peering list --workspace-name {} -g {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001D03C4E4B80>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x000001D03C5471F0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001D03C547280>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001D03C5473A0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001D03A359310>, <function CLIQuery.handle_query_parameter at 0x000001D03A3808B0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x000001D03C547160>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001D03C547310>]
az_command_data_logger: extension name: databricks
az_command_data_logger: extension version: 0.7.2
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=DatabricksClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file C:\Users\v-jingszhang\.azure\accessTokens.json as utf-8-sig
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - Authority:Performing instance discovery: ...
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - Authority:Performing static instance discovery
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - Authority:Authority validated via static instance discovery
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - CacheDriver:Found 5 potential entries.
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - CacheDriver:Resource specific token found.
adal-python: b2940ef3-a3d0-49d8-941d-3c54c315cf61 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'+MQmr8NQab1PkXGdGfuYVCCsw4XmbjfWVJEGDSOSK+Y=', RefreshTokenId: b'Ugnh91FoGxmWcvwvhYNz/jhDhthdlehVNBYVoJmWWVg='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/detest/providers/Microsoft.Databricks/workspaces/ws1/virtualNetworkPeerings?api-version=2018-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'c6d569e1-ea94-11eb-8401-b07b250bf939'
cli.azure.cli.core.sdk.policies:     'CommandName': 'databricks workspace vnet-peering list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--workspace-name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (PIP) azsdk-python-mgmt-databricks/1.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/detest/providers/Microsoft.Databricks/workspaces/ws1/virtualNetworkPeerings?api-version=2018-04-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'X-Frame-Options': 'SAMEORIGIN'
cli.azure.cli.core.sdk.policies:     'X-XSS-Protection': '1; mode=block'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': ''
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd7ee61f2-8afd-41a0-a629-1144bc7e98c4'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20210722T023029Z:d7ee61f2-8afd-41a0-a629-1144bc7e98c4'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 22 Jul 2021 02:30:28 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {}

**The correct result obtained by comparing the `az databoxedge device list`:**

debug info:

cli.knack.cli: Command arguments: ['databoxedge', 'device', 'list', '-g', 'dtest', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000026E662500D0>, <function OutputProducer.on_global_arguments at 0x0000026E66319280>, <function CLIQuery.on_global_arguments at 0x0000026E66540820>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'databoxedge': ['azure.cli.command_modules.databoxedge']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: databoxedge               0.007         5        27
cli.azure.cli.core: Total (1)                 0.007         5        27
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 5 groups, 27 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : databoxedge device list
cli.azure.cli.core: Command table: databoxedge device list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000026E68685670>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\v-jingszhang\.azure\commands\2021-07-22.11-17-11.databoxedge_device_list.1816.log'.
az_command_data_logger: command args: databoxedge device list -g {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000026E686A4B80>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x0000026E687061F0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000026E68706280>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000026E687063A0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000026E66319310>, <function CLIQuery.handle_query_parameter at 0x0000026E665408B0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x0000026E68706160>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000026E68706310>]
Command group 'databoxedge' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=DataBoxEdgeManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file C:\Users\v-jingszhang\.azure\accessTokens.json as utf-8-sig
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - Authority:Performing instance discovery: ...
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - Authority:Performing static instance discovery
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - Authority:Authority validated via static instance discovery
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - CacheDriver:Found 5 potential entries.
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - CacheDriver:Resource specific token found.
adal-python: 3d6dfa93-fe64-4f98-8247-049305b159f2 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'+MQmr8NQab1PkXGdGfuYVCCsw4XmbjfWVJEGDSOSK+Y=', RefreshTokenId: b'Ugnh91FoGxmWcvwvhYNz/jhDhthdlehVNBYVoJmWWVg='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/dtest/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices?api-version=2021-02-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '4e18897d-ea9b-11eb-bc1e-b07b250bf939'
cli.azure.cli.core.sdk.policies:     'CommandName': 'databoxedge device list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (PIP) azsdk-python-azure-mgmt-databoxedge/1.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/dtest/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices?api-version=2021-02-01-preview HTTP/1.1" 200 133
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c56e2f7f-86cd-455d-a4c6-da5679a230fa'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c56e2f7f-86cd-455d-a4c6-da5679a230fa'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20210722T031712Z:c56e2f7f-86cd-455d-a4c6-da5679a230fa'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 22 Jul 2021 03:17:11 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '133'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[]}

**Environment summary**
azure-mgmt-databricks==1.0.0

**Comment by msaranga** [comment]
@jsntcy : This has been resolved. Please close this issue
