### ISSUE TITLE
Consider TextRecord -> TextDocumentInput like TA or back to TextInput

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#15374]
not related to the PR but curious about the reason for the name change. `TextInput` was closer to TA and in case we want some sort of consistency in CS, maybe having `TextInput` here is not a bad idea either

_Originally posted by @maririos in https://github.com/Azure/azure-sdk-for-net/pull/22882#discussion_r676921862_

**Comment by heaths** [comment]
@rokulka can we get this one done in time for GA as well?

Text Analytics uses `TextDocumentInput`: https://github.com/Azure/azure-sdk-for-net/blob/9dc7eb7212a51f1db269c630406fd62f0c792838/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextDocumentInput.cs#L12

**Comment by rokulka** [comment]
@heaths - TextAnalytics will be changing their API to use "records" instead of "documents" when they go GA, the timeline for that is not finalized yet.  We can go ahead with "TextRecords" as the class name.

CC - @assafi
