### ISSUE TITLE
[Network] Somes operations defines both LRO and Paging

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1539]
This PR https://github.com/Azure/azure-rest-api-specs/pull/1468 changed the behavior of `NetworkInterfaces_GetEffectiveRouteTable` and `NetworkInterfaces_ListEffectiveNetworkSecurityGroups` to declare them at the same time LRO and Paging.

This is not supported yet in Python, and acording to @amarzavery not in C# as well.

This should then be removed from the repo, until Autorest can deal with it in all languages.

**Comment by number213** [comment]
Fixed by https://github.com/Azure/azure-rest-api-specs/pull/1547

**Comment by lmazuel** [comment]
Considered Autorest issue
