### ISSUE TITLE
Schedule Interval Field has no Type

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#1545]
As discovered by @Kemyke in Azure/azure-sdk-for-go#725, the [Interval field here has no type information](https://github.com/Azure/azure-rest-api-specs/blob/2fb9a0b3b902335ff0b0033711c234431931ec9d/specification/automation/resource-manager/Microsoft.Automation/2015-10-31/definitions.json#L2953), which means each SDK is stabbing in the dark as to what they should send across the wire.

**Comment by Kemyke** [comment]
Can someone please give us an update on this? Can we expect the fix for this basic bug?

**Comment by jeffzabel** [comment]
No recurrences of this issue since it was worked around.  Closing
