### ISSUE TITLE
[Network] Virtual Networks / Subnets: IPv6 Support

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1556]
:wave:

I've been going through the documentation for Network Interfaces and noticed a field to set the IP Version.

In order to test this, I attempted to spin up a Virtual Network (with a Subnet) with an IPv6 address space; however I got an error back from the Azure API:

```
network.VirtualNetworksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidAddressPrefixFormat" Message="Address prefix 2001:db8:1234:1a00::/56 of resource /subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba/resourceGroups/acctest-rg-651083927755134390/providers/Microsoft.Network/virtualNetworks/acctestvn6-651083927755134390 is not formatted correctly. It should follow CIDR notation, for example 10.0.0.0/24." Details=[]
```

Given this also appears to be the case in the portal when attempting to add an IPv6 address space - I'm assuming this is preparation for future use, rather than currently supported functionality.

Would it be possible to confirm if IPv6 is supported at this time, or if this field is preparation for future-use? Presumably if that's the case, an error back to the effect of "IPv6 Address Spaces aren't supported at this time" - would make more sense rather than returning an IPv4 CIDR failure?

Thanks!

cc @DeepakRajendranMsft @deepakswifty @markjbrown @Nilambari @johanste @lamchester

**Comment by johanste** [comment]
Sorry - somehow my github notification filters was down so I missed this (and a bunch of other) mention. 

[This](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface-addresses) and [this](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq) articles describes many of the capabilities and limitations of ipv6 addresses.

**Comment by anuchandy** [comment]
@tombuildsstuff Does the pointers that Johan provided address your concern? If yes can we close this issue?

**Comment by anuchandy** [comment]
@tombuildsstuff  closing this, feel free to re-open with more details if you still have issue.

**Comment by tombuildsstuff** [comment]
@anuchandy sorry missed this - would it be possible to re-open this issue?

Pulling from [this document](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview?toc=%2fazure%2fvirtual-network%2ftoc.json#details-and-limitations):

> You cannot add IPv6 load balancing rules in the Azure portal. The rules can only be created through the template, CLI, PowerShell.
> A single IPv6 address can be assigned to a single network interface in each VM.

I'd argue the API's returning the incorrect error message here (since the CLI/PowerShell) are still (presumably) calling the same endpoints - and thus presumably creating an IPv6 Subnet is valid?

Thanks!
