### ISSUE TITLE
Microsoft.Insights ScheduledQueryRuleProperties/actions has invalid type

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#15588]
See definition for /specification/monitor/resource-manager/Microsoft.Insights/preview/2021-02-01-preview/scheduledQueryRule_API.json#/definitions/ScheduledQueryRuleProperties/actions:
https://github.com/Azure/azure-rest-api-specs/blob/7384176da46425e7899708f263e0598b851358c2/specification/monitor/resource-manager/Microsoft.Insights/preview/2021-02-01-preview/scheduledQueryRule_API.json#L411-L417

Generally, "items" is only used with an "array" type. Should we have `"type": "array"` here?

Originally raised under https://github.com/Azure/bicep/issues/3806

**Comment by avjerafi** [comment]
@raych1 
We have already caught this and the fix was merged 6 days ago:
Please see: https://github.com/Azure/azure-rest-api-specs/pull/15607

**Comment by JackTn** [comment]
@anthony-c-martin  hi ~ is this issue resolved? And can you closed if it meets your expectations， thanks

**Comment by anthony-c-martin** [comment]
Looks good, thanks for fixing @avjerafi!
