### ISSUE TITLE
/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/cancel doesn't work with RBAC role Microsoft.Subscription/cancel/action

### ISSUE THREAD

**Issue by OscartGiles** [Azure/azure-rest-api-specs#15635]
What permissions are required to cancel subscriptions?

I created this role:
```json
{
    "properties": {
        "roleName": "cancel-role",
        "description": "",
        "assignableScopes": [
            "/subscriptions/{sub_id}"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Subscription/cancel/action",
                    "Microsoft.Subscription/enable/action"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

This API endpoint works:
```
/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/enable
```
This one doesn't:
```
/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/cancel
```

I get the following error message:

> Only subscription owners can perform this operation. Contact your subscription owner to perform this operation

I need to assign a role to a managed identity that can cancel subscriptions but not do anything else.

Strangely giving the role Action permission * and notAction Microsoft.Subscription/cancel/action does not stop you from being able to cancel subscriptions.

**Comment by ShilpiGautam** [comment]
@anuragdalmia please take a look and respond.

**Comment by anuragdalmia** [comment]
We explicitly look for owner role. Custom roles with same sets of permissions will not work unfortunately.

**Comment by OscartGiles** [comment]
Hi @anuragdalmia . Through trial and error we managed to cancel subscriptions with the Azure CLI and the following:

Is this likely to change at any time?


```bash
{
    "properties": {
        "roleName": "AllowAuthSub2",
        "description": "Allow authorization/* and subscription/*",
        "assignableScopes": [
            "/subscriptions/{sub-id}"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Authorization/*",
                    "Microsoft.Subscription/*"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

**Comment by anuragdalmia** [comment]
Can you help me understand your scenario. Do you want to allow a role to cancel a subscription but not any other permission that comes along with being an owner? Can you elaborate on that please.

**Comment by OscartGiles** [comment]
Exactly. We are trying to build some automation that tracks hundreds of subscriptions usage and then cancels them when a budget threshold is reached.

Essentially we have a function app with a managed identity that cancels subscriptions. The function app doesn't do anything except cancel subscriptions. Rather than make the managed identity an `owner` on our hundreds of subscriptions, it would be much better if it only had the permissions it needs. 

It seems that we've found the set of permissions that allows that (last post), but as Microsoft officially says you need an `owner` role we want to be sure these permissions will remain sufficient.
