### ISSUE TITLE
SecurityInsights DataConnector Add AzureDefender to API

### ISSUE THREAD

**Issue by ricohomewood** [Azure/azure-rest-api-specs#15632]
The current list of supported Sentinel Data Connectors misses out on one of the fundamental connectors as part of Azure Security Center which is `Azure Defender`. Due to the limitation in the API you have to configure this data connector manually by going into the connector and enabling `Azure Defender to Azure Sentinel`.

Please can we add this data connector to the list of configurable data connectors or add it to the current Azure Security Center data connector so this one also gets enabled including support for Bi-directional sync?

This will enable the streaming of Azure Defender alerts into Azure Sentinel

ref: https://docs.microsoft.com/en-us/azure/sentinel/connect-azure-security-center

**Comment by tarosler** [comment]
Hi @ricohomewood ,
The 'ASCDataConnector' is the connector should be used to stream Azure Defender alerts to Sentinel - it is already supported in the API.

Thanks,
Tal Rosler.

**Comment by DavidTrigano** [comment]
@ruowan you can go ahead and close this ticket
