### ISSUE TITLE
AutoRest azure-validator erroneously fails on core version ~2.0.4413 but not ^3.2.0

### ISSUE THREAD

**Issue by forteddyt** [Azure/azure-rest-api-specs#15654]
PR in question: https://github.com/Azure/azure-rest-api-specs/pull/15439
LintDiff Logs in question: https://github.com/Azure/azure-rest-api-specs/pull/15439/checks?check_run_id=3333578400
Fails with: `"Text": "Error: '$.definitions.Identity.properties.type.enum' has incompatible values (---\n- SystemAssigned\n- 'SystemAssigned,UserAssigned'\n- UserAssigned\n- None\n, ---\n- SystemAssigned\n)."`

The issue lies in [machineLearningServices' ResourceIdentityType enum](https://github.com/Azure/azure-rest-api-specs/blob/c340804c71501fdd95f72ef09700aec4b28d0592/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-10-01/machineLearningServices.json#L2897) sharing the same name as [common-types' ResourceIdentityType enum](https://github.com/Azure/azure-rest-api-specs/blob/c340804c71501fdd95f72ef09700aec4b28d0592/specification/common-types/resource-management/v2/types.json#L248). However, common-types' Identity definition is not referenced (neither directly not indirectly) anywhere in any of the specs defined in the readme.md. Interestingly, removing the [reference to Identity from ResourceModelWithAllowedPropertySet](https://github.com/Azure/azure-rest-api-specs/blob/c340804c71501fdd95f72ef09700aec4b28d0592/specification/common-types/resource-management/v2/types.json#L163-L169) resolves this issue. ResourceModelWithAllowedPropertySet **is not** referenced in any of the specs.

Running the validation command with `--v3` (which uses AutoRest core version `^3.2.0`, as opposed to AutoRest core version `~2.0.4413`) does not produce this failure.

```
autorest --validation --azure-validator --v3 --semantic-validator=false --model-validator=false --message-format=json --openapi-type=arm --use=@microsoft.azure/classic-openapi-validator@1.1.10 --use=@microsoft.azure/openapi-validator@1.10.1 --tag=package-2021-10-01 readme.md
```

Because of these reasons, I think this might be an issue with autorest core version `~2.0.4413`. `~2.0.4413` is used in the LintDiff pipeline. The client generation gates also does not seem to use a 3.x version, as they are failing with the same issue.

**Comment by jianyexi** [comment]
@forteddyt  this is a autorest v2 issue, as it failed within the autorest , not in the azure-validator, could  you please file a issue to autorest ?

**Comment by forteddyt** [comment]
@jianyexi sure - am I supposed to file the issue here: https://github.com/Azure/autorest?

Also, why does the azure-validator (and the validation gates in general, I guess) use AutoRest core version 2.x, instead of 3.x?

**Comment by jianyexi** [comment]
> @jianyexi Jianye Xi FTE sure - am I supposed to file the issue here: https://github.com/Azure/autorest?
> 
> Also, why does the azure-validator (and the validation gates in general, I guess) use AutoRest core version 2.x, instead of 3.x?

Yes,  because the autorest v3 has many breaking changes against v2, we can't upgrade it to v3

**Comment by forteddyt** [comment]
I see, that's unfortunate. I've opened up an issue, I'll close this one

https://github.com/Azure/autorest/issues/4262

**Comment by forteddyt** [comment]
Also to temporarily side-step this issue, I'm going to remove the [reference to Identity from ResourceModelWithAllowedPropertySet](https://github.com/Azure/azure-rest-api-specs/blob/c340804c71501fdd95f72ef09700aec4b28d0592/specification/common-types/resource-management/v2/types.json#L163-L169).
