### ISSUE TITLE
Is discriminator property a string or an enum?

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1565]
Which is the ideal way to express discriminators?
Some swaggers express them as [strings](https://github.com/Azure/azure-rest-api-specs/blob/461a494ef3ba48dcd5bfe77dfee2dc943405f337/specification/monitor/resource-manager/microsoft.insights/2016-03-01/alertRules_API.json#L461), and others as [enums](https://github.com/Azure/azure-rest-api-specs/blob/d562b7da2ed3ee6c9ea822f1053170882b4ec9f9/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/2017-04-30-preview/postgresql.json#L898). I would like them to be consistent.

**Comment by lmazuel** [comment]
Just my two cents on this. By definition a discriminator should have a fixed set of values (in Python at least, we fail if we get a discriminator value from the RestAPI that is not defined in the Swagger). Seems a good candidate for an enum indeed :)
About updating current Swaggers however, I guess it will create a breaking change in most of the languages, if we update from string to enum. In Python it will not if we use `x-ms-model-as-string=True`

**Comment by mcardosos** [comment]
I like the idea to have them as enums so you can choose, but there could be inconsistencies inside swaggers. For example, a derived type which's discriminator was not included on the enum, or the enum having values which models are not defined anywhere. ]My guess is the swagger validator could catch this kind of issues.

**Comment by veronicagg** [comment]
@lmazuel I have to think about this. Tagging a few folks that may have thoughts on this @johanste @amarzavery @vishrutshah @jianghaolu

**Comment by vishrutshah** [comment]
From the swagger 2.0 [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13) perspective, it should be `string` type. I agree that having it enum would be advantageous for SDK but from the swagger perspective, I'd keep it `string` to be precise by the specifications :) Thoughts?

**Comment by mcardosos** [comment]
@jhendrixMSFT @marstr for the curiosity
