### ISSUE TITLE
R3011 check being applied to examples where property name is "Description"

### ISSUE THREAD

**Issue by forteddyt** [Azure/azure-rest-api-specs#15663]
PR in question: #15439
LintDiff gate: https://github.com/Azure/azure-rest-api-specs/pull/15439/checks?check_run_id=3341238861
Fails with: `Description must not match the name of the node it is supposed to describe. Node name:'string' Description:'string'`

Our service has a few definitions where "Description" is a property, [BatchDeployment.Description](https://github.com/Azure/azure-rest-api-specs/blob/8a45cc6963e9363b7cdc6757f5335915d02f1bfb/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-10-01/mfe.json#L5324-L5328), for example. The issue is that the [R3011](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#R3011) check is being applied to example files' request property. For example, the [BatchDeployment CreateOrUpdate _example_](https://github.com/Azure/azure-rest-api-specs/blob/8a45cc6963e9363b7cdc6757f5335915d02f1bfb/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-10-01/examples/BatchDeployment/createOrUpdate.json#L11) has `"description": "string"` in its request body. If I change this to something like `"description": "lorem ipsum"`, then the R3011 check will pass on that case.

Is the R3011 check supposed to be applied to example json requests? It seems like the point of R3011 is to ensure schema definitions have proper descriptions, so I think it is incorrect for R3011 to be applied to example json requests.

**Comment by jianyexi** [comment]
tracked with the https://github.com/Azure/azure-openapi-validator/issues/247
