### ISSUE TITLE
Cannot reference common-types SkuTier

### ISSUE THREAD

**Issue by forteddyt** [Azure/azure-rest-api-specs#15662]
PR in question: https://github.com/Azure/azure-rest-api-specs/pull/15439
Gate in question: https://github.com/Azure/azure-rest-api-specs/pull/15439/checks?check_run_id=3341255859 (and presumably all other client generation gates)

Our service references the [common-types Sku definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v2/types.json#L187-L226) for our TrackedResource definitions ([BatchDeploymentTrackedResource](https://github.com/Azure/azure-rest-api-specs/blob/8a45cc6963e9363b7cdc6757f5335915d02f1bfb/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-10-01/mfe.json#L5395-L5437) for example). We are trying to use specifically the [common-types SkuTier enum](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v2/types.json#L195-L208) in other definitions as well ([PartialSku](https://github.com/Azure/azure-rest-api-specs/blob/8a45cc6963e9363b7cdc6757f5335915d02f1bfb/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2021-10-01/mfe.json#L9037-L9064), for example). However, because SkuTier is defined inline as part of Sku we cannot reference that common-type.

Why isn't common-types SkuTier defined separately, as its own definition, so resources can reference it?

One solution would be to copy the SkuTier definition in our own schema, then reference that but... doesn't that go against the idea of having a set of common-types definitions?

**Comment by zhenglaizhang** [comment]
@fengzhou-msft @ArcturusZhang @archerzz  could you help take a look at the .NET SDK failure under https://github.com/Azure/azure-rest-api-specs/pull/15439/checks?check_run_id=3341255859, it looks like a bug 

```cmderr	[Autorest] FATAL: System.InvalidOperationException: Swagger document contains two or more x-ms-enum extensions with the same name 'SkuTier' and different values: Free,Basic,Standard,Premium vs. Free,Basic,Standard,Premium```

**Comment by forteddyt** [comment]
The issue is not with the generation. The generation fails correctly. mfe.json's SkuTier and common-types SkuTier definitions **are** different.

> Why isn't common-types SkuTier defined separately, as its own definition, so resources can reference it?

I'm mainly asking why common-types doesn't have their enums designed to be referenceable

**Comment by zhenglaizhang** [comment]
@forteddyt for SkuTier, service team use very different value set so it's not reasonable to define them as common types, and for historical reason, its model-as-string is set as false, updating it will resolve breaking changes, currently most service teams define their own SkuTier definitions based on their needs.
For you SDK failure, it's due to track1 common issue. I talked with SDK owner, you need to set model-as-string as false or replace SkuTier with different name to get the SDK gen succeeded.

**Comment by forteddyt** [comment]
@zhenglaizhang 
> for SkuTier, service team use very different value set so it's not reasonable to define them as common types

This does not make sense. It's completely reasonable to define SkuTier as in common types, because for services that reference common-types "Sku" **it already is**. Any service team that references common-types "Sku" is automatically restricted from defining an enum named SkuTier in their spec. Service teams that reference common-types "Sku" (like our team plans to), **cannot** use different SkuTier values, because the common-types "Sku" definition already defines what the SkuTier values are.

Service teams that choose to **not reference** the common-types "Sku" definition can use their own SkuTier, yes. Those services' scenarios wouldn't be affected by this change.

Moving SkuTier out into a definition (instead of an inline definition) doesn't add any new restrictions to service teams who choose to not reference common-types "Sku". NOT moving SkuTier out into a definition adds unnecessary clutter in the specs of service teams that want to use the common-types SkuTier definition.

To be clear, I'm suggesting refactoring common-types (or bumping it into a new version) from:
```json
{
  "Sku":{
    "properties":{
      "tier":{
        "type":"string",
        "enum":[
          "Free",
          "Basic",
          "Standard",
          "Premium"
        ],
        "x-ms-enum":{
          "name":"SkuTier",
          "modelAsString":false
        },
        "description":"This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT."
      }
    }
  }
}
```
to: 
```json
{
  "Sku":{
    "properties":{
      "tier":{
        "allOf":[ // Maybe the allOf isn't needed here, and we could "$ref":"#/definitions/SkuTier" directly?
          {
            "$ref":"#/definitions/SkuTier"
          }
        ]
      }
    }
  },
  "SkuTier":{
    "type":"string",
    "enum":[
      "Free",
      "Basic",
      "Standard",
      "Premium"
    ],
    "x-ms-enum":{
      "name":"SkuTier",
      "modelAsString":false
    },
    "description":"This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT."
  }
}
```

Forget the SDK gen failure. That is just a byproduct of the root issue that SkuTier is not referenceable by service team specs.

**Comment by zhenglaizhang** [comment]
@forteddyt thanks for your detail explanation, and we need consider more,
1. understand what's the most common value sets for SkuTier
2. evaluate if this change will cause downstream SDK gen breaking changes
3. the model as string is false in common types due to historical reasons, and we need figure out how to deal with it

**Comment by forteddyt** [comment]
@zhenglaizhang sounds great, thank you very much. Please keep me posted, as I'm very interested in the outcome of this. Additionally, I just want to clarify that I have no particular feelings about `"modelAsString"`. It being `true` or `false` is a separate topic and is not related to the original issue I'm trying to bring up

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang sounds great, thank you very much. Please keep me posted, as I'm very interested in the outcome of this. Additionally, I just want to clarify that I have no particular feelings about `"modelAsString"`. It being `true` or `false` is a separate topic and is not related to the original issue I'm trying to bring up

I verified in python and go sdk, it seems not breaking change to extract the def. I will create a PR to extract the def in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/types.json and loop sdk owners to review them
