### ISSUE TITLE
[DPS] REST API review for Azure IoT Device Provisioning Service (DPS)

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-rest-api-specs#15694]
- Service name: Azure IoT Device Provisioning Service (DPS)
- Key contact for the review: @lerubin, @anushr
- Whether this is a new or existing API: existing
- Whether or not your service already been deployed: already deployed
- A brief description of the material to be reviewed/changed: reviewing general conformity of the Data Plane service API to the Azure API Guidelines plus alignment with other IoT Services
- A link to the PR/issue in the azure-rest-api-specs (public)  or azure/azure-rest-api-specs-pr (private) repo:
  - [DPS DataPlane API Review by leigharubin · Pull Request #15621](https://github.com/Azure/azure-rest-api-specs/pull/15621)

**Comment by mikekistler** [comment]
My raw notes from the review session held August 18:

Already GA service for > 3 years

What are the main resources?

What are the hero scenarios?

Walk us through the APIs a customer would use in these.

Ted: relationship of ID in path of PUT to create vs ID in request body (not marked as readOnly)

Mixing well-known and additional properties is a headache.  Separate these out.

Ted: Format of date-time strings

Look at enum values - use x-ms-enum "modelAsString: true"

Ted: Error code is an int -- that's unusual
- six-digit error code that includes 3 digit HTTP status. Oi!

Why not just present a string code or error message?

Johan: At the very least we should improve the documentation to tell customers where to find the meaning of the values.

Etag - how is this intended to be used?

AdditionalProperties of type: object ?

If-match but not if-none-match
- if-none-match is important for PUT to make sure we don't overwrite an existing enrollment

Error model does not conform to the Azure standard.
- But is consistent with other APIs in the service that are already GA

Is Put for Create complete when the response is sent?

Why expose query if you don't support filtering?

If this API is already GA then don't change anything that is already GA.

Jing: How to format the API def to make sure it is Track2 compliant?
- More documentation is always a good thing.
- Non-standard error response will require some hand-editing to map to the standard SDK exceptions

IoT has its own little SDK team - David Williamson's team
- Rope in David to this discussion.

**Comment by mikekistler** [comment]
Apologies for the stream of consciousness above -- just wanted to make sure I captured everything.

@drwill-ms Pls see above and reach out if you have any questions.

**Comment by zhenglaizhang** [comment]
Hi @mikekistler I am triaging the issues as it's labeled as `needs-triage`, it looks like the issue is for notes, so I removed the label and assigned the issue to you.  Feel free to correct me if I understand incorrectly.
