### ISSUE TITLE
[cosmos]  `filter` parameter of example is not right

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-rest-api-specs#15875]
The example can't work: https://github.com/Azure/azure-rest-api-specs/blob/e1eca381eca8ec1f80b722e5dbf060fdeef48653/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/examples/CosmosDBDatabaseGetMetrics.json#L8

Example, the filter should be in the format as follow;
filter="(name.value eq 'Available Storage' or name.value eq 'Data Size' or name.value eq 'Index Size') and timeGrain eq duration'PT5M'")

So better to update it to avoid mislead customers.

(related issue: https://github.com/Azure/azure-sdk-for-python/issues/20472)

**Comment by pjohari-ms** [comment]
Closing this issue as the related issue seems to be fixed.
