### ISSUE TITLE
SecurityRule sourceAddressPrefix and destinationAddressPrefix should not be required

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1591]
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/networkSecurityGroup.json#L663

For the following property pairs:
sourceAddressPrefix/sourceAddressPrefixes
destinationAddressPrefix/destinationAddressPrefixes

according to the PM, the user must supply one or the other. However, the swagger lists the singular versions as required, resulting in errors being thrown by the SDK when the user tries to supply only the plural.

**Comment by dsgouda** [comment]
@tjprescott can you check if the issue still exists? Please reopen and link the correct location
