### ISSUE TITLE
Incorrect data type for Cosmos SQL RoleDefinitionType 

### ISSUE THREAD

**Issue by jarrodd07** [Azure/azure-rest-api-specs#16003]
The swagger spec for the Cosmos SQL Role Definition Type is incorrect. The spec specifies that the data type is a string, but an integer value is being returned in the response. 

Link to value in spec: https://github.com/Azure/azure-rest-api-specs/blob/44017a20d8c022217b31e15643595fc7aff87926/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/rbac.json#L407

Related issue in Go SDK: https://github.com/Azure/azure-sdk-for-go/issues/15295

**Comment by ruowan** [comment]
@ArcturusZhang This issue related with go sdk issue. Help to take a look.

**Comment by nichatur** [comment]
Thanks for bringing this up. We have a fix out for returning the string instead of the int from the service side.

**Comment by jarrodd07** [comment]
Hey @nichatur, has this fix been deployed? I'm still getting the same error when calling this service using the go sdk.

**Comment by jarrodd07** [comment]
Hey @nichatur, can this issue please be re-opened? I have just retested this and I am still getting the same error from the go sdk.

**Comment by jarrodd07** [comment]
Hi @nichatur @lilyjma this issue is still not fixed and is blocking Cosmos role assignments from being added to the terraform provider. Could this issue be left open and only closed when it has actually been fixed?

**Comment by lilyjma** [comment]
Reopening issue per request.
@nichatur could you take a look when you get a chance?

**Comment by nichatur** [comment]
The fix for this is still in our deployment pipeline. It is part of our 1101 payload which is expected to deploy in the first month of next year.
The change was created in September, but deployment delays have led it to not be available in production. Apologies for the delay. Will keep this issue open and close once the fix deploys.

**Comment by jarrodd07** [comment]
Thanks both 👍

**Comment by pjohari-ms** [comment]
This issue has been fixed. Closing the issue.
