### ISSUE TITLE
The :analyze-conversation response does not properly discriminate response types

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#16055]
https://github.com/Azure/azure-rest-api-specs/blob/b37a9e7c4a87f6eee629093ea4437a166e29ce70/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/analyzeconversations.json#L274-L277

I'm still not entirely clear on the fix and having internal conversations with folks on the AutoRest and AutoRest.Csharp teams. I've compared with Cognitive Search that does the same thing (and generates the right code) but not seeing a significant difference. Their discriminators are just plain strings, but I used a swagger transform to do the same to your swagger and, while it impacted the generated code, it just changed the property type and did not fix the discrimination.

**Comment by heaths** [comment]
@ChongTang any status update on this one?

**Comment by ChongTang** [comment]
@heaths, Sorry I missed this one. I am not sure I understand the issue. Do you mean the type of the children classes are not fixed on this "did not fix the discrimination."?

**Comment by heaths** [comment]
Searching through chats, this may have been a non-issue/misunderstanding on my part, or was already resolved.

Based on https://github.com/Azure/azure-sdk-for-net/blob/35da34648d13abddacf022c6d0925f5464c78194/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Generated/Models/AnalyzeConversationResult.Serialization.cs#L34-L35 and https://github.com/Azure/azure-sdk-for-net/blob/35da34648d13abddacf022c6d0925f5464c78194/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Generated/Models/BasePrediction.Serialization.cs#L19-L23 this doesn't appear to be an issue now (and maybe never was).

**Comment by heaths** [comment]
@AhmedLeithy @ZulaMostafa just in case you see any issues with model discrimination, something to keep in mind. I don't think you will, though. I think this issue was just a result of my misunderstanding of what was expected in generated code.
