### ISSUE TITLE
Method and model renames for Conversation Analysis

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#16051]
While working on the .NET SDK, besides #16050 I found a few other nits we may want to change in the swagger:

1. Rename the [`ConversationAnalysis_AnalyzeConversations`](https://github.com/Azure/azure-rest-api-specs/blob/b37a9e7c4a87f6eee629093ea4437a166e29ce70/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/analyzeconversations.json#L33) operation ID to be singular since only a single query is involved, i.e. should be `ConversationAnalysis_AnalyzeConversation`.
2. Across our typed language SDKs, we want the options bag to match the method name, so related to the first issue above, the model [`ConversationAnalysisInput`](https://github.com/Azure/azure-rest-api-specs/blob/b37a9e7c4a87f6eee629093ea4437a166e29ce70/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/analyzeconversations.json#L92) should be renamed - and can safely be so, since model names are not in the JSON payload - to `AnalyzeConversationOptions`.
3. Similarly, [`ConversationAnalysisResult`](https://github.com/Azure/azure-rest-api-specs/blob/b37a9e7c4a87f6eee629093ea4437a166e29ce70/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/analyzeconversations.json#L258) should be `AnalyzeConversationResult`.

/cc @annatisch

**Comment by heaths** [comment]
Generally, the close aligned the REST APIs and SDK APIs are, the better off our customers are. Not only does it mean faster code generation for new APIs and easier maintenance, but decreases customer confusion. I've worked on services where the SDK and REST APIs are very different and it does cause confusion about how the SDKs and REST APIs align.

**Comment by ChongTang** [comment]
Resolved in PR: https://github.com/Azure/azure-rest-api-specs/pull/16058

**Comment by heaths** [comment]
Tip: in your PR description, add keywords like "resolves" or "resolve", or "fixes", "fixed", or "fix" and the issue number like "Fixes #16058" and when you merge the PR, it automatically closes the bug. You can also set up that association later in the PR:

![image](https://user-images.githubusercontent.com/1532486/133703169-259523a3-fe95-41f0-996d-20b9fdd0efa4.png)

Not a big deal. Just closes the issue automatically so someone doesn't have to remember to later. 🙂
