### ISSUE TITLE
projectName and deploymentName should use the parameters from the common.json swagger

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#16050]
https://github.com/Azure/azure-rest-api-specs/blob/b37a9e7c4a87f6eee629093ea4437a166e29ce70/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/analyzeconversations.json#L35-L49

See [questionanswering.json](https://github.com/Azure/azure-rest-api-specs/blob/70de88e5fb00b9217a5cafd3c1bed11ce311fc52/specification/cognitiveservices/data-plane/Language/preview/2021-05-01-preview/questionanswering.json#L38-L43) for what they did:

```json
          {
            "$ref": "common.json#/parameters/ProjectNameQueryParameter"
          },
          {
            "$ref": "common.json#/parameters/DeploymentNameQueryParameter"
          },
```

`deploymentName`, for example, should be optional and the service should default that to "prod", most likely.

/cc @annatisch

**Comment by ChongTang** [comment]
Fixed in this PR: https://github.com/Azure/azure-rest-api-specs/pull/16036
