### ISSUE TITLE
extendedlocation type for appservice should not be readonly

### ISSUE THREAD

**Issue by njuCZ** [Azure/azure-rest-api-specs#16087]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/CommonDefinitions.json#L1164 

the `type` property is marked as `readonly`, but actually when creating an app service on arc, users need to input this field. Otherwise the backend server will report  error.

please remove the `readonly`

**Comment by naveedaz** [comment]
@vinisoto  Can you please help fix this issue? Apparently, the generated swagger does not have the read-only tag, but the one in the swagger github repo does.

**Comment by vinisoto** [comment]
Hey @naveedaz. Hong's team is now looking at all Arc related items.

@howang-ms can you please assign someone from your team to take a look at this? (it is from September 2021 so probably it is already fixed?)
