### ISSUE TITLE
[SQL] SQL Data Warehouse 

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1609]
:wave:

In [the SQL Databases Swagger](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/sql/resource-manager/Microsoft.Sql/2014-04-01/sql.core.json#L2180) / SDK's - there's properties for setting the `ServiceObjectiveName` field to the following values:

- Basic
- ElasticPool
- P1
- P11
- P15
- P2
- P3
- P4
- P6
- S0
- S1
- S2
- S3
- System
- System2

However there's items missing from this list required for configuring the Data Warehouse, including (but not limited too) `DW400`.

Would it be possible to confirm which items are missing - and get them added to the Swagger? Looking at the list I'd assume that P5 & P7-10 are missing, but I may be wrong ¯\_(ツ)_/¯

Thanks!

**Comment by fearthecowboy** [comment]
Hey @jaredmoo or @nathannfan -- Can you look into this?

**Comment by jaredmoo** [comment]
Will do, although you should know that the canonical list of service objectives is determined using the capabilities API: https://github.com/Azure/azure-rest-api-specs/blob/current/specification/sql/resource-manager/Microsoft.Sql/2014-04-01/capabilities.json#L19

**Comment by tombuildsstuff** [comment]
ping @jaredmoo - is there any update available here? :)

**Comment by jaredmoo** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/3955

**Comment by jaredmoo** [comment]
Fixes have been merged into azure-rest-api-specs and azure-sdk-for-net.

**Comment by tombuildsstuff** [comment]
@jaredmoo thanks for confirming that - I've confirmed that this exists in [the Go SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/sql/mgmt/2014-04-01/sql/models.go#L261) and as such I'm going to close this issue.

Thanks!
