### ISSUE TITLE
[Unified Language Service] API Review - ExtraInformation Parameter in Entity Response Object

### ISSUE THREAD

**Issue by hazemelh** [Azure/azure-rest-api-specs#16138]
We are appending a parameter called extraInformation to our entity object response in a preview API in Language Cognitive Services, PR TBD.

The parameter is an array of objects with discriminator "kind" parameters that determine the type of the extra information being appended to the entity.

More details: https://microsoft-my.sharepoint.com/:w:/p/haelhamm/EUvSafGbrMtHicoh-OwrRAgBsNIX3heRzbOQ7f0QFYCjlw?e=4f6a1t

**Comment by hazemelh** [comment]
Please add 
APIStewardshipBoard-ReveiwRequested label

**Comment by markweitzel** [comment]
# API Stewardship Board Review 30-Sept-21
