### ISSUE TITLE
Key Vault: ARM template support for Azure Key Vault backup

### ISSUE THREAD

**Issue by sdandu21** [Azure/azure-rest-api-specs#16142]
Is there an equivalent for these Key Vault operations (Azure Key Vault backup) in Arm Templates? https://docs.microsoft.com/en-us/azure/key-vault/general/backup?tabs=azure-cli#back-up-and-restore-from-the-azure-cli-or-azure-powershell

**Comment by sebansal** [comment]
Key Vault offers individual object level backup/restore and that is a data plane operation, not ARM.
