### ISSUE TITLE
Usage properties in Network SDK should be converted to double

### ISSUE THREAD

**Issue by DeepakRajendranMsft** [Azure/azure-rest-api-specs#1624]
currentValue and Limits are declared as int64. they should be declared as double (on the service they are declared as double)

**Comment by DeepakRajendranMsft** [comment]
@EvgenyAgafonchikov  please do this is on the sdk and PS after 9/25

**Comment by mblaschke** [comment]
Still breaking the api. Any news on this topic?

**Comment by yungezz** [comment]
based on https://github.com/Azure/azure-rest-api-specs/issues/2366#issuecomment-438414616, issue is fixed.
