### ISSUE TITLE
ServicePrincipalCredentialEnum has wrong type

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-rest-api-specs#16242]
https://github.com/Azure/azure-rest-api-specs/blob/fd7603f9a8acb1decf94f7770a0bfe7b78df9b20/specification/synapse/data-plane/Microsoft.Synapse/preview/2021-06-01-preview/entityTypes/LinkedService.json#L758

Type should be `string`

**Comment by annelo-msft** [comment]
@idear1203, @wonner, would it be possible for one of you to update this type?

**Comment by annelo-msft** [comment]
@lmazuel FYI

**Comment by wonner** [comment]
Resolved in PR: https://github.com/Azure/azure-rest-api-specs/pull/16322
