### ISSUE TITLE
ENUM_MISMATCH validation has wrong description in reference markdown file

### ISSUE THREAD

**Issue by avjerafi** [Azure/azure-rest-api-specs#16294]
At https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/Semantic-and-Model-Violations-Reference.md#ENUM_MISMATCH:

The ENUM_MISMATCH validation description uses a verbatim copy of the ENUM_CASE_MISMATCH description.

**Comment by raych1** [comment]
Thanks for reporting this issue, fixed in [PR](https://github.com/Azure/azure-rest-api-specs/pull/16351)
