### ISSUE TITLE
Description of this API is misleading as this API get a list of tracked resources only 

### ISSUE THREAD

**Issue by ouldsid** [Azure/azure-rest-api-specs#16368]
https://github.com/Azure/azure-rest-api-specs/blob/cac541467ac851bee43f5abd6d528db3797c2f09/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L2938

**Comment by tim-nguyen-cs** [comment]
Hi @zhenglaizhang - I can address this. What about the description is misleading?  Is there a distinction between "tracked" and "untracked" resources?
