### ISSUE TITLE
[Network] Certain ExpressRoute parameters should be marked read-only

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#1649]
Currenly only `eTag` is flagged as read-only in Swagger.  According to the ExpressRoutes team, the following fields are also read only:

- [ ] MicrosoftPeeringConfig.legacyMode
- [ ] MicrosoftPeeringConfig.advertisedCommunities
- [ ] MicrosoftPeeringConfig.advertisedPublicPrefixState
- [ ] ipv6PeeringConfig.state

**Comment by yungezz** [comment]
Netwokr team is fixing their swagger file, first issue is to make readonly property as readonly. PR https://github.com/Azure/azure-rest-api-specs/pull/7488 . They plan to put all swagger fix in oct 2019 release. we're working with them on reviewing and fixing. close this issue.
