### ISSUE TITLE
[Service Fabrid] 8.2 spec

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#16530]
Service name : Service Fabric
Key contact for the review : Jeffrey Jarry (jejarry)
Whether this is a new or existing API : Existing API with new version
Whether or not your service already been deployed : Yes
A brief description of the material to be reviewed/changed : A small subset of our API has been updated with new fields
A link to the PR/issue in the azure-rest-api-specs (public) or azure/azure-rest-api-specs-pr (private) repo #16498

**Comment by markweitzel** [comment]
# API Stewardship Board Review:  3-Nov-21

Because this is an existing service, there will be little impact that we will be able to make, in part b/c we want to be consistent with the entirety of the service. The changes in this version are small, only one new operation and adding minor updates to the others.

**Comment by jeffj6123** [comment]
@markweitzel is this PR ok to be merged?

**Comment by markweitzel** [comment]
@jeffj6123 -- From the perspective of the API Stewardship Board, yes. The Azure SDK team may have a few separate concerns as well though. Note: I do not have commit rights on this repo so we will need to coordinate with @lmazuel and team. Happy to help there.
