### ISSUE TITLE
[cosmos-db] incorrect `type` definition in `SqlRoleDefinitionResource`

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-rest-api-specs#16560]
# Description

According to the [definition of SqlRoleDefinitionResource](https://github.com/Azure/azure-rest-api-specs/blob/f780b571abddf2fc99233212a00510d3bef6878d/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/rbac.json#L407), the `type` property should be a string.

The[ corresponding example](https://github.com/Azure/azure-rest-api-specs/blob/f780b571abddf2fc99233212a00510d3bef6878d/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-06-15/examples/CosmosDBSqlRoleDefinitionCreateUpdate.json#L11) also verify that. See the type property in both request and response.

However, in reality:
- the `type` value in request (e.g. when used in [SqlRoleDefinitionCreateUpdateParameters](https://github.com/Azure/azure-rest-api-specs/blob/6515578b7e6989fd9a1bb513486b381e72fa81c0/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/rbac.json#L436))  is a **string**. 
```json
{
  "properties": {
    "roleName": "xxxxxxx",
    "type": "CustomRole", // This is a string aligned with definition
    "assignableScopes": [
      "/subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.DocumentDB/databaseAccounts/dbaccount-xxxxx/dbs/sql-db-xxxx"
    ],
    "permissions": [
      {
        "dataActions": [
          "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/create"
        ]
      }
    ]
  }
}
```
- the `type` value in response (e.g. when used in [SqlRoleDefinitionGetResults](https://github.com/Azure/azure-rest-api-specs/blob/6515578b7e6989fd9a1bb513486b381e72fa81c0/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/rbac.json#L447)) is an **integer**
```json
{
  "id": "/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.DocumentDB/databaseAccounts/dbaccount-xxxx/sqlRoleDefinitions/xxxx",
  "name": "xxxxx",
  "properties": {
    "roleName": "xxxx",
    "type": 1, // Now it becomes an integer
    "assignableScopes": [
      "/subscriptionsxxxx/resourceGroups/xxxxx/providers/Microsoft.DocumentDB/databaseAccounts/dbaccount-xxxx/dbs/sql-db-xxxx"
    ],
    "permissions": [
      {
        "dataActions": [
          "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/create"
        ],
        "notDataActions": []
      }
    ]
  },
  "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions"
}
```

Looks like the server side returns a response with wrong type.

**Comment by Carike** [comment]
Hi @msftbot, @wmengmsft & @MehaKaushik 

Do you perhaps have an update or estimated date to resolve issue #16560 ?

It is currently blocking #13907 , which we are dependent on. 

Thank you very much in advance!

**Comment by gsadhana** [comment]
Any update on when this will get resolved? It's blocking https://github.com/hashicorp/terraform-provider-azurerm/issues/13907, which is pretty important for CosmosDB RBAC access. Thank you.

**Comment by geriamir** [comment]
Hi, any update?

**Comment by nichatur** [comment]
The fix has been deployed and is live in Production.

![image](https://user-images.githubusercontent.com/69816349/155217619-f0b34b0a-c4ea-40cd-9318-11b517aaed5c.png)
