### ISSUE TITLE
Allow App Gateway creation without specifying all properties

### ISSUE THREAD

**Issue by sirsnork** [Azure/azure-rest-api-specs#16703]
I'm using Terraform to build out Azure infrastructure but my absolute biggest pain point is App Gateways. You have to specify all the listeners/rules/IP's in a single resource. This leads to 1000+ line terraform files that just create an App Gateway. It also makes it impossible to cleanly add a new service behind the app gateway because the only way to add anew listener and rules is to edit the app gateway resource that already exist, rather than being able to just add new resources to it.

Please allow the creation of an App Gateway with no (or very minimum resources to allow Terraform to break out listeners and rules (and ideally everything else) so they can be maintained as separate resources. 

See https://github.com/hashicorp/terraform-provider-azurerm/issues/14076 for the TF issue

Thanks

**Comment by JackStromberg** [comment]
Hi @sirsnork, appreciate the feedback!  We are aware of this experience and hope to improve it as part of our long-term efforts.  Unfortunately, I don't have any dates I can share, but we do agree in the value of providing additional endpoints vs a single PUT call to make changes to the gateway.

Thank you!
#please-close
