### ISSUE TITLE
[Document Translator] REST API Review for Document Batch Translator API v1.1

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#16794]
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/16705
        
 Service name: Document Batch Translator
    
Key contact for this review: alcheng;faanis
    
Are you in the PST time zone? If not, what time zone are you in? PST;Eastern European Time (Egypt = UTC+2)
    
Is this a new API or the first API for the service?  No
    
Link to previous API version
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/TranslatorText/stable/v1.0    
    
Has your service already been deployed?
No
    
Description of the material to be reviewed/changed: 
https://microsoft-my.sharepoint.com/:w:/p/faanis/ES4dpXMEuc5IjGeTXMA6iwMBqstA6zvTV09h2XgZT8LI9A?e=gI8OiY

**Comment by markweitzel** [comment]
# API Stewardship Meeting 1-Dec-21

The main motivation for adding this field is for discovery of the @failedDocumentStatus endpoint. 
* Could we add some better documentation around this pattern in the quickstarts?
  * The examples in the quickstarts don't leverage the SDKs--shows raw code that don't show the pattern we'd like to promote. 
* remove the "@" in as the leading character in `@failedDocumentStatusLink`

> The standard pattern for "jump off to find the actual results for the LRO" is to have a `resourceLocation` attribute with the link. It would have the full set of results, though - whereas the current proposed failed results location filters on only the failed docs.

For the Word conversion API
* Consider restructuring this to have an extensible enum, with "WORD" and "NONE" as the only options.  "NONE" would be the default. This will add a bit of "future proofing"
* The options for converting the document to word should be at the target level. This could also be done at the input/job level. You should make the call based on what they see their customers doing most so long as we could version in more flexibility over time.

## References 
* [Document Translation Docs](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/reference/rest-api-guide)
* [Recording link]()
