### ISSUE TITLE
TimeSeriesInsights: Conflicting properties in inheritance chain

### ISSUE THREAD

**Issue by olydis** [Azure/azure-rest-api-specs#1683]
The [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/2017-02-28-preview/timeseriesinsights.json) has the following type situation:

Type `IoTHubEventSourceResource` has property `properties` of type `IoTHubEventSourceResourceProperties` and inherits from
type `EventSourceResource` that has property `properties` of type `EventSourceCommonProperties`

In one picture:
```
IoTHubEventSourceResource
	properties: IoTHubEventSourceResourceProperties

---inherits from---

EventSourceResource
	properties: EventSourceCommonProperties
```

I'm aware that both `properties` properties are marked to be flattened *but* there are languages which don't support that and even if, this calls for a very complicated if not weird serialization/deserialization story (is stuff cherry picked out of the single `properties` object by both classes?).

For that reason (technically: there's conflicting property definitions of the same name in an inheritance chain), AutoRest fails to generate any code. To fix that:

1) Is this really what your service does? Just making sure, since that would be the easiest "solution" in this case 😄 
2) Model the types differently, e.g. only have the `properties` on one of the two types (presumably the base type) and put the union of both property-sets in there... a little ugly

Maybe there's more/better solutions to workaround the problem...

**Comment by mcardosos** [comment]
CC @sandshadow
