### ISSUE TITLE
[AppConfiguration] Response resource Id does not start with `/`

### ISSUE THREAD

**Issue by HarveyLink** [Azure/azure-rest-api-specs#16927]
### Already synced with Shuai Wang.

As the example: https://github.com/Azure/azure-rest-api-specs/blob/9f28b00aaee6d4360ac3dee7f9a10279f5d15568/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2020-06-01/examples/PrivateLinkResourcesListByConfigurationStore.json#L13
The resource Id in response should have `/` at the beginning, this is how the ARM define Resource Id
The actual result doesn't follow this rule:
Example operation:
https://github.com/Azure/azure-rest-api-specs/blob/a7e864e0ea1b7a3133d3f1def968985d117aa2f2/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2020-06-01/appconfiguration.json#L766
![response](https://user-images.githubusercontent.com/30464227/144191700-b1a2bf0d-ac76-4f51-bfbe-7a492864d096.png)

**Comment by shenmuxiaosen** [comment]
We are rolling out the fix. It should be done by the end of next week (12/10).

**Comment by HarveyLink** [comment]
Verify fixed in latset version. Issue closed.
