### ISSUE TITLE
[Cognitive Services] REST API Review for Personalizer

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#16982]
Review scheduled by Sharath Malladi for 12/9 at 4pm PDT

Question 1- Service Name: Please paste service name in the name field above. Please provide the name that matches the GitHub repo path.
Answer- TBD
Question 2- Has your service already been deployed?
Answer- No
Question 3- Is this a new or existing API?
Answer- New
Question 4- Key contact for the review. Please provide name and email of all attendees (be sure to forward this invite).
Answer- sharathm@microsoft.com
Question 5- Please provide a link to your REST API Review PR (Pull Request).
Answer- TBD
Question 6- Provide a description of the material to be reviewed/changed. Provide a description or a link to the section of the API to be reviewed.
Answer- The customer can upload a model to Personalizer that can replace their existing model.
Question 7- Provide a link to the PR/issue in the azure-rest-api-specs (public) or azure/azure-rest-api-specs-pr (private) repo.
Answer- TBD

**Comment by markweitzel** [comment]
# API Stewardship Review 9-Dec-21

`PUT` `/model`
* Usually we see something like `/models/{modelId}`
* No need to support conditional headers to avoid stomping and optimistic concurrency e.g. `if-none-match`  -- last one in wins is OK.


## Versioning
There is a potential for "round-tripping" problems--where the service evolves in a way that does not support older models. The key is for the service to be forward compatible. 
* For example, can a v1 model work with v5 of the service? 
* Ted mentioned the idea of storing the models in source control and then reloading them 

## Misc 
* `DELETE` is a bit odd b/c it doesn't really "delete" the resource, it replaces it with an empty model. So, it's a delete by replacing it with an empty value. 
* Where possible, be deterministic, versus relying on a heuristic to determine the model. For example, we use vowpalwabbit today but might want to switch to DeepRL or other technologies that don't yet exist in the next couple of years to stay competitive. 

## Action Items
* Verify that the API versions can properly handle model updates. See: [Versioning APIs](https://www.youtube.com/watch?v=xHJpKO9hN4Q)
* Touch base with the other cognitive services folks to review their model versioning schemes.

**Comment by czubair** [comment]
Review scheduled for 2/2.

**Comment by markweitzel** [comment]
## API Stewardship Review 2-Feb-2022

@sharathmalladi - There are a few things that I'd like to draw your attention to prior to the meeting.
* If you have not had the opportunity to review the [API Style Guideline](https://aka.ms/azapi/style) then it would be good to do so. You'll find a tool we are experimenting with, Spectral, that will help with some of the basic linting of your OpenAPI doc. For exmaple, using the `x-ms-error-code` header, and ensuring there are default responses for your operations. 
* Your [Developer documentation](https://review.docs.microsoft.com/en-us/rest/api/azure-rest-preview/?branch=result_7663e6a0-5d65-4dca-83fb-f4f85b6f4fc3&view=azure-rest-preview) is automatically generated from your OpenAPI definition. You can find it in the OpenAPI Bot that gets run. It would be good to make reviewing this generated artifact part of your API practice. 
![image](https://user-images.githubusercontent.com/522116/152186177-c23db3c2-bb22-4fb2-907c-7ef325e6bab4.png)


## References
[Meeting Chat]()
[Meeting Recording]()

**Comment by haocornell-ms** [comment]
One thing to consider is to add some metadata to a model so that customers have a way to associate inferences with specific model. This will be very helpful if a customer might try multiple models or there can be concurrent model update and inferences.

**Comment by sharathmalladi** [comment]
> One thing to consider is to add some metadata to a model so that customers have a way to associate inferences with specific model. This will be very helpful if a customer might try multiple models or there can be concurrent model update and inferences.

This api only allows the customers to export and import the current model which is used for inferencing. We don't support multiple inference models at the same time.
