### ISSUE TITLE
[Azure Maps] REST API reveiw for Azure Maps Weather - AirQuality, Historical, and Tropical

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#16993]
Question 1- Service Name: Please paste service name in the name field above. Please provide the name that matches the GitHub repo path. 
Answer- weather
Question 2- Has your service already been deployed?
Answer- yes
Question 3- Is this a new or existing API?
Answer- new API
Question 4- Key contact for the review. Please provide name and email of all attendees (be sure to forward this invite). 
Answer- Eva Ou, evaou@microsoft.com
Question 5- Please provide a link to your REST API Review PR (Pull Request). 
Answer- https://github.com/Azure/azure-rest-api-specs/pull/16802
Question 6- Provide a description of the material to be reviewed/changed. Provide a description or a link to the section of the API to be reviewed.
Answer- add new weather APIs including air quality, historical weather, and tropical storms.
Question 7- Provide a link to the PR/issue in the azure-rest-api-specs (public)  or azure/azure-rest-api-specs-pr (private) repo.
Answer- https://github.com/Azure/azure-rest-api-specs/pull/16802

**Comment by markweitzel** [comment]
# API Stewardship Board Review 14-Dec-22

Note: This API is based on [AccuWeather APIs | Tropical API](https://developer.accuweather.com/accuweather-tropical-api/apis)

**Comment by czubair** [comment]
2nd Review - 1/6 at 4pm PST

**Comment by markweitzel** [comment]
# API Stewardship Board Review 6-Jan-22

`query`
Should the parameter `query` be more specific, e.g. `location`?

## Versioning
If possible, consider using date based versioning as the query parameter. 
**Action:** @markweitzel will bring up with the API LT team if, b/c this is query parameter base, we should recommend date based or numeric.

## Handling Errors
See if you can match the recommended error structure. See: [Handling Errors](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#handling-errors)

There was a discussion around the plurals of `forecasts` vs. `forecast`. This is a case where this is a close representation of Accu-Weather (which uses plural `forecasts`).

**Comment by czubair** [comment]
Review (special session) scheduled for 1/20 at 5pm PST - pending board confirmation
