### ISSUE TITLE
[Communication Services] REST API Review for Roles & Permissions

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#17032]
Service name: Roles & Permissions

Key contact for the review:  samuel.savin@microsoft.com

The scenarios are:
Contoso’s administrator is creating the CommunicationRole for Contoso application.
Contoso’s administrator is editing a CommunicationRole and changing either it’s display name or assigned permissions
Contoso’s administrator is checking the list of available Role for Contoso applications and their assigned permissions

Link to the PR:   
https://github.com/Azure/azure-rest-api-specs/pull/16675

Links to swagger: 
https://github.com/Azure/azure-rest-api-specs/blob/7887caaaedb8a7e6f3406b209e1caf6d0de6a248/specification/communication/data-plane/role/preview/2022-01-01-preview/CommunicationRole.json

**Comment by markweitzel** [comment]
# API Stewardship Review 16-Dec-21

* Using `POST` for creation b/c of privacy concerns.
  * Recommendation: use `PUT` & `PATCH`
  * `displayName` could become the check for idempotency? Or... introduce a field like `name` that can be stored by the service that can be used as the key. 
  * Idempotency MUST be implemented
  * Use repeatability requests 

See: https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#http-request--response-pattern 
✔️ YOU MAY use POST to create a resource but you must make it idempotent and, of course, the response MUST return the URL of the created resource with a 201-Created. One way to make POST idempotent is to use the Repeatability-Request-ID & Repeatability-First-Sent headers (See Repeatability of requests).

* Be careful exposing GUIDs as these are not the most developer friendly.

* `PATCH` `/roles/{id}`
  * The concern here is that the entire array is replaced on the `PATCH` and the entire set of permissions would be replaced. 
  * You should ensure you have conditional access headers, e.g. `if-match`, in place to avoid the "last writer" wins scenario. (Or `ETag`)
     * If you use `ETag` add this to all your return values.  
  * It is **STRONGLY RECOMMENDED** to avoid network (pessimistic) locking in favor of optimistic concurrency strategies.
  > Backend leases are super difficult/expensive to implement as well.  etags are significantly cheaper. Also, a backend lease sounds like it'd be per-request which still doesn't help the GET then PATCH roundtrip scenario when someone else does a PATCH in between those two?

**Comment by SamuelSA** [comment]
Updated the PR according to the above comments:
- Fixed the filter 1 nextLink fields
- Added 2-steps delete feature
- Fixed lowercase 'role' folder name
- Fixed typo in 'example' folder name
- Added ETag-based conditional access on APIs

The idempotency topic as the linked subjects are still under discussion so I left those sections untouched.

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
