### ISSUE TITLE
Missing "remoteAddressSpace" in Network "virtualNetworkPeerings"

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1704]
[According to a customer](https://github.com/Azure/azure-sdk-for-python/pull/1453), the JSON returned is:
```json
   {
      "name": "myNetworkName",
      "id": "/subscriptions/[subscription_id]/resourceGroups/[resource_group]/providers/Microsoft.Network/virtualNetworks/[vnet]/virtualNetworkPeerings/[remote_network_name]",
      "etag": "W/\"[remote_network_id]\"",
      "properties": {
        "provisioningState": "Succeeded",
        "peeringState": "Connected",
        "remoteVirtualNetwork": {
          "id": "/subscriptions/[remote_network_id]/resourceGroups/[remote_resource_group]/providers/Microsoft.Network/virtualNetworks/[remote_network_name]"
        },
        "allowVirtualNetworkAccess": true,
        "allowForwardedTraffic": true,
        "allowGatewayTransit": false,
        "useRemoteGateways": false,
        "remoteAddressSpace": {
          "addressPrefixes": [
            "10.45.170.0/24",
            "10.45.171.0/24",
            "10.45.172.0/24",
            "10.45.173.0/24"
          ]
        }
      }
    },
```
And `remoteAddressSpace` is not defined in the Swagger, then not available as an attribute.

**Comment by cr41gc** [comment]
@jianghaolu, it seems all that's missing is:

specification/network/resource-manager/Microsoft.Network/2017-09-01/virtualNetwork.json
```
@@ -897,6 +897,10 @@
           "$ref": "./network.json#/definitions/SubResource",
           "description": "The reference of the remote virtual network. The remote virtual network can be in the same or different region (preview). See here to register for the preview and learn more (https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-create-peering)."
         },
+        "remoteAddressSpace": {
+          "$ref": "#/definitions/AddressSpace",
+          "description": "The reference of the remote virtual network address space."
+        },
         "peeringState": {
           "type": "string",
           "description": "The status of the virtual network peering. Possible values are 'Initiated', 'Connected', and 'Disconnected'.",
```

**Comment by jianghaolu** [comment]
Assigned to network team. Sorry for the delay.

**Comment by gmainar** [comment]
Hi,
I don’t understand what is this or what is it assigned to me. Can you give me some context?

Thanks,
Gloria

**Comment by jianghaolu** [comment]
Hi @gmainar 

Seems like a customer is complaining that an available property in the response payload is not defined in the Swagger. I added you since you've made significant changes to the Network space. Please feel free to re-assign if someone else should be the owner of this issue.

**Comment by cr41gc** [comment]
`remoteAddressSpace` shows up in the REST response, but isn't available in the Python-SDK. From what I understand, the python-sdk is auto-generated from the OpenAPI, and the property needs to be defined in this project to be automatically pulled into the SDKs.

See the referenced issue for details.

**Comment by DeepakRajendranMsft** [comment]
@EvgenyAgafonchikov  please take a look at this and fix it. lets push it into 2017-10-01

As @cr41gc mentioned, we have to add
"remoteAddressSpace": {
+          "$ref": "#/definitions/AddressSpace",
+          "description": "The reference of the remote virtual network address space."
+        },
