### ISSUE TITLE
`Microsoft.DataFactory/Dataset`: enum values removal of compressionType is causing issue to the dependency resources

### ISSUE THREAD

**Issue by xiaxyi** [Azure/azure-rest-api-specs#17043]
PR #16563  deleted some enum values of compressionType and the removal is causing compiling issues of the dependency resource.

**Comment by Frey-Wang** [comment]
Hi @xiaxyi , PR #17036 adds these values back and is currently under review.

**Comment by Frey-Wang** [comment]
Sync offline, will not change. @xiaxyi @Jingshu923
