### ISSUE TITLE
Missing property in "Get information from template"

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#171]
Hi,

I currently need to get informations from a deployment, so I use:
https://msdn.microsoft.com/en-us/library/azure/dn790565.aspx

I discovered that the resulting JSON contains a `outputResources` node than the official documentation doesn't have:

``` json
"outputResources":[  
         {  
            "id":"Microsoft.Compute/virtualMachines/azlmaz3"
         },
         {  
            "id":"Microsoft.Compute/virtualMachines/azlmaz3/extensions/install_apache"
         },
         {  
            "id":"Microsoft.Compute/virtualMachines/memcached0"
         },
```

The information inside is very valuable for me! Since I use a Swagger generated client and since the Swagger file does not contain it neither, I cannot use it currently.

I can do a PR to add this node, but I would like someone from the Resource team to give a status about this node.

Thank you!

**Comment by devigned** [comment]
@ravbhatnagar @vivsriaus would you guys give this a look.

**Comment by salameer** [comment]
@ravbhatnagar @vivsriaus can we kindl get an update here?

**Comment by divyeshgohil85** [comment]
This `outputResources` is still not documented in https://docs.microsoft.com/en-us/rest/api/resources/deployments/listbyresourcegroup

**Comment by yungezz** [comment]
close legacy issue.
