### ISSUE TITLE
[Anomaly Detector]Root Cause Analysis API

### ISSUE THREAD

**Issue by suxi-ms** [Azure/azure-rest-api-specs#17106]
• Service name:  Anomaly Detector
• Key contact for the review:  suxi@microsoft.com
• Whether this is a new or existing API:  This is a set of new API
• Whether or not your service already been deployed:   Hasn't been deployed
• A brief description of the material to be reviewed/change:  This new feature from Anomaly Detector service is Multidimensional Root Cause Analysis (MDRCA). It can discover the root causes of problems to identify appropriate solutions within your complex metric systems such as ROI, CTR, through detecting the abnormal dimension(s) or abnormal dimension combinations when there is a big spike or drop in your metrics system, without knowing any machine learning knowledge, labeled data, or even anomaly information.
• A link to the PR/issue in  azure/azure-rest-api-specs repo:  [link](https://github.com/Azure/azure-rest-api-specs/pull/17083/checks?check_run_id=4519410187)

**Comment by czubair** [comment]
updated issue here: https://github.com/Azure/azure-rest-api-specs/issues/16984
