### ISSUE TITLE
Creating a CustomScriptExtension causes a conflict and errors out

### ISSUE THREAD

**Issue by hausec** [Azure/azure-rest-api-specs#17102]
While creating a CustomScriptExtension via PUT request it gives an error: 
```
Invoke-RestMethod : {
  "error": {
    "code": "OperationNotAllowed",
    "message": "Cannot update handlerVersion or autoUpgradeMinorVersion for VM extension 'CustomScriptExtension'. 
Change is in conflict with other extensions under handler 'Microsoft.Compute.CustomScriptExtension', with 
typeHandler version '1.4' and autoUpgradeMinorVersion 'True'."
  }
 ```
Request looks like the following:
`PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/extensions/CustomScriptExtension?api-version=2021-07-01`

Body: 
```
{
    "location":  "centralus",
    "properties":  {
                       "publisher":  "Microsoft.Compute",
                       "autoUpgradeMinorVersion":  true,
                       "typeHandlerVersion":  "1.9",
                       "type":  "CustomScriptExtension",
                   }
}
```

**Comment by Drewm3** [comment]
@amjad, could you have someone look into this issue?

**Comment by amjads1** [comment]
@MsGabsta can you please look into this issue?

**Comment by MsGabsta** [comment]
@hausec is this a new VM or an existing VM?  Does this VM already have Custom Script Extension installed as only one CSE can be installed on a resource?

**Comment by hausec** [comment]
Looks like it's working now. Thanks!
