### ISSUE TITLE
Servicebus subscription not returning `duplicate_detection_history_time_window`

### ISSUE THREAD

**Issue by atombrella** [Azure/azure-rest-api-specs#17114]
While working on this https://github.com/hashicorp/terraform-provider-azurerm/pull/14041#issuecomment-995223296 we've noticed that the API is not returning this value. In the Export template under the servicebus subscription, `duplicate_detection_history_time_window` is not listed under `properties` in the JSON template.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2021-11-01/subscriptions.json#L345 contains the field.

Hopefully I've provided enough details. Thank you!

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback on this item. We are currently actively working on this, however we don't have a timeline to share yet around when this work will finish.

**Comment by anqyan** [comment]
This is by design. Service Bus subscription does not contain that property. User should check the topic of that subscription for the duplicate detection time window.
