### ISSUE TITLE
Capacity / Quota APIs are not working as expected in go.

### ISSUE THREAD

**Issue by dnozay** [Azure/azure-rest-api-specs#17134]
see https://github.com/Azure/azure-sdk-for-go/issues/16678

TLDR:
```
{
    "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Capacity/resourceProviders/Microsoft.Compute/locations/northeurope/serviceLimitsRequests/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "name": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "properties": {
        "properties": {    <======================== repeated properties
            "message": "Request completed.",
            "provisioningState": "Succeeded",
            "requestSubmitTime": "2021-05-20T00:23:12Z",
            "value": [
                {
                    "limit": 1300,
                    "message": "Request completed.",
                    "name": {
                        "value": "STANDARDESV3FAMILY"
                    },
                    "provisioningState": "Succeeded",
                    "subRequestId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                }
            ]
        }
    },
    "type": "Microsoft.Capacity/ServiceLimitsRequests"
}
```

`properties` is repeated in the response, breaking unmarshalling.

> @dnozay , based on the swagger definition and sample provided by service team, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/reservations/resource-manager/Microsoft.Capacity/stable/2020-10-25/examples/getQuotaRequestStatusById.json, the response body should not contain duplicate 'properties', as our SDK is generated by Swagger, could you open an issue in https://github.com/Azure/azure-rest-api-specs/issues/new to ask service team fix their service behavior?

cc @lirenhe @rahuls-microsoft 

Thank you for your help

**Comment by lirenhe** [comment]
Close this one as we will use https://github.com/Azure/azure-sdk-for-go/issues/16678 to track this issue

**Comment by dnozay** [comment]
Hello @lirenhe,
we can see a change in the responses since late December, is there any update you can link to this issue?
Thank you

**Comment by lirenhe** [comment]
> Hello @lirenhe, we can see a change in the responses since late December, is there any update you can link to this issue? Thank you

The support team contact me and they are following up with this item. It looks the service team solved this problem, then I will close this item. Let me know if you have further questions. Thanks
