### ISSUE TITLE
CDN: AfdRouteCacheConfiguration.compressionSettings is typed incorrectly

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-rest-api-specs#17163]
The [`compressionSettings`](https://github.com/Azure/azure-rest-api-specs/blob/23d896b00311e101dbbd6fea04c9ae9f0006be92/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L5171) property is defined with `items` as if it's some sort of an array:

```
"compressionSettings": {
  "description": "compression settings.",
  "type": "object",
  "items": {
    "$ref": "#/definitions/CompressionSettings"
  }
}
```

Examples clearly show that it should NOT be an array: 
- https://github.com/Azure/azure-rest-api-specs/blob/23d896b00311e101dbbd6fea04c9ae9f0006be92/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/examples/Routes_Get.json#L39-L45
- https://github.com/Azure/azure-rest-api-specs/blob/23d896b00311e101dbbd6fea04c9ae9f0006be92/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/examples/Routes_Update.json#L33-L39

So the spec should likely be

```
"compressionSettings": {
  "description": "compression settings.",
  "$ref": "#/definitions/CompressionSettings"
}
```

**Comment by t-bzhan** [comment]
Ack, we are working on fixing it in the new version.

**Comment by mikhailshilkov** [comment]
> Ack, we are working on fixing it in the new version.

Great! Please consider fixing it in existing API versions as it's a bug - not really a breaking change

**Comment by t-bzhan** [comment]
Swagger fixed.
