### ISSUE TITLE
Feature: publish monitoringConfigurations for Recovery Services

### ISSUE THREAD

**Issue by josh-barker** [Azure/azure-rest-api-specs#17301]
Hi

Could you please publish the API specs for the latest version of the following endpoint?

https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vaults/xxx/monitoringConfigurations/notificationConfiguration?api-version=2017-07-01-preview

It would be helpful if you publish other endpoints under `monitoringConfigurations` too.

These endpoints will be used in the AzureRM terraform provider, as per https://github.com/hashicorp/terraform-provider-azurerm/issues/5423

Cheers

**Comment by josh-barker** [comment]
Hi @sameergMS and @dadunl, just following up on this issue.

**Comment by sameergMS** [comment]
Hi Josh – I have no idea why this is assigned to me. I do not work on anything related to this. ☹

**Comment by josh-barker** [comment]
Oh, okay. Thanks for letting me know @sameergMS .

**Comment by josh-barker** [comment]
@KeYu-AnkhSpirit, @msftbot Could you help direct this issue to the right team?

**Comment by josh-barker** [comment]
Hi @Sharmistha-Rai, I'm trying to find someone to help with this issue. It looks like you've been involved in some issues relating to Recovery Services, so I'm hoping you'd be able to direct this issue to the right people?

Thanks

**Comment by Sharmistha-Rai** [comment]
Hi @josh-barker , let me check with our team see what I can find on this. I do work with Site Recovery. Are you using the above API for an operation related to ASR or with Azure Backup?

**Comment by josh-barker** [comment]
Hi @Sharmistha-Rai , I'm using the above API to configure notifications on an RSV vault.
In the portal, you can see it on an RSV, under "Backup Alerts", and then "Configure notifications"

**Comment by Sharmistha-Rai** [comment]
Adding @pvrk from the Azure Backup team here to assist with this query.

**Comment by Sharmistha-Rai** [comment]
Adding @adityabalaji-msft to assist with the query.

**Comment by adityabalaji-msft** [comment]
Hi @josh-barker - wanted to call out a couple of points:

1. We have started to support a new alerting solution for backup based on Azure Monitor (which is our forward-looking alerting solutions). We recommend to use this new alerting solution, where you can leverage standard Azure Monitor APIs (Actin Rule APIs in particular) to configure notifications for your required scenarios. It is currently in public preview but we plan to go GA soon. More details here: https://techcommunity.microsoft.com/t5/azure-storage-blog/monitor-your-backups-effectively-using-azure-monitor-alerts-for/ba-p/2755670


2. Regarding the current alerting solution (configure email notifications) which you are using - we haven't actively advocated programmatic means of configuring notifications so far (eg. we don't have PS/CLI support). also given that this is the older alerting solution, I am not sure if we will be publicly documenting the API for this solution at this point in time. However, our team can help you out on a case by case basis, if you still want to use this API and are facing issues.

Happy to connect with you offline for any questions/concerns on the roadmap

**Comment by josh-barker** [comment]
Hi @adityabalaji-msft ,

Thanks for explaining the plans for monitoring backups.
I'll take a look into Azure Monitor on RSVs.

**Comment by josh-barker** [comment]
@Sharmistha-Rai Just wanted to say thank you for helping with redirecting this issue. Really appreciate it!
