### ISSUE TITLE
[Maps - Styling] REST API Review for Azure Maps Styling Service

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#17312]
Service Name: Azure Maps Styling Service

Key contact for the review: Xubin Zhuge(@Xubin Zhuge) / James Jonghan Park(@James Jonghan Park)

The changes contain both existing APIs(Tileset) and new APIs(StyleRecipe, StyleSet)

The service is deployed, but the proposed changes are still in progress.

What changed in this PR:
 - We create a new 2022-01-01-preview version API for Tileset, StyleSet and StyleRecipe under Creator
- We extended our exising Tileset API with Tileset Recipe ingested, and we also added Tileset Recipe GET and Validation API.
- We added two new set of APIs StyleSet and StyleRecipe which are our new APIs

Custom Styling Design doc: 

https://microsoft.sharepoint.com/:w:/t/MicrosoftMapsGeospatialTeam/EUyAGqR7R4pJoIXkXQdlQcAB7SPLJQImjNS0eQGp8xathQ?e=eccr4D

**Comment by czubair** [comment]
Review scheduled for Tues 1/25 at 1pm PST

**Comment by markweitzel** [comment]
## API Stewardship Review Board 25-Jan-22

## Discussion / Notes

* Conversation around ontology. When will we expect more/others. New ontology values will result in a new API version. 
  * Define the ontology values as an extensible enum. This way, when SDKs are generated, they will be generate the proper language types.
  * Is there a customer benefit of deprecating the old ontology?  
  * It is a breaking change if a customer cannot make an ontology with an old version. It is STRONGLY recommended to avoid breaking change. This would mean that `facility-2.0` should be supported in perpetuity. 
* There should be a discussion around if we should use an approved standard for the query/expression language. 
* The `datasetId` in the `POST` and the body is confusing. We may need to live with this b/c of historical reasons. 
  * What is the behavior if the two values are different? 
* There can only be one version w/in a service sdk. 
* There should be some documentation cleanup for the `V2` section.


## References
[Meeting Chat]()
[Meeting Recording]()

**Comment by zhugexubin** [comment]
> 

As we discussed in the review meeting that whether we would like to introduce big broken changes to modify existing GA API behavior.  The answer is no at this point. We would like to keep existing API behavior which means the new Swagger doc introduced will be consistent with the existing design pattern.

**Comment by scgbear** [comment]
## API Stewardship Review Board 21-June-2022

## Discussion / Notes

* Nouns discussion: Clarity of the /styles operations are related to the "Azure Map Style" definition
* Map Configuration: 
  * Is a long running operation because it is also loading the cached layouts whens the Map Configuration is created. 
  * Currently using POST, recommendation to use a PUT to ensure end point is idempotent. 
  * Suggesting to conform to the new LRO pattern in the [LRO PR](https://github.com/microsoft/api-guidelines/pull/353) 
* API does not have a version in the "stable" directory. Version 2.0 is in the preview folder
* Should review the "x-ms-client-id" to look to move to the authorization header
* Style api review the LRO guidelines
  * dataFormat redundant with http content type?
  * Remove dataFormat parameter, add application/zip to the content type option
  * LayersConfiguration link in the description of the body, should be a part of the spec

## Next Steps

* Review the new LRO Guideline for the Map Configuration and Style Create operation
* Move the API to the stable directory for the api
* Clean up example on TileSet configuration body
* Need to schedule another session to review the rest of the swagger

## References
[Meeting Chat]()
[Meeting Recording]()

**Comment by markweitzel** [comment]
## API Stewardship Review: 6-Jul-22

`POST` -- Add examples in the `description` of what are valid strings. 
`GET` The format in the StyleListItem should use the datetime specification. This should not be just a String. 
* See https://swagger.io/specification/v2/#data-types and our extensions at https://github.com/Azure/autorest/blob/4c6ff7470011620fc5e444f7f6a9fc59cf7dd7d3/packages/libs/openapi/src/v3/formats.ts
* `GET` `/styles/{styleId} - Make sure to add zip as a valid response type.
  * You can add two different examples in your Open API document - `x-ms-examples` add a name and reference a file that is the named example.
  * The model should be in the response body. 
* `DELETE` - the `code` should only be `BadRequest` -- you don't need to include the status code as well. NOTE: If you already return this in GA code, then keep this value. 
*   

Note: There are a few "cleanliness" errors that you should fix. An easy way to discover these is by running the spectral linter. See [Azure API Style Guide](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)


## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1655846518135?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1655846518135&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1655846518135
[Meeting Recording]()

**Comment by zhugexubin** [comment]
POST -- Add examples in the description of what are valid strings.
**We limit the maximum length for 'description' parameter to be 1024.**
GET The format in the StyleListItem should use the datetime specification. This should not be just a String.

**We add 'date-time' format for the 'created' property in StyleListItem object.**

GET `/styles/{styleId} - Make sure to add zip as a valid response type.
**We limited the response to be 'application/zip' only now.**


DELETE - the code should only be BadRequest -- you don't need to include the status code as well. NOTE: If you already return this in GA code, then keep this value.
**We will keep it as this to make it consistent with GA version.**

Ideally the request would support Accepts to tell you what to return See https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

**We don't support Accepts for now. And we only one kind of format for now instead.**

Note: There are a few "cleanliness" errors that you should fix. An easy way to discover these is by running the spectral linter. See [Azure API Style Guide](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)

We should schedule some more time for TILESET.
For the TILESET, the /tilesets/configuration/validate should be an action, and model this as /configurations:validate

We discussed this during office hours. And change tileset configuration GET and Validate to be actions.
With model POST 'tilesets:fetchConfiguration' and POST 'tilesets:validateConfiguration'.

@markweitzel After fixing all the comments above, how can we get the approval for the issue?
