### ISSUE TITLE
[Monitor] Inconsistency in package date

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/azure-rest-api-specs#1731]
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/monitor/resource-manager/readme.md
This shows one date in the header and another date in the code snippet. Which should be used?

**Comment by gucalder** [comment]
I do not see the issue.
I see package tag: package-2017-08 in the Basic Information section and package-2017-08 in the Tag section. Please clarify which dates are inconsistent?

**Comment by RikkiGibson** [comment]
The problem was fixed a few days after I opened this issue. I'll consider this resolved.

https://github.com/Azure/azure-rest-api-specs/commit/97e69db426af23a0cdfde5e5df748565ff1070b8
