### ISSUE TITLE
[Search] Parameter grouping

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1735]
Search is using parameter grouping, but grouping a [single parameter](https://github.com/Azure/azure-rest-api-specs/blob/2416692e60a12e8fc3b6d7c88272f5fcf5cc93aa/specification/search/resource-manager/Microsoft.Search/2015-08-19/search.json#L1041). Are more parameters expected to be added later to the group, or is this extension really needed here?

**Comment by brjohnstmsft** [comment]
This was an intentional design choice to create space for adding more parameters later without breaking changes. However, we haven't yet had the need to add more parameters in this particular case.

**Comment by mcardosos** [comment]
Awesome :D Closing issue
