### ISSUE TITLE
[Azure Maps Search] REST API Review for Azure Maps Search

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#17350]
Service Name: Azure Maps Search
Has your service already been deployed?: no
Is this a new or existing API?: Add new unstructured feature in public-preview API
Key contact for the review: Eva Ou, evaou@microsoft.com
REST API Review PR (Pull Request): https://github.com/Azure/azure-rest-api-specs/pull/17207
Issue: N/A
Description of the material to be reviewed/changed: Add new unstructured feature in public-preview geocoding API
Note: N/A

Review scheduled for 1/20 at 5pm PST

**Comment by markweitzel** [comment]
## API Stewardship Review 20-Jan-22

* The new `query` parameter is mutually exclusive. If it's passed with a structured parameter, then this is an error and a bad response is returned. 

## Notes / Discussion
`addressLine` query parameter is going away when the service GAs. 
Model this as one entry in the OpenAPI document. 

 

## Actions
- [ ] @evaou -- Provide a _link_ to the slides.

## References
[Meeting Recording]()
[Meeting Chat]()

**Comment by evaou** [comment]
Here's the link to the slides. 
https://microsoftapc-my.sharepoint.com/:p:/g/personal/chihcheng_microsoft_com/EXyu3VdAwt9Jrzn4TExfNaQB3xLPpLYkZhjbXkXJcMlxAA?e=gYUO0P
