### ISSUE TITLE
Provide a stable API version for Azure Policy

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-rest-api-specs#17376]
Currently, the latest tag of Azure Policy contains a preview feature 

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/readme.md#tag-package-policy-2021-06
- Microsoft.Authorization/preview/2020-07-01-preview/policyExemptions.json

Some customers need a stable version of the SDK which requires service team to release the stable version of this feature.
Please refer to this item: https://github.com/Azure/azure-sdk-for-go/issues/16528

**Comment by kenieva** [comment]
@lirenhe Exemptions are still a preview feature of Azure Policy. At the current moment, we do not have an ETA for the GA of this feature. If any customer is interested in having statements of support for production use, the PM team is happy to have those discussions. Thank you.
