### ISSUE TITLE
Review of new dataplane API in Azure Sentinel CICD

### ISSUE THREAD

**Issue by debjyoti11** [Azure/azure-rest-api-specs#17394]
We are planning to introduce two new dataplane APIs in our service. These APIs will be invoked by GItHub and Azure DevOps using their webhook mechanism to update the status of GitHub workflows or Azure DevOps pipeline. We would like to have your feedback on the API design.

@APIStewardshipBoard-ReviewRequested

**Comment by debjyoti11** [comment]
[](url
[Service-Health-Design.docx](https://github.com/Azure/azure-rest-api-specs/files/7892520/Service-Health-Design.docx)
)

**Comment by debjyoti11** [comment]
I am not able attach the lable @APIStewardshipBoard-ReviewRequested to this issue. Can you please label this issue with @APIStewardshipBoard-ReviewRequested ?

**Comment by debjyoti11** [comment]
Hi can I get a response ?

**Comment by juliango2100** [comment]
I am checking to see how we can satisfy this request.

**Comment by debjyoti11** [comment]
@JackTn  can you please help me to label the issue @APIStewardshipBoard-ReviewRequested ?
