### ISSUE TITLE
[Key Vault] Key Vault Key API Enum's are case sensitive

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1739]
👋🏻

I've been working with the `2016-10-01` version of the Key Vault Key API via the Azure SDK for Go - and have noticed it is sensitive to the casing of Enum's. Every other API I've used within Azure handles Enum values being in the incorrect case (by passing them using the Case Insensitive override) - however the Key Vault Key API requires these values be case sensitive - and returns a pretty unhelpful error message which left me head-scratching for quite a while (note in particular the missing property name):

```
keyvault.ManagementClient#CreateKey: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Property  has invalid value\r\n
```

When sending the value `unwrapKey` creating a Key Vault Key works as expected; however when sending `UnwrapKey` (or any other case-combination) this fails with the error shown above.

Would it be possible to update this Enum parsing used within this API to be case-insensitive to match the other API's within Azure?

Thanks!

**Comment by marstr** [comment]
Howdy @tombuildsstuff, just to confirm, it [looks to me](https://github.com/Azure/azure-sdk-for-go/blob/21f5db4a3b31b290b68bd706520298d37c87cd29/dataplane/keyvault/models.go#L61) like the Azure SDK for Go supplies the correct casing. Do you think there is a bug with our client-library, or is this a suggestion for how to improve the server-side service? You know you're the Go team's MVP!

**Comment by tombuildsstuff** [comment]
👋🏻 @marstr

> Do you think there is a bug with our client-library, or is this a suggestion for how to improve the server-side service?

Within Terraform we use the Enum's in two ways - [firstly to provide validation](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_app_service.go#L213) by listing all the supported Enum values - and [then to cast to/from this based on the user input](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_app_service.go#L603).

I've been meaning to file an enhancement request for the former (to expose a method a means of obtaining all the Enum values, rather than us having to list them out) which I'll open an issue about shortly.

> it looks to me like the Azure SDK for Go supplies the correct casing. 

Indeed - because we don't really want to maintain a mapping between the possible Enum values and user input, we cast to the Enum (which I'd always assumed returned the actual value of the Enum, rather than just casting it to it - but apparently not!) and then submit that to the API. As such - the cast value is sent to the API which returns the failure, I believe this is an issue with the Service which should parse Enum's case-insensitively (like every other service does) - rather than the Go SDK? :)

Thanks!

**Comment by tombuildsstuff** [comment]
👋🏻

Also doing some testing on this - looking at the generated code:

```

// JSONWebKeyType enumerates the values for json web key type.
type JSONWebKeyType string

const (
	// EC specifies the ec state for json web key type.
	EC JSONWebKeyType = "EC"
	// Oct specifies the oct state for json web key type.
	Oct JSONWebKeyType = "oct"
	// RSA specifies the rsa state for json web key type.
	RSA JSONWebKeyType = "RSA"
	// RSAHSM specifies the rsahsm state for json web key type.
	RSAHSM JSONWebKeyType = "RSA-HSM"
)
```

I've noticed when submitting the value `oct` to the API it returns an error - given this API is case sensitive, would this be incorrectly cased in the Swagger?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @olydis @rijethma @dragav - is there an update here? :)

**Comment by olydis** [comment]
@tombuildsstuff argh sorry for not getting back, completely missed your comment. Yes, `oct` is specified exactly like that in the Swagger(s): https://github.com/Azure/azure-rest-api-specs/search?utf8=%E2%9C%93&q=RSA-HSM&type=

@rijethma @dragav Can you confirm `oct` is incorrectly cased as @tombuildsstuff points out?

**Comment by schaabs** [comment]
@tombuildsstuff the "oct" key type is not currently supported.  If you are trying to create an "oct" key this is expected to fail.  I believe this was added to the swagger so that when we enable this key type on the service, existing clients will be able to use it without an update.

**Comment by mzhuazureidentity** [comment]
Hi folks,
I think i meet the same question, i am call azure rest api via postman for testing sign followed by this doc:
https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign

I am passing this in body and result here: (tried several times)
1.
body input:
{
	"alg":"RS256",
	"value":"edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb"	      
}
result:
{
    "error": {
        "code": "BadParameter",
        "message": "Property  has invalid value\r\n"
    }
}

2.
{
	"alg":"ECDSA256",
	"value":"2CC7C0EC4EF8A8A2C62FCC249F9CDDBC89158780A2040EF8D4A490989F9CFCFA"

}

{
    "error": {
        "code": "BadParameter",
        "message": "Property  has invalid value\r\n"
    }
}

3
{
	"alg":"RSA-OAEP",
	"value":"2CC7C0EC4EF8A8A2C62FCC249F9CDDBC89158780A2040EF8D4A490989F9CFCFA"

}

{
    "error": {
        "code": "BadParameter",
        "message": "Invalid signature algorithm RSA-OAEP to use with this key."
    }
}

-----
Based on several test, I got confused on the value.
How and where can find the correct value?
please advisor

**Comment by mzhuazureidentity** [comment]
for a update, i am able to run this successfully.
{
	"alg":"ES256",
	"value":"/4n6jV+RLhiquNWCIo+kZ596bfsSDilEWstbcF1v1vE="

}

The value should be the key setting up in the app.

Thanks!

**Comment by salameer** [comment]
Based on @mzhuazureidentity it seems that this can be resolved, Kindly reopen if it's still an issue

Thanks

Samer
