### ISSUE TITLE
Fix x-ms-examples for compute 2017-03-30 swagger spec.

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#1740]
Compute swagger has model validation errors https://travis-ci.org/Azure/azure-rest-api-specs/jobs/279647270. We will be merging this PR https://github.com/Azure/azure-rest-api-specs/pull/1727 as it contains changes for Ignite. However, someone from the compute team needs to fix those examples later on at the earliest possible date. This will directly impact the examples shown for the Compute REST API at docs.microsoft.com website.
/cc @gatneil @hyonholee @huangpf

**Comment by huangpf** [comment]
We got the red label!

@gatneil to help take a first cut, because I think there is an ongoing thread from you about adding examples to our specs?

**Comment by gatneil** [comment]
I will fix this hopefully later this week; just to clarify though, this won't impact the examples shown on docs.microsoft.com (details discussed offline).

**Comment by gatneil** [comment]
PR for the fix here: https://github.com/Azure/azure-rest-api-specs/pull/1758 :)

**Comment by fearthecowboy** [comment]
Was this fixed? (#1885)

**Comment by gatneil** [comment]
@fearthecowboy yup! The PR that fixed it was #1885 (abandoned #1758 because git issues)
