### ISSUE TITLE
[Purview - Scanning] REST API review for scanning data plane

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#17416]
•	Service name: Azure Purview
•	Key Contact:  Naga Yenamandra, Phani Kumar Vadali, Parv Saxena
•	New or Existing API?: Existing
•	Has your service been deployed?: No
•	Description of changes:  APIs to manage credentials, Integration Run times and Vnet.
•	

Review Scheduled 2/3 at 4pm PST

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 3-Feb-2022

@pvadali-az -- Please review the [Azure REST API Style Guidelines](http://aka.ms/azapi/specs). In those guidelines you find a helpful utility that we've been experimenting with, Spectral. Running this within VS Code will help you identify many of the correctness issues that should be addressed, e.g.
* Schema should have a description or title
* Parameter should have a description.
* `value` property in pageable response should be required

### Discussion / Notes


### Actions

## References
[Meeting Chat]()
[Meeting Minutes]()


### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by markweitzel** [comment]
## API Stewardship Board Review 18-APR-22
> This was a "one off" session consisting of @johanste, @mikekistler and @markweitzel 
>It was scheduled out of band b/c of time pressure for customers needing the `credentials` aspect of the API

There are a number of issues with the API that should be addressed. However, Mike, Johan, and I had a quick call with @pvadali-az - We approved this PR based on the following:
* the set of changes for this preview was reduced to focus on the credential API
* there is a full review of Purview **BEFORE ANY API GOES GA**

@pvadali-az will start the broader conversation for us to start working through these issues.
