### ISSUE TITLE
vmss: os disk size is not captured in spec

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-rest-api-specs#1741]
The trace on the wire does contain the information.
Please update the model type to get complete:
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L5501-L5547

**Comment by yugangw-msft** [comment]
//cc @hyonholee, please reassign if needed

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
