### ISSUE TITLE
[Cognitive Services - Text Analytics] REST API Review for Language API for TA  (2022-04-01-preview)

### ISSUE THREAD

**Issue by bidisha-c** [Azure/azure-rest-api-specs#17438]
•	Key contact for the review: bidishac@, rapopovi@
•	Whether this is a new or existing API: new
•	Whether or not your service already been deployed: not deployed
•	A brief description of the material to be reviewed/changed: API review for the transcription PII redaction and issue resolution detection service. 

Design Documents
[Transcription PII Spec](https://microsoft-my.sharepoint.com/:w:/p/bidishac/ES-y8c8CaepJgwChqBjxIpEBKjtJZSjig_nLD45LEP5DVA?e=Q29Rax)

[Issue Resolution Detection](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Fr%2Fteams%2FTextAnalyticsTeam%2FShared%2520Documents%2FGeneral%2FGPT-3%2FIssue%2520Resolution%2520Detection%2520Public%2520Preview%2520Spec.docx%3Fd%3Dwa944653ccf474f0bb9ed8cb798205306%26csf%3D1%26web%3D1&data=04%7C01%7CCala.Zubair%40microsoft.com%7C13ecf09149944cfcc18c08d9e13ffa11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637788487172684676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g%2FfaSm%2FyYW8mxvvqAbTheVb8NwxCuP6YP3bDqPVAKCY%3D&reserved=0)

**Comment by bidisha-c** [comment]
Placeholder Issue for the Language API Preview..

**Comment by czubair** [comment]
Review scheduled for 2/15 at 1pm PST

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 15-Feb-22


### Discussion / Notes
* Can we find a better name for `conversationItem`
* Could you update the language description to mention it's BCP-47? Question Answering and CLU both state this in their model property descriptions.
* Do we need three ways to sort? (order in index, timestamp, array) ?
  * Is there a way to simplify this? 
  * If only one option, implicit order b/t in put & output.
* Is ITN a very well known abbreviation in this worl? If not, can we expand it or give it a friendly name? and failing that, we should at least use x-ms-enum to add documentation for them


### Actions

## References
[Meeting Chat]()
[Meeting Recording - First part](https://microsoft.sharepoint.com/teams/AzureAPIStewardshipBoard/Shared%20Documents/General/Recordings/View%20Only/Meeting%20in%20_General_-20220215_160539-Meeting%20Recording.mp4?web=1)
[Meeting Recording - Second part]()


### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by bidisha-c** [comment]
The review [meeting transcript link](https://microsoft-my.sharepoint.com/:w:/p/bidishac/EWYUEY50J5FEhvli3vz87xsBlvfJgRu2eknjTCVpWPo3Kw?e=wwG8zn) for reference.
