### ISSUE TITLE
Virtual machine creation doesn't allow for setting network access policy on the issue disk

### ISSUE THREAD

**Issue by scott1138** [Azure/azure-rest-api-specs#17452]
The managed disk api allows for network access policy to be set. Can we do the same for the os disk?

**Comment by Drewm3** [comment]
@TravisCragg-MSFT, could you please look into this feature request to see if it is something that can be provided in the future?

**Comment by TravisCragg-MSFT** [comment]
@scott1138 Why do you want to do this during VM creation? Are you trying to avoid creating the disk first, or do you have a different scenario?

**Comment by scott1138** [comment]
@traviscragg-msft - Well, it does make the process less complex if you can do it al in one resource, but my scenario is a little different.  I use Terraform, and the latest resource for Virtual Machines doesn't support OS disk attachment.  If the VM ARM API supports the network access policy feature, we can ask the AzureRM provider team to include that feature in the Virtual Machine resources.

**Comment by tombuildsstuff** [comment]
@scott1138 out of interest what's the use-case/scenario for sharing the OS Disk / setting a Network Access Policy on it? That'd almost certainly enable a number of issues at runtime, so I can't think why this would be set to anything but `None` (and defaulted by the API)?

**Comment by scott1138** [comment]
> @scott1138 out of interest what's the use-case/scenario for sharing the OS Disk / setting a Network Access Policy on it? That'd almost certainly enable a number of issues at runtime, so I can't think why this would be set to anything but `None` (and defaulted by the API)?

@tombuildsstuff the network access policy controls the ability to export the disk. The default setting allows the disk to be export anywhere. There is an option for private link as well, but our cybersecurity team wants it set to DenyAll.

**Comment by TravisCragg-MSFT** [comment]
> I use Terraform, and the latest resource for Virtual Machines doesn't support OS disk attachment.

     This seems like an issue with Terraform, creating a VM from an existing disk is a vital scenario. 

I am taking this item as a feature request, but this will likely not be implemented in the near future.

**Comment by TravisCragg-MSFT** [comment]
Closing this issue, please let me know if any other info is needed.

**Comment by tombuildsstuff** [comment]
@TravisCragg-MSFT where's this feature request being tracked publicly?
