### ISSUE TITLE
Express Route Gateway Connection should not mark with read-only

### ISSUE THREAD

**Issue by xuzhang3** [Azure/azure-rest-api-specs#17468]
Express Route Gateway expressRouteConnections should not mark with read-only, `expressRouteConnections` is part of the request body, this property should not marked with `read-only`
API : https://docs.microsoft.com/en-us/rest/api/expressroute/express-route-gateways/create-or-update#expressroutegateway
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/e729721df20047dcb4fdb675d234b6821f1a4f81/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/virtualWan.json#L7605-L7605

**Comment by xuzhang3** [comment]
PR: https://github.com/Azure/azure-rest-api-specs/pull/16905

**Comment by jjcv-msft** [comment]
This field is read-only because expressRouteConnections are child resources of expressRouteGateways. To modify them, please target the expressRouteConnections directly.
