### ISSUE TITLE
Missing coverage for Azure SQL Management

### ISSUE THREAD

**Issue by devigned** [Azure/azure-rest-api-specs#175]
Azure Ruby SDK has received feedback that the SQL management spec is missing needed operations. Please add these as soon as possible.

Issue: https://github.com/Azure/azure-sdk-for-ruby/issues/307

**Comment by lmazuel** [comment]
I was about doing an issue, we have some feedback that SQL management is needed too in Python.

**Comment by amarzavery** [comment]
@yaakoviyun, @akromm - Can you please respond?

**Comment by lmazuel** [comment]
@yaakoviyun @akromm Any update of this one?

**Comment by thenewwazoo** [comment]
Our team is looking to migrate to Azure SQL ASAP and so we need this support very badly. Is there any timeline that we can expect for delivery?

**Comment by amarzavery** [comment]
@yaakoviyun @akromm - The Sql team please respond with a timeline. Where is this blocked?

**Comment by akromm** [comment]
@amarzavery @thenewwazoo @lmazuel We have dedicated a couple days (Aug 22-23) in which we plan to grab a couple engineers and do our best to get this done then.  If all goes well and we don't run into any unexpected problems the swagger spec should be done around that time.

**Comment by amarzavery** [comment]
@akromm - Thanks a ton for this. If you need any help from the SDK Team, then please feel free to let us know.

**Comment by thenewwazoo** [comment]
Hi @akromm, any success? :)

**Comment by SaltyDH** [comment]
Come on guys, the dreaded AWS has come up in discussions again today due to a lack of basic specs on core Azure operations... Nothing worse than setting an expectation and then going silent on the issue! Can we please get an update? I was fully prepared to do the Autorest side of things for the dotnet sdk but the spec isn't even up to date!

**Comment by akromm** [comment]
@SaltyDH The work to generate the swagger spec for Azure SQL is underway and you can find the in-progress specs here:
https://github.com/akromm/azure-rest-api-specs/tree/master/arm-sql

It has most of the APIs defined but we are still adding a few more and testing the Spec to ensure that everything is correct.

**Comment by akromm** [comment]
Additionally if you are using a .Net language we have a fully up-to-date NuGet package that has all the APIs: https://www.nuget.org/packages/Microsoft.Azure.Management.Sql/0.50.0-prerelease

**Comment by SaltyDH** [comment]
Thanks very much Adam, I'll definitely take a look at the wip specs that's awesome! I was specifically interested in a dot net core compatible package. That's why I came looking for the spec, I was hoping to get the newer auto rest project up and running. Thanks again!

**Comment by lmazuel** [comment]
Hi @akromm ! Thanks for the work! I looked at your repo, could you confirm that the SQL client will be a composite client? If so, Autorest accepts relative links in composite file, it will helps us to test it (your link inside the composite file are local links so far).
Thanks!

**Comment by akromm** [comment]
@lmazuel Yes the SQL client will be a composite client.  The problem with using relative paths is that the tool to generate the code based on the specs uses the current directory when calculating relative paths, so it is very easy to run the tool from the wrong place and end up with "File Not Found" type errors. 

I plan to change the paths to absolute paths to the files on GitHub once they are finalized and submitted to the Azure repo.

If you would like to test it feel free to change the links in the compositeSql.json file to match your local folder structure.

**Comment by lmazuel** [comment]
@akromm Current recommendation is to use relative paths, like you see for [Compute](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/compositeComputeClient.json).
The problem with absolute Github path, is when you do a PR to fix something in the future, Travis will generate your file that does not point to the content of the PR, but to an absolute path on the master branch of the repo. We already saw some bug when the PR is green / good to merge, but after merging into master finally it was broken.
I understand your problem about local paths, but it's better for the future. (FYI @amarzavery)

**Comment by amarzavery** [comment]
If you use any nightly build of September then relative paths should work fine.

**Comment by amarzavery** [comment]
@akromm   To be precise try this version of the generator 0.17.0-Nightly20160914 and relative paths should work fine.

**Comment by akromm** [comment]
@amarzavery Changing the version of the generator fixed the issue I was having with relative file paths. Thanks!

@lmazuel I have updated my repo to use relative paths.

**Comment by salameer** [comment]
Hi @akromm,

Can we kindly get an ETA on resolving this issue?

Thanks,

Samer

**Comment by jaredmoo** [comment]
The majority of SQL operations are now documented in Swagger.

**Comment by salameer** [comment]
Closing this, lately a large number of operations have been added to the specs and latest generated SDKs should now have higher coverage. 

if there are still report on missing features  kindly report them. and I would strongly recommend opening new tickets with detail of the missing operations
