### ISSUE TITLE
[Language Service - Conversational Language Understanding] REST API Review of new Preview version 2022-03-01-preview

### ISSUE THREAD

**Issue by fxs130430** [Azure/azure-rest-api-specs#17505]
#17504 <APIStewardshipBoard-ReviewRequested>

**Comment by fxs130430** [comment]
`APIStewardshipBoard-ReviewRequested`

**Comment by czubair** [comment]
Review scheduled: February 8, 2022 1:00 PM - 2:00 PM PST

**Comment by czubair** [comment]
•	Key contact for the review: @Farhad Shakerin
•	Whether this is a new or existing API: existing API, but new information in the API response
•	Whether or not your service already been deployed: deployed
•	A brief description of the material to be reviewed/changed: We are adding new objects/properties to our Named Entity response including “resolutions” of entities and “extra information” about entities.

**Comment by markweitzel** [comment]
## API Stewardship Board Review - 8-Feb-2022

@fxs130430 -- Have you looked over the [Breaking Changes Policy](https://aka.ms/azapi/spec) that is available from the REST Guidelines page? 



### Discussion / Notes


### Actions

## References
[Meeting Chat] ()
[Meeting Minutes] ()

### Helpful Documentation
[Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by fxs130430** [comment]
> ## API Stewardship Board Review - 8-Feb-2022
> @fxs130430 -- Have you looked over the [Breaking Changes Policy](https://aka.ms/azapi/spec) that is available from the REST Guidelines page?
> 
> > [Design Document](https://microsoft-my.sharepoint.com/:p:/p/fshakerin/Ee9kigohM8RFjR5DdoDByLcBKhe9bOE4M1sUHzmfas9q4Q)
> 
> ### Discussion / Notes
> * There are some models with `LUIS` in the name. Does this reveal any of our org chart?
> * `The `error` property in the error response schema should be required.` This is in common.json (line 10 or so)
> * FYI: We've updated our guidance on how to represent the path when [performing an action](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#performing-an-action). We should look at this structure and be consistent with the rest of the service and within Cognitive.
> * In the case of composition, we should consider adding `confidence` to the resolutions
> * We should ensure that, when the SDK is being considered, we should really understand the polymorphic types. For example, being able to handle unknown types gracefully.
>   
>   * For example: `UnknownResolution` or `UntypedReslution` is closer to what I'd imagine on the client or just returning the abstract base class
>   * New resolution types will result in a new API version.
> 
> ## References
> [Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1643176405210?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1643176405210&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1643176405210) [Meeting Minutes](https://microsoft.sharepoint.com/teams/AzureAPIStewardshipBoard/Shared%20Documents/General/Recordings/View%20Only/Meeting%20in%20_General_-20220208_160337-Meeting%20Recording.mp4?web=1) and [link](https://microsoft.sharepoint.com/teams/AzureAPIStewardshipBoard/Shared%20Documents/General/Recordings/View%20Only/Meeting%20in%20_General_-20220208_160337-Meeting%20Recording.mp4?web=1)
> 
> ### Helpful Documentation
> [Azure API REST Documentation](https://aka.ms/azapi/specs)

**Comment by farhad** [comment]
I don't why one of you mentioned me here ( my username is 'farhad' and I'm not Farhad Shakerin). Please be careful next time as I have no interest in receiving unsolicited notifs from github.

**Comment by ChongTang** [comment]
This is the new PR: https://github.com/Azure/azure-rest-api-specs/pull/18067

**Comment by ChongTang** [comment]
@heaths , since we already merged the PR, what should we do to this issue? Should we close it as well?
