### ISSUE TITLE
[Search] Typo in AnswerResult.score description

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#17537]
The following files contain the typo "the the":

https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview/searchindex.json#L1088-L1094

https://github.com/Azure/azure-rest-api-specs/blob/b8d48bca1298614fdf7734c26e21a88adf5375d9/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchindex.json#L1138-L1144

CC: @cybertyche

**Comment by cybertyche** [comment]
Thank you so much @mikeharder for filing this, I will come directly to this code to file anything else I see.

**Comment by bleroy** [comment]
@Mohit-Chakraborty I think you only fixed one of the two occurrences in your PR.

**Comment by Mohit-Chakraborty** [comment]
> @Mohit-Chakraborty Mohit Chakraborty FTE I think you only fixed one of the two occurrences in your PR.

I didn't make the change for the older preview (2020-06-30-Preview).
