### ISSUE TITLE
Microsoft.Compute/virtualMachines identity.type property does not seem to work as expected

### ISSUE THREAD

**Issue by devoto13** [Azure/azure-rest-api-specs#17691]
Not sure if this is the right place to report it, but I couldn't find a better one, so please redirect me if you think that there is a better place.

So I have a Bicep template to provision a virtual machine and assign a user-managed identity to it, but not the system-managed identity. According to the [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?tabs=bicep#virtualmachineidentity) the below is a correct way to do that:

```bicep
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${resourceId('mygroup', 'Microsoft.ManagedIdentity/userAssignedIdentities', 'myidentity)}': {}
    }
  }
```

And it does work as expected using 2018-06-01 API (the same version Azure Portal is using), but with 2018-10-01 or any newer version the above code snippet also creates a system-assigned identity. Which looks like the API implementation bug to me.

If that is actually a bug, it would be good to update API documentation to highlight that there is a bug in all those versions to avoid tricky to debug problems. Or if it is by design, I wonder how one can create a VM without a system-managed identity being assigned then?

For the background, the script on the VM was using [this API](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http) to acquire an access token. It worked until I've switched from 2018-06-01 to the 2021-07-01 API version. Then the script started to fail with forbidden errors. It took quite some effort to figure out that the token was generated for the system-managed identity (which was unexpectedly created) instead of the user-managed identity.

**Comment by devoto13** [comment]
I have discovered today that my organisation has configured the Microsoft Defender for Cloud and it seems to be installing some VM extensions automatically. In particular, [guest configuration extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/guest-configuration) which seems to require the system-assigned identity. I'll investigate more and try to figure out if it may the reason I'm having system-assigned identity appear on the VM. It is still unclear why would it appear when using newer APIs, but not the older API. Maybe some other behavior change is causing this effect.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@devoto13 Sounds good, I will look forward for your response.

**Comment by devoto13** [comment]
So the `SystemAssigned` identity keeps re-appearing even when there is no deployment, so I assume it is not a bug of the API, but done by the Microsoft Defender or some other organisation policy. Probably, the policy gets triggered immediately when using the new API version and is delayed when using older API version, hence my assumption that it is a bug in the API version.
