### ISSUE TITLE
Composite spec shall not hard code the base paths for child specs.

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-rest-api-specs#177]
For example: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/compositeComputeClient.json

```
{
    "info": {
        "title": "ComputeManagementClient",
        "description": "Composite Swagger for Compute Client"
    },
  "documents": [
    "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/2015-06-15/swagger/compute.json",
    "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/2015-11-01-preview/swagger/containerService.json"
  ]
}
```

The URL part: `https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute` needs to be changed to local drive location in local development, and then in PR it needs to be replaced by URLs.

It's very rigid, and error prone.

Please do not let AutoRest spec include base URL parts, and the paths inside shall be relative to the location of the composite spec files, i.e.

```
    "2015-06-15/swagger/compute.json",
    "2015-11-01-preview/swagger/containerService.json"
```

**Comment by huangpf** [comment]
@amarzavery

**Comment by devigned** [comment]
I like this idea. Those should all be relative paths.

**Comment by amarzavery** [comment]
I am not sure if that  is a good idea. I may be having swagger specs at two different locations that are not relative to a common base folder. With absolute paths, you can still compose them.

This is a low hanging fruit among all the items that we need to solve.

**Comment by huangpf** [comment]
If multiple spec files are not organized in a way that it's 'common' to something, i.e. the common base path, then is it a good idea to proceed the composition without checking?

For example, we want to composite the Compute client family (Compute\VM, Compute\VMSS...), but it's hardly likely to composite Compute with Storage RP clients?

**Comment by huangpf** [comment]
any update?

**Comment by lmazuel** [comment]
@devigned @amarzavery 
By changing this PR to use relative from the repo root, now it's working:
https://github.com/Azure/azure-rest-api-specs/pull/359

By what do you think makes more sense? Change regarding to the repo root, or the composite file folder?

**Comment by devigned** [comment]
@amarzavery is OOF for a bit.

I think the issue we had before was that there is no real idea of root without the entire directory structure. Basically, with absolute URIs, the composite document can stand on it's own.

I like the relative URI's. I think following [JSON Reference](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html) would make the most sense. Thoughts?

**Comment by lmazuel** [comment]
@devigned For what I see, JSON reference is too much complicated for our needs here. We don't need the ability to point inside the document with an anchor. But they give a recommendation about the relative uri solving:

> If the URI contained in the JSON Reference value is a relative URI, then the base URI resolution MUST be calculated according to [RFC3986], section 5.2. **Resolution is performed relative to the referring document.**

According to this, the right relative path is regarding the place of the composite file.
Then the composite the composite file for compute should be:
```json
{
  "info": {
    "title": "ComputeManagementClient",
    "description": "Composite Swagger for Compute Client"
  },
  "documents": [
    "./2016-03-30/swagger/compute.json",
    "./2016-03-30/swagger/containerService.json"
  ]
}
```

and not

```json
{
  "info": {
    "title": "ComputeManagementClient",
    "description": "Composite Swagger for Compute Client"
  },
  "documents": [
    "./arm-compute/2016-03-30/swagger/compute.json",
    "./arm-compute/2016-03-30/swagger/containerService.json"
  ]
}
```

**Comment by devigned** [comment]
@lmazuel let's just go with what you have for the time being and bring this up in the next design discussion.

/cc @sphibbs

**Comment by kirthik** [comment]
This has been done last year.
