### ISSUE TITLE
Feature Request: Changelog's

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1770]
👋 

As part of the restructuring of this repository - README files have been added to each Resource Provider which contain information on how to generate the SDK's from these files, which is great.

However - these Readme files don't contain a changelog detailing which fields have been removed/added in each API version - and if that's intentional or not; as such every time a new version of the Go SDK is released we're left trying to work out if some fields have been removed deliberately, or if it's an error in the Swagger (as has happened with Redis and Firewall Rules accidentally being removed in the latest version).

Today's example is the `EnableBatchedOperations` and `SupportOrdering` fields have been removed from the ServiceBus Queue Models - I'm assuming these fields are now Deprecated (but short of comparing the API response to the Swagger file - we've no way of knowing at the moment). Thinking about it - using the Examples Data it might make a good automated tool as part of the Pull Request process?

Would it be possible to start putting together Changelog's for each Resource Provider? These could then be collated into the Azure SDK's at release time. As a consumer - I'd started looking for this in both the [Resource Provider](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/web/resource-manager) folder or [in the folder containing the API versions](https://github.com/Azure/azure-rest-api-specs/tree/current/specification/web/resource-manager/Microsoft.Web) (but didn't see it in either).

What do you think? :)

cc @marstr / @mcardosos / @jhendrixMSFT

**Comment by mcardosos** [comment]
Something like this?
[Azure Storage Services Versions 2016-05-31 and Earlier](https://docs.microsoft.com/en-us/rest/api/storageservices/azure-storage-services-versions-2015-07-08-and-earlier)

**Comment by tombuildsstuff** [comment]
@mcardosos indeed - that's news to me (but only appears to be for Storage?)

**Comment by dsgouda** [comment]
This is an interesting idea, I'd say this is something tooling folks might have on their plate.
Reassigning this to @salameer since he'd be super interested.

**Comment by tombuildsstuff** [comment]
@salameer is there any update here? :)

**Comment by tombuildsstuff** [comment]
@yungezz I can't see the changelog's in this repository - since this has been closed would you mind linking to where these are stored? Thanks!

**Comment by yungezz** [comment]
HI @tombuildsstuff , this one is close as wont fix for now. we're clean up legacy issues with no update.
