### ISSUE TITLE
[IoTHub] Some parameters are not marked with x-ms-parameter-location

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1774]
Marking [parameters](https://github.com/Azure/azure-rest-api-specs/blob/1a9d396a81d4efc79d52d4e9d61db4480aad36ba/specification/iothub/resource-manager/Microsoft.Devices/2017-07-01/iothub.json#L2445) `resourceGroupName`, `resourceName` and `certificateName` with `"x-ms-parameter-location": "method"` would generate SDKs with a better user experience. If I generate the Go SDK with the current swagger, this parameters are generated as client parameters. They would look better in the methods instead.
cc @vishal-gandhi @mastermanu

**Comment by jlian** [comment]
We should also do this in the next swagger version. Please assign to me.

**Comment by jlian** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/4979415
