### ISSUE TITLE
[OperationsManagement] SolutionNameParameter is not located in methods

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#1777]
MArking [SolutionNameParameter](https://github.com/Azure/azure-rest-api-specs/blob/88a9e98a0144a460f4e4f4ea97466d13d2849123/specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/2015-11-01-preview/OperationsManagement.json#L449) with `"x-ms-parameter-location": "method"` would generate SDKs with a better user experience. Right now, the code generated from this swagger for the Go SDK adds `SolutionName` as a client parameter. This would better be a parameter in each method instead.
cc @dashimi16

**Comment by sarangan12** [comment]
Assigning this to @mcardosos as she has more context on this issue
