### ISSUE TITLE
Netapp.Volume API doesn't identify what we set in previous run for the SnapshotID property

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#17834]
After tested, I found Netapp Volume can be created successfully with the SnapshotID. Then I tried to only update tags of this resource but it failed and threw below error message. Seems Netapp Volume API doesn't identify what we set in previous run for the SnapshotID property even if I didn't change this property. I assume api should know what we set in previous run for the SnapshotID property to identify whether this property is changed. Does it make sense?

Error message:
```
netapp.VolumesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VolumeReadOnlyPropertyCanNotBeChanged" Message="The volume's snapshotId property is not allowed to be updated. Please check that snapshotId is not part of the update request or isn't being changed from the current value."
```

**Comment by paulomarquesc** [comment]
I'm working on this, it is not an issue with the API or SDK, this will be fixed on Terraform ANF module.
