### ISSUE TITLE
[Authorization] Bugs in Role Assignments & Definitions

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1785]
:wave:

I'm using the Azure SDK for Go to try and manage both Role Definitions and Role Assignments. Please note: in the examples below I've sanitised the outputs of our user ID's.

When attempting retrieve the `Owner` Role Definition like so:

```
resp, err := client.GetByID("8e3af657-a8ff-443c-a75c-2fe8c4bcb635")
```

The following HTTP response is returned:

```
data.azurerm_built_in_role.test: Error making Read request for Role Definition "Owner" (ID "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"): authorization.RoleDefinitionsClient#GetByID: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="MissingSubscription" Message="The request did not have a provided subscription. All requests must have an associated subscription Id."
```

Figuring this was an error with the Swagger - I checked [the documentation](https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/getbyid):

<img width="617" alt="screen shot 2017-10-02 at 21 19 40" src="https://user-images.githubusercontent.com/666005/31119469-156685ee-a829-11e7-8470-c2872ea68e9b.png">

and then updated the "name" to include the Subscription ID as listed in the documentation:

```
url := fmt.Sprintf("subscriptions/%s/%s", client.SubscriptionID, roleDefinitionId)
resp, err := client.GetByID(url)
```

Which then produced the request:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/8e3af657-a8ff-443c-a75c-2fe8c4bcb635?api-version=2015-07-01 HTTP/1.1
authorization.RoleDefinitionsClient#GetByID: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2015-07-01' is invalid. The supported versions are '2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

Finally, figuring this was an error with the API version - I updated the API version to match an ARM Template in the QuickStart Repository which used the version `2017-05-01` - which gave the response:

```
authorization.RoleDefinitionsClient#GetByID: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error"
```

---

Next - given that some of the Azure Portal functions reuse the same API's, I figured I'd see how the Portal achieves this. However after some investigation it appears this uses a completely different API/Endpoint (this is Role Assignments, but it's a different API for Role Definitions too:

```
POST https://stamp2.activedirectory.ext.azure.com/api/RoleAssignments?scope=/subscriptions/00000000-0000-0000-0000-000000000000

{
	"roleId": "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7",
	"directoryMemberIds": ["00000000-0000-0000-0000-000000000000"]
}
```

---

I've had similar errors attempting to create a new Role Assignment (`the request was incorrectly formatted`) - which lead me to believe there's an issue with both services.

As such - I believe there's issues with both the API's and the Swagger Definitions for both Role Assignments and Role Definitions. In addition the documentation needs to be updated as it's currently incorrect.

Would it be possible to confirm if this hypothesis is correct and then update the Swagger to correctly represent both API's? :)

Thanks!

**Comment by harijayms** [comment]
@tombuildsstuff are you unblocked at this point ?

**Comment by tombuildsstuff** [comment]
@perseusCode @harijayms sorry for the delayed response - I've just double checked the first example with Role Assignments and this looks good - I'll take a proper look tomorrow to validate Role Definitions too (and then close this issue when I've confirmed); but I think this looks good!

Thanks!

**Comment by tombuildsstuff** [comment]
@perseusCode thanks for confirming the ID's - this worked for us. Closing.
