### ISSUE TITLE
[Service Fabric] Add suppression to the autorest linter errors that doesn't apply

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#1786]
Based on the feedback from @VipulM-MSFT , data-plane side of the service fabric service does not enforce the guidelines around the `camelCase` notation of the properties. 

The service team is going to add suppression on the errors that do not apply than in the `6.1.x.x` release. https://github.com/Azure/azure-rest-api-specs/pull/1763#issuecomment-333925246

Error Report: http://az-bot.azurewebsites.net/linter?fileName=1763_1506975134605.json

Just opening an issue to keep a radar on that. Thanks!

**Comment by samedder** [comment]
Can you assign this to @VipulM-MSFT?

**Comment by peterpogorski** [comment]
This issue was fixed in https://github.com/Azure/azure-rest-api-specs/pull/1763#issuecomment-333925246.
