### ISSUE TITLE
Some naming issues in the Dashboard swagger

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-rest-api-specs#18144]
- [ ] The `GrafanaResource` is not a good name for a ARM resource, consider to rename it to another one, like `ManagedGrafana` .
- [ ] All body parameters in a `put` or `patch` operation should be defined as `required` .
- [ ] The naming `workspaceName` is weird here as the description is 'The name of Azure Managed Grafana' .

**Comment by jinghzhu-msft** [comment]
All concerns are solved.
