### ISSUE TITLE
Billing Subscriptions - List By Billing Account returns empty array

### ISSUE THREAD

**Issue by giordyb** [Azure/azure-rest-api-specs#18162]
Calling 

`GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingSubscriptions?api-version=2020-05-01`

(docs at https://docs.microsoft.com/en-us/rest/api/billing/2020-05-01/billing-subscriptions/list-by-billing-account)

should return a list of all of the subscriptions in the billing account.  Since 2022-03-08 it started returning an empty array. We use this call in a number of reports and automations which are now failing.

**Comment by AdamDotNet** [comment]
Hi @giordyb 

Can you confirm a couple of questions please?

1. Does the `{billingAccountName}` still have subscriptions?
2. Does the identity of the caller still have access roles assigned at the Billing Account scope?

**Comment by giordyb** [comment]
@AdamDotNet Yes and Yes.

I've been using this specific REST API endpoint for the past few months without any issues, but mind you, with an Enterprise Agreement. Then it suddenly stopped working.

I've contacted support and at first they said that this REST API call is not supported for EAs, and should only work with Microsoft Customer Agreement or Microsoft Partner Agreement (which I wasn't aware of).

I then found out that the call would successfully complete if I used the "2020-12-15-privatepreview" version of the API. 

Even though this REST API endpoint is not supported for EAs, coincidentally **it is used by the Azure Portal to list subscriptions under the Billing Account** (you can see it if you do a trace with chrome debugger) ...support even suggested that I still use the same endpoint but with the "2020-12-15-privatepreview".

If this is indeed unsupported I believe that Microsoft should provide  a **supported** way to programmatically list all of the subscriptions under a billing account with all the relevant billing properties (cost center, enrollment account id, etc).

**Comment by psinhams** [comment]
Hi @giordyb 

As per below public documentation , 2020-05-01, Billing Subscriptions - List By Billing Account does not support EA agreements. 

https://docs.microsoft.com/en-us/rest/api/billing/2020-05-01/billing-subscriptions/list-by-billing-account

Azure portal is using the version "2020-12-15-privatepreview". This version is having limited functionality as it is in private preview mode.

**Comment by giordyb** [comment]
@psinhams what is the alternative then?

**Comment by psinhams** [comment]
Hi @giordyb 
Currently there is no documented/GA Api for programmatically accessing EA Subscriptions.
You can try with "2020-12-15-privatepreview", however please note this is in preview mode, so there can be limited functionality and intermittent issues.
