### ISSUE TITLE
Support to check Azure VM creation time

### ISSUE THREAD

**Issue by ParthaI** [Azure/azure-rest-api-specs#18256]
I would like to see the VM creation time, which is not coming either in CLI, not in the console. We would like to generate a report based on the creation time of VMs. Are we missing something to understand the API or CLI? or it's not supported? Hope this is the right place to raise the request

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by jaylabell** [comment]
@avirishuv can you please take a look at this VM issue

**Comment by avirishuv** [comment]
@ParthaI, the ARM resources such as VMs do not provide a creation time property.

Closing this for now, please feel free to reopen if you have any follow up questions.
