### ISSUE TITLE
[Cognitive - Custom Speech] REST API Review, new version v3.1-preview.1

### ISSUE THREAD

**Issue by bexxx** [Azure/azure-rest-api-specs#18293]
- Service name: Cognitive Services, Custom Speech
- Key contact: Ralf Beckers
- new preview version for existing service
- service is deployed in multiple hero regions

Some existing features have been extended:
- added diarization (speaker separation) to transcription
- added language identification to transcription
- added retrieval of model files
- allow customizing model weights
- added chunked upload session for large file uploads
- added filters for GETs
- exposing capabilities of models

**Comment by czubair** [comment]
PR forthcoming

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 22-March-22


### Discussion / Notes
* Consider using the block blob storage API as the model for the `uploadSessions` api. 
* Change the upload recommendation to 8mb which is the new high throughput limit
* Add operationId to the links
* Document the default value of the `customModelWeight` to 20. 

### Actions
@bexxx -- Add a LINK to your slides here. 


## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1647021850353?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1647021850353&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1647021850353)
[Meeting Recording]()

### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

<sub>Note: The Teams channel is internal MS.</sup>

**Comment by markweitzel** [comment]
## API Stewardship Board Review 31-05-22

All minor changes and discussion centered around consistency and where to deviate. 
* `POST` `blocks/commit` 
* consider adding the `supported` prefix to the dataset name 


### Next Steps
✅  API Review Board: Signed Off

### References
[Meeting Chat]()
[Meeting Recording](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1652475048127?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1652475048127&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1652475048127)
