### ISSUE TITLE
[Communication Services - AUTH] API Stewardship Review

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#18311]
## Complete Azure API review for GA for CTE flows

**Service name:** ACS Auth

Key contact for this review: Petr Svihlik

**PR Link:** https://github.com/Azure/azure-rest-api-specs/pull/17930

**Champion scenarios** that briefly explain how developers will use your API:

- The main goal of this feature is to allow developers who use ACS (directly or via SDKs) to build and integrate a custom user interface for calling functionality with Microsoft 365 Teams identities.
- A typical scenario is building an attendant console (e.g. for receptionists to be able to accept incoming calls and redirect them to the right person). 
- Developers will use the new API to exchange AAD Access tokens (of AAD users with a Teams license) for Skypetokens. These Skypetokens can then be used to call ACS APIs directly or via SDKs.
- Changes for GA:
- Unifying the endpoint name with the method name in the SDKs (As this is a breaking change compared to the Public Preview, we’ll need help determining whether we need to create a new breaking change intake and potentially some guidance.)
- Adding two more parameters to allow Contoso restrict who can exchange the token.

**Comment by markweitzel** [comment]
## API Stewardship Board Review Meeting 23-March-22


### Discussion / Notes
* There was discussion around the updated guidance around `<noun>:<verb>` for actions. We will stay with `/teams/User/:exchangeAccessToken` to remain consistent with the existing APIs that have GA'd.
* `POST` can be used for creates, but should support the repeatability header. [Repeatability Header](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#repeatability-of-requests)


### Actions



## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1647632146941?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1647632146941&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1647632146941)
[Meeting Recording]()

### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

<sub>Note: The Teams channel is internal MS.</sup>
