### ISSUE TITLE
[Monitor] The namespace for C# code of resource-manager folder is incorrect 

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-rest-api-specs#1837]
This readme.md file is using this as namespace for CSharp: Microsoft.Azure.Management.Monitor.Management, but it should use: Microsoft.Azure.Management.Monitor

**Comment by yungezz** [comment]
fixed in PR https://github.com/Azure/azure-rest-api-specs/commit/01f6b089051096df1c6a918fd7d64ecb2058905b . close the issue.
