### ISSUE TITLE
[Monitor] Move the specs in the folder data-plane to the resource-manager folder

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-rest-api-specs#1838]
This structure is the way it is now due to historic reasons, but all the operations in the data-plane folder are going through ARM.

**Comment by lmazuel** [comment]
@gucalder You README should then be able to generate two clients, and then provide two tags, since most of the SDK have two clients.
@fearthecowboy @olydis I understand the initial problem that it's not DT, but still needs one README to be able to generate two clients. Any guidance here?

**Comment by lmazuel** [comment]
Done, we merged into one client.
