### ISSUE TITLE
[Api Management] DELETE should return 200 along with 204

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-rest-api-specs#1847]
Based on https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#delete-resource we need to support 200 for case where entity is actually deleted.

Currently, we only support 204 on DELETE. This will require a version change, as the entities are already published.

**Comment by marstr** [comment]
Seems like this was completed in the PR linked above. I'm going to close this out.

**Comment by solankisamir** [comment]
No, it was not fixed. @marstr please open it. We are working on these changes in Service Side.

**Comment by marstr** [comment]
Is there someone with more context on this issue that would be a more appropriate assignee than me?

**Comment by solankisamir** [comment]
The service side changes done and fixed.
