### ISSUE TITLE
Update Storage API to enable setting the CORS

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#1851]
👋🏻

We've had [an issue come in requesting being able to configure the CORS properties of a Storage Account](https://github.com/terraform-providers/terraform-provider-azurerm/issues/19). After taking a look in both the Go SDK and the Swagger I don't believe this functionality is currently exposed - and as such it's currently not possible to configure the CORS through the Azure SDK/API's.

Would it be possible to update the Swagger to support this functionality?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @alvadb - is there any update here? :)

**Comment by yungezz** [comment]
some example https://github.com/Azure/azure-rest-api-specs/blob/dc4abe3a0ff338c5a5c0eb229c06a57764165580/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/examples/FileServicesPut.json. @tombuildsstuff  could you pls have a look is this what you need? pls feel free to create new issue if not.

**Comment by yungezz** [comment]
blob example: https://github.com/Azure/azure-rest-api-specs/blob/e3fa2c05a467f498f1bda7d9052b4bce03be44c6/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/examples/BlobServicesPut.json
