### ISSUE TITLE
CI Prettier Check instructions are not clear.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-rest-api-specs#18550]
https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#prettier-check

What directory should I be in when running?
```
npm install
npm run prettier -- --write "specification/<service>/**/*.json"
```
I am following the current instructions, failing CI pretty print step, yep pretty print is not fixing my files when I run it.

**Comment by JackTn** [comment]
@seanmcc-msft  you can run script by using the root folder of this repo like this "npm run prettier -- --write "https://github.com/Azure/azure-rest-api-specs/specification/<service>/**/*.json"

**Comment by rcoleobrien** [comment]
Could we maybe change the instructions to show that we have to source from the root directory in the CI check instructions? I've seen this exact question pop up multiple times
