### ISSUE TITLE
Container Apps `2022-01-01-preview` and `2022-03-01` managedEnvironmentId is returned with incorrect casing

### ISSUE THREAD

**Issue by jackofallops** [Azure/azure-rest-api-specs#18661]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/stable/2022-03-01/ContainerApps.json#L489

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/preview/2022-01-01-preview/ContainerApps.json#L491

Returns the Container App's Managed Environment ID with the `Microsoft.App/managedEnvironments` segment incorrectly cased as `Microsoft.App/managedenvironments`.

**Comment by ruslany** [comment]
This was fixed in the RP and the correct casing is used now.
