### ISSUE TITLE
[Confidential Ledger] REST API Review 

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#18689]
Put the following info in the issue description:
Service name
Key contact for the review
Whether this is a new or existing API
Whether or not your service already been deployed
A brief description of the material to be reviewed/changed
Tag the issue with these labels:  APIStewardshipBoard-ReviewRequested and API Review Scoping.
Attach or link any supporting documentation, e.g. design documents to the issue.
If your OpenAPI (Swagger) is ready and you have a pull request, link the PR to the issue.

**Comment by deer-prudence** [comment]
Service name: Confidential Ledger
Key contact for the review: Emily Louden
Whether this is a new or existing API: existing API
Whether or not your service already been deployed: Confidential Ledger is in private preview
A brief description of the material to be reviewed/changed: adding the get subledger ids endpoint

**Comment by deer-prudence** [comment]
PR: https://github.com/Azure/azure-rest-api-specs/pull/18628

**Comment by markweitzel** [comment]
## API Stewardship Board Review  20-APR-2022

Looked at `app/subLedgerIds` -- This is new
* Add a `nextLink` to declare this is pageable.
* consider returning a structure that includes the subLedgerId, instead of just strings. this will make this more flexible in the future. 
* Might consider changing the name to something that reflects the concept of the object. 
* 

Please review the [OpenAPI Style Guide](https://github.com/Azure/azure-api-style-guide) -- This will help clean up some of the mechanics of the api definition. The spectral linter will help with this.

Note: @deer-prudence took some great notes in #18628  as well. 

### Reference
