### ISSUE TITLE
[Synapse - SyMS] REST API Review

### ISSUE THREAD

**Issue by piyushdubey** [Azure/azure-rest-api-specs#18744]
Service name: **SyMS**
Key contact for review: **piyushdubey (piyushdubey@microsoft.com)**
Whether this is a new or existing API: **New**
Whether or not your service is already been deployed: **Already deployed**
A bried description of the material to be reviewed/changed: **Pull Request - [118742](https://github.com/Azure/azure-rest-api-specs/pull/18742)**

**Comment by scgbear** [comment]
## API Stewardship Board Review: 21-APR-22
[Link to PR](https://github.com/Azure/azure-rest-api-specs/pull/18742)

### Notes / Discussion

* ExecuteChange POST:  
    * Constants being capitalized, values are case sensitive. Values coming from Spark naming conventions. Request is to make the values pascal case for the enum values. 
    * Operation are action operation. Request to change to match the guidelines for actions. Should be done prior to going to GA, will be a breaking change if implemented after going GA.
    * Is it an LRO? No, will respond within 1 second
    * Remove User-Agent from the spec
    * Is this an idompotent? Not idompotent. How does it know it's a duplicate request? Request add a repeatability indicator to allow for idompotency. Not required prior to going GA.
    * Look at the naming of the syMsApiDdlResponse, at least make it plural to represent the value is an array.
    * Atomic operation, Max number of items, 50, maximum of 2mb, Need to ensure these limitations and operational behavior should documented. 
    * Look at adding an id value to the requests to allow customers to associate the responces to the orginal request. Currently requiring index sequence to be maintained to map response to orginal request. Can the response be removed all together? If one fails, they all fail, if the response is not providing any value, look at removing it. Response should be 200 with empty response, when successful. Error response should provide info on why it failed.
* ExecuteChangeWithValidation. Same as previous, only it is an LRO
    * Review new LRO pattern and change the operation to match.
    * Add ID to the items in the batch to allow for referencing results to original request
    * validationType: modelAsString = true
* database GET operation:
    * 
* database/{databaseName}/{artifactType}s} GET operation
    * s suffix added to the artifactType variable in the path. Recommend a path like /databases/{databaseName}/artifacts?artifactType=TABLE
    * Use next link instead of continuation token
    * Polymorphic API: change from object to base class specification, or evaluate it not being a polymorphic api and provide seperate endpoints for each artifact type. Seperate endpoints will provide a better user experience. 
* DELETE operations should return 204


### Next Steps:

* ExecuteChange POST operation: 
    * Change to use guidelines for action operations (Pre GA)
    * Review enum based values (actionType) to provide pascal case to match expectation of json naming conventions
    * Remove User-Agent, not needed in spec
    * Recommend making the operation idompotent using repeatability indicators. Recommend prior to GA, but will not create a breaking change if implemented after going GA.
    * Expand documentation of service behavior and requirements (e.g. that it's atomic, has max number and size constrants)
    * Remove response body for 200. 
    * Return 400 when fails with the details property listing reasons for failure.
    * Add the ability to assign an ID to each item to allow for sysmetry with the LRO version of this operation
* ExecuteChangeWithValidation POSt operation Same updates on this operation as it's sync version along with:
    * Add ID to the items in the batch to allow for referencing results to original request
    * Apply new LRO pattern to the operation
    * Change validationTypeto have modelAsString = true
* database/{databaseName}/{artifactType}s} GET operation
    * Recommend changing to use a path like /databases/{databaseName}/artifacts?artifactType=TABLE 
    * Evaluate change to explicit endpoints for each artifact type
    * If operation stays polymorphic, need to make sure the return type is returning the base class type instead of a generic object.

### References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1650473732439?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1650473732439&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1650473732439)
[Meeting Recording]()

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
