### ISSUE TITLE
[ACS - Cross Platform Messaging] REST API Review

### ISSUE THREAD

**Issue by glorialimicrosoft** [Azure/azure-rest-api-specs#18777]
Responsible:
geling.li@microsoft.com

Team:
[ACS - Cross Platform Messaging](https://teams.microsoft.com/l/team/19%3aC4PXiFDHhaAs0C4_c7P2icdZU1xT4fcrAWfHDoOmyIM1%40thread.tacv2/conversations?groupId=951af3ba-82a0-4bbb-8209-c81586550ead&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) 

Whether this is a new or existing API
Existing API

Whether or not your service already been deployed
https://github.com/Azure/azure-rest-api-specs/blob/3439439b760e84e5dcc3e68edde7251c602da5f0/specification/communication/data-plane/Chat/preview/2021-10-01-preview7/communicationserviceschat.json

A brief description of the material to be reviewed/changed
- Add a new threadless messaging endpoint to allow Contoso to send a fire and forget message to CPM service

Latest : 
[Fire and Forget](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/31384/Fire-and-forget-Notifications-Alerts)

Under discussion :
[Fire and Forget](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/25210/13.-Under-discussion-Fire-and-Forget)

[Design doc - Fire and Forget](https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/31103/Swagger-API-change-on-Gateway-Fire-and-Forget)

Api Spec:

[azure-rest-api-specs/communicationserviceschat.json](https://github.com/Azure/azure-rest-api-specs/blob/gelli-addThreadlessMessagesEndpoint/specification/communication/data-plane/Chat/preview/2022-04-21-preview8/communicationserviceschat.json) 

[PR-View](https://github.com/Azure/azure-rest-api-specs/pull/18775)

Sdk view: 
[@azure/communication-chat - apiview.dev](https://apiview.dev/Assemblies/Review/2ae70f365fca49108e0258176265a20c)

**Comment by mikekistler** [comment]
Questions / comments from 5/17 REST API review:

- Parameters in the Template Message are just an array of strings with no names. Will that be sufficient for all the providers going forward?
- Support for multiple media elements in a message? If this could be a future need you should structure things for expansion now.
- Are there standard structures for this type of message?
- path naming?  "notifications"? "messages"? many options!
   - /chat/messages:send
- Idempotency?  You should make 
   - Could use OASIS repeatability request headers.
   - Could the ID be an input parameter?
- Why is this a 202 response?
   - They will be adding an API to get the status of the operation (in public preview)
   - Need to add a `status` field in the `202` response
- Authentication: Skype token or HMAC ?  (And AAD Auth)
   - Connection String ? 
- Also doing errors slightly wrong (no "default") but it's at least consistent with the rest of the spec
   - Can this be changed before GA?

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
