### ISSUE TITLE
Investigate preview strategy Proposal and automation

### ISSUE THREAD

**Issue by salameer** [Azure/azure-rest-api-specs#1888]
- Implement Preview VS stable proposal
- Investigate automation of SDK generation and corresponding branching on Downstream SDK repos.
- Investigate drop locations for generated bits and naming conventions for the drops.
- Talk to @johanste and Derek from Mayuri team about auto generation of CLI container
- Figure out config file story for Preview VS stable code generation

**Comment by lilyjma** [comment]
@salameer - can we close this?

**Comment by salameer** [comment]
Yuuuup

**Comment by salameer** [comment]
To add context, this is being as an internal item at the moment. @weshaggard  is driving a number of conversations with folks on it
