### ISSUE TITLE
Cannot create App Service plan for resource group with single character

### ISSUE THREAD

**Issue by vyadh** [Azure/azure-rest-api-specs#1889]
From the Azure CLI, I'm trying to run the command:
`az appservice plan create --name zweb --resource-group z --is-linux`

But I'm getting the following error, which I understand comes from the REST API specs:
`Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+[^\\.]$'.`

Clearly this matches 'zz' but not 'z'.

Admittedly it is a little odd to have a single-character group, and this is indeed me just playing around. However, it is a valid group name, so it seems a bit odd this command won't accept it? I'll re-create my group with a longer name I suppose, but I thought you might like to know.

**Comment by vyadh** [comment]
I guess this is a general requirement for app service currently, because I just tried the following with similar results:

`az webapp config container set --name name --resource-group z --docker-custom-image-name tag:latest --docker-registry-server-url myregistry.azurecr.io/tag:latest`

**Comment by marstr** [comment]
This is by design, Resource Groups do have a minimum length of two.

**Comment by vyadh** [comment]
Okay, thanks. I guess that must have changed since I raised this, because I was actually using a single character resource group. No big deal obviously.
