### ISSUE TITLE
CS common AzureRegion does not contain westus2, but supported in the portal

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1893]
![image](https://user-images.githubusercontent.com/1050156/31797803-230883dc-b4e5-11e7-94ca-3bfd68574944.png)

The enum should be declared "modelAsString=true", or the complete list should be added.

**Comment by lmazuel** [comment]
(note that I actually edited the swagger locally and "westus2" works as expected)

**Comment by ChrisHMSFT** [comment]
Closing this ticket as our SDKs now take an endpoint as an input instead of the region. 

Thanks,
Chris
