### ISSUE TITLE
FaceAPI: DetectedFace model does not contain FaceAttributes

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#1894]
This makes impossible to get face attribute from a call to `detect`, even if the JSON has it (since the query itself is ok).
See:
https://github.com/Azure/azure-rest-api-specs/blob/00d3e32595333775d0f2739c9ef6d7be8c02f134/specification/cognitiveservices/data-plane/Face/v1.0/Face.json#L1863-L1881

**Comment by ChrisHMSFT** [comment]
Closing this ticket since the issue has been solved. Please re-open if you are still experiencing the issue.

Thanks,
Chris
