### ISSUE TITLE
[IoT- Device Provisioning] REST API Review

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#18979]
o	Service name: Device Provisioning Service
o	Key contact for the review: @Mahesh Rohera, @Kevin Hilscher
o	Whether this is a new or existing API: New API
o	Whether or not your service already been deployed: Already deployed
o	A brief description of the material to be reviewed/changed

The Azure Device Provisioning Service is responsible for onboarding customer IoT devices to Azure such that they can now talk with the cloud or the edge for the purposes of telemetry and command and control. For this session we will be reviewing the device API. The ultimate audience for this API are device builders that want to a use zero touch mechanism to onboard their devices to a customer’s Azure IoT solution.

**Comment by mikekistler** [comment]
Notes from API Review mtg 5/25/22:

- The service has been GA for > 3 years but this is the first time the data plane API doc is being checked in to the azure-rest-api-specs repo.
   - This version is adding the Certificate Management feature to DPS
   - Specific changes / additions to API definition
      - changes to  PUT on `/{idScope}/registrations/{registrationId}/register` 
         - new request body property `clientCertificateCsr` 
         - new response body property `trustBundle`
      - new POST on `/{idScope}/devices/{registrationId}/certificates/issue` operation
      - new GET on `/{idScope}/devices/{registrationId}/operations/{operationId}` operation

Recommendations:
- Drop plans to support AMQP - standardize on MQTT for protocol from IOT clients.

- Standardize line endings for PEM in examples

- Drop Swashbuckle & maintain API defn by hand going forward
   - Might want to explore moving API defn to Cadl
   - Current use of Swashbuckle with PR checks helps detect accidental changes

- Add x-ms-enum with descriptions for each value. We can help make the SDKs produce the "right thing".

- LRO to create a certificate. Some debate on what this should look like to conform to our new LRO pattern. We'll follow up on this one.

Link to Meeting Recording

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
