### ISSUE TITLE
Storage: wrong spec for CheckNameAvailabilityResult

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-rest-api-specs#19]
https://github.com/Azure/azure-rest-api-specs/blob/4be6f83657772df3e1283e58ea9fddb0d66b91be/arm-storage/2015-05-01-preview/swagger/storage.json#L407-L412 : 
> ![image](https://cloud.githubusercontent.com/assets/159209/9870591/2959989c-5b42-11e5-9204-f8b99e7441b5.png)

https://msdn.microsoft.com/en-us/library/azure/mt163642.aspx : 

> ![image](https://cloud.githubusercontent.com/assets/159209/9870597/374459e2-5b42-11e5-9bea-1565ae5af622.png)

`nameAvailable` should be string, not boolean. Currently blocking https://github.com/Azure/azure-sdk-for-go/issues/210

**Comment by ahmetalpbalkan** [comment]
Also no clue why would anyone make something that has only `true` and `false` outcome a string instead of boolean. Congrats to that person. :clap:

**Comment by bingosummer** [comment]
There are some confusing points in the following document.
https://msdn.microsoft.com/en-us/library/azure/mt163642.aspx

![untitled](https://cloud.githubusercontent.com/assets/4787647/9871021/527a574e-5bc3-11e5-80f3-dc694b2a452f.png)

**Comment by brendandixon** [comment]
@ahmetalpbalkan Not clear if this is a specification bug. The Service seems to be returning a bool for most people.

**Comment by ahmetalpbalkan** [comment]
Turns out spec is correct and service/docs were wrong.
