### ISSUE TITLE
[Cognitive Services - Document Translator] REST API Review

### ISSUE THREAD

**Issue by alexhcheng** [Azure/azure-rest-api-specs#19029]
o	Service name: Document Translator
o	Key contact for the review: alcheng
o	Whether this is a new or existing API: new version of existing API
o	Whether or not your service already been deployed: new version has not
o	A brief description of the material to be reviewed/changed
- new single document sync API
- renaming of base path
- restructure of some json input / output

Overview of the change:    [Document Translator API v2.0.docx](https://microsoft.sharepoint.com/:w:/t/MachineTranslationTeam/EWXd_q8I2a1Kp-aP7t528SUBFIEKWOAgVTRqIZNVHnNkbg?e=DhD7Vx)

**Comment by alexhcheng** [comment]
Look at [Api Versioning](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#api-versioning)
Look at [Actions](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#performing-an-action)
[Breaking change policy](https://microsoft.sharepoint.com/:b:/r/teams/azureecosystem/servicerings/Shared%20Documents/Breaking%20Changes/Azure%20Versioning%20and%20Breaking%20Changes%20-%20Policy%20Definition%20v1.2.3.pdf?csf=1&web=1&e=ZTSCSm)

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
