### ISSUE TITLE
Add support for OS Disk resize in VMSS

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#1906]
> In https://github.com/Azure/azure-sdk-for-go/issues/818, @bpoland says:
> Hi there,
> 
> Wondering if it would be possible to add support for resizing an OS disk when deploying a Virtual Machine Scale Set.
> 
> The standalone Virtual machine supports an OsDiskSizeInMB property:
https://github.com/Azure/azure-sdk-for-go/blob/c1ff18326387fa67ccc6e1b17c76e65773684227/arm/compute/models.go#L2267
> However, the Scale Set is missing that property:
https://github.com/Azure/azure-sdk-for-go/blob/c1ff18326387fa67ccc6e1b17c76e65773684227/arm/compute/models.go#L1994
> I have been able to deploy a scale set with an ARM template specifying a disk size property like this (using API version 2017-03-30) so I know it's possible:
> ``` Go
> "storageProfile": {
>    "osDisk": {
>    "caching": "ReadWrite",
>    "createOption": "FromImage",
>    "diskSizeGB": "10",
>    "name": "[concat(variables('vmssName'), '-osp')]",
>    "osType": "Linux",
>    "image": {
>         "uri": "[variables('vmssImageUri')]"
>     }
>   }
> },
> ```
>
> Hope that makes sense -- thanks!

The relevant Swagger Definitions that map to those Go declarations can be found here:

https://github.com/Azure/azure-rest-api-specs/blob/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L3496

https://github.com/Azure/azure-rest-api-specs/blob/02a8a6b5c42725a2036afca5081af273db5fa6f0/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L5426

**Comment by marstr** [comment]
Thanks for the ping on this, @tombuildsstuff! I don't have much visibility there at the moment. I've added the labels above to hopefully send it into triage. I'll keep an eye on this issue to make sure it gets addressed.

**Comment by ig-sinicyn** [comment]
UPD#2: important: the resize works only once. Any consequent deploy with different diskSizeGB will fail with `Changing property 'osDisk.diskSizeGB' is not allowed` error.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
