### ISSUE TITLE
Microsoft.Authorization PIM API Documents Need Updating

### ISSUE THREAD

**Issue by darren-johnson** [Azure/azure-rest-api-specs#19075]
Now that the PIM API has reached GA status, the documents need to be updated to ensure they are consistent and all show the stable version in the code examples as opposed to the preview version.

3 examples of this all showing the preview version are below.

1) In https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-policy-rest-sample#update-a-role-management-policy the sample HTTP request is:

PATCH https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleManagementPolicies/{roleManagementPolicyId}?api-version=2020-10-01-preview

2) In https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-eligibility-rest-sample#remove-eligible-assignment the sample HTTP request is:

PUT https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleEligibilityScheduleRequests/{roleEligibilityScheduleRequestName}?api-version=2020-10-01-preview

3) In https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-eligibility-rest-sample#grant-eligible-assignment the sample HTTP request is:

PUT https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleEligibilityScheduleRequests/{roleEligibilityScheduleRequestName}?api-version=2020-10-01-preview

**Comment by navba-MSFT** [comment]
Both CXP and Service attention label were added. Removed the Service attention label and checking if the CXP team can assist on this.

@darren-johnson Apologies for the late reply. Thanks for reaching out to us and sharing the feedback. We are looking into this issue. We will provide an update on this shortly.

**Comment by navba-MSFT** [comment]
@darren-johnson This PR https://github.com/Azure/azure-docs-rest-apis/pull/4561 has been filed to address this. Thanks again for sharing the feedback. The PR is currently under review. If you have any questions in the meantime, please feel free to ask.

**Comment by navba-MSFT** [comment]
@darren-johnson The PR has been merged https://github.com/Azure/azure-docs-rest-apis/pull/4561. Thanks again for sharing this feedback. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
