### ISSUE TITLE
[Network Application Gateway] pickHostNameFromBackendAddress cannot be set as true

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-rest-api-specs#19129]
The [ApplicationGatewayBackendSettingsPropertiesFormat.pickHostNameFromBackendAddress](https://github.com/Azure/azure-rest-api-specs/blob/2f2b633d940230cbbd5bcf1339a2e1c48674e4a2/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/applicationGateway.json#L1924) is defined as a boolean. However, when it's set as true, I got the following error from the Azure side.

Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayBackendSettingsPickHostNameFromBackendAddressNotAllowed" Message="PickHostNameFromBackendAddress cannot be set to true for BackendSettings '/subscriptions/******/resourceGroups/acctestRG-000000/providers/Microsoft.Network/applicationGateways/acctestag-000000/backendSettingsCollection/acctest-vnet-000000-be-st'

**Comment by navba-MSFT** [comment]
@ms-zhenhua Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will get back to you once we have an update.

**Comment by navba-MSFT** [comment]
@ms-zhenhua I tried to collect the HAR traces while performing the same operation from Azure Portal and that seem to have worked. Below is the Request Body it used. See **"pickHostNameFromBackendAddress":true** in the below request body:

>Request Body:
{"name":"testgw","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw","type":"Microsoft.Network/applicationGateways","location":"southindia","tags":{"Reason":"Repro","CreatedDate":"5/24/2022 6:24:40 AM","CreatedBy":"NA","OwningTeam":"NA"},"properties":{"provisioningState":"Succeeded","resourceGuid":"0ca6960e-0208-4f1a-9a96-9e83e117ef0b","sku":{"name":"Standard_v2","tier":"Standard_v2"},"operationalState":"Running","gatewayIPConfigurations":[{"name":"appGatewayIpConfig","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/gatewayIPConfigurations/appGatewayIpConfig","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","subnet":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/virtualNetworks/testgwvnet/subnets/default"}},"type":"Microsoft.Network/applicationGateways/gatewayIPConfigurations"}],"sslCertificates":[],"trustedRootCertificates":[],"trustedClientCertificates":[],"sslProfiles":[],"frontendIPConfigurations":[{"name":"appGwPublicFrontendIp","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/frontendIPConfigurations/appGwPublicFrontendIp","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","type":"Microsoft.Network/applicationGateways/frontendIPConfigurations","properties":{"provisioningState":"Succeeded","privateIPAllocationMethod":"Dynamic","publicIPAddress":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/publicIPAddresses/testgwpip"},"httpListeners":[{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/httpListeners/test1"}]}}],"frontendPorts":[{"name":"port_80","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/frontendPorts/port_80","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","port":80,"httpListeners":[{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/httpListeners/test1"}]},"type":"Microsoft.Network/applicationGateways/frontendPorts"}],"backendAddressPools":[{"name":"testgwbackend","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/backendAddressPools/testgwbackend","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","backendAddresses":[],"requestRoutingRules":[{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/requestRoutingRules/testrule"}]},"type":"Microsoft.Network/applicationGateways/backendAddressPools"}],"loadDistributionPolicies":[],"backendHttpSettingsCollection":[{"name":"testbackend","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/backendHttpSettingsCollection/testbackend","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","port":80,"protocol":"Http","cookieBasedAffinity":"Disabled","**pickHostNameFromBackendAddress":true**,"path":"/","requestTimeout":20,"requestRoutingRules":[{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/requestRoutingRules/testrule79"}]},"type":"Microsoft.Network/applicationGateways/backendHttpSettingsCollection"}],"backendSettingsCollection":[],"httpListeners":[{"name":"test1","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/httpListeners/test1","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","frontendIPConfiguration":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/frontendIPConfigurations/appGwPublicFrontendIp"},"frontendPort":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/frontendPorts/port_80"},"protocol":"Http","hostNames":[],"requireServerNameIndication":false,"requestRoutingRules":[{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/requestRoutingRules/testrule79"}]},"type":"Microsoft.Network/applicationGateways/httpListeners"}],"listeners":[],"urlPathMaps":[],"requestRoutingRules":[{"name":"testrule","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/requestRoutingRules/testrule79","etag":"W/\"69262e7d-58b9-4bad-88d1-650649e1cab6\"","properties":{"provisioningState":"Succeeded","ruleType":"Basic","priority":1,"httpListener":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/httpListeners/test1"},"backendAddressPool":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/backendAddressPools/testgwbackend"},"backendHttpSettings":{"id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/backendHttpSettingsCollection/testbackend"}},"type":"Microsoft.Network/applicationGateways/requestRoutingRules"}],"routingRules":[],"probes":[{"name":"testtest","id":"/subscriptions/XXXXX/resourceGroups/testgw/providers/Microsoft.Network/applicationGateways/testgw/probes/testtest","properties":{"host":"temp1","path":"/","interval":30,"timeout":30,"unhealthyThreshold":3,"match":{},"minServers":0,"protocol":"Https"}}],"rewriteRuleSets":[],"redirectConfigurations":[],"privateLinkConfigurations":[],"privateEndpointConnections":[],"enableHttp2":false,"autoscaleConfiguration":{"minCapacity":1,"maxCapacity":10}}}


Could you please try the same via[ this REST API call ](https://docs.microsoft.com/en-us/rest/api/application-gateway/application-gateways/create-or-update#code-try-0)and check if that helps ? Awaiting your reply.

**Comment by ms-zhenhua** [comment]
Hi @navba-MSFT, the pickHostNameFromBackendAddress you are testing is under [ApplicationGatewayBackendHttpSettingsPropertiesFormat](https://github.com/Azure/azure-rest-api-specs/blob/2f2b633d940230cbbd5bcf1339a2e1c48674e4a2/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/applicationGateway.json#L1785). There is another pickHostNameFromBackendAddress defined under [ApplicationGatewayBackendSettingsPropertiesFormat](https://github.com/Azure/azure-rest-api-specs/blob/2f2b633d940230cbbd5bcf1339a2e1c48674e4a2/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/applicationGateway.json#L1892) which cannot be set to true

**Comment by navba-MSFT** [comment]
@ms-zhenhua I had a discussion with the AppGW PM team and they informed that, Since you are internal to Microsoft, they will coordinate with you and work on this further.

**Comment by navba-MSFT** [comment]
If you need any further assistance on this let me know.

**Comment by navba-MSFT** [comment]
@ms-zhenhua Since the PM team has informed that they are working on this offline with you, we will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
