### ISSUE TITLE
Cannot Set AgConfiguration in Sql VM AG Listener

### ISSUE THREAD

**Issue by myc2h6o** [Azure/azure-rest-api-specs#19120]
AgConfiguration seems to be used to configure `Automatic Failover`, `Sync Commit`, `Readable Secondary` mentioned in https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/availability-group-azure-portal-configure?view=azuresql&tabs=azure-cli#create-availability-group, however it's marked as `readOnly` and cannot be set in `PUT` api.

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/2f2b633d940230cbbd5bcf1339a2e1c48674e4a2/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/preview/2021-11-01-preview/sqlvm.json#L1049

**Comment by navba-MSFT** [comment]
@myc2h6o Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I see that the Service team has already been involved on this.

@azureSQLGitHub Could you please look into this and share an update ? Awaiting your reply.

**Comment by myc2h6o** [comment]
Fixed by #19189
