### ISSUE TITLE
Container Instances should support environment variable names containing dot '.'

### ISSUE THREAD

**Issue by stephanwehr** [Azure/azure-rest-api-specs#19173]
**System Info**
```
OS: Windows 10
Shell: Ubuntu 20.04 on Windows
Azure CLI: 2.36.0
```

**Expected Behavior**

Executing the following Azure CLI command should create a container instance running Elasticsearch:
`az container create --image elasticsearch:7.3.2 --name es -g test-rg --memory 2 --cpu 1 --ports 9200 --environment-variables "discovery.type=single-node"`

Using environment variable names containing dot '.' should work.

**Current Behavior**

Executing the Azure CLI command exit with an error:
```
(InvalidContainerEnvironmentVariable) The environment variable name in container 'es' of container group 'es' is invalid. A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName').
Code: InvalidContainerEnvironmentVariable
Message: The environment variable name in container 'es' of container group 'es' is invalid. A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName').
```

**Comment by navba-MSFT** [comment]
@stephanwehr Thanks for reaching out to us and sharing this feedback. I was able to reproduce this issue from AzCLI as well as Powershell. Post isolating this issue, I found that this issue isn't related to the Container Instance but the underlying image OS type. 

The bash manual mentions this clearly ([here](http://www.gnu.org/software/bash/manual/bashref.html#Definitions))

>name
A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.

The [elasticSearch](https://hub.docker.com/r/elastic/elasticsearch/tags) image seems to be using Linux OSType. So the fix / workaround has to come from the OS side and not from the AzCLI / REST API Spec. Hope this helps.

**Comment by stephanwehr** [comment]
@navba-MSFT you are correct, Bash can't but Elasticsearch can.

With the "env" command it is possible to set environment variables containing special characters.
Here is an example:
```
# env -i "cluster.initial_master_nodes=elelastico" "my:test:var=value" /bin/bash -c "env"
my:test:var=value
cluster.initial_master_nodes=elelastico
PWD=/root
SHLVL=0
_=/usr/bin/env
```

In Docker compose the environment can be set like this:
```
version: '2.2'

services:

  elasticsearch:
    image: elasticsearch:7.3.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
```

**Comment by stephanwehr** [comment]
I've dug a little bit deeper on this issues and it seems Linux executes bash and other programs with [execve()](https://man7.org/linux/man-pages/man2/execve.2.html).

With [environ()](https://man7.org/linux/man-pages/man7/environ.7.html) an initial environment can be set.

How Linux execute programs can be seen using "strace":
```
$ strace env -i "my:test:var=some text" /bin/bash -c ":" 2>&1 | grep "execve"
execve("/usr/bin/env", ["env", "-i", "my:test:var=some text", "/bin/bash", "-c", ":"], 0x7ffd31dcb018 /* 21 vars */) = 0
execve("/bin/bash", ["/bin/bash", "-c", ":"], 0x5577895c20f0 /* 1 var */) = 0
```

As I understand, on Linux container environments like Docker for example set the initial environment before executing the 1st program inside the container. There is a process environment and bash environment which both can be retrieved using commands like "env" or "printenv".

I assume referring to this error message that the API performs a syntax check on variable names which should not be there:
`{"error":{"code":"InvalidContainerEnvironmentVariable","message":"The environment variable name in container 'es' of container group 'es' is invalid. A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName')."}}`

**Comment by navba-MSFT** [comment]
@stephanwehr I just wanted to confirm if you are able to get this working with elasticsearch image with Linux OStype ? Awaiting your reply.

**Comment by stephanwehr** [comment]
@navba-MSFT I'm not able to get Elasticsearch to work with Linux OStype because environment variables containing dot '.' are not supported.

**Comment by stephanwehr** [comment]
> @stephanwehr AFAIK, this ask is something which violates the IEEE standard for environment variables.
> 
> > Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore)
> 
> Refer [this](https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html).

@navba-MSFT as stated this applies to the **Shell and Utilities** and not necessarily to other programs like Elasticsearch.

There is no hard requirement under Linux or inside a Docker container to use a shell to execute programs.

Linux itself allows variable names of type char:
```c
       #include <stdlib.h>

       int setenv(const char *name, const char *value, int overwrite);
       int unsetenv(const char *name);
```
[Reference](https://man7.org/linux/man-pages/man3/setenv.3.html)

**Comment by navba-MSFT** [comment]
@stephanwehr Thanks for clarifying. I have added the Service Team to look into this feature request ask.

**Comment by iwate** [comment]
I've tried hosting ElasticSearch on ACI and got this issue.
Are there any updates?

**Comment by justinpenguin45** [comment]
Same for me tried to use ElasticSearch with ACI and I get the same error with dotted env variable names. Why is this closed? There is no fix or workaround
