### ISSUE TITLE
[Container Instance] In operation ContainerGroups_CreateOrUpdate, this field `username` should not be required

### ISSUE THREAD

**Issue by MaryGao** [Azure/azure-rest-api-specs#19195]
Our customer found that spawning a container group using `client.containerGroups.createOrUpdate` requires passing `username` in `imageRegistryCredentials` (type `ImageRegistryCredential`), but [this field should not be required if `identity` is present](https://docs.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#deploy-using-an-azure-resource-manager-arm-template). 

After investigation, it is because the `username`  is always a required column in swagger definition. Removing the username from required fields would fix this.
Related links: https://github.com/Azure/azure-rest-api-specs/blob/6eaea09d8b428c0f0b9c8c4b47ae9496ac5fdb10/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2021-10-01/containerInstance.json#L1478-L1481

SDK Issue: https://github.com/Azure/azure-sdk-for-js/issues/21478

**Comment by navba-MSFT** [comment]
@MaryGao Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.
