### ISSUE TITLE
Azure Logic App giving Bad Gateway error when connecting with SFTP server

### ISSUE THREAD

**Issue by AbhishekPanakanti** [Azure/azure-rest-api-specs#19199]
I am trying to create Logic App using SFTP connector that triggers when a file is uploaded to server. While establishing a connection with SFTP server using Password authentication I am getting the error "**BadGateway More diagnostic information: x-ms-client-request-id is**".Any ideas why I may be getting this error ? Please tell me the correct fields to enter the values. I have the following details account = ac240522; 
password = ****; 
server = mft.company.com; 
protocol = sftp/1234; 
path = /folder/download. 

I was able to connect with the same credentials using FileZilla.
[New SFTP Connection](https://i.stack.imgur.com/AN4H6.png)

**Comment by navba-MSFT** [comment]
@AbhishekPanakanti Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

1. 502 Bad Gateway is a generic error. Please share the detailed error message here. This will help us to isolate the issue.
2. Sharing a [forum thread](https://docs.microsoft.com/en-us/answers/questions/764614/logic-app-ssh-sftp-connector-bad-gateway-500.html) where similar issue was reported. Please check if that helps.
3. If you have a firewall at your end, refer the IP configuration considerations [article](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config?tabs=azure-portal#firewall-ip-configuration-considerations).
4. Could you please confirm if you are using [SFTP-SSH](https://docs.microsoft.com/en-us/connectors/sftpwithssh/) connector and not [SFTP](https://docs.microsoft.com/en-us/connectors/sftp/) ? 
5. There are a few SFTP servers which the SFTP-SSH connector doesn't support. The list is [here](https://docs.microsoft.com/en-us/azure/connectors/connectors-sftp-ssh#limits). Please confirm if your server is not part of it. 
6. The parameters for creating the connection are listed [here](https://docs.microsoft.com/en-us/connectors/sftpwithssh/#default-connection). Hope this helps.

**Comment by navba-MSFT** [comment]
@AbhishekPanakanti I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AbhishekPanakanti The action is currently pending on you to check the above suggestions and let us know if you still see the same issue. Please feel free to reopen this thread if you need any further assistance on this.

**Comment by NirajCricket** [comment]
Hey Guys, I hit with same issue, any solution?
