### ISSUE TITLE
[containerApps] ContainerApps_ListSecrets has invalid response code and will throw RestError with 204 code

### ISSUE THREAD

**Issue by MaryGao** [Azure/azure-rest-api-specs#19196]
Our customer found that containerApps.listSecrets throws response code 204 as an error when there is no content but it shouldn't be considered an error. 

After investigation we found that this operation only takes `200` as success code. But when there is no secrets the server will return 204 with empty body so the client will throw `RestError` and this is unexpected. Adding 204 into responses would fix this.

Swagger code line: https://github.com/Azure/azure-rest-api-specs/blob/c5c5e1d0c31a0ceccda42505d6e872ff303d1c80/specification/app/resource-manager/Microsoft.App/stable/2022-03-01/ContainerApps.json#L389-L399

SDK issue link: https://github.com/Azure/azure-sdk-for-js/issues/21101

**Comment by navba-MSFT** [comment]
@MaryGao Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@MaryGao Since there are a few breaking changes with this, I am involving the Service Team to take a look at the feasibility of this changes.

**Comment by nturinski** [comment]
As per the original [issue](https://github.com/Azure/azure-sdk-for-js/issues/21101), this also applies to some delete methods in the `arm-appcontainers` SDK.  That includes:

`managedEnvironments.beginDeleteAndWait`
`containerApps.beginDeleteAndWait`

**Comment by MaryGao** [comment]
> As per the original [issue](https://github.com/Azure/azure-sdk-for-js/issues/21101), this also applies to some delete methods in the `arm-appcontainers` SDK. That includes:
> 
> `managedEnvironments.beginDeleteAndWait` `containerApps.beginDeleteAndWait`

@nturinski Could you create an issue for the package `arm-appcontainers` considering they are different packages so we could better track their status?

**Comment by MaryGao** [comment]
> As per the original [issue](https://github.com/Azure/azure-sdk-for-js/issues/21101), this also applies to some delete methods in the `arm-appcontainers` SDK. That includes:
> 
> `managedEnvironments.beginDeleteAndWait` `containerApps.beginDeleteAndWait`

@nturinski Could you suggest why you add the two deletion operations again?

After checking the original [issue](https://github.com/Azure/azure-sdk-for-js/issues/21101#issuecomment-1098293940), I think we have an agreement that there is no change for `containerApps.beginDeleteAndWait` and  the below description is expected behavior:
- For the operation containerApps.beginDeleteAndWait, it will return undefined and NOT throw any error with 204 header

I'd like to highlight that this would work for operation `managedEnvironments.beginDeleteAndWait` also.

**Comment by MaryGao** [comment]
@navba-MSFT  Any update for this thread?

**Comment by navba-MSFT** [comment]
@MaryGao I have tagged the Service team on this issue. So it is waiting on them as of now.

**Comment by qiaozha** [comment]
close it as resolved in the service backend. Thanks
