### ISSUE TITLE
[Communication - Calling Server] REST API Review

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#19308]
Service name: **ACS Server Calling** 

Key contact for this review:
Richard Cho richardcho@microsoft.com
Min Woo Lee minwoolee@microsoft.com

a. Link to previous API version: 
[azure-rest-api-specs-pr/communicationservicescallingserver.json at dev-communication-CallingServer-2022-04-07-preview · richardcho-msft/azure-rest-api-specs-pr (github.com)](https://github.com/richardcho-msft/azure-rest-api-specs-pr/blob/dev-communication-CallingServer-2022-04-07-preview/specification/communication/data-plane/CallingServer/preview/2021-08-30-preview/communicationservicescallingserver.json)

Has your service already been deployed? Yes

Review material: 
[ACS Server Calling V3 API Design.docx](https://microsoft.sharepoint-df.com/:w:/t/ServerCalling/ER6bbIzEzchBk63as-GPt8kBYp0EQTIz8zkuEZqxLMKGgA?e=m5ynCJ)

Link to swagger: [azure-rest-api-specs-pr/communicationservicescallingserver.json at dev-communication-CallingServer-2022-04-07-preview · richardcho-msft/azure-rest-api-specs-pr (github.com)](https://github.com/richardcho-msft/azure-rest-api-specs-pr/blob/dev-communication-CallingServer-2022-04-07-preview/specification/communication/data-plane/CallingServer/preview/2022-04-07-preview/communicationservicescallingserver.json)

**Comment by markweitzel** [comment]
## API Stewardship Board Review 14-Jun-22

The `createCallRequest` is not really an LRO, so have it return a `200` or `201`
Use a `PUT` for resource creation. This is the preferred method. The `POST` puts a tremendous amount of implementation and management onto the client. It should return the created resource. 

There is a general theme to simplify the api to make a single operation for 
`answer` & `initiate` create resources. This can be a single operation. And should also simplify the corresponding `GET` as well. 
* Schema should be the same
* In the future, `join` may also create a connection resource. 


`callConnections:answer` - Not an LRO. Return `200`
* The ideal way `.../callConnections/<callConnectionId>:answer`  this is a great mental model.  This would enable you to pass in the ID as part of the callbackUri.
* This should return the same resource. 
* A secondary option is to clarify the language of the path. The way this reads now we are answering the collection. Instead, we should try to make this answer a specific object.

* `redirect` and `reject` -- don't make them LROs. 


### References
[Meeting Chat]()
[Meeting Recording]()

### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

**Comment by richardcho-msft** [comment]
> ## API Stewardship Board Review 14-Jun-22
> The `createCallRequest` is not really an LRO, so have it return a `200` or `201` Use a `PUT` for resource creation. This is the preferred method. The `POST` puts a tremendous amount of implementation and management onto the client. It should return the created resource.
> 
> There is a general theme to simplify the api to make a single operation for `answer` & `initiate` create resources. This can be a single operation. And should also simplify the corresponding `GET` as well.
> 
> * Schema should be the same
> * In the future, `join` may also create a connection resource.
> 
> `callConnections:answer` - Not an LRO. Return `200`
> 
> * The ideal way `.../callConnections/<callConnectionId>:answer`  this is a great mental model.  This would enable you to pass in the ID as part of the callbackUri.
> * This should return the same resource.
> * A secondary option is to clarify the language of the path. The way this reads now we are answering the collection. Instead, we should try to make this answer a specific object.
> * `redirect` and `reject` -- don't make them LROs.
> 
> ### References
> Meeting Chat Meeting Recording
> 
> ### Helpful Documentation
> * [Azure API REST Documentation](https://aka.ms/azapi/specs)
> * [Considerations for Service Design](ConsiderationsForServiceDesign.md)
> * [REST API Guidelines](Guidelines.md)
> * [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
> * [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

We will update all our "create" endpoint to return  unified call connection object. And also update our non-LRO endpoints to return appropriate non-LRO response codes.

We would like to maintain separate endpoint for these create requests, ie. create call, answer, and join. Our reasoning is that we want the customers to think they are distinct actions being performed rather than focusing on creating a call connection resource. We also think having separate endpoints reduces chance of errors down the road rather than trying to interpret customer's intentions from the payload.

In terms of changing the methods to PUT instead of current POSTs, this is difficult for us since it would mean a large refactor in how our underlying legacy system works. Currently we rely on generated GUIDs to route requests to appropriate service instances, if we hand over the control of the id generation to customers we would lose our routing mechanism and would have to do a large refactor to accommodate it. For that reason we would like to use the repeatability headers to achieve idempotency with POSTs.

Let us know if those are acceptable tradeoffs.

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 30-Jun-22

> We would like to maintain separate endpoint for these create requests, ie. create call, answer, and join. Our reasoning is that we want the customers to think they are distinct actions being performed rather than focusing on creating a call connection resource. We also think having separate endpoints reduces chance of errors down the road rather than trying to interpret customer's intentions from the payload.
Yes. This is OK. (@JeffreyRichter to add detail)

> In terms of changing the methods to PUT instead of current POSTs, this is difficult for us since it would mean a large refactor in how our underlying legacy system works. Currently we rely on generated GUIDs to route requests to appropriate service instances, if we hand over the control of the id generation to customers we would lose our routing mechanism and would have to do a large refactor to accommodate it. For that reason we would like to use the repeatability headers to achieve idempotency with POSTs.
Yes. This is OK. (@JeffreyRichter to add detail)

* `transferToParticipant` -- Add `Operation-Location` header
* `{callConnectionId}/participants` return an object, not an array. This will allow you flexibility in the future. 

* Where possible, **declare** your collections to be pageable. This will avoid breaking changes in the future


### References 
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1655404491173?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1655404491173&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1655404491173)
[Meeting Recording]()

**Comment by richardcho-msft** [comment]
@[markweitzel](https://github.com/markweitzel) Addressed the following points:
- Updated {callConnectionId}/participants to return an object
- Updated {callConnectionId}/participants to be pageable
- Removed /operations endpoints
- Converted `POST` .../participants:get to `GET` .../participants/{participantMri}
- Did not add Operation-Location header to transferToParticipant as it no longer is considered long running nor returns operationId

**Comment by markweitzel** [comment]
# API Stewardship Board Review: 30-Aug-22

Adding two new APIs to this service. They are included in this PR, part of which was reviewed above. This review is focused on Recognize and Media Streaming operations.

On the web socket API, then understanding how data is moved across the wire will be important. This is especially true when thinking about programming languages other than C#.
* We would like to work with the team on modeling the information that flows across the web socket. This should be a distinct review session. 




## References
* [Design Doc](https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/EZyuzwMGusZDmCazIb7hiC0B8tA44yalWbFGA03vISaWrg)
