### ISSUE TITLE
README.md link for "Getting Started with Azure API Specifications" is a 404

### ISSUE THREAD

**Issue by strefethen** [Azure/azure-rest-api-specs#19319]
I was looking to get more details on the API specifications but the link in the README is a 404

External Contributors can read [Getting Started with Azure API Specifications](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/getting-started-with-azure-api-specifications.md).

**Comment by JackTn** [comment]
@strefethen  is this your want https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Getting%20started%20with%20OpenAPI%20specifications.md

**Comment by koudaiii** [comment]
Recently I found the link, So I sent Pull Request ref #19880 
![image](https://user-images.githubusercontent.com/2929102/181400697-8660dd2c-a8f6-4ff3-9764-e1178c6289b3.png)

**Comment by JackTn** [comment]
@strefethen i saw this link is correct. Can you confirm it and close this issue?
