### ISSUE TITLE
[Marketplace - Catalog] REST API Review for adding Search component

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#19320]
Service name – Marketplace Catalog API Search Service
Key contact for the review – Greg Oks
Whether this is a new or existing API – New API set in existing domain
Whether or not your service already been deployed – already deployed
A brief description of the material to be reviewed/changed – New search API’s in existing marketplace catalog API domain
A link to the PR/issue in the azure-rest-api-specs (public) or azure/azure-rest-api-specs-pr (private) repo - https://github.com/Azure/azure-rest-api-specs/pull/19292

**Comment by czubair** [comment]
Service name – Marketplace Catalog API Search Service
Key contact for the review – Greg Oks
Whether this is a new or existing API – New API set in existing domain
Whether or not your service already been deployed – already deployed
A brief description of the material to be reviewed/changed – New search API’s (new internal service) in existing marketplace catalog API domain
A link to the PR/issue in the azure-rest-api-specs (public) or azure/azure-rest-api-specs-pr (private) repo - https://github.com/Azure/azure-rest-api-specs/pull/19292

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 22-Jun-22

* Recommendation: Make this a preview

* Make the search results pageable using `nextLink`. See: [Collections](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#collections)
> Note: Enabling server driven paging (next link) does not mean that you can not/should not support client driven paging (top/skip). Server driven paging is a safety net for the service. Client driven paging is to enable clients to control how they do paging. A client can tell you that it wants the 10k first items (using top), and you/the service can decide to return those in 7 different pages.




## References
[Meeting Chat]()
[Meeting Recording]()
[Design Document](https://microsofteur-my.sharepoint.com/:p:/g/personal/gregoks_microsoft_com/EUyzrhpvbrFCq5gy8PyjVn0BlEv2EiqBA07LbntnT73ECA?e=JRP00X)

### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

**Comment by gregoks** [comment]
Hi guys,

Its been some time since we has the review  [😄]  just wanted to update that we are working to fix all the issues that came up and I will update my pr soon. 

Meanwhile I wanted to ask if its possible to release to ms docs a private preview version of our api so we could tell selected partners to use it only? And then switch to private?

Thx,

Greg
