### ISSUE TITLE
Cognitive Services data plane spec has model and linter errors

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-rest-api-specs#1933]
As seen in the [Travis CI](https://travis-ci.org/Azure/azure-rest-api-specs/builds/293290951) the [linter](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/293290963) and [model](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/293290968) validations are failing.

**Comment by vladbarosan** [comment]
@DavidLiCIG can you have a look if there are errors here otherwise close this issue please?

**Comment by DavidLiCIG** [comment]
Hi! Issues here should be resolved now but how do I close the issue? I am not sure if I have permission to do so?

**Comment by vladbarosan** [comment]
You can just press the button to close it. If everything is ok I can close it
