### ISSUE TITLE
Cognitive Service data plane swaggers (face, computervision, etc. does not have descriptions).

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#1934]
@fearthecowboy - Please take a look. Filing an issue as discussed.
Some examples 
- https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/data-plane/Face/v1.0/Face.json#L1846

- https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/data-plane/Face/v1.0/Face.json#L1874

**Comment by anuchandy** [comment]
@lebronJ can you please add necessary descriptions?

**Comment by lebronJ** [comment]
Hi, anuchandy, I think the [latest](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/Face/stable/v1.0) Face API spec already has necessary descriptions by last commit.

**Comment by ChrisHMSFT** [comment]
Closing this ticket as the Face API addressed the descriptions. 

@amarzavery please re-open if there are any remaining issues that need to be addressed.

Thanks,
Chris
