### ISSUE TITLE
[Maps - Data Registry] REST API Review

### ISSUE THREAD

**Issue by danielthank** [Azure/azure-rest-api-specs#19370]
Service name: Azure Maps Data Registry Service
Key contact for the review: Eva Ou [evaou@microsoft.com](mailto:evaou@microsoft.com)
Whether this is a new or existing API: new version of an existing API
Whether or not your service already been deployed: not deployed
A brief description of the material to be reviewed/changed: New version of data registry API (old name: data) in Azure Maps

PR: https://github.com/Azure/azure-rest-api-specs/pull/19272

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 23-Jun-22


### Discussion / Notes


### Actions


## References
[Meeting Chat]()
[Meeting Recording]()

### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

<sub>Note: The Teams channel is internal MS.</sup>
