### ISSUE TITLE
Swagger spec for microsoft.web/connections is missing

### ISSUE THREAD

**Issue by kevinlam1** [Azure/azure-rest-api-specs#194]
microsoft.web/connections isn't included in the views.

**Comment by devigned** [comment]
Thank you bring this to our attention!

@naveedaz, what do you think about this?

**Comment by naveedaz** [comment]
Unfortunately Microsoft.Web/connections is internally managed by the Resource Manager team, so it does not generate with our swagger file. I am working with them to figure out a feasible solution.

**Comment by salameer** [comment]
Hi @naveedaz 

Can we kindly get an update on your discussion with the Web/Connections taeam?

**Comment by yungezz** [comment]
close legacy issue.
