### ISSUE TITLE
[Communication - Media composition] REST API Review 

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#19429]
Service Name: 
Azure Communication Services - Media composition

Key contacts:
Orlando Watson: orlando.watson@microsoft.com

PR Link:
https://github.com/Azure/azure-rest-api-specs/pull/19026

Champion Scenarios:
[ACS Media Composition API Champion Scenarios.md](https://microsoft-my.sharepoint-df.com/:t:/p/orwatson/EfpiuARgufVPjZqKoj1CyqUBOvys1Ks6pnWXwVSLUA_r_g?e=y0kGKc)

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 5-Jul-22

* `PUT` & `PATCH` -- `PATCH` is more version resilient, and it's recommended to use `PATCH`.
* If you provide a `kind`, then use that to be explicit. Do not rely on inferencing.
  * If `kind` is a discriminator, then this will be required in Open API. See: [fixed field](https://swagger.io/specification/v2/#fixed-fields-13 says the discriminator must be required)
  * https://grep.app/search?q=discriminator%22%3A&regexp=true&filter[repo][0]=Azure/azure-rest-api-specs&filter[path.pattern][0]=data-plane&filter[lang][0]=JSON
  * https://azure.github.io/autorest/extensions/#x-ms-discriminator-value 
  * https://swagger.io/specification/v2/#composition-and-inheritance-polymorphism
  * https://swagger.io/specification/v2/#models-with-polymorphism-support
* Would be nice to drop `Body` from `MediaCompositionBody`.
* Ensure that the `POST` are idempotent. 
  * This should return a JSON object, not. just a string, e.g. {"status:"not started"} 



## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1655141705680?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1655141705680&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1655141705680)
[Meeting Recording]()
[Powerpoint Arch Diagram](https://microsoft-my.sharepoint-df.com/:p:/p/orwatson/EeXzYe9QRuRKqoTHvf32lPYBJiU1fOoob9WMJ9GkKvNwIw)

**Comment by JeffreyRichter** [comment]
First, let's imagine the service returns the current string back to client code. How is a customer supposed to parse this string and make sense of it? We want this to be easy and not error-prone for customers.

So, I suggest a modeled-as-string enum for units: "pixels" or "percent" and a number representing the value.
