### ISSUE TITLE
[Virtual Machine Extension] schema for `protectedSettingsFromKeyVault` is not clear

### ISSUE THREAD

**Issue by myc2h6o** [Azure/azure-rest-api-specs#19440]
Hi, I'm onboarding `protectedSettingsFromKeyVault` in [Terraform](https://github.com/hashicorp/terraform-provider-azurerm), but the schema seems not quite clear to me. In the Swagger, it is a plain object without any specific properties inside it. But from the example, it seems like it's only accepting a key vault id and the secret url. Is below the only acceptable properties for `protectedSettingsFromKeyVault` or it can accept other properties as wel?

https://github.com/Azure/azure-rest-api-specs/blob/28db62c152a3556a579a6031f730d3f6b9f868a4/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/virtualMachine.json#L1955-L1958

https://github.com/Azure/azure-rest-api-specs/blob/28db62c152a3556a579a6031f730d3f6b9f868a4/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/examples/virtualMachineExamples/VirtualMachineExtensions_Update.json#L18-L22

**Comment by Drewm3** [comment]
It does look like this is a bug in the swagger, at least on first inspection. @sandeepraichura, could you look into this with the VM Extensions dev team to confirm that this is actually a swagger bug, and work to get the bug fixed in an upcoming swagger update.

**Comment by Drewm3** [comment]
Correcting this to actually @MsGabsta who is the right owner. (Sorry Gabby)

**Comment by MsGabsta** [comment]
@Drewm3, I will look into this with the VM Extensions Dev Team.

**Comment by MsGabsta** [comment]
@myc2h6o thank you for opening this issue, it is indeed a bug.  We are working on fixing this, no eta currently.

**Comment by myc2h6o** [comment]
I noticed this is being fixed in 2022-08-01 https://github.com/Azure/azure-rest-api-specs/blob/4b5fe2fb0a5066c4ff2bd429dbd5e1afda6afab3/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-08-01/virtualMachine.json#L1961-L1964

**Comment by MsGabsta** [comment]
I can confirm that this issue has been resolved.

**Comment by MsGabsta** [comment]
We have finalized fix this issue

**Comment by MsGabsta** [comment]
#reassign MsGabsta

**Comment by MsGabsta** [comment]
#reassign @MsGabsta

**Comment by myc2h6o** [comment]
Thanks for the update! Please feel free to close the issue.
