### ISSUE TITLE
[Purview - PDS] REST API Review

### ISSUE THREAD

**Issue by pansharm-ms** [Azure/azure-rest-api-specs#19479]
- Service name: Purview Distribution Service (PDS)

- Key contact for the review: Pankaj Sharma (pansharm@microsoft.com)

- Whether this is a new or existing API: New API

- Whether or not your service already been deployed: Service already deployed

- A brief description of the material to be reviewed/changed:
Added the first version of the PDS API Specs.

- Important Links:
PR: https://github.com/Azure/azure-rest-api-specs/pull/19316

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 19-Oct-22

[Meeting Recording/Transcript](https://microsoft.sharepoint.com/teams/AzureAPIStewardshipBoard/_layouts/15/stream.aspx?id=%2Fteams%2FAzureAPIStewardshipBoard%2FShared%20Documents%2FGeneral%2FRecordings%2F%5BMicrosoft%20Purview%5D%20API%20Review%20%2D%20Issue%20%5F19479%2D20221019%5F120457%2DMeeting%20Recording%2Emp4)
