### ISSUE TITLE
[Communication Services - Sip routing] REST API Review

### ISSUE THREAD

**Issue by nostojicMs** [Azure/azure-rest-api-specs#19503]
Service name: Communication
Key contact for the review: Vadym Moskalenko
Whether this is a new or existing API: existing API (new version)
Whether or not your service already been deployed: Service has been deployed
A brief description of the material to be reviewed/changed: New swagger file definition to review for a new API version of PATCH /sip routing

Pull Request:
https://github.com/Azure/azure-rest-api-specs/pull/19502

Link to Design Document: https://microsoft.sharepoint-df.com/:w:/t/IC3SDK/ESvU8UOBK-ZMn_2frVj_WLcB50ssGwrGZmCp4v-Fn-C-aQ?e=m0O2hg

**Comment by markweitzel** [comment]
[API View](https://apiviewstaging.azurewebsites.net/Assemblies/Review/c11a86b451f04844a1b6ecce296dccce)
