### ISSUE TITLE
[Maps - Render & Spatial Services] REST API Review

### ISSUE THREAD

**Issue by czubair** [Azure/azure-rest-api-specs#19535]
Service name: Azure Maps Render & Spatial Services
Key contact for the review: Gigi Grajo [gigigrajo@microsoft.com](mailto:gigigrajo@microsoft.com) 
Whether this is a new or existing API: new version of an existing API
Whether or not your service already been deployed: not deployed
A brief description of the material to be reviewed/changed: New version of Render API and Spatial API in Azure Maps

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 7-Jul-22

* Pick an api version date that is earlier in time and closer to when this will be released.
* For `hostTemplate` -- make this entire string variable. This enables the user to provide the entire endpoint, this will provide more flexibility, esp. when generating downstream client libraries. 

### Refrences
[Meeting Chat]()
[Meeting Recording]()
