### ISSUE TITLE
[Compute/CloudService] The property name returned by service is `frontendIpConfigurations`, but it's defined as `frontendIPConfigurations`

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-rest-api-specs#19666]
The property name returned by service is `frontendIpConfigurations` (lower case p in Ip), but it's defined as [frontendIPConfigurations](https://github.com/Azure/azure-rest-api-specs/blob/ac40996ab146d1360a4783665bb6c0b13f345aec/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/cloudService.json#L2104) in swagger. Service team needs to fix swagger definition.

_Originally posted by @fengzhou-msft in https://github.com/Azure/azure-sdk-for-net/issues/26713#issuecomment-1134249274_

**Comment by Drewm3** [comment]
I am working with the dev owner of CloudServices to get the swagger file updated.

**Comment by Drewm3** [comment]
This will need to be changed under an upcoming version header because changing the casing in a released version header is considered a breaking change.

**Comment by jaylabell** [comment]
@Drewm3 I would like to assign this issue to you

**Comment by Drewm3** [comment]
The swagger file update was held off until there was a new API version because the API review folks consider a case change a breaking change. That is why this update has taken so long. The fix is rolling out now and should be fully deployed and available in a week or two.

**Comment by Drewm3** [comment]
This has been updated in the latest Cloud Services API spec: https://github.com/Azure/azure-rest-api-specs/blob/fe331143b67ab7679e84c47f659f3c90c0c81f64/specification/compute/resource-manager/Microsoft.Compute/CloudserviceRP/stable/2022-09-04/cloudService.json#L2096
