### ISSUE TITLE
[IoT Central] REST API Review (2022-07-31)

### ISSUE THREAD

**Issue by yang-hai-feng** [Azure/azure-rest-api-specs#19694]
Service name
IoT Central

Key contact for the review
[hayang@microsoft.com](mailto:hayang@microsoft.com), [Avneet.Singh@microsoft.com](mailto:Avneet.Singh@microsoft.com)

Whether this is a new or existing API
Existing API

Whether or not your service already been deployed
No, TBD by end of July

A brief description of the material to be reviewed/changed:

Add Enrollment Group support
Add Scheduled Job Definition support
Add Jobs support
Add Device Group List Devices support
Add Device Relationships support
Add OData support from devices, device groups, and device templates.

[Swagger PR](https://github.com/Azure/azure-rest-api-specs/pull/19693)

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 20-Jul-22

* There are a number of uses of the `$top` and in general prefixes using `$`. 
  * We discourage the use of `$` specifically to indicate that this is not OData (which we don't use in Azure)
    * For preview, it is acceptable to accept `$`, but not document this.
    * For GA, the `$` should be removed.
  * There are 3 list operations that use `$top` -- these are all in preview, so we have flexibility to remove them.
  * [Paging Design for services](https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#pagination) 
* Check the telemetry on `orderby` -- this ties you to a specific implementation under the covers. Moving away from an underlying store that supports this is VERY expensive.
  * It's recommended to support this ONLY IF ABSOLUTELY NECESSARY
* Actions: We recognize that there is the leading `/` for the action path prefix. This is OK b/c it's consistent with the existing GA operations.
* 

### References
* #19403 
* [Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1657480308687?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1657480308687&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1657480308687)
* [Meeting Recording]()


### Helpful Documentation
* [Azure API REST Documentation](https://aka.ms/azapi/specs)
* [Considerations for Service Design](ConsiderationsForServiceDesign.md)
* [REST API Guidelines](Guidelines.md)
* [OpenAPI Style Guidelines](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
* [Breaking Changes](http://aka.ms/AzBreakingChangesPolicy/)

<sub>Note: The Teams channel is internal MS.</sup>

**Comment by yang-hai-feng** [comment]
@markweitzel , Hi Mark, we removed $top, $orderby, $filter from July GA, will revise in a new preview version to align with Azure API Guidance for paging, fixed other comments provided by Mike, please help to review it, as discussed during review meeting, the only break changes are 3 existed integer fields adding a format:'int32', as it is by default treated as int32, this suppose no break.  Thanks!
