### ISSUE TITLE
[Maps - Wayfinder] API Review

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#19690]
Service Name: Azure Maps Wayfinder Service

Key contact for the review: Xubin Zhuge(@xubin Zhuge) / James Jonghan Park(@james Jonghan Park)

**Comment by davsta90** [comment]
for Azure Maps Wayfinder Service the key contact is David Stanchi (@davsta90 or davsta@microsoft.com).
The system does not support attaching html or vsdx files: please use the sharepoint link provided in email to review them

**Comment by davsta90** [comment]
![Creator_visio1](https://user-images.githubusercontent.com/88048110/177848719-0a69ef0d-19b8-42ea-8a36-e47a0e229546.jpg)
![Creator_visio2](https://user-images.githubusercontent.com/88048110/177848759-71d4ec31-b7b3-44f3-a3bc-ce377988129d.jpg)

**Comment by markweitzel** [comment]
## API Stewardship Board Review - 8-Sep-22

* It's not necessary to specify all of the error codes, e.g. `400` and just use `default`.
* don't return an array at a top level--wrap this in a json object. builds in extensibility. 
* should your lists be pageable?? We strongly encourage this to be declared as pageable (even if you don't do this today, you and still declare this in your open api document). 
* `creationMode` -- IF there is a set of known values... document the possible values and model this as an extensible enum. 
  * remove this if it's not needed
  * same note on `ontology`
