### ISSUE TITLE
[Network Application Gateway] `loadDistributionPolicies` cannot be set by default

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-rest-api-specs#19784]
When creating a new Application Gateway with [loadDistributionPolicies](https://github.com/Azure/azure-rest-api-specs/blob/c03c258c7a01a7d57b3110cc20e2e76752b6f2d6/specification/network/resource-manager/Microsoft.Network/stable/2021-08-01/applicationGateway.json#L3177), I got the following error.
Since this property is already used in [the example of MS-DOC](https://docs.microsoft.com/en-us/rest/api/application-gateway/application-gateways/create-or-update?tabs=HTTP#create-application-gateway), can it be configurable by public users by default?
Kindly help confirm this issue. Thanks.

```
{
    "error": {
        "code": "SubscriptionNotRegisteredForFeature",
        "message": "Subscription /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups//providers/Microsoft.Network/subscriptions/ is not registered for feature LoadDistributionPolicy required to carry out the requested operation.",
        "details": []
    }
}
```

**Comment by an-johri** [comment]
LoadDisctibutionPolicy (LDP) feature of ApplicationGateway is not publicly available as of now. At this point of time, this feature can only be used by subscriptions which are registered for this feature. Subscription used in this case is not registered for this feature and therefore, getting this error.

**Comment by peter-bertok** [comment]
> LoadDisctibutionPolicy (LDP) feature of ApplicationGateway is not publicly available as of now. 

Some feedback that I have provided to Microsoft via different channels is that "active-passive" load balancing is a missing feature in Application Gateway. Some legacy applications require this, and is also often used with licensed applications that provide "free" HA/DR passive secondary licenses.

This feature is *very* close to what would be required for active-passive support. It just needs the "1..100" weight per server range changed to "0..100", which would direct all traffic to the primary backend pool unless it is down completely. 

Alternatively, it would be even better to have a priority+weight type of configuration, similarly to how Azure Front Door does it.
