### ISSUE TITLE
[Purview - API Scanning] API Review 2022-07-02-preview

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#19807]
[Purview - API Scanning] API Review

PR #19797 
Planning on reservice this time slot.
I will send a meeting invite to azureapirbcore and azure-restapi-int if you don’t see any issues with the time slots. 
Other information regarding the PR/Service
- Service name: Purview-Scanning
- Key Contact(s): @Phani Kumar Vadali, @Cala Zubair
- New or Existing API: New API endpoints to an existing service
- Deployment: Service is already deployed, and these new endpoints are in use in production from UX 
- This change facilitates UX and customers to execute CRUD operations for IntegrationRuntimes and ManagedVirtualNetworks. Right now, UI calls a different Azure service (Azure Data Factory) for executing these operations. Switching over to calling Purview-Scanning will allow us to intercept request/response routing to Azure Data Factory and return Purview specific models/json-responses to the caller 
- Link to PR: [https://github.com/Azure/azure-rest-api-specs/pull/19797](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F19797&data=05%7C01%7Cmarkweitzel%40microsoft.com%7Cfbc88fd62cb943c8f86e08da68dbf434%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937591152696612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YmIwV9x2XoLcu8cMrkwVA08m5IbpUKS%2BJ5ROmQ1w%2FT0%3D&reserved=0)
Please let me know if anything else is missing.

### API REVIEWS
---
- [x] [Review session 27-07-2022](https://github.com/Azure/azure-rest-api-specs/issues/19807#issuecomment-1205475130)
- [ ] [Review session 18-08-2022]()

**Comment by pvadali-az** [comment]
I just had my review meeting with [@Mark Weitzel](mailto:markweitzel@microsoft.com) and team. 
•	API paths are not consistent across the service.
•	Polymorphic types do not follow pattern that needs to be followed.
•	Long running jobs such as InteractiveQuery do not return correct HTTP status. 
•	Overall, there is a need for a full revisit of Scanning (and other Purview) services. 
 
Next steps:
I will reserve another slot with the stewardship team with all the stakeholders involved, once [@Naga Krishna Yenamandra](mailto:Naga.Yenamandra@microsoft.com) arrives, i.e, with [@Shawn Xiao (IM)](mailto:shawnxia@microsoft.com)’ s team, [@Philip Liu](mailto:Philip.Liu@microsoft.com)’s team, [@Naga Krishna Yenamandra](mailto:Naga.Yenamandra@microsoft.com) and myself.

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 18-Aug-22

Need to meet with Naga.

**Comment by mikekistler** [comment]
@pvadali-az -- Please review the [Azure REST API Style Guidelines](http://aka.ms/azapi/specs). In those guidelines you find a helpful utility that we've been experimenting with, Spectral. Running this within VS Code will help you identify many of the correctness issues that should be addressed, e.g.

- Schema should have a description or title
- Parameter should have a description.
- value property in pageable response should be required

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 18-Aug-22
