### ISSUE TITLE
Compute to add constraints on VM Name

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#1990]
One of the Ruby SDK Customers have pointed out that, while creating a VM (Compute) the SDK does not do any validations on the name. Actually, such validations are derived from the swagger. In the case, the swagger does not have any such constraints (MaxLength, MinLength, Pattern, etc). So, I request the Compute team to consider adding such validations to the swagger. 

Link to the Original Issue: https://github.com/Azure/azure-sdk-for-ruby/issues/1012
Link to the swagger: https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L1189

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
