### ISSUE TITLE
[Cognitive Services - Personalizer] API Review 2022-09-01-preview

### ISSUE THREAD

**Issue by slahabar** [Azure/azure-rest-api-specs#19914]
[swagger pr](https://github.com/Azure/azure-rest-api-specs/pull/19912)
**Service name:** Personalizer 
**Key contact:** lamadh@microsoft.com
**Is this new or existing api?:** This version update introduces a new api set and modifies an existing api set.
Feature importance - We are introducing new api set (get, post, get list, delete) for this feature.
Evaluations - The api sets already exist in production for evaluations. We want to update the response object and add pagination.

**Whether or not your service already have been deployed?** Personalizer is a GA service. We currently support versions v1.0, v1.1-preview.1, v1.1-preview.2, v1.1-preview.3.

**A brief description of the material to be reviewed/changed.**
Feature importance is a technique for assigning scores to input features that indicates the relative importance of each feature when making a prediction. We are introducing api set (get, post, get list, delete) that allows users to manage feature importance jobs. 

Evaluations process uses past data to find better policies. The api set (get, post, get list, delete) already exists in production. We are proposing to modify the existing apis to return different payloads to support multislot feature evaluations and address existing issues like pagination in this version.
[Design document](https://microsoft.sharepoint.com/:w:/t/personalizr/ERBPkR24sCtLt9FIC_IcIkcBQGxZrzUZEVPQdXkF9CicWA?e=eqex8d)

[link to issue](https://github.com/Azure/azure-rest-api-specs/issues/19914)

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 26-Jul-22

### Versioning
* Move to date based approach. 

### `POST`
* The GA version 1.0 -- 
  * `POST` in GA is not idempotent

* Model `/featureImportances/{id}` as a `PUT`
  *  You can get the status of the job. 
  *  You can poll on the `GET`
  *  The `id` is the equivalent of the `name` -- it's the customer provided value.
  *  This is case sensitive and should be unique
  * This will be naturally idempotent.
  * Logically, a `PUT` is the equivalent of a `DELETE` and a `PUT`




## References
[Meeting Chat]()
[Meeting Recording]()
