### ISSUE TITLE
Images.get should return nil instead of an exception

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#1991]
One of the Ruby SDK customers have reported us with an enhancement request: "Images.get should return nil instead of an exception" 

Details: The method throws an exception if image does not exist, it should return null for better code integration. Its absolutely correct, when the method throws an exception, if the resource group does not exist. Can the method be made a little forgiving?

Link to the code: https://github.com/Azure/azure-sdk-for-ruby/blob/master_pre_multiapi/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/images.rb#L121

Link to the original issue: https://github.com/Azure/azure-sdk-for-ruby/issues/1032

Original Issue created by @puneetloya

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue if it is still a concern.
