### ISSUE TITLE
[Monitor] Missing tags in DiagnosticSettingsResource

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#2001]
In operation DiagnoticSettings_CreateOrUpdate, input in DiagnosticSettingsResource:
https://github.com/Azure/azure-rest-api-specs/blob/1a54c04d416c210bebcf3561732f66ab66585b29/specification/monitor/resource-manager/microsoft.insights/2017-05-01-preview/diagnosticsSettings_API.json#L115-L132

No tags are defined in this model, making impossible the creation/updating of tags (nor getting the tags using GET actually).

It's likely that this is supported, please update the model to add these.

Blocking for CLI and Python SDK
https://github.com/Azure/azure-sdk-for-python/issues/1620

FYI @gucalder @troydai

**Comment by asheniam** [comment]
DiagnosticSettingsResource is a proxy resource which does not support tags.
