### ISSUE TITLE
Cognitive Language Services defines `HealthcareEntityCategory` with SCREAMING_SNAKE_CASE but actually returns PascalCase

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#20024]
In the [2022-05-01](https://github.com/Azure/azure-rest-api-specs/blob/eeb2cff50119cfa7b724ac63c768d637ec01827a/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/analyzetext.json#L834) swagger `HealthcareEntityCategory` is defined with SCREAMING_SNAKE_CASE values like `MEDICATION_NAME` but the service returns PascalCase values like `MedicationName`, at least from batch operations.

These are the same as in [3.1](https://github.com/Azure/azure-rest-api-specs/blob/eeb2cff50119cfa7b724ac63c768d637ec01827a/specification/cognitiveservices/data-plane/TextAnalytics/stable/v3.1/TextAnalytics.json#L1886) and, thus, maybe should stay the same, though we have an opportunity to fix them; however, this could force customers to deal with any new values added later.

Since both swaggers already define the values as SCREAMING_SNAKE_CASE, maybe it's best if the service returns them that way?

**Comment by aurghob** [comment]
Changes from https://github.com/Azure/azure-rest-api-specs/pull/20120 have been moved to https://github.com/Azure/azure-rest-api-specs/pull/19558 .

**Comment by aurghob** [comment]
Also : discussed offline that the changes are only being addressed as part of the GA versions (3.1, 2022-05-01) as well the july preview and dev branch.

**Comment by heaths** [comment]
The service team has merged the fixes. Need to update the autorest.md files:

* https://raw.githubusercontent.com/Azure/azure-rest-api-specs/1646226d874de6e8d36ebd3ad088c6c5f6cc6ed0/specification/cognitiveservices/data-plane/TextAnalytics/stable/v3.1/TextAnalytics.json
* https://raw.githubusercontent.com/Azure/azure-rest-api-specs/1646226d874de6e8d36ebd3ad088c6c5f6cc6ed0/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/analyzetext.json

Then fix any BUGBUG comment referencing this issue.

**Comment by heaths** [comment]
Opened separate work items for each language. See links. Resolved by #19558
