### ISSUE TITLE
[Communication Services - Skype token custom expiration time] REST API Review

### ISSUE THREAD

**Issue by garchiro7** [Azure/azure-rest-api-specs#20040]
Service name: ACS Auth
Key contact for this review: [@Cezara Mateiasi](https://skype.visualstudio.com/SPOOL/_queries/edit/2876236/?triage=true#) 
Link to previous API version: 
2022-10-01 https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/communication/data-plane/Identity/stable/2022-10-01/CommunicationIdentity.json
Description of the material to be reviewed/changed:
Adding the possibility for the customers to issue skypetokens with a custom validity period within [1-24] hours range for a second API, that is used to generate an identity and issue a token for it.
Link to swagger:  [Enable custom skypetoken expiration for a 2nd API in the new 2021-10-01 version by cemateia · Pull Request #20039 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/20039)
Champion scenarios that briefly explain how developers will use your API:
PR #20039 

Previously approved: 
The main goal of this feature is to allow developers who use ACS (directly or via SDKs) to customize the skypetokens validity. Until now, ACS only provided the possibility for customers to generate skypetokens for a predefined period of 24 hours.
This functionality will introduce the possibility for customers to generate skypetokens with a custom validity period within the [1-24] hours range.
Customers can make requests for issuing a skypetoken without providing a validity period. In this situation, we will generate a skypetoken with a default validity of 24 hours.
Customers can make requests to issue skypetokens for a custom validity period by providing the validity interval in the request's body. Accepted values are within [1-24] hours range.
For this, we are introducing a new optional integer parameter that will hold the validity time in minutes (expiresInMinutes), in an existing API used to issue skypetokens.
Customers that do not want to use this functionality will be able to issue skypetokens the same way they did before.
No breaking change will be introduced.

New changes: We want to apply the same changes to a second API that is used to generate an identity together with a skypetoken.

**Comment by garchiro7** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/20093

**Comment by markweitzel** [comment]
## API Stewardship Review: 17-Aug-22

The changes proposed are fine, as long as they are additive. 

`minLength`: 1
* Confirmed the same error is returned whether 0 is passed. 
* Recommended that this be removed from the swagger. This is not helpful b/c it's not really a valid value. 

@JeffreyRichter -- Will approve the breaking change. 



## References
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1660752318925?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1660170603111&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1660752318925&allowXTenantAccess=false)
[Meeting Recording]()
