### ISSUE TITLE
[Cognitive Services - Language - Authoring API] <2022-10-01-preview> 

### ISSUE THREAD

**Issue by peytonfraser** [Azure/azure-rest-api-specs#20053]
Service name: Azure Cognitive Service for Language
Key contacts for the review:
- PM: Peyton Fraser <peytonfraser@microsoft.com>
- Authoring Engineering Lead: Hadeer Magdy <hadeermagdy@microsoft.com>
- [CT] Custom Summarization: Amir George <amgeo@microsoft.com>
- [CT] OOS Amir George <amgeo@microsoft.com>
- [QnA] CQA Project Versioning Victor Das <victorda@microsoft.com>
- [CLU] Versioning Amir George <amgeo@microsoft.com>
- [CT] Versioning Amir George <amgeo@microsoft.com>
- Multi region deployment Amir George <amgeo@microsoft.com>

Whether this is a new or existing API: Existing API
Whether or not your service already been deployed: Yes
A brief description of the material to be reviewed/changed: We are adding new features for the October API, including [CT] Custom Summarization, [CT] OOS, [QnA] CQA Project Versioning, [CLU] Versioning, [CT] Versioning, and Multi region deployment.

**Comment by AmirGeorge** [comment]
CLU authoring swagger: https://msazure.visualstudio.com/Cognitive%20Services/_git/API-Language-Authoring?path=/UnifiedAuthoring.APIs/Swagger/Microsoft.ConversationalLanguageUnderstanding.Authoring.v2022-10-01-preview.json

Custom Text authoring swagger: https://msazure.visualstudio.com/Cognitive%20Services/_git/API-Language-Authoring?path=/UnifiedAuthoring.APIs/Swagger/Microsoft.CustomText.Authoring.v2022-10-01-preview.json

**Comment by peytonfraser** [comment]
@markweitzel please see Amir's PRs linked above.

**Comment by markweitzel** [comment]
> https://msazure.visualstudio.com/Cognitive%20Services/_git/API-Language-Authoring?path=/UnifiedAuthoring.APIs/Swagger/Microsoft.CustomText.Authoring.v2022-10-01-preview.json

@peytonfraser -- Because these changes will flow downstream into the SDK process, we use github PRs--not AZDO--as the `source of truth` for API reviews. @AmirGeorge -- would you please create a PR in github?

**Comment by AmirGeorge** [comment]
GitHub PR https://github.com/Azure/azure-rest-api-specs/pull/20347

**Comment by markweitzel** [comment]
# API Stewardship Board Review: 23-Aug-22

* Recommended: `CustomAbstractiveSummarization` --> `CustomAbstractSummarization...`
* Document the TTL for the regex. Customers will need to know how long this can run for.

* `regex`
`expressions` reads well enough. You could consider things like cases, options, matchers, conditions, etc., if you're trying to avoid the repetition.

Consider making `expressions` a map (see below). The map is also more `PATCH`-able, if this API is so inclined.
```json
"expressions": {
  "UK Phone Numbers": {
    "language": "en",
    "pattern": "/.../" }}
```

**Comment by markweitzel** [comment]
# API Stewardship Board Review 31-Aug-22

Reviewing part of the API we did not get to on Aug 23.

Please be sure to use "format": "arm-id" per https://github.com/Azure/autorest/blob/main/packages/libs/openapi/src/v3/formats.ts#L55 for the values in that resourceIds array so they're generated as https://docs.microsoft.com/en-us/dotnet/api/azure.core.resourceidentifier?view=azure-dotnet in languages with fancy types.
* Should this be `x-ms-authorization-auxiliary` in ARM if it's the same concept
* Is there a way to remove the `armToken` - could a service principal be used instead?
  * Talk with Scott Schalb. Also connect with the ARM team (Roopesh Manda)
  * How will the token be acquired, managed, secured, etc...

There is a possibility of creating an "unreachable" / "orphaned" resources in the current process. Three possible scenarios:
* Linked & locked
* Cascade delete
* Dangling links
For the "delete & recreate with the same name scenario" -- make sure the error message is very clear what happened.

`PUT` is a create or replace. `PATCHing` an array is problematic. This should be a `POST` and follow the "Performing an Action" pattern.

`DELETE` - Create a `POST` action for this eg `unassign`
A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request.
