### ISSUE TITLE
[Cognitive Services - Language - Text API] <2022-10-01-preview>

### ISSUE THREAD

**Issue by peytonfraser** [Azure/azure-rest-api-specs#20051]
Service name: Azure Cognitive Service for Language
Key contact for the review:

- Model-Version fallback strategy override - Mikael Sitruk <mikael.sitruk@microsoft.com>
- LD Script Detection - Parag Agrawal <paragag@microsoft.com>
- LD runner up languages - DRI TBD
- [CT] OOS - Nourhan Farid <nourhanfarid@microsoft.com>
- KPE update (minor, position and importance ranking - maxKPE) - Yash Oswal <Yash.Oswal@microsoft.com>
- Abstractive Text Summarization - Yuantao Wang <yuantw@microsoft.com>
- API Contract change to support deprecation message as warning - Lakshmanan Ramu Meenal <Lakshmanan.Ramu@microsoft.com>
- Adding quota error codes in response and retry header - Nourhan Farid <nourhanfarid@microsoft.com>
- Async Job Deletion - Abby Hartman <Abigail.Hahn@microsoft.com>
- [Auto LD] renaming the 'detectedLanguage' attribute in result to something more generic (like: 'languageCode') - Nourhan Farid <nourhanfarid@microsoft.com>
- [Auto LD] Include the detected language even in case of unsupported language error for tasks - Nourhan Farid <nourhanfarid@microsoft.com>

Whether this is a new or existing API: Existing API
Whether or not your service already been deployed: Yes
A brief description of the material to be reviewed/changed: We are adding new features for the October API, including Model-Version fallback strategy override, LD Script Detection, LD runner up languages, [CT] OOS, KPE update (minor, position and importance ranking - maxKPE), Abstractive Text Summarization, API contract change to support deprecation message as warning, Adding quota error codes in response and retry header, Async job deletion, [Auto LD]  renaming the 'detectedLanguage' attribute in result to something more generic (like: 'languageCode'), and [Auto LD] Include the detected language even in case of unsupported language error for tasks

A link to the PR/issue in the azure-rest-api-specs (public)  or azure/azure-rest-api-specs-pr (private) repo
PR: #20371

**Comment by peytonfraser** [comment]
Please include me Peyton Fraser <peytonfraser@microsoft.com> in the meeting invite. Thanks!

**Comment by nourhaanfarid** [comment]
Adding Zero Shot Api 
https://github.com/Azure/azure-rest-api-specs/pull/20239

Auto LD changes
https://github.com/Azure/azure-rest-api-specs/pull/20318/checks

**Comment by bidisha-c** [comment]
Adding Resolutions for NER response: https://github.com/Azure/azure-rest-api-specs/pull/20371

**Comment by akhilayesantarao99** [comment]
Adding PRs for script detection
https://github.com/Azure/azure-rest-api-specs/pull/20339
https://github.com/Azure/azure-rest-api-specs/pull/20472

**Comment by markweitzel** [comment]
# API Stewardship Board Review: 31-Aug-22

* Consider removing resolutions that are not supported. At a minimum, document that this will not be returned.

The suggestion is you'd evolve this and CLU return the raw string, the value scoped to specific units, and the normalized value to a common base unit
* And I guess it's more of an ask before you GA to look at the code customers are writing with your service
* Are people struggling with nested switches?  Then maybe normalize.  If people just care about the type, then maybe it's fine.
Recommendation: 
> During preview, analyze the code that customers write to determine if there is a better strategy to return the values. For example, could we do the conversion ourselves. 

Next Steps
* Good for preview.

**Comment by markweitzel** [comment]
# API Stewardship Board Review: 31-Aug-22
PR: #20339 

Make `script` an extensible enum.
In .NET, for example, a modelAsString=true enum would turn into something like https://azure.github.io/azure-sdk/dotnet_implementation.html#dotnet-enums which is effectively just "known values" for a string.

Next Steps
* This part of the API is good for preview, pending the change to extensible enum.

**Comment by akhilayesantarao99** [comment]
Made script an extensible enum - https://github.com/Azure/azure-rest-api-specs/pull/20472
