### ISSUE TITLE
consumptionmanagement_client query to get the cost of a resource

### ISSUE THREAD

**Issue by tbatra18** [Azure/azure-rest-api-specs#20139]
Hi,

Can anyone explain me the response of :
`consumptionmanagement_client.usage_details.list(scope='/subscriptions/{}/'.format(azure_subscription_id))`

I get a lot of data as response of the api, but not able to understand what all it consist of?

Also, if i want to get a cost of any particular resource on a particular date, can we use the above api or any other api is   @@there?

**Comment by navba-MSFT** [comment]
@tbatra18 Could you please check and let us know if the [sample code provided here](https://docs.microsoft.com/en-us/samples/azure-samples/azure-samples-python-management/costmanagement/) helps ?

**Lists** method should help to list the usage details for the defined scope. See below:

```
list(scope: str, expand: Optional[str] = None, filter: Optional[str] = None, skiptoken: Optional[str] = None, top: Optional[int] = None, metric: Optional[Union[str, _models.Metrictype]] = None, **kwargs: Any) -> Iterable[_models.UsageDetailsListResult]
```

More Info about the **Scope** parameter: This is the scope associated with usage details operations. 

This includes '/subscriptions/{subscriptionId}/' for subscription scope.

For subscription, you can also **add billing period** to the scope using '/providers/Microsoft.Billing/billingPeriods/{**billingPeriodName**}'. 

For e.g. to specify billing period at department scope use '/providers/Microsoft.Billing/departments/{departmentId}/providers/Microsoft.Billing/billingPeriods/{billingPeriodName}'. Also, Modern Commerce Account scopes are '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}' for billingAccount scope, '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}' for billingProfile scope, 'providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}/invoiceSections/{invoiceSectionId}' for invoiceSection scope, and 'providers/Microsoft.Billing/billingAccounts/{billingAccountId}/customers/{customerId}' specific for partners.

More Info [here](https://docs.microsoft.com/en-us/python/api/azure-mgmt-consumption/azure.mgmt.consumption.operations.usagedetailsoperations?view=azure-python#azure-mgmt-consumption-operations-usagedetailsoperations-list).

**Sample Code snippet:**

usage = con_client.usage_details.list(
scope=f"/subscriptions/{subscriptionId}",
expand="properties/additionalInfo",
metric="actualcost",
filter=r"properties/usageEnd ge '2022-05-01' and properties/usageEnd le '2022-05-02'"
)

You could use headers to add your parameters.

pipy link: https://pypi.org/project/azure-mgmt-consumption/10.0.0/

fyi: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py#L160

Hope this helps.

**Comment by navba-MSFT** [comment]
@tbatra18 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tbatra18 The action is pending on you to test the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
