### ISSUE TITLE
Azure Storage - account sas versus service sas - permission order

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-rest-api-specs#20141]
Why is the [service sas permission order](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specify-permissions) specified and the [account sas permission order](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specify-the-account-sas-parameters) doesn't matter? 

```
You can combine permissions to permit a client to perform multiple operations with the same SAS. When you construct the SAS, you must include permissions in the following order:

racwdxltmeop
```

 @diberry

**Comment by navba-MSFT** [comment]
@dfberry Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please elaborate your use case? Could you please provide more context on your requirement ?

**Comment by navba-MSFT** [comment]
@dfberry I wanted to do quick follow-up to check if you had a chance to look at my above comment. Could you please elaborate on your ask and provide us more details on your requirement ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@dfberry I tested creating an account SAS with powershell with random orders of permissions, it worked. So, order shouldn’t matter for account sas. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
