### ISSUE TITLE
Filter doesnt seem to work on the Consumption api 

### ISSUE THREAD

**Issue by tbatra18** [Azure/azure-rest-api-specs#20160]
Hi,

I was trying the date filter on the following api:
https://docs.microsoft.com/en-us/azure/cost-management-billing/automate/get-usage-details-legacy-customer
The filter doesnt seem to work.
I am trying via azure python sdk.

**Comment by navba-MSFT** [comment]
@tbatra18 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you check if the below sample helps ?

Sample Code snippet:
```
usage = con_client.usage_details.list(
scope=f"/subscriptions/{subscriptionId}",
expand="properties/additionalInfo",
metric="actualcost",
filter=r"properties/usageEnd ge '2022-05-01' and properties/usageEnd le '2022-05-02'"
)
```
You could use headers to add your parameters.

pipy link: https://pypi.org/project/azure-mgmt-consumption/10.0.0/

fyi: **https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py#L160**

Hope this helps.

**Comment by navba-MSFT** [comment]
@tbatra18 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tbatra18 The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
