### ISSUE TITLE
Swagger OAV tool Max generated swagger examples have too many properties

### ISSUE THREAD

**Issue by Sandido** [Azure/azure-rest-api-specs#20174]
It looks like some of our Swagger generated files have too many properties shown, and are incorrect for the API operation. 
This API doc: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/list?tabs=HTTP#virtualmachines_list_maximumset_gen 
Is for the [VirtualMachines_List](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/virtualMachine.json#L1079) operation.

The MaximumSet example in that API doc shows the property InstanceView being returned. However, in reality, this property will never be returned in the List operation. It will only be returned when getting a specific VM, in the [VM_Get](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/virtualMachine.json#L793) operation. This is the [VM_Get ](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/get?tabs=HTTP) API doc.

Both operations return the same model in the end, the [VirtualMachine ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/virtualMachine.json#L3074) model. 
I believe because they both return the same model, the MaximumSet example is showing all of the properties in the model even ones the operation will not return in practice.

1. Can the Swagger Example generation [tool ](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/393/Swagger-Example-Generation) be modified or updated to correctly determine which properties are returned in practice?

2. If I were to generate the examples with live payloads, would the MaximumSet example only show the properties returned in the payload, thereby removing InstanceView?

**Comment by raych1** [comment]
@Sandido , automation generation tool only based on the model defined in the swagger and has no idea of server-side implementation.  The solution would be use different model for list operation and get operation aligning to server-side implementation or use payload to generate examples.

I close this issue as it's more related to the oav tool used to generate examples. Can you log issue in [oav repo](https://github.com/Azure/oav/issues) if it's necessary?
