### ISSUE TITLE
[ARM] update subscription client to use latest api-version 2017-08-01

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-rest-api-specs#2017]
See [issue](https://github.com/Azure/azure-sdk-for-node/issues/2330)

The latest api-version will return more tenant info (like domain and display name) for ListTenants call

**Comment by marstr** [comment]
Triaged and removing my assignment.

**Comment by ifeoluwaokunoren** [comment]
The default api-version of 2019-06-01 is now being used.
