### ISSUE TITLE
Compute.Disks should support GetAccess method

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#20186]
Currently, there is a GrantAccess method to grant access for the Disk. But it's better to add a new method like "GetAccess" to retrieve it. So does it make sense to add a new method "GetAccess" for it? Thanks.

**Comment by jaylabell** [comment]
@TravisCragg-MSFT can you please take a look at this issue?

**Comment by TravisCragg-MSFT** [comment]
@neil-yechenwei There is a [GetAccess](https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azdiskaccess?view=azps-8.3.0) method to retrieve existing disk accesses.

**Comment by TravisCragg-MSFT** [comment]
Does this do what you are referring to?

**Comment by TravisCragg-MSFT** [comment]
@neil-yechenwei Can you confirm if the method I linked above does what you are looking for?

**Comment by TravisCragg-MSFT** [comment]
If anyone else would like this enabled, please let us know [Here at this request at feedback.azure.com](https://feedback.azure.com/d365community/idea/9ad23e2a-9c72-ed11-a81b-000d3ae5ae95)
