### ISSUE TITLE
[MachineLearningServices] - Request to document possible values for vmSize in Amlcompute API

### ISSUE THREAD

**Issue by sinbai** [Azure/azure-rest-api-specs#20217]
For the [vmSize](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L3408) property of Amlcompute, is there a set of fixed values for vmSize of [Amlcompute API](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L812)? If so, may I ask for possible values of vmSize to be documented in the swagger? It would help terraform validate it. Thanks in advance.

**Comment by navba-MSFT** [comment]
@sinbai Thanks for reaching out to us and reporting this issue.  The Supported VM series and sizes details are already documented [here](https://docs.microsoft.com/en-us/azure/machine-learning/concept-compute-target#supported-vm-series-and-sizes). 

Please note, Azure Machine Learning doesn't support all VM sizes that Azure Compute supports. To list the available VM sizes, use one of the following methods:

[ListVMSizes REST API](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-08-01/examples/ListVMSizesResult.json)
[supported-vmsizes Python SDK](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.amlcompute.amlcompute#azureml-core-compute-amlcompute-amlcompute-supported-vmsizes)

Hope this answers.

**Comment by navba-MSFT** [comment]
@sinbai I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any queries on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sinbai I hope you had a chance to look at the above comment. Please feel free to reopen this thread if you need any further assistance. We would be happy to help.

**Comment by katbyte** [comment]
@navba-MSFT - can you please re-open this? the original request is not solved: the swagger should accurately represent the API by defining this property as an enum with the following constants.

**Comment by sinbai** [comment]
@navba-MSFT thanks for you reply. Just like katbyte said the request is to enumerate the possible values [here](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L3408) since there's a fixed set of values possible for this API. Could you reopen this issue?

**Comment by navba-MSFT** [comment]
@katbyte The update was shared **[in this comment](https://github.com/Azure/azure-rest-api-specs/issues/20216#issuecomment-1243178979)** in [another issue ](https://github.com/Azure/azure-rest-api-specs/issues/20216)thread. That issue was reported by @sinbai .

I have added the most recent update on that thread which I received from the Product Owners. Hope that helps.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your update. It is worth mentioned that [another issue](https://github.com/Azure/azure-rest-api-specs/issues/20216) is different from this one. This issue requests the enumeration of possible values [here](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L3408) , and another issue is about inconsistencies in case of the returned vm size. Could you track this issue with product team in this thread for a fix?
