### ISSUE TITLE
[Incorrect Swagger]applicationGatewayIpConfigurations defined in swagger but returned applicationGatewayIPConfigurations result to SDK issue

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-rest-api-specs#20256]
this swagger definiation is defining property [applicationGatewayIpConfigurations](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-01-01/virtualNetwork.json#L1556), 
```
"applicationGatewayIpConfigurations": {
          "type": "array",
          "items": {
            "$ref": "./applicationGateway.json#/definitions/ApplicationGatewayIPConfiguration"
          },
          "description": "Application gateway IP configurations of virtual network resource."
        }
```
but actual rest api returned applicationGatewayIPConfigurations, the P is upper case while in swagger it is lower case 
```
{
  "name": "subnet-agw",
  "id": "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/subnet-agw",
  "properties": {
      "applicationGatewayIPConfigurations": [
          {
              "id": "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Network/applicationGateways/<agw-name>/gatewayIPConfigurations/appGatewayIpConfig"
          }
      ]
  },
  "type": "Microsoft.Network/virtualNetworks/subnets"
}
```

please update correspondingly 

Routed from https://github.com/Azure/azure-sdk-for-net/issues/30516

**Comment by techrazor** [comment]
The swagger definition is providing a different value than the rest api returns, is this the wrong repository to report the issue?

**Comment by navba-MSFT** [comment]
@xboxeer Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@xboxeer The above PR has been filed. It is currently under review. In the meantime if you have any queries, please feel free to ask.

**Comment by navba-MSFT** [comment]
@xboxeer I am adding Service team to look in to this further since there is a breaking change in the above PR.

@vnetsuppgithub Could you please look into this issue and provide an update on this ? Thanks in advance.

**Comment by techrazor** [comment]
@vnetsuppgithub / @navba-MSFT, can we get an update on this? Issue has been open since Aug 15 (https://github.com/Azure/azure-sdk-for-net/issues/30516). I understand it's a "breaking change" but the current mis-cased variable doesn't do anything and needs to be fixed so users can get the appropriate data back. Thanks for any assistance you can provide.
