### ISSUE TITLE
Azure Subscriptions - Check Zone Peers isn't work

### ISSUE THREAD

**Issue by tcbjc** [Azure/azure-rest-api-specs#20312]
I want to run the official sample to check Zone Peers. But the sample isn't work. Below is my API request and response.

Post https://management.azure.com/subscriptions/XXXX/providers/Microsoft.Resources/checkZonePeers/?api-version=2020-01-01

{
  "location": "eastus",
  "subscriptionIds": [
  "subscriptions/XXXXXX"
  ]
}

{
    "error": {
        "code": "InvalidResourceType",
        "message": "The resource type could not be found in the namespace 'Microsoft.Resources' for api version '2020-01-01'."
    }
}

**Comment by navba-MSFT** [comment]
@tcbjc Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tcbjc You would need to register the feature before calling the checkZonePeers API.

You could try to register this feature flag either using PowerShell or AzCLI as below:
**PowerShell:**
Please run the following Powershell commands:
• Select the right subscription: Select-AzSubscription -SubscriptionId "123456123456123456"
• To register: Register-AzProviderFeature -FeatureName "AvailabilityZonePeering" -ProviderNamespace "Microsoft.Resources"
• To view register status: Get-AzProviderFeature -FeatureName "AvailabilityZonePeering" -ProviderNamespace  "Microsoft.Resources"



**Azure CLI:**
Please run the following Azure CLI commands:
• Select the right subscription: az account set --subscription "123456123456123456"
• To register: az feature register -n AvailabilityZonePeering --namespace Microsoft.Resources
• To view register status: az feature show -n AvailabilityZonePeering --namespace Microsoft.Resources

Once it is registered, you could try to invoke the [CheckZone Peers Rest API](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/check-zone-peers?tabs=HTTP) and check if that helps.

**Comment by navba-MSFT** [comment]
@tcbjc I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tcbjc The action is currently pending on you to try the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by AndrewCi** [comment]
> [@tcbjc](https://github.com/tcbjc) You would need to register the feature before calling the checkZonePeers API.
> 
> You could try to register this feature flag **either** using PowerShell or AzCLI as below: **PowerShell:** Please run the following Powershell commands: • Select the right subscription: Select-AzSubscription -SubscriptionId "123456123456123456" • To register: Register-AzProviderFeature -FeatureName "AvailabilityZonePeering" -ProviderNamespace "Microsoft.Resources" • To view register status: Get-AzProviderFeature -FeatureName "AvailabilityZonePeering" -ProviderNamespace "Microsoft.Resources"
> 
> **Azure CLI:** Please run the following Azure CLI commands: • Select the right subscription: az account set --subscription "123456123456123456" • To register: az feature register -n AvailabilityZonePeering --namespace Microsoft.Resources • To view register status: az feature show -n AvailabilityZonePeering --namespace Microsoft.Resources
> 
> Once it is registered, you could try to invoke the [CheckZone Peers Rest API](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/check-zone-peers?tabs=HTTP) and check if that helps.

This worked for me!
