### ISSUE TITLE
"Private Dns Zone Groups - Get" returns 200 for non-existent resources

### ISSUE THREAD

**Issue by garylirocks** [Azure/azure-rest-api-specs#20313]
Document link: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/private-dns-zone-groups/get

The API for private-dns-zone-groups returns 200 HTTP status code even when the resource does not exists, this is not consistent with other APIs, which usually return 404 when the resource does not exist.

Noticed this when I try to create a Private Dns Zone Group with the [AzAPI Terraform provider](https://docs.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider), it does not work because the API returns 200, so the provider assumes the resource already exist while it is not.

Example:

For an non-existent private DNS Zone Group, the API return 200
```sh
~ az rest --method get --url "/subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-pe-test-001/providers/Microsoft.Network/privateEndpoints/pe-vault-temp-001/privateDnsZoneGroups/nonExistentDnsZoneGroup?api-version=2022-01-01" --debug

...
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-pe-test-001/providers/Microsoft.Network/privateEndpoints/pe-vault-temp-002/privateDnsZoneGroups/nonExistentDnsZoneGroup?api-version=2022-01-01 HTTP/1.1" 200 None
cli.azure.cli.core.util: Response status: 200
...
```

While for other resource types, the API return 404

```sh
~ az rest --method get --url "/subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-non-existent?api-version=2022-01-01" --debug                                                               cli.knack.log: File logging enabled - writing logs to '/home/gary/.azure/logs'.

...
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-non-existent?api-version=2022-01-01 HTTP/1.1" 404 107
cli.azure.cli.core.util: Response status: 404
...

~ az rest --method get --url "/subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-pe-test-001/providers/Microsoft.Network/privateEndpoints/nonExistentEndpoint?api-version=2022-01-01" --debug

...
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/70256be7-d155-4702-8976-0e7f9a046876/resourceGroups/rg-pe-test-001/providers/Microsoft.Network/privateEndpoints/nonExistentEndpoint?api-version=2022-01-01 HTTP/1.1" 404 240
cli.azure.cli.core.util: Response status: 404
...
```

**Comment by navba-MSFT** [comment]
@garylirocks Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@garylirocks I have reached out to the Product Owners and awaiting their reply. I will update you once I hear from them.

**Comment by navba-MSFT** [comment]
@garylirocks Thanks for reporting this issue. We have created a workitem internally to fix this bug. We have no ETA for the fix. We will update this thread once the fix is released.
