### ISSUE TITLE
Unable to get newly created App Services using the resources Rest API 

### ISSUE THREAD

**Issue by bfeldmann12** [Azure/azure-rest-api-specs#20324]
Calling the resources [List API](https://docs.microsoft.com/en-us/rest/api/resources/resources/list) with or without filters does not return newly created App Services. For example: `https://management.azure.com/subscriptions/****/resources?$filters=resourceType EQ 'Microsoft.Web/Sites'&api-version=2022-05-01` 

However, calling the resource [Get API](https://docs.microsoft.com/en-us/rest/api/resources/resources/get) does return the newly created resource. For example: `https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Web/sites/****?api-version=2022-03-01`

Note, the newly created resource is visible in the Azure Portal under App Services.

**Expected Behavior**
`GET: https://management.azure.com/subscriptions/****/resources?$filters=resourceType EQ 'Microsoft.Web/Sites' AND name EQ '*****'&api-version=2022-05-01`
should return the same resource as calling
`GET: https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Web/sites/****?api-version=2022-03-01`

**Actual Behavior**
The list method with filter by name does not return the resource.

**Steps to Reproduce**
1. Create an Azure App Service
2. Wait for the resource to be created
3. Call the List Api
    1. Verify resource is not returned
5. Call the Get Api
    1. Verify resource is returned

**Comment by navba-MSFT** [comment]
@bfeldmann12 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@bfeldmann12 I created a new webapp and I was able to list my newly created webapp by invoking the [List REST API](https://docs.microsoft.com/en-us/rest/api/resources/resources/list). See below:

**Request**
>GET https://management.azure.com/subscriptions/XXXXXXXXXXXXX/resources?api-version=2022-05-01&%24filters=resourceType%20eq%20%27microsoft.web%2Fsites%27
Authorization: Bearer eyJ0eXXXXXXXXXXXXX

**Response Output**
>cache-control: no-cache
content-length: 62225
content-type: application/json; charset=utf-8
expires: -1
pragma: no-cache
x-ms-correlation-request-id: 8f985969-XXXXXXXXXXXXX-527e302c786d
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id: 8f985969-XXXXXXXXXXXXX-527e302c786d
x-ms-routing-request-id: XXXXXXXXXXXXX-43b5-8b97-527e302c786d

**Response Body**
><<<<< TRIMMING THE OTHER RESOURCE DETAILS >>>>>>>
{
      "id": **"/subscriptions/XXXXXXXXXXXXX/resourceGroups/navbawebappdemo/providers/Microsoft.Web/sites/navbawebappdemo",
      "name": "navbawebappdemo",
      "type": "Microsoft.Web/sites",**
      "kind": "app",
      "location": "southindia",
      "tags": {
        "Reason": "Repro",
        "CreatedDate": "8/30/2022 6:27:46 AM",
      }
    }
<<<<< TRIMMING THE OTHER RESOURCE DETAILS >>>>>>>


Could you please invoke the REST API from the [TryIT option available here](https://docs.microsoft.com/en-us/rest/api/resources/resources/list#code-try-0) ? and then serach for your webapp resource in the response ?

Awaiting your reply.

**Comment by bfeldmann12** [comment]
@navba-MSFT, it turns out this issue has to do with stale cached data between regions. We ran into this issue in our Azure DevOps pipelines using the App Service deploy task, so we also opened a ticket with Microsoft Support. Basically, our DevOps instance is hosted in the Central US, while our resources are being deployed to the East US 2 region. The app service deploy task calls the __https://management.azure.com__ endpoints, which route to the Central US APIs since the Az DevOps instance is hosted in the Central US. Unfortunately, the resources being created in the East US 2 can take some time to sync the information for the new resources into the other regions. The sync process between regions can be delayed anywhere from a few seconds to hours, which in our case is the latter. In working with MS support, we've identified that we can avoid this issue by calling the region-specific REST endpoints, so instead of calling __https://management.azure.com__, we can call __https://eastus2.management.azure.com__.

**Comment by navba-MSFT** [comment]
@bfeldmann12 Thanks for the update. I am glad that the issue has been isolated with the help of Microsoft support. Please let me know if you need any further assistance on this issue.

**Comment by bfeldmann12** [comment]
Thanks for looking into this @navba-MSFT
