### ISSUE TITLE
Security contacts api version 2020-01-01-preview for azure python SDK

### ISSUE THREAD

**Issue by sshearn** [Azure/azure-rest-api-specs#20364]
Currently, the azure python SDK supports version 2017-08-01-preview for security contacts and I'd like it to be updated to 2020-01-01-preview.

This request is forwarded from https://github.com/Azure/azure-sdk-for-python/issues/25771

**Comment by navba-MSFT** [comment]
@sshearn Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sshearn The above PR has been filed an it is currently under review. In the meantime if you have any questions, please feel free to ask.

**Comment by navba-MSFT** [comment]
@sshearn I am checking with the Product owners to get my above PR reviewed. Awaiting their reply now.

**Comment by sshearn** [comment]
@navba-MSFT This doesn't seem to work. On the latest versions of the python SDK, security contacts still only has support for `2017-08-01-preview` and not the current version `2020-01-01-preview`

See: https://github.com/azure-sdk/azure-sdk-for-python/blob/main/sdk/security/azure-mgmt-security/azure/mgmt/security/_security_center.py#L911

API Docs: https://learn.microsoft.com/en-us/rest/api/defenderforcloud/security-contacts

**Comment by sshearn** [comment]
@navba-MSFT any updates on this ?

**Comment by sshearn** [comment]
This still doesn't seem to be fixed. can anyone help ? @navba-MSFT @john35452
