### ISSUE TITLE
Operations on directory roles (Graph API) missing

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-rest-api-specs#2048]
Hi,
The methods for directory roles (and directory at all) are missing in Azure REST API and what most important, in Azure CLI. For PowerShell there is MSOL, but for all the non-Windows and PS world, there is no simple methods to operate on Directory. Now I'm using Azure AD Graph Explorer or Graph API directly from Python. I have created a blog post about this case - maybe it will be helpful for understanding the issue form the user perspective:

https://lnx.azurewebsites.net/directory-roles-for-azure-ad-service-principal/

**Comment by PacoGuy** [comment]
Any update on if the azure-cli is going to implement directory roles to match the functionality of the portal? A time-line would be very much appreciated if so! @sarangan12

**Comment by sarangan12** [comment]
Reassigning due to high priority tasks on my plate

**Comment by yungezz** [comment]
hi @smereczynski graph API is  supported in az cli at ehre: https://docs.microsoft.com/en-us/cli/azure/ext/resource-graph/graph?view=azure-cli-latest. could you pls give it a try? pls feel free to create new issue if met any problem.
