### ISSUE TITLE
CDN FrontDoor: cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01 RuleSetName not returned in GET call

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-rest-api-specs#20560]
```
resp, err := client.Get(ctx, id.ResourceGroup, id.ProfileName, id.RuleSetName, id.RuleName)
props := resp.RuleProperties

props.RuleSetName // this property is empty and does not get returned in the above call
```

[RuleSetName](https://github.com/Azure/azure-rest-api-specs/blob/163e27c0ca7570bc39e00a46f255740d9b3ba3cb/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L2159) is not being return in the `GET` call.

**Comment by ChenglongLiu** [comment]
This issue has been fixed.
