### ISSUE TITLE
[Purview - SQL DevOps Policies] API Review

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#20573]
[Purview - SQL DevOps Policies] API Review

PR: #20107 
Planning on reservice this time slot.

Service name: Purview:
Key Contact(s): 
New or Existing API:
Deployment: 
Description of change / api:
Link to hero scenarios:

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 12-Sep-22

### Notes & Discussion
* Is there a larger view of Purview that shows how all the pieces come together?
* `PUT` 
  * This should take an `id` at the end of the path. 
  * The customer should provide the name, and we will keep a mapping to the internal name/id.
  * You will need to add `ETag` support to avoid race conditions.  
    * `version` is not sufficient for handling race conditions and this is not the proper strategy. This property should 

`PATCH`
* To add a new person, this requires complete knowledge of the existing policy--including all the existing people.
* Consider changing this to a map and supporting patch.

* Need separate `GET` that takes an `id` or `policyName` 


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/522116/189705461-10c84e0d-e1bf-4166-99a0-ba46df2095a8.png)

## References
[Style Guide & Spectral Linter](https://aka.ms/azapi/style)
[Meeting Chat](https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1662485961918?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&parentMessageId=1662485961918&teamName=Azure%20API%20Stewardship%20Board&channelName=General&createdTime=1662485961918&allowXTenantAccess=false)

**Comment by sbhat9** [comment]
We are redesigning APIs as per the review comments
Please refer to the below MS-only document for the latest specs.

- [API Specs](https://microsoftapc-my.sharepoint.com/:w:/g/personal/sagarbhat_microsoft_com/ET9HdMn611BNtnXca3JGHikB5wrn7P7VwbLCw0qZEfzKQw?e=cS5Qnh) 

We have a concern with the List API. In the List API, we have a use case to fetch all the policies (both 'sqlPerfMonitor' and 'securityAuditor'). So, we will go with the below path
 `GET https://{endpoint}/devopsPolicies/aggregate` This will fetch both types of policies.
 
Please let us know your thoughts.

**Comment by mikekistler** [comment]
New PR link: https://github.com/Azure/azure-rest-api-specs/pull/21235

**Comment by mikekistler** [comment]
Notes/comments from meeting on 11/2/2022

- Put vs Patch - their use case is that the entire payload must be consistent and sent in its entirety
   - Jeffrey is sold!
- Path swizzle -- how does that affect permissions? They are basically the same. Not based on hierarchy.
- The "aggregate" segment of "/devopsPolicies is unnecessary -- you should remove it.
- Should remove "policyName" and "id" from DevopsPolicy and add "purviewResourceName" 
- Consider including Etag as a property in DevopsPolicy
- If you accept `if-match` on CreateOrReplace you should also accept it (require it?) on delete.

**Comment by mikekistler** [comment]
After the meeting we chatted in Teams about Cadl and the team was unaware of Cadl but will look into it.
