### ISSUE TITLE
[Cognitive - Form Recognizer] REST API Review - v3.0 GA

### ISSUE THREAD

**Issue by bojunehsu** [Azure/azure-rest-api-specs#20599]
### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous Open API document (swagger) if applicable, and the root paths that have been updated. </sup>
* Design Document: See https://github.com/Azure/azure-rest-api-specs-pr/pull/8150 for internal discussions.
* Previous Open API Doc: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/FormRecognizer/preview/2022-06-30-preview/FormRecognizer.json
* Updated paths: None
* Detailed changes
  * Removed support for Office/HTML input and table footnote/caption (previously supported in 2022-06-30-preview)
  * Renamed Swagger definitions to improve auto generated SDK class naming (no behavioral change)
  * Implement polymorphism in OperationDetails to support different result types (no behavior change)

**Comment by mikekistler** [comment]
Closing issues with no update in past 3 months. Please reopen if needed.
