### ISSUE TITLE
GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/hostingEnvironments?api-version=2022-03-01 Would not return all ASE's if one of ASE is stuck/bad/whatnot

### ISSUE THREAD

**Issue by sergekozh** [Azure/azure-rest-api-specs#20702]
Calling 
GET [https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/hostingEnvironments?api-version=2022-03-01]

Would not return all ASE's if one of ASE is stuck/bad/whatnot. 

I had issue with one of ASE's. 
calling GET /subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Web/hostingEnvironments/{aseName}?api-version=2021-03-01 
would return HTTP500; navigating to it in Azure Portal would show blanks and resources.azure.com would show internal server error.

The problem however is that GET [https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/hostingEnvironments?api-version=2022-03-01](https://management.azure.com/subscriptions/%7bsubscriptionId%7d/providers/Microsoft.Web/hostingEnvironments?api-version=2022-03-01) would only return a some of ASE's until it gets to the broken ASE; when it gets to ".nextLink" of the broken ASE it would not be able go list other ASEs.

I have MSFT premier ticket open for broken ASE and if needed I can provide that for details.
But again, the issue is not about the broken ASE or that doing GET on it would return HTTP500, this is all understandable.

What bothers is when you'd want to get a list of ALL ASE's in the environment, GET [https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/hostingEnvironments?api-version=2022-03-01] would not be a reliable way to do that if you have at least one non-responsive ASE

**Comment by navba-MSFT** [comment]
@sergekozh Thanks for reaching out to us and reporting this issue. Could you please share the support ticket # here ? so that I can look at the progress / status of this issue.

**Comment by navba-MSFT** [comment]
@sergekozh I wanted to do quick follow-up to check if you had a chance to look at my above comment.  Could you please share the support ticket # , once you get a chance. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sergekozh I hope you had a chance to look at the above comment. Could you also try to run the below command and check if you encounter the same issue while listing all ASEs with atleast one broken (non-responsive) ASE in the list ?

>az appservice ase list

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sergekozh The action is pending on you to share the above details. Once you have the above details, Please feel free to reopen this thread. We would be happy to help.
