### ISSUE TITLE
Azure Advisor recommendations do not return all the properties

### ISSUE THREAD

**Issue by JaimePalazuelosB** [Azure/azure-rest-api-specs#20719]
When I return the list of recommendations, or a recommendation detail, there are many properties that are not populated, like "potentialBenefit", "actions", "description" or "learnMoreLink". Those properties can be seen in the Azure Portal, but are also empty on Resource Graph.

Is there any alternative way to obtain those values?

Thanks.

**Comment by navba-MSFT** [comment]
@JaimePalazuelosB Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@JaimePalazuelosB The [Recommendations - Get ](https://learn.microsoft.com/en-us/rest/api/advisor/recommendations/get?tabs=HTTP)and [Recommendations - List Rest API ](https://learn.microsoft.com/en-us/rest/api/advisor/recommendations/list?tabs=HTTP) returns the "potentialBenefit", "actions", "description" or "learnMoreLink" properties. Did you try to invoke these APIs and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@JaimePalazuelosB I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@JaimePalazuelosB The action is currently pending on you to follow the above suggestion and let us know if that helps. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by aravind-ca** [comment]
We are facing the same issue, wherein Advisor Recommendations REST API (for List or Get) does not return all properties.  e.g., Potential benefits, Actions, Remediations are displayed in Azure portal for same subscription, however they are not returned in the REST API.  Please advise how to get this resolved.

**Comment by apd2014** [comment]
Hello everyone. I have the same issue "Azure Advisor recommendations do not return all the properties". Is this issue resolved?

**Comment by anthonyno-softcat** [comment]
@navba-MSFT this issue is still occurring; these are the only fields being returned as part of the `properties` object, and they are not fully populated as described in the documentation: 

![Image](https://github.com/user-attachments/assets/9dcd3919-9c05-41af-a8dc-47ccac7bc354)
