### ISSUE TITLE
Timeout With 500 Error When Creating VNET in WestUS3

### ISSUE THREAD

**Issue by johhess40** [Azure/azure-rest-api-specs#20737]
##Expected Terraform to be able to spin up a simple virtual network in WestUS 3 From Azure DevOps
- Using Microsoft Hosted Agents
- Latest Terraform Version
- Same code deploys fine to CentralUS, EastUS, and WestUS2
##Below is the raw log from the run
```
╷
│ Error: waiting for creation/update of Virtual Network: (Name "vnet-shared-services-westus3-pd" / Resource Group "rg-shared-services-networking-westus3-pd"): Code="InternalServerError" Message="An error occurred." Details=[]
│ 
│   with module.networks_shared_services.azurerm_virtual_network.platform["westus3"],
│   on vnets/vnets.tf line 22, in resource "azurerm_virtual_network" "platform":
│   22: resource "azurerm_virtual_network" "platform" {
│ 
╵
╷
│ Error: waiting for creation/update of Virtual Network: (Name "vnet-identity-westus3-pd" / Resource Group "rg-identity-networking-westus3-pd"): Code="InternalServerError" Message="An error occurred." Details=[]
│ 
│   with module.networks_identity.azurerm_virtual_network.platform["westus3"],
│   on vnets/vnets.tf line 22, in resource "azurerm_virtual_network" "platform":
│   22: resource "azurerm_virtual_network" "platform" {

```

**Comment by navba-MSFT** [comment]
@johhess40 Thanks for reaching out to us and reporting this issue. I tried to create a VNet in West US 3 region and I was able to create it successfully. This issue seems like a transient issue. Could you please let me know if you are still facing this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@johhess40 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  are still facing the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@johhess40 We are unable to reproduce this issue. Seems like this was a transient issue and exponential retrying after sometime should resolve such issues. If you still face the same issue, please feel free to reopen this thread and provide us the time of the issue (in UTC) along with the correlation-id. We would be happy to help.
