### ISSUE TITLE
[Bug][Compute][Virtual Machine] 'source.commandId' cannot be used together with property 'source.script'

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-rest-api-specs#20819]
When I use `PUT /subscriptions/sub-id/resourceGroups/vm-group/providers/Microsoft.Compute/virtualMachines/vm-name/runCommands/run-command-name?api-version=2022-08-01` with body:

```
            "location": 'eastus',
            "properties": {
                "source": {
                    'commandId': 'RunShellScript',
                    'script': [
                        'cd /home',
                        'mkdir test-folder'
                    ]
                },
                "timeoutInSeconds": 10000,
            }
```
the following error happened:
```
 (InvalidParameterConflictingProperties) The property 'source.commandId' cannot be used together with property 'source.script'.
```

My question is why these two parameters are not allowed to use together?

**Comment by Drewm3** [comment]
@nikhilpatel909, could you look into this question please.

**Comment by nikhilpatel909** [comment]
I am looking in to this

**Comment by vivlingaiah** [comment]
@msyyc , Could you remove the below from response body and give a try ? 
'commandId': 'RunShellScript',

**Comment by msyyc** [comment]
Hi @vivlingaiah After removing `commandId`, the cmd run successfully. But It seems that it doesn't create `test-folder` under `/home`. Is there anything I miss?

**Comment by vivlingaiah** [comment]
Hi @msyyc , In managed Run Command (PUT Run Command), script is a string not array. Use semicolon separated commands as "script":  "cd /home; mkdir test-folder" and try.

Refer the sample request body and docs here:
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed#rest-api 
(https://aka.ms/RunCommandManagedLinux)
