### ISSUE TITLE
Cognitive Services data plane:  Computer Vision OcrResult `language` property is incorrect

### ISSUE THREAD

**Issue by jz5** [Azure/azure-rest-api-specs#2084]
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/data-plane/ComputerVision/v1.0/ComputerVision.json#L877

`language` property type has become OcrResult itself.

**Comment by annatisch** [comment]
Updated URL:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/ComputerVision/stable/v1.0/ComputerVision.json#L877

**Comment by annatisch** [comment]
@shakao  - any thoughts on this? :)

**Comment by shakao** [comment]
@annatisch Oh, I added the Visual Search API--I think @DavidLiCIG did the Computer Vision spec

**Comment by ChrisHMSFT** [comment]
Closing this issue since language property is one of many items returned in the OCR result. Please re-open if you still see an issue.

Thanks,
Chris
