### ISSUE TITLE
`ResourceGuardProxy` - missing `PUT` parameter `resourceGuardResourceId`

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#20953]
swagger link: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-12-01/bms.json#L4362

example link: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-12-01/examples/ResourceGuardProxyCRUD/PutResourceGuardProxy.json

In the swagger file, there is no parameter named `resourceGuardResourceId` in `ResourceGuardProxy_Put` while in the example there is. the parameter is needed to create.

**Comment by navba-MSFT** [comment]
@ziyeqf Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ziyeqf AFAIK, the `PUT` operation is using the schema definition from ResourceGuardProxyBaseResource which inturn gets the definition reference from ResourceGuardProxyBase which has the property `resourceGuardResourceId`.

Sending you the below details if that helps.

https://github.com/Azure/azure-rest-api-specs/blob/21426cf85836ec17aaa4f20f58324a8666925e34/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-12-01/bms.json#L4392-L4397


https://github.com/Azure/azure-rest-api-specs/blob/21426cf85836ec17aaa4f20f58324a8666925e34/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-12-01/bms.json#L12551-L12564

https://github.com/Azure/azure-rest-api-specs/blob/21426cf85836ec17aaa4f20f58324a8666925e34/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-12-01/bms.json#L12528-L12534

**Comment by ziyeqf** [comment]
@navba-MSFT Thanks for your insight.

But it seems the `ResourceGuardProxyBase` is referenced in `response` of `ResourceGuardProxy_Put`, rather than `parameters`. and it's needed in parameters.

**Comment by navba-MSFT** [comment]
@ziyeqf The above PR is currently under review.
