### ISSUE TITLE
Not setting BaseUri in the Spec is translated to setting BaseUri to http://localhost by default

### ISSUE THREAD

**Issue by pomortaz** [Azure/azure-rest-api-specs#210]
For Key Vault SDK, some of the public APIs accept a key ID or secret ID, which is made up of a vault URL, key/secret name and the collection title.
E.g.:
	public async Task<KeyBundle> GetKeyAsync(string keyIdentifier, CancellationToken cancellationToken = default(CancellationToken))

Here is an example of a KeyIdentifier: https://vaultName.vault.azure.net:443/keys/keyName/keyVersion 

The default baseUri should be set to an empty string if not provided in the spec to support the above scenario.

**Comment by devigned** [comment]
> The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.

via the Swagger spec

Could you use the [Parameterized Host Extension](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-parameterized-host) for this?

**Comment by pomortaz** [comment]
Thanks. But there are some problems with Parameterized Host:
1. By defaults http:// is added to the start of BaseUri. So for host =  {vault} the BaseUri will be http://https://vaultName.vault.azure.net
 2. Specifying the order of the parameters in the path and host template is not supported when APIs get generated. So for host = {vault} and a path parameter {value}, instead of of having Foo(string vault, string value) it will be Foo(string value, string vault).
 3. Having more than one baseUri is not supported. Key Vault APIs accept keyIdentifier and secretIdentifiers, which are different URLs, but using parameterized host it is not supported to have multiple host templates.

**Comment by devigned** [comment]
I believe this issue has been handled by @amarzavery. Do you feel this is adequately resolved?

**Comment by pomortaz** [comment]
Thanks @devigned and @amarzavery. Yes, this is adequately resolved and we are unblocked. Well done! :+1:
