### ISSUE TITLE
Missing description for policyType

### ISSUE THREAD

**Issue by Freakling** [Azure/azure-rest-api-specs#21000]
https://github.com/Azure/azure-rest-api-specs/blob/2e88f0e0951d1cdbe59db4dafbc48c93a723bfa2/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2022-03-01/bms.json#L5519

This seems to be generated somehow. It is however missing description for policyType as seen in the link below.
https://learn.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/vaults/backuppolicies?pivots=deployment-language-arm-template#:~:text=int-,policyType,-%27Invalid%27%0A%27V1

**Comment by navba-MSFT** [comment]
@Freakling Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Freakling The above PR has been filed it is currently under review. In the meantime if you have any queries, please feel free to ask.
