### ISSUE TITLE
How to set CA_BUNDLE in azure python SDK?

### ISSUE THREAD

**Issue by zshu11** [Azure/azure-rest-api-specs#21054]
Hi, Guys:
I have one question about how to use CA_BUNDLE:
at azure/core/configuration.py, and other PKG-INFO, it has mentioned
that "keyword bool connection_verify: SSL certificate verification. Enabled by default. Set to False to disable,
     alternatively can be set to the path to a CA_BUNDLE file or directory with certificates of trusted CAs."
Then how alternatively to set the path for CA_BUNDLE? since connection_verify is boolean,  should it as:

self.verify ="CA_BUBLE directiory", such as

self.verify ="/var/run/CACerficate"?

Thanks.

**Comment by navba-MSFT** [comment]
@zshu11 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@zshu11 If you are using sync client, verify argument will be passed into requests library and in the doc of requests library [Advanced Usage — Requests 2.28.1 documentation](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification). Its value could be verify='/path/to/certfile'. Hope this answers. If you have any follow-up questions, please feel free to reopen this thread. We would be happy to help.
