### ISSUE TITLE
Support for `Branches` section in Virtual Hub Route Table

### ISSUE THREAD

**Issue by catriona-m** [Azure/azure-rest-api-specs#21136]
The API doesn't appear to have support for the properties in "Branches" in Virtual Hub Route Table that are available via the portal:

![image](https://user-images.githubusercontent.com/86247157/195877110-4dd7d8a9-d296-4e32-b81a-ef221f155b89.png)

**Comment by navba-MSFT** [comment]
@catriona-m Apologies for the late reply. Thanks for reaching out to us and reporting this issue. I tried to check the REST API that is invoked while changing the branches in the _Edit Route Table_ page within _Virtual WAN_ and I could see the below REST API being called by the Azure portal underneath. Hope this helps.

**Request Headers:**
POST https://management.azure.com/subscriptions/XXXXXXXXXXXXXX/resourceGroups/XXXXXXXX/providers/Microsoft.Network/virtualHubs/New/effectiveRoutes?api-version=2022-01-01 HTTP/1.1
Host: management.azure.com
Connection: keep-alive
Content-Length: 219
Authorization: Bearer eyXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Type: application/json

**Request Body:**
{"VirtualWanResourceType":"RouteTable","ResourceId":"/subscriptions/XXXXXXXXX/resourceGroups/XXXXXX/providers/Microsoft.Network/virtualHubs/New/hubRouteTables/defaultRouteTable"}




**Response output:**
HTTP/1.1 202
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 4
Content-Type: application/json; charset=utf-8
Expires: -1
Location: https://management.azure.com/subscriptions/XXXXXXXXXXXXXXXXXXXX/providers/Microsoft.Network/locations/westindia/operationResults/6ce3cba7-701b-4ca0-8f97-58f9f358e5d4?api-version=2022-01-01
Retry-After: 10
x-ms-request-id: 6ce3cba7-701b-4ca0-8f97-58f9f358e5d4
azure-asyncoperation: https://management.azure.com/subscriptions/XXXXXXXXXXXXXXX/providers/Microsoft.Network/locations/westindia/operations/6ce3cba7-701b-4ca0-8f97-58f9f358e5d4?api-version=2022-01-01
x-ms-correlation-request-id: be240546-fa87-4681-97da-0283fd62512e
azure-asyncnotification: Enabled
x-ms-arm-service-request-id: 418a094e-c3c4-4e7d-82e1-1a77213df2ee
Strict-Transport-Security: max-age=31536000; includeSubDomains
Server: Microsoft-HTTPAPI/2.0
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-routing-request-id: CENTRALINDIA:20221115T054516Z:be240546-fa87-4681-97da-0283fd62512e
Access-Control-Expose-Headers: Retry-After,x-ms-request-id,azure-asyncoperation,x-ms-correlation-request-id,azure-asyncnotification,x-ms-arm-service-request-id,Strict-Transport-Security,Date,Location,Server,x-ms-ratelimit-remaining-subscription-writes,x-ms-routing-request-id,Content-Length
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
Date: Tue, 15 Nov 2022 05:45:15 GMT

**Comment by navba-MSFT** [comment]
@catriona-m The action is currently pending on you to try the above action plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by mlcooper** [comment]
@navba-MSFT this is the [documentation](https://learn.microsoft.com/en-us/rest/api/virtualwan/hub-route-tables/create-or-update?tabs=HTTP) I am looking at for the API for for vHub Route tables. I do not see anything in this document which would allow me to configure this setting I circled below. Are you able to point the setting out in the documentation?
![image](https://user-images.githubusercontent.com/9505606/209249260-b9c0ebac-77d9-4219-8b7c-a5fc0f94639e.png)
