### ISSUE TITLE
When will Postgres on cosmos become public stable/preview?

### ISSUE THREAD

**Issue by mastoj** [Azure/azure-rest-api-specs#21179]
I noticed that https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL/preview/2020-10-05-privatepreview/postgresqlhsc.json is still in private preview state. With the actual service being GA it would be nice to have this in a public state as well.

**Comment by navba-MSFT** [comment]
@mastoj Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mastoj Azure Cosmos DB for PostgreSQL in Generally Available (GA) on Oct 12, 2022. More Info [here](https://devblogs.microsoft.com/cosmosdb/distributed-postgresql-comes-to-azure-cosmos-db/).

**Comment by navba-MSFT** [comment]
@mastoj Providing public and GA'd version of REST APIs is in our product roadmap for the current semester. If you need a tentative ETA for the same let me know. We could be happy to provide you more details. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mastoj I hope you had a chance to look at the above comment. If you need any further assistance or have any follow-up queries on this issue, please feel free to reopen this thread. We would be happy to help.

**Comment by mastoj** [comment]
@navba-MSFT , been busy so haven't had the time to follow up. I would love to have a tentative ETA since we won't start using it for real until we have it in the API. Manually provisioning the service isn't our thing.

**Comment by navba-MSFT** [comment]
@mastoj Thanks for getting back. I will provide more details on the tentative ETA soon.

**Comment by navba-MSFT** [comment]
@mastoj We're currently planning for Rest API GA to go live by end of December this year.

**Comment by mastoj** [comment]
@navba-MSFT has the API gone live yet? You mentioned December in the previous comment.

**Comment by mastoj** [comment]
@navba-MSFT do you have an update?
