### ISSUE TITLE
[DataProtection/BackupVaults] Failed to create backupVaults with datastoreType value set to SnapshotStore

### ISSUE THREAD

**Issue by sinbai** [Azure/azure-rest-api-specs#21183]
When creating the backupVaults with  the [datastoreType](https://github.com/Azure/azure-rest-api-specs/blob/9366804c62e024801daf8a578924099ff644ccf6/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-05-01/dataprotection.json#L6111) value set to `SnapshotStore` via the latest version [API](https://github.com/Azure/azure-rest-api-specs/blob/9366804c62e024801daf8a578924099ff644ccf6/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-05-01/dataprotection.json#L380), the error occurs as follows.

Error:
```

{
    "error": {
        "additionalInfo": [
            {
                "type": "UserFacingError",
                "info": {
                    "message": "Input provided for the call is invalid",
                    "recommendedAction": [
                        "Please check the required inputs"
                    ],
                    "details": null,
                    "code": "BMSUserErrorInvalidInput",
                    "target": "",
                    "innerError": null,
                    "isRetryable": false,
                    "isUserError": false,
                    "properties": {
                        "ActivityId": "8cea6775-2521-4f90-8b71-6fcf7794a1da"
                    }
                }
            }
        ],
        "code": "BMSUserErrorInvalidInput",
        "message": "Input provided for the call is invalid",
        "target": null,
        "details": null
    }
}
```
Request URL: https://management.azure.com/subscriptions/xxx/resourceGroups/1019/providers/Microsoft.DataProtection/backupVaults/sft-3?api-version=2022-05-01

Request Body:
`{"location":"eastus","properties":{"storageSettings":[{"datastoreType":"SnapshotStore","type":"LocallyRedundant"}]},"tags":{}}`

**Comment by navba-MSFT** [comment]
@sinbai Apologies for the late reply. Thanks for reaching out to us and reporting this issue. It seems like the valid enum values for the storage settings are `ArchiveStore, OperationalStore, VaultStore`.

So could you please try to specify either of the above enum values instead of `SnapshotStore` and check if that helps ?

In the meantime, I will be creating a PR to get this addressed.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your reply. Since the enum values for the storage settings are listed in the [latest API](https://github.com/Azure/azure-rest-api-specs/blob/9366804c62e024801daf8a578924099ff644ccf6/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-05-01/dataprotection.json#L6113) as `ArchiveStore`, `SnapshotStore`, `VaultStore`. If the `SnapshotStore` should be replaced with `OperationalStore`, the API should  be updated first. This is because Terraform relies on the Azure API to create Data Protection Backup Vaults. Could you let me know once the Azure API is updated?

Refer to the original terraform issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/18826

**Comment by navba-MSFT** [comment]
@sinbai Thanks for getting back. As mentioned in my above comment, I will be creating a PR to update the same and this will be reviewed by the Service team later.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your time:).
