### ISSUE TITLE
[AKS] resolve ARM completeness issues

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-rest-api-specs#2129]
Once #1956 is merged, there are still several [validation errors](http://az-bot.azurewebsites.net/linter?fileName=1956_1512851283400.json) that the `autorest --azure-validator` linter points out.

- ERROR (OperationsAPIImplementation/R3023/RPCViolation): Operations API must be implemented for '/providers/Microsoft.ContainerService/operations'.
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-09-30/location.json:36:2 ($.paths)
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-08-31/managedClusters.json:36:2 ($.paths)
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-07-01/containerService.json:36:2 ($.paths)
- ERROR (TrackedResourcePatchOperation/R3026/RPCViolation): Tracked resource 'ContainerService' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-07-01/containerService.json:748:4 ($.definitions.ContainerService)
- ERROR (TrackedResourcePatchOperation/R3026/RPCViolation): Tracked resource 'ManagedCluster' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-08-31/managedClusters.json:825:4 ($.definitions.ManagedCluster)
- ERROR (TrackedResourcePatchOperation/R3026/RPCViolation): Tracked resource 'ManagedClusterAccessProfile' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.
    - file:///Users/matt/Projects/azure-rest-api-specs/specification/containerservices/resource-manager/Microsoft.ContainerService/2017-08-31/managedClusters.json:897:4 ($.definitions.ManagedClusterAccessProfile)

**Comment by jnoller** [comment]
@mboersma can't tell if this is still an actionable issue

**Comment by mboersma** [comment]
Nope! We implemented PATCH and the discovery endpoint and cleaned up the linter warnings a while ago, but I never closed this bug. Thanks for the nudge @jnoller. 🖖
