### ISSUE TITLE
`keyvault` - PUT response is inconsistent with PUT request when `createMode = recover`

### ISSUE THREAD

**Issue by ms-zhenhua** [Azure/azure-rest-api-specs#21306]
Steps:
1. Create a new key vault instance with `networkAcls.ipRules = ["1.2.3.4/32"]`
2. Soft delete the key vault instance
3. Recreate the key vault instance with `createMode = recover` and `networkAcls.ipRules = ["1.2.3.6/32"]`
Expected Result: `networkAcls.ipRules = ["1.2.3.6/32"]` in the recreated key vault
Actual Result: `networkAcls.ipRules = ["1.2.3.4/32"]` in the recreated key vault

PUT REQUEST:
{
    "location": "westeurope",
    "properties": {
        "accessPolicies": [],
        "createMode": "recover",
        "enablePurgeProtection": true,
        "enableRbacAuthorization": false,
        "enableSoftDelete": true,
        "enabledForDeployment": false,
        "enabledForDiskEncryption": false,
        "enabledForTemplateDeployment": false,
        "networkAcls": {
            "bypass": "None",
            "defaultAction": "Deny",
            "ipRules": [
                {
                    "value": "1.2.3.6"
                }
            ],
            "virtualNetworkRules": [
                {
                    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ademo-rg/providers/Microsoft.Network/virtualNetworks/ademo-vn/subnets/default"
                }
            ]
        },
        "publicNetworkAccess": "Enabled",
        "sku": {
            "family": "A",
            "name": "standard"
        },
        "tenantId": "00000000-0000-0000-0000-000000000000"
    },
    "tags": {}
}

PUT RESPONSE:
{
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ademo-rg/providers/Microsoft.KeyVault/vaults/ademo-kv",
    "name": "ademo-kv",
    "type": "Microsoft.KeyVault/vaults",
    "location": "westeurope",
    "tags": {},
    "systemData": {
        "createdBy": "00000000-0000-0000-0000-000000000000",
        "createdByType": "Application",
        "createdAt": "2022-10-27T02:49:21.94Z",
        "lastModifiedBy": "00000000-0000-0000-0000-000000000000",
        "lastModifiedByType": "Application",
        "lastModifiedAt": "2022-10-27T06:06:50.141Z"
    },
    "properties": {
        "sku": {
            "family": "A",
            "name": "standard"
        },
        "tenantId": "00000000-0000-0000-0000-000000000000",
        "networkAcls": {
            "bypass": "None",
            "defaultAction": "Deny",
            "ipRules": [
                {
                    "value": "1.2.3.4/32"
                }
            ],
            "virtualNetworkRules": []
        },
        "accessPolicies": [],
        "enabledForDeployment": false,
        "enabledForDiskEncryption": false,
        "enabledForTemplateDeployment": false,
        "enableSoftDelete": true,
        "enableRbacAuthorization": false,
        "enablePurgeProtection": true,
        "vaultUri": "https://ademo-kv.vault.azure.net/",
        "provisioningState": "Succeeded",
        "publicNetworkAccess": "Enabled"
    }
}

X-Ms-Correlation-Request-Id: 439ef9c7-0b4f-32c8-b081-8247da2a6f1c

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@RandalliLama, @schaabs, @jlichwa. Could you please look into this once you get a chance ?

**Comment by jlichwa** [comment]
It is by design. During recovery all properties remain the same. You will need to update after recovery to change any attributes.

**Comment by navba-MSFT** [comment]
Thanks @jlichwa for your reply.

@ms-zhenhua Please look at the above comment by @jlichwa and let us know if you have any follow-up question on this. Awaiting your reply.
