### ISSUE TITLE
Can we create long term retention backup for sql managed instances using terraform

### ISSUE THREAD

**Issue by mahesh2543** [Azure/azure-rest-api-specs#21343]
@TechyMatt @spikewang
 AN SQL instance has a default backup of PITR(7 days), but can we create a LTR using terraform.

**Comment by navba-MSFT** [comment]
@mahesh2543 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please let us know if you the below article serves your requirement ? Awaiting your reply.

[Microsoft.Sql managedInstances/databases/backupLongTermRetentionPolicies using Terraform](https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/managedinstances/databases/backuplongtermretentionpolicies?pivots=deployment-language-terraform)

**Comment by navba-MSFT** [comment]
@mahesh2543 The action is currently pending on you to check if the above suggestion helps. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
