### ISSUE TITLE
`compute` Gallery doesn't return `publicNamePrefix`

### ISSUE THREAD

**Issue by myc2h6o** [Azure/azure-rest-api-specs#21342]
When using below request to create a community gallery, publicNamePrefix is set but not returned in the GET response. Though the value can be extracted from `publicNames`, it violates https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Semantic-and-Model-Violations-Reference.md#roundtrip_missing_property.

```
PUT /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}
{
  "location": "eastus",
  "properties": {
    "sharingProfile": {
      "permissions": "Community",
      "communityGalleryInfo": {
        "publicNamePrefix": "prefix",
        "publisherUri": "publisherurl.net",
        "publisherContact": "publisher@test.net",
        "eula": "testeula"
      }
    }
  }
}

GET response:
{
  "properties": {
    "sharingProfile": {
      "communityGalleryInfo": {
...
        "publicNames": [
          "prefix-446a305e-2918-473a-8244-1a2fa18d9d5c"
        ]
      }
    }
  }
}

```

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/5fc05d0f0b15cbf16de942cadce464b495c66a58/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json#L37
https://github.com/Azure/azure-rest-api-specs/blob/5fc05d0f0b15cbf16de942cadce464b495c66a58/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json#L1873

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@Drewm3, @avirishuv, @Vaibhav-Agar, @amjads1 Could you please look into this once you get a chance ?

**Comment by Drewm3** [comment]
@sandeepraichura, could you please look into this issue.

**Comment by kangsun-ctrl** [comment]
Pr for this has been merged, rolling out right. This can be closed after fully rollout.

**Comment by sandeepraichura** [comment]
@myc2h6o - Closing this out as it has been addressed
