### ISSUE TITLE
Outdated  documentation

### ISSUE THREAD

**Issue by nikidandwani** [Azure/azure-rest-api-specs#21354]
Hi team,
runtimeSubnetId was the old way of doing it and now it is no longer needed. 
It is very confusing to still see it being used or required in API specification documentation below
[Microsoft.App/managedEnvironments - Bicep, ARM template & Terraform AzAPI reference | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Ftemplates%2Fmicrosoft.app%2Fmanagedenvironments%3Fpivots%3Ddeployment-language-bicep%23vnetconfiguration&data=05%7C01%7Cnikita.dandwani%40microsoft.com%7Cafbabb32444d45fa234708dabb45993e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638028204873609470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GHiZGVcsujyJIRUouHKdael5sN8%2BRDYkYVGvieLpi7M%3D&reserved=0)
Could you remove the property or at least update the description that is more relevant and in line with the latest product?

https://github.com/Azure/azure-rest-api-specs/blob/5fc05d0f0b15cbf16de942cadce464b495c66a58/specification/app/resource-manager/Microsoft.App/preview/2022-06-01-preview/ManagedEnvironments.json#L811

**Comment by navba-MSFT** [comment]
@nikidandwani Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@nikidandwani The above PR is currently under review. In the meantime, please feel free to ask any follow-up questions.

**Comment by nikidandwani** [comment]
Thanks for the update and quick response @navba-MSFT . I see that the documentation is updated with "this field is deprecated and no longer needed..."
is it not possible to remove this field completely from the API specs? it is still confusing to see why it is still mentioned.

**Comment by navba-MSFT** [comment]
@nikidandwani Removing property from an already shipped API is a breaking change which will most likely not be approved. So to avoid any confusion the quick workaround here is to fix the documentation mentioning that this is deprecated.
