### ISSUE TITLE
Model validation LRO_RESPONSE_HEADER is not applicable to data-planes but triggers breaks in Model Validation

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#21418]
Apparently the Model Validation for LRO_RESPONSE_HEADER only applies to ARM (managment) specs, but the check runs against data plane specs and triggers false failures.

**Comment by raych1** [comment]
I created an [issue](https://github.com/Azure/oav/issues/895) to track this. @tjprescott, please also review the change we're going to make if that works for data-plane specs.
