### ISSUE TITLE
Add to the Azure API does the support for create_mode of GeoRestore for Postgres Flexible Server

### ISSUE THREAD

**Issue by SebTardif** [Azure/azure-rest-api-specs#21438]
We would like to be able to automate DR Geo Restore of our Postgres Flexible Server

**Comment by navba-MSFT** [comment]
@SebTardif Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@SebTardif You can refer this latest preview swagger changes here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-03-08-preview/FlexibleServers.json

Hope this helps.

**Comment by navba-MSFT** [comment]
@SebTardif I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by SebTardif** [comment]
@navba-MSFT Thanks, that what I was looking for.

**Comment by navba-MSFT** [comment]
@SebTardif Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
