### ISSUE TITLE
CDN Front Door does not expose `AnomalyScoring` as an ENUM value

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-rest-api-specs#21435]
Please see [Terraform issue](https://github.com/hashicorp/terraform-provider-azurerm/pull/19095) for full details. The issue is that with Front Door adopting DRS 2.0+ OWASP model they do not expose the ENUM value `AnomalyScoring` as an ENUM value in the swagger so the CLI tools which need to implement this functionality need to hard code this value in their code base and create their own validation rules based on the DRS version.

**Comment by t-bzhan** [comment]
Added the ENUM via https://github.com/Azure/azure-rest-api-specs/pull/21947/files
