### ISSUE TITLE
SecurityInsights: ThreatIntelligence (TAXII) Data Connector API not round trip consistent

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#21487]
The `taxiiLookbackPeriod` is defined as a "date-time" format in Swagger, which represents a RFC3339 date time. Whilst, on return it is in format "01/02/2006 15:04:05".

The `pollingFrequency` is defined as an enum. When specifying it using one of the enum value (a string), it returns an integer (0, 1, 2) in response.

The issue exists for both TI and TI TAXII data connector resources, at least for 2022-10-01-preview.

**Comment by pho-enix** [comment]
This is killing the python SDK:
```
Unable to deserialize response data. Data: 01/01/1970 00:00:00, iso-8601
```
Thus I would like to encourage you to go for ISO-8601 instead of RFC3339, as ISO-8601 is a subset of RFC3339.

**Comment by magodo** [comment]
Service has fixed this API, closing it.
