### ISSUE TITLE
Azure Billing API `billingSubscriptionName`

### ISSUE THREAD

**Issue by mclacore** [Azure/azure-rest-api-specs#21481]
What is this field `billingSubscriptionName`? Reference: https://learn.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/invoices/list-by-billing-subscription?tabs=HTTP

I've tried using this particular API request, and I receive back a 404 error. I've tried using the subscription ID and the subscription name, but 404 each attempt. I've confirmed that I'm using the correct `billingAccountName` because I'm getting back hydrated responses with other API requests. This seems to be the only API request that is giving me a 404, and it's unfortunate because it's the one I need.

**Comment by navba-MSFT** [comment]
@mclacore Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mclacore The billingSubscriptionName --> is your concerned subscription id. 

I am sending you the sample REST API that I invoked at my end and got the successful response. Hope this helps.

> https://management.azure.com/providers/Microsoft.Billing/billingAccounts/default/billingSubscriptions/12345-12345-1234-1234/invoices?api-version=2020-05-01&periodEndDate=2022-09-30&periodStartDate=2022-09-01

**Comment by navba-MSFT** [comment]
@mclacore I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by bradenwatkins** [comment]
@mclacore I also see that you referenced the documentation for 2019-10-01-preview. It's recommended that you refer to the latest stable version [2020-05-01](https://learn.microsoft.com/en-us/rest/api/billing/2020-05-01/invoices/list-by-billing-subscription?tabs=HTTP) which shows a similar example to what @navba-MSFT shared.

**Comment by mclacore** [comment]
@bradenwatkins sorry was on PTO.

So the newer version works, but it's also only limited to Microsoft Partner Agreement and Microsoft Customer Agreement type of subscriptions. It doesn't seem to support Microsoft Online Service Program, which is what we need it for.
