### ISSUE TITLE
LogAnalytics Saved Searches api has a maximum 15 tags limitation

### ISSUE THREAD

**Issue by seggcsont** [Azure/azure-rest-api-specs#21506]
When we are trying to create Saved Searches via terraform we get bad request.
It turned out that we are using 16 tags for this resource.

I managed to run REST Api calls via curl and it was also failing with Bad request `[The element 'Tags' has invalid child element 'Tag'.]`

If I use 15 tags or less the request is success and the resource is created.

I have found this max 15 tags limitation in the Tagging docs, but it does not mention Saved Searches.

API: https://learn.microsoft.com/en-us/rest/api/loganalytics/saved-searches/create-or-update?tabs=HTTP 
api-version: 2020-08-01

**Comment by navba-MSFT** [comment]
@seggcsont Apologies for the late reply. Thanks for reaching out to us and reporting this issue. AFAIK, This seems like a limitation from ARM resource tag side. 
REF: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources?tabs=json

This information seems to be missing from our docs. I am checking this further. I will keep you posted.
