### ISSUE TITLE
[question][loadBalancer] Loadbalancer Expand options

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-rest-api-specs#21582]
IT seems for LoadBalancers, we can expand some optional fields in LB GET Response. [Refrence](https://learn.microsoft.com/en-us/rest/api/load-balancer/load-balancers/get?tabs=Go#uri-parameters)

It is not documented what properties can be expanded.

What properties can be expanded? Additionally, I can't seem to find any example for expand operation.

**Comment by PramodValavala-MSFT** [comment]
@vijayrajah Thanks for the feedback! The format for `$expand` is like this - `frontendIPConfigurations/publicIpAddress` - which expands the sub-resource. Similarly, other sub-resources in the model can be expanded and you can specify multiple sub-resources by comma-separated values.
