### ISSUE TITLE
Azure Billing API returns empty array

### ISSUE THREAD

**Issue by georged** [Azure/azure-rest-api-specs#21580]
1. Register an app in Azure AD, add a secret
2. Assign Billing Reader role on subscription level to the app
3. Authenticate using appid/secret 
4. Call to https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=2019-10-01-preview returns empty array (calling `az billing account list` in Azure CLI returns non-empty array).
The problem is identical to https://stackoverflow.com/questions/71480731/management-azure-com-rest-api-returns-200-ok-with-an-empty-json-array-but-the

**Comment by navba-MSFT** [comment]
@georged Could you please invoke the below REST API and check if that helps ? Because the Azure CLI is also invoking the same REST API underneath.

_**https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=2020-05-01**_

Hope this helps.

**Comment by georged** [comment]
@navba-MSFT it does not work either. This is the script that I'm using to test:

```ps
$tenantId = "deadbeef-abb1-4fa6-a46d-deadbeef3a1a"
$applicationId = "deadbeef-707c-4907-b5f6-deadbeef9b32"
$secret = "1234567"
$apiEndpointUri = "https://management.azure.com/" 

$RequestAccessTokenUri = "https://login.microsoftonline.com/$tenantId/oauth2/token"
$body = "grant_type=client_credentials&client_id=$($applicationId)&client_secret=$($secret)&resource=$($apiEndpointUri)" 

$AccessToken = Invoke-RestMethod -Method Post -Uri $RequestAccessTokenUri -Body $body -ContentType $contentType

$apiuri = "$($apiEndpointUri)providers/Microsoft.Billing/billingAccounts/?api-version=2020-05-01"
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Authorization", "Bearer $($AccessToken.access_token)")

Invoke-RestMethod -Uri $apiuri -Headers $headers | ConvertTo-Json
```

**Comment by navba-MSFT** [comment]
@georged This is my sample script that worked for me. The only difference is I used my user account and you used an AAD app to get the token. Could you please check if the below sample works ?

```
$auth=Get-AzAccessToken
$authHeader= $auth.token

$output= Invoke-WebRequest -UseBasicParsing https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=2020-05-01 -Headers @{"Authorization"="Bearer $authHeader"}

$response = ConvertFrom-Json $output.Content

echo $response
```

**Comment by georged** [comment]
@navba-MSFT that script works. That's the point: interactive login works, but service principal with the billing reader role gets empty results. It feels like something is missing when acquiring the token - maybe the right scope?

**Comment by navba-MSFT** [comment]
Thanks @georged for getting back. While I used to below sample I am able to get the non empty response.

```
$tenantId = "XXXXXXXXX"
$applicationId = "XXXXXXXXX"
$secret = "XXXXXXXXX"
$apiEndpointUri = "https://management.azure.com/" 

$RequestAccessTokenUri = "https://login.microsoftonline.com/$tenantId/oauth2/token"
$body = "grant_type=client_credentials&client_id=$($applicationId)&client_secret=$($secret)&resource=$($apiEndpointUri)" 

$AccessToken = Invoke-RestMethod -Method Post -Uri $RequestAccessTokenUri -Body $body -ContentType 'application/x-www-form-urlencoded'

$output= Invoke-WebRequest -UseBasicParsing https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=2020-05-01 -Headers @{"Authorization"="Bearer $AccessToken.access_token"}

$response = ConvertFrom-Json $output.Content -ErrorAction SilentlyContinue

echo $response
```

**Comment by georged** [comment]
@navba-MSFT what is the role assignment for the application? I'm assigning billing reader for a subscription in the tenant and getting empty array back though expected to have an array with the account the subscription is under.

Could it be a limitation of a billing account type? I have Microsoft Online Services Program account.

**Comment by muazmian** [comment]
@georged have you added Billing Account owner role to the service principal on the Cost Management and Billing?

You can navigate to Cost Management and Billing -> Billing Account -> Access Control

https://learn.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/billing-role-assignments/add-by-billing-account?tabs=HTTP

**Comment by georged** [comment]
@muazmian I assigned service principal a Billing Reader role on the subscription level. My billing account is MOSP and I don't see Access Control on the account level.

**Comment by navba-MSFT** [comment]
@georged An _**Account Administrator**_ is the only owner for a Microsoft Online Service Program billing account. The role is assigned to a person who signed up for Azure. Account Administrators are authorized to perform various billing tasks like create subscriptions, view invoices or change the billing for a subscription. 

More Info: https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/manage-billing-access#account-administrators-for-microsoft-online-service-program-accounts

**Comment by georged** [comment]
@navba-MSFT I'm not looking for ownership, I'm looking only to **read** billing information. Literally from the [same page](https://learn.microsoft.com/azure/cost-management-billing/manage/manage-billing-access#give-others-access-to-view-billing-information):

![image](https://user-images.githubusercontent.com/928254/206110194-bbd6ae51-341e-4771-b764-226873d015d9.png)

I did assign Billing Reader role to the service principal on one of the subscriptions and expected read access, but billing account simply does not show up.

**Comment by navba-MSFT** [comment]
@georged The permissions needed to view the billing account is different from the permissions to control at subscription. BillingReader or any custom role is a RBAC permission on Subscription scope and they have **no significance or impact on controlling/managing billing accounts.**

One has to go to “Cost Management + Billing” blade in Portal -> Billing Scopes -> Select any billing account -> Access Control blade IAM to grant any one permissions to view billing accounts. 
 
Coming to Billing Reader, it’s a permissions available at Subscription scope. Once a user grants this permission, they will be able to download or manage only invoices of the subscription (below), not the billing accounts.
[Invoices - List By Billing Subscription - REST API (Azure Billing) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/invoices/list-by-billing-subscription?tabs=HTTP)

**Comment by georged** [comment]
@navba-MSFT 

looks like it does work - thank you for taking time to explain this! Yes, indeed, no access to the billing account. I'm yet to sort out all the details but one thing that threw me off is documentation. The 2019 version does not work at all for me - even interactively I'm getting 404. The 2020 version (api-version=2020-05-01) does work but **only** with **default** billing account, i.e. 

https://management.azure.com/providers/Microsoft.Billing/billingAccounts/default/billingSubscriptions/{subscriptionId}/invoices?periodStartDate={periodStartDate}&periodEndDate={periodEndDate}&api-version=2020-05-01

That version does work for billing readers as well because the billing account is never specified or accessed explicitly. Changes between api versions are a bit confusing, perhaps that  could be clarified somehow.

Thank you for your help!
