### ISSUE TITLE
Microsoft.ContainerRegistry anonymousPullEnabled docs should clarify not avail all SKUs

### ISSUE THREAD

**Issue by devlead** [Azure/azure-rest-api-specs#21603]
Unsure if this is the right place, but currently looking at just Bicep/Arm docs it's not clear that anonymousPullEnabled:true  isn't always avail.

https://github.com/Azure/azure-rest-api-specs/blob/be6cd9ccfcb6ba08c1c206627026eabfbff31fc1/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2022-02-01-preview/containerregistry.json#L4855-L4858

It should be documented that this is SKU-dependent and not available in all tiers.

Anonymous pull access is a preview feature, available in the Standard and Premium [service tiers](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-skus).

Reference: https://learn.microsoft.com/en-us/azure/container-registry/anonymous-pull-access

**Comment by RakeshMohanMSFT** [comment]
@devlead Thank you for reaching out, we are looking into it.
