### ISSUE TITLE
Cognitive-Services CustomSearch swagger says parameter is optional, though it is required by service

### ISSUE THREAD

**Issue by williexu** [Azure/azure-rest-api-specs#2162]
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/cognitiveservices/data-plane/CustomSearch/v1.0/CustomSearch.json#L104

The following message is returned with my 400 when it is not provided:
```
{
   "error": {
      "code": "BadArgument",
      "message": "Parameter customConfig is missed."
   }
}
```

**Comment by anuchandy** [comment]
@q3blend Hi Ahmed, can you please take a look

**Comment by q3blend** [comment]
customconfig was changed to be a required param

**Comment by williexu** [comment]
Fixed with: https://github.com/Azure/azure-rest-api-specs/pull/2304
