### ISSUE TITLE
Content-Moderator is not following the guidelines of other cognitive services

### ISSUE THREAD

**Issue by williexu** [Azure/azure-rest-api-specs#2168]
-Cognitive Services swaggers should have `add-credentials: true` added to the readme.
-securityDefinitions/security should be added to swagger for "apim_key"
-`ocpApimSubscriptionKeyParameter` should be removed from swagger

This will allow content-moderator to be consistent with the other cognitive services and utilize the credentials implemented in the generated sdks.

**Comment by lmazuel** [comment]
Fixed in #2173
