### ISSUE TITLE
[Purview - Data Quality] API Review

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#21695]
PR: https://github.com/Azure/azure-rest-api-specs/pull/20925

**Comment by markweitzel** [comment]
## API Stewardship Board Review: 1-Dec-22

the "rules" concept is also reflected in the scanning service 
* Scanning: `/classificationsrules/`
* DataQuality: `/accounts/{accountId}/assets/{assetId}/rules`
Recommendation: Change the path to /dataquality/assets/

`asset` - This is a Purview wide concept.  

British spelling `favourite`.  In general, if we have multiple regional spellings I prefer the shorter form which would be `favorite` in this case.

`POST` - These are not idempotent by default. The recommended approach of using `PUT` or `PATCH` (with upsert).

**Comment by mikekistler** [comment]
@Souvik-Microsoft the PR linked to this review request has been closed due to inactivity. Are you still hoping to move forward with these changes or has there been a plan change?
