### ISSUE TITLE
mgmt, GA release for resourcehealth

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-rest-api-specs#21712]
Currently should be "2020-05-01"

Add a live test configure, add a few tests, GA it if all good.

Likely don't need to create any resource for test, as Test sub should already have lots of resources. Just use a GenericResource to get one, <-- sorry that likely won't work for live, as the service principal may not have read permit outside the resource group (so maybe create a resource with GenericResource).

**Comment by XiaofeiCao** [comment]
1.0.0 released:
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-resourcehealth/1.0.0/jar
