### ISSUE TITLE
Document meaning of `-internal` and `-preview` version postfixes

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#218]
Currently, it's unclear what these prefixes mean.
Is `preview` mean API could be changed or deprecated or it's in some kind of close beta?
Is `private` mean that only Microsoft employees can access it?

**Comment by devigned** [comment]
Yes, agreed.

Preview indicates the API for the service has not yet reached a stable state and their may be breaking changes prior to the stable release.

Which "private" spec are you referring to?

**Comment by IvanGoncharov** [comment]
@devigned Thank you for quick answer.
> Which "private" spec are you referring to?

```
arm-intune/2015-01-14-privatepreview
```
And also `internal` ones:
```
arm-graphrbac/1.42-previewInternal
arm-graphrbac/1.6-internal
```

**Comment by salameer** [comment]
Hi  Ivan,

Private preview means that only a subset of customers have access to this API version. internal means that APIs are not available for public consumption yet.

Apologies for the late response but just wanted to make sure we follow up anyways :), pleae reopen if you have more questions on this

THanks

Samer
