### ISSUE TITLE
API Management - ContentType & ContentItem - CreateOrUpdate - missing the 'in body' parameter specification

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/azure-rest-api-specs#21849]
The `CreateOrUpdate` operations on both of the following resource types are missing the `in body` parameter in the OpenAPI specification (OAS):

- `Microsoft.ApiManagement/service/contentTypes`
- `Microsoft.ApiManagement/service/contentTypes/contentItems`

This causes the documentation `TryIt` and autogenerated libraries (e.g. nodejs `@azure/arm-apimanagement`) to break, as they don't support passing in the properties in the body, making these resource types unable to be updated or created.

For example, if you run the ["Try It" for this API](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/content-item/create-or-update?tabs=HTTP), it doesn't give you a body field in the auto-generated REST HTTP request form. The body field is needed, but it doesn't give you that field as it's not populated in the OAS for this resource type.

See the specification missing the body field here:

https://github.com/Azure/azure-rest-api-specs/blob/0ece0bdf675ef3fb1d5fc79cdf5bb3e286c83a1d/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimcontenttypes.json#L393-L459

They both need this added to their parameters lists:

```json
{
  "name": "parameters",
  "in": "body",
  "required": true,
  "schema": {
    "$ref": "./definitions.json#/definitions/{ContentTypeContract|ContentItemContract}"
  },
  "description": "Create or update parameters."
}
```

**Comment by navba-MSFT** [comment]
@AdamCoulterOz Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@AdamCoulterOz The above PR has been filed and it is currently under review.
