### ISSUE TITLE
Mark preferred version of API

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#219]
Some APIs have multiple swagger files documenting different versions.
In my service, by default show preferred version of API.
Could you please mark preferred version somehow?
For example, Git support symlinks, so you can make `$api/preferred/` point to dir with preferred version.

**Comment by devigned** [comment]
Hmm... I guess we could do this, but I'm not sure we should think about versions this way. All versions that are not preview should be equally good for customers to consume. There is no preference other than feature set.

We could provide guidance to point toward the latest, or simply have the convention rather than having to keep updating the symlink when a new version is available.

**Comment by IvanGoncharov** [comment]
> All versions that are not preview should be equally good for customers to consume.

Yes, but imagine person see your API for the first time without any previous experience with it.
I think, to explain it litter bit better I need to provide some background.

I working on [catalog](https://github.com/APIs-guru/api-models) of OpenAPI specs for public APIs.
Some [3rd-party tools/services](https://github.com/APIs-guru/api-models#existing-integrations) access it through my own [API](https://github.com/APIs-guru/api-models/blob/master/API.md).
Have [sample site](http://apis-guru.github.io/) to show simplest possible UI, I think this screenshot illustrate my current strategy:
![selection_030](https://cloud.githubusercontent.com/assets/8336157/14225288/3cd78e20-f8c6-11e5-88a4-087f0047dbff.jpg)
So user always presented with the latest version but it still possible to choose previous ones.

> We could provide guidance to point toward the latest, or simply have the convention rather than having to keep updating the symlink when a new version is available.

Alternative you can mark it inside spec itself.
In my catalog I currently use `x-preferred` with boolean as the value.
I borrow this semantic from Google Discovery, see [this](https://developers.google.com/discovery/v1/reference/apis/list#response)

**Comment by salameer** [comment]
Hi @IvanGoncharov 

The API documented inside the Stable folder version are the ones that customer would write stable code on, "Preffered" would be a bit subjective depending on what the customers are looking for. Some prefer latest stable other prefer to lock on a specific version.

Ofcourse the more recent version that you adopt the more goodness of features you get :)

Thanks

Closing and please re-open if you have other questions

Thanks

Samer
