### ISSUE TITLE
path of `Threat Intelligence` in `SecurityInsights@2022-11-01` does not match

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#21906]
the path of indicator in swagger is defined [`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/threatIntelligence/main/indicators/{name}`]("https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2022-11-01/ThreatIntelligence.json#L145"), but what we get is `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/threatIntelligence/{name}`

**Comment by TimLPaterson** [comment]
We have identified this as an issue with our API implementation not an issue with the swagger.  We will correct the API response.

**Comment by ziyeqf** [comment]
resolved as the response is consistent with Swagger
