### ISSUE TITLE
Error: creating/updating DataProtection BackupInstance Invalid input

### ISSUE THREAD

**Issue by axelluguercio** [Azure/azure-rest-api-specs#21911]
While creating a backup instance for a blob storage with Terraform I got the following error response:

Error: creating/updating DataProtection BackupInstance ("Backup Instance: (Name \"instance-stdevelopbancaempresa\" / Backup Vault Name \"bv-develop-business-banking\" / Resource Group \"rg-desarrollo-banca-empresas\")"): dataprotection.BackupInstancesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BMSUserErrorInvalidInput" Message="Input provided for the call is invalid" AdditionalInfo=[{"info":{"code":"BMSUserErrorInvalidInput","details":null,"innerError":null,"isRetryable":false,"isUserError":false,"message":"Input provided for the call is invalid","properties":{"ActivityId":"9704e318-5e0c-49cc-aa72-2e72a2c6b67d"},"recommendedAction":["Please check the required inputs"],"target":""},"type":"UserFacingError"}]

**Comment by navba-MSFT** [comment]
@axelluguercio Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@axelluguercio The valid enum values for the storage settings are `ArchiveStore`, `OperationalStore`, `VaultStore`. Could you please confirm if you had used one of these values ? Awaiting your reply.

https://github.com/Azure/azure-rest-api-specs/blob/d6b9d9d7ea3fa4e6c0c2122f7641b9b009ce482e/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2022-05-01/dataprotection.json#L6109-L6118

**Comment by navba-MSFT** [comment]
@axelluguercio I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@axelluguercio The action is currently pending on you to provide an update on the above. Please feel free to reopen this thread, once you are ready to resume troubleshooting on this issue. We would be happy to help.
