### ISSUE TITLE
Azure Cost Management API: Query throws same error

### ISSUE THREAD

**Issue by wiemkr** [Azure/azure-rest-api-specs#21966]
### Invoke-RestMethod: {"error":{"code":"BadRequest","message":"Invalid query definition, Dataset is invalid or not supplied....}}

It's been days that I'm trying to resolve this.

I'm running this cmd:
`Invoke-RestMethod -Method POST -Headers $headers -Uri "https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.CostManagement/query?api-version=2022-10-01" -Body $body -ContentType 'application/json'`

with parameters:

`$headers = @{Authorization = "Bearer $token"}`
`$body = @{
     type = 'Usage'
     timeframe = 'MonthToDate'
     dataset = @{
         granularity = 'Daily'
         aggregation = @{
             totalCost = @{
                 name = 'PreTaxCost'
                 function = 'Sum'
             }
         }
         grouping = @(
             @{
                 type = 'Dimension'
                 name = 'ServiceName'
             }
         )
     }
 }`

I'm running the cmd on PowerShell 7.2.6.

My user has Azure Cost Management Reader role in active assignment.

Can you help me resolve this?

Thank you!

**Comment by navba-MSFT** [comment]
@wiemkr Thanks for reaching out to us and reporting this issue.  We would be happy to assist you on this. 
Could you please share your use case and elaborate on your requirement ?Awaiting your reply.

**Comment by navba-MSFT** [comment]
@wiemkr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@wiemkr I hope you had a chance to look at my [above comment](https://github.com/Azure/azure-rest-api-specs/issues/21966#issuecomment-1362527650). Could you please let me know if you had any updates on this ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@wiemkr The action is currently pending on you to get back to us with an update on the above suggestion. Please feel free to reopen this issue once you are ready to resume troubleshooting on this. We would be happy to help.

**Comment by wiemkr** [comment]
I found the solution, I needed a body and to convert it to json: 

`$subscriptionId = ''`
`$uri = "https://management.azure.com/subscriptions/$subscriptionId/providers/Microsoft.CostManagement/query?api-version=2021-10-01"
$token = $(Get-AZAccessToken).Token
$securetoken = ConvertTo-SecureString $token -AsPlainText -Force`

`#Grouping by dimension, servicename`
`$body = @{`
`    type = 'Usage'`
`    timeframe = 'MonthToDate'`
`    dataset = @{`
`        granularity = 'Daily'`
`        aggregation = @{`
`            totalCost = @{`
`                name = 'PreTaxCost'`
`                function = 'Sum'`
`            }`
`        }`
`        grouping = @(`
`            @{`
`                type = 'Dimension'`
`                name = 'ServiceName'`
`            }`
`        )`
`      `  
`    }`
`}`

`$costresponse = Invoke-WebRequest -Uri $uri -Method Post -Authentication Bearer -Token $securetoken -Body ($body|ConvertTo-Json -Depth 5) -ContentType 'application/json'`
