### ISSUE TITLE
How to generate sdk from spec

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-rest-api-specs#22008]
I'm looking to generate the SDK for serialconsole. The [readme](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/serialconsole/resource-manager/readme.md) indicates that running `autorest readme.md` should generate all the SDKs but the output said `0 files generated`.

The following did work for me.
```
autorest --python --v3 ./readme.python.md  \
    --input-file=./Microsoft.SerialConsole/stable/2018-05-01/serialconsole.json \
    --input-file=./Microsoft.SerialConsole/stable/2018-05-01/serialport.json \
    --output-folder=generatedpy
```

However, this does not match the contents of the azure-sdk-for-python repo. My invocation combines the operations into a single file whereas azure-sdk-for-python splits them by serialconsole and serialport.

[azure-sdk-for-python/sdk/serialconsole/azure-mgmt-serialconsole/azure/mgmt/serialconsole/operations](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/serialconsole/azure-mgmt-serialconsole/azure/mgmt/serialconsole)
```
├── __init__.py
├── _microsoft_serial_console_client_operations.py
├── _patch.py
└── _serial_ports_operations.py
```
azure-rest-api-specs/specification/serialconsole/resource-manager/generatedpy/operations (mine)
```
├── __init__.py
├── _operations.py
└── _patch.py
```

Do you know how to invoke autorest to generate the output in the same way as azure-sdk-for-python?

**Comment by rguptar** [comment]
@keryul

**Comment by lfraleigh** [comment]
@ArthurMa1978 can you help with this?

**Comment by ArthurMa1978** [comment]
Hi @rguptar for Python sdk you can file a ticket on our [OpenAPI Hub](https://portal.azure-devex-tools.com/tools/request-api-release) and we will release the sdk for you
