### ISSUE TITLE
Azure resource visualizer API to generate SVG or PNG?

### ISSUE THREAD

**Issue by vikramdadwal** [Azure/azure-rest-api-specs#22097]
[Azure resource visualizer API to generate SVG or PNG?](https://stackoverflow.com/questions/74323884/azure-resource-visualizer-api-to-generate-svg-or-png)

**Comment by SaurabhSharma-MSFT** [comment]
@vikramdadwal We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@vikramdadwal Unfortunately, there is no such API and the diagram is generated client side based on relationships that is determine in the resource object. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@vikramdadwal We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
