### ISSUE TITLE
Unable to create vm from image in azure compute gallery

### ISSUE THREAD

**Issue by satyakrish** [Azure/azure-rest-api-specs#22133]
Created a custom centos image and published it to azure compute gallery
Offer: eurolinuxspzoo1620639373013
Publisher: centos-stream-8-0-free
Plan: centos-stream-8-0-free

1. While creating a vm using the above image from compute gallery via portal, vm creation fails stating plan information is required, whereas there is no option in the vm creat form to provide plan information

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMMarketplaceInvalidInput","message":"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: '/subscriptions/50ceaa60-b403-4964-8b62-e3a9f5ba9651/resourceGroups/otvm-testing/providers/Microsoft.Compute/virtualMachines/otvm-centos'."}]}
```

2. When i try to create a vm using the same sku from market place image, the vm creation is successful. 

This means when vm is created from market place image the plan infomration is somehow passed successfully. But when using a custom image (from compute gallery) creating using the same market place image the plan information is not getting passed from compute gallery while creating the vm. So there is some issue is passing plan information from compute image gallery to vm creation request.

**Comment by navba-MSFT** [comment]
@satyakrish Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@satyakrish A Marketplace image, or an image associated to a publisher, in Azure has the following attributes:

<html>
<body>


Term | Definition
-- | --
Publisher | The organization that created the image. Examples: Canonical, MicrosoftWindowsServer
Offer | Name of a group of related images created by a publisher. Examples: Ubuntu Server, WindowsServer
SKU | An instance of an offer, such as a major release of a distribution. Examples: 16.04-LTS, 2016-Datacenter
Version | The version number of an image SKU


</body>
</html>

To view an image's purchase plan information, run [Get-AzVMImage](https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvmimage?view=azps-9.3.0)(PS) or [*az vm image show *](https://learn.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-show)(CLI) to obtain the above properties.

**Example:**
```
$version = "2016.127.20170406"
Get-AzVMImage -Location $locName -Publisher $pubName -Offer $offerName -Skus $skuName -Version $version
```
Once the properties have been identified, validate your configuration for the deployment and compare the results. Add the plan information to your deployment.

**Example:**
PurchasePlan : {
     "publisher": "microsoft-ads",
     "name": "windows2016",
     "product": "windows-data-science-vm"

To learn more about deploying an image with Marketplace terms and plan information:

To understand how to configure Marketplace plan information correctly, [Windows](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage#view-plan-properties) and [Linux](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage#view-plan-properties)

Learn more about how to set Marketplace plan information [via the ARM API](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update#plan)

**Comment by navba-MSFT** [comment]
@satyakrish I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@satyakrish The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
