### ISSUE TITLE
Support `Bypass Next Hop IP for workloads within this VNet` in Virtual Hub vNet connection

### ISSUE THREAD

**Issue by mlcooper** [Azure/azure-rest-api-specs#22195]
I am unable to find API support for `Bypass Next Hop IP for workloads within this VNet` in Virtual Hub vNet connection`, but this is a setting I need to configure programmatically. Here is a picture of the setting:
![image](https://user-images.githubusercontent.com/9505606/212490712-7feb2bdd-8cfa-4061-869e-f8fe19008142.png)

Related to https://github.com/hashicorp/terraform-provider-azurerm/issues/19372

**Comment by navba-MSFT** [comment]
@mlcooper Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mlcooper 

> The setting: **Bypass Next Hop IP for workloads within this VNet**
> Ensures that the Next Hop IP is set up to direct traffic for destination prefixes. Enable "Yes" for VMs within this VNet to bypass "Next Hop IP" VM (**this can only be set on creation of the connection**). So you cannot update it after creation.

You can leverage this REST API:
https://learn.microsoft.com/en-us/rest/api/virtualwan/hub-virtual-network-connections/create-or-update?tabs=HTTP


You can use this parameter:
<html>
<body>


VnetLocalRouteOverrideCriteria | Parameter determining whether NVA in spoke vnet is bypassed for traffic with destination in spoke vnet.
-- | --

</body>
</html>
Sending you the sample if that helps:

PUT https://management.azure.com/subscriptions/XXXXXXXXX/resourceGroups/MyRGName/providers/Microsoft.Network/virtualHubs/New/hubVirtualNetworkConnections/MyTempName?api-version=2022-01-01 

Content-Length: 688
Authorization: Bearer eyJ0eXXXXXXXXXXXXX
Content-Type: application/json
Accept-Encoding: gzip, deflate, br

{"name":"temp123","properties":{"remoteVirtualNetwork":{"id":"/subscriptions/XXXXXXXXX/resourceGroups/MyRGName/providers/Microsoft.Network/virtualNetworks/navbatestvnet"},"enableInternetSecurity":true,"routingConfiguration":{"associatedRouteTable":{"id":"/subscriptions/XXXXXXXX/resourceGroups/MYRGName/providers/Microsoft.Network/virtualHubs/New/hubRouteTables/defaultRouteTable"},"propagatedRouteTables":{"ids":[],"labels":["default"]},"vnetRoutes":{"staticRoutes":[{"name":"testName","addressPrefixes":["10.0.0.1/10"],"nextHopIpAddress":"10.0.0.250"}],"staticRoutesConfig":**{"vnetLocalRouteOverrideCriteria":"Equal"}}}}}**

Hope this helps.

**Comment by mlcooper** [comment]
Hi @navba-MSFT, in the Azure Portal this setting is `yes` or `no`. In the API it seems the choices are `Equal` or `Contains`. Where can I find the definition of `Equal` and `Contains`? Which one is equivalent to `yes`?

**Comment by navba-MSFT** [comment]
@mlcooper Thanks for your reply.

<html>
<body>


VnetLocalRouteOverrideCriteria | Parameter determining whether NVA in spoke vnet is bypassed for traffic with destination in spoke vnet.
-- | --



</body>
</html>

`"vnetLocalRouteOverrideCriteria":"Contains"` ---> When the setting is NO.

`"vnetLocalRouteOverrideCriteria":"Equal"` ---> When the setting is YES.

Hope this helps.

**Comment by mlcooper** [comment]
Thank you; this is what I was looking for. I think the documentation should be improved to include
```
"vnetLocalRouteOverrideCriteria":"Contains" ---> When the setting is NO.

"vnetLocalRouteOverrideCriteria":"Equal" ---> When the setting is YES.
```

**Comment by navba-MSFT** [comment]
@mlcooper Thanks for the update and feedback. I will pass on this feedback to the Product Owners to get this info included in our documentation.
