### ISSUE TITLE
[BUG] Resources - Get By Id - GET https://management.azure.com/{resourceId}?api-version=2021-04-01 is not returning workspace

### ISSUE THREAD

**Issue by int292** [Azure/azure-rest-api-specs#22203]
### **Library name and version**

Azure REST Api: management.azure.com
Version: 2021-04-01

### **Describe the bug**

The GET REST API Resources - GetById call give a error on resourcetype OperationalInsights/workspaces

var resourceId = "/subscriptions/{subscription}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}"

response = await _httpClient.GetAsync($"https://management.azure.com{resourceId}?api-version=2021-04-01"); 

https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id

*Message*:     

{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'westeurope' and API version '2021-04-01' for type 'workspaces'. The supported api-versions are '2015-03-20, 2015-11-01-preview, 2017-01-01-preview, 2017-03-03-preview, 2017-03-15-preview, 2017-04-26-preview, 2020-03-01-preview, 2020-08-01, 2020-10-01, 2021-06-01, 2021-03-01-privatepreview, 2021-12-01-preview, 2022-10-01'. The supported locations are 'eastus, westeurope, southeastasia, australiasoutheast, westcentralus, japaneast, uksouth, centralindia, canadacentral, westus2, australiacentral, australiaeast, francecentral, koreacentral, northeurope, centralus, eastasia, eastus2, southcentralus, northcentralus, westus, ukwest, southafricanorth, brazilsouth, switzerlandnorth, switzerlandwest, germanywestcentral, australiacentral2, uaecentral, uaenorth, japanwest, brazilsoutheast, norwayeast, norwaywest, francesouth, southindia, koreasouth, jioindiacentral, jioindiawest, qatarcentral, canadaeast, westus3, swedencentral'."}}

*Exception type*:	

400 Bad Request

*Failed method*:	

Resources - Get By Id - GET https://management.azure.com/{resourceId}?api-version=2021-04-01
Resource Management
API Version:
2021-04-01

### **Expected behavior**

The call await _httpClient.GetAsync($"https://management.azure.com{resourceId}?api-version=2021-04-01") is returning the workspace resouretype

### **Actual behavior**

_httpClient.GetAsync($"https://management.azure.com{resourceId}?api-version=2021-04-01") gives 400 Bad Request

### **Reproduction Steps**

Calling this part of code:

```
var resourceId = "/subscriptions/{subscription}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}"

response = await _httpClient.GetAsync($"https://management.azure.com{resourceId}?api-version=2021-04-01"); .
```

### **Environment**

N/A

**Comment by navba-MSFT** [comment]
@int292 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@int292 While I invoked the [Get By ID Rest API](https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id), I was able to get the 200 success status code. Sending my Request URL here if that helps:

>https:// management.azure.com/subscriptions/XXXXX/resourceGroups/MYRGName/providers/Microsoft.OperationalInsights/workspaces/MyLAWorkspaceName?**api-version=2022-10-01**

So could you please change the API version to `2022-10-01` and try ?

Alternatively, you could also invoke the [Workspaces - Get](https://learn.microsoft.com/en-us/rest/api/loganalytics/workspaces/get?tabs=HTTP) REST API to get a workspace instance. Hope this helps.

**Comment by navba-MSFT** [comment]
@int292 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@int292 The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by snerte** [comment]
> @int292 While I invoked the [Get By ID Rest API](https://learn.microsoft.com/en-us/rest/api/resources/resources/get-by-id), I was able to get the 200 success status code. Sending my Request URL here if that helps:
> 
> > https:// management.azure.com/subscriptions/XXXXX/resourceGroups/MYRGName/providers/Microsoft.OperationalInsights/workspaces/MyLAWorkspaceName?**api-version=2022-10-01**
> 
> So could you please change the API version to `2022-10-01` and try ?

Yes this works, could you apply the fix in that version to the latest api version?

Also, using this api for these resources using `api-version=2022-10-01` results in an 'unsupported' error. Could you please fix getting all types of resources in the latest api version?

``` cs
     "Microsoft.OperationalInsights/workspaces",
            "Microsoft.Logic/workflows",
            "Microsoft.KeyVault/vaults",
            "Microsoft.Web/connections",
            "Microsoft.Logic/integrationAccounts",
            "MICROSOFT.WEB/connections"
```
