### ISSUE TITLE
When will the ARM API for postgres on cosmos be out of preview?

### ISSUE THREAD

**Issue by mastoj** [Azure/azure-rest-api-specs#22278]
According to this ticket, https://github.com/Azure/azure-rest-api-specs/issues/21179,  the ARM API for postgres on cosmos would most likely be out of preview by the end of 2022. That didn't happen, so what is the ETA on it being out of preview?

**Comment by navba-MSFT** [comment]
@mastoj Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mastoj The Rest API General Availability for Azure CosmosDB for PostgreSQL is in the latest stages of development. We expect to announce the GA in 2-8 weeks, depending on the review & announcement processes. Hope this helps.

**Comment by navba-MSFT** [comment]
@mastoj I hope you had a chance to look at my above comment. Please feel free to reopen this thread if you need any further assistance. We would be happy to help.
