### ISSUE TITLE
Regex for Postgres serverName doesn't match documentation in the portal

### ISSUE THREAD

**Issue by thomas11** [Azure/azure-rest-api-specs#22302]
Path: [`specification/postgresql/resource-manager/types/common-types.json#L16`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/types/common-types.json#L16)
RP: Microsoft.DBforPostgreSQL

The above file has a validation pattern for the `serverName` property: `^[a-z][a-z0-9]*$"`. This pattern does not match the documentation in the portal, which says
> Server name must be at least 3 characters and at most 63 characters.
> Server name must only contain lowercase letters, numbers, and hyphens. The server name must not start or end in a hyphen.
> Server name must be available.

The difference is that according to the docs, hyphens are allowed in the name.

**Comment by navba-MSFT** [comment]
@thomas11 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
