### ISSUE TITLE
Looking for deleteSubscription functionality

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-rest-api-specs#22307]
Hello,

I notice in the docs (and Github code) there is an option to cancel a subscription, and to delete the alias. However, I am missing the capability to actually delete a subscription.
I recognize that there is a grace-period before a subscription can be deleted, but i don't believe that is a reason to not provide the functionality to be able to delete subscriptions through the REST API?

For example, we now have automation that is going to create sandbox subscriptions, but also production subscriptions. What they are used for, we don't have to care about. When we need to cancel the subscriptions, and they stay there for 90 days, it means we have to create a (human) procedure to check if it got deleted successfully. I would much rather build something that does the check, and then uses the REST API to delete the subscription.

I have seen this: https://learn.microsoft.com/en-us/rest/api/subscription/2021-10-01/alias/delete?tabs=HTTP
But I have no need to only delete an alias. This doesn't allow me to provide any sort of body that instructs the API to delete a specific subscription.

**Comment by navba-MSFT** [comment]
@MMollyy Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please check and let me know if you have invoked the [Subscription Cancel REST API](https://learn.microsoft.com/en-us/rest/api/subscription/2021-10-01/subscription/cancel?tabs=HTTP) ? 

> After your subscription is canceled, Microsoft waits 30 - 90 days before permanently deleting your data in case you need to access it, or if you change your mind. We don't charge you for keeping the data. **90 days after you cancel a subscription, the subscription is automatically deleted.**

More Info [here](https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/cancel-azure-subscription#what-happens-after-subscription-cancellation). 

Hope this helps.

**Comment by MMollyy** [comment]
Hi @navba-MSFT thanks for the reply. I know about the cancel subscription functionality, as well as the 90-day grace period.

I have used it, but I still would like to delete subscriptions which I know I can delete immediatly.

**Comment by navba-MSFT** [comment]
@MMollyy It’s by design that azure subscription cannot be deleted directly, this is because blindly deleting subscription without proper lifecycle email notification and waiting time may cause livesites for customers who do not have enough time making sure all resources can be deleted. So the [above ](https://github.com/Azure/azure-rest-api-specs/issues/22307#issuecomment-1407953900) mentioned suggestion is the approach that should be taken.
