### ISSUE TITLE
Azure breaking changes policy is deprecated without a publicly accessible alternative

### ISSUE THREAD

**Issue by strefethen** [Azure/azure-rest-api-specs#22326]
A comment at the top of this guide suggests it is deprecated and refers to an internal MSFT URL.

https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Breaking%20changes%20guidelines.md

> <deprecated. For internal contributor, please refer to https://aka.ms/AzBreakingChangesPolicy for the topic>

Is there a publicly available replacement?

**Comment by navba-MSFT** [comment]
@strefethen 
Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
