### ISSUE TITLE
Update Site Source Control: Bitbucket GetRepository: (410) Gone.

### ISSUE THREAD

**Issue by laminingr** [Azure/azure-rest-api-specs#22333]
I am getting the below error when attempting to update the site source control:

Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: Bitbucket GetRepository: (410) Gone. 
at Microsoft.Web.Hosting.SourceControls.OAuthV1Provider

I am doing a Put Method to the following url:
https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Web/sites/{{appServiceName}}/sourcecontrols/web?api-version=2021-02-01

Using this payload:
{
  "properties": {
    "repoUrl": {{repoUrl}},
    "branch": "{{repoBranch}}",
    "isManualIntegration": false,
    "deploymentRollbackEnabled": false,
    "isMercurial": false
  }
}

I am authenticating via the BitBucket Api first and then I update the Service Principle’s BitBucket tokens before doing the above call, but I am not able to get this to work.

Using this endpoint to update the BitBucket Token:
https://management.azure.com/subscriptions/{{azSubscriptionId}}/providers/Microsoft.Web/sourceControls/BitBucket?api-version=2014-11-01

Payload:
{
  "properties": {
     "token": "{{bbTokenValue}}",
     "tokenSecret":"{{bbTokenSecret}}"
  }
}

**Comment by navba-MSFT** [comment]
@antcp @AzureAppServiceCLI  Adding Service team to look into this. Could you please look into this issue, once you get a chance ? Thanks in advance.

**Comment by arjunbaliga** [comment]
@AzureAppServiceCLI @antcp - Could you please share you insights

**Comment by laminingr** [comment]
Got it working through the Azure Resource Manager .Net SDK using my Identity via Visual Studio.
