### ISSUE TITLE
`Microsoft.CognitiveServices` value cannot be null

### ISSUE THREAD

**Issue by mclacore** [Azure/azure-rest-api-specs#22395]
Using Azure's REST API documentation about listing the available SKUs for Azure Cognitive Services is broken, both from the `Try it!` mode and external source like Postman. I get the error:

```JSON
{
    "error": {
        "code": "BadRequest",
        "message": "Value cannot be null. (Parameter 'requestObject.Skus')"
    }
}
```

**Steps to reproduce**
1. This is where I'm running the request from: https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/check-sku-availability/check-sku-availability?tabs=HTTP
2. I set the `location` to `eastus` or `westus` or any region, really.

**Comment by navba-MSFT** [comment]
@mclacore Thanks for reaching out to us and reporting this issue. I was able to invoke [this API ](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/check-sku-availability/check-sku-availability?tabs=HTTP#code-try-0)and got a successful response. See below:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/57353862/216293198-44d1abfa-4e63-412b-b3a5-e22fb34b0028.png">

Sending you my Request Body if that helps.
```
{
      "kind": "Face",
      "type": "Microsoft.CognitiveServices/accounts",
      "skus": [
       "S0"
      ]
}
```

**Comment by mclacore** [comment]
I'm still seeing the same issue, but I no longer need this API endpoint, so I'm going to close this issue. Thanks.
