### ISSUE TITLE
[Maps - Proxy] API Review

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-rest-api-specs#22411]

**Comment by koyasu221b** [comment]
Service Name: Azure Maps Proxy API
Review Created By: huangwill Will Huang
Review Date:
PR:

**Comment by weidongxu-microsoft** [comment]
@koyasu221b
Ping me when you have the PR ready.

**Comment by koyasu221b** [comment]
@weidongxu-microsoft Got it.

**Comment by mikekistler** [comment]
@koyasu221b @weidongxu-microsoft Reminder to update this issue with a link to the PR.
