### ISSUE TITLE
Network security group rules require a priority

### ISSUE THREAD

**Issue by thomas11** [Azure/azure-rest-api-specs#22448]
In Microsoft.Network, the [definition of SecurityRule does not list the `priority` property as required](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/networkSecurityGroup.json#L820), but the Azure portal does and it seems to be actually required.

**Comment by navba-MSFT** [comment]
@thomas11 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@thomas11 I am sharing the 2 examples here for the NSG creation:

1. [Create network security group **without** custom Security rule](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/create-or-update?tabs=HTTP#create-network-security-group)

2. [Create network security group **with custom SecurityRule and priority**](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/create-or-update?tabs=HTTP#create-network-security-group-with-rule)

The latter, makes use of:
 <html>
<body>


properties.securityRules | [SecurityRule](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/create-or-update?tabs=HTTP#securityrule)[] | A collection of security rules of the network security group.
-- | -- | --

Please let me know if this helps.

**Comment by thomas11** [comment]
Hi @navba-MSFT, your reply unfortunately does not address my issue. You give one example without security rules, and one with security rules _with priorities_. But my question is about rules _without_ priorities. I don't think that's allowed but according to the schema it is because the `priority` property is not marked as required. That should be fixed.

**Comment by navba-MSFT** [comment]
@thomas11 Thanks for clarifying. I tried to create a NSG security rule without the priorities and it failed as expected. So that means that the priority is a _required_ field. [ This is the API](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/create-or-update?tabs=HTTP#code-try-0) I invoked:

Sending you my Request body ( **without** the _priority_ field):

```
{
  "properties": {
    "securityRules": [
      {
        "name": "rule1",
        "properties": {
          "protocol": "*",
          "sourceAddressPrefix": "*",
          "destinationAddressPrefix": "*",
          "access": "Allow",
          "destinationPortRange": "80",
          "sourcePortRange": "*",
          "direction": "Inbound"
        }
      }
    ]
  },
  "location": "eastus"
}
```
As expected, it failed with 400 Bad Request error with below expected error message:

```
{
  "error": {
    "code": "SecurityRuleInvalidPriority",
    "message": "Security rule has invalid Priority. Value provided: 0 Allowed range 100-4096.",
    "details": []
  }
}
```

**Comment by thomas11** [comment]
Hi @navba-MSFT, thank you for reproducing. This is what I expected. Therefore, the priority should be marked as "required" in the API spec as I pointed out above. Unfortunately, I pasted a wrong link initially, apologies. This is now fixed. To reiterate, I think `priority` needs to be added [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/networkSecurityGroup.json#L820).

**Comment by navba-MSFT** [comment]
@thomas11 It seems like we have a check implemented at the service side for the `priority `field and if its missing the below error is being thrown. So irrespective of making it required or not, the check is happening. 

```
{
  "error": {
    "code": "SecurityRuleInvalidPriority",
    "message": "Security rule has invalid Priority. Value provided: 0 Allowed range 100-4096.",
    "details": []
  }
}
```

**Comment by thomas11** [comment]
Hi @navba-MSFT, I know the check is happening. But this is an issue on the azure-rest-api-specs repository, and it is about the specs, not the service. The field should be marked as required in the spec to match the reality of the service.

**Comment by navba-MSFT** [comment]
@thomas11 Thanks for your reply. I have created the above PR and it is currently under review.
