### ISSUE TITLE
[Consumption Api] - tiny typo in description for "Usage - Details List" endpoint

### ISSUE THREAD

**Issue by mikeclayton** [Azure/azure-rest-api-specs#22446]
Hello. I hope this is the right place to report documentation errors - please let me know if they should go somewhere else...

In the [Usage Details - List](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP#uri-parameters) documentation for the Consumption Api the "scope" parameter contains the following (reformatted for ease of reading):

> Also, Modern Commerce Account scopes are:
>
>   * '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}' for billingAccount scope,
>   * '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}' for billingProfile scope,
>   * 'providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}/invoiceSections/{invoiceSectionId}' for invoiceSection scope, and
>   * 'providers/Microsoft.Billing/billingAccounts/{billingAccountId}/customers/{customerId}' specific for partners.

Here's a screenshot as well for completeness:

![image](https://user-images.githubusercontent.com/1193763/216589292-c0adce1e-6933-44e1-a45c-a83a4c95f337.png)

The uri templates in the last two patterns *don't" start with a forward slash, but presumably *should*? I've not been able to test if the leading forward slash is necessary since I don't have access to an appropriate billing account.

Here's an example of where where ```'providers/``` appears:

https://github.com/Azure/azure-rest-api-specs/blob/8c9a6bd96daf9e0e7f4bba47df78dfa0a23acf07/specification/consumption/resource-manager/Microsoft.Consumption/stable/2021-10-01/consumption.json#L5571

but there's a fair number of other locations as well if you just ```findstr``` / ```grep``` the entire codebase.

I'm happy to send a PR if you accept them?

**Comment by navba-MSFT** [comment]
@mikeclayton Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
