### ISSUE TITLE
[Compute VMSS] Newly created VMSS with ephemeral OS disk has outdated VM models

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-rest-api-specs#22552]
Hi team, as the title suggests, the VMs that are created along with the VMSS are outdated:
![Screen Shot 2023-02-10 at 5 48 09 PM](https://user-images.githubusercontent.com/92354331/218060245-3d1af0d2-f8e8-4797-a671-73965f084132.png)

However, when we do further scale-ups, new VMs are fine, not outdated:
![Screen Shot 2023-02-10 at 5 51 47 PM](https://user-images.githubusercontent.com/92354331/218060460-945806b9-b7c1-4913-94bd-b986b5e2e9b3.png)

The original VM has to be manually upgraded (VMSS has upgrade policy of MANUAL).

I wonder if this is a bug?

**Comment by hilaryw29** [comment]
Looking into this issue

**Comment by XiaofeiCao** [comment]
Thanks @hilaryw29 . 

We also noticed that when we scale up ephemeral uniform VMSS using API, any properties present under `virtualMachineProfile.storageProfile.osDisk` (even though nothing is changed) will lead to outdated VM models as well. 

Not sure if it's related to this issue.

**Comment by hilaryw29** [comment]
Hi @XiaofeiCao,

It seems like there was an extension added by policy after the VMSS was created. No manual upgrade was performed on the first VM, so the VM showed an outdated model. New scale outs after the extension was added had the latest model, which is expected behaviour. Let me know if this helps, thanks.

**Comment by XiaofeiCao** [comment]
Hi @hilaryw29 

We did experience the delay of the outdated model after the VMSS was created. Since we know the root cause of the issue, I guess that's not a big deal in our case. 

Thanks, it helps!
