### ISSUE TITLE
API Calls for Azure Monitor Diagnostic settings enablement

### ISSUE THREAD

**Issue by levgoronshteyn** [Azure/azure-rest-api-specs#22556]
Hi Team,

I would like to see if there is a list of API calls i can make for any resource that supports Azure Monitor Diagnostic settings? The reason for the ask is to be able to build out a Terraform module that will be able to enable diagnostic settings on any or all supported resources in Azure without needing to figure out the right format of how to enable the settings.

**Comment by navba-MSFT** [comment]
@levgoronshteyn Thanks for reaching out to us and reporting this issue. This is the REST API that can be invoked for creating or updating the diagnostic settings for the specified resource:

https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP
