### ISSUE TITLE
Using azure PUT API to Create Network interface but its show ""message": "The resource definition is invalid." " .

### ISSUE THREAD

**Issue by dsingh1706** [Azure/azure-rest-api-specs#22603]
How do I can use azure API to Create nics (Network interface)  and update nics.

Error: `{
    "error": {
        "code": "InvalidResource",
        "message": "The resource definition is invalid."
    }
}`

Code :
`import adal
import requests
import os
import json

tenant = 'id'
authority_url = 'https://login.microsoftonline.com/tenant'
#client_id = 'id'
client_id = 'id'
client_secret ='id'

resource = 'https://management.azure.com/'

context = adal.AuthenticationContext(authority_url)
token = context.acquire_token_with_client_credentials(resource, client_id, client_secret)

print("Diksha..............#####TOKEN is ")
print(token)

headers = {'Authorization': 'Bearer ' + token['accessToken'], 'Content-Type': 'application/json'}
#headers = {'Authorization': 'Bearer ' + token['accessToken']}
print("Diksha headers..........",headers)
params = {'location': 'rg-east-01',
              'ip_configurations': [
                 {
                    'name': 'ipconfig1',
                    'subnet':'subnet-18',
                    # None: Disassociate;
                    'public_ip_address': None,
                 }
              ]
              }
url='https://management.azure.com/subscriptions/suid/resourceGroups/rg-east-01/providers/Microsoft.Network/networkInterfaces/test-nic?api-version=2020-01-01'
print("diksha....URL:",url)

r = requests.put(url, headers=headers,params=params)

print(json.dumps(r.json(), indent=4, separators=(',', ': ')))
`

**Comment by navba-MSFT** [comment]
@dsingh1706 Thanks for reaching out to us and reporting this issue. This error message usually occurs when the JSON payload in the PUT request is not formatted correctly or is missing required parameters. Since your requirement is to Create (PUT) an Azure Network Interface then you can invoke **[this REST API](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?tabs=HTTP)**.

Refer the sample request headers and request body [**here**](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?tabs=HTTP#create-network-interface). 

More Info [**here**](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/virtual-network/virtual-network-network-interface.md#powershell).

**Comment by navba-MSFT** [comment]
@dsingh1706 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by dsingh1706** [comment]
@navba-MSFT thanks for answering. But I want abb one secondary IP to one NIC. Can you share any PUT examples?

**Comment by navba-MSFT** [comment]
@dsingh1706 You can leverage the below sample Put Request Body:

```
{
  "properties": {
    "enableAcceleratedNetworking": true,
    "disableTcpStateTracking": true,
    "ipConfigurations": [
      {
        "name": "ipconfig1",
        "properties": {
          "publicIPAddress": {
            "id": "/subscriptions/subID/resourcegroups/RGName/providers/Microsoft.Network/publicIPAddresses/testip1"
          },
          "primary": true,
          "subnet": {
            "id": "/subscriptions/bsubID/resourceGroups/RGName/providers/Microsoft.Network/virtualNetworks/virtualNetwork1/subnets/subnet1"
          }
        }
      },
      {
        "name": "ipconfig2",
        "properties": {
          "publicIPAddress": {
            "id": "/subscriptions/subID/resourcegroups/RGName/providers/Microsoft.Network/publicIPAddresses/testip2"
          },
          "subnet": {
            "id": "/subscriptions/subID/resourceGroups/RGName/providers/Microsoft.Network/virtualNetworks/virtualNetwork1/subnets/subnet1"
          }
        }
      }
    ]
  },
  "location": "eastus"
}
```

**Comment by dsingh1706** [comment]
Thanks :) @navba-MSFT :)
