### ISSUE TITLE
[azurerm v3.31.0] error while creating APIM using Terraform

### ISSUE THREAD

**Issue by samiko-nd** [Azure/azure-rest-api-specs#22632]
I am having an issue while creating APIM via terraform, using azurerm v3.31.0. 
After 33m30s I get the error message - waiting for recovery of "Api Management" pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0.

Hashicorp have confirmed it's a problem with Azure API (https://github.com/hashicorp/terraform-provider-azurerm/issues/8579)

**Comment by navba-MSFT** [comment]
@samiko-nd Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please share the subscription-id, correlation-id and the time of the issue in UTC ?

**Comment by navba-MSFT** [comment]
@samiko-nd I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please share the subscription-id, correlation-id and the time of the issue in UTC over email navba [ @ ] microsoft . (dot) com. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@samiko-nd The action is currently pending on you to share the above requested details. Once you are ready to resume troubleshooting on this, please feel free to reopen this thread. We would be happy to help.
