### ISSUE TITLE
Management Groups diagnosticSettings 500 internalservererror on PUT

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-rest-api-specs#22647]
## Description

I'm trying to send Management Group activity logs to a Log Analytics Workspace, following this info:

* https://learn.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/create-or-update?tabs=HTTP
* https://learn.microsoft.com/en-us/rest/api/monitor/management-group-diagnostic-settings/create-or-update?tabs=HTTP
* https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/common-deployment-errors
* https://sameeraman.github.io/blog/2021/06/20/mgauditlogs/

I get StatusCode 500 "InternalServerError", returned header `x-ms-failure-cause` says `service`.
Happens both when using Az PowerShell module like so:

```powershell
Invoke-AzRestMethod -Method 'PUT' -Path (
    'providers/microsoft.management/managementGroups/{0}/providers/microsoft.insights/diagnosticSettings/{1}?api-version=2020-01-01-preview' -f
        $Mg.'Name',
        $Log.'Name'
) -Payload $Body
```

And API endpoint directly like so:

```powershell
$Headers = [ordered]@{
    'Authorization' = [string] 'Bearer {0}' -f (Get-AzAccessToken -ResourceTypeName 'Arm').'Token'
}
Invoke-RestMethod -Method 'Put' -Headers $Headers -Body $Body -ContentType 'application/json' -Uri (
    'https://management.azure.com/providers/microsoft.management/managementGroups/{0}/providers/microsoft.insights/diagnosticSettings/{1}?api-version=2020-01-01-preview' -f
        $Mg.'Name',
        $Log.'Name'
)
```

With a body / payload like so:

```powershell
$Body = [string](
    [ordered]@{
        'properties' = [ordered]@{
            'workspaceId' = [string] $Log.'ResourceId'
        }
        'logs' = [array](
            [ordered]@{
                'category' = [string] 'Administrative'
                'enabled'  = [bool] $true
            },
            [ordered]@{
                'category' = [string] 'Policy'
                'enabled'  = [bool] $true
            }
        )
    } | ConvertTo-Json -Compress -Depth 3
)
```

## Reproduce

* PIM / add RBAC "Log Analytics Contributor" on both the Management Group in question, and the target Log Analytics Workspace.
* Authenticate with PowerShell.
* Find Log Analytics Workspace full resource ID, and Management Group name/id, either in the Azure portal, or with Az PowerShell.
* Get info on them (so above code works) like so:
  * `$Mg = Get-AzManagementGroup -GroupId '<management_group_name>' -WarningAction 'SilentlyContinue'`
  * `$Log = Get-AzResource -ExpandProperties -ResourceId '<log_analytics_full_resource_id>'`
* Run above code.

## What I've tried for troubleshooting

* Refresh auth/credentials.
  * `Clear-AzContext -Force`
  * `Connect-AzAccount`
* Force TLS 1.2 only.
  * `[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12`

## Questions

1. Response and [doc on deployment errors](https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/common-deployment-errors) points to a backend issue, rather than me goofing. Any known errors with mentioned endpoint?
2. Any obvious goofs in above logic / PowerShell? It should work according to the linked [API endpoint doc](https://learn.microsoft.com/en-us/rest/api/monitor/management-group-diagnostic-settings/create-or-update?tabs=HTTP) and [blog post](https://sameeraman.github.io/blog/2021/06/20/mgauditlogs/) as far as I can see.
3. Can "InternalServerError" / 500 also mean that I've done something wrong? If yes, [this doc](https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/common-deployment-errors) should be updated to reflect it.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by o-l-a-v** [comment]
I just found out that this was caused of me goofing with the `$Body`, by not putting `logs` inside `properties`.

Was:

```powershell
$Body = [string](
    [ordered]@{
        'location' = [string] 'global'
        'properties' = [ordered]@{
            'workspaceId' = [string] $Log.'ResourceId'               
        }
        'logs' = [array](
            [ordered]@{
                'category' = [string] 'Administrative'
                'enabled'  = [bool] $true
            },
            [ordered]@{
                'category' = [string] 'Policy'
                'enabled'  = [bool] $true
            }
        )
    } | ConvertTo-Json -Depth 3 -Compress
)
```

Became:

```powershell
$Body = [string](
    [ordered]@{
        'properties' = [ordered]@{
            'workspaceId' = [string] $Log.'ResourceId'
            'logs' = [array](
                [ordered]@{
                    'category' = [string] 'Administrative'
                    'enabled'  = [bool] $true
                },
                [ordered]@{
                    'category' = [string] 'Policy'
                    'enabled'  = [bool] $true
                }
            )   
        }
    } | ConvertTo-Json -Depth 3 -Compress
)
```

And now it works. :)
