### ISSUE TITLE
Validate all SDKs as part of CI

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#2270]
Some languages are more lax than others so sometimes swagger errors that don't cause compile-time errors in node/python/ruby will cause compile-time errors in others (e.g. Go).  For an example see this PR https://github.com/Azure/azure-rest-api-specs/pull/2095.  The missing nextLink field causes a compile time error for Go rendering the package for this API version unusable.  I believe this is problematic for other SDKs but given the nature of the languages this issue won't surface until runtime.

**Comment by yungezz** [comment]
all SDK generation is in CI pipeline already. close this one.
