### ISSUE TITLE
`sqlvirtualmachine` - enum in `AgReplica` Is In Wrong Case

### ISSUE THREAD

**Issue by myc2h6o** [Azure/azure-rest-api-specs#22768]
The casing seems not correct in Swagger compared to Service.

e.g.: After setting `SYNCHRONOUS_COMMIT` as swagger said, the value returned by Get response is `Synchronous_Commit`
Similar issue happens for other properties in `AgReplica`

Ref: https://github.com/Azure/azure-rest-api-specs/blob/8468620c009664ed91a3148c04cf77b6c8eb7b6f/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/stable/2022-02-01/sqlvm.json#L1115-L1128

**Comment by navba-MSFT** [comment]
@myc2h6o Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by myc2h6o** [comment]
Hi @navba-MSFT thanks for the quick fix! the `readableSecondary` property has the similar issue as well during my test. It is set to `All` at service side instead of `ALL` from swagger
