### ISSUE TITLE
Service Fabric docs for clusterCodeVersion link to nonexistent file

### ISSUE THREAD

**Issue by thomas11** [Azure/azure-rest-api-specs#22806]
In several API versions of Service Fabric, the property `Cluster.clusterCodeVersion` is documented as

> "description": "The Service Fabric runtime version of the cluster. This property can only by set the user when **upgradeMode** is set to 'Manual'. To get list of available Service Fabric versions for new clusters use [ClusterVersion API](./ClusterVersion.md). [...]"

The link goes to `./ClusterVersion.md` which does not exist. This actually causes dead links in the official MS documentation, e.g. [here](https://learn.microsoft.com/en-us/rest/api/servicefabric/clusters/list?tabs=HTTP#cluster).

The following versions are affected:

```
$ rg -Fl '[ClusterVersion API](./ClusterVersion.md)' azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/

azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2019-03-01-preview/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2020-01-01-preview/managedcluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2019-06-01-preview/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2020-12-01-preview/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2017-07-01-preview/servicefabric.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2019-11-01-preview/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2021-06-01/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2018-02-01/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2020-03-01/cluster.json
azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2019-03-01/cluster.json
```

**Comment by navba-MSFT** [comment]
@thomas11 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by thomas11** [comment]
Hi @lirenhe, @navba-MSFT, thank you for fixing this issue. Unfortunately, the fix in the linked PR was only made for one API version, while there are several. Can we please fix this for all versions?
