### ISSUE TITLE
Synapse RoleAssignments through ResourceManager

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#22838]
We're looking to support RoleAssignments when using Synapse Private Endpoints. Unfortunately, Role Assignments are only supported through the DataPlane API which appears to only be accessible publicly. Is it possible to have the ResourceManager API support roleAssignments.

DataPlane API for reference: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/synapse/data-plane/Microsoft.Synapse/preview/2020-08-01-preview/roleAssignments.json

**Comment by navba-MSFT** [comment]
@mbfrahry Synapse RBAC extends the capabilities of [Azure RBAC](https://learn.microsoft.com/en-us/azure/role-based-access-control/overview) for Synapse workspaces and their content. 

[Role Assignments - Create REST API ](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?tabs=HTTP)helps to Create or update a role assignment by scope and name.

I have a few questions to get some clarity on your ask:

1. Are you referring to[ This API ](https://learn.microsoft.com/en-us/rest/api/synapse/data-plane/role-assignments/create-role-assignment?tabs=HTTP)? 
2. Do you want the above API functionality which is called via (https://myworkspace.dev.azuresynapse.net/ endpoint) to be implemented via the ARM REST API  ?
3. Could you please elaborate on your use case and about this requirement ?

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mbfrahry I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mbfrahry** [comment]
Hey @navba-MSFT,

We're looking to manage a Synapse Cluster when it is configured with a Private Endpoint, it's not possible to access the Data Plane API - as such it's not possible to create Role Assignments (which has to be done via the Data Plane API).

As such this issue is requesting that it's possible to create Role Assignments within Azure Synapse via the Resource Manager API's (which is *not* related to the Role Assignments API).

Hope that helps.

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for clarifying. I had a discussion with the Product Owners regarding this ask. 

Synapse RBAC role assignment creation with ARM is not supported at present. There is no ETA for this feature.

**Comment by katbyte** [comment]
@navba-MSFT - as this is still a valid request can it please be reopend and remain open until a solution exists?
