### ISSUE TITLE
DBforPostgreSQL DataEncryption type inconsistency

### ISSUE THREAD

**Issue by jbrezina** [Azure/azure-rest-api-specs#22851]
[DataEncryption type](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FlexibleServers.json#L777) has 2 values in the specs at the moment - SystemAssigned and AzureKeyVault.
When I use _SystemAssigned_, I get an error in return that it is an invalid value. The value I get from Azure Cloud by default is _SystemManaged_.

**Comment by navba-MSFT** [comment]
@jbrezina Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
