### ISSUE TITLE
The virtual cluster still exists after the Azure SQL Managed Instance management and subnet are fully removed

### ISSUE THREAD

**Issue by sinbai** [Azure/azure-rest-api-specs#22870]
Per  the following details in this [doc](https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql#duration)  (in our case , there is only one SQL Managed instance and one virtual clusters in one subnet), my understanding is that if the SQL  instance and subnet have been fully deleted, it means that the virtual cluster has also been fully removed, correct? If yes, in the automated test,  we encountered a situation where the instance and subnet were deleted but the virtual cluster still existed (90% repro rate) issue. Is that means the response is not waiting long enough for the virtual cluster to be removed? Looking forward to this issue being investigated and resolved quickly, thanks in advance.

![image](https://user-images.githubusercontent.com/39109137/222348885-dfc6ba46-db0e-40e4-a3b6-8335b5c92f74.png)

**Comment by navba-MSFT** [comment]
@sinbai I had a discussion with the Product owners and they are requesting a Support ticket to be created with Microsoft Support to look into this further. Please open the support ticket and share the support ticket # here.

**Comment by navba-MSFT** [comment]
@sinbai I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know the support ticket # once you create it.. Awaiting your reply.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your assistance. I would create a ticket  when I am done with the high priority work at hand. And I would let you know once the ticket is created.

**Comment by navba-MSFT** [comment]
@sinbai Thanks for the update.

**Comment by navba-MSFT** [comment]
@sinbai I wanted to do quick follow-up to check if you had a chance to create the support ticket for this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sinbai The action is pending on you to create a support ticket. Please update the support ticket # in this thread once you get a chance. Our Microsoft support professional will reach out to you and troubleshoot this issue further.

**Comment by sinbai** [comment]
@navba-MSFT thanks for following up on this issue. After further automated testing, I found out this is a [resource.list-by-resource-group API ](https://learn.microsoft.com/en-us/rest/api/resources/resources/list-by-resource-group) issue. The reason our test cases are failing is that the resourceClient.ListByResourceGroup API returns that virtualCluster still exists (does not actually exist). So I think the support ticket is unnecessary, thank you very much for your assistance.
