### ISSUE TITLE
Storage Accounts - Create API does not return body as explained in documentation

### ISSUE THREAD

**Issue by kaganmersin** [Azure/azure-rest-api-specs#22897]
Hello Team,

When I try to create Storage Account with Postman while following below documentation, Azure respond with empty body 
Documentation: https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create?tabs=HTTP#storageaccount
![image](https://user-images.githubusercontent.com/46555755/222709405-ea503d0e-3afc-4717-8571-ca08f22dec90.png)

But I see storage account were created successful. If I execute post request again I will get the proper body, but not with the first time I try
![image](https://user-images.githubusercontent.com/46555755/222709662-5f30bece-1bd6-4118-8287-31494411e8ea.png)

**Comment by blueww** [comment]
@kaganmersin 

Create Storage Account API is a long running API (see [swagger](https://github.com/Azure/azure-rest-api-specs/blob/66174681c09b101de03fd35399080cfbccc93e8f/specification/storage/resource-manager/Microsoft.Storage/stable/2022-09-01/storage.json#L200) ). 
So it has 2 return code: 200 and 202. 
In the [doc](https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create?tabs=HTTP#response), you can see : When it return 202, means `Accepted -- Create or update request accepted; operation will complete asynchronously.` So the create operation is still not finished, and can't return the account properties to you. 
In this case, there should be a header "Location" in the 202 responds, which is an asyncoperations link. You should Get this link repeatedly (with intervel as "Rety-After" header in second), until it return 200 which mean the operation is finished, and you will see the account properties in the final 200 responds body.

**Comment by navba-MSFT** [comment]
@kaganmersin I hope you had a chance to look at the above comment. Please let us know if you have any follow-up queries.

**Comment by navba-MSFT** [comment]
@kaganmersin I wanted to do quick follow-up to check if you had a chance to look at the above comment. Please let us know if you had any updates on this. Awaiting your reply.
