### ISSUE TITLE
MaintenanceAssignment.List API shouldn't always return lowercase for the name of Maintenance Configuration

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#22894]
After tested, I found [MaintenanceAssignment.List](https://learn.microsoft.com/en-us/rest/api/maintenance/configuration-assignments/list?tabs=HTTP) API always returns lowercase for the name of Maintenance Configuration ("acctest-mc") like below this.
```
/subscriptions/xx-xx-xxx-xx/resourceGroups/acctestRG-maint/providers/Microsoft.Compute/virtualMachines/acctestVM/providers/Microsoft.Maintenance/configurationAssignments/acctest-mc
```

Actually, List API should return "acctest-MC" like below this.
```
/subscriptions/xx-xx-xxx-xx/resourceGroups/acctestRG-maint/providers/Microsoft.Compute/virtualMachines/acctestVM/providers/Microsoft.Maintenance/configurationAssignments/acctest-MC
```

So could you take a look this issue? Thanks.

**Comment by Drewm3** [comment]
Hi @neil-yechenwei, I have marked this as a feature request because I know from similar questions on the VM list API that we do not consider it a bug if case is not maintained. However, I know it is a preference for customers to have the case maintained for any resource name or other custom string that the customer provides.

**Comment by maulikshah23** [comment]
@kamalbh , could you please review this?

**Comment by ApnaLakshay** [comment]
Adding this item as a backlog to be taken up in the Selenium Semester.

**Comment by TravisCragg-MSFT** [comment]
This will not be taken up for the current planning period and will be re-assessed in early 2025.

**Comment by TravisCragg-MSFT** [comment]
This has been added to our backlog, and will be fixed at some point in the next year.
