### ISSUE TITLE
DNSZones.ListComplete API doesn't return any value

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#22921]
Hi team,
Recently we found DNSZones.ListComplete API doesn't return any value. Seems it's a regression issue. So could you take a look? Thanks.

Request payload:
```
GET https://management.azure.com/subscriptions/xx-xx-xx-xx/providers/Microsoft.Network/dnsZones
```

API response:
```
nil/null
```

**Comment by tombuildsstuff** [comment]
@neil-yechenwei FYI this isn't an API issue - see [this issue on `hashicorp/go-azure-sdk`](https://github.com/hashicorp/go-azure-sdk/issues/356) for more information - as such this issue can be closed in favour of the issue on `hashicorp/go-azure-sdk`

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , thanks for reminder.
