### ISSUE TITLE
API Policy Assignments - List For Management Group not working

### ISSUE THREAD

**Issue by MartinBouchery** [Azure/azure-rest-api-specs#22997]
Hello,

This API call as stated in the example does not work. [Policy Assignments - List For Management Group](https://learn.microsoft.com/en-us/rest/api/policy/policy-assignments/list-for-management-group?tabs=HTTP#examples)

It seems it says the api-version parameter is missing. Without the filter, you get a missing filter error. I also tried to revert the api-version and filter parameters without success.

`GET https://management.azure.com/providers/Microsoft.Management/managementGroups/TestManagementGroup/providers/Microsoft.Authorization/policyAssignments?$filter=atScope()&api-version=2022-06-01`

**Comment by navba-MSFT** [comment]
@MartinBouchery Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@MartinBouchery Could you please share the error message that you are receiving while invoking the above REST API ?

**Comment by navba-MSFT** [comment]
@MartinBouchery I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@MartinBouchery The action is currently pending on you to try the above suggestion and get back to us. Please feel free to reopen this thread. We would be happy to help.
