### ISSUE TITLE
Update documentation for CosmosDB Postgres API

### ISSUE THREAD

**Issue by mclacore** [Azure/azure-rest-api-specs#23079]
Hi,

I noticed that CosmosDB Postgres API documentation hasn't been added yet. Will that be added soon?

**Comment by navba-MSFT** [comment]
@mclacore Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mclacore The API specs are published a few days ago: See [here](https://learn.microsoft.com/en-us/rest/api/postgresqlhsc/).

**Comment by navba-MSFT** [comment]
@mclacore I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mclacore** [comment]
Yes, thanks. We can close.

**Comment by navba-MSFT** [comment]
@mclacore Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
