### ISSUE TITLE
App Service Public Certificate - Eventual Consistency Issue

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#23138]
I've been working with [Web 2021-03-01 API](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01) and am seeing issues where the App Service Public Certificate returns a 404 for a random amount of time. Sometimes it'll return the resource immediately and others it'll take 10+ minutes. 

This is the [command](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01) we're attempting to use. 

The certificate also appears in the portal immediately after creation and it seems to be immediately available through the [list command](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-03-01/WebApps.json#L7861)

Is there something happening behind the scenes that prevents the Certificate from being returned through the Get call despite it being available through other means?

**Comment by navba-MSFT** [comment]
@mbfrahry Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Since the certificates are loaded fine most of the time and fails intermittently with 404 and takes longer time to load, this would require a closer troubleshooting. Could you please let us know the feasibility of opening a support ticket to look into this further ?

**Comment by navba-MSFT** [comment]
@mbfrahry I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mbfrahry As mentioned above, Please open a support ticket with Microsoft so that our support professionals can troubleshoot this issue closely and identify the root cause. If you have any concerns or queries, please feel free to reopen this thread and we would be happy to help.
