### ISSUE TITLE
Auto create branches and commit for approved PRs in the private repo

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#2314]
In stand-up @fearthecowboy had a great suggestion that when a PR in the private repo has been approved, instead of letting it linger in an open state we should automatically create a branch for that PR, rebase it, then commit.  This would ensure that the PR is preserved and avoid the risk of losing PRs due to user error (e.g. deleting the source branch/fork would cause the PR to be lost).

**Comment by fearthecowboy** [comment]
// cc @salameer 

This would have the distinct benefit of also being able to 'close' a PR in private, since it would be merged into the target branch.

**Comment by marstr** [comment]
Closing as stale, for what it's worth I've been doing this manually for my private repository reviews.
