### ISSUE TITLE
Resource type 'Microsoft.DBforPostgreSQL/flexibleServers' does not support creation of 'SystemAssigned' resource identity

### ISSUE THREAD

**Issue by sinbai** [Azure/azure-rest-api-specs#23176]
Per[ the latest API](https://github.com/Azure/azure-rest-api-specs/blob/ce64ee97437c0af59515e38bc86b45ffedfb1334/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FlexibleServers.json#L816), the flexibleServers should support creation of 'SystemAssigned' , but it doesn't . See the below for details:

Request:
PUT /subscriptions/?/resourceGroups/acctestRG-postgresql-230320155838217513/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-230320155838217513?api-version=2022-12-01 

`{"identity":{"type":"SystemAssigned"},"location":"eastus","properties":{"administratorLogin":"adminTerraform","administratorLoginPassword":"QAZwsx123","availabilityZone":"2","backup":{"geoRedundantBackup":"Disabled"},"highAvailability":{"mode":"Disabled"},"network":{},"storage":{"storageSizeGB":32},"version":"12"},"sku":{"name":"Standard_D2s_v3","tier":"GeneralPurpose"},"tags":{}}`

Response:

```
{"error":{"code":"CannotSetResourceIdentity","message":"Resource type 'Microsoft.DBforPostgreSQL/flexibleServers' does not support creation of 'SystemAssigned' resource identity. 
The supported types are 'UserAssigned'."}}
```

**Comment by navba-MSFT** [comment]
@sinbai Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sinbai As per [our documentation ](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-with-managed-identity) PostgreSQL flexibleServers should support both System and User Managed identities.

Could you please follow this article and let me know if you still face the same issue ? Awaiting your reply.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your reply. Actually not. See below for details:

Request:
PUT /subscriptions/?/resourceGroups/acctestRG-postgresql-230320155838217513/providers/Microsoft.DBforPostgreSQL/flexibleServers/acctest-fs-230320155838217513?api-version=2022-12-01

`{"identity":{"type":"SystemAssigned"},"location":"eastus","properties":{"administratorLogin":"adminTerraform","administratorLoginPassword":"QAZwsx123","availabilityZone":"2","backup":{"geoRedundantBackup":"Disabled"},"highAvailability":{"mode":"Disabled"},"network":{},"storage":{"storageSizeGB":32},"version":"12"},"sku":{"name":"Standard_D2s_v3","tier":"GeneralPurpose"},"tags":{}}`

Response From API:

```
{"error":{"code":"CannotSetResourceIdentity","message":"Resource type 'Microsoft.DBforPostgreSQL/flexibleServers' does not support creation of 'SystemAssigned' resource identity. 
The supported types are 'UserAssigned'."}}
```

**Comment by navba-MSFT** [comment]
@sinbai I am working internally with the Product Owners, I will provide you an update once I hear from them.

**Comment by navba-MSFT** [comment]
@sinbai I have got an update from the Product Owners that if you’re creating a flexible server with SystemAssigned MI for CMK, then, no that won’t work. We don’t have support for SystemAssigned MI. That is by-design right now. And we don’t have plan to support that in the near future. 

Please remove the whole part from your request body for now: "identity":{"type":"SystemAssigned"}

I am checking internally on updating the swagger too.
