### ISSUE TITLE
Incorrect parameter value in Swagger specification for MS Sentinel API

### ISSUE THREAD

**Issue by billyman6675** [Azure/azure-rest-api-specs#23182]
I noticed the swagger spec for the Source Controls endpoint for Microsoft Sentinel lists "DevOps" as an accepted value for the repoType parameter, using this value causes the API request to fail. I found the true accepted value within the Azure portal The true accepted value is "AzureDevOps". The incorrect value is presented in both the swagger spec and learn.microsoft.com documentation.

https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/source-controls/create?tabs=HTTP#repotype
[specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-03-01-preview/SourceControls.json](https://github.com/Azure/azure-rest-api-specs/blob/0080664dbdee831fb21fc817e2acd434fd0fd146/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2023-03-01-preview/SourceControls.json)

**Comment by SaurabhSharma-MSFT** [comment]
@billyman6675 The PR for the fix has been created and it will be merged upon the approval. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
