### ISSUE TITLE
https://prices.azure.com/api/retail/prices API call - Missing product names

### ISSUE THREAD

**Issue by JNickson** [Azure/azure-rest-api-specs#23279]
Question - I know the preview has some additional product names like Cosmos DB, are key vaults also going to be added in the near future, and if possible what does the timeline look like regarding this?

**Comment by navba-MSFT** [comment]
@JNickson Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@JNickson Try access the link with the `serviceName `filter as shown below:

```
https://prices.azure.com/api/retail/prices?$filter=serviceName eq 'Key Vault'
```

This should show the retail price for key vault. Hope this helps.

**Comment by navba-MSFT** [comment]
@JNickson I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@JNickson The action is pending on you to try the [above suggestion](https://github.com/Azure/azure-rest-api-specs/issues/23279#issuecomment-1486572923). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
