### ISSUE TITLE
SecurityInsights: Get Incidents Api response does not include 'systemData' property.

### ISSUE THREAD

**Issue by devenramani** [Azure/azure-rest-api-specs#23383]
While trying out the Get Incidents API Request the response as documented in [this article](https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/incidents/get?tabs=HTTP#incident) shows the 'systemData' object, but it never is returned in the actual API response.

Steps to Reproduce - 
Request Get Incident API :  GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/incidents/{incidentId}?api-version=2023-03-01-preview

Response : `{
  "id": "/subscriptions/d0cfe6b2-9ac0-4464-9919-dccaee2e48c0/resourceGroups/myRg/providers/Microsoft.OperationalIinsights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/incidents/73e01a99-5cd7-4139-a149-9f2736ff2ab5",
  "name": "73e01a99-5cd7-4139-a149-9f2736ff2ab5",
  "etag": "\"0300bf09-0000-0000-0000-5c37296e0000\"",
  "type": "Microsoft.SecurityInsights/incidents",
  "properties": {
    "title": "My incident",
    "description": "This is a demo incident",
    "severity": "High",
    "status": "Closed",
    "classification": "FalsePositive",
    "classificationReason": "InaccurateData",
    "classificationComment": "Not a malicious activity",
    "owner": {
      "objectId": "2046feea-040d-4a46-9e2b-91c2941bfa70",
      "email": "john.doe@contoso.com",
      "assignedTo": "john doe",
      "userPrincipalName": "john@contoso.com",
      "ownerType": "User"
    },
    "labels": [],
    "firstActivityTimeUtc": "2019-01-01T13:00:30Z",
    "lastActivityTimeUtc": "2019-01-01T13:05:30Z",
    "lastModifiedTimeUtc": "2019-01-01T13:15:30Z",
    "createdTimeUtc": "2019-01-01T13:15:30Z",
    "incidentNumber": 3177,
    "additionalData": {
      "alertsCount": 0,
      "bookmarksCount": 0,
      "commentsCount": 3,
      "alertProductNames": [],
      "tactics": [
        "InitialAccess",
        "Persistence"
      ],
      "techniques": [
        "T1091",
        "T1133",
        "T1053"
      ],
      "providerIncidentUrl": "https://security.microsoft.com/incidents/3177?tid=5b5a146c-eba8-46af-96f8-e31b50d15a3f"
    },
    "relatedAnalyticRuleIds": [
      "/subscriptions/d0cfe6b2-9ac0-4464-9919-dccaee2e48c0/resourceGroups/myRg/providers/Microsoft.OperationalIinsights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/alertRules/fab3d2d4-747f-46a7-8ef0-9c0be8112bf7"
    ],
    "incidentUrl": "https://portal.azure.com/#asset/Microsoft_Azure_Security_Insights/Incident/subscriptions/d0cfe6b2-9ac0-4464-9919-dccaee2e48c0/resourceGroups/myRg/providers/Microsoft.OperationalIinsights/workspaces/myWorkspace/providers/Microsoft.SecurityInsights/incidents/73e01a99-5cd7-4139-a149-9f2736ff2ab5",
    "providerName": "Azure Sentinel",
    "providerIncidentId": "3177"
  }
}`

How can I get the 'systemData' property in the response object?

**Comment by navba-MSFT** [comment]
@devenramani Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by trindels** [comment]
@navba-MSFT - It appears that the same issue is occuring for the Microsoft.SecurityInsights/alertRules (Get/List) API.

**Comment by navba-MSFT** [comment]
@devenramani I am discussing this internally with the Sentinel team. I will update this thread once I hear from them.

**Comment by navba-MSFT** [comment]
@devenramani @trindels I am yet to hear from them. I will update this thread once I receive their reply.

**Comment by navba-MSFT** [comment]
@devenramani @trindels I got a reply from the Product owners. It appears in the swagger and our [documentation](https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/incidents/get?tabs=HTTP#systemdata) because this field is part of the common Resource ARM type. 

In Sentinel we never implemented/supported the `systemData `field.

**Comment by navba-MSFT** [comment]
@devenramani I hope you had a chance to look at the above reply shared by our Product Group team. Please feel free to reopen this thread if you have any follow-up questions.
