### ISSUE TITLE
MySql Server PUT should be called Create instead of CreateOrUpdate

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#2339]
https://github.com/Azure/azure-rest-api-specs/blob/679502c4b4af7af7115509f7b9b7ec16d78de70b/specification/mysql/resource-manager/Microsoft.DBforMySQL/preview/2017-04-30-preview/mysql.json#L42

MySQL and Postgres both support PATCH for servers, but the PUT call is called "Servers_Create" in Postgres but "Servers_CreateOrUpdate" in MySQL.  They should logically be the same.

**Comment by lmazuel** [comment]
@rahulgouthamDOTgs could you help tag the right person here?

**Comment by lmazuel** [comment]
Fixed:
https://github.com/Azure/azure-rest-api-specs/blob/5a702f17ac0989db40df4b42186cfbe4a0996bbd/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json#L42

**Comment by rahulgouthamDOTgs** [comment]
@QingqingYuan  Can you help ? I am not sure who is the contact for mysql .

**Comment by lmazuel** [comment]
@rahulgouthamDOTgs looking at the Swagger now, fr me it's solved. Feel free to tell otherwise if I misunderstood something :)

**Comment by QingqingYuan** [comment]
@lmazuel  Yes, we fixed this during service GA. :)
