### ISSUE TITLE
[Microsoft.CostManagement/views] API usage portal differs from REST API Spec

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-rest-api-specs#23436]
When trying to create an Azure Terraform provider resource I got really confused how to create a view.

In the portal the API is using different values than are available in the REST API Spec:
- `properties.query.type` has value `actualCost` -> According to definition: Only value is 'Usage' (required)
- `properties.query.timeframe` has value `None` -> According to definition: Possible values are 'Custom', 'MonthToDate', 'WeekToDate', 'YearToDate'

```json
# Request body on PUT for https://management.azure.com/subscriptions/<id>/providers/Microsoft.CostManagement/views/test3?api-version=2021-10-01
{
  "properties": {
    "currency": "EUR",
    "dateRange": "Last6Months",
    "query": {
      "type": "ActualCost",
      "dataSet": {
        "granularity": "Monthly",
        "aggregation": {
          "totalCost": {
            "name": "Cost",
            "function": "Sum"
          },
          "totalCostUSD": {
            "name": "CostUSD",
            "function": "Sum"
          }
        },
        "sorting": [
          {
            "direction": "ascending",
            "name": "BillingMonth"
          }
        ]
      },
      "timeframe": "None"
    },
    "chart": "StackedColumn",
    "accumulated": "true",
    "pivots": [
      {
        "type": "Dimension",
        "name": "ServiceName"
      },
      {
        "type": "Dimension",
        "name": "ResourceLocation"
      },
      {
        "type": "Dimension",
        "name": "ResourceGroupName"
      }
    ],
    "scope": "subscriptions/<id>",
    "kpis": [
      {
        "type": "Budget",
        "id": "COST_NAVIGATOR.BUDGET_OPTIONS.NONE",
        "enabled": true,
        "extendedProperties": {
          "name": "COST_NAVIGATOR.BUDGET_OPTIONS.NONE"
        }
      },
      {
        "type": "Forecast",
        "enabled": true
      }
    ],
    "displayName": "test3"
  }
}
```

What is the source of truth and are there any valid examples for the REST API calls to craete some nice views?

And if someone would be so nice to explain how to construct the `aggregation` object and what the possibilities are for that: that would be awesome!

**Comment by SaurabhSharma-MSFT** [comment]
@aristosvo We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@aristosvo Sorry for the delay.  Can you please look into the documentation over [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.costmanagement/views?pivots=deployment-language-terraform) which is for CostManagement in Terraform.  It has same values are it is available through the REST API endpoint.
