### ISSUE TITLE
Missing string type for ManagedServiceIdentity enum

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-rest-api-specs#2344]
It looks like there is a missing typedef in swagger specs of ManagedServiceIdentity:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/CommonDefinitions.json#L1038

This breaks the go SDK that expects a map while the output of the identity field is a plain string:
```json
{
     .....
    "kind": "app",
  },
  "identity": {
    "type": "SystemAssigned",
    "tenantId": "....",
    "principalId": "......"
  }
}
```
see also
https://github.com/Azure/azure-sdk-for-go/issues/992#issuecomment-360561749

**Comment by dsgouda** [comment]
Tagging @naveedaz  since he last worked on this spec

**Comment by jhendrixMSFT** [comment]
Ping @naveedaz

**Comment by jhendrixMSFT** [comment]
Spec has been fixed, will get rolled up into next major release of Go SDK.
