### ISSUE TITLE
Logz: Monitor API doesn't return `UserInfo`

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#23461]
This API: https://learn.microsoft.com/en-us/rest/api/logz/monitors/get?tabs=HTTP

> GET https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.Logz/monitors/myMonitor?api-version=2020-10-01

reuses the same model for Create and Get, which both define the property `UserInfo` - however whilst this value can be set via Create, this isn't returned from the Get API.

As such can this API bug be fixed / this data returned?

Thanks!

**Comment by navba-MSFT** [comment]
@tombuildsstuff Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tombuildsstuff This is expected behavior, as currently we are removing the ‘User Info’ details before patching Monitor Resource along with other details. Currently we are working internally to understand if there is a way we can store and subsequently return ‘User Info’ details in GET Monitor without violating any existing rules. Hope this answers.

**Comment by tombuildsstuff** [comment]
@navba-MSFT 

> This is expected behavior

My understanding is that the ARM Specification states that any field sent to the API (which isn't a password/API Key) **must** be returned in the API Response/via a GET call, which would mean this API doesn't comply with the ARM Specification?

> as currently we are removing the ‘User Info’ details before patching Monitor Resource along with other details.

Can you clarify what you mean by this, are you saying that this field will be removed entirely (e.g. also from Creation), or only during updates? Neither of these will fix the issue with the GET API, however?

**Comment by navba-MSFT** [comment]
@tombuildsstuff Thanks for getting back. I have discussed this issue internally with our Product owners. We will fix this Bug in Get API to return the `UserInfo` data. I don't have any fixed ETA for the fix at this moment.

**Comment by tombuildsstuff** [comment]
@navba-MSFT looks like the same issue exists within the `SubAccounts` API, can that be fixed at the same time, or should I open a separate issue to track that?

> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Logz/monitors/{monitorName}/accounts/{accountName}

**Comment by navba-MSFT** [comment]
> @navba-MSFT looks like the same issue exists within the `SubAccounts` API, can that be fixed at the same time, or should I open a separate issue to track that?
> 
> > /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Logz/monitors/{monitorName}/accounts/{accountName}

@tombuildsstuff Yes, please file a new issue. So that we can track it separately.

**Comment by navba-MSFT** [comment]
@tombuildsstuff A quick update. The fix for this should be available in end of May'23.

**Comment by navba-MSFT** [comment]
@tombuildsstuff Fix is deployed in Production. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
