### ISSUE TITLE
Service: Consumption. Filter parameter does not work for Usage Details API for CSP Subscription(API Version: 2023-03-01) 

### ISSUE THREAD

**Issue by SanyuktaAgrawal** [Azure/azure-rest-api-specs#23510]
I used this https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP

I tried to filter usage details by multiple different filters on properties/resourceGroup, properties/date, properties/reservationId but I always get the same data for CSP subscriptions.

URLs tried: 

1. https://management.azure.com/subscriptions/xxx/providers/Microsoft.Consumption/usageDetails?api-version=2023-03-01&$filter=properties/resourceGroup+eq+'XYZ'

2. https://management.azure.com/subscriptions/xyz/providers/Microsoft.Consumption/usageDetails?$filter=properties/reservationId+eq+'xxx'&metric=amortizedcost&api-version=2023-03-01

3. https://management.azure.com/subscriptions/xxx/providers/Microsoft.Consumption/usageDetails?api-version=2023-03-01&$filter=properties/date+ge+'2023-04-04'+AND+properties/date+lt+'2023-04-05'

Expectation: Get filtered data.
Actula Response: All data without any filters.

**Comment by navba-MSFT** [comment]
@SanyuktaAgrawal Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Regarding the [Usage Details - List](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP) REST API, Microsoft will be retiring the Consumption Usage Details API at some point in the future. We do not recommend that you take a new dependency on this API. Please use the [Cost Details API ](https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?tabs=HTTP)instead. 

This API is the replacement for all previously release Usage Details APIs. Request to generate a cost details report for the provided date range, billing period (Only enterprise customers) or Invoice Id asynchronously at a certain scope. The initial call to request a report will return a 202 with a 'Location' and 'Retry-After' header. The 'Location' header will provide the endpoint to poll to get the result of the report generation. The 'Retry-After' provides the duration to wait before polling for the generated report. A call to poll the report operation will provide a 202 response with a 'Location' header if the operation is still in progress. Once the report generation operation completes, the polling endpoint will provide a 200 response along with details on the report blob(s) that are available for download. The details on the file(s) available for download will be available in the polling response body.

**Comment by navba-MSFT** [comment]
@SanyuktaAgrawal I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@SanyuktaAgrawal I hope you had a chance to look at the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by DuyTheNguyen** [comment]
I can filter by start date and end date by following [this](https://github.com/Azure/azure-rest-api-specs/issues/11764#issuecomment-741448519), but

Can you please advise how to filter by resource group name?
