### ISSUE TITLE
Logz SubAccounts API doesn't return `UserInfo`

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#23573]
@navba-MSFT looks like the same issue exists within the `SubAccounts` API, can that be fixed at the same time, or should I open a separate issue to track that?

> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Logz/monitors/{monitorName}/accounts/{accountName}

_Originally posted by @tombuildsstuff in https://github.com/Azure/azure-rest-api-specs/issues/23461#issuecomment-1510728888_

See a similar issue for the Logz `Monitor` API in #23461

**Comment by navba-MSFT** [comment]
@tombuildsstuff  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tombuildsstuff I shared this issue with the Product Owners. Currently awaiting their reply. I will update this thread once I hear from them.

**Comment by navba-MSFT** [comment]
@tombuildsstuff A quick update. The fix for this should be available in end of May'23.

**Comment by navba-MSFT** [comment]
@tombuildsstuff Fix is deployed in Production. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
