### ISSUE TITLE
Azure RecoveryServices.Backup documentation incomplete and pointing to wrong node

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/azure-rest-api-specs#2362]
The current RecoveryService - Backup documentation is pointing to `site-recovery` node (https://docs.microsoft.com/en-us/rest/api/site-recovery/backupjobs/list). Ideally it should have been pointing to `backup` (https://docs.microsoft.com/en-us/rest/api/backup/) node. 

Also, current documentation is present only for api-version `2017-07-01` and other api-version `2016-12-01` is missing from there which lead to incomplete documentation as major APIs are present with second version.

**Comment by DheerendraRathor** [comment]
@marstr Any update on this? This is very crucial for us as customers don't have any documentation for missing APIs.

**Comment by marstr** [comment]
@DheerendraRathor, please submit a PR which adjusts your documentation as desired.

**Comment by DheerendraRathor** [comment]
What will be the content or PR? Is it documented somewhere about how public documentation is generated from here?

**Comment by marstr** [comment]
I'm unclear on the ask here. There is an external team that takes these Swaggers and generates documentation with them. @mikekinsman is a PM on that team, and the guy I interact with when I have documentation questions or concerns.

If your Swaggers are complete and accurate, then I'm not sure an issue in the specs repository is the best way to get your concerns addressed.

Is there something I'm missing? Sorry, let me know if there are some actions regarding the Swaggers that need to be taken.

**Comment by mikekinsman** [comment]
@DheerendraRathor 

> The current RecoveryService - Backup documentation is pointing to site-recovery node (https://docs.microsoft.com/en-us/rest/api/site-recovery/backupjobs/list). Ideally it should have been pointing to backup (https://docs.microsoft.com/en-us/rest/api/backup/) node.
Where is the bad link? 

> Also, current documentation is present only for api-version 2017-07-01 and other api-version 2016-12-01 is missing from there which lead to incomplete documentation as major APIs are present with second version.
Following up in email about this.

**Comment by marstr** [comment]
I'm going to close this issue out, it sounds like it doesn't directly pertain to this repository. If there is something actionable that pops-up for this repo, feel free to ping the thread and have it re-opened.
