### ISSUE TITLE
Invalid id in response of CostManagement-Export: it doesn't start with "/" 

### ISSUE THREAD

**Issue by dvbb** [Azure/azure-rest-api-specs#23704]
All `export` related operations return error resource id 

e.g. :
https://github.com/Azure/azure-rest-api-specs/blob/6054f1d9f96a4f5189dace33facf9144d468e705/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/examples/ExportCreateOrUpdateBySubscription.json#L47

Usually, ARM Resource's id should start with /. This is a blocking issue for CostManagement Track2 .NET SDK.

**Comment by ArthurMa1978** [comment]
Created [another issue](https://github.com/Azure/azure-sdk-for-net/issues/37481) in ,net sdk repo.
