### ISSUE TITLE
Metric API Metrics_List top parameter is modeled as number

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#2371]
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/monitor/resource-manager/microsoft.insights/preview/2017-05-01-preview/metrics_API.json#L372 

number means double in C# and Java. I hardly can imagine how useful top 1.5 records will sound. This property should be "integer".

**Comment by asheniam** [comment]
Thanks for reporting this.  Top should be an integer.  We are looking at a fix.

**Comment by kpajdzik** [comment]
Fixed in #6485
