### ISSUE TITLE
Network SubResource cannot have the x-ms-azure-resource flag

### ISSUE THREAD

**Issue by dsgouda** [Azure/azure-rest-api-specs#2372]
The `x-ms-azure-resource` flag is reserved only for Resources (`TrackedResource` and `ProxyResource`) i.e., they must at least have the `name`, `id` and `type` properties defined.
The definition `SubResource` defined in the network spec here contains only `id` and therefore does not qualify as a resource but has been assigned the `x-ms-azure-resource` flag. This has been subsequently referenced in other specs incorrectly which may cause linter validation errors and perhaps generated code that is incorrect. 
Please fix this soon.

**Comment by MikhailTryakhov** [comment]
fixed
