### ISSUE TITLE
APIM Apis - List By Service / how to send multiple tags in the query param

### ISSUE THREAD

**Issue by copdips** [Azure/azure-rest-api-specs#23731]
Hello,

I would like to send a query with multiple tags (single tag works already) in the query params of Apis - List By Service

https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/list-by-service?tabs=HTTP
![image](https://user-images.githubusercontent.com/13083856/234602131-0ef096cf-1a2e-4b8e-92cb-bfce8bca4556.png)

Suppose, I have two tags: a,b
I tried `"a,b"`,   `"a:b"`, `"a b"`, `"a;b"`, but none of them works, could you please tell me how to send mulitple tags

**Comment by navba-MSFT** [comment]
@copdips Thanks for reaching out to us and reporting this issue. If you want to include only APIs that have both tags "a" and "b", you can use `tags=a&tags=b`.

Your Request URL would look like below:

> https:// management.azure.com/subscriptions/{subID}/resourceGroups/{RG}/providers/Microsoft.ApiManagement/service/{apimName}/apis?api-version=2022-08-01&**tags=a&tags=b**

Hope this helps.

**Comment by copdips** [comment]
@navba-MSFT ,
based on [this reponse](https://github.com/Azure/azure-sdk-for-python/issues/30103#issuecomment-1534002012) from azure python sdk team, could you please check the [API swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/817e7cea0b7e3194868825cbef6d4e62a7895951/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/apimapis.json#L73-L77) of APIM Apis

**Comment by navba-MSFT** [comment]
@copdips Thanks for your reply. Could you please check and confirm if you have tried my[ above suggestion](https://github.com/Azure/azure-rest-api-specs/issues/23731#issuecomment-1525151467) and invoke the API to see if you get the right response ? Awaiting your reply.

**Comment by copdips** [comment]
@navba-MSFT 
according to my test, only the first `tags=aa` is taken into account by the API, the second `tags=bb` is ignored silently.
api-version=2022-08-01

**Comment by navba-MSFT** [comment]
@copdips Could you please send us the REST API request URL and the request headers you had used ? 

PS: Remove the tokens and subscription ID and resource names from the request.

**Comment by copdips** [comment]
@navba-MSFT 

```bash
az rest --uri "/subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$resource_group_name/providers/Microsoft.ApiManagement/service/$apim_service_name/apis?api-version=2022-08-01&tags=aa&tags=bb"
```

the result shows all the APIs with tag `aa`, not with tags `aa` and `bb` only

**Comment by navba-MSFT** [comment]
@copdips My bad. I tried to invoke the above API with **tags=a&tags=b** in the query string. It lists the API which has either tag A or tag B or both. In short, it follows the OR condition , not AND condition. I have even tested this from the Azure Portal. Could you please test from Azure Portal and confirm if that works ?

<img width="320" alt="image" src="https://github.com/Azure/azure-rest-api-specs/assets/57353862/19ee18fc-c2a9-4b60-8ea9-c17e7d65c5d1">

**Comment by copdips** [comment]
@navba-MSFT 
from the portal, it does an OR operation. and what I need is an AND operation:

![Screenshot by Dropbox Capture](https://github.com/Azure/azure-rest-api-specs/assets/13083856/a851c060-47f8-4b9c-8109-9d8e16260db3)

**Comment by navba-MSFT** [comment]
@copdips It only supports OR operation as of now and it is by design.

**Comment by copdips** [comment]
@navba-MSFT 
thx for the confirmation about the OR operation, but how to resolve the issue I mentionned firstly that how to use `tags=a&tags=b` in Python SDK?
[as explained by Python SDK team](https://github.com/Azure/azure-sdk-for-python/issues/30103#issuecomment-1534002012), there could be some drift in the APIM swagger definition and APIM API that the sawgger says it doesn't support multiple same query param. The Python SDK follows the swagger definition but not the real capability of the API.

**Comment by navba-MSFT** [comment]
@copdips Thanks for your reply. The workaround I can suggest now is, after you list the APIs using the` tags=a&tags=b `you can perform the filtering programmatically. Iterate through the list of APIs returned in the response and filter them based on the desired tags **(A and B)** in your code or script.

**Comment by copdips** [comment]
@navba-MSFT 
it turns out that it might have some mismatching between API and its swagger definition, although we can do some local filtering after the API call. But OK, I'll close this issue, thank you very much for your help.
