### ISSUE TITLE
Incorrect Validation for ResourceNameRestriction

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-rest-api-specs#23737]
https://github.com/Azure/azure-rest-api-specs/pull/22978/checks?check_run_id=13024521883

> The resource name parameter 'notificationName' should be defined with a 'pattern' restriction.
> Location: [Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json#L1828](https://github.com/Azure/azure-rest-api-specs/blob/e6e61df03b325344f43cdfe756c44ed58d94e409/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimworkspaces.json#L1828)

The parameter already has restriction as defined here 

https://github.com/Azure/azure-rest-api-specs/blob/e6e61df03b325344f43cdfe756c44ed58d94e409/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimanagement.json#L467

**Comment by solankisamir** [comment]
Same issue for 
https://github.com/Azure/azure-rest-api-specs/pull/22978/checks?check_run_id=13024521967

> The resource name parameter 'accessName' should be defined with a 'pattern' restriction.
> Location: [Microsoft.ApiManagement/preview/2022-09-01-preview/apimtenant.json#L354](https://github.com/Azure/azure-rest-api-specs/blob/e6e61df03b325344f43cdfe756c44ed58d94e409/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/apimtenant.json#L354)

**Comment by solankisamir** [comment]
@JackTn this is an issue in the tooling itself.

**Comment by JackTn** [comment]
@solankisamir My fault. I create a new issue https://github.com/Azure/azure-openapi-validator/issues/501 on https://github.com/Azure/azure-openapi-validator#azure-openapi-validator repo. You can follow that one and i close this one. Thanks !
