### ISSUE TITLE
Microsoft.DataFactory/factories/pipelines@2018-06-01 - The definition of isolationLevel in SqlServerSource is missing

### ISSUE THREAD

**Issue by gabrielweyer** [Azure/azure-rest-api-specs#23857]
## Description

The `isolationLevel` property is not defined in the OpenAPI specification, but it's a working field.

```bicep
@description('Azure location for the deployed Azure Resources')
param azureLocation string = resourceGroup().location

@description('Azure Data Factory resource name. Globally unique.')
@minLength(1)
param dataFactoryName string = resourceGroup().location

resource dataFactory 'Microsoft.DataFactory/factories@2018-06-01' = {
  name: dataFactoryName
  location: azureLocation
  identity: {
    type: 'SystemAssigned'
  }
}

resource sqlServerLinkedService 'Microsoft.DataFactory/factories/linkedServices@2018-06-01' = {
  name: 'sql_server'
  parent: dataFactory
  properties: {
    type: 'SqlServer'
    typeProperties: {
      connectionString: 'Data Source=.;Initial Catalog=SomeDatabase;Integrated Security=False;User ID=SomeUserName;Password=SomePassword;'
    }
  }
}

resource sqlServerDataset 'Microsoft.DataFactory/factories/datasets@2018-06-01' = {
  name: 'sql_server_some_table'
  parent: dataFactory
  properties: {
    linkedServiceName: {
      referenceName: sqlServerLinkedService.name
      type: 'LinkedServiceReference'
    }
    type: 'SqlServerTable'
    typeProperties: {
      schema: 'dbo'
      table: 'SomeTable'
    }
  }
}

resource pipeline 'Microsoft.DataFactory/factories/pipelines@2018-06-01' = {
  name: 'pipeline'
  parent: dataFactory
  properties: {
    activities: [
      {
        name: 'MyCopy'
        type: 'Copy'
        inputs: [
          {
            type: 'DatasetReference'
            referenceName: sqlServerDataset.name
          }
        ]
        outputs: [
          {
            type: 'DatasetReference'
            referenceName: sqlServerDataset.name
          }
        ]
        typeProperties: {
          source: {
            type: 'SqlServerSource'
            sqlReaderQuery: 'SELECT Id from dbo.SomeTable;'
            isolationLevel: 'RepeatableRead' // Not defined in the spec
          }
          sink: {
            type: 'SqlServerSink'
          }
        }
      }
    ]
  }
}
```

## Details

According to the [documentation](https://learn.microsoft.com/en-us/azure/data-factory/connector-sql-server?tabs=data-factory#sql-server-as-a-source), `isolationLevel` is a valid property:

![image](https://user-images.githubusercontent.com/2101647/236807346-fad884be-909c-49c1-ad02-b6496db47df6.png)

When deploying the Bicep file provided above, the `isolationLevel` property is set as expected in the Azure Data Factory Studio:

![image](https://user-images.githubusercontent.com/2101647/236807431-a191d2da-0fb7-4b7c-81e9-fa083087c3c1.png)

The `isolationLevel` property is missing from the [API specs](https://github.com/Azure/azure-rest-api-specs/blob/07c55de803057861912799405580ea9d022853fc/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L2632-L2668).

**Comment by navba-MSFT** [comment]
@gabrielweyer Thanks for reaching out to us and reporting this issue. The `isolationLevel` property is available in the swagger specs and the accepted values are ReadCommitted/ReadUncommitted/RepeatableRead/Serializable/Snapshot. The default value is `ReadCommitted`.

See below:

https://github.com/Azure/azure-rest-api-specs/blob/d5c8648e01a2a2a743c2649c9522d21f5db952ce/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L2617-L2621

**Comment by gabrielweyer** [comment]
Thank you @navba-MSFT, the property is indeed present on `SqlSource`, but it is not present on `SqlServerSource`. I'm not too sure why I ended up using `SqlServerSource` because the documentation states I should be using `SqlSource`:

![image](https://github.com/Azure/azure-rest-api-specs/assets/2101647/74767143-62ac-4f13-86fb-df895de8abbb)

Do you know what is the difference between `SqlSource` and `SqlServerSource`?

**Comment by navba-MSFT** [comment]
@gabrielweyer SqlSource is a generic connector that can be used with any SQL-based database, including SQL Server, MySQL, Oracle, and others. It offers a set of common properties that are applicable to all SQL-based databases, such as queryTimeout, partitionColumn, and partitionCount. 

SqlServerSource is a connector specifically designed for reading data from SQL Server databases. It offers properties that are specific to SQL Server, such as useBulkCopy, tableOption, and sqlReaderQueryTimeout. 

If you need to specify the isolationLevel property when reading data from a SQL Server database, you should use the SqlSource connector instead of SqlServerSource. This is because the isolationLevel property is a common property that is applicable to all SQL-based databases, not just SQL Server.

**Comment by gabrielweyer** [comment]
Thanks for clearing this up. I'm happy to close this issue.
