### ISSUE TITLE
Update API for WebApps - Update Application Settings is broken

### ISSUE THREAD

**Issue by ericstoekl** [Azure/azure-rest-api-specs#2393]
Hi Azure Folks,
I am attempting to use this [Azure REST API](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/updateapplicationsettings) to update the App Settings in my Azure Functions. The only other way to update is [through the CLI tool](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish), which is not an option for me because I would like to modify the App Settings in my VSTS CI/CD pipeline.

I know that I can use the [Azure REST API for listing out the app settings](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listapplicationsettings), and this works for me. I use this command:

```
curl -i -X POST https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Web/sites/<AZ_FUNCTION_NAME>/config/appsettings/list\?api-version\=2016-08-01 -H "Authorization: bearer <TOKEN>" -d ""
```

I get back a JSON object that includes the list of my App Settings. Cool!

However, when I try to use the Update API, like this:

```
curl -i -X PUT https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Web/sites/<FUNCTION_NAME>/config/appsettings\?api-version\=2016-08-01 -H "Authorization: bearer <TOKEN>" -d '{"SiteAppSettings":"MY_UNIQUE_APP_VERSION=0.0.2"}'
```

I have tried many forms of that Body JSON, and all I ever get is this response back:

```
{"Code":"BadRequest","Message":"SiteAppSettings object is not present in the request body.","Target":null,"Details":[{"Message":"SiteAppSettings object is not present in the request body."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01008","MessageTemplate":"{0} object is not present in the request body.","Parameters":["SiteAppSettings"],"Code":"BadRequest","Message":"SiteAppSettings object is not present in the request body."}}],"Innererror":null}
```

I can't find any reference to `SiteAppSettings` in the documentation. What is the correct syntax for this Update API call?

Thanks,
Eric

**Comment by ericstoekl** [comment]
Thank you!

**Comment by dagrooms52** [comment]
I think this may be an issue with the docs as I just stumbled across it as well. 

I propose making the error message something like `"properties" object is not present in the request body` or adding an example to the documentation showing the key `"properties"` being used in the PUT request.

**Comment by js-kyle** [comment]
Also came across this issue, would be good to get a relevant error message
