### ISSUE TITLE
Cost Details report API returns "202 Accepted"

### ISSUE THREAD

**Issue by Mantrareborn** [Azure/azure-rest-api-specs#24014]
I've been trying to get a full usage detailed report using the MS new API, my ultimate goal is to create a powershell script that gets usage on demand (when running the script) on a specific time period.
I used Postman to get the initial test whether the API calls the right data or not, but i've been getting the "202 Accepted" response from postman (see screenshot):
![image](https://github.com/Azure/azure-rest-api-specs/assets/16080423/541fe268-b789-44c4-b6be-3ecda780bea1)

What does that mean, am I missing something on the request ?

**Comment by SwathiDhanwada-MSFT** [comment]
@Mantrareborn Thanks for your question. The initial call to request a report will return a 202 with a 'Location' and 'Retry-After' header. The 'Location' header will provide the endpoint to poll to get the result of the report generation. The 'Retry-After' provides the duration to wait before polling for the generated report. A call to poll the report operation will provide a 202 response with a 'Location' header if the operation is still in progress. Once the report generation operation completes, the polling endpoint will provide a 200 response along with details on the report blob(s) that are available for download. The details on the file(s) available for download will be available in the polling response body.

**Comment by Mantrareborn** [comment]
Hello @SwathiDhanwada-MSFT here a sample of my code 
it's always returns an empty object in the response with no crashes :

`generateReportUri = "https://management.azure.com/subscriptions/$subscriptionId/providers/Microsoft.CostManagement/generateCostDetailsReport?api-version=2022-10-01"

    $reportRequest = @{
        metric = "ActualCost"
        timePeriod = @{
            start = $startDate
            end = $endDate
        }
    }
    $headers = @{
        "Authorization" =  "Bearer $((Get-AzAccessToken).Token)"
        "Retry-After" = "5000"
    }

  
    $reportResponse = Invoke-RestMethod -Uri $generateReportUri -Method Post -Body ($reportRequest | ConvertTo-Json) -Headers $headers



    # Get usage report URI
    $usageGet1Uri = $reportResponse.Headers["Location"]

    # Download and rename the usage report file
    $usageReport = Invoke-RestMethod -Uri $usageGet1Uri -Method Get -Headers @{ "Authorization" = "Bearer $((Get-AzAccessToken).Token)" }
    $blobLink = $usageReport.Manifest.blobs.blobLink
    $subscriptionName = (Get-AzSubscription -SubscriptionId $subscriptionId).Name
    $fileName = "$subscriptionName.csv"`

the problem that $reportResponse is just empty , it's not null and it's doesn't crash , just an empty variable 
![image](https://github.com/Azure/azure-rest-api-specs/assets/16080423/bb50549b-23d8-4d67-8d4b-f1d702616868)

**Comment by Mantrareborn** [comment]
Hello @SwathiDhanwada-MSFT the issue is solved now, it was Invoke webrequest instead of Invoke-RestMethod, I will be closing this issue now, thanks
