### ISSUE TITLE
LIST storage accounts under a subscription failed during pagination

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#24136]
When LISTing all the storage accounts under a subscription (total amount is high):

```
GET /subscriptions/<subscription id>/providers/Microsoft.Storage/storageAccounts?%24skiptoken=<token>&api-version=2021-09-01 HTTP/1.1
```

it failed with error below:

```
HTTP/2.0 502 Bad Gateway
Content-Length: 149
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 16 May 2023 21:22:39 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: e7cca614-d21d-b11c-c6f9-1c3b11df891c
X-Ms-Failure-Cause: service
X-Ms-Request-Id: 4bf764e6-ab59-45ba-b449-fd7b0779403b
X-Ms-Routing-Request-Id: WESTUS:20230516T212239Z:4bf764e6-ab59-45ba-b449-fd7b0779403b

{"error":{"code":"ProviderError","message":"Resource provider 'Microsoft.Storage' failed to return collection response for type 'storageAccounts'."}}: timestamp=2023-05-16T21:22:39.106Z
```

Suspicion is that there is a maximum limit of storage accounts under the same subscription to be retrieved from storage.AccountsClient List API. If existing storage accounts exceeded the limit, storage.AccountsClient List API will unable to reply.

## Related Issues

https://github.com/hashicorp/terraform-provider-azurerm/issues/21860

**Comment by blueww** [comment]
@magodo 

The error is reported from storage server, so this is a server issue.
Would you like to raise a help request in Azure portal like following picture, then the related team will be engaged to help you?
![image](https://github.com/Azure/azure-rest-api-specs/assets/6926193/717965cb-8cea-4b65-9a8a-a16e26a7433e)

**Comment by magodo** [comment]
@blueww Thank you for the advice, I've already openned a IcM ticket for this.

**Comment by blueww** [comment]
Close this issue, as it's server issue and should track in server side help ticker.
