### ISSUE TITLE
Support for PostgreSQL Flexible Server version 15

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-rest-api-specs#24186]
It would be great if version 15 could be added to this list: https://github.com/Azure/azure-rest-api-specs/blob/c9fd3070a45da18959192265c0e62dd34b521ab1/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FlexibleServers.json#L376-L379

This would ease adaptation of it in the Terraform Provider for Azure and other IaC tools.

Related:
- https://github.com/hashicorp/terraform-provider-azurerm/pull/21934

**Comment by navba-MSFT** [comment]
@aristosvo Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@aristosvo The above PR has been filed and it is currently under review.

**Comment by aristosvo** [comment]
@navba-MSFT Any reason why it is not fixed in the 2022-12-01 API? That is the one I'm using at the moment.

**Comment by navba-MSFT** [comment]
@aristosvo Please note that currently this API version is currently exposed only for private preview features, so I had to revert the  change from the current GA version` 2022-12-01` and keep it just for this version `2023-03-01-preview`.
