### ISSUE TITLE
Inconsistent list operations across Azure Swagger specifications

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#243]
# Inconsistent list operations across Azure Swagger specifications

Azure libraries for Java and other languages carry a large surface area. A major part of API ergonomics is consistent naming themes. Consistency makes it easier to use and memorize and also enables portability of learning. Having learnt a part of the library, developers can apply that learning across other parts of the libraries.

Specifications should use a consistent set of simple names for list operations across resources and resource providers, and offer list operations where developers are expecting:
- `list()` // list all 'resources' under a subscription
- `listByResourceGroup()` // list all resources in a resource group within a subscription

Where applicable, code gen may add `next` to support pagination:
- `listNext()` // list next for `list()` _generated by code gen_
- `listByResourceGroupNext()` // list next for `listByResourceGroup()` _generated by code gen_

Examined three Swagger specs - compute, storage and network. Samples quoted below are representative samples of a larger number of such inconsistencies. There might be additional inconsistent patterns if someone were to examine other Swagger specs - say `listBySubscription()` or `listInSubscription()` or `listInResourceGroups()` or `listAtResourceLevel()` or `listLocations()`.
## `list()` and `listAll()` used interchangeably with the _same_ semantics

Examples -
- [`StorageAccounts.list()`](https://github.com/Azure/azure-rest-api-specs/blob/0220c4e691422fd07cf26c8450a08b661798558a/arm-storage/2016-01-01/swagger/storage.json#L240) // list all storage accounts under a subscription
- [`VirtualMachines.listAll()`](https://github.com/Azure/azure-rest-api-specs/blob/3a9e2f263e16af428cfa7ec265ab1378d1cf66de/arm-compute/2016-03-30/swagger/compute.json#L1183) // list all virtual machines in a subscription
- [`VirtualNetworks.list()`](https://github.com/Azure/azure-rest-api-specs/blob/ee48544fac3da0ea018479fdc2272d8d11e/arm-network/2016-03-30/swagger/network.json#L3879) // list all virtual networks in a subscription
- [`ExpressRouteServiceProviders.list()`](https://github.com/Azure/azure-rest-api-specs/blob/2a137ee48544fac3da0ea018479fdc2272d8d11e/arm-network/2016-03-30/swagger/network.json#L1164) // List all Express Route Service Providers, independent of a resource group or a subscription
## `list(string)` and `listByResourceGroup(string)` are used interchangeably with the same semantics

Examples -
- [`VirtualNetworks.list(resourceGroupName)`](https://github.com/Azure/azure-rest-api-specs/blob/2a137ee48544fac3da0ea018479fdc2272d8d11e/arm-network/2016-03-30/swagger/network.json#L3907) // list all virtual networks in a resource group within a subscription
- [`StorageAccounts.listByResourceGroup(resourceGroupName)`](https://github.com/Azure/azure-rest-api-specs/blob/0220c4e691422fd07cf26c8450a08b661798558a/arm-storage/2016-01-01/swagger/storage.json#L268) // list all storage accounts in a resource group within a subscription
## `listAll()` is missing where developers would expect them

Examples -
- `VirtualMachineImages.listAll()` // list all virtual machine images. To realize this functionality, additional coding is required:
  
  ```
  var locations = getAzureLocations()
  for each (var location in locations) {
      var publishers = images.listPublishers(location.name)
          for each (var publisher in publishers) {
              var offers = images.listOffers(location.name, publisher.name)
                  for each (var offer in offers) {
                      var skus = images.listSkus(location.name, publisher.name, offer.name)
                          foreach (var sku in skus) {
                              images.list(location.name, publisher.name, offer.name, sku.name)
                  }
              }
          }
      }
  }
  ```
- `VirtualNetworkGateways.listAll()` // list all virtual network gateways
## Complicated `list()` names with complex parameters

Examples -
- [`listVirtualMachineScaleSetVMNetworkInterfaces(resourceGroupName, virtualMachineScaleSetName, virtualMachineIndex)`](https://github.com/Azure/azure-rest-api-specs/blob/2a137ee48544fac3da0ea018479fdc2272d8d11e/arm-network/2016-03-30/swagger/network.json#L1703) // list all virtual network interfaces in a virtual machine within a virtual machine scale set

**Comment by devigned** [comment]
I not sure we want to have ListNext if we are return lazy evaluated enumerable. Perhaps we'd have listNext for low level operations, but I'd imagine we'd want lazy enumeration more often than not.

**Comment by devigned** [comment]
@selvasingh, perhaps a pull request for these changes would best illustrate the issues and how we should fix them.

**Comment by selvasingh** [comment]
Right, lazy iterator is the chosen approach for Java ... there is no next()

**Comment by devigned** [comment]
Let's move the "VirtualMachineImages.listAll() // list all virtual machine images. To realize this functionality, additional coding is required:" issue into it's own issue.

**Comment by kirthik** [comment]
Closing this since linter catches this. We will start reporting it in CI soon.
