### ISSUE TITLE
92 variations of list operation names across Azure Swagger specifications

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#244]
# One More Thing ...
## There are 92 other variations of list names

The **good news** is that these list names can be modeled as `CollectionObject.list()` and `CollectionObject.listByResourceGroup()`.

Example One -

```
/catalog/usql/databases/{databaseName}/assemblies": { 
  "get": { 
     "tags": [ 
     "Catalog" 
   ], 
  "operationId": "Catalog_ListAssemblies", 
  "description": "Retrieves the list of assemblies from the Data Lake Analytics catalog. 
```

This can be modeled as `Assemblies.list()`.

Example Two -

```
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeAnalytics/accounts/{accountName}/StorageAccounts/": {
  "get": {
  "tags": [
     "Account"
  ],
  "operationId": "Account_ListStorageAccounts",
  "description": "Gets the first page of Azure Storage accounts, if any, linked to the specified Data Lake Analytics acco
```

This can be modeled as `StorageAccounts.list()`.

92 other variations of list names by Swagger specs are -

Authorization -
- [`listForResourceGroup()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L74)
- [`listForResource()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L109)
- [`listForResource()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L248)
- [`listForResourceGroup()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L321)
- [`listForScope()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L611)

Batch Management
- [`listKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-batch/2015-12-01/swagger/BatchManagement.json#L392)

CDN
- [`listBySubscriptionId()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-cdn/2015-06-01/swagger/cdn.json#L43)
- [`listByProfile()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-cdn/2015-06-01/swagger/cdn.json#L364)
- [`listByEndpoint()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-cdn/2015-06-01/swagger/cdn.json#L926)
- [`listByEndpoint()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-cdn/2015-06-01/swagger/cdn.json#L1247)

Compute
- [`listAvailableSizes()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L203)
- [`listTypes()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L294)
- [`listVersions()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L334)
- [`listOffers()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L687)
- [`listPublishers()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L727)
- [`listSkus()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L761)
- [`listAvailableSizes()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L1211)
- [`listSkus()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L1730)

Data Lake Analytics
- [`listStorageContainers()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json#L289)
- [`listSasTokens()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json#L396)
- [`listStorageAccounts()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json#L589)
- [`listDataLakeStoreAccounts()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json#L697)
- [`listExternalDataSources()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L251)
- [`listCredentials()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L376)
- [`listProcedures()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L508)
- [`listTables()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L647)
- [`listViews()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L786)
- [`listTableStatistics()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L932)
- [`listTypes()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L1032)
- [`listTableValuedFunctions()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L1172)
- [`listAssemblies()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L1304)
- [`listSchemas()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L1429)
- [`listDatabases()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json#L1547)

Data Lake Store
- [`listFirewallRules()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-store/account/2015-10-01-preview/swagger/account.json#L139)
- [`listFileStatus()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-store/filesystem/2015-10-01-preview/swagger/filesystem.json#L307)

DNS
- [`listZonesInResourceGroup()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-dns/2015-05-04-preview/swagger/dns.json#L546)
- [`listZonesInSubscription()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-dns/2015-05-04-preview/swagger/dns.json#L596)

Logic
- [`listBySubscription()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-logic/2015-02-01-preview/swagger/logic.json#L43)
- [`listSecretKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-logic/2015-02-01-preview/swagger/logic.json#L723)

Network
- [`listArpTable()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L845)
- [`listRoutesTable()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L902)
- [`listRoutesTableSummary()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L959)
- [`listVirtualMachineScaleSetVMNetworkInterfaces()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L1703)
- [`listVirtualMachineScaleSetNetworkInterfaces()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L1752)

Notification Hubs
- [`listAuthorizationRules()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L467)
- [`listKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L509)
- [`listAuthorizationRules()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L970)
- [`listKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L1019)

Redis
- [`listKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-redis/2015-08-01/swagger/redis.json#L238)

Remote App
- [`listInResourceGroup()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L238)
- [`listInSubscription()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L278)
- [`listPublishedApps()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L421)
- [`listSessions()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L589)
- [`listStartMenuApps()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L855)

Resources
- [`listAtResourceGroupLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L410)
- [`listAtResourceLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L453)
- [`listAtSubscriptionLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L560)
- [`listResources()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L509)
- [`listForResource()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1609)
- [`listForResourceGroup()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1680)
- [`listForScope()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1988)
- [`listLocations()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/subscriptions/2015-11-01/swagger/subscriptions.json#L43)

Scheduler
- [`listBySubscription()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2016-01-01/swagger/scheduler.json#L43)
- [`listJobHistory()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2016-01-01/swagger/scheduler.json#L655)

Storage
- [`listKeys()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-storage/2015-06-15/swagger/storage.json#L258)

Web
- [`listPremierAddOnOffers()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1291)
- [`listDomainRecommendations()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1612)
- [`listSiteAppSettings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10574)
- [`listSiteAppSettingsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10621)
- [`listSiteConnectionStrings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10802)
- [`listSiteConnectionStringsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10849)
- [`listSiteAuthSettings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11030)
- [`listSiteAuthSettingsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11077)
- [`listSitePublishingCredentials()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11258)
- [`listSitePublishingCredentialsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11306)
- [`listSiteMetadata()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11361)
- [`listSiteMetadataSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11408)
- [`listSitePremierAddOnsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11812)
- [`listSitePremierAddOns()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11862)
- [`listSiteBackups()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L12723)
- [`listSiteBackupsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L12768)
- [`listSitePublishingProfileXml()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L13655)
- [`listSitePublishingProfileXmlSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L13717)
- [`listSiteRelayServiceConnections()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14808)
- [`listSiteRelayServiceConnectionsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14855)
- [`listTopLevelDomainAgreements()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L15417)

Batch
- [`listPoolUsageMetrics()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L236)
- [`listFromTask()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L1962)
- [`listFromComputeNode()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L2100)
- [`listFromJobSchedule()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L4861)
- [`listPreparationAndReleaseTaskStatus()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L5005)
- [`listSubtasks()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/batch/2015-12-01.2.2/swagger/BatchService.json#L7739)

**Comment by selvasingh** [comment]
#243

**Comment by devigned** [comment]
Top level resources should have only list and list by resource group. 

The naming should be taken one by one for listByItems.

**Comment by amarzavery** [comment]
It would be nice if we can name list as listBySubscription. Thus we have two consistent names across all the services
- ListBySubscription (Provides all the resources in a subscription)
- ListByResourceGroup (Provides all the resources in a resourcegroup)

The reasoning behind naming List as ListBySubscription is that we want to create a wrapper method named `List()` which will either call ListBySubscription or ListByResourceGroup based on the parameter provided for the wrapper method. We will be coming up with a generic extension for creating a wrapper method.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/296

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/389

**Comment by kirthik** [comment]
Linter will catch this going forward.
