### ISSUE TITLE
[CostManagement] Is there a query API limit for Cost Management?

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-rest-api-specs#24407]
# Description
I have a trouble calling query api for Costmanagement.
I got error msg like `too many request`
![image](https://github.com/Azure/azure-rest-api-specs/assets/38625842/f8953e96-4bcf-4f0b-851d-7c834195bfa6)

# Question
1.I would like to learn about the API request limits for Cost Management, similar to the information provided in this article (https://learn.microsoft.com/en-us/answers/questions/1190190/what-is-the-criteria-for-azure-consumption-api-rat)
![image](https://github.com/Azure/azure-rest-api-specs/assets/38625842/26d693f1-e52d-47a9-a797-dfc15fbf3c4f)

2. If there are any conditions that could result in limitations or restrictions, I would appreciate it if you could provide me with details about those conditions

**Comment by navba-MSFT** [comment]
@ImMin5 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

We are working on proper documentation for all scenarios, but to unblock you now, here are the numbers:

•	**ARM rate limit:** 100 calls per 5 minutes 
•	**Qpu limits**: [https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/manage-automation#data-latency-and-rate-limits](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fcost-management-billing%2Fcosts%2Fmanage-automation%23data-latency-and-rate-limits&data=05%7C01%7Cnavba%40microsoft.com%7Cf0e730822c5b4c80d4ca08db6e3d1738%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638224980916364145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QUwyEOqZJKydSHWyBKzsMRW4Y0FIMpOebb5zpDuya1E%3D&reserved=0)

**Internal limits** 
o	4 calls per minute per scope
o	20 calls per minute per tenant
o	2000 calls per minute per ClientType

PS: If no ClientType is provided in the header, the 2000 calls are shared with ALL customers that have ClientType set to empty.
The recommendation here is to provide one unique “ClientType” value for all your calls in the request header.

In the case of 429, please look for the below response headers. They will tell you how long to wait before making the next call.
•	x-ms-ratelimit-microsoft.costmanagement-qpu-retry-after
•	x-ms-ratelimit-microsoft.costmanagement-entity-retry-after
•	x-ms-ratelimit-microsoft.costmanagement-tenant-retry-after
•	x-ms-ratelimit-microsoft.costmanagement-client-retry-after

Hope this answers. If you have any follow-up questions, please feel free to reopen this issue.

**Comment by ImMin5** [comment]
@navba-MSFT 
Thank you for your detailed reply.
That was what i want to know exactly.

But could you take a look one more time?

Following your recommendation, I implemented the inclusion of 'ClientType' in the headers for my requests. However, I encountered a challenge where the request quota was consumed in its entirety, including the entity, tenant, and client quotas. Consequently, I am still experiencing the 429 'too many errors' responses.

I was wondering if there is a possibility to exclusively consume the client quota for my requests?

**Comment by navba-MSFT** [comment]
@ImMin5 Thanks for getting back. This would now require a closer troubleshooting. Could you please open a support ticket with Microsoft support ? so that we can troubleshoot this issue by looking at the backend logs and assist you better.

**Comment by ImMin5** [comment]
@navba-MSFT 
Thank you for your kindness reply.

**Comment by pdecat** [comment]
Hi, found some really interesting information in this issue!

Is there an API to query current Cost Management API quotas without consuming them?

Also, how does one specify `ClientType` using the [Python SDK](https://github.com/Azure/azure-sdk-for-python)?

**Comment by toyama0919** [comment]
@pdecat 
> Never mind, it is as simple as passing a headers dict to the client's constructor.

How did you achieve this?

**Comment by pdecat** [comment]
Hi @toyama0919, here's an example with the python SDK:

```
        # Pass ClientType header to avoid sharing quotas with all customers,
        costmanagement_client = CostManagementClient(
            credentials,
            headers={
                "ClientType": "my-custom-client-type",
            },
            logging_enable=True,
        )
```

**Comment by toyama0919** [comment]
@pdecat 
Thanks! I'll  try.

**Comment by toyama0919** [comment]
@pdecat 
My problem is solved! Thank you.

**Comment by michaelschuett-tomtom** [comment]
> [@ImMin5](https://github.com/ImMin5) Apologies for the late reply. Thanks for reaching out to us and reporting this issue.
> 
> We are working on proper documentation for all scenarios, but to unblock you now, here are the numbers:
> 
> • **ARM rate limit:** 100 calls per 5 minutes • **Qpu limits**: [https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/manage-automation#data-latency-and-rate-limits](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fcost-management-billing%2Fcosts%2Fmanage-automation%23data-latency-and-rate-limits&data=05%7C01%7Cnavba%40microsoft.com%7Cf0e730822c5b4c80d4ca08db6e3d1738%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638224980916364145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QUwyEOqZJKydSHWyBKzsMRW4Y0FIMpOebb5zpDuya1E%3D&reserved=0)
> 
> **Internal limits** o 4 calls per minute per scope o 20 calls per minute per tenant o 2000 calls per minute per ClientType
> 
> PS: If no ClientType is provided in the header, the 2000 calls are shared with ALL customers that have ClientType set to empty. The recommendation here is to provide one unique “ClientType” value for all your calls in the request header.
> 
> In the case of 429, please look for the below response headers. They will tell you how long to wait before making the next call. • x-ms-ratelimit-microsoft.costmanagement-qpu-retry-after • x-ms-ratelimit-microsoft.costmanagement-entity-retry-after • x-ms-ratelimit-microsoft.costmanagement-tenant-retry-after • x-ms-ratelimit-microsoft.costmanagement-client-retry-after
> 
> Hope this answers. If you have any follow-up questions, please feel free to reopen this issue.

I came across this and can't find your 2000 calls per client type global bucket on any azure document. I ask because you know the caller and tenant id of every request so it would seem almost insane to have a 2000 req/min GLOBAL limit per ClientType.
