### ISSUE TITLE
Listing databricks workspaces from a subscription doesnt work: list_by_subscription() in azure-mgmt-databricks crashes whereas list_dy_resource_group works.

### ISSUE THREAD

**Issue by anogues** [Azure/azure-rest-api-specs#24413]
- azure-mgmt-databricks
- 1.0.0 but it happens also with the beta versions (also msrest 0.7.1 but tried with 0.6.9 as well and same issue)
- Windows
- 3.11

**Describe the bug**
When trying to list workspaces by subscription it returns the iterator but upon iterating the results it crashes with the following error:

>>> dbr_client.workspaces.list_by_subscription()
<iterator object azure.core.paging.ItemPaged at 0x1bef2f4aa10>
>>> for i, r in enumerate(dbr_client.workspaces.list_by_subscription()):
...     print(r)
...
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 128, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\core\paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\azure\mgmt\databricks\operations\_workspaces_operations.py", line 597, in extract_data
    deserialized = self._deserialize('WorkspaceListResult', pipeline_response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1454, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Python\Lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1436, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\msrest\serialization.py", line 1180, in rest_key_extractor
    return working_data.get(key)
           ^^^^^^^^^^^^^^^^
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'", AttributeError("'list' object has no attribute 'get'"))

**To Reproduce**
1. Create a piece of code with the folowing:
credential = DefaultAzureCredential(exclude_shared_token_cache_credential=True, exclude_interactive_browser_credential=False, exclude_visual_studio_code_credential=True)
 dbr_client = DatabricksClient(credential, yourSubscriptionIdHere)
 dbr_client.workspaces.list_by_subscription()

The function to return by resource group works fine:

 dbr_client.workspaces.list_by_resource_group("XXXXXXXXXXX")
<iterator object azure.core.paging.ItemPaged at 0x23919f1ff90>
>>> dbr_client.workspaces.list_by_resource_group("XXXXXXXXXXXXXX").__dict__
{'_args': (<function WorkspacesOperations.list_by_resource_group.<locals>.get_next at 0x000002391AD627A0>, <function WorkspacesOperations.list_by_resource_group.<locals>.extract_data at 0x000002391AD62840>), '_kwargs': {}, '_page_iterator': None, '_page_iterator_class': <class 'azure.core.paging.PageIterator'>}

but the subscription altough it returns the iterator something doesnt work well when you iterate over it
>>> dbr_client.workspaces.list_by_subscription().__dict__
{'_args': (<function WorkspacesOperations.list_by_subscription.<locals>.get_next at 0x000002391AD62840>, <function WorkspacesOperations.list_by_subscription.<locals>.extract_data at 0x000002391AD62980>), '_kwargs': {}, '_page_iterator': None, '_page_iterator_class': <class 'azure.core.paging.PageIterator'>}

**Expected behavior**
In the past (like 6 months ago) it worked and returned an object with all the databricks workspaces in a subscription

**Additional context**
Since its not working you need to resort to the api. The api call returns the data fine so i assue its a problem on how its handled the return of the api call. Currently y had to switch to the following:

    url = 'https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Databricks/workspaces?api-version=2023-02-01'.format(subscriptionId=subscriptions[subscription])
    headers = {'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + tokenDefault
        }
    response = requests.get(url=url,headers = headers)    
    d = json.loads(response.text)
    for wks in d:
        print(wks['properties']['workspaceUrl'])

**Comment by anogues** [comment]
@msyyc Thanks for your analysis.

The strange thing is that i've checked and this was working fine till two weeks ago. I have some jobs that started cvrashing by then, so not sure what could have happened? Some regression? But i dont see any new library being updated neither the api endpoint is still the old one...

**Comment by weidongxu-microsoft** [comment]
Same/similar issue on Java SDK https://github.com/Azure/azure-sdk-for-java/issues/35198

From customer report on above issue, it seems some tenant works, some tenant not (response is array)...

**Comment by navba-MSFT** [comment]
Removing CXP attention label from this.

**Comment by anogues-danone** [comment]
Yes, it seems the same thanks. Please let us know once solved.

BR,
Albert

**Comment by anogues-danone** [comment]
> 

Hello @msyyc 

I can't download, link throws 404.

Can you give me the right one so I can try?

BR;
Albert

**Comment by msyyc** [comment]
please try this link:  [azure_mgmt_databricks-1.0.0b1-py3-none-any.whl](https://newstorageyyc.blob.core.windows.net/2023-06/sdk_pr_30768/azure_mgmt_databricks-1.0.0b1-py3-none-any.whl)
nit: Client name is changed from `DatabricksClient` to `AzureDatabricksManagementClient`

**Comment by anogues-danone** [comment]
Hello @msyyc 

I confirm it works now.

BR,
Albert
