### ISSUE TITLE
openapi-pipeline-app / SDK azure-powershell check failing since April 2023

### ISSUE THREAD

**Issue by jijohn14** [Azure/azure-rest-api-specs#24445]
Sample PRs with check failure:
- https://github.com/Azure/azure-rest-api-specs/pull/24399/checks?check_run_id=14265695115
- https://github.com/Azure/azure-rest-api-specs/pull/24426/checks?check_run_id=14240365442

Error logs show below  details:

error	Fatal error: SSL error: syscall failure: Broken pipe
error	The following packages are still pending:
error		Az.app.DefaultTag

**Comment by JackTn** [comment]
@jijohn14 the pipeline issue need resolved by azure-sdk-tools, I has created new on https://github.com/Azure/azure-sdk-tools/issues/6351 and close this issue. Pls follow that issue, thanks
