### ISSUE TITLE
[OpenAI.Inference] Fix java emission

### ISSUE THREAD

**Issue by glecaros** [Azure/azure-rest-api-specs#24497]
This issue tracks reenabling java emission that was disabled to unblock merging #24382

**Comment by jpalvarezl** [comment]
I've opened a [PR](https://github.com/Azure/azure-rest-api-specs/issues/24497) in the `azure-sdk-for-java` repo running code gen against the commit hash added for the Dall-e changes. We are still identifying what could be the causes that make the CI to fail, but preliminarily I identified the following:
- `LRO`s introduced the usage of `Azure.Core.experimental`  API. I am specifically talking about [PollResult](https://github.com/Azure/azure-sdk-for-java/pull/35549/files#diff-ecfcbaef21e9bc3878272dbf8e46da30de1ce4b991418e6b86af1f1cbf43fe2fR27) . 
- The import for the project is not able to resolve the `experimental` package. It appears to be related to how the `module-info.java` file is [setup](https://github.com/Azure/azure-sdk-for-java/pull/35549/files#diff-c28ff5e89263f5776096206a2ec05837c20f87f3b53ca39ebf8bbafe62377b11)
