### ISSUE TITLE
Price Sheet GET (REST API) has started returning SKUs for only Low Priority VMs

### ISSUE THREAD

**Issue by jagan-at-sl** [Azure/azure-rest-api-specs#24491]
This REST API call in Python3:
test_api_url = f'https://management.azure.com/subscriptions/{subscription_id}/providers/Microsoft.Consumption/pricesheets/default?api-version=2020-01-01-preview'

used to return SKUs that included regular VMs.  In the last couple of weeks, it has started returning SKUs for VMs that are always low-priority.  

```
    {
      "currencyCode": "USD",
      "tierMinimumUnits": 0.0,
      "retailPrice": 0.0096,
      "unitPrice": 0.0096,
      "armRegionName": "italynorth",
      "location": "IT North",
      "effectiveStartDate": "2023-06-27T00:00:00Z",
      "meterId": "02978600-31b9-55a9-9605-0ed935dcf4be",
      ---> "meterName": "B2s Low Priority",
      "productId": "DZH318Z0BQNH",
      "skuId": "DZH318Z0BQNH/02FV",
      ---> "productName": "Virtual Machines BS Series Windows",
      ---> "skuName": "B2s Low Priority",
      "serviceName": "Virtual Machines",
      "serviceId": "DZH313Z7MMC8",
      "serviceFamily": "Compute",
      "unitOfMeasure": "1 Hour",
      "type": "DevTestConsumption",
      "isPrimaryMeterRegion": true,
      "armSkuName
      ": "Standard_B2s"
    },
```

Seems like some sort of error in the implementation due to some recent change that, if true, needs to be fixed ASAP

**Comment by navba-MSFT** [comment]
@jagan-at-sl Thanks for reaching out to us and reporting this issue. I see that you are using an older api-version. Could you please use the `api-version` 2023-03-01 and check the behavior ? Awaiting your reply.

**Comment by jagan-at-sl** [comment]
This is what I get:
{"error":{"code":"404","message":"Cost management data is not supported for subscription(s) xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx in the provided api-version. Please use api-version 2019-10-01 or later. (Request ID: 70b565e1-4590-4b8b-acd4-3c028c6966a1)"}}

**Comment by jagan-at-sl** [comment]
Some additional details that may be helpful:
[Azure-Support-Request.txt](https://github.com/Azure/azure-rest-api-specs/files/11786439/Azure-Support-Request.txt)

**Comment by navba-MSFT** [comment]
@jagan-at-sl Thanks for getting back and sharing the details. I need to gather some details about this issue.  Please send me an email navba [ @ ] microsoft . (dot) com.

**Comment by navba-MSFT** [comment]
@jagan-at-sl I hope we have been able to address your queries internally over email. It was pleasure working with you. If you need any further assistance on this issue in future, please reach out to us and we would be happy to help.

**Comment by jagan-at-sl** [comment]
Thanks Naveen, you have been very helpful.

Jagan
