### ISSUE TITLE
Security Error Channeled Through HTTP 200 

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#245]
# Security Error Channeled Through HTTP 200

Security Principal Operation Error is channeled through HTTP 200 - See [`Collection.addUser()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L1305) in Remote App Swagger spec.

```
      "200": {
        "description": "",
        "schema": {
          "$ref": "#/definitions/SecurityPrincipalOperationErrorDetails"
        }
```

Is this intentional?

**Comment by yungezz** [comment]
HI @calexan could you pls provide a update?

**Comment by yungezz** [comment]
close since no response for years.
