### ISSUE TITLE
Microsoft.Compute/virtualMachines/{vmName} does not return SecurityProfile

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-rest-api-specs#24660]
Hi
it seems https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}?api-version=2023-03-01 does not always properly return the SecurityProfile.

Example:
After creating a VM via ARM (no encryption at host set in arm template)

1) SecurityProfile is not returned
```
[...]
no securityProfile at all
[...]
```

2) Turning encryption at host on for that VM it now returns:
```
[...]
    "securityProfile": {
      "encryptionAtHost": true
    },
[...]
```

Same VM with encryptionAtHost turning it off again:

```
[...]
    "securityProfile": {
      "encryptionAtHost": false
    },
[...]
```

I would expect this to be returning always like this:
```
[...]
    "securityProfile": {
      "encryptionAtHost": true/false,
      "securityType": ...,
      "uefiSettings": ...
    },
[...]
```

**Comment by Klaas-** [comment]
References https://github.com/ansible-collections/azure/pull/1205

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by hilaryw29** [comment]
@TravisCragg-MSFT would you mind taking a look at this? Thanks!

**Comment by TravisCragg-MSFT** [comment]
@Klaas- This is by design, and in line with most non-critical VM properties.If you are looking to check it programmatically, check if it exists first. 

If you would like us to change this functionality in the future, [please leave your feedback Here](https://feedback.azure.com/d365community/forum/ec2f1827-be25-ec11-b6e6-000d3a4f0f1c).

**Comment by Klaas-** [comment]
@TravisCragg-MSFT I think you misunderstood what I tried to say, from the current specification I would expect them to be always returned: https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/get?tabs=HTTP&tryIt=true&source=docs#securityprofile for some other properties it says optional, those I would not expect to be always returned.

**Comment by Klaas-** [comment]
So I am guessing if you want to keep it this way you should say in specs which are not always returned :)

**Comment by TravisCragg-MSFT** [comment]
@Klaas- We do not state which properties are optional and which are always returned on the VM model. Only a small subset would be considered mandatory, and we do not document those. There are also many that have co-dependencies on other properties. 

The only optional properties we state on that doc are sub-properties, and I agree that is inconsistent.
