### ISSUE TITLE
support OpenAI GPT 0613 function calling spec

### ISSUE THREAD

**Issue by nicholasgibson2** [Azure/azure-rest-api-specs#24719]
The [latest available Azure OpenAI API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-06-01-preview/inference.json) does not support the [function calling](https://openai.com/blog/function-calling-and-other-api-updates) feature released for GPT 0613. ([Stackoverflow discussion](https://stackoverflow.com/questions/76543136/how-to-do-function-calling-using-azure-openai))

**Comment by apthagowda97** [comment]
Any update on when it is releasing?

**Comment by terrysGp** [comment]
When will it be updated？

**Comment by nicholasgibson2** [comment]
Resolved by https://github.com/Azure/azure-rest-api-specs/pull/24534

**Comment by stjean2016** [comment]
> Resolved by #24534
Does it work for you? I tried it (function calling request) by rest api in Postman with api-version=2023-07-01-preview and still get the same error message: "Unrecognized request argument supplied: functions".

**Comment by nicholasgibson2** [comment]
@stjean2016 doesn’t work for me yet, I’m assuming there’s a delay between merging to main and releasing the updated API .
