### ISSUE TITLE
[TypeSpec Validation] Add rule to ensure specs match file and folder structure guidelines

### ISSUE THREAD

**Issue by raych1** [Azure/azure-rest-api-specs#24984]
We are missing the validation on the path requirement for typespec specs. for example, management plane type specs should be put under the folder of `xxx.Management`. `Management` word should be capitalized. 

This is an example [rp spec](https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/whiteboxcadlprovider) checked in without following the guidance.

The rule in TypeSpecValidation should verify everything documented here: https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/typespec-structure-guidelines.md

Another example is the top-level folder under `specification` should be lower-case.  Example violation here: https://github.com/Azure/azure-rest-api-specs-pr/pull/13680#pullrequestreview-1566328115

**Comment by mikeharder** [comment]
Please fix #24983 before this issue
