### ISSUE TITLE
Delete Redis Cache Returns Abnormal 404

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#250]
# Delete Redis Cache Returns Abnormal 404

Delete a Redis Cache [returns an abnormal 404](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-redis/2015-08-01/swagger/redis.json#L127). In this case, developers will not be able to differentiate request accepted vs. resource was not found. When a resource is not found, an exception will not be thrown.

```
    "responses": {
      "200": {
        "description": ""
      },
      "202": {
        "description": ""
      },
      "404": {
        "description": ""
      }
    }
```

If a method encounters an abnormal condition that it cannot handle, it should throw an exception. If a method is throwing an exception for an abnormal condition that we feel that developers should consciously decide how to handle, then throw a checked exception in a client library with sufficient information. A client library cannot through an exception if a method does not thrown an exception.

Is this 404 definition intentional?

**Comment by devigned** [comment]
In some situations a 404 might be considered ok. Perhaps, on a delete or a get, one would not expect an exception on a 404. Though, it would be good to understand that this by design.

For example, HttpClient will not throw on a 404 by default.

**Comment by selvasingh** [comment]
Most common expectation: throws a language-specific exception when an error response is returned by Azure Redis Cache indicating either a problem with the data in the request or a server side issue.

**Comment by kirthik** [comment]
404 is removed in new api version - https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L177
