### ISSUE TITLE
[TypeSpec Validation] Make scripts work on pwsh 7.2 and 7.3

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#25022]
I believe one or both of the powershell scripts in TypeSpecValidation only work on pwsh 7.2, due to a breaking change in 7.3.  While 7.2 is LTS, many systems auto-upgrade to 7.3, so I think we need to start ensuring our scripts work on both versions.

See the links from this comment for guidance on making scripts work in both versions:

https://github.com/PowerShell/PowerShell/issues/18694#issuecomment-1654566209

**Comment by Scordo** [comment]
We use somehting like that for executables like msbuild where we had to use ``` "`"xyz`"" ``` to pass quotes:

```powershell
function Use-LegacyNativeCommandArgumentPassing {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$true)]
    [scriptblock]
    $Script
  )

  if (!(test-path variable:PSNativeCommandArgumentPassing)) {
    & $Script
    return
  }

  $oldPSNativeCommandArgumentPassing = $PSNativeCommandArgumentPassing

  try {
    $Global:PSNativeCommandArgumentPassing = 'Legacy'
    & $Script
  }
  finally {
    $Global:PSNativeCommandArgumentPassing = $oldPSNativeCommandArgumentPassing
  }
}

Use-LegacyNativeCommandArgumentPassing {
      & $msbuildExecutablePath $msBuildParameters
}

```

Maybe this is of some help for you.
