### ISSUE TITLE
Service Fabric Swagger Spec Does Not Define Errors 

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#251]
# Service Fabric Swagger Spec Does Not Define Errors

[Service Fabric Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/8222f850a8e1b4e869e577b020cb6ac9da59f7f3/servicefabric/2016-01-28/swagger/servicefabric.json) does not define any errors.

However, [Service Fabric REST API](https://msdn.microsoft.com/en-us/library/azure/dn707642.aspx) throws many exceptions.

**Comment by devigned** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/566
