### ISSUE TITLE
[TypeSpec Validation] Add rule to require all new specs use TypeSpec

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#25138]
The key question is, what is the definition of a "new spec"?  Is it as simple as this?

> A "new spec" is any new folder under `data-plane` or `resource-manager`, GA or preview, that contains a swagger file without the `x-typespec-generated` flag.

The definition we agreed on may be slightly less strict:

> A "new service" is a service that does not yet have an API version in a "stable" folder in the main branch of the public repo

Also add mechanism to suppress rules per spec.

Options:
- Align with https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/828/How-to-suppress-validation-rules
- Create a new file like `tsvconfig.yaml`

**Comment by mikeharder** [comment]
CC: @rkmanda

**Comment by konrad-jamrozik** [comment]
Relevant [Teams thread](https://teams.microsoft.com/l/message/19:2250b04ad1ad4bc3a25ad9760881fef0@thread.tacv2/1691021583809?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0cab4ce9-7691-42ae-82e3-460d4346a710&parentMessageId=1691021583809&teamName=ARM%20API%20Reviewers&channelName=RPC%20governance%20-%20Azure%20SDK%20bridge&createdTime=1691021583809).
