### ISSUE TITLE
Missing Error Definitions or References in 9 Swagger Specs 

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#252]
# Missing Error Definitions or References in 9 Swagger Specs
- [Data Lake Catalog](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/catalog/2015-10-01-preview/swagger/catalog.json)
- [DNS](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-dns/2015-05-04-preview/swagger/dns.json)
- [Graph RBAC](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-graphrbac/1.6-internal/swagger/graphrbac.json)
- [Logic](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-logic/2015-02-01-preview/swagger/logic.json)
- [Notification Hubs](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json)
- [Resources Features](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/features/2015-12-01/swagger/features.json)
- [Resources Lock](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json)
- [Search](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-search/2015-02-28/swagger/search.json)
- [Service Fabric](https://github.com/Azure/azure-rest-api-specs/blob/8222f850a8e1b4e869e577b020cb6ac9da59f7f3/servicefabric/2016-01-28/swagger/servicefabric.json)

[Notification Hubs REST API](https://msdn.microsoft.com/en-us/library/azure/dn223269.aspx) throws several error codes however its Swagger does not define any of these.

[Search REST API](https://msdn.microsoft.com/en-us/library/azure/dn798925.aspx) throws several error codes however its Swagger does not define any of these.

[Azure Active Directory Graph API](https://msdn.microsoft.com/library/azure/ad/graph/howto/azure-ad-graph-api-error-codes-and-error-handling) throws several error codes however its Swagger does not define any of these.

So on and on ...

**Comment by devigned** [comment]
Which error codes are you referring to? Please be specific or the issues will be long lived and difficult to determine if they are completely resolved.

**Comment by selvasingh** [comment]
@devigned - if you go to their corresponding REST API specs, then you can see it. I provided some examples in the first comment

**Comment by devigned** [comment]
@Azure/adx-autorest-contributors and @Azure/openapi-advisors any thoughts on this issue?

**Comment by brjohnstmsft** [comment]
@devigned Two thoughts, one specific to Search, one general:

1. The Search Swagger specs are not what I would call "production-ready" yet. We have an issue open to decide what to do about this: https://github.com/Azure/azure-rest-api-specs/issues/195  It would be great to close on it so we can be omitted from these sweeps until we are ready.
2. From a codegen standpoint, would adding the additional error codes change anything? For example, in C#, AutoRest basically assumes that success means return a response, while failure means throw a `CloudException`. I'm confident we have already captured all the success cases in the Search specs. Other than for documentation purposes, is there any value in explicitly enumerating all the possible failure cases in the specs?

**Comment by devigned** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/566 <-- to help follow 3.0 suggestions

**Comment by devigned** [comment]
We should have a shared (common) set of schema, a base error should be returned by default (non-success responses) specialized by the error code via a polymorphic discriminator. This will provide the information to specialize the initialized class as well as the to document all of the possible error responses.

**Comment by kirthik** [comment]
Closing since this is being tracked here - https://github.com/Azure/autorest/issues/1523.
