### ISSUE TITLE
Broken link in Getting started with OpenAPI specifications content

### ISSUE THREAD

**Issue by strefethen** [Azure/azure-rest-api-specs#25243]
Steps
1. Browse [here](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/Getting%20started%20with%20OpenAPI%20specifications.md)
2. Click "Azure REST API guidelines"

Results in 404.

I believe the proper link is [here](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md).

**Comment by navba-MSFT** [comment]
@strefethen Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
