### ISSUE TITLE
Unable to get resources details, associated with Azure Data Collection Rule using data_collection_rule_associations.get()

### ISSUE THREAD

**Issue by raviguhcl** [Azure/azure-rest-api-specs#25261]
Hi, I am trying to get list of resources associated with a DCR (Data Collection Rule) using following module but unable to get the required details.
MonitorManagementClient(credential, subscription_id, api_version="2022-06-01")
_Package Name: azure-mgmt-monitor
Package Version: 6.0.1
Operating System: Windows
Python Version: 3.10.7_

Appreciate, if someone could help me to understand the correct way.

_FYI: I am not expert in Python, so need help !!_

Explored :

data_collection_rules.get(RG Name, DCR Name) - Returns DCR configuration without any details of Associated Resources.

data_collection_rule_associations.get(DCR uri, association_name) - DCR uri is ok but don't know, how to get Association name for respective DCR

Tried with static values (by collecting Association name using powershell) but throwing error as:

data_collection_rule_associations.get(/subscriptions/<SubscriptionID>/resourceGroups/<RGName>/providers/Microsoft.Insights/dataCollectionRules/<DCR Name>, assoc-sjxkjcrpc4d6j)

_"Message: Association cannot be created for resource of type 'Microsoft.Insights/dataCollectionRules'. Supported types are: Microsoft.AzureStackHCI/virtualmachines,Microsoft.AzureStackHCI/clusters,Microsoft.Compute/virtualMachineScaleSets,Microsoft.Cache/redis,Microsoft.Compute/virtualMachines,......"_

_FYI: URL followed for PowerShell Cmdlet https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azdatacollectionruleassociation?view=azps-10.2.0#example-2-get-data-collection-rules-associations-by-rule-(dcr)_

Any pointer would be highly appreciated.

Ravi

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by raviguhcl** [comment]
Appreciate, if someone could help me with any pointer towards right direction or may be anything I might have missed.

**Comment by raviguhcl** [comment]
> Adding Service team to look into this.

Hi team, Appreciate, if you could help me to understand, if this is possible with any present module or not?
if yes, could you please let me know the module name?

any response would be highly appreciated !!

Regards, Ravi

**Comment by raviguhcl** [comment]
Hi @navba-MSFT / @JackTn 

Kindly update, if someone is looking into this issue?

**Comment by raviguhcl** [comment]
I got, how to extract the required details.

**Comment by navba-MSFT** [comment]
@raviguhcl Thanks for getting back and sharing the update. We will now proceed with closure of this GitHub issue.
