### ISSUE TITLE
Microsoft.Resources swaggers including invalid characters

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-rest-api-specs#25309]
Reference article [here](https://learn.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2020_10_01.operations.resourcegroupsoperations?view=azure-python#azure-mgmt-resource-resources-v2020-10-01-operations-resourcegroupsoperations-list) shows in a way not expected like:
![image](https://github.com/Azure/azure-rest-api-specs/assets/119990644/982ab766-5f80-4acc-aae7-11474702b34f)
And it's possibly caused by the characters `<br><br>`  included in the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2725).
![image](https://github.com/Azure/azure-rest-api-specs/assets/119990644/517c7f2c-d279-4286-89e2-9aba6cba2b76)
To make the page shows normally, could the swaggers and docs updated to delete these characters?

Same problem also exists in the links shown below and following versions of the swagger:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2877
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2725
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2386

To get original issue report:
https://github.com/Azure/azure-sdk-for-python/issues/31647

**Comment by navba-MSFT** [comment]
@ChenxiJiang333 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
