### ISSUE TITLE
kubeConfig should have "format": "byte" along with "type": "string"

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#2546]
If `"format": "byte"` is specified then the generated code will be able to serialize and deserialize this property [kubeconfig](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservices/resource-manager/Microsoft.ContainerService/stable/2017-08-31/managedClusters.json#L917) correctly.

As per swagger specification, [this](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) is the recommended way of describing base64 encoded characters.

@mboersma - Please make sure to fix this.
/cc @milismsft

**Comment by lmazuel** [comment]
@mboersma I was looking at CLI, and it seems this will just change this:
```python
        encoded_kubeconfig = access_profile.kube_config
        kubeconfig = base64.b64decode(encoded_kubeconfig).decode(encoding='UTF-8')
```
to this:
```
        kubeconfig = access_profile.kube_config.decode(encoding='UTF-8')
```
while at the same time providing free base64 decoding for SDK customers

**Comment by milismsft** [comment]
FYI I would prefer if this change is done as part of a new API version rather than using the same version as it was done not to far in the past for other "non-breaking" changes (see access profiles)... Especially since it's not blocking and can be easily worked around in the SDKs for now.

**Comment by mboersma** [comment]
This does seem like an obvious improvement. 

@milismsft I've encountered a lot of resistance when proposing we rev the AKS API version before, and in this case we're not even changing server-side code. If it's possible to inline such a change into `v20170831`, that may be the only way to accomplish this in a reasonable time frame.

**Comment by amarzavery** [comment]
@mboersma - I have already made this change in the node sdk over [here](https://github.com/amarzavery/azure-sdk-for-node/commit/ee97ff2f7c8e2e64b76d8928ad39994f18740766#diff-0a74c6a77b8831b901bdc04ea6390e13R93) and [published](https://www.npmjs.com/package/azure-arm-containerservice) the sdk. This was easier than adding a layer on top that would do the right thing.
