### ISSUE TITLE
16 Similar Error Definitions with Same & Different Names in Swagger Specs

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#255]
#16 Similar Error Definitions with Same & Different Names in Swagger Specs

There are several similar error definitions across Azure Swagger specs with same & different names.

In languages like Java and C#, similar error definitions with same & different names generate similar, multiple exception class definitions with same & different names in different name spaces.

Azure libraries for Java and other such languages carry a large surface area. A major part of API ergonomics is consistent naming themes, uniform definition of errors, uniform error handling, etc. Consistency makes it easier to use and memorize and also enables portability of learning. Having learnt a part of the library, developers can apply that learning across other parts of the libraries.

In Swagger specifications, designers should avoid duplicate definition of errors with same or different names. This, in turn, helps language-specific client library generators to choose an already existing exception class for each kind of abnormal condition that may cause an operation to thrown an error; define new exception classes, if needed.

The table below describes the current state - 16 similar error definitions with different names. These definitions can be represented with a single base error definition that comprises of `{code, message, source-of-error, description, details}` and Swagger specs MAY extend the definition to differentiate or pack additional info.

<table>
  <tr>
    <th>#</th>
    <th>Service</th>
    <th>Error</th>
    <th>Code</th>
    <th>Message</th>
    <th>Source-of-error</th>
    <th>Description</th>
    <th>Details</th>
    <th>Additional-info</th>
  </tr>
  <tr>
    <td>1</td>
    <td>CDN</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-cdn/2015-06-01/swagger/cdn.json#L2405">ErrorResponse</a> </td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>2</td>
    <td>Compute</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L4436">ApiError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>3</td>
    <td>Data Lake Analytics Account</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/account/2015-10-01-preview/swagger/account.json#L1569">Error</a></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>4</td>
    <td>Data Lake Job</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-analytics/job/2015-11-01-preview/swagger/job.json#L719">Job Error Details</a></td>
    <td></td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Plenty of info</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Data Lake Store Account</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-store/account/2015-10-01-preview/swagger/account.json#L866">Error</a></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
  </tr>
  <tr>
    <td>6</td>
    <td>Intune</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-intune/2015-01-14-preview/swagger/intune.json#L1767">Error</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>7</td>
    <td>Mobile Management</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-mobileengagement/2014-12-01/swagger/mobile-engagement.json#L1704">ApiError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>8</td>
    <td>Network</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L7265">Error</a></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>9</td>
    <td>Resources - Resources</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L2260">ResourceManagementErrorWithDetails</a></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td></td>
  </tr>
    <tr>
    <td>10</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L9793">DeleteCertificateError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>11</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L10759">JobSchedulingError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>12</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L11011">TaskSchedulingError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>13</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L11177">AutoScaleRunError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>14</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L11216">ResizeError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>15</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L12175">ComputeNodeError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <td>16</td>
    <td>Batch</td>
    <td><a href="https://github.com/Azure/azure-rest-api-specs/blob/44d9fc96a85ca02b701200a5a7d57268d81ac3ef/batch/2016-02-01.3.0/swagger/BatchService.json#L12723">BatchError</a></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
</table>

**Comment by brjohnstmsft** [comment]
> These definitions can be represented with a single base error definition that comprises of  {code, message, source-of-error, description, details}  and Swagger specs MAY extend the definition to differentiate or pack additional info.

@selvasingh: Bruce from the Search team here. The only commonality the type `ItemError` has with the others is an error message. Why would we change it to inherit from a type that has far more properties? That seems to go against the goal of making the Swagger spec accurately model the REST API.

FYI @chaosrealm @devigned

**Comment by selvasingh** [comment]
@brjohnstmsft BTW, there are two common items - message and description. Regardless, ItemError is different from other error definitions. So, removed it off the list

**Comment by devigned** [comment]
@Azure/adx-autorest-contributors and @Azure/openapi-advisors any thoughts on this issue?

**Comment by matthchr** [comment]
@selvasingh @devigned
I work on the Batch team, so addressing some of the error types which were listed above from the Azure Batch service swagger specification.

The Errors you listed are almost all errors in the body of entities rather than errors which generate exception types.  For example, the following errors _do not_ map onto exceptions:
1) DeleteCertificateError
2) JobSchedulingError
3) TaskSchedulingError
4) AutoScaleRunError
5) ResizeError
6) ComputeNodeError

These types are used because our service performs many operations asynchronously on behalf of the user and because the operation is not being performed in the context of a particular user API call, it doesn't make sense to propagate errors which occur as part of an asyncronous workflow as an exception. Thus they follow the `FooError` naming, but are not exceptions but are rather just properties.

The one that _does_ map onto an exception is: BatchError

I believe that the topic of a common Exception or Error base class for use across libraries has been discussed, and if such a thing were to exist (for example in the client runtimes of each language with a `code` and `message` field), then `BatchError` ought to inherit from that (or maybe just use the base if it matches exactly).

**Comment by kirthik** [comment]
Closing this since we are tracking it here - https://github.com/Azure/autorest/issues/1523
