### ISSUE TITLE
[TypeSpec Validation] Determine specs to validate by following imports

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#25544]
Currently, `Get-TypeSpec-Folders.ps1` validates all specs under folder `specification/foo`, when any file under this folder is changed.  This is required to handle cases where specs use shared files from other folders.  Specs are currently forbidden from importing files outside their top-level folder under `specification`, so this is a pretty good heuristic.

However, some folders are getting large enough this may be too course of a metric.  An example is `specification/cognitive`, as shown in this run:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3030757&view=logs&j=52599800-cfcd-5615-dd98-137d26e8cb9a&t=c0acbdc7-6ccc-5699-6c3a-c41428f73fe2&l=63

We might be able to improve `Get-TypeSpec-Folders.ps1` by trying to analyze code, like the imports in `*.ts` files, or the settings in `tsconfig.yaml`, to determine exactly which specs might be impacted by changed files.

**Comment by ckairen** [comment]
closing, dup of: https://github.com/Azure/azure-rest-api-specs-pr/issues/17683
