### ISSUE TITLE
[Monitor] The metricnamespace for the new metrics API is incorrectly specified as a client level parameter

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-rest-api-specs#2565]
The metricnamespace for the new metrics API is incorrectly specified as a client level parameter. It is only used in the multi-dimensional Metrics API. 

The argument must be specified as method level argument.

**Comment by dsgouda** [comment]
@gucalder please close this issue if it has been fixed.

**Comment by dsgouda** [comment]
@gucalder  please reopen if necessary
