### ISSUE TITLE
Create one alert for all the vms under the rg

### ISSUE THREAD

**Issue by ArthiSaravana** [Azure/azure-rest-api-specs#25654]
Need help in this:

Need to create this one alert for multiple vms. am able to create multiple alert for multiple vms. If a prd env has 70+ vms I cant create 70+ cpu ulitization alert in the sub. thats not a good practice even sub or rg has alert limitations. so, my requirement is how to select all the vms in a rg for a single alert.

resource alertRule 'Microsoft.Insights/scheduledQueryRules@2022-06-15' =  {
  name: 'alertname'
  location:  location
  properties: {
    enabled: true
    autoMitigate: false
    severity: 0
    evaluationFrequency:''
     scopes: [
      resourceId('Microsoft.Compute/virtualMachines', vm)
  ]
  targetResourceTypes: [
    'Microsoft.Compute/virtualMachines'
   ]
   windowSize: ''
   skipQueryValidation: false
   criteria: {
    allOf: [
      {
        query: ''
        timeAggregation: ''
        metricMeasureColumn: ''
        dimensions: [
          {
            name: ''
            operator: ''
            values: [
              *
            ]
          }
        ]
        resourceIdColumn: ''
        operator: ''
        threshold: 80
        failingPeriods: {
          numberOfEvaluationPeriods: 1
          minFailingPeriodsToAlert: 1
        }
      }
    ]
   }
   actions: {
    actionGroups: []
   }
  }
}

**Comment by navba-MSFT** [comment]
@ArthiSaravana Thanks for reaching out to us and reporting this issue. 

Azure Monitor supports monitoring multiple resources of the same type with a single metric alert rule, for resources that exist in the same Azure region. This feature is currently only supported in Azure public cloud and only for Virtual machines, SQL server databases, SQL server elastic pools and Azure Stack Edge devices. 

Dynamic Thresholds alerts rule can also help create tailored thresholds for hundreds of metric series (even different types) at a time, which results in fewer alert rules to manage.

This section will describe Azure Resource Manager templates for **three scenarios** to monitor multiple resources with a single rule.

- Monitoring all virtual machines (in one Azure region) in one or more resource groups.
- Monitoring all virtual machines (in one Azure region) in a subscription.
- Monitoring a list of virtual machines (in one Azure region) in a subscription.

Static Threshold sample JSON template and parameter file is available **[here](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/alerts/resource-manager-alerts-metric.md#static-threshold-alert-on-all-virtual-machines-in-one-or-more-resource-groups)**
Dynamic Threshold sample JSON template and parameter file is available [**here**.](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/alerts/resource-manager-alerts-metric.md#dynamic-thresholds-alert-on-all-virtual-machines-in-one-or-more-resource-groups)

Hope this helps.

**Comment by navba-MSFT** [comment]
@ArthiSaravana The action is pending on you to follow the above action plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
