### ISSUE TITLE
ApiManagement: Rename ResourceType api-version-sets to apiVersionSets

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-rest-api-specs#2570]
The Resource Type should be camel-cased and contain only Alphanumeric Characters.

https://github.com/Azure/azure-rest-api-specs/pull/2483#discussion_r168652097

**Comment by marstr** [comment]
Triaged and removing my assignment.

**Comment by solankisamir** [comment]
resource type has been updated in 2019-01-01 spec [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimapiversionsets.json#L37)
