### ISSUE TITLE
We are sorry, your Cognitive Services resource is unavailable.

### ISSUE THREAD

**Issue by mike-j-b** [Azure/azure-rest-api-specs#25834]
Unable to chat in the openai playground when I have added my own data. Getting then above error message in the health section of the openai resource

**Comment by navba-MSFT** [comment]
@mike-j-b Apologies for the late reply. Thanks for reaching out to us and reporting this issue. This seems like a transient issue. Could you please check and let us know if you are still seeing the same issue ? Awaiting your reply.
