### ISSUE TITLE
Feature request: API for management solutions

### ISSUE THREAD

**Issue by pixelicous** [Azure/azure-rest-api-specs#2598]
According to [this document](https://docs.microsoft.com/en-us/rest/api/loganalytics/) there are no exposed APIs

[Management solutions documentation](https://docs.microsoft.com/en-us/azure/operations-management-suite/operations-management-suite-solutions)

**Comment by joshgav** [comment]
@pixelicous Log Analytics is known as "OperationalInsights" in APIs and SDKs. Are the operations you seek available in https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights?

Go docs here: https://godoc.org/github.com/Azure/azure-sdk-for-go/services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights

cc @tombuildsstuff

**Comment by pixelicous** [comment]
thx @joshgav ill look into it
