### ISSUE TITLE
17 App Service Operations Return Abnormal 404 and 409 

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#261]
#17 App Service Operations Return Abnormal 404 and 409

Numerous Create, Delete, Update and Reboot operations in the App Service Swagger spec return abnormal 404 and 409. Developers will not be able to differentiate request succeeded OR accepted versus resource was not found OR there is a conflict. When a resource is not found or there is a conflict, an exception will not be thrown.

```
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "$ref": "#/definitions/Object"
        }
      },
      "202": {
        "description": "Operation is in progress",
        "schema": {
          "$ref": "#/definitions/Object"
        }
      },
      "400": {
        "description": "Bad request"
      },
      "404": {
        "description": "Not found"
      },
      "409": {
        "description": "Conflict"
      }
    },
```

If an operation encounters an abnormal condition that it cannot handle, it should throw an exception. If an operation is throwing an exception for an abnormal condition that we feel that developers should consciously decide how to handle, then throw a checked exception in a client library with sufficient information. A client library cannot through an exception if an operation does not define errors in Swagger.

Are these 404 and 409 definitions intentional?

Here is a SAMPLE list of those 404 and 409 occurrences -
- [`HostingEnvironments.createOrUpdateHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1809)
- [`HostingEnvironments.deleteHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1876)
- [`HostingEnvironments.rebootHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L2167)
- [`HostingEnvironments.createOrUpdateMultiRolePool()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3074)
- [`HostingEnvironments.createOrUpdateWorkerPool()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3299)
- [`ManagedHostingEnvironments.createOrUpdateManagedHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3818)
- [`ManagedHostingEnvironments.deleteManagedHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3879)

**Comment by devigned** [comment]
@Azure/adx-autorest-contributors and @Azure/openapi-advisors any thoughts on this issue?

**Comment by kirthik** [comment]
This is by design - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#negative-responses
