### ISSUE TITLE
Hybrid compute REST API - Child links for REST API reference are broken

### ISSUE THREAD

**Issue by sachinpanwar** [Azure/azure-rest-api-specs#26171]
The links are broken due to which we cannot check Hybrid compute rest API reference. 
![image](https://github.com/Azure/azure-rest-api-specs/assets/11601385/bbccf1c2-bde5-49b3-a905-b114ac3b5a96)

And from developer tool console, we can see this error. 
![image](https://github.com/Azure/azure-rest-api-specs/assets/11601385/16b87982-4d9c-4221-bc8c-9a6b7656095c)

---
#### Document Details

* Service: **azure-arc**
* Sub-service: **azure-arc-servers**
* Content: [Hybrid Compute](https://learn.microsoft.com/en-us/rest/api/hybridcompute/)

**Comment by JackTn** [comment]
@vedkale can you check on this issue, Thanks! Let me know if you have any question!

**Comment by sachinpanwar** [comment]
Checked again and could see that it is fixed.
