### ISSUE TITLE
[Monitor] Parameter "top" should be an int, not number

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#2655]
https://github.com/Azure/azure-rest-api-specs/blob/7924ec3d1bfb9576f2a04be97cab25147d119363/specification/monitor/resource-manager/microsoft.insights/stable/2018-01-01/metrics_API.json#L339-L340

This is registered as type "number" which gets interpreted by autorest as a float for generation of the Python SDK. If the SDK is used, even when an int is provided it gets serialized into a float and the service throws an error. 

cc/ @lmazuel

**Comment by lmazuel** [comment]
Merged
