### ISSUE TITLE
`ConfigurationAssignments_Get` returns HTTP 400 instead of 404 when the assignment is not existing

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#26565]
Once a maintenance has been assigned to a VM， GET on not existing assignments will be returned with HTTP 400 instead of HTTP 404

reproduce steps:
1. create a VM and two maintenance configs "assignment1" and "assignment2"
2. assign "A" to the VM ( indeed call `PUT https://management.azure.com/subscriptions/{my_sub_id}/resourceGroups/{rg_name}/providers/Microsoft.Compute/virtualMachines/{vm_name}/providers/Microsoft.Maintenance/configurationAssignments/assignment1`)
3. then GET "B" assignment (call `GET https://management.azure.com/subscriptions/{my_sub_id}/resourceGroups/{rg_name}/providers/Microsoft.Compute/virtualMachines/{vm_name}/providers/Microsoft.Maintenance/configurationAssignments/assignment2`)

the 3rd action will be returned with HTTP 400 "Invalid configurationAssignmentName: assignment2. Confirm api version."

**Comment by hilaryw29** [comment]
Looking into this, thanks!

**Comment by TravisCragg-MSFT** [comment]
@ziyeqf We understand that this response code is incorrect, but we will not be prioritizing the fix at this time. If this needs additional urgency, please let us know.
