### ISSUE TITLE
`OperationalInsights@2021-06-01-preivew` - `Clusters_update` is a LRO but the response has not defined HTTP 202

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-rest-api-specs#26678]
The operation [`Cluster_update`](https://github.com/Azure/azure-rest-api-specs/blob/78eac0bd58633028293cb1ec1709baa200bed9e2/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2021-06-01/Clusters.json#L286) is a long running operation and it will return HTTP 202, but it has not been defined in Swagger.

**Comment by JackTn** [comment]
@dulikvor can you help to see this issue, thanks!
