### ISSUE TITLE
`Microsoft.Compute/VirtualMachineScaleSets` `Microsoft.Network/loadBalancers` ETAGs / Conditional get/put are not defined in swagger. 

### ISSUE THREAD

**Issue by MartinForReal** [Azure/azure-rest-api-specs#26693]
ETAGs / Conditional get/put are not properly defined in swagger. 

support for etag header was not defined in swagger of compute/network service. 

With these config defined, etag support can be properly modeled in sdk. Could you please add more description for conditional get/update request? Thanks!

https://github.com/Azure/azure-rest-api-specs/blob/90a65cb3135d42438a381eb8bb5461a2b99b199f/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/virtualMachineScaleSet.json#L84

related issue: https://github.com/Azure/azure-sdk-for-go/issues/8917

**Comment by MartinForReal** [comment]
related : https://github.com/Azure/azure-sdk-for-go/issues/21056

**Comment by TravisCragg-MSFT** [comment]
@MartinForReal Thanks for your feedback! we are looking into this now

**Comment by hilaryw29** [comment]
Hi @MartinForReal

Etag should already be added for load balancer (and other networking) resources -- https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-06-01/loadBalancer.json

Networking does not define headers in swagger for specific resource. 

Etag for VMSS in GET/PUT/PATCH response with header support in PUT/PATCH calls is also now complete/rolling out -- #26368 

Please let us know if this addresses your ask, thanks!

**Comment by MartinForReal** [comment]
Hi @hilaryw29 , 
Thanks for the reply! I'm wondering if we can add definition of etag headers to swagger. Because sdk team may build model for these parameters and provide etag utils in sdk. For now, I have to create a client for each conditional request, in this way I can add extra header for the single request. But I don't think it is necessary.

**Comment by hilaryw29** [comment]
Hi @MartinForReal, support for etag header should now be available for VMSS/VM resources in the swagger. For load balancer support, the latest I've heard is that they do not define headers for specific resource in swagger. I don't know if there are any plans for them to provide support in the future.
 
Closing this as resolved for now from VMSS side but please feel free to re-open if any additional questions. Thanks!
