### ISSUE TITLE
[Compute] VirtualMachineScaleSet Example Issue

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-rest-api-specs#27029]
original issue: https://github.com/Azure/azure-sdk-for-python/issues/33268

example link: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSet_Create_WithPriorityMixPolicy.json

Properties `platformFaultDomainCount` and `networkApiVersion` under `networkProfile` are required when the `orchestrationMode` is set as `Flexible` but not included in this example.

It should include these properties like the snippet below:
```
"properties": {
    "orchestrationMode": "Flexible",
    "platformFaultDomainCount": 1,
    "priorityMixPolicy": {
      "baseRegularPriorityCount": 4,
      "regularPriorityPercentageAboveBase": 50
    }
    "virtualMachineProfile": {
      "networkProfile": {
        "networkApiVersion": "2020-11-01",
...
```

**Comment by hilaryw29** [comment]
Hi @ChenxiJiang333, thank you for raising this. We'll look through the VMSS examples and send out a PR to fix this. Thanks!

**Comment by hilaryw29** [comment]
Closing this issue as fix was created and is now merged into main. Thanks! cc: @aleclawlor
