### ISSUE TITLE
typespec-validation structure rule doesn't seem to detect if the main.tsp is in `resource-manger` folder

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/azure-rest-api-specs#27072]
From this PR https://github.com/Azure/azure-rest-api-specs-pr/pull/16294 which had a bad structure(existing) it wasn't complaing

`/specifications/provider/resource-manager/main.tsp` instead of 

`/specifications/provider/MyService.Management/main.tsp`

Guessing we can see the same problem with `data-plane` folder.

Maybe we need to just add some explicit check to make sure the typespec wasn't created under those. Problem is right now avocado will then complain that you have unreferenced examples because it think the typespec examples are mean to be referenced from a swagger file.

**Comment by mikeharder** [comment]
This should have been caught here:

https://github.com/Azure/azure-rest-api-specs/blob/8290f26b5a481b37c0e098593e475a9321a0cfe3/eng/tools/typespec-validation/src/rules/folder-structure.ts#L49-L56

Folder `resource-manager` should have failed our capitalization check.  But we must have a bug.  I will add a test and fix the bug.

**Comment by mikeharder** [comment]
Verified fixed:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3343503&view=logs&j=52599800-cfcd-5615-dd98-137d26e8cb9a&t=c0acbdc7-6ccc-5699-6c3a-c41428f73fe2&l=56
