### ISSUE TITLE
[Bug] VM extension `settings` property returned by `VirtualMachines.Get` is not Json Object

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-rest-api-specs#27146]
Originated from IcM: https://portal.microsofticm.com/imp/v3/incidents/incident/449703041/summary

API: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2020-12-01/compute.json#L3226

Response: 
```json
{
  "name": "KeyVaultForLinux",
  "id": "/subscriptions/REDACTED/resourceGroups/rg-xiaofei5/providers/Microsoft.Compute/virtualMachines/test2023122005/extensions/KeyVaultForLinux",
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "location": "eastus",
  "properties": {
    "autoUpgradeMinorVersion": true,
    "provisioningState": "Updating",
    "publisher": "Microsoft.Azure.KeyVault",
    "type": "KeyVaultForLinux",
    "typeHandlerVersion": "1.0",
    "settings": "secretsManagementSettings" // this is not Json
  }
}

```

This seems to contradict with the swagger definition: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2020-12-01/compute.json#L7774

```json
"settings": {
  "type": "object",
  "description": "Json formatted public settings for the extension."
}
```

This issue exists on latest 2023-07-01 as well.

**Comment by TravisCragg-MSFT** [comment]
Hi Xiaofei, to clarify - your issue is that this returns the 'secretsmanagementsettings' and not the JSON value of those setttings?

**Comment by TravisCragg-MSFT** [comment]
@XiaofeiCao Does this happen on other extensions outside of KeyVault? This seems like an encrypted version of the settings so keys are not in plaintext, which makes sense to me.

**Comment by XiaofeiCao** [comment]
> @XiaofeiCao Does this happen on other extensions outside of KeyVault? This seems like an encrypted version of the settings so keys are not in plaintext, which makes sense to me.

Yeah, I've only see this happening for KeyVault extension. The setting value is just "secretsManagementSettings"..

**Comment by GabstaMSFT** [comment]
@XiaofeiCao we are working on deploying a fix for this, will update this issue once the fix is rolled out.

**Comment by XiaofeiCao** [comment]
Hi @GabstaMSFT , seems the issue has already been fixed and rolled out :) 
May I know if it's the fix just for KeyVaultForLinux extension, or all extensions in general?

**Comment by GabstaMSFT** [comment]
@XiaofeiCao this was a platform fix and should be visible on all extensions.
