### ISSUE TITLE
DataMigration assigns a single discriminator value to multiple model types

### ISSUE THREAD

**Issue by daschult** [Azure/azure-rest-api-specs#2728]
The DataMigration TaskOutput discriminator values have duplicates on the following two lines:
https://github.com/Azure/azure-rest-api-specs/blob/cbe38334cd972faa38e96b55b24048b1550fc338/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-03-15-preview/definitions/MigrateSqlServerSqlDbTask.json#L309
https://github.com/Azure/azure-rest-api-specs/blob/cbe38334cd972faa38e96b55b24048b1550fc338/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-03-15-preview/definitions/MigrateSqlServerSqlMITask.json#L194
The model hierarchy looks like this right now:
```json
TaskOutput.MigrateSqlServerSqlDbTaskOutput.MigrateSqlServerSqlDbTaskOutputError: ErrorOutput
TaskOutput.MigrateSqlServerSqlMITaskOutput.MigrateSqlServerSqlMITaskOutputError: ErrorOutput
```
For a given discriminator name (such as `TaskOutput.MigrateSqlServerSqlDbTaskOutput.MigrateSqlServerSqlDbTaskOutputError`), all of the possible values (such as `ErrorOutput`) must be distinct.
Please change the discriminator values to `DbErrorOutput` and `MIErrorOutput`, or whatever values you prefer, as long as they are distinct.

**Comment by hitenjava** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/2760 created to fix this.

**Comment by hitenjava** [comment]
Fixed
