### ISSUE TITLE
Virtual Machine Scale Set VMs - List API does not return tags for "Orchestration mode: Flexible" Scale Sets

### ISSUE THREAD

**Issue by bgola-signalfx** [Azure/azure-rest-api-specs#27441]
The https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list API does not return tags for VMs when the flexible orchestration mode is used. For the uniform mode tags are returned properly.

Sample request:
`https://management.azure.com/subscriptions/5db89e2c-2127-4418-9a31-dac67b04e87b/resourceGroups/bgola-test-flexible_group/providers/Microsoft.Compute/virtualMachineScaleSets/bgola-test-flexible/virtualMachines?api-version=2023-09-01`

Sample response for the flexible mode:
```json
{
  "value": [
    {
      "name": "bgola-test-flexible_04945d5e",
      "id": "/subscriptions/5db89e2c-2127-4418-9a31-dac67b04e87b/resourceGroups/bgola-test-flexible_group/providers/Microsoft.Compute/virtualMachineScaleSets/bgola-test-flexible/virtualMachines/bgola-test-flexible_04945d5e",
      "type": "Microsoft.Compute/virtualMachineScaleSets/virtualMachines",
      "location": "westeurope",
      "instanceId": "bgola-test-flexible_04945d5e",
      "zones": [
        null
      ]
    }
  ]
}
```

Sample response for the uniform mode:
```json
{
  "value": [
    {
      "name": "aks-agentpool-14709675-vmss_6",
      "id": "/subscriptions/5db89e2c-2127-4418-9a31-dac67b04e87b/resourceGroups/MC_Built-In-Technology-Solutions_BITS-AKS-Test_westus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-14709675-vmss/virtualMachines/6",
      "type": "Microsoft.Compute/virtualMachineScaleSets/virtualMachines",
      "location": "westus",
      "tags": {
        "Project": "Built-In Technology Solutions",
        "aks-managed-consolidated-additional-properties": "2ef6bd7a-353a-11ee-afc8-deb3f01c93e7",
        "aks-managed-createOperationID": "",
        "aks-managed-creationSource": "vmssclient-aks-agentpool-14709675-vmss",
        "aks-managed-kubeletIdentityClientID": "8833d46b-3f78-4096-8419-2a9bb74b3574",
        "aks-managed-operationID": "f91e8f60-a01e-46cd-a1c6-87129050aea7",
        "aks-managed-orchestrator": "Kubernetes:1.24.15",
        "aks-managed-poolName": "agentpool",
        "aks-managed-resourceNameSuffix": "81201883",
        "aks-managed-ssh-access": "LocalUser"
      },
      "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
          "/subscriptions/5db89e2c-2127-4418-9a31-dac67b04e87b/resourceGroups/MC_Built-In-Technology-Solutions_BITS-AKS-Test_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/BITS-AKS-Test-agentpool": {
            "principalId": "fdc00193-91fd-4290-8881-709574dc379c",
            "clientId": "8833d46b-3f78-4096-8419-2a9bb74b3574"
          },
          "/subscriptions/5db89e2c-2127-4418-9a31-dac67b04e87b/resourcegroups/MC_Built-In-Technology-Solutions_BITS-AKS-Test_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-bits-aks-test": {
            "principalId": "348f54da-9b9e-4210-9222-02bddd4692ba",
            "clientId": "8128b5d9-d1c9-4899-b217-70f1ea614671"
          }
        }
      },
      "instanceId": "6",
      "sku": {
        "name": "Standard_B2s",
        "tier": "Standard"
      },
      "properties": {
        "latestModelApplied": true,
        "modelDefinitionApplied": "VirtualMachineScaleSet",
        "networkProfileConfiguration": {
          (...)
        },
        "provisioningState": "Succeeded",
        "hardwareProfile": {
          "vmSize": "Standard_B2s"
        },
        "vmId": "a5a38c5c-2ddb-4356-8d6e-281138bb3724",
        "storageProfile": {
          (...)
        },
        "osProfile": {
          (...)
        },
        "networkProfile": {
          (...)
        },
        "timeCreated": "2023-04-12T12:57:40.4732867+00:00"
      },
      "resources": [
        (...)
      ]
    }
  ]
}
```

**Comment by Maykwaches** [comment]
**Nombre del Producto:**
AkiomedicalWatches_AI

**Descripción del Producto:**
¡Descubre un nuevo horizonte en salud y rendimiento con AkiomedicalWatches_AI! Este reloj inteligente fusiona tecnología avanzada con asistentes personales para ofrecerte una experiencia única.

**Características Destacadas:**
- **Entrenador Personal Avanzado:** Algoritmos disciplinados que te guían hacia tu mejor versión.
- **Monitoreo Médico Integral:** Sensores avanzados para seguimiento en tiempo real y recomendaciones personalizadas.
- **Programas Específicos:** Diseñados para optimizar áreas clave como ocio, estudios o creatividad.
- **Conexión en la Nube:** Vincula tu smartphone para gestionar perfiles, programas y ahorrar espacio en el dispositivo.
- **Asistente de Rendimiento:** Acceso a algoritmos avanzados para una asistencia personalizada basada en el estado físico detectado.
- **Integración de IA:** Diseñado para conectarse y potenciar la experiencia con asistentes virtuales como ChatGPT y otras IA.

¡Únete a la revolución de AkiomedicalWatches_AI y experimenta la sinfonía de tecnología, salud e inteligencia artificial! Tu bienestar, tu rendimiento, tu mejor versión, ahora con el poder de la IA. 

¿Qué opinas? ¿Hay algún aspecto específico que te gustaría mejorar o ajustar?

**Comment by Maykwaches** [comment]
AkiomedicalWatches_AI_Collaboration**

**Descripción:**
¡Únete a la revolución de la salud y la tecnología con AkiomedicalWatches_AI! Este repositorio está dedicado a desarrollar y mejorar los relojes inteligentes que fusionan salud y asistencia avanzada. Buscamos colaboradores apasionados por la innovación y la mejora continua en el campo de la tecnología portátil y la salud.

**Objetivo:**
Desarrollar funciones avanzadas de seguimiento médico, recomendaciones de salud y hábitos saludables para AkiomedicalWatches_AI.

**Colaboradores Buscados:**
1. Desarrolladores de software con experiencia en aplicaciones para dispositivos portátiles.
2. Diseñadores de experiencia de usuario (UX) y diseño industrial.
3. Expertos en salud y bienestar para aportar conocimientos en monitoreo médico y recomendaciones saludables.

**Estructura del Repositorio:**
- **/src:** Código fuente de la aplicación AkiomedicalWatches_AI.
- **/designs:** Diseños y prototipos del reloj.
- **/docs:** Documentación del proyecto y guías para colaboradores.

**Cómo Colaborar:**
1. Haz un fork del repositorio.
2. Desarrolla nuevas funciones o mejora las existentes en tu rama.
3. Envía pull requests para revisión y posible integración.

¡Únete a nosotros para crear el futuro de la tecnología vestible y la salud!

**Nota:** Asegúrate de tener las herramientas y entorno de desarrollo adecuados para trabajar en el proyecto. ¡Esperamos tu colaboración!

**Comment by JackTn** [comment]
@TimLovellSmith @grizzlytheodore @rkmanda can someone check on this issue, Thanks! let me know if there has any question!

**Comment by hilaryw29** [comment]
We are currently looking into this, thanks!

**Comment by hilaryw29** [comment]
Hi @bgola-signalfx, thank you for raising this.

This behavior is by design that VMSS VMs List API will only return the VM resource id, VM name, other orchestration properties and instanceProtected for Flexible orchestration mode. The VM model property is not under the scope of the Flexible VMSS.

If you'd like to get the VM properties on a Flexible scale set, please use [ListVM](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list?view=rest-compute-2023-10-02&tabs=HTTP) with the VMSS filter instead. 

Example:

`GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines?$filter='virtualMachineScaleSet/id' eq /subscriptions/{subId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmssName}'&$expand=instanceView&api-version=2023-09-01`

This will return a list of VMs in a Flexible VMSS with the VM model properties (including tags). Please feel free to re-open if there are any other questions, thanks!
