### ISSUE TITLE
Ambiguous Permissions on Properties Complicate 75+ Create-OR-Update Operations

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#275]
# Ambiguous Permissions on Properties Complicate 75+ Create-OR-Update Operations #

There are 75+ Create-OR-Update operations (across Azure Swagger specs) with ambiguous, undocumented permissions on properties (or parameters). If permissions on properties were unambiguously represented in Swagger specs then a generated client library could offer simpler programming experiences and improved predictability.

Let us look at one example.

[`VirtualMachines.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L931  ) - one of the parameters is `VirtualMachine`. Here is a breakdown of permissions of a **subset** of properties of `VirtualMachine`:

<table>
  <tr>
    <th>Property</th>
    <th>Permission</th>
  </tr>
  <tr>
    <td>id</td>
    <td>read (4)</td>
  </tr>
  <tr>
    <td>storageProfile::imageReference</td>
    <td>read | initialize (6)</td>
  </tr>
  <tr>
    <td>storageProfile::osDisk::createOption</td>
    <td>read | initialize (6)</td>
  </tr>
  <tr>
    <td>storageProfile::osDisk::vhd::uri</td>
    <td>read | initialize (6)</td>
  </tr>
  <tr>
    <td>availabilitySet</td>
    <td>read | initialize (6)</td>
  </tr>
  <tr>
    <td>hardwareProfile</td>
    <td>read | initialize | update (7)</td>
  </tr>
  <tr>
    <td>storageProfile::dataDisks</td>
    <td>read | initialize | update (7)</td>
  </tr>
  <tr>
    <td>storageProfile::osDisk::caching</td>
    <td>read | initialize | update (7)</td>
  </tr>
  <tr>
    <td>networkProfile</td>
    <td>read | initialize | update (7)</td>
  </tr>
  <tr>
    <td>tags</td>
    <td>read | initialize | update (7)</td>
  </tr>
</table>

Today, because of this ambiguous situation, when a developer calls the [`VirtualMachines.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L931  ) operation, the only available option is trial and error to find out what combinations of parameters work.

The good news is that it is possible to capture these permissions.

[Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) says, *"Declares the property as "read only". This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request. Properties marked as `readOnly` being true SHOULD NOT be in the required list of the defined schema. Default value is false "* Some of Azure Swagger specs use this property. 

`readOnly` can only represent read permissions but CANNOT represent read | initialize (6) OR read | initialize | update (7). A new Swagger extension will solve the problem - 

<table>
  <tr>
    <th>Field Name</th>
    <th>Type</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>mutability</td>
    <td>integer</td>
    <td>Represents the permission of the property: <br/>-read (4) <br/>-initialize (1) <br/>-read | initialize (6)<br/>-read | initialize | update (7)<br/>Default is read | initialize | update (7)</td>
  </tr>
</table> 

Capturing permissions on properties will simplify programming experiences and improve predictability across languages - C#, Java, Node, Python, Ruby, PHP, Go - and tools - PowerShell and cross-platform CLI.

Today, regardless of the ambiguous situation, **hand-written** PowerShell commandlets and cross-platform CLI commands absorb the complexity and simplify it for developers - there are two distinct paths for Create and Update:

[PowerShell: Create a virtual machine](https://msdn.microsoft.com/en-us/library/azure/mt603754.aspx) that uses [`VirtualMachines.createOrUpdate()`](https://github.com/Azure/azure-powershell/blob/41a9deccbd1518f7a2881a0838c101ed657a7614/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs#L114)

    PS C:\> New-AzureRmVM -ResourceGroupName $ResourceGroupName -Location $Location -VM $VirtualMachine

[PowerShell: Update a virtual machine](https://msdn.microsoft.com/en-us/library/azure/mt603662.aspx) that uses [`VirtualMachines.createOrUpdate()`](https://github.com/Azure/azure-powershell/blob/0738b5d368f6cf9005ed0a72c48b67637bf887a0/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/UpdateAzureVMCommand.cs#L57)

    PS C:\> Update-AzureRmVM -ResourceGroupName "ResourceGroup11" -Name "VirtualMachine07" -VM $VirtualMachine

If permissions on properties were unambiguously represented in Swagger specs then a generated client library could offer simpler programming experiences and improved predictability.

## Reference - today, there are 75+ such Create-OR-Update operations with such ambiguous permissions on properties ##

Authorization

- [`RoleDefinitions.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-authorization/2015-07-01/swagger/authorization.json#L722  )

Compute

- [`AvailabilitySets.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L44  )
- [`VirtualMachineExtensions.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L401  )
- [`VirtualMachines.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L931  )
- [`VirtualMachineScaleSets.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-compute/2016-03-30/swagger/compute.json#L1401  )

Data Lake Store Account

- [`Account.createOrUpdateFirewallRule()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-datalake-store/account/2015-10-01-preview/swagger/account.json#L214  )

DNS

- [`RecordSets.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-dns/2015-05-04-preview/swagger/dns.json#L44  )
- [`Zones.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-dns/2015-05-04-preview/swagger/dns.json#L406  )

Intune

- [`Ios.createOrUpdateMAMPolicy()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-intune/2015-01-14-preview/swagger/intune.json#L302  )
- [`Android.createOrUpdateMAMPolicy()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-intune/2015-01-14-preview/swagger/intune.json#L489  )

Logic

- [`Workflows.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-logic/2015-02-01-preview/swagger/logic.json#L175  )
- [`WorkflowAccessKeys.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-logic/2015-02-01-preview/swagger/logic.json#L618  )

Network

- [`ApplicationGateways.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L122  )
- [`ExpressRouteCircuitAuthorizations.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L412  )
- [`ExpressRouteCircuitPeerings.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L608  )
- [`ExpressRouteCircuits.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L790  )
- [`LoadBalancers.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L1277  )
- [`LocalNetworkGateways.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L1395  )
- [`NetworkInterfaces.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L1648  )
- [`NetworkSecurityGroups.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L2002  )
- [`PublicIPAddresses.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L2205  )
- [`RouteTables.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L2408  )
- [`Routes.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L2618  )
- [`SecurityRules.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L2814  )
- [`Subnets.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L3017  )
- [`VirtualNetworkGatewayConnections.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L3157  )
- [`VirtualNetworkGateways.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L3471  )
- [`VirtualNetworks.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-network/2016-03-30/swagger/network.json#L3824  )

Notification Hubs

- [`Namespaces.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L81  )
- [`Namespaces.createOrUpdateAuthorizationRule()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L222  )
- [`NotificationHubs.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L609  )
- [`NotificationHubs.createOrUpdateAuthorizationRule()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-notificationhubs/2014-09-01/swagger/notificationhubs.json#L764  )

Redis

- [`Redis.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-redis/2015-08-01/swagger/redis.json#L44  )

Remote App

- [`Collection.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-remoteapp/2014-09-01/swagger/remoteapp.json#L338  )

ARM Resources - Locks

- [`ManagementLocks.createOrUpdateAtResourceGroupLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L43  )
- [`ManagementLocks.createOrUpdateAtResourceLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L97  )
- [`ManagementLocks.createOrUpdateAtSubscriptionLevel()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/locks/2015-01-01/swagger/locks.json#L252  )

ARM Resources - Account

- [`Deployments.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L100  )
- [`ResourceGroups.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L591  )
- [`Resources.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1046  )
- [`Tags.createOrUpdateValue()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1228  )
- [`Tags.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1273  )
- [`PolicyDefinitions.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-resources/resources/2016-02-01/swagger/resources.json#L1511  )

Scheduler

- [`JobCollections.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2014-08-01-preview/swagger/scheduler.json#L143  )
- [`Jobs.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2014-08-01-preview/swagger/scheduler.json#L393  )
- [`JobCollections.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2016-01-01/swagger/scheduler.json#L143  )
- [`Jobs.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-scheduler/2016-01-01/swagger/scheduler.json#L393  )

Search

- [`Services.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-search/2015-02-28/swagger/search.json#L128  )

SQL

- [`SecurityAlertPolicy.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-sql/2015-05-01/swagger/sql.json#L45  )

App Service - Web App

- [`Certificates.createOrUpdateCertificate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L120  )
- [`Certificates.createOrUpdateCsr()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L371  )
- [`Domains.createOrUpdateDomain()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L747  )
- [`HostingEnvironments.createOrUpdateHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1747  )
- [`HostingEnvironments.createOrUpdateMultiRolePool()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3012  )
- [`HostingEnvironments.createOrUpdateWorkerPool()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3230  )
- [`ManagedHostingEnvironments.createOrUpdateManagedHostingEnvironment()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L3762  )
- [`ServerFarms.createOrUpdateServerFarm()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L4685  )
- [`ServerFarms.createOrUpdateVnetRoute()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L5134  )
- [`Sites.createOrUpdateSiteVNETConnectionSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L5880  )
- [`Sites.createOrUpdateSiteVNETConnection()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L6137  )
- [`Sites.createOrUpdateSite()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L7324  )
- [`Sites.createOrUpdateSiteSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L7542  )
- [`Sites.createOrUpdateSiteHostNameBinding()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L9472  )
- [`Sites.createOrUpdateSiteHostNameBindingSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L9650  )
- [`Sites.createOrUpdateSiteConfig()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L9828  )
- [`Sites.createOrUpdateSiteConfigSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L9998  )
- [`Sites.createOrUpdateSiteSourceControlSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10182  )
- [`Sites.createOrUpdateSiteSourceControl()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10411  )
- [`Sites.createOrUpdateSiteRelayServiceConnection()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14360  )
- [`Sites.createOrUpdateSiteRelayServiceConnectionSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14603  )
- [`Sites.createOrUpdateSiteVNETConnectionGateway()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14971  )
- [`Sites.createOrUpdateSiteVNETConnectionGatewaySlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L15186  )
- [`DataSources.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/search/2015-02-28/swagger/searchservice.json#L20  )
- [`Indexers.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/search/2015-02-28/swagger/searchservice.json#L319  )
- [`Indexes.createOrUpdate()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/search/2015-02-28/swagger/searchservice.json#L667  )

**Comment by devigned** [comment]
Why do we need `read | initialize`? Shouldn't that just be a readonly property? If they can't be updated in the API, why should we provide any way to initialize?

@Azure/adx-autorest-contributors thoughts?

**Comment by selvasingh** [comment]
Please see a partial breakdown of permissions of a subset of properties of virtual machine where some of the parameters are part of a create operation, then it is read only

**Comment by devigned** [comment]
@selvasingh the way I interpret that is that the constructor should require the `readonly | initialize` properties and not provide a setter for those properties. Anything that is `readonly | initialize | update` should be optional and provide a setter. Is that an incorrect interpretation?

**Comment by devigned** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/425 <-- perhaps, we should use composition as described here.

**Comment by selvasingh** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/698

**Comment by devigned** [comment]
I'm going to close this issue and track it via #307.
