### ISSUE TITLE
No ETag in Virtual Machines - Get response

### ISSUE THREAD

**Issue by andlr** [Azure/azure-rest-api-specs#27527]
[API documentation for Virtual Machines - Get](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/get?view=rest-compute-2023-10-02&tabs=HTTP) specifies that response returns `etag` property:

| Name | Type   | Description                                                                                                                                   |
|------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| etag | string | Etag is property returned in Create/Update/Get response of the VM, so that customer can supply it in the header to ensure optimistic updates. |

I've tried executing this sample request from documentation using curl:
```
GET https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM?$expand=userData&api-version=2023-09-01
```

In documentation, sample response contains "etag":
```json
{
  "name": "myVM",
  "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "West US",
  "tags": {
    "myTag1": "tagValue1"
  },
  "etag": "\"1\"",
```

But Azure Compute API doesn't return it in responses to my requests.

I need it to avoid race conditions when updating Virtual Machine. Is there a way to do it without ETag?

**Comment by TravisCragg-MSFT** [comment]
@andlr I am getting additional clarity on the etag functionality with the VM API and get back to you.

**Comment by Mitthu1990** [comment]
Any update on this ? I am facing the same issue.

**Comment by TravisCragg-MSFT** [comment]
@andlr @Mitthu1990 I am able to get the ETAG when sending API requests using API version 2023-09-01. Can you give a more specific example of when you are not seeing these Etags?

**Comment by andlr** [comment]
I've just tried this request again, and it does work now. But it didn't half a year ago, when I've created this issue. I guess I can close it now
