### ISSUE TITLE
[FEATURE REQ] Support setting Key Vault Certificate Contact in Control Plane API.

### ISSUE THREAD

**Issue by mybayern1974** [Azure/azure-rest-api-specs#27992]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.4/certificates.json#L126

### API Spec version

what ever version as long as that would be control plane API

### Please describe the feature.

**Summary**
Support setting Key Vault Certificate Contact in Control Plane API. This feature has been supported in Data Plane API as [here](setting Key Vault Certificate Contact in Control Plane API). 

**Background**
Terraform AzureRM provider now is providing deployment experience of provision both the Key Vault and its [certificate contacts](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#contact) with asking users only need to write one Terraform Key Vault configuration including contacts info as parameters, which is being implemented by calling Key Vault control plane API and [Certificate Contacts Data Plane API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.4/certificates.json#L126). 

However, some users are running into issues: they disable their Key Vault public network access and setup some file wall rules, ending up blocking their access to Azure Control Plane APIs, ending up their provisioning Key Vault failed by Terraform. There are possible workarounds for them, which however either needs users to change their Terraform configurations or needs Terraform AzureRM provider to involve breaking changes. 

Filing this issue to check whether Azure Key Vault team has plan to support the Contact feature in Control Plane API which can benefit Terraform users in terms of neither they nor TF have to introduce breaking changes to unblock those users.

**Comment by jlichwa** [comment]
No plan to expose certificates to Control Plane, it violates network restrictions as issue described above. Certificates, Keys, Secrets management is only allowed through secure access including network and identity access restrictions.
