### ISSUE TITLE
AI Search Client Swagger Import into APIM URL Formatting

### ISSUE THREAD

**Issue by howardginsburg** [Azure/azure-rest-api-specs#28180]
### API Spec link

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/search/data-plane/Azure.Search/stable/2023-11-01/searchindex.json

### API Spec version

2023-11-01

### Question/Query

Trying to put APIM in front of the Azure AI Search API.  When importing the swagger, it loses the proper URL formatting for the operations.

For example, the document count operation comes in as:
 /docs/$count?api-version={api-version}

when it should correctly import as:
 /{indexname}/docs/$count?api-version={api-version}

Can someone help me understand why this is happening, and what options there are to avoid manually or scripting the corrections?

**Comment by mattgotteiner** [comment]
Hi @howardginsburg ,

In the linked swagger the "[x-ms-parameterized-host](https://azure.github.io/autorest/extensions/#x-ms-parameterized-host)" extension is used to parameterize all the operations

It does not appear that this extension is supported by APIM

https://learn.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions#supported-extensions

If you want to import the Search swagger I do think that manual or scripted corrections are required. You can also make a request that APIM supports this extension.

I hope this helps,
Matt

**Comment by howardginsburg** [comment]
Thanks Matt!  I agree that manual scripting is the best option for the time being to make it so that updates to the swagger can be easily managed.

Sample repo can be found at https://github.com/howardginsburg/APIMSwaggerFix for anyone that comes across this at a later date.
