### ISSUE TITLE
[BUG] Bad unicode in object description

### ISSUE THREAD

**Issue by iann0036** [Azure/azure-rest-api-specs#28258]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/36de5cef6b87d3122e7b2eef3db30da49ef0f88f/specification/security/resource-manager/Microsoft.Security/preview/2023-12-01-preview/automations.json

### API Spec version

2023-12-01-preview

### Describe the bug

At https://github.com/Azure/azure-rest-api-specs/blob/36de5cef6b87d3122e7b2eef3db30da49ef0f88f/specification/security/resource-manager/Microsoft.Security/preview/2023-12-01-preview/automations.json#L615, the characters at the beginning of the description field which look like spaces are bad unicode equivalents. They broke some personal automation.

### Expected behavior

The description should be free of irregular unicode points.

### Actual behavior

The description field begins: `The�Log�Analytics�Workspace�to�which�event`

### Reproduction Steps

See file.

**Comment by zzhxiaofeng** [comment]
@Nessya123 Please help have a look, thank you.

**Comment by Nessya123** [comment]
@zzhxiaofeng - how can I push a fix to the repo?

**Comment by raych1** [comment]
@Nessya123 , can you create a PR with the changes to the repo?

**Comment by Nessya123** [comment]
@raych1 - should I fork the repo and then create a PR? sorry, I am not familiar with the process.

**Comment by raych1** [comment]
@Nessya123 , yes, please. I thought you updated the swagger last time, didn't it?

**Comment by Nessya123** [comment]
Hi,

I opened a PR with a fix that already approved with all required approvals, and it's pending merge:
https://github.com/Azure/azure-rest-api-specs/pull/28984

**Comment by Nessya123** [comment]
The PR with the fix is merged.

**Comment by Nessya123** [comment]
Bug is resolved
