### ISSUE TITLE
ExpressRoutes broken due to name change

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#2825]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-02-01/expressRouteCircuit.json#L1326

In all prior Swaggers, this was called "ExpressRouteCircuitPeeringType". The rename has caused breakages in SDKs and tooling. Was this intentional?

**Comment by marstr** [comment]
Howdy @tjprescott, was the rename between API Versions?

**Comment by tjprescott** [comment]
From "ExpressRouteCircuitPeeringType" to "ExpressRoutePeeringType".

**Comment by marstr** [comment]
Sorry, what I mean was did the name change inside of a single API Version, or was the change between two API Versions?

**Comment by tjprescott** [comment]
Between them.

**Comment by marstr** [comment]
Kk, there may not be much recourse then.  Technically, they're allowed to make changes between API Versions. It is a good data-point though, you could send a mail to Samer/Kirthi so that they can catalog this.

**Comment by tjprescott** [comment]
Thanks @marstr I'll do that.

**Comment by salameer** [comment]
This one is very interesting captain Travis,

I think we need to analyze why did the change happen:
- Did the reviewers ask for this changes?
- Did the service team do it and if so for what reason?

Then we can dig deep into a direction to avoid these, but there are many reasons why this happened and technically they did the right thing here

**Comment by salameer** [comment]
Can we trace that and then we can follow on it?

**Comment by tjprescott** [comment]
The strange thing is that rest of the other ExpressRoute model names kept the same names.
