### ISSUE TITLE
Method: HEAD returning 400 Bad Request for resource endpoints (Check if exists)

### ISSUE THREAD

**Issue by AaronFixer** [Azure/azure-rest-api-specs#2856]
Example endpoint: https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistencebyid

For all resources, I'm receiving a bad request when using a manual request (Postman) and through the .NET SDK. 

There are no problems with the resource in questions. I am able to perform a GET on the same resources, just with a different API Version.

**Comment by annatisch** [comment]
Thanks @AaronFixer - are you able to perform a HEAD on the same resources using a difference API version? Trying to ascertain if the issue is with the API version or the HEAD requests in general.

**Comment by AaronFixer** [comment]
@annatisch  I've tried with many other API endpoints, especially resource ones. All other endpoints respond with a 405 Method not Allowed.

**Comment by annatisch** [comment]
@rajshah11 @stankovski @vivsriaus - do you have any thoughts?

**Comment by ifeoluwaokunoren** [comment]
@AaronFixer - is this still and issues? If yes, can you please provide an example of what API is returning a Bad Request? and is this for a specific resourceType?
cc @Tiano2017

**Comment by ifeoluwaokunoren** [comment]
Hey @AaronFixer - following up with my previous question, before I close out this issue - thanks.

**Comment by ajaygit158** [comment]
Hi,

I was trying out this API CheckExistenceById
Api version used: 2020-06-01
I tried the API with Resource Group and I received response 204
However, when resource Id provided was a storage account, the API failed with 400 bad Request.
Similarly, for Recovery Services Vault, I received 400 Bad Request.

I am using postman to perform the query.
URL: https://management.azure.com/subscriptions/<subId>/resourceGroups/<rgName>/providers/Microsoft.RecoveryServices/vaults/<vaultName>?api-version=2020-06-01

Http Method: HEAD

The resources exist and I can see them on portal.

**Comment by ifeoluwaokunoren** [comment]
We're tracking this issue via https://github.com/Azure/azure-rest-api-specs/issues/8092
