### ISSUE TITLE
[BUG] Newly created resources are not returned by the list API, but are returned by the listByResourceGroup API

### ISSUE THREAD

**Issue by juniormbe** [Azure/azure-rest-api-specs#28600]
### API Spec link

https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters?api-version=2024-01-01

### API Spec version

2024-01-01

### Describe the bug

After creating a resource (a Kubernetes cluster in this case), we perform a query to list all the clusters in the subscription using the [List API](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list?view=rest-aks-2024-01-01&tabs=HTTP) and notice that the cluster is not returned in the response. 

We have to wait a certain amount of time, which can go up to several minutes, for it to be returned by this API. On the other hand, the cluster is immediately returned by the [List By ResourceGroup API](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-by-resource-group?view=rest-aks-2024-01-01&tabs=HTTP).

Using the List API

`GET https://management.azure.com/subscriptions/xxxx/providers/Microsoft.ContainerService/managedClusters?api-version=2024-01-01`
````
{
    "value": []
}
````

Using the List By ResourceGroup API

`GET https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ContainerService/managedClusters?api-version=2024-01-01`
````
{
    "value": [
        {
            "id": "/subscriptions/xxxx/resourcegroups/xxxx/providers/Microsoft.ContainerService/managedClusters/xxxx",
            "location": "australiaeast",
            "name": "kub-efossombelocalroot-pdj",
            "tags": {...},
            "type": "Microsoft.ContainerService/ManagedClusters",
            "properties": {
                "provisioningState": "Creating",
                "powerState": {
                    "code": "Running"
                },
                "kubernetesVersion": "1.29.2",
                "currentKubernetesVersion": "1.29.2",
                "dnsPrefix": "xxx",
                "fqdn": "xxx",
                "azurePortalFQDN": "xxx",
                "agentPoolProfiles": [...],
                "linuxProfile": {...},
                "servicePrincipalProfile": {...},
                "nodeResourceGroup": "...",
                "enableRBAC": false,
                "supportPlan": "KubernetesOfficial",
                "networkProfile": {...},
                "maxAgentPools": 1,
                "autoUpgradeProfile": {},
                "securityProfile": {},
                "storageProfile": {...},
                "oidcIssuerProfile": {...},
                "workloadAutoScalerProfile": {},
                "resourceUID": "xxx"
            },
            "sku": {...}
        }
    ],
    "nextLink": "https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ContainerService/managedClusters?%24skipToken=xxxx&api-version=2024-01-01&skipToken=xxxx"
}
````

Same behavior when using the cli-Azure (version `2.58.0`)
```
xxx@xxx ~ % az aks list -o table                    

xxx@xxx ~ % az aks list -g xxx -o table
Name                        Location       ResourceGroup     KubernetesVersion    CurrentKubernetesVersion    ProvisioningState    Fqdn
--------------------------  -------------  ----------------  -------------------  --------------------------  -------------------  ---------------------------------
xxx                         australiaeast  xxx               1.29.2               1.29.2                      Creating             xxx.hcp.australiaeast.azmk8s.io
```

Same behavior Java SDK (`com.azure.azureresourcemanager`) (Tested with version `2.13.0` and `2.37.0`)
```
AzureResourceManager client = factory.buildResourceManager();

client.kubernetesClusters().list().stream().toList(); // Call the List API
client.kubernetesClusters().listByResourceGroup(name).stream().toList(); // Call the List By Resource API
```

### Expected behavior

The api list must return the created resources without delays of availability of newly created resources.

### Actual behavior

Newly created resources are not returned by the list API

### Reproduction Steps

1. Create a kunernetes custer from API
2. Immediately try to list all the clusters of the subscription with the List API
   2.1. You notice that the newly created cluster is not returned in the response
3. Try to list the clusters of the resource group to which the newly created cluster belongs with the List By ResourceGroup API
   3.1. You see that the cluster is returned in the response

**Comment by zzhxiaofeng** [comment]
@FumingZhang Please help have a look, thank you.

**Comment by fyrnaga** [comment]
Let us know if you need anything more from our side.

**Comment by FumingZhang** [comment]
@juniormbe, @fyrnaga, could you please provide more details about
- when did the issue occur?
- which subscription did you use?

This seems to be an anomaly in server-side. If it is not related to the SDK, please open a support ticket to the AKS team and you could share more details there.

BTW, I tried to make a repro (with python SDK & azure-cli), both list by sub and by resource group works fine.

**Comment by juniormbe** [comment]
Hi @FumingZhang

This latency happens every time we create kubernetes clusters. (This also happens when creating other resources but it is more pronounced for Kubernetes clusters)

Here are the stats from tests carried out today:

Subscription ID: `1bdc0343-1eb7-49e6-b986-5dd354002cc7`

First cluster
--------------
Cluster-name: kub-efossombe-test-001
Region: eastus
Create request time: 13:14:30 UTC
Available in ListByResource Group API time: 13:15:10 UTC (time spend: few seconds)
Available in List API time: 13:29:07 UTC (time spend: ~15min)

Second cluster
--------------
Cluster-name: kub-efossombe-test-002
Region: australiaeast
Create request time: 13:14:30 UTC
Available in ListByResource Group API time: 13:15:10 UTC (time spend: few seconds)
Available in List API time: 13:29:07 UTC (time spend: ~15min)

![list-kubernetes-cluster](https://github.com/Azure/azure-rest-api-specs/assets/11160371/d3286176-b1fd-48fb-bc55-ca2fdbf4ef32)

**Comment by FumingZhang** [comment]
Thanks for sharing the details. I checked the log and found a very strange thing. During the period from `2024-04-10 13:15:00` to `2024-04-10 13:28:00`, ARM received 164 list by sub requests and all ends with success, but there is no record on the AKS side during this period. From a behavioral point of view, it seems that ARM returns an empty result for AKS. To further investigate the cause, please open a support ticket.
