### ISSUE TITLE
[Question] Azure OpenAI 2024-03-01-preview - AssistantEventHandler returns chunk objects instead of delta.

### ISSUE THREAD

**Issue by hayescode** [Azure/azure-rest-api-specs#28745]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-03-01-preview/inference.json

### API Spec version

2024-03-01-preview

### Question/Query

Azure OpenAI users are unable to use [Assistant Streaming](https://platform.openai.com/docs/assistants/overview/step-4-create-a-run?context=with-streaming) because, at least in part, the events returned are like `thread.messsage.chunk` instead of `thread.message.delta`. We are unable to map to the necessary [stream event types](https://github.com/openai/openai-python/blob/v1.22.0/src/openai/types/beta/assistant_stream_event.py#L162). I am using the Async content filtering in preview iwith GPT4.

**Comment by Adlef** [comment]
Thank you for opening this issue. I would be very interested in integrating Stream feature on Azure OpenAI Assistants.

**Comment by hayescode** [comment]
@adlef FYI it seems to be returning `.delta` instead of `.chunk` now so it's working for me.
