### ISSUE TITLE
[TypeSpec Requirement] Add date-based suppression expiration mechanism

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#28754]
```
- tool: TypeSpecRequirement
  path: data-plane/**/*.json
  reason: Schedule fully committed until this date
  validThrough: 2024-05-31
```

* If `currentDate <= validThrough`, apply suppression
* If `currentDate > validThrough`, print warning and ignore suppression
* Should `validThrough` be required or optional?
* If required, should we enforce a maximum range (e.g. 1 year from `currentDate`)?

**Comment by konrad-jamrozik** [comment]
This builds on https://github.com/Azure/azure-rest-api-specs/issues/27348

**Comment by rkmanda** [comment]
We dont foresee any permanent suppressions for the TypeSpec requirement. So we should make validThrough required and the max range could be 6 months from currentDate

**Comment by mikeharder** [comment]
Closing in favor of https://github.com/Azure/azure-rest-api-specs/issues/28754
