### ISSUE TITLE
[TypeSpec Requirement] Only allow suppressions for individual versions

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#28755]
* Compare path to regex `/(preview|stable)/[A-Za-z0-9._-]+/`
  * If match, suppression is targeting a single version, and is allowed
  * Else, suppression is too broad, print error message and fail check
  
```
# Allowed
- tool: TypeSpecRequirement
  path: data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview/**/*.json

# Disallowed
- tool: TypeSpecRequirement
  path: data-plane/**/*.json
```

Optional improvement: https://github.com/Azure/azure-rest-api-specs/issues/29000

**Comment by konrad-jamrozik** [comment]
This builds on:
- https://github.com/Azure/azure-rest-api-specs/issues/27348
