### ISSUE TITLE
"name" field should be readonly in ResourceGroup object

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#288]
The `name` field in `ResourceGroup` object is not readonly in the resources Swagger:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-02-01/swagger/resources.json#L1980

But according to REST API that modify a ResourceGroup, there is no reason to do not make it read-only, since it's not documented as an input in the JSON body:
https://msdn.microsoft.com/en-us/library/azure/dn790525.aspx
https://msdn.microsoft.com/en-us/library/azure/dn790582.aspx

This will simplify SDK ResourceGroup constructor

**Comment by TianoMS** [comment]
"name" is actually allowed in the request body of Create/Update resource group, although it's only used for validation purpose.

**Comment by amarzavery** [comment]
That vioaltes ARM's RPC guidelines. Why do you need to check the name from the body when the name is provided in the url. "name" should be readOnly.
+ @ravbhatnagar - Please take a look at this.

**Comment by ravbhatnagar** [comment]
This will be a breaking change. We will investigate and see how/when this can be addressed.

**Comment by yungezz** [comment]
close legacy issue.
