### ISSUE TITLE
[BUG] device registry tsp definition, wrong operationId in tsp example files

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-rest-api-specs#28804]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceregistry/DeviceRegistry.Management/examples/2023-11-01-preview/Create_AssetEndpointProfile.json#L2

### API Spec version

2023-11-01-preview

### Describe the bug

operationId `Create_AssetEndpointProfile` is wrong

### Expected behavior

Should be `AssetEndpointProfiles_CreateOrReplace`. Similar issues with all example files in examples folder.

### Actual behavior

`Create_AssetEndpointProfile`

### Reproduction Steps

example files issue. I tried to correct it, though generated swagger files contain duplicates...
https://github.com/Azure/azure-rest-api-specs/pull/28783/files

**Comment by zzhxiaofeng** [comment]
@davidemontanari Please help have a look, thank you.

**Comment by davidemontanari** [comment]
@zzhxiaofeng, PR has been linked to this bug. Please take a look. Thanks.

**Comment by XiaofeiCao** [comment]
Thanks @davidemontanari !
