### ISSUE TITLE
missing `x-ms-parameter-location: method` for Parameters in `policyDefinitionVersions.json`

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-rest-api-specs#29030]
https://github.com/Azure/azure-rest-api-specs/pull/24542 introduces new api-version for `Microsoft.Authorization`. However, compared with [existing definition](https://github.com/Azure/azure-rest-api-specs/blob/73319147d7508a9621ff1a60fb8123711b04010e/specification/resources/resource-manager/Microsoft.Authorization/stable/2023-04-01/policySetDefinitionVersions.json#L799-L806), it misses `x-ms-parameter-location: method` for `PolicyDefinitionName`/`PolicyDefinitionVersion` of [policyDefinitionVersions.json](https://github.com/Azure/azure-rest-api-specs/blob/73319147d7508a9621ff1a60fb8123711b04010e/specification/resources/resource-manager/Microsoft.Authorization/stable/2023-04-01/policyDefinitionVersions.json#L783-L798) and `PolicySetDefinitionName` of [policySetDefinitionVersions.json](https://github.com/Azure/azure-rest-api-specs/blob/73319147d7508a9621ff1a60fb8123711b04010e/specification/resources/resource-manager/Microsoft.Authorization/stable/2023-04-01/policySetDefinitionVersions.json#L783C6-L798), which causes [client signature breaking](https://github.com/Azure/azure-sdk-for-python/pull/35489/files#diff-63354bd18012d75e92a869d0707972b511ffe146190d2a671814041066c4da4f) of SDK:
![image](https://github.com/Azure/sdk-release-request/assets/70930885/f62a7a3d-9826-4539-a256-8cbbb08f4529)

**Comment by zzhxiaofeng** [comment]
@calecarter Please help have a look, thank you.

**Comment by msyyc** [comment]
The issue is fixed by https://github.com/Azure/azure-rest-api-specs/pull/29345/files
