### ISSUE TITLE
[BUG] Key for blob etag in the Path List API Spec doesn't match with whats returned from the backend

### ISSUE THREAD

**Issue by RamneekGambhir** [Azure/azure-rest-api-specs#29233]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/data-plane/Azure.Storage.Files.DataLake/preview/2023-05-03/DataLakeStorage.json

### API Spec version

2023-05-03

### Describe the bug

Unable to Read Blob ETag from SDK Path List functions. 
In the spec, the key for etag is "eTag" but the backend returns "etag". Same issue in the previous spec versions as well.

Sample of json payload returned from the backend:
```
payload: {"paths":[{"contentLength":"0","creationTime":"133600651741685854","etag":"0x8DC732CDF49E85E","expiryTime":"0","group":"$superuser","isDirectory":"true","lastModified":"Mon, 13 May 2024 09:12:54 GMT","name":"abcd","owner":"$superuser","permissions":"rwxr-x---"}....... 
```

But the Spec has "eTag". 
https://github.com/Azure/azure-rest-api-specs/blob/ecc0170a2005f5f38231ae4dbba40594d3c00a04/specification/storage/data-plane/Azure.Storage.Files.DataLake/preview/2023-05-03/DataLakeStorage.json#L3324

Would be great if this is fixed in the backend. 

### Expected behavior

Should be able to read ETag from Path List SDK.

### Actual behavior

Unable to read ETag from Path List SDK. 

### Reproduction Steps

```go
	fc := cl.NewFileSystemClient(ctrName)
	
	pager := fc.NewListPathsPager(true, nil)

	for pager.More() {
		resp, err := pager.NextPage(context.Background())
		if err != nil {
			t.Fatal(err)
		}
		for _, p := range resp.Paths {
			if p.ETag == nil {
				t.Fatal("etag is nil")
			}
		}
	}
```

### Environment

github.com/Azure/azure-sdk-for-go/sdk/storage/azdatalake v1.1.2

**Comment by seanmcc-msft** [comment]
This is not a service issue.  Next step is to see if the Go Storage SDK can property parse "etag" with FileSystemClient.GetPaths() (or whatever this API is called in Go).

**Comment by RamneekGambhir** [comment]
The generated file parsing this in go sdk:

https://github.com/Azure/azure-sdk-for-go/blob/897e9035c566063952597bc3b470858e866c2a0b/sdk/storage/azdatalake/internal/generated/zz_models_serde.go#L255
