### ISSUE TITLE
[BUG][Storage] There's no check on case and resource existence when add existing virtual networks to a storage account

### ISSUE THREAD

**Issue by ChenxiJiang333** [Azure/azure-rest-api-specs#29466]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/resource-manager/Microsoft.Storage/stable/2023-01-01/storage.json#L2987

### API Spec version

2023-01-01

### Describe the bug

original issue: https://github.com/Azure/azure-sdk-for-python/issues/36071

It's now able to add a duplicated subnet regardless of the case sensitive as well as a non-existing subnet to a storage account through API which should not be allowed.

### Expected behavior

For same subnet with different cases, should have a check or dont duplicate added it .
For a non-existing subscription's subnet, should have a check for the given Vnet ID.

### Actual behavior

Same subnet with different cases and non-existing subnets can be added to the storage account without any block.

### Reproduction Steps

Send request to: https://management.azure.com/subscriptions/{subscriptions}/resourceGroups/{resourceGroups}/providers/Microsoft.Storage/storageAccounts/{storage} with body:
```
{
    "properties": {
        "networkAcls": {
            "virtualNetworkRules": [{"id": {subnet_resource_id}, "action": "Allow"}]
        }
    }
}
```

Whether with a non-existing subnet_resource_id or a subnet name with different cases. the subnet can always be added to the storage account successfully.

![image](https://github.com/Azure/azure-rest-api-specs/assets/119990644/ff9da036-5ae9-45d4-8998-a09938455802)

**Comment by blueww** [comment]
@ChenxiJiang333 

The check should be done in server side, client side might don't have permission to check, and adding the check on server side can benefit all client side like Portal/Powershell/CLI/SDK.
For server ask, would you please raise a help ticket on Azurite portal to get help from related team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333
> 
> The check should be done in server side, client side might don't have permission to check, and adding the check on server side can benefit all client side like Portal/Powershell/CLI/SDK. For server ask, would you please raise a help ticket on Azurite portal to get help from related team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.

Hi @gengyujie, I have no such option under my tenant, could you follow this direction to raise a help ticket?
![image](https://github.com/Azure/azure-rest-api-specs/assets/119990644/c459d6e1-b0d6-400c-9ecf-a651f276e272)

**Comment by ChenxiJiang333** [comment]
Hi @yifanz7, could storage team have a look at this issue?

**Comment by ChenxiJiang333** [comment]
> @ChenxiJiang333
> 
> The check should be done in server side, client side might don't have permission to check, and adding the check on server side can benefit all client side like Portal/Powershell/CLI/SDK. For server ask, would you please raise a help ticket on Azurite portal to get help from related team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.

Has created the support ticket, thanks.

**Comment by ChenxiJiang333** [comment]
closed for already send feedback to service team.
