### ISSUE TITLE
x-ms-operation-wrapper: Generating Wrapper methods for similar operations

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#295]
It would be nice if we can generate a wrapper method for similar operations, that give a subset of the result or a filtered result based on the parameters provided to the method.

Let us consider [`ListBySubscription()`](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-01-01/swagger/storage.json#L240) and [`ListByResourceGroup(string resourcegroup)`](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-01-01/swagger/storage.json#L268) over 
StorageAccounts. They both return StorageAccounts (same type) but different items due to scope.
It makes sense to group/wrap them together in a wrapper method. This gives us a benefit to autogenerate CLI/powershell commands from the wrapper method.

What would be the best way to describe this wrapping/grouping in an extension using swagger?

One approach that I can think of is: To annotate/tag every operation that needs to be wrapped with an extension named:

```
"x-ms-operation-wrapper": { 
     "WrappedOperationId": "OperationGroup_WrapperMethod",  
      "description" : "Description for the wrapper method"
}
```

```
. . .
"paths": {
    "/subscriptions/{subscriptionId}/providers/Microsoft.Storage/storageAccounts": {
      "get": {
        "tags": [
          "StorageAccounts"
        ],
        "operationId": "StorageAccounts_ListBySubscription",
        "description": "Lists all the storage accounts available under the subscription. Note that storage keys are not returned; use the ListKeys operation for this.",
        "parameters": [
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/StorageAccountListResult"
            }
          }
        },
>>> "x-ms-operation-wrapper": {
          "WrappedOperationId": "StorageAccounts_List"
         "description" : "Lists Storage accounts in a resource group if provided or in a subscription."
        },
        "x-ms-pageable": {
          "nextLinkName": null
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts": {
      "get": {
        "tags": [
          "StorageAccounts"
        ],
        "operationId": "StorageAccounts_ListByResourceGroup",
        "description": "Lists all the storage accounts available under the given resource group. Note that storage keys are not returned; use the ListKeys operation for this.",
        "parameters": [
          {
            "name": "resourceGroupName",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "The name of the resource group within the user's subscription."
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/StorageAccountListResult"
            }
          }
        },
>>> "x-ms-operation-wrapper": {
          "WrappedOperationId": "StorageAccounts_List",
          "description" : "Lists Storage accounts in a resource group if provided or in a subscription."
        },
        "x-ms-pageable": {
          "nextLinkName": null
        }
      }
    }
. . .
}
```

Some rules will be enforced when this extension is applied. They are as follows:
- The Wrapper method will have a union of all the methods as its parameters in the method signature.
- It will route the call to the right method, based on matching parameter sets
  - A **required parameter** in **all** the inner methods will be a **required parameter on the wrapper method**.
  - If the parameter is required in one inner method and optional in another then that parameter will be optional parameter on the wrapper method.
- The return type of the wrapper method will be the same as the return type of all the inner methods
- All the inner methods should belong to the same operation group if they follow the Noun_Verb format. If the inner methods are operations on the client then it should be fine.
- AutoRest will throw an exception during generation if:
  - the return type of all the underlying methods is not the same (I am not sure if inheritance should be considered).
  - All the inner methods do not belong to the same operation group

Let me know your thoughts on this.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/389

**Comment by kirthik** [comment]
closing this ..proposal not accepted
