### ISSUE TITLE
"x-ms-generate-genericVersion": Generating a ListBySubscription() for services that do not have that.

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#296]
All the services in Azure provide a mechanism to list all the resources in a resource group. Some services walk the extra mile to provide a mechanism to list all the resources in a subscriptions and that is awesome. However, some services do not and this can be problematic. 

> Until those services make it possible, it would be nice if the generated clients can fill that gap by generating a method that loops through all the resource groups to get the list of resources in a subscription. 

This provides functional parity on the client side (The resulting function can be slower as it needs to make n+1 requests to get all the resources, where n is the number of resource groups).

The objective is to provide enough metadata to the generator so that it can generate the ListBySubscriptions() method. Whether this is done in parallel or a synchronous fashion is the prerogative of the Generator.

In any case this means that either every service will have to take a dependency on the resource management package or include the listing of resource groups as an operation in their swagger spec or all the runtimes can have this one method hand coded `msRestAzure.resourceGroups.list()`.

This can be done in 2 possible ways. I like the second approach more over the first one. What do you guys think?
1.   **Mark the ListByResourceGroup() method with an extension**:
   `"x-ms-generate-genericVersion": {"operationId": "ListBySubscriptions" }`
    This will indicate the generator to create a method named ListBySubscriptions() that will get the list of resourcegroups and list the resources within them.
2.  **Create a new operation named ListBySubscriptions under the already defined `"x-ms-paths": {}` extension**
   -   We can add two more extensions on it.
     -  Add `"x-ms-generate-genericVersion" : true` This extension will be a Boolean in this scenario. It is an indication that we need to ignore the path. 
       - Add `"x-ms-operation-wrapper": { "WrappedOperationId": "List" }`. This will still create the wrapper method for the generated ListBySubscriptions as described in #295 and we get all the benefits.

```
. . .
"paths": {
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts": {
      "get": {
        "tags": [
          "StorageAccounts"
        ],
        "operationId": "StorageAccounts_ListByResourceGroup",
        "description": "Lists all the storage accounts available under the given resource group. Note that storage keys are not returned; use the ListKeys operation for this.",
        "parameters": [
          {
            "name": "resourceGroupName",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "The name of the resource group within the user's subscription."
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/StorageAccountListResult"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": null
        },
        "x-ms-operation-grouping": {
          "methodName": "StorageAccounts_List"
        }
      }
    }
. . .
}
"x-m-paths": {
  "/genericListBySubscription": {
    "get": {
      "tags": [
        "StorageAccounts"
      ],
      "operationId": "StorageAccounts_ListBySubscription",
      "description": "Lists all the storage accounts available under the subscription. Note that storage keys are not returned; use the ListKeys operation for this.",
      "parameters": [
        {
          "$ref": "#/parameters/ApiVersionParameter"
        },
        {
          "$ref": "#/parameters/SubscriptionIdParameter"
        }
      ],
      "responses": {
        "200": {
          "description": "",
          "schema": {
            "$ref": "#/definitions/StorageAccountListResult"
          }
        }
      },
      "x-ms-pageable": {
        "nextLinkName": null
      },
>>>> "x-ms-generate-genericVersion": true,
>>>> "x-ms-operation-wrapper": {
          "WrappedOperationId": "StorageAccounts_List"
       }
    }
  }
}
```

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/389

**Comment by kirthik** [comment]
closing this - proposal not accepted
