### ISSUE TITLE
[Discussion] How best to customize "body" parameter name for BodyParameter

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-rest-api-specs#29696]
# Context

Isabella added `BodyParameter` to service spec.
```
alias BodyParameter<
  T,
  TName extends valueof string = "body",
  TDoc extends valueof string = "Body parameter."
> = {
  @doc(TDoc)
  @friendlyName(TName)
  @bodyRoot
  body: T;
};
```

The default parameter name is `body`.

In certain cases, client would like either to revert it back to name prior to this change, to avoid breaking changes; or use a different name for specific language.

Therefore, the question is how best to do this
1. for a single API
2. for a single (or a subset of) language

# Approaches considered 

### For all APIs

If `BodyParameter` is a model (instead of alias), this would be easiest
```
@@clientName(BodyParameter.body, "requestOptions");
```

### For all languages

This would be easiest
```
op getEmbeddings is Azure.Core.ResourceAction<
  Deployment,
  BodyParameter<EmbeddingsOptions, "embeddingOptions", "<doc>">,
  Embeddings
>;
```

# For 1 API and specified language

### Use meta type `op.parameters::<parameter>`

Chenjie mentioned about `op.parameters::body`.

It works for simple API (if `BodyParameter` is a model) e.g.
```
op simpleApi(...BodyParameter<EmbeddingsOptions>): Embeddings;

@@clientName(simpleApi::parameters.body, "embeddingOptions");
```

But it does not work for templated API e.g.
```
op getEmbeddings is Azure.Core.ResourceAction<
  Deployment,
  BodyParameter<EmbeddingsOptions>,
  Embeddings
>;

@@clientName(getEmbeddings::parameters.body, "embeddingOptions");
```

[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7CskfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5SZXN0O9AVSHR0cNEVVukAqMgbQcR5LkNvcmXPEsV8R8h7xyIKQHNlcnZpY2Uoe3RpdGxlOiAiVGV4dCBhdXRob3LkAP99KQpA5wEOZWQoU8Yux3dzKQpuYW1lc3BhY2UgxDhByDc7CgplbnVtIM8wIHsKICBAdXNlRGVwZW5kZW5jeSjqALHoAM5zLnYxXzBfUHJldmlld18yKQogIHYxOiAiMjAyMS0wxAMiLAp9CgphbGlhcyBCb2R5UGFyYW1ldGVyPAogIFQsxAVOYW1lIGV4dGVuZHMgdmFsdWVvZiBzdOQAniA9ICJib2R5IsUpRG9j2yjEXiBwyF8uIgo%2BID3mAMdkb2MoxD3kAJ9AZnJpZW5kbHnEdijFfMUXxGZSb290CiAgxAs6IFQ7Cn07Cgptb2RlbO4Auk3EE%2F8Av%2F8Av%2F8Av%2BcAv%2F8Avf8AvekAvVJlcXVlc3TFYcRT5AIKOsd65QGeQHJvdXRlKCJvcDEiKQpvcCBzaW1wbGUoLi4u8wD5y08%2BKTogdm9pZDsKLy8gbm90IHdvcmsgd2hlbvMBMiBpcyDlAJEKQEDmA2DlAMbGbDo66QD7cy7kAMQsICJyZeQAqiIp5AL96QCiMuwAojLxAKP%2FAJ71AJ7kAJnlAqH0AJky%2FwCa6gCaM%2BYAmnRlbXBsYXRlZMRX6wMzUnBjT3DkA9Npb248%2FwFXLCB7fT7zALdvcMRVyWLuALDJF%2F4Asg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

We may check with Timothee whether this is a bug. <-- Confirmed this be bug, but fix is not scheduled.

### Just write a model with `@bodyRoot` for the API

This would be cumbersome, but it should work
```
model EmbeddingsBodyParameter {
  @doc("<doc>")
  @bodyRoot
  body: EmbeddingsOptions;
}

@@clientName(EmbeddingsBodyParameter.body, "embeddingOptions");
```

**Comment by ArcturusZhang** [comment]
Is there a way to let the friendly name of `body` to be the same as the type `T`?
Something like:
```
alias BodyParameter<
  T,
  TName extends valueof string = "{firstCharToLower(nameof(T))}",
  TDoc extends valueof string = "Body parameter."
> = {
  @doc(TDoc)
  @friendlyName(TName)
  @bodyRoot
  body: T;
};
```
I am not sure if there is a way in typespec to do this.

**Comment by weidongxu-microsoft** [comment]
Previous default handling in Java is same to .NET, that `embeddingOptions` be the parameter name, if the model containing the implicit body be `EmbeddingOptions`.

This one would work (though the camelCasing is done in emitter).
```
alias BodyParameter<
  T,
  TName extends valueof string = "{name}",
  TDoc extends valueof string = "Body parameter."
> = {
  @doc(TDoc)
  @friendlyName(TName, T)
  @bodyRoot
  body: T;
};
```

But this kind of make the default good for Java/.NET, but bad for e.g. Python.

**Comment by weidongxu-microsoft** [comment]
We will use approach **Just write a model with @bodyRoot for the API** if no other approach can apply.
