### ISSUE TITLE
Certificate list operations responses are incorrectly modeled for 2016-03-01

### ISSUE THREAD

**Issue by johanste** [Azure/azure-rest-api-specs#2980]
The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/Certificates.json#L18) shows that the result is supposed to be a "normal" page:able structure (value array property and next link), but the service is returning an array instead. 

[Generated management libraries](https://pypi.org/project/azure-mgmt-web/0.30.1/) and [REST reference documentation](https://docs.microsoft.com/en-us/rest/api/appservice/certificates/list) are broken as a result.

**Comment by naveedaz** [comment]
@johanste  This issue was fixed on the backend in API version 2018-11-01. Do you still need the older API version to reflect the response backend returns or do you plan on using the new API version?
