### ISSUE TITLE
Microsoft.ApiManagement Services_Get returns a numerical value for vpnType 

### ISSUE THREAD

**Issue by johanste** [Azure/azure-rest-api-specs#2982]
Per the (swagger)[https://github.com/Azure/azure-rest-api-specs/blob/0bef2b99ad6d52781e3c308bc6b420f6eef59ef7/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2016-10-10/apimdeployment.json#L971], the return type is supposed to be a string/enum. 

This is causing generated SDKs to fail on deserialization.

**Comment by lmazuel** [comment]
Hey @johanste ! Could you give more context about about what you actually receive from Azure?

**Comment by solankisamir** [comment]
This issue was fixed on service side. Please reactivate if you still see this ussur
