### ISSUE TITLE
[BUG] `tool_choice="required"` is still not supported in the latest OpenAI API version

### ISSUE THREAD

**Issue by minhduc0711** [Azure/azure-rest-api-specs#29844]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.yaml#L1678-L1686

### API Spec version

2024-06-01

### Describe the bug

In the specification file above, I see that the chat completion's parameter `tool_choice` should support `required` as a valid value, but I got an error when setting it as such.

### Expected behavior

I should be able to set `tool_choice="required"`, and the endpoint will always return a tool call.

### Actual behavior

I got the following error:
```
Traceback (most recent call last):
  File "/data/mdm/iva_webapi/test_openai.py", line 16, in <module>
    chat_completion = client.chat.completions.create(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/mdm/miniforge3/envs/iva/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/mdm/miniforge3/envs/iva/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^
  File "/data/mdm/miniforge3/envs/iva/lib/python3.11/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/mdm/miniforge3/envs/iva/lib/python3.11/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/data/mdm/miniforge3/envs/iva/lib/python3.11/site-packages/openai/_base_client.py", line 1030, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "'$.tool_choice' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

### Reproduction Steps

```python
import os

from openai import AzureOpenAI

gpt_35_16k_endpoint = os.getenv("OPENAI_GPT_35_16K_ENDPOINT")
gpt_35_16k_key = os.getenv("OPENAI_GPT_35_16K_KEY")
gpt_35_16k_deployment = os.getenv("OPENAI_GPT_35_16K_DEPLOYMENT")

if gpt_35_16k_deployment and gpt_35_16k_key and gpt_35_16k_endpoint:
    client = AzureOpenAI(
        azure_endpoint=gpt_35_16k_endpoint,
        api_key=gpt_35_16k_key,
        api_version="2024-06-01",
    )

    chat_completion = client.chat.completions.create(
        model=gpt_35_16k_deployment,
        messages=[
            {
                "role": "user",
                "content": "Weather in hanoi today",
            }
        ],
        tools=[
            {
                "type": "function",
                "function": {
                    "name": "get_weather",
                    "description": "Get the current weather in a given location",
                    "parameters": {                                                                                    
                        "type": "object",                                                                              
                        "properties": {                                                                                
                            "location": {"type": "string", "description": "The city and state, e.g. San Francisco, CA"}
                        },
                    },
                },
            }
        ],
        tool_choice="required",
    )
    print(chat_completion.to_json(indent=2))
```

### Environment

openai python package version: 1.35.14

**Comment by hobofan** [comment]
And here I thought I was just holding it wrong...

I've been encountering the exact same issue. Would be very nice to see this fixed, as for our current use-case this is quite crucial, and with `tool_choice=auto`, I'm getting a high rate of text responses that identify the tool to call correctly but don't actually trigger a tool call response.

**Comment by janaka** [comment]
I think the issue still is that the latest Azure OpenAI API with these options has not been released yet. It's confusing because the Azure client has the enum to set the latest version so we expect the service exist. Even some places of the docs and specs have the new version but the following page is still showing  `2024-05-01-preview`. I think `2024-06-01` is what has this feature.

https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation

**Comment by hobofan** [comment]
@janaka From what is shown on other pages, the `2024-06-01` version of the inference API has been released as GA. This page shows it as the current GA release: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference . If it wasn't released yet, I would assume that you would get the same 404 error that you get if you submit a non-existent API version with a request.

But yeah, for some reason the current preview release is older than the current GA release.

**Comment by janaka** [comment]
@hobofan oh interesting. I'd not seen those pages before. If the GA bit was update when that page says it was last updated it's after I last tried. iirc I was getting a 404 or similar. Thanks for sharing those links.

**Comment by janaka** [comment]
Looks like my assumption is invalid, that the Azure OpenAI API version numbers tracked the OpenAI OpenAI API version. They seem completely independent.

So Azure just have not released these features on the inference API.

**Comment by hobofan** [comment]
> So Azure just have not released these features on the inference API.

See the link to the specification in top-level comment. According the the spec, the `required` option should now be supported (it didn't exist in the enum in previous versions). So either the spec is wrong, or this is a bug in the implementation.

**Comment by janaka** [comment]
@jpalvarezl @YunsongB @trrwilson any of you able to shed some light? Please help us understand what the actual released version of the inference API is? is the readme up to date? `release_2023_05_15` is the released version? seems off to me.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/readme.md

**Comment by hobofan** [comment]
Tried to do the same API calls, and looks like `tool_choice="required"` is working now!

**Comment by janaka** [comment]
just tried now, still getting `Invalid value: 'required'. Supported values are: 'none' and 'auto'.'` Maybe the update is still being rolled out.

**Comment by PatrickLef** [comment]
Also getting `Invalid value: 'required'. Supported values are: 'none' and 'auto'.'` with gpt-4o in east-us and sweden

**Comment by vivia11** [comment]
Also getting `Invalid value: 'required'. Supported values are: 'none' and 'auto'.` with gpt-4o in Canada.

This worked with gpt-3.5 turbo though.

**Comment by janaka** [comment]
Our deployment is east-us

@hobofan which region is your deployment?

**Comment by hobofan** [comment]
From what I can tell in France Central (I only consume the deployment and don't have access to see the deployment details though).

**Comment by janaka** [comment]
there's a new preview spec with `tool_choice=required` that's something though prob means nothing given the stable spec has it but doesn't work in all regions. 

https://github.com/Azure/azure-rest-api-specs/blob/4b847aabd57c3477f6018bcce7d5156006dd214d/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-07-01-preview/inference.json#L5580

**Comment by minhduc0711** [comment]
> gpt-3.5-turbo accepts `required`, but 4o does not.
Yeah, this still happens in `2024-07-01-preview` for me.

**Comment by janaka** [comment]
gtk - how are you testing? curl or something? at least yesterday the dotnet lib didn't have that version in the enum.

**Comment by minhduc0711** [comment]
I used the Python script in https://github.com/Azure/azure-rest-api-specs/issues/29844#issue-2410566860 and simply updated the `api_version` parameter.

**Comment by janaka** [comment]
> I used the Python script in [#29844 (comment)](https://github.com/Azure/azure-rest-api-specs/issues/29844#issue-2410566860) and simply updated the `api_version` parameter.

gotcha - with gtp-4o right?

**Comment by minhduc0711** [comment]
Yes with gpt-4o

**Comment by janaka** [comment]
it will be interesting to see what happens when they release `gpt-4o 2024-08-06` on the inferencing API as that's a bit useless without an updated REST API.

**Comment by janaka** [comment]
So `2024-07-01-preview` announced on the what's new page but the tool_choice=required isn't _deployed_ yet :( https://learn.microsoft.com/en-us/azure/ai-services/openai/whats-new

**Comment by sabbadino** [comment]
Hello MS , any plan about this will be available?

**Comment by WhoIsDoctorWho** [comment]
Looks like availability is based not only on api version but on **a region of a deployment** as well.

We have three regions: 
EU2 - tool_choice="required" does work
CNE, AUE - tool_choice="required" does **NOT** work 

api_version="2024-04-01-preview"
Any thoughts on this?

**Comment by janaka** [comment]
> Looks like availability is based not only on api version but on **a region of a deployment** as well.
> 
> We have three regions: EU2 - tool_choice="required" does work CNE, AUE - tool_choice="required" does **NOT** work
> 
> api_version="2024-04-01-preview" Any thoughts on this?

@WhoIsDoctorWho I'm not surprised given others have said similar things in GH issues. The model is also a variable. My assumption these features are canary released and probably influenced by very large customers.

It's really poor from Azure not to even communicate the state of feature release clearly, forgot a roadmap of what's coming.

**Comment by minhduc0711** [comment]
> it will be interesting to see what happens when they release gpt-4o 2024-08-06 on the inferencing API as that's a bit useless without an updated REST API.

@janaka FYI, I've just tried [the newly released gpt-4o 2024-08-06](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#global-standard-model-availability) and `tool_choice=required` seems to function consistently across regions (I tried eastus, eastus2 and swedencentral).

**Comment by sabbadino** [comment]
Yes gpt 4o 2024-08-06 has just been delivered on azure and also structured output works ok, at least in Sweden

**Comment by janaka** [comment]
just been upgrading and test (via the C# lib) against a new 06-08-2024 deployment in eastus - though the Azure SDK doesn't have the REST API version add, so using reflection to set that).

- tool_choice=required - being accepted 
- parallel_tool_calls=false - being accepted
- structured output - checking out at the moment

**Comment by sabbadino** [comment]
@janaka , with latest 2.0 beta Ms provided nuget package the structured output option  worked without any hack in my machine

**Comment by minhduc0711** [comment]
Closing this as all of our deployments now accept `tool_choice=required`
```
3.5-france: OK
4o-mini-eastus: OK
4o-mini-sweden: OK
4o-france: OK
4o-northcentralus: OK
4o-sweden: OK
4o-2024-08-06-sweden: OK
4o-2024-08-06-eastus: OK
4o-2024-08-06-eastus2: OK
```

**Comment by 9hsein5** [comment]
It is still a bug currently with latest api version, not supported
