### ISSUE TITLE
[Se]  Implementation of TypeSpec 'infoblurb' Mechanism in Brownfield PRs

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-rest-api-specs#30370]
### API Spec link

NA

### API Spec version

NA

### Please describe the feature.

We need to set up a mechanism to insert a non-blocking, high-visibility comment in every brownfield PR for services not yet converted to TypeSpec. This is part of the Brownfields adoption plan, aiming to encourage early adoption of TypeSpec conversion. The comment should inform teams about the TypeSpec tool and offer hands-on assistance from the TypeSpec Onboarding Support team for early adopters. It's crucial that this comment does not block PR merging and can be suppressed by teams blocked from converting due to pending centralized work.

Criteria for the comment to appear:
- The PR is for handwritten swagger.
- No suppression for TypeSpec conversion has been applied.

Action:
- Add a non-blocking comment to the PR with predefined text encouraging early TypeSpec conversion and offering support.

This setup should not include any blocking warnings, only a non-blocking comment. The text of the comment should be as follows:

> *NOTE* - Brownfield services will soon be required to convert from OpenAPI to TypeSpec. The TypeSpec team has developed a [tool](https://azure.github.io/typespec-azure/docs/migrate-swagger/get-started) to assist with this transition. By converting early, you’ll receive hands-on assistance and provide valuable feedback to improve the tool. Contact [TypeSpec Onboarding Support](https://teams.microsoft.com/l/channel/19%3A906c1efbbec54dc8949ac736633e6bdf%40thread.skype/TypeSpec%20Discussion?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) to join a select group of early adopters and ensure a smooth transition.

**Comment by mikeharder** [comment]
I think this should be added to the existing check "TypeSpec Requirement", which already has the logic to determine greenfield vs brownfield.  Here's the conclusion of the check:

https://github.com/Azure/azure-rest-api-specs/blob/46b386376ab0d53228a7f366d28e44bac8d592c3/eng/scripts/TypeSpec-Requirement.ps1#L169-L175

After L170, the check should additionally:

* Print a warning (pointing to the spec file)
  * This should appear in the check summary and the "code review" tab, giving two places for spec authors to see it.
* Add a label `brownfield`
  * The label description should be a short URL pointing to TSP conversion instructions
  * Can be used for querying open PRs
  * Will also be used by the "Next Steps to Merge" (NSTM) comment generator to include the blurb

And last but not least:

* Update NSTM to include the blurb

**Comment by mikeharder** [comment]
@mario-guerra, @MattGertz: What should happen if check TypeSpecRequirement is suppressed?  Currently, the tool checks for suppressions very early, and skips all other analysis if the check is suppressed.  Since we want very much to avoid the tool failing or crashing if the spec author has suppressed it.

https://github.com/Azure/azure-rest-api-specs/blob/b88e6adfec1361cdafbea6200d0ef889f6f2fd20/eng/scripts/TypeSpec-Requirement.ps1#L83-L90

So if TSR is suppressed, it will also suppress all the brownfield notices.  Currently, I believe very few specs should have TSR suppressed, and any which do should be tracked by ARM or DP.

**Comment by mario-guerra** [comment]
@mikeharder it's fine if the infoblurb is suppressed when the TSR suppression is applied.

**Comment by mikeharder** [comment]
Mostly completed in https://github.com/Azure/azure-rest-api-specs/pull/31814.  Remaining work:

* Review and update notice text
* Add notice to "Next Steps to Merge" comment, based on presence of label "brownfield"

**Comment by mikeharder** [comment]
@mario-guerra, @MattGertz: This work item should be mostly complete. First, please review the text I'm currently using for the notice, which is shorter than what was suggested originally:

> Brownfield services will soon be required to convert from OpenAPI to TypeSpec. See https://aka.ms/azsdk/typespec.

I'd like to keep the message itself relatively short so it doesn't get cutoff in the GitHub UI, with a link to more details (that's also easier to update than the check itself).  But I can test a longer message and see how it looks.

Second, if possible, I'd like to defer adding the notice to the "Next Steps to Merge" comment until this component is moved to our new engineering system, so we don't need to make this change in our old system.  But, I can add it to the old system, if we think the current implementation of the notice isn't visible enough.
