### ISSUE TITLE
[Swagger ApiDocPreview] Failing with "Get-AzAccessToken is not recognized"

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#30411]
Example:

<img width="851" alt="image" src="https://github.com/user-attachments/assets/c039978f-8c15-49d8-9401-78ff6fe92dc0">

https://github.com/Azure/azure-rest-api-specs/pull/30405/checks?check_run_id=29610824063

**Comment by nickwalkmsft** [comment]
The Learn docs team is tracking this, I should have an update tomorrow.

**Comment by nickwalkmsft** [comment]
This has been fixed, runs are succeeding.
