### ISSUE TITLE
Azs.Backup.Admin: nextBackupTime and lastBackupTime should be treated as DateTime

### ISSUE THREAD

**Issue by daozha** [Azure/azure-rest-api-specs#3043]
@deathly809 
The "nextBackupTime" and "lastBackupTime" in BackupLocation.json are treated as string. In C# SDK these will be deserialized into format losing time zone info.
We need to treat these as DateTime, just as createdDateTime in Backups.json

**Comment by deathly809** [comment]
@sarangan12 Please assign to me and knithinc.  This is for the Azure Stack admin modules which we will be handling.  

This is a bug in the spec and we will have to propagate changes forward.  Will be a minor breaking change and will have to ask on how to handle this one.

**Comment by daozha** [comment]
Fixed in #3225
