### ISSUE TITLE
Azure API throttling (get VMs) and x-ms-ratelimit-remaining-subscription-reads

### ISSUE THREAD

**Issue by ggusev4** [Azure/azure-rest-api-specs#3044]
- Rest call to get VMs  frequently returns 429 status code ( for example,  every hour for entire day) with error pointed to calls limit reached:
>> Azure Resource Manager read/write per hour limit reached. Will retry in: 1200 seconds

- header value x-ms-ratelimit-remaining-subscription-reads of azure responses always contains big values 13000 - 14000, all other header values related to calls rate ( x-ms-ratelimit-remaining-subscription-writes, x-ms-ratelimit-remaining-tenant-reads., etc.)  are null.
For example we observed that the previous get call to azure that passed (was made less  than 1 sec before) exposed in the response  x-ms-ratelimit-remaining-subscription-reads > 13000.

The header values doesn't provide any real number about reaching the limit as it's supposed to be per https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits#retrieving-the-header-values

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
