### ISSUE TITLE
[FEATURE REQ] Add a new Versioning-Approved-Retired label that works just like all the other Versioning-Approved-* labels.

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-rest-api-specs#30652]
### API Spec link

N/A

### API Spec version

N/A

### Please describe the feature.

Azure service teams periodically retire service versions (especially previews and GAs after a breaking change is introduced). This causes a PR to be created which deletes the swagger files for that service version. We need this label so we can track this new metric so see things like how many service versions got retired this month, etc.

**Comment by mikeharder** [comment]
I think this is a one-line change:

https://dev.azure.com/devdiv/DevDiv/_search?action=contents&text=versioning-approved&type=code&lp=code-Project&filters=ProjectFilters%7BDevDiv%7DRepositoryFilters%7Bopenapi-alps%7D&pageSize=25&result=DefaultCollection/DevDiv/openapi-alps/GBmain//public/swagger-validation-common/src/breakingChanges.ts

**Comment by mikeharder** [comment]
@JeffreyRichter: Should I also add label `BreakingChange-Approved-Retired`?

**Comment by JeffreyRichter** [comment]
No, do not add BreakingChange-Approved-Retired. They are always retiring an existing version, not creating a new version to retire.

**Comment by JeffreyRichter** [comment]
That's awesome if it is just a 1-line fix! Best ROI yet!

**Comment by mikeharder** [comment]
Can you suggest a sample PR to trigger the requirement of a `Versioning-Approved` label?  Will this work?  I'm still waiting for checks to finish.

https://github.com/test-repo-billy/azure-rest-api-specs/pull/3513

**Comment by mikeharder** [comment]
PR: https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/579729

**Comment by JeffreyRichter** [comment]
This PR (https://github.com/Azure/azure-rest-api-specs-pr/pull/19649) should have Versioning-Approved-Benign removed and Versioning-Approved-Retired applied. Earlier today I added Versioning-Approved-Benign because -Retired didn't exist yet. This PR is what caused me to create this issue for you.

I would update the PR myself but I don't see the new label available to me yet.

**Comment by mikeharder** [comment]
My PR in test-repo-billy is working.  Next steps:

1. Deploy updated pipeline-bot to test-repo-billy
2. Test adding new label to https://github.com/test-repo-billy/azure-rest-api-specs/pull/3513
3. Add new label to azure-rest-api-specs and azure-rest-api-specs-pr
4. Deploy updated pipeline-bot to prod

**Comment by mikeharder** [comment]
@JeffreyRichter: Does this look good?

https://github.com/test-repo-billy/azure-rest-api-specs/pull/3513

Do we need to update anything else, like docs?

**Comment by mikeharder** [comment]
Closing unless there is remaining work.  The label has been added to both public and private repos, and the new pipeline-bot has been deployed.

**Comment by JeffreyRichter** [comment]
I just updated this PR - worked like a charm! Thank you so much especially for the blazingly fast turn around.
