### ISSUE TITLE
Resources_CreateOrUpdate

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#308]
When using the `ResourcesOperations.create_or_update` method in the Python SDK to set tags on an existing resource a CloudError is raised because the operation returns HTTP Code 202 (Accepted). The operation is successful in that the resource has the correct tags after the call.

The swagger for this command only lists 200 and 201 as valid response codes. Typically 202 kicks off a long running operation which (hopefully) returns a 200. It seems that 202 should be added as an acceptable response and that (possibly) the operation be modeled as a LRO so that the client is informed whether the operation succeeded or failed.

**Comment by adammila** [comment]
I came to report the same problem. However, contrary to what tjprescott says a 202 Accepted response never "returns a 200", so there's no simple way to report the result. Instead, I think there should be a way to obtain the provioning status of a resource in the same way that we can for resource groups.

**Comment by tjprescott** [comment]
@adammila the Python SDK (and presumably others?) will start a long running operation poller that will queries the state of the resource at intervals until the operation completes and a 200 is returned instead of 202. That's what I meant by returning a 200.

**Comment by yugangw-msft** [comment]
Looks like it was fixed
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/operations/resources_operations.py#L442
