### ISSUE TITLE
DomainRegistration/generateSsoRequest results in 404

### ISSUE THREAD

**Issue by justin-chizer** [Azure/azure-rest-api-specs#31031]
Any help on why it returns a 404 would be greatly appreciated. I was told I can use this command to change the nameservers.
https://github.com/Azure/azure-rest-api-specs/blob/f37b54b187bac95237c62478a10b94e9cff236f3/specification/web/resource-manager/Microsoft.DomainRegistration/stable/2024-04-01/examples/ListOperations.json#L51

```
az rest -m post -u https://management.azure.com/subscriptions/***/providers/Microsoft.DomainRegistration/generateSsoRequest\?api-version\=2024-04-01
```

**Comment by v-jiaodi** [comment]
@naveedaz Please help take a look, thanks.

**Comment by justin-chizer** [comment]
This is the MS support ticket that I have 2410080040014180

**Comment by justin-chizer** [comment]
Hi @naveedaz!

Any update here?

**Comment by ian-park-fad** [comment]
@naveedaz 

please update....

**Comment by justin-chizer** [comment]
This issue is causing much headache for my support engineer and the product team that she is working with. No one is happy. 
We need a solution that allows customers to access the Wild West Domains portal so we can manage the domain we own. 
I understand that managing through the Azure Portal is not an option. But we still own the domain. 
@naveedaz

**Comment by naveedaz** [comment]
@joerob-msft  Can you please take a look?

**Comment by joerob-msft** [comment]
> Any help on why it returns a 404 would be greatly appreciated. I was told I can use this command to change the nameservers.
> 
> [azure-rest-api-specs/specification/web/resource-manager/Microsoft.DomainRegistration/stable/2024-04-01/examples/ListOperations.json](https://github.com/Azure/azure-rest-api-specs/blob/f37b54b187bac95237c62478a10b94e9cff236f3/specification/web/resource-manager/Microsoft.DomainRegistration/stable/2024-04-01/examples/ListOperations.json#L51)
> 
> Line 51 in [f37b54b](/Azure/azure-rest-api-specs/commit/f37b54b187bac95237c62478a10b94e9cff236f3)
> 
>  "name": "Microsoft.DomainRegistration/generateSsoRequest/Action", 
> ```
> az rest -m post -u https://management.azure.com/subscriptions/***/providers/Microsoft.DomainRegistration/generateSsoRequest\?api-version\=2024-04-01
> ```

Managing the domain through the GoDaddy portal is no longer supported.

If you need to change the nameservers please open a support ticket and they can help update these.

In the future you will be able to manage these in the Azure Portal, but this feature is not available yet.

**Comment by justin-chizer** [comment]
@joerob-msft We need to make nameserver changes during our low traffic times which for one of our domains will occur at 7am PST Saturday. Having someone from the Azure product team make that change is not scalable. We have over 20 domains we are trying to manage. Please try to escalate the feature in Azure so we can do this on our own and not bother support or product team.
