### ISSUE TITLE
[TypeSpec Validation] Enforce SDK emitter configuration for greenfield services

### ISSUE THREAD

**Issue by raych1** [Azure/azure-rest-api-specs#31043]
**Description**
Greenfield services are required to use TypeSpec to describe their service APIs, and an error will be reported if a greenfield service doesn't use TypeSpec. 

In addition, we want to have the SDK generated using the TypeSpec in the spec PR instead of using the swagger. This allows both service teams and reviewers to evaluate and test the SDK code at early stage. Otherwise, it is too late to re-work the API spec after the spec PR has been merged and gaps are found in the generated SDK.

This is an [example spec PR](https://github.com/Azure/azure-rest-api-specs/pull/30455) which is a green field service and didn't configure the SDK emitter. As a result, the spec PR was merged without reporting the SDK generation issue. After the spec PR was merged, it was discovered that the SDK could not actually be generated. 

**Request**
For MPG, .NET, Java, Python, JS, and Go emitters should all be configured in the `tspconfig.yaml`.

@mikeharder @lirenhe

**Comment by mikeharder** [comment]
Should be similar to existing check, but would need to be scoped to only greenfields:

https://github.com/Azure/azure-rest-api-specs/blob/c70915c5016ca848277650fff63c0ce7370fb997/eng/tools/typespec-validation/src/rules/emit-autorest.ts#L27-L35

**Comment by josefree** [comment]
This is not only for greenfield services. It should apply to brownfield services converted to TypeSpec as well

**Comment by wanlwanl** [comment]
dup to https://github.com/Azure/azure-sdk-tools/issues/9355, close this one
