### ISSUE TITLE
Should `SnapshotUpdate` reference `SnapshotUpdateProperties`?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#3105]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/disk.json#L1117

Today it's referencing `DiskUpdateProperties` which has `DiskSku`. Maybe there should be a type `SnapshotUpdateProperties` that uses `SnapshotSku` (which already exists)?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
