### ISSUE TITLE
VirtualNetworkGateway exposes POST operation that returns XML payload wrapped in JSON

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#3129]
```
POST "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworkGateways/{virtualNetworkGatewayName}/supportedvpndevices": {
"operationId": "VirtualNetworkGateways_SupportedVpnDevices",
"description": "Gets a xml format representation for supported vpn devices.", 
```
there is no documentation provided in description field for the format that the caller should expect. The sample contains XML with an error on one of the fields (tag cannot be assigned a value). 

Fixing the return type to XML will fix only the payload protocol violation in the swagger declaration but will be a breaking change as well. It is strongly advised to have proper JSON serializable types in swagger especially for VirtualNetworkGateway where all the other endpoints produce JSON. 

Please keep in mind that most of our generated SDK’s (if not all) do not support XML payloads at all and SDK user will still have to make direct REST calls manually (because I believe we will just skip the method that produces XML).

**Comment by MikhailTryakhov** [comment]
fixed, please review
