### ISSUE TITLE
[TypeSpec APIView] Disable old version of check running in unified pipeline

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#31867]
Should be similar to the PRs removing Swagger APIView (unintentionally split across two PRs):

https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/592698
https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/592748

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/9518
