### ISSUE TITLE
arm-logic/2015-02-01-preview missing $filter parameter for workflow trigger history

### ISSUE THREAD

**Issue by antmeehan** [Azure/azure-rest-api-specs#320]
According to https://msdn.microsoft.com/library/azure/mt643788.aspx the 'Get trigger history for the workflow' action has a `$filter` parameter:

```
https://{endpoint}/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows/{workflowName}/triggers/{triggerName}/histories?api-version=2015-08-01-preview&$filter=status eq 'Succeeded'
```

However, https://github.com/Azure/azure-rest-api-specs/blob/48bc044a6288328f0d3e545eb099a4732d97820f/arm-logic/2015-02-01-preview/swagger/logic.json#L966 is missing the parameter in the definition.

**Comment by amarzavery** [comment]
@tonytang-microsoft-com - Can you take a look at this issue?

**Comment by tonytang-microsoft-com** [comment]
Fixed by PR 327
