### ISSUE TITLE
ApiManagement - Adding Api to Product fails, if the product has space 

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-rest-api-specs#3260]
Customer is using Add-AzureRmApiManagementApiToProduct.

When their ProductId has a space, this command will failed at this error:
[error]Unable to configure Azure ApiManagement. 'productId' does not match expected pattern '(^[\w]+$)|(^[\w][\w\-]+[\w]$)'.

This is a bug in the Swagger spec. The service side does not have any such limitation.

**Comment by solankisamir** [comment]
Original Issue https://github.com/Azure/azure-sdk-for-net/issues/4458

**Comment by marstr** [comment]
Triaged, removing myself as assignee.
