### ISSUE TITLE
Child links and SDKs

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-rest-api-specs#328]
It will be easiest to explain with an example. Say you want to get the private IP address of a VM.

To do this, you need to Get the VirtualMachine, look at the NetworkProfile, pick one of the NetworkInterfaceReferences and then do a GET on that URL to retrieve the actual NIC configuration, including ip configurations and their private addresses.

Unfortunately, this is cumbersome, at least in the Go SDK. The Get operation for the InterfacesClient takes resourceGroup and interfaceName. This requires me to manually string decompose the InterfaceReference from the VM response.

What is the recommendation for how SDKs should handle this? How do the other SDKs handle this scenario?

**Comment by lmazuel** [comment]
I'm glad to see your issue, same problem in Python:
https://github.com/Azure/azure-sdk-for-python/issues/534

We already got some discussion to allow "get" to take the full id to avoid parsing, but we didn't achieve anything yet in that way.

**Comment by devigned** [comment]
Yep... All of the AutoRest generated languages should have generic HTTP methods (GET, PUT, POST, etc...) which provide auth, retry, and the rest of the client middleware. That way you can make generic calls to Azure without needing a generated method.

I think we should also provide helpers for parsing ARM URIs, but that's a bit of a mask over this issue.

**Comment by kirthik** [comment]
This is an autorest issue - https://github.com/Azure/autorest/issues/1824
