### ISSUE TITLE
[Monitor] Add serviceBusRuleId to the DiagnosticSettings resource

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-rest-api-specs#3293]
The attribute serviceBusRuleId was removed from the spec, but it is still being used and supported by the back end.

**Comment by annatisch** [comment]
Thanks @gucalder - are you able to specify which version of the preview/stable spec that this was removed from?

**Comment by annatisch** [comment]
The only place I can see where this might apply is in Diagnostic setting - the preview vs the most resent stable spec:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/microsoft.insights/stable/2016-09-01/serviceDiagnosticsSettings_API.json#L305

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/microsoft.insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L383

Are you able to comment @vcanaa?

**Comment by annatisch** [comment]
@gucalder - seems with the merging of PR #3285 that this can now be closed?

**Comment by gucalder** [comment]
Correct, this can be closed.
