### ISSUE TITLE
[Network] IP address is required for VNET's check IP availability call

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#3307]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2017-06-01/virtualNetwork.json#L720

The specs say this is not required, but if you try to make the call without it you get this error:

```
Private IP address is null or empty in the CheckIpAddressAvailability call. Specify IpAddress=$(ipaddress) as a query parameter in the request URI.
```

It should be required=True

**Comment by MikhailTryakhov** [comment]
fixed in swagger, would be released in a couple of days https://github.com/Azure/azure-rest-api-specs/pull/4339
