### ISSUE TITLE
DuplicateModelCollsion error in automation swaggers

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#3317]
SDKs cannot be generated from automation swaggers due to DuplicateModelCollsion error:
```
ERROR (Fatal/DuplicateModelCollsion): Duplicated model name with non-identical definitions
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/runbook.json:1056:4 ($.definitions.JobStreamProperties)
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/job.json:780:4 ($.definitions.JobStreamProperties)
    - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/dscCompilationJob.json:561:4 ($.definitions.JobStreamProperties)
```

Reason for DuplicateModelCollsion: if two files that are in the same “tag” in the Readme defines the same model name Foo, both object have to be exactly (at the comma exactly level) the same, or they have to be a reference to an external common file

**Comment by andyw248** [comment]
JobStreamProperties are now exactly the same, to the comma level, in all three files. Note that runbook.json and dscCompilationJob.json also have new versions (2018-06-30 and 2018-01-15, respectively).
