### ISSUE TITLE
Examples are broken on AzureFirewalls

### ISSUE THREAD

**Issue by EvgenyAgafonchikov** [Azure/azure-rest-api-specs#3347]
Branches and API version affected
master (2018-04-01), Network-July-Release (2018-04-01, 2018-06-01)

1. There are errors like below. Need to be added to [suppressions](https://github.com/Azure/azure-rest-api-specs/blob/Network-July-Release/specification/network/resource-manager/readme.md#suppression)
```
ERROR (RequiredPropertiesMissingInResourceModel/R2020/RPCViolation): Model definition 'AzureFirewall' must have the properties 'name', 'id' and 'type' in its hierarchy
```
Command to check:
```
<specs repo path>\specification\network\resource-manager>autorest --azure-validator --openapi-type=arm --tag=package-2018-06
```
2. Multiple examples are broken.
Command to check:
```<specs repo path>\specification\network\resource-manager>oav validate-example Microsoft.Network\stable\2018-06-01\azureFirewall.json```

**Comment by EvgenyAgafonchikov** [comment]
@joannakleong, could you please have a look

**Comment by joannakleong** [comment]
PR merged of fix https://github.com/Azure/azure-rest-api-specs/pull/3350
