### ISSUE TITLE
Zones is missing in VirtualMachineScaleSetVM

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-rest-api-specs#3358]
Copied from https://github.com/Azure/azure-sdk-for-go/issues/2183 from @feiskyer

`Zones` is missing in VirtualMachineScaleSetVM. We need this to support availability zones in Kubernetes. Kubernetes is using 2017-12-01 compute api, but zones is also missing in latest 2018-04-01 version.

`Zones` has already been in VirtualMachineScaleSet, so we need add this also to VirtualMachineScaleSetVM.

https://github.com/Azure/azure-sdk-for-go/blob/fbe7db0e3f9793ba3e5704efbab84f51436c136e/services/compute/mgmt/2018-04-01/compute/models.go#L7548-L7570

Could some one help to add this?

cc @brendandburns @khenidak
cc @joshgav @jhendrixMSFT

**Comment by marstr** [comment]
Triaged, removing my assignment.

**Comment by joshgav** [comment]
cc @hyonholee

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
