### ISSUE TITLE
storage.json 2016-01-01 Usage_List does not flatten

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#340]
In storage.json 2016-01-01, the `Usage_List` method remove the following from the 2015-06-15 spec:
```json
        "x-ms-pageable": {
          "nextLinkName": null
        }
```
Which makes the method return `UsageListResult` instead of `List<Usage>`. This seems like an unnecessary breaking change in every language.

**Comment by lmazuel** [comment]
@amarzavery @devigned ?
Makes Python ugly too:
```python
for usage in storage_client.usage.list().value:
    print('\t{}'.format(usage.name.value))
```
