### ISSUE TITLE
read only field

### ISSUE THREAD

**Issue by sheenaajay** [Azure/azure-rest-api-specs#3447]
Request for "readOnly" field for all read only properties

For example provisioningState doesnt have the readOnly field
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-04-01/networkSecurityGroup.json#L805

**Comment by annatisch** [comment]
@deepakrajendranmsft @MikhailTryakhov - do you have any thoughts on this?

**Comment by MikhailTryakhov** [comment]
provisioningState is never may be readonly
