### ISSUE TITLE
UsageDetailsExpand - 2018-06-30 is not working

### ISSUE THREAD

**Issue by jackting73** [Azure/azure-rest-api-specs#3480]
@ampravinr @annatisch 
By following the article: https://docs.microsoft.com/en-us/rest/api/consumption/usagedetails/listbybillingperiod#usagedetailsexpand

1. I tried to get the UsageDetails and MeterDetails with version 2018-06-30, but it seems only support 2018-05-31 now ?
2. I then try the 2018-5-31 version and with the parameter "meterDetails" and "additionalProperties" in the UsageDetailsExpand, but seems only shows partial meterDetails and without any additionalProperties ... Any idea how to make the additionalProperties appear ?

=Here is my sample request:
https://management.azure.com/{subscriptionId}/providers/Microsoft.Billing/billingPeriods/201809-1/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&api-version=2018-05-31
=Here is the response:
 {
            "id": "/subscriptions/{subscriptionId}/providers/Microsoft.Billing/billingPeriods/201809-1/providers/Microsoft.Consumption/usageDetails/c92c7237-9b9f-c7c7-3c93-52aa432c054a",
            "name": "c92c7237-9b9f-c7c7-3c93-52aa432c054a",
            "type": "Microsoft.Consumption/usageDetails",
            "tags": null,
            "properties": {
                "billingPeriodId": "/subscriptions/{subscriptionId}/providers/Microsoft.Billing/billingPeriods/201809-1",
                "usageStart": "2018-06-12T00:00:00.0000000Z",
                "usageEnd": "2018-06-13T00:00:00.0000000Z",
                "instanceId": "/subscriptions/{subscriptionId}/resourceGroups/SkyWork/providers/Microsoft.RecoveryServices/vaults/SkyWork",
                "instanceName": "SkyWork",
                "meterId": "6551548b-7e61-4f51-896e-eb907d256b95",
                "usageQuantity": 0.016128,
                "pretaxCost": 4.847141376,
                "currency": "TWD",
                "isEstimated": false,
                "subscriptionGuid": "0291f03d-0332-472c-be7f-3f9d1c902310",
                "meterDetails": {
                    "meterName": "Protected Instances",
                    "meterCategory": "Recovery Services",
                    "unit": "Instances",
                    "meterLocation": "All Regions",
                    "meterSubCategory": "Backup"
                }
            }
        },

**Comment by jackting73** [comment]
@sarangan12 
Hi Sarangan,
From the API response, I can't see the "totalIncludedQuantity" in the "meterDetails" and also no "additionalProperties" in the "properties", since the article below describe we can get the Late Arriving Data from the addtionalProperties. So, no sure these information can be got in 2018-6-30 version(but seems not work now) or I use the wrong API request.
Please help indicate how to get the totalIncludedQuantity and additionalProperties, thanks.

Article Link: [](https://azure.microsoft.com/en-us/blog/azure-usage-forecast-api-and-other-updates-from-may/)

**Comment by ms-premp** [comment]
Hi @jackting73 

1. API version 2018-06-30 is available.. Please give it a try.

2. The example for late arriving data is here [late-arriving-data](https://docs.microsoft.com/en-us/rest/api/consumption/#late-arriving-data)

The additionalProperties field will be present in response, if there are some additional info available to show, else it will be omitted to optimize the response payload size.

Thanks

**Comment by jackting73** [comment]
Hi @ms-premp 

Thanks for your help. 

1. For the API version 2018-6-30, it works now.
2. For the late arriving data of addtionalProperties or other fields, seems still no luck, here is my sample:

=request1=
https://management.azure.com/subscriptions/{mySubscriptionId}/providers/Microsoft.Consumption/usageDetails?api-version=2018-03-31&$expand=properties/additionalProperties
=snippet response=
https://billingapi20180630.blob.core.windows.net/billing/apiResponse.PNG
=usage report=
https://billingapi20180630.blob.core.windows.net/billing/billingAPIversion20180630.PNG

=request2=
https://management.azure.com/subscriptions/{mySubscriptionId}/providers/Microsoft.Billing/billingPeriods/201810-1/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&api-version=2018-06-30
=totalIncludedQuntity not showing =
https://billingapi20180630.blob.core.windows.net/billing/noTotalIncludedQuantity.PNG

You may see there could be two issues here:
1. From the usage report, there will have some resources consumed quantity(7/11/2018) from the previous billing cycle then to be calculated in this billing cycle, but I can't get this consumed quantity by using this API. (Will the consumed quantity from previous billing cycle should be showing in the additionalProperties?)
2. From the request2, not sure why some of the fields in  the meterDetails not showing(ex: additionalProperties/service name/service tier).  I have searched all the API response I got then didn't see any. May I know how to make the field appear ? 

Thanks.

**Comment by ms-premp** [comment]
Hi @jackting73 

1. The **late arriving data** feature is primarily for third party services, that have delays in reporting usage. Please refer to the details here  [Consumption Features](https://azure.microsoft.com/en-us/blog/azure-usage-forecast-api-and-other-updates-from-may/).
For your case, you should make a call to get usage for previous billing period. Please refer [Usage By Billing Period](https://docs.microsoft.com/en-us/rest/api/consumption/usagedetails/listbybillingperiod). Before making this request please get a list of available billing periods for your subscription and use the desired billing period Id for getting usage. Refer here for more details [How to get billing periods](https://docs.microsoft.com/en-us/rest/api/consumption/#getting-list-of-billing-periods)

2. Service Name and Service Tier features are available only for **Enterprise Customers**.  Please refer to the details here [Consumption Features](https://azure.microsoft.com/en-us/blog/azure-usage-forecast-api-and-other-updates-from-may)


Thanks

**Comment by jackting73** [comment]
Hi @ms-premp 

Really appreciate, seems I misunderstanding the field and features.
No questions here, thanks.

**Comment by ms-premp** [comment]
np @jackting73 .. you are welcome.
@sarangan12 please close this issue.

**Comment by anurag8899** [comment]
I am trying to pull amortizedcost but when i am trying this API:
https://management.azure.com/subscriptions/{subid}/providers/Microsoft.Billing/billingPeriods/202204/providers/Microsoft.Consumption/usageDetails?$expand=meterDetails,additionalProperties&metric=AmortizedCost&api-version=2018-05-31"
it is giving me this : {'error': {'code': '429', 'message': 'Too many requests. Please retry after 60 seconds.'}}
help me how to get amortized cost with meterdetails and cost in it
