### ISSUE TITLE
How to create vmimage via REST API?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-rest-api-specs#3484]
In https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json, there are only several APIs to list the vmimage. But how to create vmimage via REST API?

**Comment by lmazuel** [comment]
@yugangw-msft ?

**Comment by bingosummer** [comment]
Thanks @yugangw-msft for your help.

What we are doing now is to publish a Windows image on Windows, via a specific Powershell module `C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Compute\PIR.psd1`. Then we use the [vmimage_list](https://github.com/Azure/azure-rest-api-specs/blob/9754d04e95bc4ffe16186aa76f652773923f5e10/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json#L820) API to list the available versions. E.g.
```
    offer: bosh-windows-server-1709
    publisher: pivotal
    sku: 1709-9plus
    version: 1709.10.018001
```
Since the publishing depends on a specific powershell module, so we can't publish an ubuntu image in Linux. So we raised this issue to check whether a REST API can do the same work as PIR.psd1.

For the two solutions, I think, solution 1 doesn't work because we want to publish an image and every one can use the image to create VM. Solution 2 seems worth to have a try. I guess, creating VM from a gallery image is different from creating VM from a vmimage. Will `shared gallery image` replace `marketplace image` in future?

Additionally, there are so many concepts about images. vmimage (aka VirtualMachineImage), platform image, gallery image, shared gallery image, marketplace image and managed image. Is there a doc to describe what these concepts mean and the difference?

**Comment by yugangw-msft** [comment]
> So we raised this issue to check whether a REST API can do the same work as PIR.psd1.
I don't believe so. Based on the PS module you mentioned, It is from RDFE mode and this repository contains pretty much ARM only APIs

    >  creating VM from a gallery image is different from creating VM from a vmimage. 
It is different but simple, that in the payload, you set the `storageProfile.imageReference.id` to the resource id of a particular gallery image version

   > Will shared gallery image replace marketplace image in future?
I don't think so. Platform image repository should still be the main channel for users to access common images. 

   > there are so many concepts about images
AFAIK, `vmimage` (based on the context),  `platform image` , `marketplace image`, are same things. Subtle differences among them are some are free, some have plan info so you pay extra, and some have proprietary software installed that you need to accept the terms before use them.
`managed image` is ARM only, associate with the resource of `Microsoft.compute/Images`
`gallery image` is ARM only, associate with the child resource `Microsoft.Compute/galleries/{galleryName}/images`

**Comment by bingosummer** [comment]
@yugangw-msft , very detailed explanation . I appreciate your help.
