### ISSUE TITLE
network paging extension error

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#349]
The network Swagger file has an error

The latest codegen enforce the check for paging extension to make sure there has a property in the response to match the property name specified in extension.

This file presents an error on Travis.

**Comment by xingwu1** [comment]
This is valid issue for network swagger file.

**Comment by amarzavery** [comment]
[Usages_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-03-30/swagger/network.json#L3147)
[UsagesListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-03-30/swagger/network.json#L6756)

**Comment by amarzavery** [comment]
@deepakrajendranmsft - Can you please verify whether Usages_List is truly pageable? Does it support nextLink? The extension has been defined with nextLink however the model UsagesListResult does not have nextLink as a modelProperty. If this is not a pageable operation and you still want flattening (IEnumerable\<Usage\>) to be returned then please explicitly set nextLink property of the x-ms-pageable extension to null. Check the docs over [here](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-pageable).

[Usages_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-03-30/swagger/network.json#L3147)
[UsagesListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-03-30/swagger/network.json#L6756)

**Comment by lmazuel** [comment]
@amarzavery @deepakrajendranmsft still broken

**Comment by lmazuel** [comment]
I just tested the new file 2016-06-01 and it's broken too. What are your plan to fix that?
Thanks,
@amarzavery @deepakrajendranmsft
