### ISSUE TITLE
compute paging error

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#352]
The compute composite Swagger file has an error

The latest codegen enforce the check for paging extension to make sure there has a property in the response to match the property name specified in extension.

This file presents an error on Travis.

**Comment by xingwu1** [comment]
This is valid issue for ListUsagesResult of Usage_List.

**Comment by amarzavery** [comment]
@huangpf @sauryadas 

 Can you please verify whether Usages_List is truly pageable? Does it support nextLink? The extension has been defined with nextLink however the model UsagesListResult does not have nextLink as a modelProperty. If this is not a pageable operation and you still want flattening (IEnumerable\<Usage\>) to be returned then please explicitly set nextLink property of the x-ms-pageable extension to null. Check the docs over [here](https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-pageable).

**Comment by huangpf** [comment]
I will check with the team, but this spec was converted from the Hyak->Swagger tool by your team, so maybe the bug (if any) is from there.

BTW, can the code gen tool not enforce the check?

**Comment by amarzavery** [comment]
The hyak to swagger converter was not 100% accurate and it just gave the service teams something to start with rather than service teams writing the swagger spec from scratch. This bug was caught as a larger goal of creating a linter for the spec. Now that it has ben caught, please make sure to resolve this at the earliest.

**Comment by huangpf** [comment]
That's a very valid ask, and we would double check it, and fix it.

But instead of ad-hoc check and fix, can you do a sweep check on the big specs, so that we can fix them all? Thanks. + @hyonholee

**Comment by amarzavery** [comment]
As I said this is a part of a larger goal. The Swagger spec linter (winter) is coming !! #GOT ;)
@tbombach

**Comment by huangpf** [comment]
The usage list API doesn't seem to be pageable, but some others with this property defined do not seem to work properly in AutoRest generated Node.js SDK & thus CLI.

Please refer to:
https://github.com/Azure/azure-xplat-cli/issues/2961
https://github.com/Azure/azure-xplat-cli/issues/2960

**Comment by lmazuel** [comment]
Close this one, it's ok now. Thanks all!
