### ISSUE TITLE
Azure Maps client SDK

### ISSUE THREAD

**Issue by cornem** [Azure/azure-rest-api-specs#3525]
Are there any plans to create a client SDK for the Azure Maps service? At the moment, only a management SDK is available.

**Comment by dsgouda** [comment]
@yuqi2 Please take a look since you have worked on the Management Maps Specs in the past

**Comment by dsgouda** [comment]
@jp94 could you take a look

**Comment by rbrundritt** [comment]
We do plan to expose a swagger endpoint publicly so that anyone can create client libraries using Autorest. We are still going through and testing and verifying that the generated libraries are correct before publishing this publicly.

**Comment by dsgouda** [comment]
@cornem hope that answers your query. Feel free to open another issue if you have further questions.

**Comment by anderejd** [comment]
Please re-open and post a link here when the OpenAPI specification is published.

**Comment by dsgouda** [comment]
I shall leave that to @rbrundritt

**Comment by rbrundritt** [comment]
An open source .NET client has been created here: https://github.com/perfahlen/AzureMapsRestServices An official .NET client is planned by the Azure Maps team later this year.
