### ISSUE TITLE
Wrong response in ListCertificates.json (Microsoft.Web)

### ISSUE THREAD

**Issue by SteveVaneeckhout** [Azure/azure-rest-api-specs#3526]
https://github.com/Azure/azure-rest-api-specs/blob/41038700e0b39554265f2a1c1ae699eb484500a1/specification/web/resource-manager/Microsoft.Web/stable/2016-03-01/examples/ListCertificates.json#L10

According to this file, the response should start with `{ "value": [ ... ] }` but the real response (taken from Fiddler) starts immediately with the array: `[{"id":"/subscriptions/[subscriptionId]/resourceGroups/[customerName]/providers/Microsoft.Web/certificates/DE6...`

This results in the Azure SDK and JSON.NET not being able to deserialize the response: https://github.com/Azure/azure-libraries-for-net/issues/51

**Comment by marstr** [comment]
Triaged and removing my assignment.

**Comment by AnilKongariMSFT** [comment]
@SteveVaneeckhout, Thank you for raising this issue up. We were able to reproduce the issue and have brought this to the attention of the Azure App Services product group to see if this is something they can fix. 

I have posted an alternative workaround to unblock the scenario at below MSDN Link.
https://social.msdn.microsoft.com/Forums/en-US/a01f6487-0164-4d52-b3cc-110055090d2b/fluent-management-api-appservicesappservicecertificateslist-always-throws-an-error?forum=windowsazurewebsitespreview 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
