### ISSUE TITLE
BackupStatus not available in the ApiVersion written in the Swagger

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#3547]
The declaration of backupStatus is inside the 2017-07-01 file:
https://github.com/Azure/azure-rest-api-specs/blob/ccefbaf343f2c71f3314e93c149b48e9e76d2e90/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2017-07-01/bms.json#L67-L112

However, looking at ARM endpoint, this does not exists:
```json
      {
        "additionalProperties": {
          "apiProfiles": [
            {
              "apiVersion": "2016-06-01",
              "profileVersion": "2018-06-01-profile"
            }
          ]
        },
        "aliases": null,
        "apiVersions": [
          "2016-06-01"
        ],
        "locations": [
          "West US",
          "East US",
          "North Europe",
          "West Europe",
          "Brazil South",
          "East Asia",
          "Southeast Asia",
          "North Central US",
          "South Central US",
          "Japan East",
          "Japan West",
          "Australia East",
          "Australia Southeast",
          "Central US",
          "East US 2",
          "Central India",
          "South India",
          "West Central US",
          "Canada Central",
          "Canada East",
          "West US 2",
          "UK South",
          "UK West",
          "Korea Central",
          "Korea South",
          "France Central",
          "Central US EUAP",
          "East US 2 EUAP"
        ],
        "properties": null,
        "resourceType": "locations/backupStatus"
      },
```

And when people try to use the generated SDK out of it, create this message:

> Message: The resource type 'locations/backupStatus' could not be found in the namespace 'Microsoft.RecoveryServices' for api version '2017-07-01'. The supported api-versions are '2016-06-01,2016-08-10,2016-05-01,2015-12-15,2015-12-10,2015-11-10,2015-06-10,2015-08-10,2015-08-15,2015-03-15'

Ref:
https://github.com/Azure/azure-sdk-for-python/pull/3030

**Comment by lmazuel** [comment]
FYI @johanste

**Comment by DheerendraRathor** [comment]
@lmazuel I've updated ARM endpoints to accept 2017-07-01.

**Comment by lmazuel** [comment]
Thanks @DheerendraRathor ! The customer who got the issue is using ukwest, is what you did available there as well?

**Comment by lmazuel** [comment]
Ok, I see it too, with even "ukwest". Thanks!
