### ISSUE TITLE
resources.resources paging error

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#355]
The resources.resources Swagger file has an error

The latest codegen enforce the check for paging extension to make sure there has a property in the response to match the property name specified in extension.

This file presents an error on Travis.

**Comment by amarzavery** [comment]
[ResourceProviderOperationDetailListResult](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-02-01/swagger/resources.json#L2272)

[ResourceProviderOperationDetails_List](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-02-01/swagger/resources.json#L1519)

**Comment by amarzavery** [comment]
@vivsriaus - Please send a PR for deleting the provider operation paths from the swagger spec as they rightly belong to Authorization.

**Comment by vivsriaus** [comment]
@amarzavery Here you go: https://github.com/Azure/azure-rest-api-specs/pull/357
