### ISSUE TITLE
GraphRbac ResetPassword support

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#358]
Hi,

I have a user who ask for ResetPassword support in GraphRbac SDK:
https://msdn.microsoft.com/Library/Azure/Ad/Graph/api/users-operations#ResetUserPassword

I don't see the operation in the 1.6-internal file, neither in the the current OpenPR 1.6:
https://github.com/Azure/azure-rest-api-specs/pull/344

Could someone add this in the Swagger file?

For the record, the Python issue:
https://github.com/Azure/azure-sdk-for-python/pull/633

Thanks!

**Comment by amarzavery** [comment]
#344 fixes this.
