### ISSUE TITLE
VM Scaleset Instance PowerStatus

### ISSUE THREAD

**Issue by rezamt** [Azure/azure-rest-api-specs#3593]
Hi I am trying to get the power status of Azure ScaleSet instances as you can see them on the dashboard. 

By looking at documentation, you need to call [GetInstanceView ](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/getinstanceview) but I am getting only the ProvisioningState. (There is no $expand  attributes either)

So my question is how am I suppose to get the "PowerState/stopped" etc?   

Here is the result of API Call :
`
{
  "virtualMachine": {
    "statusesSummary": [
      {
        "code": "ProvisioningState/succeeded",
        "count": 2
      }
    ]
  },
  "extensions": [
    {
      "name": "web",
      "statusesSummary": [
        {
          "code": "ProvisioningState/succeeded",
          "count": 2
        }
      ]
    }
  ],
  "statuses": [
    {
      "code": "ProvisioningState/succeeded",
      "level": "Info",
      "displayStatus": "Provisioning succeeded",
      "time": "2018-08-06T05:42:36.6425181+00:00"
    }
  ]
}
`

**Comment by rezamt** [comment]
Any update on this? am I right or I am missing something?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
