### ISSUE TITLE
DatabaseAccountListKeysResult incorrectly models received response

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#3603]
Operation ```DatabaseAccounts_ListKeys``` returns a [DatabaseAccountListKeysResult](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json#L1772) however this doesn't accurately model the response body.
```json
{
  "primaryMasterKey": "xxx",
  "secondaryMasterKey": "xxx",
  "primaryReadonlyMasterKey": "xxx",
  "secondaryReadonlyMasterKey": "xxx"
}
```
Note the missing ```properties``` object for the read-only keys.  I suspect the confusion comes from the x-ms-client-flatten setting; this is purely an SDK convenience mechanism and does not participate in modeling payloads.  The swagger needs to be updated as now there is no way to retrieve the read-only keys.

**Comment by shurd** [comment]
Thank you for identifying this model error in the swagger. We will make the needed correction for the account keys response. We are tracking this internally as work item 469202. ETA for the update is August 2019.

**Comment by shurd** [comment]
The change has been merged so the swagger correctly models the response when listing keys.
