### ISSUE TITLE
App service environments APIs in web package return XML instead of JSON

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#3621]
Example API
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/AppServiceEnvironments.json#L591
Calling this with invalid params returns an XML response
```xml
<Error xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/windowsazure"><Code>InternalServerError</Code><Message></Message></Error>
```
I also noticed https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/AppServiceEnvironments.json#L549 returned an XML response in a non-error case.
The swagger states these APIs consume/produce JSON which is incorrect.  Note that most code generators don't support XML payloads so if the RP returning XML is expected it will take some significant work to get the SDKs working.

**Comment by naveedaz** [comment]
@jhendrixMSFT I am not able to repro this issue using ARM client. What is the Content-Type header set to for the requests you tried?

**Comment by jhendrixMSFT** [comment]
I can no longer repro this as well, looks like it's been fixed.
