### ISSUE TITLE
ApplicationInsights web tests Create or Update can return a 201

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#3638]
Hit a customer:
https://github.com/Azure/azure-sdk-for-python/issues/3141

It seems operation "WebTests_CreateOrUpdate" can return a 201 based on the exception the customer got, which is not described in the Swagger:
https://github.com/Azure/azure-rest-api-specs/blob/ddbce7c26366d3503a8694b0e045f3a3e158aada/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/webTests_API.json#L128-L135

**Comment by lmazuel** [comment]
Tagging you @alexeldeib as last author on this file, please tag the right owner if not you :). Thanks!

**Comment by lmazuel** [comment]
Side note: I worked with the customer to patch its Python code to add 201 as a correct status code, and he confirmed it worked. So should be really simple.
Thanks,

**Comment by jhendrixMSFT** [comment]
Also hit this in Go https://github.com/Azure/azure-sdk-for-go/issues/2465

**Comment by lmazuel** [comment]
Service team confirmed they hot-fixed the server to stop returning 201.
