### ISSUE TITLE
beginRunCommand -  Can I specify a script instead of set of command with this VM node.js API

### ISSUE THREAD

**Issue by karungithub** [Azure/azure-rest-api-specs#3645]
Hi,
I am trying to run a script on the VM to mount and unmount certain volumes. Is it possible to have all these command in script and specify the script file in beginRunCommand to be executed.  The script that I have is little bit too long to provide all the commands in the API.
Also, do you have any tests that show the usage of the beginRunCommand().

Thanks,
-Karun

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
