### ISSUE TITLE
linuxProfile should be optional for AKS cluster

### ISSUE THREAD

**Issue by metacpp** [Azure/azure-rest-api-specs#3703]
The linuxProfile is required for AKS creation:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservices/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L979

But if end user chooses to create the AKS from Azure portal, it does not require the linuxProfile to be set.

The API spec should be consistent with behavior from Azure portal.

This causes issue raised by Terraform user:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1806

I also opened an issue on GO SDK team to track it:
https://github.com/Azure/azure-sdk-for-go/issues/2519

**Comment by annatisch** [comment]
Adding @mboersma

**Comment by mboersma** [comment]
I don't see that `linuxProfile` is required to create an AKS cluster. The code @metacpp points to is showing that there are two required fields for a `ContainerServiceLinuxProfile`, but [`ManagedClusterProperties`](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservices/resource-manager/Microsoft.ContainerService/stable/2018-03-31/managedClusters.json#L1140) does not appear to require `linuxProfile`. And in the Python SDK generated from this swagger, a [`ManagedCluster`](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-containerservice/azure/mgmt/containerservice/models/managed_cluster.py#L15) does not require `linuxProfile`.

Maybe I'm confused about the actual issue we need to fix. cc: @zqingqing1.

**Comment by mboersma** [comment]
`linuxProfile` isn't required, and the original question was solved by changing usage of the Go SDK. I think this issue can be closed @metacpp.

**Comment by annatisch** [comment]
Thanks @mboersma!
@metacpp - please reopen if you feel that this has not been addressed.
