### ISSUE TITLE
PostgreSQL create virtual network rule returns 202 although IgnoreMissingVnetServiceEndpoint is set to false

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-rest-api-specs#3719]
For details https://github.com/Azure/azure-sdk-for-go/issues/2534

**Comment by vladbarosan** [comment]
Taking the history of PosgreSQL, @QingqingYuan can you help the customer here ?

**Comment by jeffreyCline** [comment]
Adding link to [Provider PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1774)

**Comment by QingqingYuan2** [comment]
Provider PR is designed this as async operation. The operation result will return "Bad Request" in this case.

**Comment by aullom1** [comment]
The bug as it is reported, and the PR, deal entirely with PostgreSQL.  However, this is also a problem with MySql.  Do you want a new bug for this, or is it appropriate to fix IgnoreMissingVnetServiceEndpoint for all databases?

**Comment by QingqingYuan2** [comment]
We handle both of the databases together. No need for separate bug. 
This bug has been fixed from RP side. PostgreSQL and MySQL both return 400 when "IgnoreMissingVnetServiceEndpoint" is set to false while vnet is not enabled the service.

**Comment by rachel-msft** [comment]
This was fixed in November as Qingqing mentioned. Please close @hovsepm.

**Comment by rachel-msft** [comment]
@aullom1, @hovsepm, @jeffreyCline could you help with closing this issue?
