### ISSUE TITLE
Microsoft.Network/stable/2016-06-01/network.json has semantic validation errors

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#3787]
See https://github.com/Azure/azure-rest-api-specs/pull/3785 for the failures.
   [ { code: 'OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION',
       message: 'Missing required property definition: nextHopType',
       path: [ 'definitions', 'ExpressRouteCircuitRoutesTable' ] },
     { code: 'OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION',
       message: 'Missing required property definition: nextHopType',
       path: [ 'definitions', 'ExpressRouteCircuitRoutesTableSummary' ] },
     { code: 'EQUIVALENT_PATH',
       message: 'Equivalent path already exists: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{virtualNetworkGatewayConnectionName}/sharedkey',
       path: 
        [ 'paths',
          '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{virtualNetworkGatewayConnectionName}/sharedkey' ] } ],

**Comment by MikhailTryakhov** [comment]
foxed in Ignite release
