### ISSUE TITLE
CI should verify that files are appropriately formatted (UTF-8, newlines, whitespace...)

### ISSUE THREAD

**Issue by lvh** [Azure/azure-rest-api-specs#380]
In #372, I originally suggested that maybe CI should do:

```
iconv -f utf-8 -t utf-8 **json > /dev/null
```

However, this is not the only inconsistency I tripped over. For example, at time of writing, `arm-devtestlabs/2016-05-15/swagger/DTL.json` contained CRLF line endings (other files use LF).

One way to do both enforce, document and automate all of this is an [`.editorconfig` file](http://editorconfig.org/). This lets you specify:
- file encodings
- line endings
- end-of-line whitespace
- line length (non-standard but commonly supported extension; probably not needed for this repo).

Many editors support this either natively or with a plugin. This includes the Github built in editor, Emacs, vim, Visual Studio, and Visual Studio Code.

Here's an example config:

```
# EditorConfig is awesome: http://EditorConfig.org

root = true

[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
charset = utf-8
indent_style = space
```

This would cover all the inconsistencies I have found in the specs so far. Using [eclint](https://www.npmjs.com/package/eclint), you can automatically both check and even fix all current issues; so it's easy to move to this and it's easy to fix existing issues.

@john-hart, @lmazuel: If I write this PR, is there any chance it gets merged?

**Comment by lvh** [comment]
This also appears to be an issue in other PRs, e,g https://github.com/Azure/azure-rest-api-specs/pull/379. It seems like giving people a tool to do this automagically would save a ton of developer and reviewer time :)

**Comment by kirthik** [comment]
Moved to - https://github.com/Azure/autorest/issues/1825

**Comment by fearthecowboy** [comment]
Reopening -- this is a CI issue, not autorest

**Comment by salameer** [comment]
@bsiegel not sure if we have this already, but seems like a good investment if we don't.

**Comment by lmazuel** [comment]
I would suggest use a gitattribute files to enforce all JSON to be LF.
https://help.github.com/articles/dealing-with-line-endings/

```
*.json text eof=lf
```

**Comment by bsiegel** [comment]
We can go further, it's pretty easy to add the editorconfig file and then add a pre-commit hook that runs the files through eclint first. The only downside is that we'd need to either commit the tool to the repo or people would have to run 'npm install' locally to pull it down.

**Comment by lvh** [comment]
I don’t know why this was closed: the associated PR does not appear to resolve the problem that existing JSON files are in disarray, and CI does not prevent regressions.

**Comment by yungezz** [comment]
HI @NullMDR could you pls have a look? before adding check, pls see how to fix existing errors. thanks.

**Comment by akning-ms** [comment]
Hi @NullMDR, is this fixed?

**Comment by NullMDR** [comment]
We already have prettier that could do format, but for the newline and utf-8 I need to confirm if it works with current prettier.

**Comment by zhenglaizhang** [comment]
@PhoenixHe-msft any update on this thread?

**Comment by Petermarcu** [comment]
Closing as this issue is too old. If this is still an issue, we should open a new issue on the tooling.
