### ISSUE TITLE
[Network] Resource ID is not read-only?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#382]
In all other Swagger specs, `id` is `read-only`:

``` json
"Resource": {
  "properties": {
    "id": {
      "readOnly": true,
      "type": "string",
      "description": "The id of the resource"
    },
    "name": {
      "readOnly": true,
      "type": "string",
      "description": "The name of the resource"
    },
    "type": {
      "readOnly": true,
      "type": "string",
      "description": "The type of the resource"
    },
    "location": {
      "type": "string",
      "description": "The location of the resource"
    },
    "tags": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "The tags of the resource"
    }
  },
  "x-ms-azure-resource": true
}
```

However, in the network Swagger spec, [it is not](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L7131).

This hides the subsequent bug that we are sending `Resource` instead of `SubResource` for nested resources in 
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L5173
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L5889 (In this particular one, `VirtualMachine` is a `SubResource` yet the NSG is a `Resource`)
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json#L6433

**Comment by selvasingh** [comment]
@DeepakRajendranMsft - please review this issue

**Comment by markjbrown** [comment]
This is due to the $expand issue. We cannot make resource id read only. Closing.

**Comment by salameer** [comment]
Closing

**Comment by fengzhou-msft** [comment]
> This is due to the $expand issue. We cannot make resource id read only. Closing.

@markjbrown can you explain what is the $expand issue? Does it mean resource Id in network is writable?

**Comment by fengzhou-msft** [comment]
@markjbrown Thanks for the prompt reply.  The linked PR #1629 is for ACR description update, I don't see how it's related to the Resource ID issue in network. Can you double check?

**Comment by markjbrown** [comment]
Sorry, I was confusing this with another issue.
