### ISSUE TITLE
[Feature request] API to get parameters from a template

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-rest-api-specs#383]
Requested by customers from Java side: https://github.com/Azure/azure-sdk-for-java/issues/727.
This is supported in AWS.

It doesn't feel like a tricky API to write considering the code to parse the template and understand the parameters already exists.

**Comment by TianoMS** [comment]
@ravbhatnagar to take a look.

**Comment by ravbhatnagar** [comment]
No plans to support this. Haven't heard this as a top feature ask from the customers. @kirthik - Please close as wont fix. We can revisit if we hear feedback on this.
