### ISSUE TITLE
Network enums all modeled as strings

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#384]
In `arm-network/2016-03-30/swagger/network.json` of the 41 uses of `modelAsString` all have a value of `true`. In some cases this makes sense, such as Application Gateway SKU name/tier, but in many other cases it does not make sense (i.e. enabled/disabled, static/dynamic, http/https).

**Comment by liumichelle** [comment]
We cannot make this change because it will be a breaking change

@tjprescott - can you close this issue?

**Comment by salameer** [comment]
@tjprescott,

Not sure the benifit VS value makes sense to do these changes for these already public APIs, so I would recommend closing. BUT :) @DeepakRajendranMsft and @liumichelle  it would be great to spread awareness that for new Resource types and addition to swaggers it would be great to model as enums where appropriate :)
