### ISSUE TITLE
Filtering resource group collection supports filtering only on tags

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#3853]
Please update the docs for operation [ResourceGroups_List](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2018-02-01/resources.json#L882) that the filter parameter supports filtering on tags only.
Related: https://github.com/Azure/azure-sdk-for-go/issues/2480

**Comment by stevemcquaid** [comment]
Any update on this @jhendrixMSFT ?

**Comment by jhendrixMSFT** [comment]
@chidmdxx can you please follow up on this?

**Comment by tim-nguyen-cs** [comment]
This has been updated in our most recent API version (`2021-04-01`); therefore, this issue will be closed now.
