### ISSUE TITLE
The arm-network spec is missing descriptions

### ISSUE THREAD

**Issue by John-Hart** [Azure/azure-rest-api-specs#386]
For example the blank descriptions for the 200 Responses in 
NetworkInterfaces_GetEffectiveRouteTable and NetworkInterfaces_ListEffectiveNetworkSecurityGroups are not very helpful

**Comment by salameer** [comment]
Keeping on Deepak's side

**Comment by markjbrown** [comment]
These have been fixed. Looking at the latest API version below. There is support for Vnet Peering and the operations all have descriptions for 200 responses. I think we can close this.

CC @DeepakRajendranMsft @liumichelle 

NetworkInterfaces_ListEffectiveNetworkSecurityGroups:
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/networkInterface.json#L333

NetworkInterfaces_GetEffectiveRouteTable
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/networkInterface.json#L287

Virtual Network Peering
https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/virtualNetwork.json#L475

**Comment by DeepakRajendranMsft** [comment]
@salameer can we close this please. Mark is saying that we fixed them

**Comment by liumichelle** [comment]
@salameer ping on this - can we close out the issue?

**Comment by salameer** [comment]
Closing according to recommendation
