### ISSUE TITLE
KeyVault delete should declare to return nothing

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#392]
Look inside the KeyVault Swagger file, the delete operation is declared to return the deleted KeyVault:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L73

Actually, there is no return (the RestApi doc says the same thing):
https://msdn.microsoft.com/en-us/library/azure/mt620022.aspx

It does not create an error (at least in Python), but create an error in the documentation.

@pomortaz @amarzavery

**Comment by amarzavery** [comment]
@lmazuel - you are right. If I compare the documentation for create and delete in the MSDN REST API doc, the document for create says 200 (OK) as one of the valid responses and does provide an example schema for the response. Whereas, the document for delete does not provide an example schema for 200 (OK) response.
If the Key vault service does not return the deleted vault then the swagger spec should be updated accordingly.

**Comment by pomortaz** [comment]
@lmazuel and @amarzavery thanks for pointing it out. That's correct. Delete does not return a vault property. I fixed it: https://github.com/Azure/azure-rest-api-specs/pull/398
