### ISSUE TITLE
Generating Models classes from 2018-04-01 stable version doesn't generate CloudError Model

### ISSUE THREAD

**Issue by ryperl** [Azure/azure-rest-api-specs#3988]
After Generating basic models for the 2018-04-01 spec version with AutoRest the output doesn't generate the required classes to compile successfully in C#, it seems that the CloudError, and  CloudErrorBody definitions are not being generated.  Unless I am implementing this incorrectly.

E:\scratch\azure-rest-api-specs\specification\trafficmanager\resource-manager\Microsoft.Network\stable\2018-04-01>autorest --input-file=trafficmanager.json --output-folder=models --csharp --namespace=TrafficManager.Models
AutoRest code generation utility [version: 2.0.4283; node: v8.9.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '.autorest\@microsoft.azure_autorest-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4289)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.81)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)

E:\scratch\azure-rest-api-specs\specification\trafficmanager\resource-manager\Microsoft.Network\stable\2018-04-01>

**Comment by annatisch** [comment]
Thanks @ryperl 
These are common models that should be in the C# Azure runtime:
https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure

Are you referencing this project?

**Comment by ryperl** [comment]
@annatisch I am using this specification to generate model classes for the Azure TrafficManager Rest API's.  following this guidance - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/trafficmanager/resource-manager/readme.md

I am not referencing the above sdkcommon project.

**Comment by annatisch** [comment]
Thanks @ryperl - the Azure runtime is a requirement for generated Azure SDKs.

Not only does it include generic models like CloudError, but also the core REST pipeline and utilities for dealing with various Azure feature from authentication to long running operation polling.

Autorest generated SDKs are intended to be used with a language-specific runtime.

**Comment by annatisch** [comment]
Followed up further offline.

Please re-open if you feel this hasn't yet been addressed.
