### ISSUE TITLE
[AzureStack] Backup object contains BackupId which is just a substring of Resource name

### ISSUE THREAD

**Issue by daozha** [Azure/azure-rest-api-specs#4029]
From @deathly809 's suggestion, BackupId should be removed.  The ARM endpoints take the NAME of the resource as the identifier. And BackupId is just redundant.

**Comment by dsgouda** [comment]
@daozha do you know who this can be assigned to?

**Comment by deathly809** [comment]
@dsgouda He actually has a PR to fix it.  Just assign it to him.
