### ISSUE TITLE
[Network - Application Gateway] Request for "App Service" support

### ISSUE THREAD

**Issue by Fredrik-C** [Azure/azure-rest-api-specs#4066]
The REST Api (and fluent SDK) lacks options to specify App Service options as you can du in the Portal UI.

Please extend:
**ApplicationGatewayBackendAddress** to include "appService" option (available in portal UI).
**ApplicationGatewayBackendHttpSettings** to include "Use for App Service" option (available in portal UI).

**Comment by surajmb** [comment]
@Fredrik-C ,  "Use for App Service" is only a UI element and when you enable it, it essentially asks the user to choose the custom probe and enables the "pick hostname from backend address" switch by default.

In PowerShell/REST API, to get the same result as Use for App Service, you can use the switches directly. Check the example below,

"backendHttpSettingsCollection": [
      {
        "name": "appGatewayBackendHttpSettings",
        "id": "/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Network/applicationGateways/xxxxxxxx/backendHttpSettingsCollection/appGatewayBackendHttpSettings",
        "etag": "W/\"09f93026-69e9-426e-8fa1-6254df8edffb\"",
        "properties": {
          "provisioningState": "Succeeded",
          "port": 80,
          "protocol": "Http",
          "cookieBasedAffinity": "Disabled",
          **"pickHostNameFromBackendAddress": true,**
          "requestTimeout": 30,
          **"probe": {
            "id": "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Network/applicationGateways/xxxxxxx/probes/HttpCustomProbe"
          },**
          "requestRoutingRules": [
            {
              "id": "/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/applicationGateways/xxxxxxx/requestRoutingRules/HttpRule1"
            }
          ]
        },
        "type": "Microsoft.Network/applicationGateways/backendHttpSettingsCollection"
      }
    ],

**Comment by surajmb** [comment]
@anuchandy please close this issue.

**Comment by surajmb** [comment]
@anuchandy, can we close this issue?

#please-close
