### ISSUE TITLE
Use common types in swaggers

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-rest-api-specs#4073]
This will eliminate the need to redefine in each swagger the common ARM definitions.

 @fearthecowboy can you any details on this ? is it enough to just refer these types ( im thinking unwanted extra definitions might be brought in ) or there are other things we need to take care ?

**Comment by fearthecowboy** [comment]
Before referencing them, the common type definitions need to be cleanly split up into separate files, and common parameters definitions in a separate file, so that we're not pulling in unwanted unused models when not necessary.

And then we'd need a very clear guide on how to properly leverage them.

**Comment by tombuildsstuff** [comment]
@vladbarosan whilst I feel this is the right thing to do from a code level - values for fields like `location` and `resourceGroup` can be case sensitive depending on the API being used (and whilst this isn't currently handled in the Swagger, I could see it being in future) - as such I'm wondering if this could do with some documentation to avoid creating subtle issues in the future? (not that they'd be hard to fix, but thought it's worth raising)

**Comment by vladbarosan** [comment]
@tombuildsstuff , since resource group is an ARM concept it shouldn't have different behavior across services. can you provide an example where that might be the case  ?

**Comment by akning-ms** [comment]
All ARM related common definition already in specification\common-types\resource-management\v2\types.json
so close this issue
