### ISSUE TITLE
Capture Image from VM ask parameters not documented

### ISSUE THREAD

**Issue by zhitongLBN** [Azure/azure-rest-api-specs#425]
when I use capture image from vm 
https://msdn.microsoft.com/en-us/library/azure/mt163560.aspx
it ask for 

```
Required parameter 'CaptureVMInput' is missing (null)
```

but nothing was told about this in the api doc, please fix it, thx :)

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
