### ISSUE TITLE
Problem auto-generating SDK for Go in the storagesync spec

### ISSUE THREAD

**Issue by shawns1** [Azure/azure-rest-api-specs#4262]
The output folder in the readme.go.md config file doesn’t exist within a "preview" sub-folder and it looks like it should since the input is coming from a preview subfolder.  We are getting an error during code generation that says "FATAL: System.InvalidOperationException: codegen for preview swagger Microsoft.StorageSync/preview/2018-10-01/storagesync.json must be under a preview subdirectory"

The PR that contains the Go SDK Generation failure:  #4249 

Also as a side note, the folder name (version) doesn’t have “-preview” after it although it is in a preview sub-folder.

**Comment by annatisch** [comment]
Looks like the path has the incorrect directory - thanks for reporting :)

**Comment by jhendrixMSFT** [comment]
I updated the PR with the fix so closing.
