### ISSUE TITLE
New CostManagement spec version 2018-12-01-preview needs to be added to Readme.md file

### ISSUE THREAD

**Issue by shawns1** [Azure/azure-rest-api-specs#4264]
The following spec was introduced but not added to the corresponding Readme.md file:  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2018-12-01-preview/costmanagement.json

The Readme.md file is located here:  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/readme.md

The SDK will not be auto-generated until the spec is added.

**Comment by hovsepm** [comment]
Assigning to @kjeur

**Comment by kjeur** [comment]
@hovsepm Raised PR https://github.com/Azure/azure-rest-api-specs/pull/4269

**Comment by hovsepm** [comment]
Fixed. Closing the issue.
