### ISSUE TITLE
New SQL Specs added but not in Readme.md file yet

### ISSUE THREAD

**Issue by shawns1** [Azure/azure-rest-api-specs#4265]
The following sql specs were added but the Readme.md file has not been updated with these specs yet so the SDK is not building for these.  The specs are located here:  https://github.com/Azure/azure-rest-api-specs/tree/master/specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview

The Readme is located here:  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/readme.md

**Comment by jaredmoo** [comment]
This is intentional. When an API is ready to be published in azure-sdk-for-net, we will add it to package-composite-* in readme. At that time we should also add it to package-pure-* so that other SDK's like Go will also get the API. Please let me know if there are any specific API's that are missing from package-pure-*.

**Comment by shawns1** [comment]
According to @lmazuel, The file Microsoft.ApiManagement/preview/2018-06-01-preview/apimdiagnostics.json was changed which is used in the tag package-2018-06-preview, but the default tag of the Readme is package-2018-01.  As a result, we are not getting any auto-generated SDKs for the specs listed above.  @lmazuel, can you please provide any additional details if I am missing something?  Thanks.

**Comment by jaredmoo** [comment]
Are we talking about ApiManagement or Sql?

**Comment by shawns1** [comment]
Sorry...wrong issue.  I was looking at the version and it was the same in my notes.  Let me double check.  the SDKs are not being generated above but I'll have to double check.

**Comment by shawns1** [comment]
Sorry...the versions were the same as an ApiManagement issue that was similar.  Here is the correct notes and info I got from @lmazuel:  

This PR is introducing a completely new Swagger file Microsoft.Sql/preview/2018-06-01-preview/DatabaseVulnerabilityAssessment.json and this file was not added into the main Readme.  We don’t know how to generate a file that is nowhere in any Readme.  PR triggered for other language are false positives. 

We are in the process of rolling out auto-generated SDKs for PRs and this particular PR failed to generate any code.

**Comment by shawns1** [comment]
Here is the original PR:  https://github.com/Azure/azure-rest-api-specs/pull/4256

**Comment by shawns1** [comment]
Per Jared:  It is not guaranteed that every API published in Swagger is something that we want SDKs to be published for at that time. For example we may be documented a deprecated API, or more commonly we may be documenting an API that is in the middle of going live (we need to have Swagger approved by Gaurav before it can be lit up, so we usually publish swagger before it is live). This has been the case since we started publishing swagger. So, I don’t see how this issue is generally actionable for us.
