### ISSUE TITLE
Too many variations of list operation names in Web App Swagger

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#431]
There are too many variations of list names. The good news is that these list can be modeled as `CollectionObject.list()` and `CollectionObject.listByResourceGroup()
`

#244 

Web

- [`listPremierAddOnOffers()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1291  )
- [`listDomainRecommendations()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L1612  )
- [`listSiteAppSettings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10574  )
- [`listSiteAppSettingsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10621  )
- [`listSiteConnectionStrings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10802  )
- [`listSiteConnectionStringsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L10849  )
- [`listSiteAuthSettings()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11030  )
- [`listSiteAuthSettingsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11077  )
- [`listSitePublishingCredentials()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11258  )
- [`listSitePublishingCredentialsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11306  )
- [`listSiteMetadata()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11361  )
- [`listSiteMetadataSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11408  )
- [`listSitePremierAddOnsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11812  )
- [`listSitePremierAddOns()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L11862  )
- [`listSiteBackups()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L12723  )
- [`listSiteBackupsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L12768  )
- [`listSitePublishingProfileXml()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L13655  )
- [`listSitePublishingProfileXmlSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L13717  )
- [`listSiteRelayServiceConnections()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14808  )
- [`listSiteRelayServiceConnectionsSlot()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L14855  )
- [`listTopLevelDomainAgreements()`](https://github.com/Azure/azure-rest-api-specs/blob/822b51ed9d19cb79f6684220cca21b673f804bb7/arm-web/2015-08-01/swagger/service.json#L15417  )

**Comment by martinsawicki** [comment]
based on 8/15 discussion, this is no. 8 on the blocking issues list
