### ISSUE TITLE
Many required parameters are NOT being labeled as required (Web App Swagger)

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#432]
Examples:

- Server farm id
- Server farm SKU
- Certificate order's product type

https://github.com/Azure/azure-rest-api-specs/blob/a8190a7741815cd9b86ca861bb00ec9f8b18b8b8/arm-web/2015-08-01/swagger/service.json#L17501

https://github.com/Azure/azure-rest-api-specs/blob/a8190a7741815cd9b86ca861bb00ec9f8b18b8b8/arm-web/2015-08-01/swagger/service.json#L17397

https://github.com/Azure/azure-rest-api-specs/blob/a8190a7741815cd9b86ca861bb00ec9f8b18b8b8/arm-web/2015-08-01/swagger/service.json#L16436

**Comment by martinsawicki** [comment]
per 8/15 discussion, this is no. 6 on the blocking issues list
