### ISSUE TITLE
Internal Server Error 500 by using "Billing Period - List "

### ISSUE THREAD

**Issue by jackting73** [Azure/azure-rest-api-specs#4328]
Hi,

I'm using the endpoint try to get the billing period but got the Internal Server Error 500 on some subscription. My subscription is MSDN/PAYG/AIO. Any idea or workaround to get the billing period? Thanks.

Document: https://docs.microsoft.com/en-us/rest/api/billing/billingperiods/list
![image](https://user-images.githubusercontent.com/13516911/47483369-acfa8680-d86b-11e8-9130-b42b54bc9837.png)

**Comment by dsgouda** [comment]
@wilcobmsft would you know someone who can take a look at this one?

**Comment by wilcobmsft** [comment]
There was a known issue in one of our downstream systems. It should be resolved now. Can you please try again and let us know if you're still able to reproduce the issue?

**Comment by jackting73** [comment]
@wilcobmsft 

It works now.
May I know is there any other API also can get the billing period ?
(Because I found this issue happened several times this year, so I'm looking for other API which could be more stable)

Thanks,
