### ISSUE TITLE
List operations do not use the standard paged list (Web App Swagger)

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#433]
List operations do not use the standard paged list. See concrete example in compute Swagger. There are about 90+ list operations that do not use the standard paged list

Concrete example in compute Swagger - https://github.com/Azure/azure-rest-api-specs/blob/59ac2af2f2b86dcc536ebaa3786c25cf0d9c3002/arm-compute/2016-03-30/swagger/compute.json#L1173

Standard paged list - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Paging-x-ms-pageable

**Comment by selvasingh** [comment]
Here is a sample list that does not use the standard paged list https://github.com/Azure/azure-rest-api-specs/blob/a8190a7741815cd9b86ca861bb00ec9f8b18b8b8/arm-web/2015-08-01/swagger/service.json#L8022

**Comment by martinsawicki** [comment]
based on 8/15 discussion, this is #3 on blocking issues list
