### ISSUE TITLE
Many read only properties are NOT being labeled as read only (Web App Swagger)

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#435]
Many read only properties are NOT being labeled as read only. Example.

See https://github.com/Azure/azure-rest-api-specs/blob/a8190a7741815cd9b86ca861bb00ec9f8b18b8b8/arm-web/2015-08-01/swagger/service.json#L21446

**Comment by martinsawicki** [comment]
per 8/15 discussion, this is no. 7 on the blocking issues list
