### ISSUE TITLE
nodeDeallocationOption sending enum ordinal breaks Go SDK

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#4356]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/3171
The operation `Pool_ListByBatchAccount` is returning the value `nodeDeallocationOption` by ordinal which doesn't work for all languages.  As a result this API is not usable in the Go SDK.  Below is a sample of the response body.
```json
"resizeOperationStatus": {
    "nodeDeallocationOption": 0,
    "resizeTimeout": "PT15M",
    "startTime": "2018-10-29T13:51:26.7338118Z",
    "targetDedicatedNodes": 1
},
```

**Comment by devigned** [comment]
This has been called out by multiple customers. It would be great if we could get a fix out there ASAP.

**Comment by matthchr** [comment]
@kiwidev - Were you aware of this?

**Comment by kiwidev** [comment]
Thanks. I've put a fix into our service which will address this. Will update once we have an ETA for when it will hit production.

**Comment by sylr** [comment]
@devigned @kiwidev Any news about this ?

**Comment by sylr** [comment]
@devigned @kiwidev guys ?

**Comment by kiwidev** [comment]
Hi @sylr, sorry for the delay, we've had some delays in deploying our latest release train. This should be available through all regions by Wednesday next week.

**Comment by matthchr** [comment]
This should be fixed now. You probably can close this issue.

**Comment by jhendrixMSFT** [comment]
@sylr is this working for you now?

**Comment by bgklein** [comment]
Issue was addressed in REST API release https://docs.microsoft.com/en-us/rest/api/batchservice/batch-service-rest-api-versioning#latest-version-2018-12-0180 and should now be resolved.
