### ISSUE TITLE
Cannot build servicefabric package-2018-02 due to mismatched duplicate models

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#4359]
ERROR (Fatal/DuplicateModelCollsion): Duplicated model name with non-identical definitions
    - file:///C:/vladdb/repos/devdiv/sdks/azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/preview/2017-07-01-preview/application.json:973:4 ($.definitions.ApplicationHealthPolicy)
    - file:///C:/vladdb/repos/devdiv/sdks/azure-rest-api-specs/specification/servicefabric/resource-manager/Microsoft.ServiceFabric/stable/2018-02-01/cluster.json:534:4 ($.definitions.ApplicationHealthPolicy)

**Comment by jhendrixMSFT** [comment]
@TassaduqBasu are you the correct person to investigate this?  We are unable to build any SDKs for this swagger due to this error.

**Comment by peterpogorski** [comment]
@jhendrixMSFT is this still an error that you are experiencing?

**Comment by jhendrixMSFT** [comment]
Verified fixed via https://github.com/Azure/azure-rest-api-specs/pull/5852, thanks for following up.
