### ISSUE TITLE
Many list operations are modeled as Get operations (Web App Swagger)

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#436]
Here are some examples. There are so many such operations in Web App Swagger

![image](https://cloud.githubusercontent.com/assets/3642444/17193021/fcd1c1f6-5405-11e6-83c8-65afbf821c39.png)

![image](https://cloud.githubusercontent.com/assets/3642444/17193041/10b20c30-5406-11e6-9983-c08ea5147875.png)

**Comment by selvasingh** [comment]
#244

**Comment by amarzavery** [comment]
We will be catching this in the linter, where we enforce them to use the noun_verb pattern for operationId.
/cc @tbombach

**Comment by selvasingh** [comment]
That is good

**Comment by selvasingh** [comment]
I saw so many such operations in the Web App Swagger so I stopped counting or collecting links to those operations

**Comment by amarzavery** [comment]
That is good as well ;)

**Comment by martinsawicki** [comment]
per 8/15 discussion, this is #8 on the blocking issues list
