### ISSUE TITLE
SKU parameter missing in ServiceBus CreateOrUpdate

### ISSUE THREAD

**Issue by garimakhulbe** [Azure/azure-rest-api-specs#439]
According to the documentation: https://msdn.microsoft.com/en-us/library/azure/mt639408.aspx#Anchor_0, user should be able to specify SKU options when creating/updating the namespace resource but this attribute is missing in request parameters in swagger. Why is it missing? Go SDK Issue [#366](https://github.com/Azure/azure-sdk-for-go/issues/366)

https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2014-09-01/swagger/servicebus.json#L81

**Comment by amarzavery** [comment]
@sazeesha - Can you take a look at this issue? Is this resolved in the current PR #395

**Comment by garimakhulbe** [comment]
Any update on this?

**Comment by garimakhulbe** [comment]
I can see SKU is added in recent commits. Thanks.

We have couple of other issues in swagger. Kind attribute is also missing in CreateOrUpdate namespace. 

Go SDK issue: [#367](https://github.com/Azure/azure-sdk-for-go/issues/367).

**Comment by garimakhulbe** [comment]
This is resolved. Thanks.
