### ISSUE TITLE
Subnet previously used by deleted api management service cannot be deleted

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#4409]
Seems like [ApiManagementService_Delete](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/apimdeployment.json#L325) should be a long-running operation.
See https://github.com/Azure/azure-sdk-for-go/issues/2199 for more details.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT out of interest, is there a rough timeframe for this?

**Comment by jhendrixMSFT** [comment]
We need to get the RP engaged.  @solankisamir do you own this?

**Comment by jhendrixMSFT** [comment]
@solankisamir I believe that the subnet is being freed, the question is the semantics of the API.  It's returning a 200 which states that the resource has been deleted however this is misleading as the delete is in progress.  Should this be modeled as a LRO?  @ravbhatnagar do you have any opinion on this?

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT @solankisamir since this issue was originally opened in [July 2018](https://github.com/Azure/azure-sdk-for-go/issues/2199) would it be possible to escalate this to the Service Team? Based [on this comment](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582#issuecomment-452008563) it appears the Subnet isn't usable for up to 2 hours during any change to it at the moment, which means we'd have to poll for this long (which I'd like to avoid if possible).

Thanks!

**Comment by joranm** [comment]
Hi @solankisamir, sounds good. If this will be fixed in version `2019-01-01` would be great!

**Comment by solankisamir** [comment]
We updated the service side code to make DELETE a long-running operation. Will be working through updating the REST spec and the SDKs.

[Release Notes](https://azure.microsoft.com/en-us/updates/azure-api-management-update-february-14/)

**Comment by hbuckle** [comment]
@solankisamir - any idea when this will be in the specs? The problem with updating the service side before the specs is that delete operations from clients are now failing as the service is returning 202, which the client can't handle as it isn't in the specs.

**Comment by tombuildsstuff** [comment]
> The problem with updating the service side before the specs is that delete operations from clients are now failing as the service is returning 202, which the client can't handle as it isn't in the specs.

On this note - isn't this technically a breaking change since it didn't previously return this status code and this isn't listed in the Swagger?

**Comment by hbuckle** [comment]
It is indeed - deleting api management from terraform now fails

```
Error deleting API Management Service "apim8naix" (Resource Group "fixtures8naix"): apimanagement.ServiceClient#Delete: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: Service returned an error. Status=202 Code="Unknown" Message="Unknown service error"
```

**Comment by tombuildsstuff** [comment]
@hbuckle would you mind opening an issue on our side, so we can patch this?

**Comment by solankisamir** [comment]
> > The problem with updating the service side before the specs is that delete operations from clients are now failing as the service is returning 202, which the client can't handle as it isn't in the specs.
> 
> On this note - isn't this technically a breaking change since it didn't previously return this status code and this isn't listed in the Swagger?
`2018-06-01-preview` is a `preview` version of the API, where we can make breaking changes. `2019-01-01` or `2018-01-01` are stable versions, where this becomes our liability.

**Comment by hbuckle** [comment]
Fair point - I didn't realise Terraform was using the preview API. @tombuildsstuff 2018-01-01 is still returning 200 for deletes

**Comment by tombuildsstuff** [comment]
@solankisamir is there an expected timeline for when the Swagger for 2019-01-01 will be available?

**Comment by tombuildsstuff** [comment]
ping @solankisamir :)

**Comment by solankisamir** [comment]
@tombuildsstuff we are just wrapping up a couple of changes required for the stable api-version change. Will update the thread asap. Should be done within a week or two.

**Comment by tombuildsstuff** [comment]
@solankisamir cool thanks 👍

**Comment by tombuildsstuff** [comment]
hey @solankisamir 

Is there an updated ETA for this? We've got some features blocked which dependent on this new API version:

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/3203
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2613

Thanks!

**Comment by solankisamir** [comment]
yes, the PR is in review now https://github.com/Azure/azure-rest-api-specs/pull/5568

**Comment by tombuildsstuff** [comment]
awesome thanks 👍
I was searching by the “API Management” label so I missed that

**Comment by solankisamir** [comment]
The Spec has been released [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-01-01/apimdeployment.json) and the GO SDK has been updated [here](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2019-01-01/apimanagement)
