### ISSUE TITLE
Long running operations must be modeled as long running operations (Web App Swagger)

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-rest-api-specs#443]
Example: Create or Update Certificate Order is a long running operation but Swagger does not describe it that way. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/swagger/service.json#L300. Must add "x-ms-long-running-operation": true, and use 201

Similarly, **other long running operations must be modeled the same way**

See guidance on how to model long running operations. https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md

**Comment by martinsawicki** [comment]
Per 8/15 discussion, this is #1 on blocking issues list
