### ISSUE TITLE
[ARM-Compute] Request to expose vmId in virtual machine scale set operations 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#445]
This issue is opened on behalf of customer request [Azure/azure-sdk-ruby Issue 15](https://github.com/Azure/azure-sdk-ruby/issues/15)

[vmId ](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L3661) was exposed as part of [VirtualMachineProperties](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L3621) for Virtual Machine get operations. We'd love to see vmId being exposed in virtual_machine_scale_set_vms operations as well.

**Comment by hyonholee** [comment]
It is in "VirtualMachineScaleSetVMProperties".

**Comment by vishrutshah** [comment]
Thanks @hyonholee for the update. Seems like issue is resolved with new swaggers. Thanks!
