### ISSUE TITLE
Linter diff not catching issue where an exception was thrown by linter due bad file reference in readme.md

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#4465]
Job https://travis-ci.org/Azure/azure-rest-api-specs/jobs/411518416 passed but shows an exception being thrown in the log

Processing configs:

[ 'specification/hardwaresecuritymodules/resource-manager/readme.md' ]

The results will be logged here: "/home/travis/build/Azure/azure-rest-api-specs/output/3548.json".

Processing "specification/hardwaresecuritymodules/resource-manager/readme.md":

Executing: npx autorest --reset && npx autorest@2.0.4152 --validation --azure-validator --message-format=json specification/hardwaresecuritymodules/resource-manager/readme.md

An error occurred while executing JSON.parse() on the linter output for specification/hardwaresecuritymodules/resource-manager/readme.md:

'[{\n  "Channel": "fatal",\n  "Text": "swagger-document-override/md-override-loader - FAILED"\n},\n{\n  "Channel": "fatal",\n  "Text": "Error: Could not read \'file:///home/travis/build/Azure/azure-rest-api-specs/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2018-10-31-preview/keyvault.json\'."\n},\n{\n  "Channel": "fatal",\n  "Text": "swagger-document/loader - FAILED"\n},\n{\n  "Channel": "fatal",\n  "Text": "Error: Could not read \'file:///home/travis/build/Azure/azure-rest-api-specs/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2018-10-31-preview/keyvault.json\'."\n}\n!Error: Could not read \'file:///home/travis/build/Azure/azure-rest-api-specs/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2018-10-31-preview/keyvault.json\'.]'

SyntaxError: Unexpected token ! in JSON at position 659

    at JSON.parse (<anonymous>)

    at getLinterResult (/home/travis/build/Azure/azure-rest-api-specs/scripts/momentOfTruth.js:67:31)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)

whixh indicates that the file the readme pointed to could not be read.
This should bubble up as a failure, as this PR wasn't properly validated due to this.

**Comment by veronicagg** [comment]
The readme is referencing an incorrect file, but we cannot have the tool report success when there's something wrong and the tool is actually catching it by throwing an exception but not reporting it later. Per our conversation offline, I'm reopening the issue. Thanks.

**Comment by sarangan12** [comment]
Code Changes Complete. PR Merged. No pending action items. Closing this now.
