### ISSUE TITLE
datalake.Store data-plane definition casing inconsistency

### ISSUE THREAD

**Issue by daschult** [Azure/azure-rest-api-specs#4503]
I was recently using the Node.js datalake.Store SDK and found a casing-inconsistency here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datalake-store/data-plane/Microsoft.DataLakeStore/stable/2016-11-01/filesystem.json#L1671
```json
"FileStatusResult": {
  "properties": {
    "fileStatus": {
      "$ref": "#/definitions/FileStatusProperties",
      "readOnly": true,
      "description": "the file status object associated with the specified path."
    }
  },
  "description": "Data Lake Store filesystem file status information response."
}
```
The response that I get back from the service actually looks like this:
```json
{
  "FileStatus": {
    "length": 0,
    "pathSuffix": "",
    "type": "DIRECTORY",
    "blockSize": 0,
    "accessTime": 1490302583819,
    "modificationTime": 1490302583819,
    "replication": 0,
    "permission": "770",
    "owner": "2e6c02d2-a364-4530-9137-d17403996cbf",
    "group": "2e6c02d2-a364-4530-9137-d17403996cbf",
    "aclBit": false
  }
}
```
As you can see, the top level property in the response is `FileStatus`, but in the specification file it's `fileStatus`. Case sensitivity matters. Please fix the specification or the service.

**Comment by ro-joowan** [comment]
@daschult - please reassign this to @lewu-msft

**Comment by daschult** [comment]
@sumantmehtams and I talked about this, and he indicated that they aren't interested in having a JavaScript SDK anymore, so this doesn't matter. I'm closing this issue.
