### ISSUE TITLE
DocumentDB listConnectionStrings only lists 1 "Default MongoDB Connection String"

### ISSUE THREAD

**Issue by jeremie0** [Azure/azure-rest-api-specs#4571]
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}/listConnectionStrings?api-version=2015-04-08
and az cosmosdb list-connection-strings  only return 1 connection string. 

From the description and the fact that the DatabaseAccountListConnectionStringsResult is described as "An array that contains the connection strings for the Cosmos DB account", I think that all 4 connection strings should be returned : 'primary', 'secondary', 'primaryReadonly', 'secondaryReadonly'.

**Comment by shurd** [comment]
Hi @jeremie0, thank you for bring up this request. In January of this year, we altered the response of the API request so that all 4 connection strings are included in the response.
