### ISSUE TITLE
Typo timeOccured in ADHybridHealthService

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4577]
Should be "Occurred" in the following
https://github.com/Azure/azure-rest-api-specs/blob/bd2aca046b487c2ae2f13cc91d26c5f8aae93571/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L4146

https://github.com/Azure/azure-rest-api-specs/blob/bd2aca046b487c2ae2f13cc91d26c5f8aae93571/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L4565

https://github.com/Azure/azure-rest-api-specs/blob/bd2aca046b487c2ae2f13cc91d26c5f8aae93571/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L5413

**Comment by jianghaolu** [comment]
@gamitra please take a look
