### ISSUE TITLE
Typo aadDistringuishedName in ADHybridHealthService

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4578]
Should be "distinguished" in 
https://github.com/Azure/azure-rest-api-specs/blob/bd2aca046b487c2ae2f13cc91d26c5f8aae93571/specification/adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService/stable/2014-01-01/ADHybridHealthService.json#L4590-L4593

**Comment by jhendrixMSFT** [comment]
Fixed

**Comment by nschonni** [comment]
Thanks! There are a few more I filled yesterday too https://github.com/Azure/azure-rest-api-specs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ADHybridHealthService
I wasn't sure if these could be fixed in the stable API

**Comment by nschonni** [comment]
Sounds good, I just wasn't sure how those breaking changes were fixed. Thanks for clarifying.
