### ISSUE TITLE
Improve the input and output for checkNameAvailabilityoperation in notification hubs

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#459]
@smithab
- The property name in the body parameter and the result should be spelled correctly "isAvailable" rather than "isAvailiable" 
- Is it relevant to provide location as one of the properties in the body parameter? Does the service check the name availability across all the locations or a specified location? Either the location should be required or it should be removed.
- CheckAvailabilityParameters should not have tags while checking the namespace availability. It is completely irrelevant.
- There should be a property named "reason" that provides meanigful information if the name is not available
- The response for check availability can never be a resource. The user will be using this operation to check whether the name is available before creating a resource of that name. So how can this response have properties like id, type, location, tags. It is completely non-sensible.

Please take a look at how storage has modeled and designed a similar operation https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2016-01-01/swagger/storage.json#L434 and double check what your service is actually doing.

**Comment by kirthik** [comment]
Notification Hubs team confirmed this as an issue on their side but no action has been taken so far. cc @smithab
