### ISSUE TITLE
Storage Accounts - Check Name Availability API Result misses infomation

### ISSUE THREAD

**Issue by gavinfish** [Azure/azure-rest-api-specs#4594]
I try to use the Storage Accounts - Check Name Availability API at https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/checknameavailability. But it does not return the information declared at https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/checknameavailability#checknameavailabilityresult. It only return the `nameAvailable` value now even I change to the previous API version like `2016-01-01`.

My used storage account has already exists in the subscription.

**Comment by blueww** [comment]
@gavinfish 

SDK just return what server return. It seems "Reason" and "Message" are not always return. 
In my testing, it returns when the account name is invalid like "ABC". 

```powershell
PS C:\Users\weiwei\Desktop\PSH_Script\Issues> Get-AzureRmStorageAccountNameAvailability ABC

NameAvailable             Reason Message                                                                                                                                                 
-------------             ------ -------                                                                                                                                                 
        False AccountNameInvalid ABC is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
```

**Comment by gavinfish** [comment]
@blueww you can see that it should return reason `AlreadyExists` when the storage account has already exists from https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/checknameavailability#reason . This worked fine and just breaks recently.

**Comment by blueww** [comment]
@gavinfish 
I have sent mail to SRP team to check if this is a designed server behavior change or not.

**Comment by gavinfish** [comment]
Thanks @blueww 
It seems changed yesterday and this causes an issue in our Jenkins plugin, details [JENKINS-54885](https://issues.jenkins-ci.org/browse/JENKINS-54885). I also test all API versions which support Check Name Availability, and they all return the same results. So I think it should be a change on the service side.

**Comment by blueww** [comment]
@gavinfish 
I will update you if get any responds from the SRP team.

**Comment by blueww** [comment]
@gavinfish 
As I get from SRP team:

> This should be mitigated for now. We will rollout the real fix in next few days.

**Comment by gavinfish** [comment]
Thanks, it works fine now. closing
