### ISSUE TITLE
provisioningState property should always be marked as readonly

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#460]
Provisioning state is an outcome of a request (mostly a deployment request) made to a service in Azure.
I have not come across a use case where the client needs to modify the value of the provisioning state while making a request to the service.
Even while cancelling a deployment, there is an action associated with the deployment request and the outcome is specified with the provisioning state being "cancelled".

**Comment by kirthik** [comment]
closing due to  lack of data.
