### ISSUE TITLE
Typo softareUpdateConfigurationRunTasks in Microsoft.Automation

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4607]
Should be "software"
https://github.com/Azure/azure-rest-api-specs/blob/605dd0c1f1cb5f5d10c657fd160104c5bc3508f3/specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/softwareUpdateConfigurationRun.json#L268-L272

**Comment by andyw248** [comment]
Minor, closing.

**Comment by nschonni** [comment]
These are minor, but they affect the documentation, and are likely to cause client support requests when they spell it correctly and it doesn't work.
Not as big a deal now since the build will fail unless corrected when submitting a new version of the API though
