### ISSUE TITLE
VirtualNetworkGateways incorrect Swaggers

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#4642]
A few bug that forces the CLI to manually override the SDK:

- VirtualNetworkGateways_Generatevpnclientpackage also returns 202, which is not declared in Swagger.

- VirtualNetworkGateways_Generatevpnclientpackage and VirtualNetworkGateways_GenerateVpnProfile needs a final call on Location to get the final result. This requires an annotation in the Swagger, as made before for NetworkWatcher (for example):
https://github.com/Azure/azure-rest-api-specs/blob/a1d1c199d0aeee081315f772e10dd8184475fa3d/specification/network/resource-manager/Microsoft.Network/stable/2018-10-01/networkWatcher.json#L813-L817

Please add the same `x-ms-long-running-operation-options` for both of these operations. And please fix it for all api versions, not just the latest.

**Comment by MikhailTryakhov** [comment]
Hey @lmazuel  please use [this table](https://microsoft.sharepoint.com/teams/WAG/AzureNetworking/_layouts/OneNote.aspx?id=%2Fteams%2FWAG%2FAzureNetworking%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2FPowerShell%20tests%20ownership%7C999ED209-6ACB-4339-9CE8-B02F7A97FCE2%2F%29) to assign to the service team directly.
