### ISSUE TITLE
Typo expectedDataSizeInTeraBytes in Microsoft.DataBox

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4670]
"terabytes" is a single word and shouldn't be camelcase
https://github.com/Azure/azure-rest-api-specs/blob/7eac00e198e9d16c5f5d8c2fb8869fac81f5caa0/specification/databox/resource-manager/Microsoft.DataBox/stable/2018-01-01/databox.json#L1465

**Comment by jhendrixMSFT** [comment]
Spoke with the owner of this swagger, this is how the data looks on the wire so we cannot change it.

**Comment by jhendrixMSFT** [comment]
@sojain @saran94 to answer your question
