### ISSUE TITLE
Typo ADCCatalogs_ListtByResourceGroup in 

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4673]
There is a extra "t" in "List"
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/datacatalog/resource-manager/Microsoft.DataCatalog/stable/2016-03-30/datacatalog.json#L50

**Comment by salameer** [comment]
@nschonni please note that these specs represent the service, if there's a typo in the service side then it should be fixed there and not here :)

**Comment by nschonni** [comment]
For sure, I don't work for Microsoft, so I can report it here and hopefully gets pulled internally if it isn't just a Swagger generation issue.
