### ISSUE TITLE
Typo EventHubs_PosttAuthorizationRule in eventhub/Microsoft.EventHub

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4688]
Extra "t" at the end of "Post"

https://github.com/Azure/azure-rest-api-specs/blob/273e8adc23e7190173441ba028b287d00d281683/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2015-08-01/EventHub.json#L881

**Comment by jfggdl** [comment]
@nschonni, This has been fixed and released. Please feel free to test it. I am going to close this issue, but if you still have a concern or question, please feel free to reopen this issue.
