### ISSUE TITLE
Typo StorageAccountRegenerteKeyParameters in Microsoft.KeyVault

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4699]
Should be "Regenerate"

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/keyvault/data-plane/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L4589

https://github.com/Azure/azure-rest-api-specs/blob/7741b58490385d8ef511a61faab42038b8fdce7e/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L5506

https://github.com/Azure/azure-rest-api-specs/blob/7741b58490385d8ef511a61faab42038b8fdce7e/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.0/keyvault.json#L5506

**Comment by sarangan12** [comment]
Not going to pursue this
