### ISSUE TITLE
Typo: MilliSeconds shouldn't be camelcase

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4715]
Found it this way in a few files
- specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/examples/GetOperations.json
- specification/monitor/resource-manager/microsoft.insights/preview/2017-05-01-preview/metricDefinitions_API.json
- specification/monitor/resource-manager/microsoft.insights/preview/2017-05-01-preview/metrics_API.json
- specification/monitor/resource-manager/microsoft.insights/stable/2016-03-01/metricDefinitions_API.json
- specification/monitor/resource-manager/microsoft.insights/stable/2016-09-01/metrics_API.json
- specification/monitor/resource-manager/microsoft.insights/stable/2018-01-01/metricDefinitions_API.json
- specification/monitor/resource-manager/microsoft.insights/stable/2018-01-01/metrics_API.json
- specification/servicefabric/data-plane/Microsoft.ServiceFabric/stable/6.2/servicefabric.json
- specification/servicefabric/data-plane/Microsoft.ServiceFabric/stable/6.3/servicefabric.json

**Comment by sarangan12** [comment]
Not going to pursue this
