### ISSUE TITLE
Typo Uknown in network/resource-manager/Microsoft.Network/networkWatcher.json

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4721]
Should be "Unknown"
Found in a few API versions https://github.com/Azure/azure-rest-api-specs/search?q=Uknown&type=Code

**Comment by nschonni** [comment]
@number213 not sure if this is your group too

**Comment by number213** [comment]
@irrogozh @MikhailTryakhov please take a look

**Comment by EvgenyAgafonchikov** [comment]
Fixed by @irrogozh in the current version
