### ISSUE TITLE
Model validation failed but CI job showed success exit code

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#4744]
Check job https://travis-ci.org/Azure/azure-rest-api-specs/jobs/457417470 Model validation seems to have thrown an exception 
 Number of swaggers found in this PR: 2
 Files deleted in this PR are as follows:
[]
(node:4150) UnhandledPromiseRejectionWarning: #<Object>
(node:4150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:4150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

but job exited with 0 and successfully.

CI should fail due to model validation error.

**Comment by sergey-shandar** [comment]
It's fixed after rerun.
```

 error : 

code: JSON_PARSING_ERROR

id: OAV104

message: 'unexpected token, token: }, line: 12, column: 7'

innerErrors:

  - kind: structure

    code: unexpected token

    position:

      line: 12

      column: 7
```
