### ISSUE TITLE
Typo MessagingPlanproperties in servicebus/resource-manager/Microsoft.ServiceBus

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4759]
Looks like it was mentioned in https://github.com/Azure/azure-rest-api-specs/pull/2831#pullrequestreview-110221332 so maybe there is an internal work item already, otherwise it should be "MessagingPlanProperties"

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2014-09-01/servicebus.json#L2581

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2014-09-01/servicebus.json#L2612

**Comment by sarangan12** [comment]
Not going to pursue old service versions
