### ISSUE TITLE
Automation API?

### ISSUE THREAD

**Issue by liamjbennett** [Azure/azure-rest-api-specs#476]
Is the automation API missing from these specs?

https://msdn.microsoft.com/en-us/library/azure/mt662285.aspx

**Comment by amarzavery** [comment]
@safeermohammed - Can you provide a timeline for this?

**Comment by colemickens** [comment]
We now have people asking for this is Azure SDK For Go. https://github.com/Azure/azure-sdk-for-go/issues/418

**Comment by mcardosos** [comment]
@safeermohammed ping

**Comment by safeermohammed** [comment]
Currently plan is to get this in by March/April timeframe

**Comment by kirthik** [comment]
Automation API is checked in - https://github.com/Azure/azure-rest-api-specs/tree/master/arm-automation/2015-10-31
