### ISSUE TITLE
Typo Ruleproperties in servicebus/resource-manager/Microsoft.ServiceBus

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4761]
Should be camel cased to "RuleProperties"

https://github.com/Azure/azure-rest-api-specs/blob/6e127e682da4a23887d655657abfc3379d719540/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2017-04-01/servicebus.json#L3901

https://github.com/Azure/azure-rest-api-specs/blob/6e127e682da4a23887d655657abfc3379d719540/specification/servicebus/resource-manager/Microsoft.ServiceBus/stable/2017-04-01/servicebus.json#L3912

**Comment by amarzavery** [comment]
I don't think the service team will fix that since it will result in a binary breaking change for sdks in languages like C# and Java where the name of the model classes matter.
