### ISSUE TITLE
Event Hubs API?

### ISSUE THREAD

**Issue by liamjbennett** [Azure/azure-rest-api-specs#477]
Is this included in the spec?

https://msdn.microsoft.com/en-us/library/azure/mt639489.aspx

**Comment by amarzavery** [comment]
@sazeesha can you provide a timeline for this?

**Comment by sazeesha** [comment]
We will have a EventHub swagger spec out in around two weeks.

**Comment by sazeesha** [comment]
Here it is : https://github.com/Azure/azure-rest-api-specs/tree/master/arm-eventhub/2015-08-01/swagger
