### ISSUE TITLE
Typo restorableDroppededDatabaseId in 

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4782]
Should be "Dropped" instead of "Droppeded"

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/backups.json#L127

It's in an old stable API so it's probably not fixable now

**Comment by jeroenterheerdt** [comment]
this cannot be fixed since, as @nschonni said, it's a stable API.

**Comment by jeroenterheerdt** [comment]
@azuresdkci go ahead and close this
