### ISSUE TITLE
Typo occurences property in StorSimple8000 and StorSimple1200

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4805]
Should be "occurrences"

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/storsimple8000series/resource-manager/Microsoft.StorSimple/stable/2017-06-01/storsimple.json#L4996-L5000

https://github.com/Azure/azure-rest-api-specs/blob/0d9a904f95e116b3f92127d7584ea44412991351/specification/storSimple1200Series/resource-manager/Microsoft.StorSimple/stable/2016-10-01/StorSimple.json#L5902-L5906

**Comment by sarangan12** [comment]
Old versions of the service. Not going to pursue this

**Comment by nschonni** [comment]
@sarangan12 these aren't the old versions of the service, but the only versions of the service
