### ISSUE TITLE
ServiceBus Topics Api

### ISSUE THREAD

**Issue by andyroyle** [Azure/azure-rest-api-specs#482]
The specs in this repo don't match the documentation: https://msdn.microsoft.com/en-us/library/azure/mt639397.aspx

Unfortunately that documentation also seems to be wrong (GetTopic returns a different schema back and CreateTopic doesn't accept the listed schema).

**Comment by amarzavery** [comment]
@sazeesha - Can you take a look at this?

**Comment by sazeesha** [comment]
@andyroyle: When you create a topic you are setting only the properties that can be set, and GET returns all the TopicProperties. You can consider swagger to be the source of truth. Can you point me to what is inconsistent.

**Comment by andyroyle** [comment]
The simplest case of CreateTopic; as per this spec: https://msdn.microsoft.com/en-us/library/azure/mt639409.aspx

The only required field should be `location`, but if you send such a request then you get a `400 (Bad Request)` response.

**Comment by jtaubensee** [comment]
@andyroyle - Are you still experiencing issues with the CreateTopic call?

**Comment by jtaubensee** [comment]
Closing this issue as CreateTopic is succeeding with just the location parameter.

**Comment by andyroyle** [comment]
Hey, sorry; I stepped away from this for a while. 

I just tried it again and it seems that it's now passing. 

Not sure what changed!
