### ISSUE TITLE
Typo workflowAccesskey not camel case in Microsoft.Logic

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4837]
Should be "AccessKey"

https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/logic/resource-manager/Microsoft.Logic/preview/2015-02-01-preview/logic.json#L650

**Comment by amarzavery** [comment]
Is there a specific reason for the parameter to be named accessKey instead of workflowAcessKey ?

**Comment by nschonni** [comment]
Sorry, I was just pointing out that the "K" wasn't capitalize in the word. "workflowAcessKey" is the correct full property name

**Comment by amarzavery** [comment]
I see. I don't think this requires a change. This will cause unnecessary breaking changes in the API and the sdks that get generated from it. Hence closing the issue.
