### ISSUE TITLE
HDInsights API?

### ISSUE THREAD

**Issue by andyroyle** [Azure/azure-rest-api-specs#484]
Any timeline on when this is likely to be available?

https://msdn.microsoft.com/en-us/library/azure/mt622197.aspx

**Comment by omafnan** [comment]
Hi Andy, the HDInsight APIs are available today. What is missing or what problem are you having?

**Comment by amarzavery** [comment]
He wants to know when will there be swagger/open-api specs for hdinsight? What is the timeline for this?

**Comment by omafnan** [comment]
We are hoping to have swagger specs for HDI by end of this calendar year.

**Comment by andyroyle** [comment]
thanks @omafnan

**Comment by tombuildsstuff** [comment]
hey 👋 @omafnan / @amarzavery / @kirthik / @kamaljit - is there any update on when these will be available? Thanks :)

**Comment by kirthik** [comment]
swagger is checked in - https://github.com/Azure/azure-rest-api-specs/tree/master/arm-hdinsight
