### ISSUE TITLE
Pipelines_CreateOrUpdate examples crashing model validation process

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#4862]
Commenting out either of the examples allows them to run, but it seems like both together are causing an issue for `oav`

https://github.com/Azure/azure-rest-api-specs/blob/8bc8571d5d796f7c02b1dc8ce88effd2ba7a23e2/specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/datafactory.json#L1680-L1688

https://github.com/Azure/azure-rest-api-specs/blob/8bc8571d5d796f7c02b1dc8ce88effd2ba7a23e2/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L1929-L1937

```
<--- Last few GCs --->

[93106:0x104800000]    54125 ms: Mark-sweep 1378.5 (1416.4) -> 1378.3 (1417.4) MB, 696.3 / 0.0 ms  (average mu = 0.080, current mu = 0.004) allocation failure scavenge might not succeed
[93106:0x104800000]    55275 ms: Mark-sweep 1379.3 (1417.4) -> 1378.9 (1417.9) MB, 1146.5 / 0.0 ms  (average mu = 0.033, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a78ce9cfb7d]
    1: StubFrame [pc: 0x1a78ce9d0eea]
Security context: 0x253356b9d9f1 <JSObject>
    2: reduceToSingleString(aka reduceToSingleString) [0x2533a99d7f91] [internal/util/inspect.js:~1160] [pc=0x1a78cedfd15c](this=0x2533023025b1 <undefined>,0x2533e5354369 <Object map = 0x2533d498e6e1>,0x25338c311c51 <JSArray[3]>,0x253302302851 <String[0]: >,0x25338c311c31 <JSArray[2]>)
    3: formatRaw(aka formatRaw) [0x...

Abort trap: 6
```

**Comment by shawnxzq** [comment]
@JackTn What's do you expect service team to do this? Is it still an issue since it's opened for years, and we know limited on the model validation process.

**Comment by shawnxzq** [comment]
Close it for now since no one follow up on this.

**Comment by nschonni** [comment]
@shawnxzq I'm not sure if this is happening still, but I don't thing I follow the logic of closing this because the one person you pinged on the MS side didn't respond

**Comment by shawnxzq** [comment]
@nschonni I once though this issue is opened to MS service team by the MS swagger/SDK team, and the issue itself is not something service team is working on, so close it since the team didn't respond to it. 

So what's the issue caused in your side? Thanks!
