### ISSUE TITLE
[Microsoft.Sql] [APIIssue] Missing APIs for securityAlertPolicies

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-rest-api-specs#4910]
LIST api to get all securityAlertPolicies for a database missing.
StorageAccountAccessKey MUST not be returned in GET/PUT response

**Comment by aamalvea** [comment]
@ayeletshpigelman Can you take a look at this?

**Comment by ayeletshpigelman** [comment]
Hi,

there is always only one policy. is this API needed anyway?

**Comment by jeroenterheerdt** [comment]
@ravbhatnagar can you please answer @ayeletshpigelman's question? I'll close the issue 1/1 if you do not reply.
