### ISSUE TITLE
[Redis Cache][Doc] Export operation has "import" documentation

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#497]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L418 

import has the same documentation - https://github.com/Azure/azure-rest-api-specs/blob/master/arm-redis/2016-04-01/swagger/redis.json#L372 

I think there is no need for 2 methods (export/import) that has the same functionality ;)

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by SiddharthChatrolaMs** [comment]
Discussed this on IM with Hovsep

**Comment by hovsepm** [comment]
The issue is fixed in the most latest swagger version of Redis. Closing.
