### ISSUE TITLE
Storage custom domain indirect validation does not work

### ISSUE THREAD

**Issue by bernerha** [Azure/azure-rest-api-specs#4995]
The az cli uses another argument for the custom domain verification (broken) as the REST API offers (works).

We are using the REST API as a workaround because the az cli is broken.
The command
`account update --use-subdomain true --custom-domain xxx --name xxx --subscription xxx`
doesn't update the attribute "useSubDomain".

Funfact: The REST API doesn't use "useSubDomain" it uses "useSubDomainName".
After the REST call:
`
curl --request PATCH --data '{"properties": {"customDomain": {"name": "xxx", "useSubDomainName": true}}}' -H "Authorization: Bearer xxx" -H "Content-Type: application/json" https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/res9407/providers/Microsoft.Storage/storageAccounts/sto8596?api-version=2018-07-01
`

the config get changed to:

`
"customDomain": { "name": "xxx", "useSubDomain": null, "useSubDomainName": "true" },
`

and everything works as expected.

Relatet issue in another project: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2542

**Comment by jhendrixMSFT** [comment]
This was fixed in https://github.com/Azure/azure-rest-api-specs/pull/4938
