### ISSUE TITLE
Resource group name pattern does not accept parenthesis

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-rest-api-specs#502]
From the documentation at https://msdn.microsoft.com/en-us/library/azure/dn790546.aspx:
{resource-group-name} must uniquely identify the resource group within the subscription. It must be no longer than 80 characters long. It can only contain alphanumeric characters, dash, underscore, **opening parenthesis, closing parenthesis** or period. The name cannot end with a period. Currently, using a parenthesis in the name causes problems when using Azure PowerShell or Azure CLI. Therefore, we recommend you avoid using an opening or closing parenthesis in the name.

Here are some examples of operations that have this issue from the spec:
[ResourceGroups_CreateOrUpdate](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2015-11-01/swagger/resources.json#L589)
[ResourceGroups_Delete](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2015-11-01/swagger/resources.json#L637)
[ResourceGroups_Patch](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2015-11-01/swagger/resources.json#L637)
[ResourceGroups_Get](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2015-11-01/swagger/resources.json#L671)

azure-xplat-cli, azure-cli and azure-powershell all have open issues relating to this:
https://github.com/Azure/azure-xplat-cli/issues/3109
https://github.com/Azure/azure-cli/issues/799
https://github.com/Azure/azure-powershell/issues/2768

**Comment by lmazuel** [comment]
You mean this is a bad idea:
https://github.com/Azure/azure-rest-api-specs/pull/490

**Comment by lmazuel** [comment]
@derekbekoe  Ok, I undertand now, you want #490 to be used in all Swagger files with RG right?
Because currently the Swagger is blocking valid syntax like "derek(4".
Am I right?

**Comment by derekbekoe** [comment]
@lmazuel I did not see PR #490 when I created this issue. It looks like that takes care of it.

Where RG is defined in other Swagger files, if there is pattern matching on RG, the pattern should be correct. If there isn't pattern matching, it would be okay to leave it.

**Comment by derekbekoe** [comment]
Once new SDKs get generated and integrated into the CLIs & PowerShell, it looks like those related issues can also be closed then.

**Comment by derekbekoe** [comment]
Closing issue as #490 was the fix for this.
