### ISSUE TITLE
Load Balancer SKU returns a Tier field not specified in documentation

### ISSUE THREAD

**Issue by danielestevez** [Azure/azure-rest-api-specs#5049]
https://github.com/Azure/azure-rest-api-specs/blob/aa18874b5c74b41c0e1d94c1422bd4e000a448ec/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/loadBalancer.json#L1040

REST API returns a tier field in any GET operation (https://docs.microsoft.com/en-us/rest/api/load-balancer/loadbalancers/listall) as part of the LoadBalancerSKU object, but this is not included in this specification or in the actual documentation

` "sku": {
        "name": "Basic",
        "tier": "Regional"
      }`

Is this missing in the specification/documentation and has a meaning? Or the API is returning a wrong field there?

**Comment by gmainar** [comment]
A fix has been made so that the field won't be returned by server.

**Comment by danielestevez** [comment]
Thanks for the fix! I suppose there's no Tier or implications associated to this field
