### ISSUE TITLE
Insights API Status?

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-rest-api-specs#505]
Hi, is anyone working on the Insights APIs? Is there an expected timeline yet?

**Comment by amarzavery** [comment]
The PR has been submitted https://github.com/Azure/azure-rest-api-specs/pull/496 and it is in review.

**Comment by tombuildsstuff** [comment]
Looks like the Team has been focused around adding the swagger required for checks/monitoring for the moment

I've just opened a PR to add support for CRUDing Application Insights instances which we can use to build the API's if it helps? https://github.com/Azure/azure-rest-api-specs/pull/757

**Comment by kirthik** [comment]
@tombuildsstuff : Just want to clarify Insights API is different from Application Insights

**Comment by kirthik** [comment]
Insights management plane Spec is checked in here - https://github.com/Azure/azure-rest-api-specs/tree/master/arm-insights 
Data plane spec is here - https://github.com/Azure/azure-rest-api-specs/tree/master/insights
