### ISSUE TITLE
two reference names for same field VirtualNetworkPeeringParameters

### ISSUE THREAD

**Issue by sheenaajay** [Azure/azure-rest-api-specs#5064]
two reference names for same field VirtualNetworkPeeringParameters

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetwork.json#L657

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetwork.json#L1067

**Comment by jl-ms** [comment]
Investigating. Thanks for the patience.

**Comment by allegradomel** [comment]
@sheenaajay - I'm looking into this but can't see what you're pointing out in these files - can you please comment with the appropriate lines so I can take a look?

**Comment by allegradomel** [comment]
Closing since no response - please let us know if the issue persists @sheenaajay
