### ISSUE TITLE
Monitor MetricAlerts incorrect casing of webhook properties results in downstream bugs

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-rest-api-specs#5065]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json#L323

See: https://github.com/Azure/azure-cli/issues/8223

I believe the correct casing should be `webHookProperties` not `webhookProperties`. When I use the CLI to create an alert with this field, it populates the `webHookProperties` field on the server. However, because `webhookProperties` gets propagated to the Python SDK, when I try and then update this alert, the data is lost (because it sends it as `webhookProperties` that the service ignores).

**Comment by osariel** [comment]
targetResourceType property is missing or invalid.. [Code: "BadRequest"]

**Comment by yashmuel** [comment]
@tjprescott this issue has been closed (Azure/azure-cli#8223)
can we close the current as well?

**Comment by tjprescott** [comment]
@yashmuel, based on the discussion in the CLI issue, it seems this has been fixed, perhaps on the service end. You should be good to close this.

**Comment by yashmuel** [comment]
Thanks, closing.
