### ISSUE TITLE
Cosmosdb account name should have regexp matching

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#5066]
Account name does not support "_" character, and error from service is not helpful.

The usual fix here is to define a regexp with the correct pattern that matches a possible account name on the server. This allows client side validation.

Create issues for customers:
https://github.com/Azure/azure-sdk-for-python/issues/4210

**Comment by shurd** [comment]
We are tracking this change internally as work item 449210. The change is in review, and should be available in the swagger within the next two weeks. This is not an urgent change, so we will wait to release new SDKs until the next substantial change.
