### ISSUE TITLE
Publish owners of the API schemas.

### ISSUE THREAD

**Issue by tariq1890** [Azure/azure-rest-api-specs#5085]
It is helpful to know who the owners of the Schema are, so that we can ask the right people when the consumers have questions.

Perhaps, we could add an owners field in the swagger JSONs.

**Comment by tariq1890** [comment]
A response would be greatly appreciated.

**Comment by akning-ms** [comment]
Hi @tariq1890  we have codeowner file in repo to know who is the owner for the RP. it is useful for your question?

**Comment by tariq1890** [comment]
@akning-ms I don't work for Microsoft anymore

**Comment by akning-ms** [comment]
codeowner file can support this requirement, so close the issue
