### ISSUE TITLE
Missing APIs in arm-search Swagger spec

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-rest-api-specs#509]
Missing apis in swagger spec [https://github.com/Azure/azure-rest-api-specs/tree/05d88eea8224e737c7f32d36efd04881b346ecf7/arm-search/2015-02-28/swagger/search.json]
-   GET on searchService/{name} [list is there in swagger]
-   List
-   POST on searchServices/{name}/regenerateAdminKey/{keyType}
-   POST on checkNameAvailability
-   PUT, GET and DELETE operations on queryKey, there is only one operation available in swagger to listQueryKeys.
  Missing APIs in swagger spec which are not listed on on https://msdn.microsoft.com/en-us/library/azure/dn832684.aspx but working.
-   POST on searchServices/{name}/Start
-   POST on searchServices/{name}/Stop

**Comment by brjohnstmsft** [comment]
Added missing operations in the latest Swagger: https://github.com/Azure/azure-rest-api-specs/pull/637

Note that we are purposefully omitting "Start" and "Stop" because these operations don't do anything useful and tend to confuse customers who think that Stop should suspend billing (it doesn't).
