### ISSUE TITLE
Missing supported SKUs in arm-search Swagger spec

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-rest-api-specs#510]
Missing supported SKUs in arm-search Swagger spec [https://github.com/Azure/azure-rest-api-specs/tree/05d88eea8224e737c7f32d36efd04881b346ecf7/arm-search/2015-02-28/swagger/search.json]

Following SKUs are missing
-   Basic,
-   S3 Standard (Preview)
-   S3 Premium (Preview)

**Comment by brjohnstmsft** [comment]
New SKUs have been added in the latest Swagger: https://github.com/Azure/azure-rest-api-specs/pull/637
