### ISSUE TITLE
Wrong operation metadata returned by Azure Search RP [arm-search]

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-rest-api-specs#511]
Operation metadata returned by Search service is inaccurate (some operations are not working and some are not listed)
Additional APIs listed (but are not implemented) in (https://management.azure.com/providers/Microsoft.Search/operations?api-version=2015-08-19)
-   Operations on diagnosticSettings
-   Operations on metricDefinitions
-   Operation on logDefinitions
-   Microsoft.Search/searchServices/queryKey/read
-   Microsoft.Search/searchServices/queryKey/delete

There are missing action in the operation metadata
Like get on listQueryKey, deleteQueryKey which are listed on https://msdn.microsoft.com/en-us/library/azure/dn832684.aspx 

Other suggestions for APIs design
-   queryKey could have been a nested (child) resource and CRUD operations could be supported on that rather than 3 different actions listQueryKeys, createQueryKey and deleteQueryKey.
  o   Also auto generated query key is not named, it should be named
  o   Deleting a key require key as parameter rather than name, which will make it hard to use for users.
-   regenerateAdminKeys/{keyType} does not look like an action on the searchServices resource, it looks like an nested resource. If regenerateAdminKeys is an action parameter to that should be there after ? or in the body.

**Comment by brjohnstmsft** [comment]
I've added the missing query key operations in the latest Swagger: https://github.com/Azure/azure-rest-api-specs/pull/637

The `diagnosticSettings`, `metricDefinitions`, and `logDefinitions` operations are internal implementation details of the AppInsights feature and are not meant to be exposed through ARM directly (from any RP, not just Search).

Regarding API design choices, our RP was designed long before the ARM contract was stable. We'll consider improving the API the next time we have to make major changes to it.
