### ISSUE TITLE
Wrong API version mentioned in Azure Search RP [arm-search]

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-rest-api-specs#513]
Wrong API version mentioned in arm-search Swagger spec [https://github.com/Azure/azure-rest-api-specs/tree/05d88eea8224e737c7f32d36efd04881b346ecf7/arm-search/2015-02-28/swagger/search.json]

Swagger is targeting older version 2015-02-28 whereas current version seems to be 2015-08-19

**Comment by brjohnstmsft** [comment]
New Swagger for 2015-08-19 is now available: https://github.com/Azure/azure-rest-api-specs/pull/637
