### ISSUE TITLE
MetricValue.count incorrectly marked as int64, service returns a float

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#5130]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/3949

Count is an int, but the JSON is a float:
```
error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number 4.0 into Go struct field MetricValue.count of type int64' , json looks like ... {"timeStamp":"2019-01-27T04:32:00Z","count":4.0}
```
Here's the offending swagger (there might be other instances, please verify).
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-01-01/metrics_API.json#L169

**Comment by salameer** [comment]
@aydany can you kindly take a look ?

**Comment by akahn** [comment]
Our application will need to be able to get `Count` from the metrics API. Any update on getting this issue fixed?

**Comment by asheniam** [comment]
Thanks for reporting this.  We are looking at fixing the swagger.

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/azure-rest-api-specs/pull/6485
