### ISSUE TITLE
Microsoft.Compute/skus shows Availability Zone support in East US

### ISSUE THREAD

**Issue by justnoise** [Azure/azure-rest-api-specs#5163]
This is more of a data issue...

I'm seeing the `Microsoft.Compute/skus` API ([https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list](https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list)) giving bad data data for Availability Zones support in location "East US".  This can be seen from the command line:
```
az vm list-skus -l eastus --zone -otable

ResourceType     Locations    Name                Zones    Capabilities
---------------  -----------  ------------------  -------  --------------
virtualMachines  eastus       Standard_B1ms       1,2,3    ['MaxResourceVolumeMB=4096',... ]
...
```

However, per the [docs](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview#regions-that-support-availability-zones) and testing it out, it's not possible to launch VMs into an availability zone in `East US`.  Trying to do so via the API gives an error code `ResourceTypeNotSupportAvailabilityZones`.  The Azure portal allows the user to specify an AZ in East US.  The validation step fails at the end of the process.  The error is: 

`The resource type 'virtualMachines' does not support availability zones at location 'eastus' and api-version '2017-05-10'.'.'. (Code: InvalidTemplateDeployment)`

In the portal, other locations without AZ support have the AZ option grayed out.  This makes me think that the bug is caused by bad data returned from https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list

This bug impacts any software using resourceskus/list to determine availability zone support for a location.

Note: I was pointed at the issue tracker in this repo by @AzureSupport in a twitter PM.  Let me know if there is a better place to submit this issue.

**Comment by salameer** [comment]
ping @savyasachisamal

**Comment by mjconnection** [comment]
This was an intermediate state when Availability Zones were being enabled in East US.  Availability Zones in East US are available now.
