### ISSUE TITLE
momentOfTruth script error - linter running out of memory for network specs

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#5200]
Looks like Linter tool is running out of memory, see Example https://travis-ci.org/Azure/azure-rest-api-specs/jobs/492486405
Error:
<--- Last few GCs --->\n\n[5764:0x2e975b0]   193421 ms: Mark-sweep 1329.1 (1544.4) -> 1329.0 (1544.9) MB, 1707.8 / 0.0 ms  allocation failure GC in old space requested\n[5764:0x2e975b0]   195063 ms: Mark-sweep 1329.0 (1544.9) -> 1329.0 (1496.4) MB, 1641.4 / 0.0 ms  last resort GC in old space requested\n[5764:0x2e975b0]   196640 ms: Mark-sweep 1329.0 (1496.4) -> 1329.0 (1489.9) MB, 1576.7 / 0.0 ms  last resort GC in old space requested\n\n\n<--- JS stacktrace --->\n\n==== JS stack trace =========================================\n\nSecurity context: 0xb5f532258b9 <JSObject>\n    1: split(this=0x11b912438731 <String[184]: mem:///172?file%3A%2F%2F%2Fhome%2Ftravis%2Fbuild%2FAzure%2Fazure-rest-api-specs%2Fspecification%2Fnetwork%2Fresource-manager%2FMicrosoft.Network%2Fstable%2F2018-12-01%2FrouteTable.json>)\n    2: get Description [/home/travis/.autorest/@microsoft.azure_autorest-core@2.0.4302/node_modules/@microsoft.azure/autorest-core/dist/lib/data-store/data-store.js:...\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: node::Abort() [node]\n 2: 0x8ccf9c [node]\n 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]\n 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]\n 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]\n 6: v8::internal::HashTable<v8::internal::StringTable, v8::internal::StringTableShape>::NewInternal(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [node]\n 7: v8::internal::HashTable<v8::internal::StringTable, v8::internal::StringTableShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [node]\n 8: v8::internal::HashTable<v8::internal::StringTable, v8::internal::StringTableShape>::EnsureCapacity(v8::internal::Handle<v8::internal::StringTable>, int, v8::internal::PretenureFlag) [node]\n 9: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [node]\n10: v8::internal::RegExpResultsCache::Enter(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::FixedArray>, v8::internal::Handle<v8::internal::FixedArray>, v8::internal::RegExpResultsCache::ResultsCacheType) [node]\n11: v8::internal::Runtime_StringSplit(int, v8::internal::Object**, v8::internal::Isolate*) [node]\n12: 0x23f767b042fd\nAborted (core dumped)]'

SyntaxError: Unexpected token < in JSON at position 48633

**Comment by salameer** [comment]
Hi @Veronica, please cover this in our dashboards
