### ISSUE TITLE
Swagger update required for user assigned MSI

### ISSUE THREAD

**Issue by navdixit** [Azure/azure-rest-api-specs#5237]
We are using Fluent SDK Microsoft.Azure.Management.AppService.Fluent (ref: https://github.com/Azure/azure-libraries-for-net) for creating Azure functions. We are planning to use “user assigned” MSI for functions apps. When we followed the [documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fapp-service%2Foverview-managed-identity%23adding-a-user-assigned-identity-preview&data=02%7C01%7Cnavdixit%40microsoft.com%7C7d29361292644085230908d6946ff069%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636859605828494405&sdata=%2F6ROa2ZmWb5ta0vEr6Tap%2FksSzgCrM8aQQsCwJ55zi4%3D&reserved=0), couldn’t find an option to assign “user assigned MSI” to a functions app using Fluent library.
To have this feature done in fluent sdk, swagger update is needed.

James Christianson should be able to help on this issue.

**Comment by anuchandy** [comment]
Closing this issue, update necessary for UMSI are in.

https://github.com/Azure/azure-rest-api-specs/pull/5288
https://github.com/Azure/azure-rest-api-specs/pull/5542
https://github.com/Azure/azure-rest-api-specs/pull/5536
