### ISSUE TITLE
TumblingWindowTrigger struct is missing the `Annotations` field

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#5274]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/4147

See type defined here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L333

**Comment by hvermis** [comment]
The annotations have been added to Trigger base class:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L27
