### ISSUE TITLE
Swagger comment for Key Vault Access Policy has the wrong value

### ISSUE THREAD

**Issue by WodansSon** [Azure/azure-rest-api-specs#5303]
Per the documentation Key Vault supports 1024 access policies:
https://docs.microsoft.com/en-us/azure/key-vault/key-vault-secure-your-key-vault#data-plane-access-control

The current swagger states that it supports 0 - 16 access policies:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2018-02-14/keyvault.json#L858

However, the RP controller code was updated on 6/4/2018 to support the 1024 value:
```
private const int MaxVaultAccessPolicies = 1024;
```

Can we get the swagger updated to reflect the correct 1024 number?

**Comment by ShaneBala-keyvault** [comment]
assign MARKGRAY

**Comment by ShaneBala-keyvault** [comment]
#assign MARKGRAY
