### ISSUE TITLE
Trying to stop a backup job that is currently copying data to the vault results in a 400 error code

### ISSUE THREAD

**Issue by FelixBorst** [Azure/azure-rest-api-specs#5306]
I recently updated my azure recovery services vault to v2 using the command:

```
HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Features/providers/Microsoft.RecoveryServices/features/InstantBackupandRecovery/register?api-version=2015-12-01
```

This will let the azure recovery services do a backup in the following order:
1. Take snapshot
2. Create recovery point
3. Transfer snapshot to recovery services vault

I now try to cancel a running backup job that is in the process of transferring the snapshot to the vault the error occurs. I used the following calls:

```
HTTP Method:
POST

Absolute Uri:
https://management.azure.com/Subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.RecoveryServices/vaults/MyVault/backupJobs/MyBackupJobID/cancel?api-version=2016-12-01
```

This gives me the jobId of the cancelJob as a result (in this case: dfe88208-88f6-48fb-81ee-52d4187b1dc0):

```
https://management.azure.com/Subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.RecoveryServices/vaults/MyVault/backupJobs/MyBackupJobID/operationResults/dfe88208-88f6-48fb-81ee-52d4187b1dc0?api-version=2016-12-01
```

If I now check for the status of the running job using
```
HTTP Method:
GET

Absolute Uri:
https://management.azure.com/Subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.RecoveryServices/vaults/MyVault/backupJobs/Azure/operationResults/dfe88208-88f6-48fb-81ee-52d4187b1dc0?api-version=2016-12-01
```

It gives me a 400 Bad Request Error.

The above commands have been tested using:
- The PowerShell Cmdlet "Stop-AzureRmRecoveryServicesBackupJob" (AzureRM.RecoveryServices.Backup v4.4.1)
- The PowerShell Cmdlet "Stop-AzRecoveryServicesBackupJob"(Az.RecoveryServices v1.0.0)
- The API directly

As this error also occured when calling the API directly, I thought this would be the best place to open the issue.
Am I doing something wrong here or is this feature not yet supported?

**Comment by FelixBorst** [comment]
Any news on this one?

**Comment by pvrk** [comment]
You can only cancel the job as long as it is in the first state (take snapshot). Once that phase is completed and the job moves to the data transfer phase, a backup job cannot be cancelled. Will document this behavior

**Comment by FelixBorst** [comment]
Hi @pvrk, thank you for your answer.

A documentation would be helpful indeed, but I feel a better interaction with the user would also be helpful. Right now you just get an error message that does not contain any details:
The Azure portal only throws an "An error occured" message, the REST api does not give any details either?

In my opinion, a fitting error message would enhance the user experience with this endpoint.

**Comment by pvrk** [comment]
@FelixBorst: Thanks for the elaboration and I acknowledge the issue. Will work on it and update this thread. For now, marking this as a question. Once I know more about the REST API response, will change to bug/new feature request.

**Comment by TAdityaAnirudh** [comment]
Hi there. Couple of updates on this one. 
1. We have started using azure-async-header along with the location header for most of our long running operations, cancel job being one of them. Please use that to track cancellation operations. They provide much better error messages.
2. We have updated the error message to reflect the current status and its cancel-ability. Changes should roll out to production in a month's time.
Hope this addresses the concerns.

**Comment by pvrk** [comment]
@FelixBorst : Have you read @TAdityaAnirudh 's response? Hope this is clear. Can we proceed to closing the issue?

**Comment by pvrk** [comment]
@FelixBorst: Any update on this?

**Comment by pvrk** [comment]
@FelixBorst : Another gentle reminder. Any update on this?

**Comment by pvrk** [comment]
@FelixBorst : Another gentle reminder. Please update us with your latest findings.

**Comment by pvrk** [comment]
Closing this issue due to lack of response. Customer can re-open the issue with the new/updated findings.
