### ISSUE TITLE
MachineLearning: description should not contain HTML tag

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#531]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-machinelearning/2016-05-01-preview/swagger/webservices.json#L5

```
"description": "These APIs allow end users to operate on Azure Machine Learning Web Services resources. They support the following operations:<ul><li>Create or update a web service</li><li>Get a web service</li><li>Patch a web service</li><li>Delete a web service</li><li>Get All Web Services in a Resource Group </li><li>Get All Web Services in a Subscription</li><li>Get Web Services Keys</li></ul>",
```

**Comment by lmazuel** [comment]
@amarzavery I'm not sure based on the history of the file to who I should assign this. If you could take a look :)

**Comment by amarzavery** [comment]
@ericwill-msft and @tudorid - can you take a look at this issue?

**Comment by kirthik** [comment]
@lmazuel : Could you clarify the issue with HTML in description?

**Comment by lmazuel** [comment]
@kirthik not all language use the same kind of generator to build their technical documentation. Or we can use documentation generator that are not HTML at all.

In case of Python, HTML tags are not expected and produce bad documentation. So, I see two solutions:
- We consider description fields are HTML, and we have to remove them in Python in our pre-process treatment
- We consider description fields are basic text, and not HTML tags are allowed.

No HTML is more open to scenarios. But if it's part of the docs.microsoft.com process to produce doc, I can understand :)

**Comment by lmazuel** [comment]
Note that Swagger spec says:
description - string - A short description of the target documentation. [GFM syntax](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) can be used for rich text representation.

**Comment by troydai** [comment]
I'd like to upvote this issue. I saw HTML elements in monitor's SDK as well. It's a bad practice. HTML is a presentation level language, it shouldn't be used to describe rich text in lower level spec definitions. The higher level conversion of the spec, for example, Python SDK pulls the HTML tags directly into their doc string ([example](https://github.com/Azure/azure-sdk-for-python/search?p=2&q=%3Cbr%3E&type=&utf8=%E2%9C%93)) will introduce unwanted noise into CLI.
