### ISSUE TITLE
[API Management] Missing "202 Accepted" for Delete operation

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-rest-api-specs#5316]
In the current stable version of the API Management Service, when doing a `DELETE` on an existing API Management Service, an HTTP 202 Accepted is returned. However, 202 is not defined as a valid HTTP return code for this service.

Spec in question: https://github.com/Azure/azure-rest-api-specs/blob/7cfc460c5b4f17a896510314e12432f9fdc2eecd/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/apimdeployment.json#L361-L395 (missing 202)

**Comment by solankisamir** [comment]
Delete on 2018-01-01 was sync operation, hence 202 is not valid response. Starting 2019-01-01 api version, Delete on service is async and had been added to the spec
