### ISSUE TITLE
`Resource ID` is missing in API Management Logger response

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-rest-api-specs#5318]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/4211

According to the response documented [here](https://docs.microsoft.com/en-us/rest/api/apimanagement/logger/createorupdate#apimanagementcreateehlogger) the `LoggerContractProperties` type should have a `resourceId` field however it's missing from the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/apimloggers.json#L396).

**Comment by solankisamir** [comment]
The example is from `2018-06-01-preview`  version and resourceId is documented in the rest spec - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/apimloggers.json#L459

**Comment by jhendrixMSFT** [comment]
@solankisamir thanks!
@junyiyi see package github.com/Azure/azure-sdk-for-go/services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT unfortunately we're unable to use the `2018-06-01-preview` API at this time [due to the breaking change in the API](https://github.com/Azure/azure-rest-api-specs/issues/4409); since this exists in the response from the `2018-01-01` API - would it be possible to get this exposed in the Swagger there too?

Thanks!

**Comment by jhendrixMSFT** [comment]
That would be up to @solankisamir if this functionality is available in that API version.

**Comment by solankisamir** [comment]
@tombuildsstuff which end to end story is impacted due to missing `resourceId` property in `2018-01-01`

**Comment by tombuildsstuff** [comment]
@solankisamir this not being exposed at this time means we're unable to expose the resourceID field in the Terraform resource for API Management Loggers: https://github.com/terraform-providers/terraform-provider-azurerm/pull/2994
