### ISSUE TITLE
Possible bug in arm-intune paging response

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-rest-api-specs#532]
The GET MAM statuses call defined here:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-intune/2015-01-14-preview/swagger/intune.json#L1498

Uses the x-ms-pagable extension, yet the schema referenced as the response model is not a collection:

```
"StatusesDefault": {
      "properties": {
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/StatusesProperties"
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        }
      ],
      "description": "Default Statuses entity for the given tenant."
    }
```

Is this intentional? It definitely doesn't generate correctly with the Autorest Python generator, but maybe this is handled in other languages?
FYI @lmazuel

**Comment by annatisch** [comment]
@amarzavery, @tbombach,
Are you guys able to comment on whether this swagger is valid/standard?
If so I will need to adapt the Python generator to accommodate it - it seems the C# client already handles this scenario, but I'm not sure whether that's intentional or not....

**Comment by salameer** [comment]
Hi @annatisch I'll close this one for now since it seems that it's been open for a while, please reopen of you believe it's still a problem
