### ISSUE TITLE
Readonly flag is missing from the specs virtualNetwork.json

### ISSUE THREAD

**Issue by sheenaajay** [Azure/azure-rest-api-specs#5371]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetwork.json#L1040

 "provisioningState"

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetwork.json#L1215

        "resourceGuid": {
          "type": "string",
          "description": "The resourceGuid property of the Virtual Network resource."
        },

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/virtualNetwork.json#L1219

        "provisioningState": {
          "type": "string",
          "description": "The provisioning state of the PublicIP resource. Possible values are: 'Updating', 'Deleting', and 'Failed'."
        },

**Comment by salameer** [comment]
Hi @MikhailTryakhov please route as required

**Comment by MikhailTryakhov** [comment]
It's RNM

**Comment by chandrasekarsrinivasan** [comment]
Assigning to Amol.

**Comment by allegradomel** [comment]
@sheenaajay,
Thanks for bringing this to our attention - we're working on this and will update soon

**Comment by allegradomel** [comment]
@sheenaajay, this has been fixed[ check the most recent version ](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualNetwork.json)

**Comment by allegradomel** [comment]
#please-close
