### ISSUE TITLE
Service Fabric REST API - method 'Deploy Service Package To Node' results in serialization error 500

### ISSUE THREAD

**Issue by MattiKiiskinen** [Azure/azure-rest-api-specs#5380]
I am trying to use REST API method [Deploy Service Package To Node](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deployservicepackagetonode). When request is sent to cluster, I got error

> The remote server returned an error: (500) SerializationError.

URI and body of the request has been built with following approach. 
```// Uri
string uri = string.Format( "https://{0}/Nodes/{1}/$/DeployServicePackage?api-version={2}&timeout={3}",
		this.ClusterConnection, nodeName, apiVersion, timeout );

// Request body
dynamic jsonBody = new JObject();
jsonBody.ServiceManifestName = this.ServiceManifestName;
jsonBody.ApplicationTypeName = this.ApplicationTypeName;
jsonBody.ApplicationTypeVersion = this.ApplicationTypeVersion;
jsonBody.NodeName = nodeName;

// Serialize body.
string body = JsonConvert.SerializeObject( jsonBody );

// Invoke request
InvokePost( uri, body );
```

I have used similar approach with other Service Fabric REST API request [Provision Application Type](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-provisionapplicationtype) which is executed successfully. Debugging the URI and parameters did not reveal anything when I compared the failing and successful requests.

**Failing request - Deploy Service Package To Node**:

URI:
`https://mycluster.westeurope.cloudapp.azure.com:19080/Nodes/_nt1vm_2/$/DeployServicePackage?api-version=6.0&timeout=60`

Body:
```
{
"ServiceManifestName": "MyContainerPkg",
"ApplicationTypeName": "MyContainer",
"ApplicationTypeVersion": "1.0.0",
"NodeName": "_nt1vm_2"
}
```

**Successful request - Provision Application Type**:

URI: 
`https://mycluster.westeurope.cloudapp.azure.com:19080/ApplicationTypes/$/Provision?api-version=6.2&timeout=60`

Body:

```
{
  "Kind": "ImageStorePath",
  "ApplicationTypeBuildPath": "MyContainer",
  "ApplicationPackageCleanupPolicy": "Automatic"
}
```

**Is there anything special that I have misunderstood from the reference [Deploy Service Package To Node](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deployservicepackagetonode)?** 

**Another question: why parameter 'nodeName' is given both in path and body?** Path/query parameters listed in [Deploy Service Package To Node](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deployservicepackagetonode) vs. body parameters listed in [DeployServicePackageToNodeDescription](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-deployservicepackagetonodedescription)

**Comment by MattiKiiskinen** [comment]
Some more information:

I have uploaded the manifest files to Image Store, and provisioned the application type using the REST API. I can create application using REST API method [Create Application](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-createapplication), so the manifest files should be OK. There are set of parameters in the application manifest files, which are set ParameterList given in [ApplicationDescription](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-applicationdescription).

The values given in [body parameters](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-deployservicepackagetonodedescription) of Deploy Service Package To Node do match to the app. type that is provisioned to the cluster. Values of ServiceManifestName, ApplicationTypeName and ApplicationTypeVersion are same as set in manifest files and as visible in SF Explorer, and value of NodeName parameter is set to a node name read from the cluster with [GetNodeInfoList](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getnodeinfolist) API. 

The package is quite big, and thus I would use to [Deploy Service Package To Node](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-deployservicepackagetonode), for the reasons described in the reference:

> this API provides a way to download code packages including the container images on a specific node outside of the normal application deployment and upgrade path. This is useful for the large code packages and container images to be present on the node before the actual application deployment and upgrade, thus significantly reducing the total time required for the deployment or upgrade

**Any ideas what could cause my problem with the "serialization error" ? 
How could I debug this more in detail?**

**Comment by salameer** [comment]
Hi @vipul-modi 

Any thoughts on who can help out on this topic from Service Fabric's side?

**Comment by iyyappam** [comment]
It is a bug in our code that is not handling empty “PackageSharingPolicyInfo” correctly. We will fix it in the next iteration. In the mean time, could you try creating the body with “PackageSharingPolicyInfo” (with “PackageSharingScope” to “None”).

**Comment by salameer** [comment]
Hi @MattiKiiskinen 

Kindky retry the workaround and re-open if still needed
