### ISSUE TITLE
Description for enum type

### ISSUE THREAD

**Issue by lebronJ** [Azure/azure-rest-api-specs#5516]
I have searched for whether OpenAPI Specification (Swagger) supports descriptions for individual enum values and found the current answer seems no. Just to double confirm if this is correct or any workarounds.

We'd like this feature for better API reference, e.g. [here](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/face/face/detectwithstream#recognitionmodel).

**Comment by brjohnstmsft** [comment]
@lebronJ I agree; This is a long-standing pain point for my team too. However, I recommend opening this issue in the Azure/AutoRest repo. That's where such a feature would need to be implemented.

**Comment by lebronJ** [comment]
> @lebronJ I agree; This is a long-standing pain point for my team too. However, I recommend opening this issue in the Azure/AutoRest repo. That's where such a feature would need to be implemented.

Thanks @brjohnstmsft for the response, understood.
