### ISSUE TITLE
Specs do not seem to include common storage services

### ISSUE THREAD

**Issue by pimterry** [Azure/azure-rest-api-specs#5520]
I'm trying to integrate these specs into an [HTTP debugging tool](https://httptoolkit.tech), to automatically do request validation & documentation by comparing the spec definitions to real HTTP requests.

In theory that all works great, but on close inspection I'm struggling to find the specs for many of the common operations in the Azure docs that I'd like more detail on. For example:

* List containers on the Blob service: https://docs.microsoft.com/en-us/rest/api/storageservices/list-containers2
	* The URL should be `https://<account-name>.blob.core.windows.net/?comp=list`
	* I can't find a single spec that specifies anything like that as a `host` or `x-ms-parameterized-host`
* Putting a message on a queue with the Queue Service: https://docs.microsoft.com/en-us/rest/api/storageservices/put-message
	* The URL should be `https://<account-name>.queue.core.windows.net/<queue-name>/messages`
	* I can't find any specs with any kind of host like this, or containing `/messages`
	* I can't find any specs refering to the `visibilitytimeout` param, or the `QueueMessagesList` type of the response

Do specs for these operations exist somewhere? I've given it a good search, and I'm really surprised I can't find them, given there's so many other services that are documented here, and I would've expected these services to be very commonly used. What am I missing?

**Comment by anuchandy** [comment]
@rickle-msft is this something your team can help triaging?

**Comment by rickle-msft** [comment]
@pimterry The swagger for Storage services (blob, queue, file) is not published here yet. It has been our intention to publish them for a while, so I will bring it up with my team again to see if we can move them into this repo.

**Comment by pimterry** [comment]
Ah, I see, thanks @rickle-msft! It would be very useful to have those specs here, if that's at all possible.

**Comment by zhusijia26** [comment]
Based on conversation with @rickle-msft , the ETA is 8/23/2019.

**Comment by kartikshah9** [comment]
@rickle-msft is there an update on this item. Accordingly we can close the item

**Comment by rickle-msft** [comment]
@kartikshah9 We did GA the SDKs based on the 2019-02-02 swagger. You can see those swaggers here: https://github.com/Azure/azure-rest-api-specs/tree/storage-dataplane-preview. 2019-02-02 should be stable in terms of its api surface since we publicly released packages based on it. The timeline of getting those merged into master is a little less clear. Perhaps @tg-msft or @pemari-msft could speak more to that.

**Comment by tg-msft** [comment]
I can't speak for the timeline, but that work is being tracked by https://github.com/Azure/azure-sdk/issues/859

**Comment by amishra-dev** [comment]
please reactivate if you have futher questions, i see that the docs have been updated with more details.
