### ISSUE TITLE
Support unregister for Microsoft.Features

### ISSUE THREAD

**Issue by jluk** [Azure/azure-rest-api-specs#5607]
AKS heavily utilizes the feature registration process for preview capabilities. We educate customers to use az feature register, but there is currently no simple user operation to undo this action. Ask is to support unregister via swagger so CLI can consume this downstream.

**Comment by jhendrixMSFT** [comment]
@mzehgir do you know what team this should be routed to?

**Comment by andyliuliming** [comment]
+1

**Comment by jluk** [comment]
@krisbash or @ravbhatnagar thoughts?

**Comment by ifeoluwaokunoren** [comment]
Fix merged: https://github.com/Azure/azure-rest-api-specs/pull/8788
