### ISSUE TITLE
Fix the examples in Consumption 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#5625]
There are existing model validation errors for Consumption. Refer https://travis-ci.org/Azure/azure-rest-api-specs/jobs/518056993

**Comment by bgsky** [comment]
Thanks for creating an issue to help track progress on scope validations. We will propose a new preview version to address scope validations soon.

**Comment by ms-premp** [comment]
This should already be resolved.

**Comment by ramaganesan-rg** [comment]
Resolving as per Prem's comments. thank you!
