### ISSUE TITLE
Looking for CPU memory usage REST API in azure

### ISSUE THREAD

**Issue by madhut** [Azure/azure-rest-api-specs#5664]
Hi There,
I was trying to find the REST API for the cpu memory usage in azure for the list of subscriptions . In list of subscriptions looking for each resource group- > each VM usage details . Also would like to know the allocation and the usage memory in GB.
Can someone help me with this issue?
Thanks,
Venkata

**Comment by salameer** [comment]
hi @Madhut is this a Dup of #5703, I will close for now and You can vote on the other one and add your comments there, if not please reopen this one

THANKS for reaching OUT :)
