### ISSUE TITLE
Breaking Change in the Log Analytics Solution API

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#5676]
👋 

We've noticed a breaking change in the API Response for the Log Analytics Solution API - where the `location` field is now returned in the incorrect format.

When creating a Log Analytics Solution in the location `eastus2` - the location returned from the API is `eus2`; as such we detect this as a drift (and since the location has changed we require that this resource is destroyed/recreated):

```
------- Stdout: -------
=== RUN   TestAccAzureRMLogAnalyticsSolution_basicContainerMonitoring
=== PAUSE TestAccAzureRMLogAnalyticsSolution_basicContainerMonitoring
=== CONT  TestAccAzureRMLogAnalyticsSolution_basicContainerMonitoring
--- FAIL: TestAccAzureRMLogAnalyticsSolution_basicContainerMonitoring (128.29s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: azurerm_log_analytics_solution.test
          location:              "eus2" => "eastus2" (forces new resource)
          plan.#:                "1" => "1"
          plan.0.name:           "ContainerInsights(acctestLAW-190417150453221002)" => "<computed>"
          plan.0.product:        "OMSGallery/ContainerInsights" => "OMSGallery/ContainerInsights"
          plan.0.publisher:      "Microsoft" => "Microsoft"
          resource_group_name:   "acctestRG-190417150453221002" => "acctestRG-190417150453221002"
          solution_name:         "ContainerInsights" => "ContainerInsights"
          workspace_name:        "acctestLAW-190417150453221002" => "acctestLAW-190417150453221002"
          workspace_resource_id: "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/acctestRG-190417150453221002/providers/Microsoft.OperationalInsights/workspaces/acctestLAW-190417150453221002" => "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/acctestrg-190417150453221002/providers/microsoft.operationalinsights/workspaces/acctestlaw-190417150453221002"  
```

It's worth saying that this appears to be region specific - since this test passes in `westeurope` - would it be possible for someone to take a look?

From our end this issue's been reported several times upstream so far:

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/3256
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/3201

Thanks!

**Comment by dsgouda** [comment]
@hyonholee can someone from Compute take a look?

**Comment by salameer** [comment]
Not Sure this is Compute, it's operational insights @mozehgir please assign to who ever is the contact from that team

**Comment by AntonChernysh** [comment]
I think Azure fixed this over last weekend: It works as expected now:
```List of available regions for the resource type is 'eastus,westeurope,southeastasia,australiasoutheast,westcentralus,japaneast,uksouth,centralindia,canadacentral,westus2,australiaeast,australiacentral,francecentral,koreacentral,northeurope,centralus,eastus2,eastasia,westus,southcentralus'```
No more "Short" locations for log analytics solution.

**Comment by shemers** [comment]
Hi @tombuildsstuff, 
this issue was resolved from Azure side, can you confirm that it does not recreates for you?

**Comment by tombuildsstuff** [comment]
Appears to be fixed from our side 👍
