### ISSUE TITLE
need a swagger for Azure Billing REST API

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-rest-api-specs#57]
Being that we spend many thousands of dollars on Azure each month, we are interested in producing custom reports of the usage. I would like to use the relatively new [Azure Billing REST API](https://msdn.microsoft.com/en-us/library/azure/mt218998.aspx) for this. I am looking for a Swagger definition of these APIs. I could probably help fill them out if the stubs get created in a git branch.

**Comment by anweiss** [comment]
+1

**Comment by devigned** [comment]
@Matt-Westphal could you comment on a timeline for creating a swagger representation of the commerce API?

**Comment by amarzavery** [comment]
Customers in node sdk have been requesting it as well https://github.com/Azure/azure-sdk-for-node/issues/1717

**Comment by lmazuel** [comment]
Hot topic in Python too, I received an email for this in December 2015.

**Comment by Matt-Westphal** [comment]
@moinak3 might have a better answer for this.

**Comment by amarzavery** [comment]
I have generated the swagger spec from the hyak spec in master branch and am currently reviewing it. So far the generated swagger spec looks good to me. If you want I can do a PR and everyone can review it. What does everyone think about it?

**Comment by Matt-Westphal** [comment]
Thanks Amar.
