### ISSUE TITLE
The operation NetworkInterfaces_ListVirtualMachineScaleSetVMNetworkInterfaces does not belong in the networking swagger...

### ISSUE THREAD

**Issue by johanste** [Azure/azure-rest-api-specs#570]
...because it actually is a path that belongs to the Microsoft.Compute namespace... and thus uses a different API version (unless, by accident, the current network spec API version happens to - accidentally - also be a valid/supported API version for the compute RP

This is currently not the case, and thus, the autorest generated client libraries are failing when calling public azure.

**Comment by liumichelle** [comment]
@DeepakRajendranMsft - closing this issue as it has already been discussed with Compute.

**Comment by johanste** [comment]
@liumichelle, please include the result of the discussion in the issue.

**Comment by markjbrown** [comment]
@DeepakRajendranMsft Can you provide the details from that discussion for @johanste here? thanks.

**Comment by DeepakRajendranMsft** [comment]
we have discussed this in length compute and sdk team. The correct fix would be too have the APIs in the compute swagger and the compute swagger should reference the network swagger for the reference of the nic. We deemed this too expensive and complex(to introduce a dependency on compute and network sdks) and decided to let it remain on the networking spec.

@johanste good to close?

**Comment by liumichelle** [comment]
@johanste / @salameer - is this issue good to close?

**Comment by johanste** [comment]
@DeepakRajendranMsft, I would disagree that the correct fix is for compute to reference the NIC model in networking, since the consequence of this would be to include the transitive closure of **all** resource types reachable from NIC (which, due to how NRP treats $expand, is pretty much all of networking). This is the root of the dependency that compute did not want to introduce, and it is something that I would recommend against. 

A better solution is to include only the reachable properties NIC in compute, especially since the schema for the NIC is tied to the API version of compute, not the API version of networking.

The problem with keeping things as they are now is that it is **extremely** fragile, and we have already seen regression introduced by incorrectly changes to API versions in the networking swagger representation due to the obscured dependency between NRP and CRP API versions.

**Comment by salameer** [comment]
Seems like there's more to it here

**Comment by johanste** [comment]
But, to be clear, the high order bit is to keep things working and not continue to regress. As long as that requirement is met, you are free to ignore my recommendations :).

**Comment by MikhailTryakhov** [comment]
fixed
