### ISSUE TITLE
how to get cpu memory utilization of allocation/usage details? also how to create multiple tenants who has access to create them?

### ISSUE THREAD

**Issue by madhut** [Azure/azure-rest-api-specs#5702]

**Comment by madhut** [comment]
Hi there ,
I'm searching for the rest API to get the CPU memory utilization of allocation/usage details. Can some one help me to get the rest API?. Also would like to know who has the access to create multiple tenants ?. 
Thanks.

**Comment by madhut** [comment]
Hi salameer,
Thanks for the response I appreciate it . But we are looking for the API's which can give us the allocated/currently using memory for the particular VM in azure. Also looking for is there any API can help us to find the infra memory of VM in azure?
Thanks,
Venkata

**Comment by shandilvarun** [comment]
you have enable guest memory metrics using extended metrics. Details here: https://docs.microsoft.com/en-us/azure/cost-management/azure-vm-extended-metrics

**Comment by madhut** [comment]
Than you Shandilvarun. Sure I will try it out.
-Venkata

**Comment by madhut** [comment]
Hi Shandilvarun,
I looked into the link : https://docs.microsoft.com/en-us/azure/cost-management/azure-vm-extended-metrics . But to "enable the extended metrics" options are not available in my azure portal. We tried to do it with powershell  also but no use. Now we are looking for another option to enable that. 
Please suggest if you have any.
Thanks,
Venkata.

**Comment by Drewm3** [comment]
Moving this over to the Azure Monitor group who owns the API for getting metrics from within the VM which includes memory.

**Comment by KevinBlasko** [comment]
Can you explain what you mean when you say that the options to enable extended metrics are not available in your azure portal?

You should be able to access these settings by navigating to the overview page for the Virtual machine in question, selecting "Diagnostic Settings" in the list of settings in the pane on the left (it will be under the "Monitoring" section), and then following the instructions in the doc under the "Enable guest-level monitoring on existing VMs" heading (https://docs.microsoft.com/en-us/azure/cost-management/azure-vm-extended-metrics#enable-guest-level-monitoring-on-existing-vms)

If you are unable to see this page, please open up a support ticket and reference this github issue along with screenshots showing the issue you are running into with the Portal.

**Comment by KevinBlasko** [comment]
Please reopen this issue when you have the information above or open a support ticket in Azure.
