### ISSUE TITLE
VM memory utilization of allocation/usage in Azure.

### ISSUE THREAD

**Issue by madhut** [Azure/azure-rest-api-specs#5703]
Hi there,
I'm trying to get the VM memory utilization of allocation/usage in azure through rest API. Can some one help me with this?
Thanks.

**Comment by salameer** [comment]
@Varuon can you kindly help out here or loop in whoever can help here?

**Comment by Drewm3** [comment]
@madhut, memory usage for a VM is available through the Azure Monitor APIs once you have enabled Azure Monitor for the VM. Please see the following link for details on using the Azure Monitor REST APIs: [https://docs.microsoft.com/en-us/azure/azure-monitor/platform/rest-api-walkthrough](url)
