### ISSUE TITLE
Documentation should provide a skeleton Swagger file

### ISSUE THREAD

**Issue by tbombach** [Azure/azure-rest-api-specs#571]
This would be used as part of the getting started process, so that a new spec author could have a starting point, rather than a blank file. This is not intended to replace "good patterns" examples, but rather a very basic outline that gets the ball rolling.

**Comment by tbombach** [comment]
Targeting having a PR for this by Monday morning

**Comment by kirthik** [comment]
We will be driving this from a different venue
