### ISSUE TITLE
Incomplete tenant/list spec at azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2018-06-01/subscriptions.json

### ISSUE THREAD

**Issue by iouri-s** [Azure/azure-rest-api-specs#5739]
The spec is incomplete for later versions as well.

Only two properties are listed:

 "TenantIdDescription": {
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "The fully qualified ID of the tenant. For example, /tenants/00000000-0000-0000-0000-000000000000."
        },
        "tenantId": {
          "readOnly": true,
          "type": "string",
          "description": "The tenant ID. For example, 00000000-0000-0000-0000-000000000000."
        }
      },
      "description": "Tenant Id information."
    },

More properties are returned. It would be nice to have them in the spec (especially displayName) and the SDKs.

{"value":[{"id":"/tenants/FF96f16e-aaea-4648-9fdf-8011ad807bee","tenantId":"FF96f16e-aaea-4648-9fdf-8011ad807bee","countryCode":"US","displayName":"xxxxx","domains":["xxxxx.onmicrosoft.com"]}]}

**Comment by anthony-c-martin** [comment]
Thanks for reporting this! I have published the missing definitions in https://github.com/Azure/azure-rest-api-specs/pull/8384.
