### ISSUE TITLE
[IoTHub] summary and description should not contain the same content

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#586]
IoTHub copy/paste the same content into "summary" and "description". This should not be the case, since this leads to bad documentation:
![252cb8ae](https://cloud.githubusercontent.com/assets/1050156/19167180/5eeb8656-8bbf-11e6-9608-5d1ac8ccbfe9.PNG)

**Comment by jlian** [comment]
In our next swagger version publish we will fix this. Please assign to me.

**Comment by jlian** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/4979397
