### ISSUE TITLE
Sites creation not working correctly

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-rest-api-specs#589]
Documentation to `sites` resources tells that properties like `alwaysOn`, `webSocketsEnabled` or `defaultDocuments` should be set on `properties` node of the `siteConfig` object. That's not working at all, but when I set those values directly on `siteConfig` it works correctly. Below you can find the correct document, and document generated by with correspondence with the documentation:

SDK:
```
{
	"location": "westeurope",
	"properties": {
		"name": "MY_SITE_NAME",
		"serverFarmId": "MY_FARM_ID",
		"clientAffinityEnabled":false,
		"siteConfig": {
			"location": "westeurope",
			"properties": {
			        "alwaysOn":true,
			        "webSocketsEnabled":true,
			        "defaultDocuments":["index.html"]
			}  
		}
	}
}
```
Working document:
```
{
	"location": "westeurope",
	"properties": {
		"name": "MY_SITE_NAME",
		"serverFarmId": "MY_FARM_ID",
		"clientAffinityEnabled":false,
		"siteConfig": {
			"location": "westeurope",
			"alwaysOn":true,
			"webSocketsEnabled":true,
			"defaultDocuments":["index.html"]
		}
	}
}
```

**Comment by amarzavery** [comment]
@jkubrynski - Those properties are getting flattened in the sdk. It is a convenience for the customer so he/she does not have to write properties.* all the time a property needs to be added/updated/accessed.

[This is the definition of the siteConfig object](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/swagger/service.json#L17865) which has nested _properties_.
On [this line](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2015-08-01/swagger/service.json#L18080) of the siteConfig definition we have an extension `"x-ms-client-flatten": true` that brings those nested properties one level up.

So there is nothing wrong in the sdk. If you follow intellisene, it should guide you to do the right thing.

**Comment by jianghaolu** [comment]
Thanks @amarzavery It's an SDK bug.
