### ISSUE TITLE
[EventsHub] CreateOrUpdate eventhub http response returns strings instead of ints

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#597]
Hello!
The Go SDK received an issue about CreateOrUpdate returning strings. Creating the eventhub looks like it is fine, the problem is just the response.

[Bug in the Event Hubs SDK](https://github.com/Azure/azure-sdk-for-go/issues/413)

Should the swagger define partitionIds like this:
```
"partitionIds": {
 "type": "array",
 "items": {
  "type": "string"
 },
 "description": "Current number of shards on the Event Hub."
},
```
instead of
```
"partitionIds": {
 "type": "array",
 "items": {
  "type": "integer"
  },
 "description": "Current number of shards on the Event Hub."
}
```

?
cc @sazeesha @jhendrixMSFT

**Comment by jtaubensee** [comment]
Can this be closed per #613?
