### ISSUE TITLE
Network: required property "nextHopType" is not defined in the model definition 

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#598]
"ExpressRouteCircuitRoutesTable":  and "RoutePropertiesFormat" has nextHopType as a required property, however, it is not defined in the model definition. I believe, nextHop is the nextHopType.
/cc @deepakrajendranmsft

**Comment by DeepakRajendranMsft** [comment]
@amarzavery when you say model, you mean swagger?

**Comment by Nilambari** [comment]
nextHopType/nextHop  is not required in ExpressRouteCircuitRoutesTable, so removed it.
RoutePropertiesFormat have defined nextHopType so its correct. Including this fix in PR :- https://github.com/Azure/azure-rest-api-specs/pull/639

**Comment by amarzavery** [comment]
@DeepakRajendranMsft - Both. The model definition in swagger is incorrect. Which translates to an in correct Model class in any AutoRest generated client.

**Comment by Nilambari** [comment]
I made fixes after discussing with Deepak offline.

**Comment by kirthik** [comment]
Closing since Pr is merged
