### ISSUE TITLE
Unable to create DevOps project from Azure Portal

### ISSUE THREAD

**Issue by SuhasMandumale** [Azure/azure-rest-api-specs#5984]
I am trying to create a DevOps project from [Azure Portal](portal.azure.com) but getting following errors, can anybody help me with this i was able to create DevOps project from same way yesterday and 2 days back but today i m getting these errors.

![image](https://user-images.githubusercontent.com/34735776/57842806-e2a49400-77ea-11e9-8be9-f220d5bd4e4a.png)

![image](https://user-images.githubusercontent.com/34735776/57842901-11226f00-77eb-11e9-9d7d-95a02c505746.png)

Short Error message as below
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"InternalServerError","message":"{\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The unknown resource response code 'Redirect' is encountered.\"\r\n }\r\n}"}]}`

Full error mesaage as below
`{ "id": "/subscriptions/{subscriptionID}/resourceGroups/VstsRG-suhasmandumale-b1ba/providers/Microsoft.Resources/deployments/Deploy_DevOps_Project_suhaspolymer/operations/051D9EC93851F0F5", "operationId": "051D9EC93851F0F5", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-05-16T08:31:06.5721934Z", "duration": "PT1.3201535S", "trackingId": "f05b29a6-d0c1-41a9-8592-a7be2df01294", "serviceRequestId": "e244bd84-b55b-4b45-8738-3b50a7fcde7b", "statusCode": "InternalServerError", "statusMessage": { "error": { "code": "ResourceDeploymentFailure", "message": "The unknown resource response code 'Redirect' is encountered." } }, "targetResource": { "id": "/subscriptions/{subscriptionID}/resourceGroups/VstsRG-suhasmandumale-b1ba/providers/microsoft.visualstudio/account/suhasmandumale", "resourceType": "microsoft.visualstudio/account", "resourceName": "suhasmandumale" }, "request": { "content": { "location": "South India", "properties": { "operationType": "Link", "accountName": "suhasmandumale", "ownerUpn": "" } } }, "response": { "content": "<html><head><title>Object moved</title></head><body>\r\n<h2>Object moved to <a href=\"https://app.vssps.visualstudio.com/_signin?realm={tokens}">here</a>.</h2>\r\n</body></html>\r\n" } }}`

**Comment by kpajdzik** [comment]
Hey @SuhasMandumale, this issue is not related to this repository but I'll try to reach out to Azure DevOps team.

**Comment by ericmattingly** [comment]
There was an incident in Azure DevOps today causing this.  It should work as expected now.  Sorry for the interruption!

You can find more information about it here - https://status.dev.azure.com/_event/120785657
