### ISSUE TITLE
[ServiceBus] type mismatch for PUT/GET networkRuleSet

### ISSUE THREAD

**Issue by j5lim** [Azure/azure-rest-api-specs#6012]
The path `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ServiceBus/namespaces/{namespaceName}/networkRuleSets/default` in the spec uses a plural name `networkRuleSets` but the actual name of the resource type created / returned from the RP is singular 'Microsoft.ServiceBus/Namespaces/**NetworkRuleSet**'.

The RP also accepts the request URI with the singular name `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ServiceBus/namespaces/{namespaceName}/networkRuleSet/default` but it is not spec'd. The spec should define the path so that any parties that depend on the spec can use.

**Comment by nemakam** [comment]
@v-Ajnava , could you please take a look at this one?

**Comment by v-Ajnava** [comment]
Hi @j5lim , thanks for reporting,  as per the Swagger guidelines resource types should be plural, I will talk with team and will update the thread.

**Comment by axisc** [comment]
This is setup due to swagger guidelines. Closing this issue.

@j5lim - thanks for raising this issue.
