### ISSUE TITLE
[EventHub] type mismatch for PUT/GET networkRuleSet

### ISSUE THREAD

**Issue by j5lim** [Azure/azure-rest-api-specs#6013]
The path `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/networkRuleSets/default` in the spec uses a plural name `networkRuleSets` but the actual name of the resource type created / returned from the RP is singular 'Microsoft.EventHub/Namespaces/**NetworkRuleSet**'.

The RP also accepts the request URI with the singular name `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/networkRuleSet/default` but it is not spec'd. The spec should define the path so that any parties that depend on the spec can use.

**Comment by jfggdl** [comment]
@j5lim, a fix has been released earlier today. I will close this issue for now. Thanks for bringing this bug to our attention.
