### ISSUE TITLE
Incorrect version in `arm-cdn/2016-10-02/swagger/cdn.json` spec

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#612]
It specified [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-cdn/2016-10-02/swagger/cdn.json#L4) as `2016-04-02` which is inconsistent with the file name.

BTW, you can add  this check to your CI scripts

**Comment by hovsepm** [comment]
Thanks @IvanGoncharov for catching it. but it is false alarm. Our workflow is that we first copy and merge existing swagger under new API version folder name, and them make changes on it in the second PR which may come in a couple of days. That way we can concentrate only on changes between old and new version. CDN spec with the version fix was merged today you can take a look now.

**Comment by IvanGoncharov** [comment]
@hovsepm Thank you for the quick response. I opened #624 to discuss your workflow.
