### ISSUE TITLE
Azure Machine Learning data plane APIs need x-ms-examples for all the operations

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#6167]
Reference PR https://github.com/Azure/azure-rest-api-specs/pull/5734
/cc @hendrytl @Greeshmamadalam

**Comment by v-strudm-msft** [comment]
We see this was posted over two years ago, but was never   addressed so are closing it. Our apologies. Should this still be an issue,  please re-open this issue and we will respond on a timely basis. Thank you.
