### ISSUE TITLE
Change workflow to keep 'master' branch in valid state(without version duplication)

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#624]
This issue is based on @hovsepm response from #612:

>  Our workflow is that we first copy and merge existing swagger under new API version folder name, and them make changes on it in the second PR which may come in a couple of days. That way we can concentrate only on changes between old and new version.

I totally get why you want to review only changes between versions.
But Idea behind Git & Github is that you keep your `master` branch in the valid state and use branches/PRs for development.

It especially important since developers outside Microsoft depend on this repo in their own projects.
For example, I aggregate your specs in my [directory of OAS specs](https://github.com/APIs-guru/openapi-directory) so when you commit APIs with the duplicating version it brakes my update scripts.

**Comment by kirthik** [comment]
Closing this issue since we are addressing it in a different way. @IvanGoncharov : We are working on cleaning up all swaggers to ensure they are of good quality.
