### ISSUE TITLE
ACS: expose the list all under a subscription

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-rest-api-specs#630]
API exist: https://msdn.microsoft.com/en-us/library/azure/mt703445.aspx 
We need to update the swagger doc

**Comment by brendandburns** [comment]
I believe this can now be closed, [list all is in the swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2017-01-31/swagger/containerService.json#L42)
