### ISSUE TITLE
Export deployment operations

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-rest-api-specs#6379]
We have a template export API, along with PowerShell and CLI that seem to call it.
https://docs.microsoft.com/en-us/rest/api/resources/deployments/exporttemplate
https://docs.microsoft.com/en-us/powershell/module/az.resources/export-azresourcegroup?view=azps-2.3.2
https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest#az-group-deployment-export

What RBAC operation allows this action? There are various resources/deployments/ operations but none that specifically say "export".
I'm looking here.
https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftresources

Thanks!

**Comment by zikalino** [comment]
Most likely it will be **Microsoft.Resources/deployments/read** but requires some further checking.

**Comment by zikalino** [comment]
closing as not much activity here...

**Comment by zikalino** [comment]
please reopen if you still need any more help

**Comment by dcbrown16** [comment]
@zikalino ok, I guess you meant that the further checking has to be done by us. Thank you.
