### ISSUE TITLE
Issue with EA and CSP pricing on Pricing Calculator

### ISSUE THREAD

**Issue by aquibqureshi26** [Azure/azure-rest-api-specs#6425]
Hi Team,

Thanks, This is regarding Azure Pricing Calculator. At the bottom there is a feature of calculating EA pricing But as i do have access to multiple subscription hence i cannot see scroll bar and submit button and this is a bug on Azure Pricing calculator Portal.

I have attached the screenshot below. This happens on any web browser be it Edge or Chrome. I have tried zooming in but it doesn't make any difference.

I've opened a premier support ticket for the same : 119062623000948 

Pricing calculator : https://azure.microsoft.com/en-in/pricing/calculator/

![pricingcalculator](https://user-images.githubusercontent.com/40310215/59999037-94eb3900-967e-11e9-9f83-274c6f588025.png)

**Comment by erich-wang** [comment]
@wilcobmsft, would you know anyone who could take care of this?

**Comment by aquibqureshi26** [comment]
Anyone from PG tried to repro this?

**Comment by erich-wang** [comment]
@aquibqureshi26 , the team is working on the fix, and I'll update here if any progress, thanks.

**Comment by erich-wang** [comment]
@aquibqureshi26 , the issue has been fixed per service team, please have a try.
