### ISSUE TITLE
Improvements/Fixes for ACR SDK

### ISSUE THREAD

**Issue by estebanreyl** [Azure/azure-rest-api-specs#6457]
We have been notified that some features are not currently supported/working as expected in the Azure Container Registries SDK for .NET generated from our provided swagger in particular :
```
1.	Pagination for getting repositories and tags is hard to use
2.	v2 manifest is not supported
3.	PUT manifest is not supported
```
Other API calls also require validation/testing.  This is a small issue tracker for this work item. Will update as more progress is done.

**Comment by graypj** [comment]
Adding more details：

1. Pagination is a response header and current swagger is not parsing in in responses.
```
Link: </v2/_catalog?last=azcopy&n=1&orderby=>; rel=\"next\"
```

2. `/v2/{name}/manifests/{reference}` only supports Get method with default header. Put and Delete method is not supported yet. Also `application/vnd.docker.distribution.manifest.v2+json` mediaType is required do get manifest in v2 schema.

3. Tag deletion is expecting 204 for success code but it's actually 202.

4. `/oauth2/exchange` is not supported

5. `/oauth2/token` is not supported.

**Comment by graypj** [comment]
> 3. Tag deletion is expecting 204 for success code but it's actually 202.

This is currently a blocking issue for us. It would be great if this can be prioritized.

**Comment by estebanreyl** [comment]
Will take a look at that immediately

**Comment by graypj** [comment]
That's what I found. I haven't tested other scenarios.

**Comment by estebanreyl** [comment]
To update. I have replicated issue 3. Also confirmed 202 is the only expected correct status. The same issue exists for patch which also relies on 204 but should be 201. We do have a more updated swagger that does include Put for /v2/{name}/manifests/{reference} and addresses these last couple of issues at https://github.com/estebanreyl/azure-rest-api-specs/commit/4f95280b8bc50ad503b002351c875bebbe5e52a2 . I am currently working on top of it to address the other concerns and validate the generation of the SDK. You can probably look forward to a lot of progress tomorrow as it took me some time to understand how this all worked. Nonetheless if the 202 issue was the blocking component we could build the sdk using autorest immediately before proceeding with getting everything upstream. @graypj How are you using the SDK, are you manually building it or using the preview nugget package ?

**Comment by graypj** [comment]
We are currently using the preview nugget package. Can that be updated as well when these features are added？

**Comment by estebanreyl** [comment]
Absolutely, Ill begin asking how this can be carried out.

**Comment by estebanreyl** [comment]
To update on the previous point it seems as soon as this goes through here we can quickly get the preview nugget package out. As an additional update, as of commit https://github.com/msyihchen/azure-rest-api-specs/commit/49992327f94dc3493f633093e898c8eb85872a1a I have at least in theory (Still working on testing to make sure everything is indeed running smoothly) implemented items 1,2,3 along with fixing other portions of the swagger that seem to be inconsistent with our api. Still need to do a lot of testing and oauth2 is pending. Will update as appropiate.

**Comment by michaeljqzq** [comment]
Added @erich-wang since it is .NET SDK related issue

**Comment by erich-wang** [comment]
Please refer to the [process](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md) (visible only to Microsoft employee) if you need to generate .net management SDK from swagger spec

**Comment by estebanreyl** [comment]
https://github.com/AzureCR/azure-rest-api-specs/tree/estebanreyl/dot_net_sdk Is now housing the most updated work in progress of this. Oauth2 paths have been added though the entire flow (As a result of Swagger 2 limitations) will be custom built in C# for that particular sdk. The same will have to be done for others generated from this swagger. Most paths have been verified to work. Still have to look at distinct versions of manifests though.

**Comment by estebanreyl** [comment]
To update as of https://github.com/AzureCR/azure-rest-api-specs/commit/5b84330110c43213160bc42f03fa82e95903be4e all discussed features have been implemented and tested. I will begin the process of making sure everything is up to standards as specified [here](https://github.com/Azure/adx-documentation-pr/blob/master/tools/tools.md) . Will hopefully get through that quickly and PR.
