### ISSUE TITLE
Microsoft.Portal swagger refers to non-existent API version

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#6466]
A swagger spec for Microsoft.Portal was recently added for api-version 2015-11-01-preview, but this version does not appear to be supported by the Resource Provider. As an example, using armclient:
```
C:\Users\antmarti>armclient get /subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/dashboards/providers/Microsoft.Portal/dashboards/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY?api-version=2015-11-01-preview
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'centralus' and API version '2015-11-01-preview' for type 'dashboards'. The supported api-versions are '2015-08-01-preview, 2019-01-01-preview, 2018-10-01-preview'. The supported locations are 'centralus, eastasia, southeastasia, eastus, eastus2, westus, westus2, northcentralus, southcentralus, westcentralus, northeurope, westeurope, japaneast, japanwest, brazilsouth, australiasoutheast, australiaeast, westindia, southindia, centralindia, canadacentral, canadaeast, uksouth, ukwest, koreacentral, koreasouth, francecentral, southafricanorth'."
  }
}
```

The pull request which added this version:
https://github.com/Azure/azure-rest-api-specs/pull/5811

**Comment by antmarti-microsoft** [comment]
@jjbfour FYI. I couldn't find your Microsoft alias on the original PR.

**Comment by antmarti-microsoft** [comment]
(re-opening - accidentally closed)

**Comment by jjbfour** [comment]
oops. Looks like I specified the wrong version. Let me update.

**Comment by ifeoluwaokunoren** [comment]
@jjbfour Also, there's no swagger for all of the versions your RP supports: 2015-08-01-preview, 2019-01-01-preview, 2018-10-01-preview. Can you please publish swagger for all of these versions?

**Comment by jjbfour** [comment]
yeah i'll add those api versions as well.

**Comment by antmarti-microsoft** [comment]
@jjbfour Any updates on this?

**Comment by jjbfour** [comment]
@antmarti-microsoft waiting on review: https://github.com/Azure/azure-rest-api-specs/pull/6470

**Comment by antmarti-microsoft** [comment]
Sorry, I missed that. I've signed off for ARM and added a few comments to the PR - please take a look when you get a chance.

**Comment by ifeoluwaokunoren** [comment]
@jjbfour thanks for making the changes !
I still dont see swagger for the other apiVersions your RP supports - 2019-01-01-preview, 2018-10-01-preview

**Comment by jjbfour** [comment]
I'm adding the 2019-01-01-preview version. PR: https://github.com/Azure/azure-rest-api-specs/pull/6643
The Hubs UX only lets you add one at a time. I'll add the other version once this gets completed.

**Comment by jjbfour** [comment]
@ifeoluwaokunoren sorry took so long here is the last one. PR: https://github.com/Azure/azure-rest-api-specs/pull/6825/files

**Comment by Juliehzl** [comment]
It looks things go well. @anthony-c-martin Please confirm if it works for you. If no problem, I will close this issue.

**Comment by ifeoluwaokunoren** [comment]
Thank you ! @jjbfour  btw, can you ping me on teams so I can have your actual msft alias.
