### ISSUE TITLE
[media] Storage should be required for "create"

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#647]
media has currently two operations "create" and "update", then it's possible to use two different objects `MediaServiceCreateParameters` and `MediaServiceUpdateParameters` in order to have `storage` required in `MediaServiceCreateParameters` ([as it is](https://msdn.microsoft.com/en-us/library/azure/mt750387.aspx)).

Currently, creating with only `location` (the only required parameter) leads to a confusing:
```
azure.mgmt.media.models.api_error.ApiErrorException: Operation returned an invalid status code 'Bad Request'
```

@amarzavery for guidance/opinion.

**Comment by akucer** [comment]
Just verified that this is no longer an issue. Storage is currently a required parameter. Closing issue out.
