### ISSUE TITLE
Allow api-version to be optional for ResourceManagementClient

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-rest-api-specs#65]
With the current client, there is no way for users to override api-version in a get resource call. For example, if I want to get a storage account using the latest api version supported by the RP (Microsoft.Storage), I can't do this

**Comment by olydis** [comment]
@vivsriaus Assuming you are talking about https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Resource/Microsoft.Azure.Management.ResourceManager/Generated/ResourcesOperationsExtensions.cs#L312, I think this got resolved since you posted this issue, correct? :-)
