### ISSUE TITLE
[HDInsight] - Always model as string for every enum definition

### ISSUE THREAD

**Issue by idear1203** [Azure/azure-rest-api-specs#6505]
The Swagger review board requires `modelAsString` for `x-ms-enum` is always true. We cannot fix this now because it will be a breaking change. This issue should be addressed in the next API version. For new enum definition, we should definitely obey the best practice.

**Comment by aim-for-better** [comment]
Internal issue, we will solve this issue in next api version.

**Comment by aim-for-better** [comment]
We are still tracking this one.

**Comment by aim-for-better** [comment]
We are still tracking this one.

**Comment by aim-for-better** [comment]
on going

**Comment by aim-for-better** [comment]
on going

**Comment by aim-for-better** [comment]
on going

**Comment by aim-for-better** [comment]
on going

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
fixing

**Comment by aim-for-better** [comment]
will fix this by the end of Sept

**Comment by aim-for-better** [comment]
code complete
