### ISSUE TITLE
[PublicIPPrefix]Missing loadBalancerFrontendIpConfiguration property in PublicIPPrefix swagger/go-sdk

### ISSUE THREAD

**Issue by xuto2** [Azure/azure-rest-api-specs#6506]
After I attach a public ip prefix to an Azure standard load balancer as the frontend ip configuration of an outbound rule, i can see the property "loadBalancerFrontendIpConfiguration" in the public ip prefix. Below is the arm url to get the public ip prefix and the content of the public ip prefix. However, I don't find this property even in the latest swagger(https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/publicIpPrefix.json).

The ask is introducing this attribute in the swagger and then in the go-sdk data model. We program in GO and we need this attribute to check if an existing public ip prefix is already attached to an Azure standard load balancer or not.

(https://management.azure.com/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourceGroups/MC_tonyxuRGEastUS2EUAP_slb_euap_vmss31_eastus2euap/providers/Microsoft.Network/publicIPPrefixes?api-version=2018-07-01)

{
      "name": "slb-outbound-prefix",
      "id": "/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourceGroups/MC_tonyxuRGEastUS2EUAP_slb_euap_vmss31_eastus2euap/providers/Microsoft.Network/publicIPPrefixes/slb-outbound-prefix",
      "etag": "W/\"9527169c-4c24-4c9d-8c58-e104d7dfa1fd\"",
      "type": "Microsoft.Network/publicIPPrefixes",
      "location": "eastus2euap",
      "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "76e00ae6-3265-4331-93ca-48879486105a",
        **"loadBalancerFrontendIpConfiguration": {
          "id": "/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourceGroups/MC_tonyxuRGEastUS2EUAP_slb_euap_vmss31_eastus2euap/providers/Microsoft.Network/loadBalancers/kubernetes/frontendIPConfigurations/77cf0b2e-e411-4803-9515-319a5d52d60b"
        },**
        "prefixLength": 29,
        "publicIPAddressVersion": "IPv4",
        "ipPrefix": "52.253.228.96/29",
        "ipTags": []
      },
      "sku": {
        "name": "Standard",
        "tier": "Regional"
      }
    }

**Comment by kpajdzik** [comment]
@MikhailTryakhov, @jhendrixMSFT Could you take a look?

**Comment by MikhailTryakhov** [comment]
@number213 please review as well

**Comment by number213** [comment]
Opened PR to add this porperty to the specs: https://github.com/Azure/azure-rest-api-specs/pull/6606

**Comment by number213** [comment]
Specs are fixed by https://github.com/Azure/azure-rest-api-specs/pull/6693
PR for Go SDK was opened: https://github.com/Azure/azure-sdk-for-go/pull/5318

**Comment by jhendrixMSFT** [comment]
Thanks for letting me know.  The fix will be released in Go this month.  Closing issue as it's been resolved.
CC @ArcturusZhang
