### ISSUE TITLE
Need to get supported locations list for a blob storage account before sending a request to create it. 

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-rest-api-specs#651]
When I create a blob storage account I don't know which locations are supported until I send a request and get the following exception: 
```
com.microsoft.azure.CloudException: 400 is not a valid polling status code: The account type is not supported in the specified location.
```
So, a customer have to walk through all the possible location before a supported one is found.

This is how Portal behaves:

![image](https://cloud.githubusercontent.com/assets/6579928/19902803/5f9b89ba-a029-11e6-860a-0261bba76f65.png)

It would be great to have something similar.

**Comment by rpohane** [comment]
In the updated Azure Portal, the dropdown list of locations on the Create Storage Account page now only displays those locations which are supported.

**Comment by zhusijia26** [comment]
Close the issue based on response above. Please reopen if there is still questions.
