### ISSUE TITLE
API Request:  Auto-Shutdown on VMS

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-rest-api-specs#6533]
@bernie-g commented on [Wed Jun 19 2019](https://github.com/Azure/azure-libraries-for-net/issues/707)

On the actual azure portal you can configure Auto Shutdown times for the VM, but I don't see any way to do this in the API. Is this even possible at all?

---

@praries880 commented on [Thu Jun 20 2019](https://github.com/Azure/azure-libraries-for-net/issues/707#issuecomment-503754507)

Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @yaohaizh 

---

@yaohaizh commented on [Tue Jul 02 2019](https://github.com/Azure/azure-libraries-for-net/issues/707#issuecomment-507584027)

The swagger spec doesn't have any spec about auto shutdown? @praries880, in this case, where can I direct this issue to?

**Comment by Drewm3** [comment]
Hi @yaohaizh, the automatic shutdown of VMs is a function of the Azure Dev/Test Labs service which has been extended to support VMs outside of the actual Dev/Test Labs service. You can configure this through the APIs or through an ARM template by using the template example shown  [https://docs.microsoft.com/en-us/azure/templates/microsoft.devtestlab/2018-09-15/schedules](here).

As a hint, if there is ever something that you see exposed in the portal, but you are not able to find the appropriate documentation then you can go through the portal and click on the "Download a template for automation" link at the bottom of the Create VM blade. This will give you the ARM template which exposes the specific resources that are going to be created. This template can then be used as examples for your own development.

**Comment by AmirKehtarian** [comment]
It looks like the link below is useful for automatically shutting down and start up VMS
https://learn.microsoft.com/en-us/rest/api/dtl/virtual-machines/list-applicable-schedules?tabs=HTTP
