### ISSUE TITLE
API Request: Add support for batch operations on VMs

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-rest-api-specs#6545]
Currently, there is no way to perform batch operations on VMs. In cases where a fleet of VMs need to be stopped/started, individual API calls must be made for each VM in the fleet--which is incredibly tedious. The compute RP should support batch operations for common tasks, such as starting, stopping, and getting the power status of multiple VMs.

This functionality is supported on other clouds and a consistent pain point for those trying to replicate logic written for AWS on Azure.

**Comment by mjconnection** [comment]
First, thank you for reaching out to the Microsoft team.  We identified your issue as a Virtual Machine feature request.  We don't have that feature, but we are interested in hearing more from you and others.  We have created a UserVoice idea here https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38117446-api-request-add-support-for-batch-operations-on-v  for you to provide more feedback and upvote this feature to become a high priority for our feature teams roadmap planning.
