### ISSUE TITLE
Storage ManagementPolicies reuses parameter definition with readonly flag from GET in PUT request 

### ISSUE THREAD

**Issue by stuartleeks** [Azure/azure-rest-api-specs#6549]
The API spec for storage ManagementPolicies has [GET](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L616) and [PUT](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L653) operations which share the same [parameter definition](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L2158).

The parameter definition marks the policy property as readonly which prevents Autorest generating code to serialise it on CreateOrUpdate calls which means that ManagementPolicies cannot be created/updated with the Azure Go SDK. This is also blocking adding support for creating/updating ManagementPolicies via Terraform.

**Comment by zfchen95** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/6551
@NelsonDaniel , I submitted a PR to fix. Please approve.

**Comment by stuartleeks** [comment]
Thanks @zfchen95  - is it possible to fix #6554 at the same time? :-)

**Comment by zfchen95** [comment]
@stuartleeks Updated in PR https://github.com/Azure/azure-rest-api-specs/pull/6551 (changed integer to float)

**Comment by stuartleeks** [comment]
Awesome - thanks @zfchen95 :-)

**Comment by blueww** [comment]
The fix PR is already merged, so the issue should be fixed.
