### ISSUE TITLE
Storage ManagementPolicies: Spec for DateAfterModification/DateAfterCreation specifies property as int but non-integer representation is returned from API call

### ISSUE THREAD

**Issue by stuartleeks** [Azure/azure-rest-api-specs#6554]
According to the API spec, the [DateAfterModification](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L2317) definition uses an `int` value for the `daysAfterModificationGreaterThan` property, but the representation that comes back in the response from the PUT request is `10.0` rather than `10` as seen in the snippet below.

As with #6549, this breaks any generated code (e.g. the Azure Go SDK) and anything upstream that wants to use those SDKs (e.g. the Terraform AzureRm provider)

```json
{"properties":{"policy":{"rules":[{"enabled":true,"name":"rule1","type":"Lifecycle","definition":{"actions":{"baseBlob":{"tierToCool":{"daysAfterModificationGreaterThan":10.0},"tierToArchive":{"daysAfterModificationGreaterThan":50.0},"delete":{"daysAfterModificationGreaterThan":100.0}}},"filters":{"blobTypes":["blockBlob"],"prefixMatch":["container1/prefix1"]}}}]},"lastModifiedTime":"2019-07-04T14:50:46.7171698Z"}}                                                                                          
```

**Comment by raych1** [comment]
> but the representation that comes back in the response from the PUT request is 10.0 rather than 10 as seen in the snippet below
Is the response you are talking about from SDK or from the API directly?

**Comment by stuartleeks** [comment]
That snippet is from the error message in the SDK which dumps out the raw API response

**Comment by blueww** [comment]
@huizlAzure 
Would you please help to look at the swagger issue for ManagementPolicies

**Comment by zfchen95** [comment]
Fix in PR https://github.com/Azure/azure-rest-api-specs/pull/6551/files

**Comment by raych1** [comment]
@stuartleeks , the fix was merged and can ;you verify and close if it's fixed?

**Comment by stuartleeks** [comment]
Thanks @zfchen95  and @raych1. Once the GO SDK has been re-generated I will be able to test whether the issue is fixed :-)

**Comment by raych1** [comment]
@stuartleeks , can you verify and close if this issue is fixed?

**Comment by raych1** [comment]
@stuartleeks, I'm closing this issue with inactivity. Feel free to re-open this issue if it's not resolved.
