### ISSUE TITLE
DeploymentOperationProperties - missing 'provisioningOperation' attribute

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-rest-api-specs#6573]
@hjhhh3000vitae

The provisioningOperation missed on DeploymentOperationProperties  yet can be found from REST responses. 
Related issue: https://github.com/Azure/azure-libraries-for-java/issues/772

**Comment by snaheth** [comment]
Hi @yaohaizh, this is no longer missing in [API Version: 2019-10-01](https://docs.microsoft.com/en-us/rest/api/resources/deploymentoperations/get#provisioningoperation).
