### ISSUE TITLE
Compute: `costs` values is not returned for ResourceSKU 

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-rest-api-specs#6574]
There is field defined in the swagger spec for sku's costs:  https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/skus.json, but can not find this values from the service return responses.
Related issue: 
https://github.com/Azure/azure-libraries-for-net/issues/718

**Comment by mjconnection** [comment]
Hey thanks for reporting this issue.  We are sending this to the correct team to do some additional research.

@hyonholee - Spoke to @Drewm3 and he will be looking into this issue.

**Comment by Drewm3** [comment]
This is by design. There are a set of standard SKU definitions in the swagger, but only though documented here for compute are supported today: [https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list]

**Comment by yaohaizh** [comment]
Just wonder should the swagger spec need change to reflect this design?

**Comment by qub1n** [comment]
I see different version in API:

2019-04-01
in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/skus.json

but 
2017-09-01 in https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list

Isn't this the root cause?

**Comment by qub1n** [comment]
> This is by design. There are a set of standard SKU definitions in the swagger, but only though documented here for compute are supported today: [https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list]

Why this desing?

azure-libraries-for-net team does not want to add support for Cost API without having it in swagger.
On the other hand it is by design that it is not in swagger?

So what is the correct approach to accessing the Costs?

**Comment by Drewm3** [comment]
The reason for the current design is the fact that there is not a commerce provided API to get the cost of a specific type of resource that is available consistently through all channels of Azure customers. For example there is an API that works for Azure customers who have signed up through the Azure Portal, but that API does not work for Azure customers who are paying through a mechanism called an Enterprise Agreement. Within Azure VMs we are willing to change this design if/when there is a consistent way for us to provide a reference which all customers can use to get the price of the VM size, but we are unable to provide multiple configuration details for the multiple different methods required to get the price of a resource today.

**Comment by qub1n** [comment]
ok, thanks for explaining.
