### ISSUE TITLE
GenericResource model missing properties

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#6584]
Properties such as `createdTime`, `changedTime` are missing from GenericResource model.
When listing GenericResources these property names can be specified in the Data query params.

**Comment by anthony-c-martin** [comment]
@anuchandy Do you mean the [GenericResourceFilter](https://github.com/Azure/azure-rest-api-specs/blob/71d8146c525fe565f2d6570e7c05de1423b8084c/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json#L4170-L4186) model?

**Comment by anuchandy** [comment]
@anthony-c-martin This model https://github.com/Azure/azure-rest-api-specs/blob/71d8146c525fe565f2d6570e7c05de1423b8084c/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json#L4733

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin This model
> 
> https://github.com/Azure/azure-rest-api-specs/blob/71d8146c525fe565f2d6570e7c05de1423b8084c/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json#L4733

Thanks for clarifying!

**Comment by anthony-c-martin** [comment]
Thanks for reporting this! I've added these properties in https://github.com/Azure/azure-rest-api-specs/pull/8420.
