### ISSUE TITLE
listChannelWithKeys should not allow PUT operations

### ISSUE THREAD

**Issue by rodrigorodriguez** [Azure/azure-rest-api-specs#6585]
The method subscriptions/${subscriptionId}/resourceGroups/${group}/providers/Microsoft.BotService/botServices/${botId}/channels/WebChatChannel should not accept PUT.  We had an error that would be elucidated if it had thrown an exception.

**Comment by rodrigorodriguez** [comment]
Cc: @arenasio @jramos-br.

**Comment by swagatmishra2007** [comment]
This has been fixed a while back and only Post is allowed now
