### ISSUE TITLE
convertToSinglePlacementGroup for VirtualMachineScaleSets inside Compute.json (2019-03-01) missing parameter

### ISSUE THREAD

**Issue by alanchen1910** [Azure/azure-rest-api-specs#6660]
The definition for convertToSinglePlacementGroup under VirtualMachineScaleSets inside Compute.json (2019-03-01) is missing ApiVersionParameter as a parameter

**Comment by Drewm3** [comment]
@avirishuv, please check to see if this is still an issue. This issue was opened last year, but was missed in triage for a long time. So it may have already been fixed.
