### ISSUE TITLE
Cost Management - wrong parameter for QueryFilter

### ISSUE THREAD

**Issue by logachev** [Azure/azure-rest-api-specs#6674]
swagger for cost management API contains an issue here:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-01-01/costmanagement.json#L1031

QueryFilter doesn't accept `dimension` value, it requires it to be `dimensions`. As a result, it is impossible to use generated SDKs.

(Probably there is also an issue with `tag` instead of `tags`)

**Comment by jochav** [comment]
We are working on updating the documentation. Thank you for bringing this up to us!

**Comment by jochav** [comment]
ETA for documentation update is Jan 2021.

**Comment by ramaganesan-rg** [comment]
hello. we will update the documentation in Jan. can you please let us know if we can go ahead to close this issue? 
You are welcome to reopen if you don't see the changes after Jan,
