### ISSUE TITLE
devops/build/source providers/get path contents doesn't work with provider tfsgit

### ISSUE THREAD

**Issue by KnicKnic** [Azure/azure-rest-api-specs#6688]
when calling `GET https://dev.azure.com/{organization}/{project}/_apis/sourceProviders/{providerName}/pathcontents?api-version=5.1-preview.1`
 doesn't work with provider tfsgit

Always I get an empty json array returned.

Documentation does not indicate that https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source%20providers/get%20path%20contents?view=azure-devops-rest-5.1 does not work with tfsgit

**Comment by nschonni** [comment]
Think the repo you're looking for it is https://github.com/MicrosoftDocs/vsts-rest-api-specs

**Comment by KnicKnic** [comment]
@nschonni  thanks, created https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/253 to track
