### ISSUE TITLE
Swagger Spec for Azure KeyVault is missing

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-rest-api-specs#67]
Need a swagger spec for KeyVault.

**Comment by devigned** [comment]
@herveyw thoughts?

**Comment by colemickens** [comment]
Ping

**Comment by herveyw** [comment]
Not before Chlorine.

**Comment by thenewwazoo** [comment]
Any chance of getting this soon?

**Comment by amarzavery** [comment]
@pomortaz is working on it. She should be able to provide an accurate time line.

**Comment by pomortaz** [comment]
Sorry @thenewwazoo. Key Vault is targeting to publish Swagger spec early Summer.

**Comment by bradygaster** [comment]
@pomortaz Have there been any updates on this spec's ETA? C+E Content is working with @devigned to make sure that not only the CLI & SDK experiences are excellent, but that our Azure reference content updates include Key Vault. Could you include me on any correspondence and update this issue as you learn more about the ETA for the spec? 

Thanks!

**Comment by colemickens** [comment]
Ping?

**Comment by pomortaz** [comment]
@bradygaster thanks for explaining the situation. I will let you know about the ETA when I learn more.
Can you explain how C+E content is planning to include Key Vault? Are there going to be a REST API documentation for Key Vault based on the swagger spec?

**Comment by colemickens** [comment]
The Swagger spec is needed because we auto-generate our client SDKs from the Swagger spec. For example `azure-sdk-for-go` lacks KeyVault support because there is no Swagger spec available.

**Comment by bradygaster** [comment]
@pomortaz just like @colemickens plans to do, content will be using the Swagger to generate reference documentation for the API. Then, we'll "add some stuff" (that I can't disclose at this time as we're still in design phase on a few items, but moving quickly) that will make it easy for customers to know how the individual SDKs will make calls to those endpoints, as well as demonstrate appropriate CLI calls to make use of the APIs.

**Comment by colemickens** [comment]
So, when are we expecting to get an ETA to write a Swagger spec for KeyVault? It's been nearly 7 months and the lack of this Swagger spec affects **every** SDK for Azure.

**Comment by colemickens** [comment]
CC: @johngossman

**Comment by herveyw** [comment]
@colemickens I think you already had the answer in this thread: early summer. The team is working on our SDK but Autorest has broken some of our API, Java appears to needs a new wrapper and we're adding "some stuff". There's little interest in foisting these breaking changes on our existing customers until that stuff is ready.

**Comment by colemickens** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json

**Comment by pomortaz** [comment]
Data-plane swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/keyvault/2015-06-01/swagger/keyvault.json
