### ISSUE TITLE
maps 2017-01-01-preview spec under stable folder

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#6700]
The API appears to be marked as a preview version, but is under the stable folder. Don't know if it actually affects any of the generation.

**Comment by zikalino** [comment]
@nschonni this won't really affect any generation as long as it's correctly referenced from readme.mf files, and the preview package is quite old already, so it really doesn't matter too much.
Of course it doesn't look good and is confusing, so if you want, pls go ahead and create a PR to clean it up. Then we can check if everything works correctly and I will merge it, just reference this issue from the PR.

**Comment by nschonni** [comment]
I would, but every time I've done those folder name type PRs, they get closed 😆 since I think they want them from the service owner (or an MS person)

**Comment by zikalino** [comment]
@nschonni then assign this to me, I will merge it ;-)
but honestly, I am not sure what's the story here.
it think it was never used to generate any package, for instance first Python release is here:

https://pypi.org/project/azure-mgmt-maps/0.1.0/

on 8th May 2018, so **package-2018-05** is the first tag that was released (for Python SDK).

So I think that file is completely obsolete....

**Comment by nschonni** [comment]
@zikalino the PR got closed without merging. Is the idea just to leave it as-is?
