### ISSUE TITLE
Updating Network Security Group with REST API does not honor ETag

### ISSUE THREAD

**Issue by cbrit** [Azure/azure-rest-api-specs#6789]
Hello,
I'm a little new to working with ETags but they way that I understand they work with storage services is that if you include the last known etag of a resource in the header of a PUT request, the resource will only be updated if the actual ETag matches. Correct? I assumed this same functionality would be available for other services.

I need this functionality for Network Security Groups because I will have multiple clients configuring access to a VM and I don't want them to overwrite each other.

Expected behavior: Including "ETag" in PUT request header (or even in the body) should cause an update to fail if the resource's ETag does not match.

Actual behavior: ETag is ignored and resource is updated no matter what.

Is this a feature that just has not been implemented for NSG yet?

Thank you!

**Comment by allegradomel** [comment]
@cbrit, thanks for your patience, working on updating you soon

**Comment by cbrit** [comment]
Thanks @allegradomel, it's not preventing me from doing anything.

**Comment by allegradomel** [comment]
@cbrit: I reviewed the ETag behavior again and I see where your confusion comes from. Storage services use ETags for concurrency but -to my knowledge- _this is not something that is ever specified explicitly by the user_. Please follow up with any questions you have!

**Comment by cbrit** [comment]
@allegradomel Yeah it's totally possible that I misunderstood their purpose. Seemed at the time like that would be useful to the user if they have multiple processes that may need to change a rule without collision and I couldn't tell from the docs if it was meant for my own usage. I'm ok with this being closed if it is not a feature that y'all want to implement.

Thank you!

**Comment by allegradomel** [comment]
Glad to help! 

#please-close
