### ISSUE TITLE
Sql ServerDnsAliases_Acquire missing schema for 200 response

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-rest-api-specs#6814]
In specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/serverDnsAliases.json
There is no schema defined in the spec for the 200 response, but there is in the example file specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/examples/ServerDnsAliasAcquire.json
I'm guessing it should be "#/definitions/ServerDnsAlias"

**Comment by ericshape** [comment]
@nschonni 
thanks for your feedback!
we have fixed this issue in https://github.com/Azure/azure-rest-api-specs/blob/56a09bdef2f81383fae1716f2539fffc626c9d4b/specification/sql/resource-manager/Microsoft.Sql/preview/2020-08-01-preview/ServerDnsAliases.json#L231-L287

if you have any questions about SQL DB, please add SQL tag in your question :)
