### ISSUE TITLE
Query_UsageByScope return type is incorrectly defined

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#6822]
About this operation:
https://github.com/Azure/azure-rest-api-specs/blob/d8e61eccaaa0f9ddeb95dfed0a6dcebe06dbbc3b/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-01-01/costmanagement.json#L153

The return type `QueryResult` does not represent the actual JSON payload. Example of JSON payload from a customer:
```json
{
	"id": "subscriptions/00000000-0000-0000-0000-0000000000/providers/Microsoft.CostManagement/query/0ba0616a-88fb-4b07-ba2b-c32fa43f73da",
	"name": "0ba0616a-88fb-4b07-ba2b-c32fa43f73da",
	"type": "Microsoft.CostManagement/query",
	"location": null,
	"sku": null,
	"eTag": null,
	"properties": {
		"nextLink": null,
		"columns": [{
			"name": "UsageDate",
			"type": "Number"
		}, {
			"name": "Currency",
			"type": "String"
		}],
		"rows": [
			[20190601, "USD"],
			[20190602, "USD"],
			[20190603, "USD"],
			[20190604, "USD"],
			[20190605, "USD"],
			[20190606, "USD"],
			[20190607, "USD"],
			[20190608, "USD"],
			[20190609, "USD"],
			[20190610, "USD"],
			[20190611, "USD"],
			[20190612, "USD"],
			[20190613, "USD"],
			[20190614, "USD"],
			[20190615, "USD"],
			[20190616, "USD"],
			[20190617, "USD"],
			[20190618, "USD"],
			[20190619, "USD"],
			[20190620, "USD"],
			[20190621, "USD"],
			[20190622, "USD"],
			[20190623, "USD"],
			[20190624, "USD"]
		]
	}
}
```

QueryResult does not match this definition. The Swagger indeed says that the root node is a `value` node of type `array`, which is incorrect. I believe this error was made to fit the `x-ms-pageable` extension, but actually this option is not appplicable here since the list is not at the root. Also, examples have been modified to fit the Swagger, and does not represent the truth of the server.

I would do in order to fix it:
- Fix all the examples to be the **actual** server output and don't touch them anymore
- Remove the x-ms-pageable extension
- Fix QueryResult to describe properly the server (i.e. until CI passes on the examples)

Side note: being that the JSON returned does not follow ARM guideline, I would strongly encourage to have qn QPI review with ARM team (but out of the scope of this issue).

**Comment by ms-premp** [comment]
@Imazuel this is fixed in the swagger. Hence closing this item.

**Comment by ramaganesan-rg** [comment]
Per Prem's comment, this issue has been fixed. please reopen if you see this issue still lingering.
