### ISSUE TITLE
[DocDB] question about required parameters

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#683]
Hi @dmakwana

I saw in the quickstart deployment of DocDB:
https://github.com/Azure/azure-quickstart-templates/blob/master/101-documentdb-account-create/azuredeploy.json

That neither 'consistency_policy' nor 'locations' are required. Using "Automation options" on the portal shows usage of 'locations', but not 'consistency_policy':

```json
       {
            "apiVersion": "2015-04-08",
            "kind": "GlobalDocumentDB",
            "type": "Microsoft.DocumentDb/databaseAccounts",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "properties": {
                "databaseAccountOfferType": "Standard",
                "locations": [
                    {
                        "id": "[concat(parameters('name'), '-', parameters('location'))]",
                        "failoverPriority": 0,
                        "locationName": "[parameters('locationName')]"
                    }
                ]
            }
        }
```

Could you confirm if these parameters are required as the Swagger says?

FYI @amarzavery

**Comment by dmakwana** [comment]
There is a default consistency policy and so it is not necessarily required. The "locations" parameter however is required. The quickstart deployments of DocumentDB all seem to be out of date. We have a slightly modified version to accommodate for geo-replication of the database. I will note down to make the changes in those quickstart templates. And I think we can go ahead and remove the required tag for "consistencyPolicy"

**Comment by lmazuel** [comment]
Thanks @dmakwana !
I added this in the open PR https://github.com/Azure/azure-rest-api-specs/pull/682

**Comment by lmazuel** [comment]
PR merged, close this one. Thanks!
