### ISSUE TITLE
Typo in filename 'apimmanagement.json'

### ISSUE THREAD

**Issue by IvanGoncharov** [Azure/azure-rest-api-specs#684]
[apimmanagement.json](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-apimanagement/2016-07-07/swagger/apimmanagement.json) has two `m`.

**Comment by IvanGoncharov** [comment]
It brakes my scripts, can you please fix it?

**Comment by IvanGoncharov** [comment]
Can you please fix this super simple issue?
It severely blocks my project.

**Comment by kirthik** [comment]
Closing this since File name is fixed.
