### ISSUE TITLE
[EventHub] Missing EventHub properties

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#687]
Hello!
The Go SDK received an [issue](https://github.com/Azure/azure-sdk-for-go/issues/446) about a missing property when creating an EventHub, [ArchiveDescription](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.eventhubdescription_properties.aspx). I also noticed there are some other missing properties, like `Authorization`,  `ExtensionData`, `IsReadOnly`, `Path`, and `UserMetadata`.

cc @sazeesha

**Comment by sazeesha** [comment]
ArchiveDescription is in the pipeline to be added to the Swagger, rest of the properties will be deprecated.

**Comment by tombuildsstuff** [comment]
👋 hey @sazeesha - is there any update on when this will be available?

**Comment by sazeesha** [comment]
@tombuildsstuff we will be taking this in January.

**Comment by tombuildsstuff** [comment]
@sazeesha oh cool that's great, thanks a lot :)

**Comment by tombuildsstuff** [comment]
👋 hey @sazeesha - is there any update available here? :)

**Comment by v-Ajnava** [comment]
@tombuildsstuff , ArchiveDescription now known as CaptureDescription is available.  hence closing the issue.
