### ISSUE TITLE
Add Json format check to CI

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-rest-api-specs#6873]
Thanks for input from @nschonni, more info https://github.com/Azure/azure-rest-api-specs/pull/6496

**Comment by nschonni** [comment]
@NullMDR just pulling the conversation back from https://github.com/Azure/azure-rest-api-specs/pull/7290#issuecomment-533971189
There are 2 ways I showed in the linked PR, but @erich-wang wasn't comfortable using Docker/Deb approaches

**Comment by NullMDR** [comment]
fixed by https://github.com/Azure/azure-rest-api-specs/pull/7637
