### ISSUE TITLE
[DocDB] "regenerate_key" fails on 202

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#696]
Hi @dmakwana

`regenerate_key` only declares a valid response HTTP code 200.
However, I received a 202 (and then with the current Swagger received an exception).

Could you check if this is the expected behavior?

Thanks!

**Comment by dmakwana** [comment]
@lmazuel thanks! 202 is the expected response, I've created a PR here: #697

**Comment by lmazuel** [comment]
PR merged, thanks!
