### ISSUE TITLE
Issue with Cognitive Services QnAMaker Swagger

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#7121]
As of September 4 2019, in the Cognitive Services [QnAMaker Swagger](https://github.com/Azure/azure-rest-api-specs/blob/d547b7794cad660fd3cceee790e407a4d534308c/specification/cognitiveservices/data-plane/QnAMaker/readme.md#runtime-release-40), this section is not correct. 

You cannot put batch without any tag. If you do, Autorest reads it by default and tries to generate both QnAMaker and QnaMakerruntime inside the same SDK. So, you will have 2 clients inside one SDK which is not what we want. 

If you want both QnAMaker and QnAMakerRuntime inside the same SDK, then add the ```stable/v4.0/QnAMakerRuntime.json``` file to ```release_4_0``` tag. If you want the runtime to be seperate, then let us know how you would like to release it. You can follow a similar model to LUIS runtime and release it as its own package.  

In either case, the swagger needs to be modified by the service team

**Comment by bingisbestest** [comment]
@sarangan12 We do want the default behavior. The main reason being that a lot of DTOs are shared. If they were separate sdks it would be very difficult for the user to use dtos with conflicting names.

**Comment by sarangan12** [comment]
@bingisbestest When you say you do not want the default behavior, I assume you mean "We do NOT want to release them as in the same SDK since they have conflicting names". Am I correct? 

If my interpretation is correct, would the statement "We would like to release them as seperate SDKs" be correct? If so, why don't you create another folder named QnAMaker Runtime and add the runtime swagger there. LUIS Runtime does that: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/LUIS 

With the current setup, the users do get conflicting names. But if you follow the LUIS runtime approach, users will be able to use both your SDKs without any conflicts.

**Comment by bingisbestest** [comment]
I said we do want the default behavior. Please take a look at my response.

**Comment by sarangan12** [comment]
The issue has been opened for the past 4 years. I checked the latest file. I do not see any issues. It seems that the file has been fixed. Also, the swagger itself has not been updated in the last 2 years. I am closing this. @xirzec FYI...
