### ISSUE TITLE
Breaking change in SQL Server Database Retention Policies create_or_update APIs

### ISSUE THREAD

**Issue by logachev** [Azure/azure-rest-api-specs#7122]
SQL Server APIs to create or update Retention Policies recently had a breaking change not reflected in swagger.

Before: When called PUT, returned an object with the created\updated policy details.

Current: Returned an object with an operation status

It breaks tools using these APIs because SDK still behaves the old way and expects the `BackupShortTermRetentionPolicy` object

**Comment by yungezz** [comment]
service team need update Swagger to align with service behavior. HI @logachev  could you pls share which version tag of API you're using?

**Comment by jeroenterheerdt** [comment]
@logachev since the last activity here is from end of September I am going ahead and close this issue. Please respond if you need more help.

**Comment by jeroenterheerdt** [comment]
@yungezz please close this issue.

**Comment by logachev** [comment]
@jeroenterheerdt Sorry for the late reponse.
It appeared an issue was on our side. Closing.
