### ISSUE TITLE
Async operations without `"x-ms-long-running-operation": true`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#7124]
[Original issue](https://github.com/Azure/azure-sdk-for-go/issues/5662)
In the [get](https://github.com/Azure/azure-rest-api-specs/blob/1cf40364e6a4456ad2f6360656864b1eed11cf0b/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-06-01/recoveryservicesbackup.json#L322), [create](https://github.com/Azure/azure-rest-api-specs/blob/1cf40364e6a4456ad2f6360656864b1eed11cf0b/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-06-01/recoveryservicesbackup.json#L362) and [delete](https://github.com/Azure/azure-rest-api-specs/blob/1cf40364e6a4456ad2f6360656864b1eed11cf0b/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-06-01/recoveryservicesbackup.json#L414) operation, the description says it is an async operation, but without property `"x-ms-long-running-operation": true`, in the generated SDK, these method will be treated as synchronous operation.
Also, the descriptions mentioned an API called `GetPolicyOperationResult`, which does not exist in any of swagger nor any part of the generated SDK.

**Comment by pvrk** [comment]
@pratimaupadhyay02 : Can you please take a look at this?

**Comment by pratimaupadhyay02** [comment]
The issue has been fixed in service side. Swagger update will be out in few weeks.

**Comment by pvrk** [comment]
@pratimaupadhyay02 : can you please update on the latest status?

**Comment by pratimaupadhyay02** [comment]
The fix is in an ongoing PR. This will be checked in by end of next week.

**Comment by mepand** [comment]
The fix has been released. Since there is no further action pending on the PG side, closing the issue.
