### ISSUE TITLE
[KeyVault - ARM] Use of required property permission that can be empty object?

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#713]
While creating a vault, I came across the scenario where the property of the model is required but can be empty. I am not sure it's right or wrong but wanted to understand why if complex object is required than none of it's sub objects are required. 

**Example**:

[permissions](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L290) is required inside the [AccessPolicyEntry](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L264) but permission doesn't have any property that is required in [permissions ](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L293) defintions. 

Due to this, SDKs always have to pass an empty object that containing nothing. Below is the example operation that is required to create vault as of today:

```
curl -X PUT -d '{"location":"West US","properties":{"tenantId":"<TENENT_ID>","sku":{"family":"A","name":"standard"},"accessPolicies":[{"tenantId":"<TENENT_ID>","objectId":"<TENENT_ID>","permissions":{}}]}}' -H "Content-Type:application/json" -H "user-agent:Azure-SDK-For-Ruby/0.6.0/" -H "Authorization: Bearer <OAUTH_TOKEN>" -H "accept-language: en-US" -H "x-ms-client-request-id: c28e3c54-7f0b-4545-9f06-490252287702" https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/keyvaulttest/providers/Microsoft.KeyVault/vaults/vault3453?api-version=2015-06-01
```

but from the client side the following should be the same:

```
curl -X PUT -d '{"location":"West US","properties":{"tenantId":"<TENENT_ID>","sku":{"family":"A","name":"standard"},"accessPolicies":[{"tenantId":"<TENENT_ID>","objectId":"<TENENT_ID>"}]}}' -H "Content-Type:application/json" -H "user-agent:Azure-SDK-For-Ruby/0.6.0/" -H "Authorization: Bearer <OAUTH_TOKEN>" -H "accept-language: en-US" -H "x-ms-client-request-id: c28e3c54-7f0b-4545-9f06-490252287702" https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/keyvaulttest/providers/Microsoft.KeyVault/vaults/vault3453?api-version=2015-06-01
```

The difference is client doesn't need to create empty object for _permission_ inside _AccessPolicyEntry_. So i'd like to understand the reason behind declaring permission as required without being really required theoretically. 

@pomortaz Could you please help us understand the reasons if any from the service perspectives? Thanks!

**Comment by pomortaz** [comment]
@vishrutshah the reason is that, logically at least one permission need to be set for secret, certificate or key from permission list for the vault to be usable. However, I could not force this logic in the swagger spec.

**Comment by vishrutshah** [comment]
@pomortaz I see that makes sense, you want OR conditions between keys, secrets and certificates. 

In that case shouldn't server return error when permission object is empty i.e. not setting any of keys, secrets or certificates? Because i am able to create vault and based on you response seems like that is logically unusable at all. That doesn't sound good either as if i am not mistaken, i am able to create a vault without any permission. 

Below example Curl Operation successfully create vault:
```
curl -X PUT -d '{"location":"West US","properties":{"tenantId":"<TENENT_ID>","sku":{"family":"A","name":"standard"},"accessPolicies":[{"tenantId":"<TENENT_ID>","objectId":"<TENENT_ID>","permissions":{}}]}}' -H "Content-Type:application/json" -H "user-agent:Azure-SDK-For-Ruby/0.6.0/" -H "Authorization: Bearer <OAUTH_TOKEN>" -H "accept-language: en-US" -H "x-ms-client-request-id: c28e3c54-7f0b-4545-9f06-490252287702" https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/keyvaulttest/providers/Microsoft.KeyVault/vaults/vault3453?api-version=2015-06-01
```
![vault](https://cloud.githubusercontent.com/assets/8782776/20198271/9cbdb60c-a758-11e6-807b-1f8383b00369.PNG)

Should this be the accepted behavior from server side?

Thanks!

**Comment by pomortaz** [comment]
Yes, from server side it is accepted to create a resource with no permission. However, if the permission is not set, then no key, secret or certificate operations could be executed. So your argument is valid.

**Comment by kirthik** [comment]
@vishrutshah - Please follow up with @pomortaz

**Comment by kirthik** [comment]
@vishrutshah - Could you please provide what the action item here is? If resolved, please close

**Comment by vishrutshah** [comment]
As there is not good way to model on swagger whether one of the three properties must exists, no action item can be taken on swagger from service team.
