### ISSUE TITLE
Microsoft.Web ListFunctions definition incorrect

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-rest-api-specs#7143]
Hi, 

I'm seeing an issue using the Golang SDK to retrieve Functions Secrets. This appears to track back to the swagger definition. 

The current definition for this function:

https://github.com/Azure/azure-rest-api-specs/blob/8a02736ee4e89d8115d4ed5d2001e8c8d78ca878/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json#L3105-L3110

https://github.com/Azure/azure-rest-api-specs/blob/8a02736ee4e89d8115d4ed5d2001e8c8d78ca878/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json#L18896-L18920

It' appears to be incorrect, it states that the returned `key` and `trigger_url` properties will be under a `properties` top level object but when talking to the API they aren't. See an example request below from the Golang SDK.

```json
2019/09/06 18:44:58 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/5774ad8f-d51e-4456-a72e-0447910568d3/resourceGroups/acctestRG-190906184259523442/providers/Microsoft.Web/sites/acctest-190906184259523442-func/functions/testfunc/listsecrets?api-version=2018-02-01: 
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Sep 2019 17:44:57 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=dcb710fa4b4f37e252a09aa7622aa6877443e01a6826dc6315d627d3e24938b7;Path=/;HttpOnly;Domain=acctest-190906184259523442-func.scm.azurewebsites.net
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding,Accept-Encoding
X-Aspnet-Version: 4.0.30319
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 6798cf5f-0f80-4edb-417a-795f39053598
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1195
X-Ms-Request-Id: 3ec9d873-52eb-40a3-b3cb-c757384b029c
X-Ms-Routing-Request-Id: UKWEST:20190906T174458Z:9c9e5933-e722-4a86-94de-6ddf9d4a0a80
X-Powered-By: ASP.NET
X-Powered-By: ASP.NET

Body:
{"key":"eL43nOMQie1Yd5somekeyhere0y5V2AqEX2tA==","trigger_url":"https://acctest-190906184259523442-func.azurewebsites.net/api/testfunc?code=eL43nOMQie1Yd5somekeyhereWrzS30y5V2AqEX2tA=="}
```

Because of this if you do a request like the following you are returned an object where all the properties are `nil`.

```golang
resp, err := webClient.AppServicesClient.ListFunctionSecrets(ctx, resourceGroup, name, functionName)
	if err != nil {
		if utils.ResponseWasNotFound(resp.Response) {
			return fmt.Errorf("Function %q was not found in Function App %q in Resource Group %q", functionName, name, resourceGroup)
		}

		return fmt.Errorf("Error retrieving Function %q (Resource Group %q): %s", name, resourceGroup, err)
	}
```

It's worth noting that it appears this mistake may have also been made on other calls but I haven't reviewed the whole definition just the calls I'm using.

**Comment by lawrencegripper** [comment]
I've attempted a change in PR #7155 to fix this one up - hope that's ok!

**Comment by yungezz** [comment]
hi @lawrencegripper is it ok to close the issue now since linked PR merged? Thanks.

**Comment by lawrencegripper** [comment]
Sure I'm not sure it resolved this issue but iirc it put new api's in that supersede these ones. Haven't tested them.
