### ISSUE TITLE
Investigate automation example validation error

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#7188]
Investigate and fix model validation error in the PR https://github.com/Azure/azure-rest-api-specs/pull/7180. Errors are [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=107719&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742).

@vrdmr assigned to you since you contributed to this spec in the past, feel free to assign right owner.

**Comment by andyw248** [comment]
"Build not found". From the PR it appears the only change was to remove a double word from a description string.
