### ISSUE TITLE
validatemoveresources

### ISSUE THREAD

**Issue by Bafff** [Azure/azure-rest-api-specs#7204]
In 
https://docs.microsoft.com/en-us/rest/api/resources/resources/validatemoveresources
![image](https://user-images.githubusercontent.com/26187677/64818323-77aa7480-d5b4-11e9-906c-c1c24619c788.png) says that there we need to fill in target subscription.

BUT this field is for source

**Comment by iamalexmang** [comment]
Kind reminder.

**Comment by ifeoluwaokunoren** [comment]
We actually did fix this in this PR: https://github.com/Azure/azure-rest-api-specs/pull/8524, but it got reverted. So I'd be following up to see why the change was reverted.

**Comment by ifeoluwaokunoren** [comment]
New PR to fix: https://github.com/Azure/azure-rest-api-specs/pull/14562

**Comment by ifeoluwaokunoren** [comment]
PR merged: https://github.com/Azure/azure-rest-api-specs/pull/14562
