### ISSUE TITLE
Default Rest Version must be updated in Storage Datalake Service

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#7214]
For Datalake Storage, in the service side the default value for xMsVersion (rest version/x-ms-version header) is set to a old value which does not support OAUTH. Since this field is only optional, the customer requests are failing. Please update the default rest version

**Comment by manishsat** [comment]
Any update on this?

**Comment by sarangan12** [comment]
This seems to be fixed with the latest regeneration. CLosing this issue
