### ISSUE TITLE
ARM violation, duplicate path in specification/resources/resource-manager/Microsoft.Solutions/preview/2016-09-01-preview/managedapplications.json

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-rest-api-specs#7228]
File:
`specification/resources/resource-manager/Microsoft.Solutions/preview/2016-09-01-preview/managedapplications.json`

Duplicate path:
```
/{applianceId}
/{applianceDefinitionId}
```

This would cause validation failure in CI.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=109572

Please take a look whether it could be fixed.

Reference, fixed in `specification/resources/resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json`
```
  "x-ms-paths": {
    "/{applicationDefinitionId}?disambiguation_dummy": {
```
But it might not be the same implementation in service.

**Comment by MSEvanhi** [comment]
Spoke to Weidong offline. This issue has been fixed with Weidong's suggestion in later versions of the SDK.
