### ISSUE TITLE
Please delete the search-v2-preview branch

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-rest-api-specs#726]
FYI @tbombach or anyone else who can help.

A while back I created a `search-v2-preview` branch in the upstream `azure-rest-api-specs` repo for my team's feature development. We're no longer using this branch, but my permissions to delete it seem to have been revoked.

Can one of the admins of this repo please delete the `search-v2-preview` branch?

Thanks!

**Comment by tbombach** [comment]
Redirecting to @fearthecowboy, since I'm no longer on the team

**Comment by amarzavery** [comment]
done

**Comment by brjohnstmsft** [comment]
Thanks!
