### ISSUE TITLE
how to  upload private or public certificate to one web app

### ISSUE THREAD

**Issue by test123114** [Azure/azure-rest-api-specs#7264]
According to my research,  we can use the[ rest api](https://docs.microsoft.com/en-us/rest/api/appservice/certificates/createorupdatel) to create certificate 

> PUT https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/certificates/{name}?api-version=2016-03-01

Can I use it to upload private and public certificate to one web app? If ok, how to do

**Comment by yungezz** [comment]
HI @test123114 is this helpful to you? https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-ssl

**Comment by test123114** [comment]
Ok. I will check it

**Comment by akning-ms** [comment]
Hi @test123114, Can we close it if you feel the link is helpful. thanks
