### ISSUE TITLE
Type mismatch in backup.JobSupportedAction

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#7268]
Despite the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/c383a94ea03a8364693023df2003f53c6127b7c8/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2017-07-01/bms.json#L1107) of `recoveryservicebackup` declared enum type `JobSupportedAction` as `string`, the value in the response returned from server is an integer.

[Related issue](https://github.com/Azure/azure-sdk-for-go/issues/5339)

**Comment by metrue** [comment]
Can anyone take a look, it's a big block issue.

**Comment by ArcturusZhang** [comment]
Hi @dheerendrarathor could you help about this?

**Comment by pvrk** [comment]
@TAdityaAnirudh : can you please take a look at this?

**Comment by ArcturusZhang** [comment]
Hi @TAdityaAnirudh is there any updates about this issue?
We have another customer [complaining](https://github.com/Azure/azure-sdk-for-go/issues/6543) about this now.

**Comment by pvrk** [comment]
Assigning this to @deymadhumanti

**Comment by pvrk** [comment]
We have realized that there might some breaking changes if we go ahead and implement the fix directly. Hence the plan is to provide the fix from a new API version onwards and the older API versions will continue to behave the same.

**Comment by mepand** [comment]
Fix has been checked in . ETA is 30th Jan

**Comment by adityabalaji-msft** [comment]
The fix is in progress and should be available by end of September

**Comment by adityabalaji-msft** [comment]
The fix is now available

**Comment by adityabalaji-msft** [comment]
Closing this issue for now as the fix has been deployed. Feel free to re-open in case you are still facing issues.
