### ISSUE TITLE
Determine the exact contents (columns) and location fo the lookup table for Spec versions

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-rest-api-specs#734]
### Description

Determine the pieces of data that should be captured and displayed about each spec, currently:

- spec name
- version
- Boolean fields for stability measurement
  - Completeness
  - Correctness
  - Compliance
  - Composition
  - API Stability
  - Link to latest Tag

**Comment by salameer** [comment]
Yeah I think this is looong Dead by now :)
