### ISSUE TITLE
Determien the format and mechanism for storing spec metadata

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-rest-api-specs#735]
### Description
By current plans, spec metadata will be stored as structured metadata associated with the latest release containign the spec version.  Need to verify the gitub APIs that would allow creating and reading releases.  If these do not pan out, the data could be stores:
- In a metadata file alongside the spec
- in swagger extensions inside the spec

Verifyu that the APIsthat would enable creatign and reading structured release comments exits, and decide on the precise format to eb sued

**Comment by salameer** [comment]
Closing Guys
