### ISSUE TITLE
ListBlobFlatSegmentResponse shouldn't include `delimiter`

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-rest-api-specs#7350]
https://github.com/Azure/azure-rest-api-specs/blob/ccf01ab1567a0ced8bd9d8de5d897e2cb1a03e0e/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-02-02/blob.json#L8257

/cc @XiaoningLiu

**Comment by Juliehzl** [comment]
@jasonyang-msft @xiaonlimsft Can one of you have a look at this issue?

**Comment by blueww** [comment]
@jeremymeng 

As the agreement, for all dataplane issues, please add "Client" label, or our monitor of storage SRP issues will raise false alarm.
Thanks!

**Comment by XiaoningLiu** [comment]
This can be resolved by removing this from swagger and re-generate, @jeremymeng if like to take this in preview.4 please go head update the swagger in this repo.

**Comment by jeremymeng** [comment]
Closing as it's fixed.
