### ISSUE TITLE
Document exact spec lifeccyle

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-rest-api-specs#736]
### Description
Write up the details of how the spec lifecycle is implemented
- For new specs
  - Who creates the topic branch
  - Who tags the branch once changes are checked in
  - Who updates the release metadata when an SDK or documentation drop is released
  - Who merges the topic branch when all criteria have been met
- For spec edits
  - Who creates the tag after a spec edit

**Comment by salameer** [comment]
Already done in the adx wiki
