### ISSUE TITLE
Setup a mechansim to tag one or two folks from the service team whenever there is a PR 

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-rest-api-specs#741]
- A github bot should assign folks from the service team to review PRs pertaining to the swagger spec for their service. This ensures that they have reviewed the PR. The reviewers should also make sure to look for breaking changes and add a breaking change label accordinly. If we can have a tool do this by comparing the changes then this would be awesome.

**Comment by kirthik** [comment]
@amarzavery : Do you want to keep this open?

**Comment by kirthik** [comment]
This is done
