### ISSUE TITLE
Calls to `/expressRouteCrossConnections` endpoint fail with 404

### ISSUE THREAD

**Issue by akki-s** [Azure/azure-rest-api-specs#7410]
As per the the documentation for [GET expressroutecrossconnections](https://docs.microsoft.com/en-us/rest/api/expressroute/expressroutecrossconnections/get) the supported version is `2019-07-01` but while trying the API I get the error - `The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-07-01'.` This error is for other operation as well such as List and PUT.

I've also tried the version `2019-08-01` and get the same error.

I can also reproduce this issue by going to azure resource explorer (resources.azure.com) at https://resources.azure.com/subscriptions/{subscriptionId}/providers and browsing to the node `providers->Microsoft.Network->expressRouteCrossConnections` and can see the error that complains with the similar but with a different API version - `The resource type could not be found in the namespace 'Microsoft.Network' for api version '2018-07-01'.`

I verified by executing the below `Powershell` command, and it looks like `expressRouteCrossConnections` is not available in `Microsoft.Network` provider. This looks like a bug to me whereby resource type is missing.

```ps
(Get-AzureRmResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes
```

**Comment by akki-s** [comment]
anyone looking into it?

**Comment by mialdrid** [comment]
Hey @akki-s 
The ExpressRoute cross connection resource/ARM Partner API sits behind a feature flag, that needs to be enabled on the subscription level. Your subscription needs to be enrolled in order to GET the cross connection resource.

**Comment by akki-s** [comment]
@mialdrid Thanks for the update. You have already mentioned the same and regarding other express route endpoints when we had a call. Thanks for the help.
