### ISSUE TITLE
Cognitive Services Specs are in Another Repo

### ISSUE THREAD

**Issue by devigned** [Azure/azure-rest-api-specs#743]
It would be great to get these specs pulled into this repo (https://github.com/MicrosoftTranslator/SwaggerFiles/issues/1).

**Comment by salameer** [comment]
@daniel-ms

**Comment by salameer** [comment]
Hi Daniel can you folks kindly look into this?

**Comment by felixwa** [comment]
@devigned, the link is dead, what exactly issue was?

**Comment by devigned** [comment]
@felixwa there were swagger files for the text translation service as well as others. The issue requested the specifications be added to https://github.com/azure/azure-rest-api-specs repo rather than residing in https://github.com/MicrosoftTranslator/SwaggerFiles. 

I ended up having to go to the documentation site for text translation, inspect the Dom for the page (as it was driven by swagger for the service), then download the swagger file for the service so that I could create a client in my language of choice.

This may no longer be the case.

If it is still the case, it would be great to commit these specs to a central repository.

**Comment by felixwa** [comment]
@devigned , https://github.com/MicrosoftTranslator/SwaggerFiles is still a 404 for me but I see what you meant. I will sync up with the teams to see if we should put all individual API swagger files into this repo.

**Comment by devigned** [comment]
@felixwa I expect there have been some movement of repositories in the MicrosoftTranslator GitHub org since the 116 days that have past since this was first posted. Trust me, it was there originally.

**Comment by salameer** [comment]
CLosing this, we have CS swagger in this repo now
