### ISSUE TITLE
The type of attribute tags for NetApp Account shouldn't be raw type interface{}

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#7447]
After checked it seems that the type of Tags from every other resource is map[string]*string, but currently the type of attribute tags for NetApp Account is type "interface{}", which is different then all the other resources and it adds unnecessary complexity (https://github.com/Azure/azure-sdk-for-go/blob/8c372e6e1243e0427dffb2d750099ee3ed161a44/services/netapp/mgmt/2019-06-01/netapp/models.go#L95). this is probably an error/issue with the swagger and API, right?
The type of attribute Tags from NetApp Acount Resource in repo "azure-sdk-for-go":
![image](https://user-images.githubusercontent.com/19754191/66532530-46d14700-eb42-11e9-8b43-9d8a9c4d8a00.png)
The type of attribute Tags from other resource like resource PrivateLinkService in repo "azure-sdk-for-go":
![image](https://user-images.githubusercontent.com/19754191/66532560-66686f80-eb42-11e9-9969-e67703d8bc7f.png)

And I found the type of attribute Tags for NetApp Account is also different than other resource like "network" in repo "Azure/azure-rest-api-specs".
The type of attribute Tags for NetApp Account in repo Azure/azure-rest-api-specs:
![image](https://user-images.githubusercontent.com/19754191/66534994-ad5a6300-eb4a-11e9-8895-571c5b346201.png)
The type of attribute Tags for other resource like "network" in repo Azure/azure-rest-api-specs:
![image](https://user-images.githubusercontent.com/19754191/66535027-ca8f3180-eb4a-11e9-948f-58a99976b4dc.png)

**Comment by leonardbf** [comment]
Should this be changed for each existing NetApp API, 2017-08-15, 2019-05-01, 2019-06-01 and the latest 2019-07-01? Does it also require a regeneration of SDK code for either each or latest? A new API 2019-08-01 is expected at the end of this month. Is it sufficient to go in there?

**Comment by ArcturusZhang** [comment]
> Should this be changed for each existing NetApp API, 2017-08-15, 2019-05-01, 2019-06-01 and the latest 2019-07-01? Does it also require a regeneration of SDK code for either each or latest? A new API 2019-08-01 is expected at the end of this month. Is it sufficient to go in there?

Since this is a breaking change to SDK (maybe for swagger too), I think it is best to have it changed in the next api version (2019-08-01), we are OK with that.

**Comment by leonardbf** [comment]
Ok, I will link this issue when I create the 2019-08-01 PR.

**Comment by neil-yechenwei** [comment]
> Ok, I will link this issue when I create the 2019-08-01 PR.

Thanks for your response quickly. Can we learn a rough ETA (deadline) when to onboard the fix?

**Comment by leonardbf** [comment]
The RP release associated with the 2019-08-01 API is planned for the beginning of November so I expect we will push this API version to github for review toward the end of October, perhaps late next week.

**Comment by akning-ms** [comment]
@leonardbf Seems this issue is fixed? if yes, can you help close this issue?

**Comment by leonardbf** [comment]
> @leonardbf Seems this issue is fixed? if yes, can you help close this issue?

@akning-ms I have unassigned myself from the ticket. It seems I do not have authorisation to close. And yes as mentioned above the issue should be resolved.

**Comment by neil-yechenwei** [comment]
thank you @leonardbf for the fix
