### ISSUE TITLE
role assignment api does not provide principal name and roledefination name

### ISSUE THREAD

**Issue by sangam-sgm** [Azure/azure-rest-api-specs#7460]
Hi
i am going to use azure rest api for one of my application but i found that there is difference in response which we get from cli and what is there in rest api. CLI provides prinicipal name and roledefinationName but noot in rest api. Is there somethig which ca be done to get the name also?

**Comment by weidongxu-microsoft** [comment]
@sangam-sgm 

Could you provide the REST API call and preferrable request/response? If possible please also provide the AZ CLI command that you are comparing. That would save me the time to guess which "role assignment api" you are calling.

**Comment by sangam-sgm** [comment]
Rest API call: GET **https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleAssignments?api-version=2015-07-01**

![image](https://user-images.githubusercontent.com/24355589/66626423-cf6ce780-ec15-11e9-8351-11ea66f40d96.png)


CLI: **az role assignment**
![image](https://user-images.githubusercontent.com/24355589/66626081-87999080-ec14-11e9-974a-c4eff4e56d0c.png)  **from  service principal account type (contributor role)**

![image](https://user-images.githubusercontent.com/24355589/66626286-51104580-ec15-11e9-91ce-e03ea590a107.png) **from user account (user role)**

please let me know if you want anything else

**Comment by weidongxu-microsoft** [comment]
@sangam-sgm 

You can run az with `--debug` to see the detail of what it calls.

The result from CLI is accomplished by multiple API calls.

First is roleAssignments call, which hae "roleDefinitionId" and "principalId".

Next is roleDefinitions call, from "id"="roleDefinitionId" one can get "roleName".

And finally graph API call to query the "pincipalId", to get "principalName".

**Comment by sangam-sgm** [comment]
Means a single CLI is composed of several apis.... Can not be made these into a single atleast the PrincipalName.... Because if we are using Rest API then we have to call managemet.azure.com and then graph api both with different permission and access token

**Comment by weidongxu-microsoft** [comment]
@sangam-sgm AFAIK you had to go through graph API for user principal name / service principal name.

@rlrossiter Do you know is there any other way to get principal name?

**Comment by rlrossiter** [comment]
@weidongxu-microsoft You are correct, the only way to get the principal name is by querying the Graph API

**Comment by yungezz** [comment]
hi @sangam-sgm is your question get answered?

**Comment by sangam-sgm** [comment]
yeah Thanks

**Comment by yungezz** [comment]
thanks, i'll close the issue then. pls create new issue if you have any furthur question.
