### ISSUE TITLE
MFA info in azure rest api

### ISSUE THREAD

**Issue by sangam-sgm** [Azure/azure-rest-api-specs#7461]
Is there any way or rest api by which we can get MFA info for Azure cloud services?

**Comment by maggiepint** [comment]
@mjconnection are you able to help here?

**Comment by sangam-sgm** [comment]
Any update on this issue???

**Comment by sangam-sgm** [comment]
Hi @mjconnection is there any solution or alternatives to get the info.

**Comment by Drewm3** [comment]
@sangam-sgm, could you provide more details on what "MFA info" you are looking for in the API? Generally the older ASM interfaces used management certs instead of anything supporting MFA for REST APIs.

**Comment by Drewm3** [comment]
Closing this due to no response.
