### ISSUE TITLE
Cannot set BackendIPConfigurations on ApplicationGateway

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-rest-api-specs#7475]
(Area: network management)

I created an ApplicationGateway through the portal.  I then wanted to add a BackendIPConfiguration to the BackendAddressPool.  I wrote the following code (pardon the hideous variable names, this was trying to prove to myself that the problem existed):

```
var nm = new NetworkManagementClient(credentials);
nm.SubscriptionId = credentials.DefaultSubscriptionId;

var a = nm.ApplicationGateways.GetAsync("itowlsonacs7", "k8s-aaging-test-ingress-1").Result;

var bep = a.BackendAddressPools[0];
if (bep.BackendIPConfigurations == null)
{
    bep.BackendIPConfigurations = new List<NetworkInterfaceIPConfigurationInner>();
    bep.BackendAddresses = null;
}
bep.BackendIPConfigurations.Add(new NetworkInterfaceIPConfigurationInner("/subscriptions/21dd4ed1-9ce5-4633-b202-a27b157920dc/resourceGroups/itowlsonacs7/providers/Microsoft.Network/networkInterfaces/k8s-agent-DB1C7F54-nic-0/ipConfigurations/ipconfig1"));

var after = nm.ApplicationGateways.BeginCreateOrUpdateAsync("itowlsonacs7", "k8s-aaging-test-ingress-1", a).Result;
```

The CreateOrUpdate was apparently accepted (no exception occurred), but the BackendIPConfiguration was _not_ set on the gateway, nor did the gateway go into updating state.

It's possible there's a bug in the above code, but I've seen a similar issue when creating gateways from code, where all gateway properties _except_ BackendIPConfigurations were set correctly.  So I suspect something is amiss in the library or in the networking Swagger spec.

I _can_ set BackendIPConfigurations via the portal, but looking at the network trace in dev tools, this seems to be performing an ARM batch update of both the gateway _and_ the NIC.  The application gateway SDK docs don't mention this as being required.

**Comment by surajmb** [comment]
@yaohaizh , if this is a documentation issue now, I've updated the script here to use NIC update. https://docs.microsoft.com/en-us/azure/application-gateway/quick-create-powershell#create-two-virtual-machines

We'll take up the work item to make it clear in the docs as well as in PS. Can this be closed if it is addressed?
