### ISSUE TITLE
[EventHubs] Consumer Groups API is wrong

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#753]
:wave:

I'm working with the EventHubs Consumer Groups API - with the intention of

When I do a PUT request - the response is
```
{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000resourceGroups/tharvey-ehdev4/providers/Microsoft.EventHub/namespaces/th-eh-dev4/eventhubs/th-eh-devtest4/consumergroups/th-eh-devcgtest4",
	"name": "th-eh-devcgtest4",
	"type": "Microsoft.EventHub/ConsumerGroups",
	"location": "North Europe",
	"tags": null,
	"properties": {
		"createdAt": "2016-11-22T12:12:19.9324273Z",
		"updatedAt": "2016-11-22T12:12:19.9324273Z",
		"userMetadata": "some-meta-data"
	}
}
```

When I retrieve this value via an HTTP GET - I get the following response
```
{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-ehdev4/providers/Microsoft.EventHub/namespaces/th-eh-dev4/eventhubs/th-eh-devtest4/consumergroups/th-eh-devcgtest4",
	"name": "th-eh-devcgtest4",
	"type": "Microsoft.EventHub/ConsumerGroups",
	"location": "North Europe",
	"tags": null,
	"properties": {
		"createdAt": "2016-11-22T12:12:18.8550968",
		"updatedAt": "2016-11-22T12:12:18.8550968",
		"userMetadata": "some-meta-data"
	}
}
```

Note the difference both of the `CreatedAt`/`UpdatedAt` fields - which are in the incorrect format.

I believe this is a bug in the server side - the result of which is that the date is being parsed back incorrectly at present

Thanks!

**Comment by mcardosos** [comment]
CC @sazeesha

**Comment by tombuildsstuff** [comment]
ping @sazeesha - is there an update here? :)

**Comment by salameer** [comment]
@sazeesha kindly follow up on these long overdue issues that are assigned to you

**Comment by tombuildsstuff** [comment]
ping @sazeesha - is there any update here?

**Comment by salameer** [comment]
@sazeesha kindly note that we will be escalating this issue

**Comment by jfggdl** [comment]
@v-ajnava was able to reproduce this problem. We are working to determine the potential differences in the implementation that may explain the difference in time and format.

**Comment by jfggdl** [comment]
@tombuildsstuff, when you are saying that "Note the difference both of the CreatedAt/UpdatedAt", are you referring to the DateTimeKind difference, the "Z" at the end (createdAt": "2016-11-22T12:12:19.9324273Z vs. createdAt": "2016-11-22T12:12:18.8550968) or the timestamp (seconds) difference, or both?

**Comment by jfggdl** [comment]
@tombuildsstuff We are going to close this issue, but please feel free to clarify the discrepancy on the response (question above) and we can reopen this issue.

**Comment by tombuildsstuff** [comment]
@jfggdl sorry, was on holiday.

> when you are saying that "Note the difference both of the CreatedAt/UpdatedAt", are you referring to the DateTimeKind difference, the "Z" at the end (createdAt": "2016-11-22T12:12:19.9324273Z vs. createdAt": "2016-11-22T12:12:18.8550968) or the timestamp (seconds) difference, or both?

In this instance I was referring to the format (`Z`) - I'd assume that all DateTime's returned in the API Response would be the same format (whichever that is)

Hope that helps!
