### ISSUE TITLE
[Network] Invalid swagger: Missing required definition property 'nextHopType' + unused definition "AzureAsyncOperationResult"

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#754]
Semantic validation on network.json spec 2016-09-01 results in invalid swagger:

   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'MISSING_REQUIRED_DEFINITION_PROPERTY',
            message: 'Definition requires property but it is not defined: **nextHopType**',
            path: 
             [ 'definitions',
               '**ExpressRouteCircuitRoutesTableSummary**',
               'required',
               '0' ] } ],
       failedValidation: true,
       warnings: 
        [ { code: '**UNUSED_DEFINITION**',
            message: 'Definition is defined but is not used: #/definitions/**AzureAsyncOperationResult**',
            path: [ 'definitions', 'AzureAsyncOperationResult' ] } ],
       code: 'INTERNAL_ERROR' } ] }

**Comment by amarzavery** [comment]
@Nilambari @deepakrajendranmsft - Can you guys take a look at this issue?

**Comment by Nilambari** [comment]
@dihan0604 Can you Please take a look at it? As Ding worked on this.

**Comment by veronicagg** [comment]
Also, api-version 2016-03-30 reports Duplicate API Path error as well:

azure-rest-api-specs/arm-network/2016-03-30/swagger/network.json should be valid Swagger

Errors
------
MISSING_REQUIRED_DEFINITION_PROPERTY : #/definitions/ExpressRouteCircuitRoutesTable/required/0 : Definition requires property but it is not defined: nextHopType
MISSING_REQUIRED_DEFINITION_PROPERTY : #/definitions/ExpressRouteCircuitRoutesTableSummary/required/0 : Definition requires property but it is not defined: nextHopType
**DUPLICATE_API_PATH :** #/paths//subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{virtualNetworkGatewayConnectionName}/sharedkey : API path (or equivalent) already defined: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{virtualNetworkGatewayConnectionName}/sharedkey

**Comment by jhendrixMSFT** [comment]
@dihan0604 have you had a chance to look at this?

**Comment by dihan0604** [comment]
This has been fixed, Link: https://github.com/Azure/azure-rest-api-specs/pull/855
