### ISSUE TITLE
'Next Steps' link in repository notes gives 404 error

### ISSUE THREAD

**Issue by raymondjstone** [Azure/azure-rest-api-specs#7557]
In repository docs

Next steps
The next step in the process after a spec is completed is to generate SDKs and API reference documentation. Go to the Azure Developer Experience guide for more information.

The link used is broken

**Comment by yungezz** [comment]
hi @raymondjstone could you pls share more info? which resource provider and which API? which version?

**Comment by ChenTanyi** [comment]
@yungezz could you please take a look at this issue?

**Comment by raymondjstone** [comment]
The repository on which the issue was raised, ie https://github.com/Azure/azure-rest-api-specs in the notes the section 'next steps' has a wrong link

**Comment by yungezz** [comment]
HI @raymondjstone the `next step` link is a private doc now which is for Microsoft employee only since it contains workflow and guideline for internal usage.  We can refine the wording in this repo to reflect that.

**Comment by yungezz** [comment]
hi @raymondjstone the `next step` link is fixed now. will close the issue then. Feel free to create new issue if found any other problem. thanks.
