### ISSUE TITLE
Network Watcher: availableProvidersList return InternalServerError

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-rest-api-specs#7579]
- Create network on region.

- REST calling from https://docs.microsoft.com/en-us/rest/api/network-watcher/networkwatchers/listavailableproviders
```REST
POST https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/javanwmrg99069/providers/Microsoft.Network/networkWatchers/nw52622/availableProvidersList?api-version=2019-08-01
```

- Result

```JSON
{
  "error": {
    "code": "InternalServerError",
    "message": "An error occurred.",
    "details": []
  }
}
```

**Comment by damendo** [comment]
Hi @yaohaizh can you file a support request and reference this comment so we can investigate this internally

**Comment by damendo** [comment]
#assign damendo

**Comment by damendo** [comment]
We have opened an internal investigation into this, expect to fix it by end of week.

**Comment by KarenHammons** [comment]
@damendo is this fix complete?

**Comment by irrogozh** [comment]
The problem was with Kusto data tables we used in this API. They were empty because MOI team migrated to another cluster. We were managed to start jobs to upload data into our cluster. But the code on the backend should be changed to reference correct data sets. After it's done, fix should be rolled out. Current estimate for this work (with roll out) is 4 weeks.

**Comment by damendo** [comment]
This API ([List Available Providers](https://docs.microsoft.com/en-us/rest/api/network-watcher/networkwatchers/listavailableproviders)) along with ([Get Azure Reachability Report](https://docs.microsoft.com/en-us/rest/api/network-watcher/networkwatchers/getazurereachabilityreport)) have been marked as Preview. 

Given preview status, low usage and competing projects; fixing issues related to either of these APIs is not a priority for us and we do not expect to close this out anytime soon.

**Comment by damendo** [comment]
#please-close
