### ISSUE TITLE
API version in rest api for resources

### ISSUE THREAD

**Issue by sangam-sgm** [Azure/azure-rest-api-specs#7596]
Hi,

I am hitting an api to get all available resource and after getting the all the resources iam again hitting  the id of each resources to get more info about all the resources available.
so for this i have to append again api version in each of the resource id to form valid api. But some of the resource fails with error message.
Is there any possibility to hit the api directly without api version which will be directly pointing to latest API.
API i am using - https://management.azure.com/subscriptions/{subscriptionId}/resources?api-version=2019-08-01 
after this lets say it returns id like:
**/subscriptions/{subscriptionId}/resourceGroups/{groupName}/providers/Microsoft.Compute/disks/xxxxx**

in this api how i ll know that which version will work.
Either the id should return with api version or to make version stable for each resource.
Please help me with this.
Thanks

**Comment by tim-nguyen-cs** [comment]
Hi @sangam-sgm - I understand your concern here, but all of Azure's REST API endpoints are versioned to resolve breaking changes and mitigate compatibility issues. If a breaking change is made, a new version of an API will be released - thus, an API version must explicitly be stated to determine user functionality.

If you're given a resource ID, for example, different API versions will return different results; thus, specify an API version that correlates with your desired use case. If the most stable version is specified by default, some requests may not work if, for example, additional query parameters are required or an endpoint is removed altogether.

Hope this helps, but definitely let me know if you have any other questions.
