### ISSUE TITLE
Can not get storage account access key

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#7597]
1. I post a creation of a server blob auditing policy as: 
https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{resourcegp}/providers/Microsoft.Sql/servers/{sqlServer}/auditingSettings/default?api-version=2017-03-01-preview

body:
{
	"properties": {
        "state": "Enabled",
        "storageAccountAccessKey": "XXXX",
        "storageEndpoint": "https://XX.blob.core.windows.net"
      }
}

get 202 Accepted

2. I get this server blob auditing policy as belows, the storage_account_access_key is empty if I get its attribute,should it be empty? Could I get storage_account_access_key?
 {
    "properties": {
        "state": "Enabled",
        "storageEndpoint": "XX",
        "retentionDays": 0,
        "auditActionsAndGroups": [
            "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",
            "FAILED_DATABASE_AUTHENTICATION_GROUP",
            "BATCH_COMPLETED_GROUP"
        ],
        "storageAccountSubscriptionId": "00000000-0000-0000-0000-000000000000",
        "isStorageSecondaryKeyInUse": false,
        "isAzureMonitorTargetEnabled": false
    },
    "id": "XX",
    "name": "Default",
    "type": "Microsoft.Sql/servers/auditingSettings"
}

**Comment by maggiepint** [comment]
Looks like this relates to the feature request linked in 2217, so I'm going to close this issue as tracked there. Definitely upvote if you are interested.
