### ISSUE TITLE
[Key Vault] For recover, tenantId and sku should not be required 

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-rest-api-specs#7621]
https://github.com/Azure/azure-rest-api-specs/blob/191aa6f4e91585f08acf453f47817a36f1db9c69/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2018-02-14/keyvault.json#L901-L904

When [`createMode`](https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/createorupdate#createmode) is `recover` (to recover a Key Vault), `tenantId` and `sku` should not be required. 

This works:
```
PUT https://management.azure.com/subscriptions/{}/resourceGroups/{}/providers/Microsoft.KeyVault/vaults/{}?api-version=2018-02-14

{
  "location": "southeastasia",
  "properties": {
    "createMode": "recover"
  }
}
```

**Comment by jlichwa** [comment]
@RandalliLama - Is that possible to define conditional required fields in swagger?

**Comment by RandalliLama** [comment]
@jlichwa I don't believe so.

**Comment by jlichwa** [comment]
@jiasli since it is shared operation, it does not seem it is possible to make it required only when create mode is "recover", remove it completely will fail for creation of new vault. Any suggestions?

**Comment by jlichwa** [comment]
Due to lack of conditional options in swagger, it is closed for now
