### ISSUE TITLE
How to suppress/avoid the "must have patch operation" message?

### ISSUE THREAD

**Issue by msfcolombo** [Azure/azure-rest-api-specs#7642]
This is about PR https://github.com/Azure/azure-rest-api-specs/pull/7631. I'm getting this error:

```
R3026 - TrackedResourcePatchOperation
Tracked resource 'PrivateEndpointConnection' must have patch operation that at least supports the update of tags. It's strongly recommended that the PATCH operation supports update of all mutable properties as well.

```

The private endpoint specification (MSFT internal) does not define PATCH operation for `PrivateEndpointConnection` resources. Is there a way to fix that error without doing the hack of re-defining resource properties?

By the way, the Azure Storage service is doing the same thing: https://github.com/Azure/azure-rest-api-specs/blob/68f5da55ba23770f8d7b698b1dea29934583b6cb/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L2627-L2641

How did they get away without having `PATCH` operation? Is this a new requirement?

**Comment by msfcolombo** [comment]
@schaabs FYI

**Comment by anuchandy** [comment]
@msfcolombo - swagger readme allows specifying suppressions e.g [here](https://github.com/Azure/azure-rest-api-specs/blob/7fe24f57e1d0e3560535be0730db43feb3239a36/specification/workloadmonitor/resource-manager/readme.md#tag-package-2018-08-31-preview). You will need to get sign-off from "Azure Resource Manager RP API Review" board for adding such ARM suppressions in readme.

**Comment by msfcolombo** [comment]
Ok, I have applied the suppression. Thanks @anuchandy, you can close this ticket.
