### ISSUE TITLE
Deployments / WhatIf API - Property change type "Delete" not accurate in results

### ISSUE THREAD

**Issue by inuvano-labs** [Azure/azure-rest-api-specs#7649]
As per https://docs.microsoft.com/en-us/rest/api/resources/deployments/whatif#propertychangetype the description for "Delete":

"The property exists in the current state and is missing from the desired state. It will be deleted when the deployment is executed."

However, this contradicts the behaviour observed in Azure Resource Manager templates and also the output from the /whatif API method returns properties marked as "Delete" that will not be deleted on execution.

Example:

On an ARM template defining a VM with basic properties for storageProfile:

`
... 
               "storageProfile": {
                    "imageReference": {
                        "publisher": "MicrosoftWindowsServer",
                        "offer": "WindowsServer",
                        "sku": "2016-Datacenter",
                        "version": "latest"
                    },
                    "osDisk": {
                        "createOption": "FromImage",
                        "managedDisk": {
                            "storageAccountType": "Standard_LRS"
                        }
                    },
                    "dataDisks": []
                }
...
`
Deltas returned:

`
...
                   {
                        "path": "properties.storageProfile.osDisk.caching",
                        "propertyChangeType": "Delete",
                        "before": "ReadWrite"
                    },
                    {
                        "path": "properties.storageProfile.osDisk.diskSizeGB",
                        "propertyChangeType": "Delete",
                        "before": 127
                    },
                    {
                        "path": "properties.storageProfile.osDisk.managedDisk.id",
                        "propertyChangeType": "Delete",
                        "before": "<ID-OF-MANAGED-DISK>"
                    }
...
`
I believe the "Delete" delta type should only be returned if the property has been explicitly set to "null" in the source template. If the property is omitted it should ignored.

Is this expected behaviour of the /whatif api?

**Comment by alex-frankel** [comment]
@inuvano-labs, can you share the original template? The What-If API is still in private preview so this noise is expected, but once I have the template, I will create an issue for it in the [What-If issues](https://aka.ms/whatifissues) so we can track it.

Once that is done this can be closed. If I don't hear back soon @rthorn17 we can close this.

**Comment by snaheth** [comment]
Closing due to no response. @inuvano-labs - Feel free to reopen it if you can share the template.
