### ISSUE TITLE
Network Watcher - Check Connectivity documentation

### ISSUE THREAD

**Issue by ViniciusSouza** [Azure/azure-rest-api-specs#7650]
During a project we (me and @Guilhermeslucas) identified the following issues:

- It's not clear to the documentation that we need to call the queue API and then check the job status
- The destination parameter for the connectivityCheck's body can accept Resource Id too, this is not clear too
- Add a specification for the operationResults' endpoint, there is not a single reference for this endpoint in the documentation and it is necessary to retrieve the connectivity check result. 
- Add a code example for ConnectivityCheck, any language to be used as a reference.
- When we try to post  another connectivity check using the same parameters as source and destination we have a RetryableError
- The Sample response provided is from a different endpoint OperationResult and not from connectivityCheck.

**Comment by damendo** [comment]
Thanks @ViniciusSouza for surfacing, those look like terrible errors in the docs. Will try to fix these soon.

**Comment by damendo** [comment]
Targeting end of month to make the changes

**Comment by damendo** [comment]
Resource ID is now mentioned. 
Examples exist and can be plugged into ARMClient, etc. 
The OperationResult endpoint is not owned by us but seems like a platform-wide method to get results of aysnc operations. Other issues seem intermittent.

**Comment by damendo** [comment]
#please-close
