### ISSUE TITLE
Sorting api response data

### ISSUE THREAD

**Issue by sangam-sgm** [Azure/azure-rest-api-specs#7668]
Can we sort the response of this api based on changedDate or CreateDate:

**GET https://management.azure.com/subscriptions/{subscriptionId}/resources?api-version=2019-08-01**
Just want to know if sorting of api response is possible through any optional parameter or not?
If yes then need help with the parameter name.

**Comment by ifeoluwaokunoren** [comment]
Thanks for submitting this request. We currently don't support sorting based on changedDate or CreateDate as we don't have index built on either changedDate or createDate. 
You can reply on this thread if you want us to add this feature request to our product backlog.
