### ISSUE TITLE
[Cognitive Services] Model validation fails with errors

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#767]
> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-cognitiveservices/swagger/cognitiveservices.json:
	> Operation: CognitiveServicesAccounts_GetProperties
		> example-in-spec
			> RESPONSE_BODY_VALIDATION_ERROR: Found errors in validating the example for response with statusCode "200" in operation "CognitiveServicesAccounts_GetProperties".
				> InnerErrors:
				  1. code: INVALID_TYPE
				     message: **Expected type object but found type string**
				     path: 
				     description: Cognitive Services Account is an Azure resource representing the provisioned account, its type, location and SKU.

Example in spec should be specified as json and not string.
From swagger:
```json
        "responses": {
          "200": {
            "description": "The resource provider should return 200 (OK) to indicate that the operation completed successfully.\nFor a detailed explanation of each field in the response body, please refer to the request body description in the PUT resource section. The only GET specific properties are “name,” “type” and “id.”\nField\tDescription\nKind\trequired.  String.\n\tThe API set for this API account. It can be \n\t· a single API, for example: Face API, Vision API, Speech API. \n\ta bundle of APIs:  Face + Speech, Vision + Emotion, etc.\nsku.name\tRequired.\n\tThe pricing tier/plan of this API. Could be: \n\tF0 - Free\n\tB0 - Basic\n\tS0 - Standard\n\tP0 - Premium\n",
            "schema": {
              "$ref": "#/definitions/CognitiveServicesAccount"
            },
            "examples": {
              "application/json": "{\n  “id”: “/subscriptions/{id}/resourceGroups/{group}/providers/{rpns}/{type}/{name}”,\n  “name”: “{name}”,\n  “type”: “Microsoft.CognitiveSerices/accounts”,\n  \"location\": \"North US\",\n  \"tags\": {\n    \"key1\": \"value 1\",\n    \"key2\": \"value 2\"\n   },\n  \"kind\" : \"resource kind\",\n   \"sku\": {\n\t    \"name\": \"sku code\"\n\t} \n  “etag”: “00000000-0000-0000-0000-000000000000”,\n  \"properties\": { }\n}"
            }
          },
```

	> Operation: CognitiveServicesAccounts_ListByResourceGroup
		> example-in-spec
			> INTERNAL_ERROR: An internal error occured while validating the example for response with statusCode "200" in operation "CognitiveServicesAccounts_ListByResourceGroup".
			> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the example for response with statusCode "200" in operation "CognitiveServicesAccounts_ListByResourceGroup".',
  innerErrors: [ [TypeError: obj must be an Array or an Object] ] }

Definition in swagger for response object only defines a value array, doesn't contain a next link, which is listed in the example from the spec.
Also example should be specified as a json object, not a string.

From swagger:

```json
        "responses": {
          "200": {
            "description": "The resource provider should return 200 (OK) to indicate that the operation completed successfully. For other errors (e.g. internal errors) use the appropriate HTTP error code.\nThe nextLink field is expected to point to the URL the client should use to fetch the next page (per server side paging). This matches the OData guidelines for paged responses here. If a resource provider does not support paging, it should return the same body (JSON object with “value” property) but omit nextLink entirely (or set to null, *not* empty string) for future compatibility.\nThe nextLink should be implemented using following query parameters:\n· skipToken: opaque token that allows the resource provider to skip resources already enumerated. This value is defined and returned by the RP after first request via nextLink.\n· top: the optional client query parameter which defines the maximum number of records to be returned by the server.\nImplementation details:\n· NextLink may include all the query parameters (specifically OData $filter) used by the client in the first query. \n· Server may return less records than requested with nextLink. Returning zero records with NextLink is an acceptable response. \nClients must fetch records until the nextLink is not returned back / null. Clients should never rely on number of returned records to determinate if pagination is completed.",
            "schema": {
              "$ref": "#/definitions/CognitiveServicesAccountListResult"
            },
            "examples": {
              "application/json": "{\n  “value”: [\n    {\n        “id”: “{url to resource 1}”,\n        “name”: “Name1”,\n        “type”: “Microsoft.CognitiveServices/accounts”,\n        \"location\": \"North US\"    \n        \"kind\" : \"resource kind\",\n        \"sku\": {\n\t        \"name\": \"sku code\"\n\t  }, \n        \"etag\": \"00000000-0000-0000-0000-000000000000\",\n        \"properties\": { }\n    },\n    {\n        “id”: “{url to resource 2}”,\n        “name”: “Name2”,\n        “type”: “Microsoft.CognitiveServices/accounts”,\n        \"location\": \"North US\",\n        \"kind\" : \"resource kind\",\n        \"sku\": {\n\t        \"name\": \"sku code\"\n\t  }, \n        \"etag\": \"00000000-0000-0000-0000-000000000000\",\n        \"properties\": { }\n    }\n  ],\n  “nextLink”: “{originalRequestUrl}?$skipToken={opaqueString}”\n}"
            }
          },
```

Swagger model definition:
```json
    "CognitiveServicesAccountListResult": {
      "properties": {
        "value": {
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "#/definitions/CognitiveServicesAccount"
          },
          "description": "Gets the list of Cognitive Services accounts and their properties."
        }
      },
      "description": "The list of cognitive services accounts operation response."
    },
```

**Comment by felixwa** [comment]
@kirthik, you can assign this to me.
@veronicagg, could you tell me what tool you were using to scan the swagger and got these errors? And could you give me some quick hints on how to fix it?

**Comment by felixwa** [comment]
@veronicagg , I guess you were using node cli.js validate-example? I get different set of errors though:

error: Found errors in validating the response with statusCode "200" for example in spec for operation "CognitiveServicesAccounts_GetProperties".:

{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for example in spec for operation "CognitiveServicesAccounts_GetProperties".',
  innerErrors:
   [ { code: 'INVALID_RESPONSE_BODY',
       errors:
        [ { code: 'INVALID_TYPE',
            params: [ 'object', 'string' ],
            message: 'Expected type object but found type string',
            path: [],
            description: 'Cognitive Services Account is an Azure resource representing the provisioned account, its type, location and SKU.' } ],
       message: 'Invalid body: Expected type object but found type string',
       path: [] } ] }

**Comment by veronicagg** [comment]
@felixwa errors may have changed a bit, since we're actively working on the tool, feel free to look at one of the latest: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/211069098#L1056

and linter validations: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/211069096#L3330 (you can search for cognitiveservice specs in the log to see all failures).

**Comment by veronicagg** [comment]
@felixwa I think in particular for this error: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/211069098#L1056 you'd want to turn the example in this line https://github.com/Azure/azure-rest-api-specs/blob/master/arm-cognitiveservices/2016-02-01-preview/swagger/cognitiveservices.json#L223  into an object instead of surrounding it with "" (which makes it be a string, see http://swagger.io/specification/#exampleObject)

**Comment by felixwa** [comment]
@veronicagg , this issue has been fixed with the new version (2017-04-18) of swagger file. Can you close this one or you need me to fix the old version too (2016-02-01-preview)?

**Comment by veronicagg** [comment]
@felixwa sounds good, thanks!
