### ISSUE TITLE
[Compute] Semantic validation fails with duplicate api path error

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#769]
compute.json swagger document is reported invalid due to duplicate api paths:

> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-compute-compute/swagger/compute.json:
	> Operation: AvailabilitySets_CreateOrUpdate
		> x-ms-examples
			> Scenario: TestOperationsPUT12
				> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the body parameter for example "TestOperationsPUT12" in operation "AvailabilitySets_CreateOrUpdate".',
  innerErrors: 
   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'DUPLICATE_API_PATH',
            message: 'API path (or equivalent) already defined: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets/{availabilitySetName}',
            path: 
             [ 'paths',
               '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets/{availabilitySetName}' ] },
          { code: 'DUPLICATE_API_PATH',
            message: 'API path (or equivalent) already defined: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}',
            path: 
             [ 'paths',
               '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}' ] } ],
       failedValidation: true,
       warnings: 
        [ { code: 'UNUSED_DEFINITION',
            message: 'Definition is defined but is not used: #/definitions/ApiError',
            path: [ 'definitions', 'ApiError' ] },
          { code: 'UNUSED_DEFINITION',
            message: 'Definition is defined but is not used: #/definitions/ComputeLongRunningOperationProperties',
            path: [ 'definitions', 'ComputeLongRunningOperationProperties' ] } ] } ] }

There are also 2 model definitions not being used #/definitions/ApiError, #/definitions/ComputeLongRunningOperationProperties.

**Comment by hyonholee** [comment]
Resolved: https://github.com/Azure/azure-rest-api-specs/pull/1238
