### ISSUE TITLE
Azure Policy Assignment Create\Delete operations return before finished

### ISSUE THREAD

**Issue by logachev** [Azure/azure-rest-api-specs#7691]
Azure Policy Assignment create and delete operations aren't marked as long-running operations but sometimes they return before the change is persisted.

As a result, if Policy Assignment Get operation is called right after create or delete, it return the wrong result (either Policy doesn't exist yet or still exists).

**Comment by weidongxu-microsoft** [comment]
@logachev

Is it this version you are referring to?
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/policyinsights/resource-manager/Microsoft.PolicyInsights/stable/2019-10-01/policyStates.json

**Comment by logachev** [comment]
@weidongxu-microsoft  I think so. I was using latest Python SDK to make calls.

**Comment by weidongxu-microsoft** [comment]
@logachev 
It seems to be this one instead https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-06-01/policyAssignments.json

If you are using Python SDK it might be better to directly raise issue in their repo https://github.com/Azure/azure-sdk-for-python (v2019_06_01 is the latest in Python SDK)
I could help move it if you wishes.

Also if you can estimate how frequent this happens, it would help us in reproducing the issue.

I am involving Python dev for triage.

@zikalino 
Hi Zim. Would you let some dev take a look on this? Authorization/policy would be a commonly used service and I personally not expecting swagger be in wrong definition. Hence my guess is either Python SDK got a bug or service itself got a bug.

**Comment by logachev** [comment]
I don't think this is an SDK issue.. SDK is not doing anything but making a REST call, right?

So with my understanding, the REST API returns success earlier than the actual state is updated.

It happens pretty frequently, I think I saw it ~30-40% of time.

I'll try to do it with Postman to exclude SDK piece, but the scenario is really:

1. Create policy assignment
2. Get just created policy assignment -- this one is failing frequently.. Works if there is a few seconds delay between steps 1 and 2

**Comment by logachev** [comment]
@weidongxu-microsoft I can confirm it has nothing to do with the SDK..
I can repro this with curl. Please insert your subscription id & token to the script.

It outputs only return codes.. Run it multiple times and you'll see 404 right after 201.
Sometimes GET returns 200 but DELETE returns 204 and the next GET returns 200.. So Delete operation didn't work.

```
export subscription=
export token=
export url="https://management.azure.com/subscriptions/${subscription}/providers/Microsoft.Authorization/policyAssignments/cctestpolicy_sub?api-version=2019-06-01"

curl -X PUT $url -H "Authorization: Bearer $token" -H "Content-Type: application/json" -d "{\"properties\":{\"displayName\":\"cctestpolicy_sub\",\"policyDefinitionId\":\"/providers/Microsoft.Authorization/policyDefinitions/404c3081-a854-4457-ae30-26a93ef643f9\",}}" -w "%{http_code}\n" -s -o /dev/null
curl -X GET $url -H "Authorization: Bearer $token" -w "%{http_code}\n" -s -o /dev/null
curl -X DELETE $url -H "Authorization: Bearer $token" -w "%{http_code}\n" -s -o /dev/null
curl -X GET $url -H "Authorization: Bearer $token" -w "%{http_code}\n" -s -o /dev/null

```

**Comment by weidongxu-microsoft** [comment]
@logachev Thanks for the sample call.

I just made a bash script (your curl cmd) with loop 20 and run it several times, but not able to produce (I am in WSL Debian 9, but that should matter much).

```
$ bash test.sh
iteration 1
201
200
200
404
iteration 2
201
200
200
404
iteration 3
201
200
200
404
iteration 4
201
200
200
404
iteration 5
201
200
200
404
iteration 6
201
200
200
404
iteration 7
201
200
200
404
iteration 8
201
200
200
404
iteration 9
201
200
200
404
iteration 10
201
200
200
404
iteration 11
201
200
200
404
iteration 12
201
200
200
404
iteration 13
201
200
200
404
iteration 14
201
200
200
404
iteration 15
201
200
200
404
iteration 16
201
200
200
404
iteration 17
201
200
200
404
iteration 18
201
200
200
404
iteration 19
201
200
200
404
iteration 20
201
200
200
404
```

**Comment by logachev** [comment]
Can you try to run it more? I was using Ubuntu WSL, but it shouldn't matter.

It doesn't happen as frequent as I said before, but it happens.
I saw a few options:

201 -> 404 -> 200 ->404
201 ->200 -> 204 -> 200

**Comment by kenieva** [comment]
After assessing this more closely by our team, this delay is an expect behavior due to Resource Manager and the replication between regions. We are working towards helping the delay, but we do expect a small delay either way. Thanks for the feedback.

**Comment by jongio** [comment]
@kenieva - If we expect a delay, then shouldn't this be marked as a long-running operation and supported as such?

**Comment by kenieva** [comment]
We are working with the ARM team on that.
