### ISSUE TITLE
[DataLake-Account] Semantic validation fails with Duplicate API paths

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#771]
arm-datalake-account contains duplicate API paths as indicated below:
> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-datalake-account/swagger/account.json:
	> Operation: StorageAccounts_Get
		> x-ms-examples
			> Scenario: CreateGetUpdateDeleteTestGET149
				> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the response with statusCode "200" for example "CreateGetUpdateDeleteTestGET149" in operation "StorageAccounts_Get".',
  innerErrors: 
   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'DUPLICATE_API_PATH',
            message: 'API path (or equivalent) already defined: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeAnalytics/accounts/{name}',
            path: 
             [ 'paths',
               '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeAnalytics/accounts/{name}' ] } ],
       failedValidation: true,
       warnings: 
        [ { code: 'UNUSED_DEFINITION',
            message: 'Definition is defined but is not used: #/definitions/CreateStorageAccountInfo',
            path: [ 'definitions', 'CreateStorageAccountInfo' ] },
          { code: 'UNUSED_DEFINITION',
            message: 'Definition is defined but is not used: #/definitions/Error',
            path: [ 'definitions', 'Error' ] } ],
       code: 'INTERNAL_ERROR' } ] }

There's also 2 model definitions not being used.

**Comment by begoldsm** [comment]
fixed in pr: https://github.com/Azure/azure-rest-api-specs/pull/764
