### ISSUE TITLE
[DataLake-catalog] Model validation fails with errors

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#774]
> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-datalake-catalog/swagger/catalog.json:
	> Operation: Catalog_CreateSecret
		> x-ms-examples
			> Scenario: SecretAndCredentialCRUDTestPUT134
				> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the response with statusCode "200" for example "SecretAndCredentialCRUDTestPUT134" in operation "Catalog_CreateSecret".',
  innerErrors: [ { [TypeError: obj must be an Array or an Object] code: 'INTERNAL_ERROR' } ] }

Model from swagger:
```json
        "responses": {
          "200": {
            "description": "Successfully created the specified secret in the specified database.",
            "schema": {
              "$ref": "#/definitions/USqlSecret"
            }
          }
        },
```
Example:
```json
{
  "parameters": {
    "databaseName": "testdb11293",
    "secretName": "testsecret12087",
    "api-version": "2016-11-01",
    "expanded": "true",
    "parameters": {
      "password": "testsecretpwd16470",
      "uri": "https://adlasecrettest.contoso.com:443"
    }
  },
  "responses": {
    "200": {
      "body": ""
    }
  }
}
```

**Comment by lmazuel** [comment]
@begoldsm ?

**Comment by begoldsm** [comment]
@veronicagg see PR: #764
