### ISSUE TITLE
[Datalake Store - account] Semantic validation failed with duplicate api path

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#775]
> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-datalake-store-account/swagger/account.json:
	> Operation: FirewallRules_CreateOrUpdate
		> x-ms-examples
			> Scenario: FirewallAndTrustedProviderTestPUT119
				> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the body parameter for example "FirewallAndTrustedProviderTestPUT119" in operation "FirewallRules_CreateOrUpdate".',
  innerErrors: 
   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'DUPLICATE_API_PATH',
            message: 'API path (or equivalent) already defined: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeStore/accounts/{accountName}',
            path: 
             [ 'paths',
               '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeStore/accounts/{accountName}' ] } ],
       failedValidation: true,
       warnings: 
        [ { code: 'UNUSED_DEFINITION',
            message: 'Definition is defined but is not used: #/definitions/Error',
            path: [ 'definitions', 'Error' ] } ] } ] }

There's also an unused model definition.

**Comment by begoldsm** [comment]
@veronicagg see PR: https://github.com/Azure/azure-rest-api-specs/pull/764 to fix the unused model. For the duplicate path error I am not seeing any duplicate paths with that name in the latest version of the spec (2016-11-01)

**Comment by veronicagg** [comment]
Thanks @begoldsm . Regarding the duplicate path error, here are the 2 that look to be duplicates:

- "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeStore/accounts/{name}"

- "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataLakeStore/accounts/{accountName}"

Could the operations under each be all under one of the paths? is there an actual distinction between {name} and {accountName} ?

**Comment by begoldsm** [comment]
oh good catch! No there is no difference, delete just somehow ended up under its own. This is now fixed.

**Comment by salameer** [comment]
Hello @begoldsm and @veronicagg does that mean this ticket should be resolved, is there a PR associated with your fix to the duplication @begoldsm?

**Comment by veronicagg** [comment]
yes, PR https://github.com/Azure/azure-rest-api-specs/pull/764 resolved the issue.
