### ISSUE TITLE
[GraphRBAC] Semantic validation fails with Duplicate API path

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#776]
> Validating "examples" and "x-ms-examples" in /Users/Veronica/github/openapi-validation-tools/arm-graphrbac/swagger/graphrbac.json:
	> Operation: Applications_Create
		> x-ms-examples
			> Scenario: CRUDApplicationTestPOST21
				> { code: 'INTERNAL_ERROR',
  message: 'An internal error occured while validating the body parameter for example "CRUDApplicationTestPOST21" in operation "Applications_Create".',
  innerErrors: 
   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'DUPLICATE_API_PATH',
            message: 'API path (or equivalent) already defined: /{tenantID}/groups/{objectId}',
            path: [ 'paths', '/{tenantID}/groups/{objectId}' ] } ],
       failedValidation: true,
       warnings: [] } ] }

**Comment by veronicagg** [comment]
1.42-previewInternal also reports errors:
azure-rest-api-specs/arm-graphrbac/1.42-previewInternal/swagger/graphrbac.json

Errors
------
DUPLICATE_API_PATH : #/paths//{tenantID}/groups/{objectId} : API path (or equivalent) already defined: /{tenantID}/groups/{objectId}
DUPLICATE_API_PATH : #/paths//{tenantID}/users/{upnOrObjectId} : API path (or equivalent) already defined: /{tenantID}/users/{upnOrObjectId}

**Comment by salameer** [comment]
Closing this, let's address at a PR level as specs are being updated
