### ISSUE TITLE
[Intune] Semantic validation errors - missing require properties in response body

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#777]
Response body is missing required properties:

  innerErrors: 
   [ { [Error: The Swagger document(s) are invalid]
       errors: 
        [ { code: 'MISSING_REQUIRED_DEFINITION_PROPERTY',
            message: 'Definition requires property but it is not defined: platform',
            path: [ 'definitions', 'GroupProperties', 'required', '1' ] },
          { code: 'MISSING_REQUIRED_DEFINITION_PROPERTY',
            message: 'Definition requires property but it is not defined: userId',
            path: [ 'definitions', 'OperationResultProperties', 'required', '0' ] },
          { code: 'MISSING_REQUIRED_DEFINITION_PROPERTY',
            message: 'Definition requires property but it is not defined: platform',
            path: [ 'definitions', 'OperationResultProperties', 'required', '2' ] } ],

Model from Swagger:
```json
    "GroupProperties": {
      "required": [
        "friendlyName",
        "platform"
      ],
      "properties": {
        "friendlyName": {
          "type": "string"
        }
      }
    },
```

Example:
```json
{
  "parameters": {
    "hostName": "fef.msua06",
    "policyName": "75a94659-9d84-4652-b61f-412a5ab0e9a9",
    "api-version": "2015-01-14-preview"
  },
  "responses": {
    "200": {
      "body": {
        "value": [
          {
            "id": "/providers/Microsoft.Intune/locations/fef.msua06/androidPolicies/75a94659-9d84-4652-b61f-412a5ab0e9a9/groups/43f17d38-5b3e-4f21-8867-ad5afccb0ea1",
            "name": "43f17d38-5b3e-4f21-8867-ad5afccb0ea1",
            "type": "Microsoft.Intune/locations/androidPolicies/groups",
            "properties": {
              "friendlyName": "AzureCLIGroup1"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by salameer** [comment]
Closing this, let's address at a PR level as specs are being updated
