### ISSUE TITLE
[Logic] Model validation fails with errors

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#778]
Model validation reports erros when validating responses against .net tests recordings for logic 2015-08-01 spec:
	> Operation: IntegrationAccountAgreements_List
		> x-ms-examples
			> Scenario: ListIntegrationAccountAgreementsGET115
				> InnerErrors:
				  3. code: ENUM_MISMATCH
				     message: No enum match for: EDIFACT
				     path: value,1,properties,agreementType

	> Operation: IntegrationAccountSchemas_CreateOrUpdate
		> x-ms-examples
			> Scenario: CreateAndDeleteIntegrationAccountSchemaPUT62
				> InnerErrors:
				  1. code: INVALID_TYPE
				     message: Expected type object but found type string
				     path: properties,metadata
				     description: The metadata.
				  2. code: INVALID_TYPE
				     message: Expected type object but found type string
				     path: properties,content
				     description: The content.

From swagger:
```json
    "AgreementType": {
      "type": "string",
      "enum": [
        "NotSpecified",
        "AS2",
        "X12",
        "Edifact"
      ],
      "x-ms-enum": {
        "name": "AgreementType",
        "modelAsString": false
      }
    },
```
```json
  "IntegrationAccountSchemaProperties": {
      "type": "object",
      "properties": {
        "schemaType": {
          "$ref": "#/definitions/SchemaType",
          "description": "The schema type."
        },
        "targetNamespace": {
          "type": "string",
          "description": "The target namespace."
        },
        "createdTime": {
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "description": "The created time."
        },
        "changedTime": {
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "description": "The changed time."
        },
        "content": {
          "type": "object",
          "description": "The content.",
          "properties": {}
        },
        "contentType": {
          "type": "string",
          "description": "The content type."
        },
        "contentLink": {
          "$ref": "#/definitions/IntegrationAccountContentLink",
          "readOnly": true,
          "description": "The content link."
        },
        "metadata": {
          "type": "object",
          "description": "The metadata.",
          "properties": {}
        }
      }
    },
```
Other models in the spec containing 'metadata' and 'content' show similar issue. 

	> Operation: Workflows_Validate
		> x-ms-examples
			> Scenario: ValidateWorkflowPOST203
				> InnerErrors:
				  1. code: INVALID_TYPE
				     message: Expected type object but found type string
				     path: properties,definition
Also for logic 2016 spec:
```json
        "definition": {
          "$ref": "#/definitions/Object",
          "description": "The definition."
        },
```

**Comment by pankajsn** [comment]
@kirthik already fixed

**Comment by kirthik** [comment]
@pankajsn - Could you please provide the commit id?

**Comment by salameer** [comment]
closing and if not fixed this would blocked at a PR level as specs are being updated
