### ISSUE TITLE
The hanaonazure spec doesn't define the "SapMonitorParameter" for "update" operation in hanaonazure.json

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#7789]
**The swagger json with problem:** 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hanaonazure/resource-manager/Microsoft.HanaOnAzure/preview/2017-11-03-preview/hanaonazure.json

**More details:**
In swagger json file, the update file has no properties parameter 'SapMonitorParameter' definition as create.
create:
"put": {
"tags": [
"HanaOnAzure"
],
"operationId": "SapMonitors_Create",
"x-ms-long-running-operation": true,
"summary": "Creates a SAP monitor.",
"description": "Creates a SAP monitor for the specified subscription, resource group, and resource name.",
"x-ms-examples": {
"Create a SAP Monitor": {
"$ref": "./examples/SapMonitors_Create.json"
}
},
"parameters": [
{
"$ref": "#/parameters/ApiVersionParameter"
},
{
"$ref": "#/parameters/SubscriptionIdParameter"
},
{
"$ref": "#/parameters/ResourceGroupNameParameter"
},
{
"$ref": "#/parameters/SapMonitorNameParameter"
},
{
"$ref": "#/parameters/SapMonitorParameter"
}
],

update:
"patch": {
"tags": [
"HanaOnAzure"
],
"operationId": "SapMonitors_Update",
"summary": "Patches the Tags field of a SAP monitor.",
"description": "Patches the Tags field of a SAP monitor for the specified subscription, resource group, and monitor name.",
"x-ms-examples": {
"Update Tags field of a SAP monitor": {
"$ref": "./examples/SapMonitors_PatchTags.json"
},
"Delete Tags field of a SAP monitor": {
"$ref": "./examples/SapMonitors_PatchTags_Delete.json"
}
},
"parameters": [
{
"$ref": "#/parameters/ApiVersionParameter"
},
{
"$ref": "#/parameters/SubscriptionIdParameter"
},
{
"$ref": "#/parameters/ResourceGroupNameParameter"
},
{
"$ref": "#/parameters/SapMonitorNameParameter"
},
{
"$ref": "#/parameters/TagsParameter"
}
],

**Comment by PakDLiu** [comment]
We are aware of this issue, our PATCH API only updates Tags right now.
We have a backlog item to enable updating different parts of the SapMonitor.

**Comment by maggiepint** [comment]
Going to close this as SAP team has it in backlog.
