### ISSUE TITLE
Where does the Event Schema goes in the Function App

### ISSUE THREAD

**Issue by acarlstein** [Azure/azure-rest-api-specs#7792]
Greetings, I apologize for asking here but I can't find where to do so.

We are creating a function app which connects to an Event Grid.
The documentation talks about an Event Schema (plus shows the JSON example); however, its missing the location in which such schema should be saved.

Does it goes into the package.json? Do we need to create a JSON file and put it there?
Do anyone knows? 

Thanks for helping out in advance.

**Comment by MyronFanQiu** [comment]
@acarlstein Hello. I will invite service team to answer the question.

**Comment by MyronFanQiu** [comment]
@hillaryc Could you help answer the questions?

**Comment by ahamad-MS** [comment]
Hello @acarlstein . Thanks for reaching out. It is unclear to me what documentation are you referring to. Can you please provide a link to the document to allow us to triage this better. And what error message or behavior are you seeing?

Also, if this is Event Grid Trigger function, then the function itself knows about this schema.

**Comment by ahamad-MS** [comment]
Hello @acarlstein . Thanks for reaching out. It is unclear to me what documentation are you referring to. Can you please provide a link to the document to allow us to triage this better. And what error message or behavior are you seeing?

Also, if this is Event Grid Trigger function, then the function itself knows about this schema.

**Comment by jfggdl** [comment]
acarlstein, We have not heard from you in a while. Please feel free to reply to us with your answers to the questions posted by ahamad-MS. In the meantime, I will be closing this issue, but if we see a response we can reopen it. Thanks.
