### ISSUE TITLE
[TrafficManager] types that can be possibly modeled as extendable eums

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#781]
The following types can be possibly modeled as extendable enums

1. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-trafficmanager/2015-11-01/swagger/trafficmanager.json#L551

```java
    public partial class EndpointMonitorStatus 
    {
        public static readonly EndpointMonitorStatus INACTIVE = new EndpointMonitorStatus("Inactive");
        public static readonly EndpointMonitorStatus DISABLED = new EndpointMonitorStatus("Disabled");
        public static readonly EndpointMonitorStatus ONLINE = new EndpointMonitorStatus("Online");
        public static readonly EndpointMonitorStatus DEGRADED = new EndpointMonitorStatus("Degraded");
        public static readonly EndpointMonitorStatus CHECKING_ENDPOINT = new EndpointMonitorStatus("CheckingEndpoint");
        public static readonly EndpointMonitorStatus STOPPED = new EndpointMonitorStatus("Stopped");
....
    }
```

2. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-trafficmanager/2015-11-01/swagger/trafficmanager.json#L573

```java
    public partial class EndpointType
    {
        public static readonly EndpointType AZURE = new EndpointType("Microsoft.Network/trafficManagerProfiles/azureEndpoints");
        public static readonly EndpointType EXTERNAL = new EndpointType("Microsoft.Network/trafficManagerProfiles/externalEndpoints");
        public static readonly EndpointType NESTED_PROFILE = new EndpointType("Microsoft.Network/trafficManagerProfiles/nestedEndpoints");
....
    }
```

3. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-trafficmanager/2015-11-01/swagger/trafficmanager.json#L617

```java
    public partial class ProfileMonitorStatus 
    {
        public static readonly ProfileMonitorStatus INACTIVE = new ProfileMonitorStatus("Inactive");
        public static readonly ProfileMonitorStatus DISABLED = new ProfileMonitorStatus("Disabled");
        public static readonly ProfileMonitorStatus ONLINE = new ProfileMonitorStatus("Online");
        public static readonly ProfileMonitorStatus DEGRADED = new ProfileMonitorStatus("Degraded");
        public static readonly ProfileMonitorStatus CHECKING_ENDPOINT = new ProfileMonitorStatus("CheckingEndpoint");
....
    }
```

**Comment by fearthecowboy** [comment]
Redirecting to original author: @ms-alguerra 

I believe that @anuchandy  is asking that you add an `enum` restriction and a `x-ms-enum` extension on those string fields:

``` json
"enum": [
  "Inactive",
  "Disabled",
  ...etc...
],
"x-ms-enum" : {
  "name": "EndpointMonitorStatus",
  "modelAsString": true
}

```

**Comment by liumichelle** [comment]
This would cause a breaking change - we will send this to the team to consider for future releases @dilukose

**Comment by salameer** [comment]
@liumichelle can you  put more info on where that request would  be tracked before closing this issue?

**Comment by vladca** [comment]
This is done, as a result of an unrelated swagger review: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-trafficmanager/2017-05-01/swagger/trafficmanager.json#L740; @anuchandy , can you confirm everything you wanted is in?

**Comment by veronicagg** [comment]
Looks good to me, EndpointMonitorStatus  and ProfileMonitorStatus. 
I don't see EndpointType  converted, but @anuchandy may confirm whether it's necessary. 
Thanks!

**Comment by anuchandy** [comment]
@veronicagg thank you, yes I can confirm that `EndpointMonitorStatus` and `ProfileMonitorStatus` has been converted to extendable enums as requested.

It looks like `EndpointType` cannot be expressed as an enum, mainly because the value on the wire is not same as the name we want to expose to user. 

| Name  | Value |
| ------------- | ------------- |
| AZURE  | Microsoft.Network/trafficManagerProfiles/azureEndpoints  |
| EXTERNAL  | Microsoft.Network/trafficManagerProfiles/externalEndpoints  |
| NESTED_PROFILE | Microsoft.Network/trafficManagerProfiles/nestedEndpoints  |

@veronicagg, just wanted to double-check, is the above assumption correct from open API perspective?

**Comment by veronicagg** [comment]
@anuchandy this may help in that case: https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-client-name

**Comment by anuchandy** [comment]
@veronicagg thanks, seems x-ms-client-name can be used when `property name` in the json payload is not user-friendly, so using this extension we can expose better name in SDK for the same json `property name`.

The issue with expressing `EndpointType` as enum is, there is no way to provide user friendly names for enum values which become `property values` in the json payload.

Looks like no action from service team, hence closing.
