### ISSUE TITLE
Azure Speaker API not working for Identification

### ISSUE THREAD

**Issue by lumayara** [Azure/azure-rest-api-specs#7868]
Hi.. Following @rposbo 's demo we were able to use the verification part but not identification part. It doesn't seem to be working.
It gets my profile created but doesn't save my recording to Identify.. I am getting this error: {"error":{"code":"BadRequest","message":"Invalid Http Request"}}

**Comment by akning-ms** [comment]
@lumayara Can you provide more info for this issue. e.g which service are you referring to for this issue？
@rposbo Do you know the detail?

**Comment by rposbo** [comment]
This was fixed in the demo (removing content type `multipart/form-data` that's no longer accepted); however, the API documentation needs to be updated to remove references to that header in the code examples
