### ISSUE TITLE
sql vm group can't add sql vm

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#7948]
Hi, I have created a sql vm, and then created a sql vm group. Then I have updated sql vm associated with this sql vm group, 201 success code returned, but then I get sql vm list in sql vm group, return empty list. 

associate sql vm with a sql vm group
put : `https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/weiyuping/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/sqlvm-test?api-version=2017-03-01-preview`
body:
```
{
      "location": "westeurope",
      "properties": {
      	"sqlServerLicenseType": "PAYG",
        "virtualMachineResourceId": "/subscriptions/{{subscriptionid}}/resourcegroups/weiyuping/providers/Microsoft.Compute/virtualMachines/sqlvm-test",
        "sqlVirtualMachineGroupResourceId": "/subscriptions/{{subscriptionid}}//resourceGroups/weiyuping/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachineGroups/testvmgroup",
        "wsfcDomainCredentials": {
          "clusterBootstrapAccountPassword": "<Password>",
          "clusterOperatorAccountPassword": "<Password>",
          "sqlServiceAccountPassword": "<Password>"
        }
      }
    }
```
response: 201 created

get sql vm list from a sql vm group
Get: `https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/weiyuping/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachineGroups/testvmgroup/sqlVirtualMachines?api-version=2017-03-01-preview`

reponse 200: 
```
{
    "value": []
}
```

**Comment by vadeveka** [comment]
Hi @yupwei68, whenever you execute an async operation such as sqlvm create/update or sqlvm group update, it will typically generate a 201 response with an operationResults URL in the response headers. You can use this URL to query the status of the operation. If the operation fails, the operationResults response would contain the error message.
Please refer to [Track asynchronous Azure operations](https://docs.microsoft.com/azure/azure-resource-manager/management/async-operations). Hope this helps.

**Comment by yupwei68** [comment]
@vadeveka Thanks for your help. Could you provide some docs on how to create a sql vm group? 
Because I follow the steps in CLI: create a sqlvm-> create a storage account-> create a sqlvm group(success)(the doc says that this step creates the cluster with the name previously given, installs the cluster role on the SQL Server VMs, and adds them to the cluster)-> add the sqlvm into the sqlvm group,  but the last step turns out to be an error :"code": "Ext_MachineNotJoinedToExpectedDomain",
        "message": "Machine is not joined to expected domain."

**Comment by vasivara-MSFT** [comment]
@yupwei68 Is your VM already joined to a domain? What is the domain address the VM is joined to and what is the domain address that you gave while creating the sql vm group? are they both same?

**Comment by yupwei68** [comment]
@vasivara-MSFT Thanks for your reply. I think I need to create AAD Domain and add my sqlvm into that domain first.
