### ISSUE TITLE
[MobileEngagement] Global parameters should specify location

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#796]
This [global parameters](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-mobileengagement/2014-12-01/swagger/mobile-engagement.json#L4078) should include `"x-ms-parameter-location": "method"`.

**Comment by mcardosos** [comment]
@guperrot

**Comment by dsgouda** [comment]
Seems like this has been fixed. @guperrot can you confirm and close this issue?

**Comment by mcardosos** [comment]
Looks like fixed :D
Thanks!
