### ISSUE TITLE
Properties with null value don't match their expected type, null is not supported in swagger

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#798]
When running swagger validation tools (https://github.com/Azure/openapi-validation-tools) against example payloads extracted from .Net test recordings, one class of issue reported is "Expected type X but found type null", particularly on responses. Example: https://github.com/Azure/azure-rest-api-specs/issues/766
Swagger 2.0 specification does not support null, so there's no standard way to specify it. 
To resolve the issue, there are a few of options to consider:
   1. Properties coming back in responses with null values may not need to be sent back in the response. If the properties are not required, then they should not be part of the service response, so allowing null value would not be necessary. 
   2. If we need to allow properties with null values, then we could:
              **A.** Consider adding an extension for it. There have been conversation in the openapispec initiative about adding this to the next version of the spec (https://github.com/OAI/OpenAPI-Specification/issues/229). It's not clear when the new specification will be released. Before that happens, we may need to implement 'x-ms-nullable' extension to allow for these cases, "x-ms-nullable" could be a boolean value applicable to each property, indicating whether the property is allowed to be null or not.
                **B.** For swagger validation purposes only, we could skip errors on null values (which avoids modifications to the specs for now), and filter out those errors from the result presented to the user of the validation tool. This could be part of implementing some kind of "exclusion list" for errors from the tool (https://github.com/Azure/openapi-validation-tools/issues/57).

@amarzavery, @johanste, @salameer, @fearthecowboy, @lmazuel , @begoldsm please take a look and let me know your thoughts. 
@fearthecowboy is 'x-ms-nullable' expected to be implemented as an extension in AutoRest? There seems to be some support for C# but didn't see it for others.

**Comment by fearthecowboy** [comment]
We actually have an implementation (somewhat) for `x-nullable` already. (There were already non-AutoRest generators that had added such a thing previously).

Internally, in AutoRest, the notion of nullability is fairly limited, the implicit rules (assumptions) about required/read-only drive the behavior, and `x-nullable` is only used as advice for selection of primitive types.

If you're talking about using `x-nullable` to drive behavior on validation, we should probably think about that.

This is one of those things on my list of **'Unwritten Assumptions That AutoRest Makes That Are Not Necessarily True'**

**Comment by veronicagg** [comment]
@fearthecowboy ok, thanks. Yes, we should discuss the uses of x-nullable so that we can use it for validation. Feel free to comment on the above, I've also tagged this issue for "discussion".

**Comment by kirthik** [comment]
@veronicagg : Can you please write a proposal on this so we can talk in the upcoming discussion meeting?

**Comment by johanste** [comment]
In general, using null values as semantically meaningful should be discouraged (except in PATCH operations w. content type application/merge-patch+json). My first reaction is that we should raise the issue with the service since in most cases that I've seen, the key/null value on the wire is typically handled in *exactly* the same way as a missing key/value pair (the fact that the service sits behind a strongly typed model class hides the distinction of missing vs. null value). 

Having said that, yes, supporting `x-isnullable` or `x-nullable`, at least for the purpose of validation would be good. Supporting nullable values in requests would require a longer discussion since that would impact serialization and possibly introduce breaking changes in existing SDKs.

**Comment by brjohnstmsft** [comment]
> In general, using null values as semantically meaningful should be discouraged (except in PATCH operations w. content type application/merge-patch+json). My first reaction is that we should raise the issue with the service since in most cases that I've seen, the key/null value on the wire is typically handled in exactly the same way as a missing key/value pair (the fact that the service sits behind a strongly typed model class hides the distinction of missing vs. null value).

@johanste You're making a lot of assumptions about the semantic difference between "null" and "missing" that may not hold for a data-plane service. Please keep that in mind when considering possible solutions. I'm with @fearthecowboy when it comes to making assumptions. They have a tendency to bite you later.

**Comment by nathannfan** [comment]
Just chiming in with an outside Swagger development perspective - it would be really helpful to be able to suppress these null errors in example validation. Validate-example should accept valid examples.  Valid examples should accurately represent what an ARM API returns, and many APIs are returning nulls.

I understand it may be helpful the first time the error appears in pointing out a potential API flaw, but updating the APIs in Azure production before continuing work is not feasible, and digging through the null errors to find the other errors is not trivial if there are a lot of them.

**Comment by veronicagg** [comment]
@salameer @kirthik could we discuss this and try to close on the decision in the next sprint?

**Comment by veronicagg** [comment]
https://github.com/Azure/oav/issues/158

**Comment by amarzavery** [comment]
This PR https://github.com/Azure/oav/pull/185 adds support for x-nullable for model validation in oav.
