### ISSUE TITLE
create a sql vm fail

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#8004]
Hi all,

I follow the example to create a sql vm, [link](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/preview/2017-03-01-preview/examples/CreateOrUpdateSqlVirtualMachineMIN.json),get 201 created. But the portal show that sql vm isn't created successfully and when we get a createsqlvirtualmachine operation result, it shows error code:Ext_SqlInstanceIsNotInstalled

put https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/acctestRG15/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctvm15?api-version=2017-03-01-preview
```
{
    "location": "eastus",
    "properties": {
        "virtualMachineResourceId": "/subscriptions/{{subscriptionId}/resourceGroups/acctestRG15/providers/Microsoft.Compute/virtualMachines/acctvm15",
        "sqlServerLicenseType": "PAYG"
    }
}
```
response 201 created:
```
{
    "properties": {
        "virtualMachineResourceId": "/subscriptions/{{subscriptionId}/resourceGroups/acctestRG15/providers/Microsoft.Compute/virtualMachines/acctvm15",
        "provisioningState": "Provisioning",
        "sqlServerLicenseType": "PAYG",
        "sqlManagement": "Full",
        "sqlImageSku": "Unknown"
    },
    "location": "eastus",
    "id": "/subscriptions/{{subscriptionId}/resourceGroups/acctestRG15/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctvm15",
    "name": "acctvm15",
    "type": "Microsoft.SqlVirtualMachine/sqlVirtualMachines"
}
```
portal shows:
![Annotation 2019-12-19 103203](https://user-images.githubusercontent.com/56525716/71141391-f1569c00-224e-11ea-8897-0f9d0943293f.png)

get https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.SqlVirtualMachine/locations/eastus/operationTypes/createsqlvirtualmachine/operationResults/{{id}}?api-version=2017-03-01-preview

```
{
    "name": "{{id}}",
    "status": "Failed",
    "startTime": "2019-12-19T02:47:31.94Z",
    "error": {
        "code": "Ext_SqlInstanceIsNotInstalled",
        "message": "Could not find any SQL Server instance in the Virtual Machine."
    }
}
```

**Comment by yupwei68** [comment]
It shows at the VM that the extension has installed with failure.
![Annotation 2019-12-24 150424](https://user-images.githubusercontent.com/56525716/71401835-06c03180-2666-11ea-8cfd-46413564891c.png)
After I remove the extension, reinstalled the extension successfully. And I recreate the sql vm, it cover the extension with failure.
And our unit test doesn't allow the extension to be reinstalled.

**Comment by yupwei68** [comment]
The reason appears to be  that my vm doesn't use image from "MicrosoftSQLServer". Please add that into creation sqlvm check

**Comment by vadeveka** [comment]
Hi @yupwei68, you are correct in observing that a sqlvm resource is created before some of the checks. The resource will go though provisioning state and move to ready or failed states depending on provisioning result. This is expected behavior with the current implementation of sqlvm creation.

**Comment by yupwei68** [comment]
@vadeveka Thanks for your reply.

**Comment by yupwei68** [comment]
@vadeveka , Currently I have a new question. I create a sqlvm with provision succeed. Then I get this sqlvm with expand autoPatchingSetting.
First time, I get a  500 internal error:
`{"error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: 'c8f6ece9-fbc5-428a-99a5-85f05c60540b'"}}`
Second time, I get a 200 success message:
```
 {"properties":{"virtualMachineResourceId":"/subscriptions/{{subscriptions}}/resourceGroups/acctestRG-mssqlvm-tf/providers/Microsoft.Compute/virtualMachines/acctest-VM-tf","provisioningState":"Succeeded","sqlImageOffer":"SQL2019-WS2019","sqlServerLicenseType":"PAYG","sqlManagement":"Full","sqlImageSku":"Developer","autoPatchingSettings":{"enable":false},"keyVaultCredentialSettings":{"enable":false},"serverConfigurationsManagementSettings":{"sqlConnectivityUpdateSettings":{"connectivityType":"PRIVATE","port":1433},"sqlWorkloadTypeUpdateSettings":{},"sqlStorageUpdateSettings":{},"additionalFeaturesServerConfigurations":{"isRServicesEnabled":false}}},"location":"eastus","tags":{},"id":"/subscriptions/{{subcriptionid}}/resourceGroups/acctestRG-mssqlvm-tf/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/acctest-VM-tf","name":"acctest-VM-tf","type":"Microsoft.SqlVirtualMachine/sqlVirtualMachines"}
2020/01/13 15:40:21 [WARN] Provider "azurerm" produced an unexpected new value for azurerm_mssql_virtual_machine.test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .auto_patching[0].day_of_week: was cty.StringVal("Sunday"), but now cty.StringVal("")
      - .auto_patching[0].enable: was cty.True, but now cty.False
      - .auto_patching[0].maintenance_window_duration_in_minutes: was cty.NumberIntVal(60), but now cty.NumberIntVal(0)
      - .auto_patching[0].maintenance_window_starting_hour: was cty.NumberIntVal(2), but now cty.NumberIntVal(0)
      - .key_vault_credential[0].credential_name: was null, but now cty.StringVal("")
      - .key_vault_credential[0].service_principal_name: was null, but now cty.StringVal("")
      - .key_vault_credential[0].service_principal_secret: inconsistent values for sensitive attribute
      - .key_vault_credential[0].azure_key_vault_url: was null, but now cty.StringVal("")
```

Could you provide any kind help?

**Comment by jeroenterheerdt** [comment]
kindly open a new issue for the new question, that helps in our tracking. thanks.
