### ISSUE TITLE
[arm-insights 2015-07-01] Semantic validation fails with Unresolvable path parameter error

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#803]
azure-rest-api-specs/arm-insights/2015-07-01/swagger/insightsManagementClient_DiagnosticsSettings.json should be valid Swagger

Errors
------
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{resourceUri}/providers/microsoft.insights/diagnosticSettings/service/get/parameters/2/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{resourceUri}/providers/microsoft.insights/diagnosticSettings/service/put/parameters/3/name : API path parameter could not be resolved: subscriptionId

**Comment by gucalder** [comment]
This is resolved in both insights and monitor folders. The extra (unused) parameter subId has been removed.

**Comment by johnkemnetz** [comment]
@kirthik can you close this since it is now resolved?

**Comment by kirthik** [comment]
@gucalder : Can you please provide the commit id? That will make it easier to track

**Comment by gucalder** [comment]
The commit for this specific file is #efed63280648eebdec8be513470cd6c23783efb6 from 2017-02-16.
