### ISSUE TITLE
[arm-resources 2015-11-01] Semantic validation reports unresolvable API path parameter errors

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#804]
/azure-rest-api-specs/arm-resources/resources/2015-11-01/swagger/resources.json should be valid Swagger

Errors
------
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//providers/{resourceProviderNamespace}/operations/get/parameters/2/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}/delete/parameters/3/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}/put/parameters/4/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}/get/parameters/3/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{policyAssignmentId}/delete/parameters/2/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{policyAssignmentId}/put/parameters/3/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{policyAssignmentId}/get/parameters/2/name : API path parameter could not be resolved: subscriptionId
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//{scope}/providers/Microsoft.Authorization/policyAssignments/get/parameters/3/name : API path parameter could not be resolved: subscriptionId

**Comment by TianoMS** [comment]
@veronicagg can you provide more details? How did you get these errors?

**Comment by kirthik** [comment]
ping @veronicagg

**Comment by TianoMS** [comment]
we have to consider this as not repro because of not enough information. @kirthik can you close this issue?

**Comment by veronicagg** [comment]
@TianoMS sorry looked like I missed previous pings on this, in terms of the errors above:
for example for /{scope}/providers/Microsoft.Authorization/policyAssignments/{policyAssignmentName}
the following specified parameters are not part of the path for that operation and if so, they should be removed:
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }

**Comment by TianoMS** [comment]
@veronicagg "ApiVersionParameter" is a query parameter so it should be OK to keep. "SubscriptionIdParameter" seems not applicable in some APIs. Will need to fix. @ravbhatnagar to triage.

**Comment by veronicagg** [comment]
@TianoMS yes, you're correct about the query parameter, my bad including it above, the errors originally reported all refer to subscriptionId not applicable.

**Comment by ravbhatnagar** [comment]
Looks like an easy fix. @TianoMS - please fix when you get a chance.

**Comment by ifeoluwaokunoren** [comment]
Resolved here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2015-11-01/resources.json#L1863
