### ISSUE TITLE
[arm-trafficmanager 2015-11-01] Semantic validation reports unresolvable path parameter error

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-rest-api-specs#805]
/azure-rest-api-specs/arm-trafficmanager/2015-11-01/swagger/trafficmanager.json should be valid Swagger

Errors
------
UNRESOLVABLE_API_PATH_PARAMETER : #/paths//providers/Microsoft.Network/checkTrafficManagerNameAvailability/post/parameters/2/name : API path parameter could not be resolved: subscriptionId

**Comment by liumichelle** [comment]
@ms-alguerra can you please take a look at this?

**Comment by vladca** [comment]
This should be done as part of https://github.com/Azure/azure-rest-api-specs/commit/7a5fdd890e4587600f041e602ca14b72e3a2492b

**Comment by veronicagg** [comment]
Yes, this is resolved now, thanks!
