### ISSUE TITLE
The type of property isEnabled for Managed Application Definition should be boolean not string

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#8064]
I am trying to get resource Managed Application Definition with azure go sdk but it failed and threw below error message after created this resource successfully. After investigated, the property type of isEnabled in local package is string, however, the property type of isEnabled in the response returned from azure side is boolean. As they are inconsistent, so it encountered property type conversion issue. So the property type of isEnabled for managed application definition in repos azure-rest-api-spec (https://github.com/Azure/azure-rest-api-specs/blob/06b9412319ada8678c0ce07016cac1bf66258b1d/specification/resources/resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json#L1014) and azure-sdk-for-go (https://github.com/Azure/azure-sdk-for-go/blob/781d9fb592a1818cb7fb8e0855ea9c00b095a9e9/services/resources/mgmt/2018-06-01/managedapplications/models.go#L589) should be updated from string to bool, right? If yes, please help to fix it ASAP since we’re blocked on here. Thanks.

The error message:
The error message:
Error: Error retrieving Managed Application Definition (Managed Application Definition Name "neiltest2-managedapplicationdefinition" / Resource Group "neiltest2-resources"): managedapplications.ApplicationDefinitionsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal bool into Go struct field ApplicationDefinitionProperties.isEnabled of type string' JSON = '{"properties":{"authorizations":[{"principalId":"xxxx","roleDefinitionId":"xxxxx"}],"isEnabled":true,"lockLevel":"ReadOnly","displayName":"TestManagedApplicationDefinition","description":"Test Managed Application Definition","artifacts":[{"name":"ApplicationResourceTemplate","type":"Template","uri":"https://xxxx/applicationdefinitions/xxxxx/xxx/applicationResourceTemplate.json"},{"name":"CreateUiDefinition","type":"Custom","uri":"https://xxxx/subscriptions/xxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition/applicationArtifacts/CreateUiDefinition?api-version=2017-09-01"},{"name":"MainTemplateParameters","type":"Custom","uri":"https://management.azure.com/subscriptions/xxxxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition/applicationArtifacts/MainTemplateParameters?api-version=2017-09-01"}]},"id":"/subscriptions/xxxxxx/resourceGroups/neiltest2-resources/providers/Microsoft.Solutions/applicationDefinitions/neiltest2-managedapplicationdefinition","name":"neiltest2-managedapplicationdefinition","type":"Microsoft.Solutions/applicationDefinitions","location":"eastus","tags":{}}'

on main.tf line 6, in resource "azurerm_managed_application_definition" "example":
6: resource "azurerm_managed_application_definition" "example" {

Repro steps:
Create a resource group
Create Resource Managed Application Definition
Immediately call "Get" go rest api to get resource Managed Application Definition, which returns below error message

**Comment by ArcturusZhang** [comment]
Hi @armleads-azure could you please have a look at this issue?

**Comment by neil-yechenwei** [comment]
Hi @dandanwang0320 , I saw you had made change(https://github.com/Azure/azure-rest-api-specs/pull/7803) to fix this issue in this repo azure-rest-api-spec. May I know when the fix would be synced to repo "azure-sdk-for-go"(https://github.com/Azure/azure-sdk-for-go)?

**Comment by dandanwang0320** [comment]
Let me test the dot net sdk first before I merge the Go SDK.

**Comment by MSEvanhi** [comment]
This has been fixed in later versions of the SDK: 
github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-07-01/managedapplications
in v39.0.0

**Comment by ArcturusZhang** [comment]
Hi @neil-yechenwei since this has been fixed in a higher api-version, maybe you will have to upgrade the api-version...

While in the meantime, @MSEvanhi is it possible to back port this fix to the old api-version as well? Despite this might be a breaking change for the old api-version, I suppose as a bug fix, it may be allowed
