### ISSUE TITLE
zoneMappings property is missing from ARM GET /subscriptions/{subscriptionId}/providers response definition

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#8097]
The definition here (and in other API versions) is missing this property definition on the ProviderResourceType definition:

https://github.com/Azure/azure-rest-api-specs/blob/8179f85219cba709013ac46ca9a2d99644423da7/specification/resources/resource-manager/Microsoft.Resources/stable/2019-07-01/resources.json#L2028-L2072

This affects our SDKs and docs - see https://docs.microsoft.com/en-us/rest/api/resources/providers/list#providerresourcetype

**Comment by akning-ms** [comment]
Not sure whether it is belong to ARM-core, pls help reassign if need. Thanks

**Comment by anthony-c-martin** [comment]
> Not sure whether it is belong to ARM-core, pls help reassign if need. Thanks

`ARM - Core` is correct - thanks!

**Comment by cschen13** [comment]
Hello, has any progress been made on this, or is there some other part of the Azure REST API that provides an authoritative list of supported AZs by resource provider?

**Comment by ifeoluwaokunoren** [comment]
Issue fixed with this PR: https://github.com/Azure/azure-rest-api-specs/pull/13936
