### ISSUE TITLE
[Redis] Get firewall rules endpoint returns a HTTP 504 Timeout

### ISSUE THREAD

**Issue by elliot-resdiary** [Azure/azure-rest-api-specs#8107]
We use Terraform to manage our Azure resources and Terraform will often make `GET` API calls to understand the current state of our infrastructure. For the past few days, the endpoint to fetch Redis firewall rules has been giving us `HTTP 504` about 80% of the time.

```
{"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."}}
[DEBUG] AzureRM Request: 
GET /subscriptions/<subscription-id>resourceGroups/<resource-group>/providers/Microsoft.Cache/Redis/<cache-name>/firewallRules/<firewall-rule-name>?api-version=2018-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.12.6 (amd64-linux) go-autorest/v12.2.0 Azure-SDK-For-Go/v31.1.0 redis/2018-03-01
X-Ms-Correlation-Request-Id: 9f2caebd-e081-853a-621e-a5756f7bb496
Accept-Encoding: gzip
```

This may be somehow related to #1499.

**Comment by Badgerati** [comment]
I keep on getting the same responses as well, using terraform for just trying to create an Azure Redis Cache. The occurrence rate I see it about the same as well - 80% of the time, if not higher, it's a failure.

I raised an issue over on terraform (https://github.com/terraform-providers/terraform-provider-azurerm/issues/5355) as was unsure, but starting to think this might now be more Azure API related.

**Comment by elliot-resdiary** [comment]
This was either a temporary or intermittent issue since we haven't been able to reproduce it today. I have a known failing request ready in Postman if the issue returns - that should isolate this as an Azure API problem rather than a Terraform one.

**Comment by Badgerati** [comment]
I've just had 4/4 runs complete successfully, so also happy to say that it's stable for now.

**Comment by MECHANDR** [comment]
Issue has been addressed at the API layer and it is no longer impacting based on comments.
@elliot-resdiary, Thanks for reporting. Please reopen if you see this issue again.
