### ISSUE TITLE
The property type of "Version" for Management Partner is inconsistent between azure client side and azure server side

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#8178]
I tried to create association with azure go sdk (https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/managementpartner/mgmt/2018-02-01/managementpartner) but it failed and threw below error message. After investigated, the failure is caused by type conversion issue. The property type of “Version” in azure go sdk (https://github.com/Azure/azure-sdk-for-go/blob/fa96a3744b0e40e6e0d3ddf985f80cfe2d51d6d6/services/preview/managementpartner/mgmt/2018-02-01/managementpartner/models.go#L258) and azure rest api spec (https://github.com/Azure/azure-rest-api-specs/blob/c678aa6849d5d46807fe7fc3a2eff430b590bcbe/specification/managementpartner/resource-manager/Microsoft.ManagementPartner/preview/2018-02-01/ManagementPartner.json#L293) is “string”. However, the property type of “Version” in the response returned from azure side is number. As they are inconsistent, so it encountered type conversion issue. After updated the property type of “Version” from “string” to number type in my local azure go sdk package, then it can create assocation successfully. So could you help to have a look? If it’s a bug, could you help to fix it asap since we’re blocked on here. I also filed an issue on repo azure rest api spec (). Thanks.

Error message:
Error: Error creating Management Partner "xxxxxx": managementpartner.PartnerClient#Create: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field PartnerProperties.version of type string' JSON = '{"id":"/providers/microsoft.managementpartner/partners/xxxxx","type":"Microsoft.ManagementPartner/partners","name":"xxxx","etag":19,"properties":{"partnerId":"xxxx","partnerName":"xxxxx","tenantId":"xxxxx","objectId":"xxxxxx","version":19,"updatedTime":"2020-01-17T03:53:37.7735538Z","createdTime":"2020-01-17T01:44:06.3772514Z","state":"Active"}}'

  on main.tf line 1, in resource "azurerm_management_partner" "example":
   1: resource "azurerm_management_partner" "example" {

**Comment by neil-yechenwei** [comment]
@jeffrey-ACE , could you help to have a look for this issue? If it's a bug, please help to fix it asap since we're blocked on it. Thanks so much.

**Comment by weidongxu-microsoft** [comment]
Hello @jeffrey-ace, this appears to be an inconsistency between swagger spec and service implementation on managementpartner. Could you take a look?

**Comment by ArcturusZhang** [comment]
This issue has been resolved in #8276
