### ISSUE TITLE
[Network] VPN type required for Virtual Network Gateway?

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#818]
Hi,

Looking at the portal, it seems that VPNType is optional when using "ExpressRoute" gateway type (the box totally disapears):

In ExpressRoute:
![image](https://cloud.githubusercontent.com/assets/1050156/21333212/1459c502-c603-11e6-8cc2-cf133b767bca.png)

In VPN:
![image](https://cloud.githubusercontent.com/assets/1050156/21333227/314c3ffa-c603-11e6-9bae-b69198863fa3.png)

However, in the Swagger file, "vpn_type" is required, this means that even on ExpressRoute mode we have to fill something to be able to create the initial payload.

Seems to me it should be optional, or at least be clear on the documentation what is expected in ExpressRoute mode.

**Comment by amarzavery** [comment]
@DeepakRajendranMsft - Please take a look at this issue.

**Comment by liumichelle** [comment]
@DeepakRajendranMsft - assign this to @amitsriva - can you please take a look?

**Comment by liumichelle** [comment]
@MohitGargVpn can you take a look at this issue?

**Comment by Nilambari** [comment]
Checked with PM to update the online documentation to specify that for template based ExpressRoute Gateway deployments, Please fill value as :- VPN type = Route-based.

**Comment by salameer** [comment]
@liumichelle this should be closed when the documentation in Done
