### ISSUE TITLE
App Service Plans - Restart Web Apps - NotImplemented - ExtendedCode: 51009

### ISSUE THREAD

**Issue by rspaulino** [Azure/azure-rest-api-specs#8186]
Hi, I'm trying calling this API from https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/restartwebapps#code-try-0 - "REST API Try It"
and from Powershell but I keep getting the same error: 

{
  "Code": "NotImplemented",
  "Message": "The requested method is not implemented.",
  "Target": null,
  "Details": [
    {
      "Message": "The requested method is not implemented."
    },
    {
      "Code": "NotImplemented"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "51009",
        "MessageTemplate": "The requested method is not implemented.",
        "Parameters": [],
        "Code": "NotImplemented",
        "Message": "The requested method is not implemented."
      }
    }
  ],
  "Innererror": null
}

But when I call the restart from the "Azure Mobile App" I can see it succeed but when I can it from code it keep failing, any ideas? thanks.

**Comment by lirenhe** [comment]
Not sure whether the error message is from service side. Service team, please take a look.

**Comment by ajts-001** [comment]
I get this as  well.  Is this a bug or a problem in my code?

**Comment by hammer5280** [comment]
Hello, I am getting same response code when testing from here as well and Try it:

https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans/restartwebapps#code-try-0

Any updates on this?
Thanks

**Comment by 23min** [comment]
Looks like there hasn't been any follow up on this. I'm getting a 501 as well. 
If I add optional parameter `{softrestart}`, (true) the API responds with 200, but nothing happens, despite keys being update in KeyVault.
If softrestart = false, I get a 501 again.

How are we supposed to start a function app via code?

**Comment by 23min** [comment]
> Looks like there hasn't been any follow up on this. I'm getting a 501 as well.
> If I add optional parameter `{softrestart}`, (true) the API responds with 200, but nothing happens, despite keys being update in KeyVault.
> If softrestart = false, I get a 501 again.
> 
> How are we supposed to start a function app via code?

Ok. Well I managed to solve my need. Instead of `restart` I used `stop`, then `start`. That worked! 
But it would be good if the restart API was looked at because it does not work as advertised.

**Comment by iRubens** [comment]
Same for me! Both from "Azure.ResourceManager.AppService" and from the portal as mentioned before.
This API would be very useful, but sadly it isn't...

Any news on this?
