### ISSUE TITLE
[Network] Create VN Gateway, 'name=default' required in VirtualNetworkGatewayIPConfiguration?

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#819]
When created a VN Gateway, if you forget to specify a `name` argument to `VirtualNetworkGatewayIPConfiguration` we receive an (unhelpful) error from ARM: `Cannot parse the request.`

Digging using the Automation window on the Portal, it seems that there is only one value possible: 'default'
![image](https://cloud.githubusercontent.com/assets/1050156/21334052/395e3ee0-c609-11e6-9978-f96805183c42.png)

So:
- If this is a constant, please declare it as constant with "default" as unique value
- If this can vary, please declare it as required parameter

In any situation, please correct the error message on the RestAPI message. Took me one hour and diff from the Portal to figure this out. And trapped also a customer (https://github.com/Azure/azure-sdk-for-python/issues/910)

**Comment by amarzavery** [comment]
@DeepakRajendranMsft - Please take a look at this issue.

**Comment by liumichelle** [comment]
@DeepakRajendranMsft - assign this to @amitsriva

**Comment by liumichelle** [comment]
@MohitGargVpn can you take a look?

**Comment by Nilambari** [comment]
This is no repro. 'name' is the required parameter for command let:-New-AzureRmVirtualNetworkGatewayIpConfig for creating new Vnet gateway ip config which you pass to create a new VirtualNetworkGateway. If you do not pass name param, it will ask to pass value for it.
You can pass any valid value for name param except default. Please find below command lets:-

PS C:\WINDOWS\system32> **New-AzureRmVirtualNetworkGatewayIpConfig** -PublicIpAddress $publicip -Subnet $subnet
cmdlet New-AzureRmVirtualNetworkGatewayIpConfig at command pipeline position 1
**Supply values for the following parameters:**
(Type !? for Help.)
**Name:** vnetGatewayConfigName1


Name                      : vnetGatewayConfigName1
Id                        : /subscriptions/b636ca99-6f88-4df4-a7c3-2f8dc4545509/resourceGroups/ResourceGroupNotSet/providers/Microsoft.Network/virtualNetworkGateways/VirtualNetworkGatewayNameNotSet/virtualNetworkGatewayIpConfiguration/vnetGatewayConfigName1
Etag                      :
PrivateIpAddress          :
PrivateIpAllocationMethod : Dynamic
Subnet                    : {
                              "Id": "/subscriptions/b636ca99-6f88-4df4-a7c3-2f8dc4545509/resourceGroups/VpnGw3RG1/providers/Microsoft.Network/virtualNetworks/vnetName1/subnets/GatewaySubnet"
                            }
PublicIpAddress           : {
                              "Id": "/subscriptions/b636ca99-6f88-4df4-a7c3-2f8dc4545509/resourceGroups/VpnGw3RG1/providers/Microsoft.Network/publicIPAddresses/publicIpName1"
                            }

Please help close this issue.

**Comment by kirthik** [comment]
@lmazuel  - Could you please look at @Nilambari's response above and close this if you have no other concerns.

**Comment by lmazuel** [comment]
@kirthik @Nilambari Sorry I didn't see the answer earlier.

I have concerns, @Nilambari you wrote "The 'name' is required parameter". Then do define this parameter as required in the Swagger (as I suggested at first). [It's still not the case.](https://github.com/Azure/azure-rest-api-specs/blob/1a88e3f49b78c6ec74f9174115e5233cb6fe20c4/specification/network/resource-manager/Microsoft.Network/2017-06-01/virtualNetworkGateway.json#L1060-L1082)

**Comment by MikhailTryakhov** [comment]
fixed
