### ISSUE TITLE
Reopen #8068

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#8193]
hi

As mentioned in [this comment](https://github.com/Azure/azure-rest-api-specs/issues/8068#issuecomment-574522531) unfortunately #8068 highlights an issue in the Azure Compute API which has been closed in error - can we please re-open this so that we can get this API bug fixed?

Thanks!

**Comment by erich-wang** [comment]
reopen #8068 and close this issue.
