### ISSUE TITLE
Add APIs to manage Application Gateway child resources

### ISSUE THREAD

**Issue by boillodmanuel** [Azure/azure-rest-api-specs#8252]
Hello,

network/ApplicationGateway provides only 1 api :
- applicationgateways [MAIN]

network/LoadBalancer provides 7 api to manage resources and inner resources : 
- loadbalancers [MAIN]
- loadbalancer backendaddresspools
- loadbalancer frontendipconfigurations
- loadbalancer loadbalancingrules
- loadbalancer networkinterfaces
- loadbalancer outboundrules
- loadbalancer probes

The Azure cli for ApplicationGateway provides ~20 modules, see  here: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest

Could you add the missing modules in the SDK?

**Comment by boillodmanuel** [comment]
Seems related to https://github.com/Azure/azure-rest-api-specs/issues/2313

**Comment by winthrop28** [comment]
@boillodmanuel quick clarifying question - are you looking for a PUT API on child resources of the Application Gateway?

**Comment by boillodmanuel** [comment]
@winthrop28 , I don't know exactly what would be the HTTP method between PUT and POST or DELETE😀.
But definitely I'm asking for APIs to create, update and delete application gateway's child resources.

In my use case, different teams would update the application gateway :
- network teams will create an empty Application Gateway (#2313) that will manage all HTTP incoming trafic
- project team A will add (update and delete) backend and rule to route traffic to their application
- project team B also...

**Comment by boillodmanuel** [comment]
Asked on azure feedback site: https://feedback.azure.com/forums/217313-networking/suggestions/39634588-add-rest-apis-and-sdk-to-manage-application-gatewa
If people following this issue could vote on it, it will be great 👍

**Comment by winthrop28** [comment]
Thanks for the feedback!
