### ISSUE TITLE
[Network] Nested resources are absent from the spec

### ISSUE THREAD

**Issue by iouri-s** [Azure/azure-rest-api-specs#826]
For example the path /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/loadBalancers/{lbName}/incomingNatRules/{name} is not represented even though it is a documented API: https://msdn.microsoft.com/en-us/library/azure/mt740351.aspx

**Comment by amarzavery** [comment]
@deepakrajendranmsft - Can you take a look at this issue?

**Comment by DeepakRajendranMsft** [comment]
Hi, yes this is a known issue, we wll try to fix it at the earliest

**Comment by salameer** [comment]
Keeping on Deepak's side

**Comment by DeepakRajendranMsft** [comment]
this has been fixed https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-08-01/loadBalancer.json#L596

**Comment by salameer** [comment]
closing
