### ISSUE TITLE
Management Groups - List - missing management groups

### ISSUE THREAD

**Issue by juanjojulian** [Azure/azure-rest-api-specs#8263]
Hi, [Management Groups - list](https://docs.microsoft.com/en-us/rest/api/resources/managementgroups/list) or '_az account management-group list_' are unable to list second level (child) management groups if I'm not listed as the owner of the management group.

An Example to clarify:

- I have four management groups under my Tenant Root where my group "Cloud Admins" is 'owner' and I can list them with the API and az cli.
- I have five management groups under one of the previous management groups (Childs) where my group "Cloud Admins" is 'owner' but I cannot see them when I list with API/cli.
- If I modify one of the child management groups and add my user (not group but user) as owner then that management group appears in the list when I make use of the API/cli.

Hope the problem is clear, if you need more info please ask.

**Comment by rthorn17** [comment]
Hi @juanjojulian -  Yes we are aware of this open issue and it is something we need to fix on our API side.  We are in design discussions and I don't have a timeline yet.  Will update this when I do. Thanks

**Comment by wsf11** [comment]
Hi @rthorn17 , any update on this issue?

I am experiencing this same issue except with SP. I have a management group structure and my SP is owner of the Tenant Root Group. Unless I grant my SP `Management Group Reader` on the management group itself, I cannot see it when I run a `management group list` REST API query. However, if I run a `management group get`, it appears.

**Comment by rthorn17** [comment]
We have deployed a change over the weekend to correct this behavior.  When doing a list call on MGs, you will now be returned all MGs that you have access to as expected.  Direct Access or Inherited Access MGs are shown.
