### ISSUE TITLE
Documentation for X509CertificateProperties is missing basic_constraints

### ISSUE THREAD

**Issue by mkreidenweis** [Azure/azure-rest-api-specs#8295]
The documentation for Key Vault REST API type `X509CertificateProperties` is missing the documentation of the `basic_constraints` structure here:
https://github.com/Azure/azure-rest-api-specs/blob/b91c2b941d20647ccd41d5857d8a0b8ec020e2a0/specification/keyvault/data-plane/Microsoft.KeyVault/stable/2016-10-01/keyvault.json#L3650

The `basic_constraints` are shown in many examples, e.g. here:
https://github.com/Azure/azure-rest-api-specs/blob/c87d2b0c787c12d635c36fb44a431d2270912234/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/examples/GetCertificatePolicy-example.json#L24

There is some documentation of this structure here, which the documentation could be based on: https://docs.microsoft.com/en-us/rest/api/keyvault/certificates-and-policies#d509-props
However, it has a typo in `path_len_contraint` -- needs to be `path_len_constraint`.

There might be some other missing fields somewhere, as noted by @nschonni in https://github.com/Azure/azure-rest-api-specs/pull/6126#issuecomment-496361936

**Comment by heaths** [comment]
@akning-ms I don't work on the service side. @RandalliLama, can someone on your team look into this?

**Comment by sebansal** [comment]
Basic constraints is to tell you whether it’s a CA or not. We do not support it in UI/powershell. You can achieve it through the SDK or restapi. People building PKI on top of key vault find a way out on how to achieve it and they ask for it. 
 
Basic Constraint is a field which is optional for leaf certs but a must for CA cert. CA building folks are looking for that capability.

**Comment by sebansal** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/10783

**Comment by mkreidenweis** [comment]
Hi @sebansal, thanks for looking into this. I'm a bit confused now though. 
In #10783 you add the description back to the `GetCertificatePolicy-example.json`, where it actually existed when at the time I opened this ticket, until it was later removed in https://github.com/Azure/azure-rest-api-specs/commit/8b175d253e5115f49b7691f0fc9de538ea181049#diff-8989e600baa1215ff227cd5b6f6686c2L24

However, I would expect it to be added especially to the `X509CertificateProperties` structure documentation as well, e.g. in 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/certificates.json#L1540

The call where it's most important is actually `CreateCertificate`.

**Comment by vsabella** [comment]
This does not appear to work in Azure GovCloud - the field is ignored and the certificate does not contain basic constraints.

**Comment by heaths** [comment]
@sebansal, you said:

> You can achieve it through the SDK or restapi.

Since it's not defined in swagger, we actually don't support it in the SDK. If this is something that should be exposed publicly, it needs to be defined in swagger.

**Comment by tringuyen-yw** [comment]
How come this issue is closed? As of 2021-05-20  the page [Azure REST API - Create Certificate](https://docs.microsoft.com/en-us/rest/api/keyvault/createcertificate/createcertificate#x509certificateproperties) still missed the info related to `x509_props.basic_constraints`. This issue shows a JSON https://github.com/Azure/azure-cli/issues/18178 which defines the X509v3 Basic Constraints having the `CA: true` property set.

**Comment by heaths** [comment]
@sebansal, @jlichwa is `basic_constraints` supported in the REST API? We can add this to the SDK, but it has to be in the swagger properly.

**Comment by jlichwa** [comment]
+ @RandalliLama if creating certificate with setting "basic_constraints" is supported. My understanding that since it is not documented in swagger, it is not supported today.

**Comment by tringuyen-yw** [comment]
@jlichwa [18178 az keyvault certificate create unable to set X509 Certificate properties Basic Constraints CA = true](https://github.com/Azure/azure-cli/issues/18178) proves that a REST API call is able to create a x509 CA cert WITH basic constraints having property `CA: true` WORKING (while the same operation using Azure CLI could not.

I think that it is rather the swagger test is not up-to-date

**Comment by jlichwa** [comment]
@tringuyen-yw  we don't see any public documentation, no support on Portal or SDKs, so it is unlikely it is fully released, well tested, covering all scenarios option.

**Comment by jlichwa** [comment]
It seems like there is feature request here: https://github.com/Azure/azure-rest-api-specs/issues/11962#issuecomment-827181465
#please-close
