### ISSUE TITLE
Should we combine swagger directory `recoveryservices` and `recoveryservicebackup`?

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#8308]
Related issue: https://github.com/Azure/azure-sdk-for-go/issues/7279

Currently, every rest api request uri under swagger directory [recoveryservicebackup](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable) is based on 
```
/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{vaultName}/
```
which corresponds to a resource `vault` in `recoveryservices`. 

This difference of directories caused the SDK generated from those two directories of swaggers cannot share the same namespace. For instance, in go SDK, the `vault` resource is under package `recoveryservices` package, but its sub-resource `ResourceVaultConfig` is under package `backup`.

Is there any possibility that we can combine those two directories and make the resource `vault` from `recoveryservices` has the same SDK namespace as those sub-resources from `recoveryservicebackup`, which makes a lot more sense?

**Comment by pvrk** [comment]
@ArcturusZhang : Unfortunately, recovery services vault is used for both ASR and backup and hence this lies in a 'upper' namespace. The backup related vault configurations like is recoveryservicesbackup namespace. I acknowledge the confusion but we may not be able to change anything here, as of now.

**Comment by ArcturusZhang** [comment]
Hi @katbyte and @tombuildsstuff the service team has replied, would you please have a look or discussion about this issue?

**Comment by pvrk** [comment]
Any update on this? I have to close the bug if no other issues are there since the closing time is now being tracked.

**Comment by ArcturusZhang** [comment]
Hi @pvrk sure, I am going to close this one, since there is no other option regarding on this particular naming issue...
