### ISSUE TITLE
Microsoft.Network: `securityRule` resource group name not respecting case sensitivity

### ISSUE THREAD

**Issue by notchairmk** [Azure/azure-rest-api-specs#8309]
When creating a `securityRule`, the case of resource group name is inherited from the `networkSecurityGroup` ignoring case passed as a parameter.

Repro steps: 

 1. Create resource group with `resourceGroupName = "test-rg"`
 2. Create network security group with `resourceGroupName = "TEST-RG"`
 3. Create security rule associated to network security group created in step 2 with `resourceGroupName = "test-rg"`
 4. Subsequent GET of security rule created in step 3 has `resourceGroupName` with value of `"TEST-RG"`

For example, when creating a `virtualNetwork` associating a `subnet` if created with `virtualNetwork.resourceGroupName = "test-rg"` and `subnet.resourceGroupName = "TEST-RG"`, performing a GET subnet respects case sensitivity of resource group name passed at create time, i.e. GET returns `subnet.resourceGroupName = "TEST-RG"`.

**Comment by allenjzhang** [comment]
Thanks for reporting the issue. What is the tool you are seeing problem in? CLI, Powershell or SDK (particular language)?

**Comment by allenjzhang** [comment]
This is not specifically REST API spec issue. These issues have been [reported on other repos as well. Here is one of them.](https://github.com/Azure/azure-sdk-for-java/issues/1508) Sounds like this requires coordination of ARM and each of the providers to address this. 

I will close this on this repo. Thanks.
