### ISSUE TITLE
Azure Container Service: Windows Support

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#833]
:wave: Hi Everybody!

![inline](http://vignette3.wikia.nocookie.net/simpsons/images/5/5e/Dr._Riviera.png/revision/latest?cb=20120509073411)

I've been working with Azure Container Service (ACS) for a few weeks now - [hooking it up into Terraform](https://github.com/hashicorp/terraform/pull/10820) - and I've noticed a few issues/limitations along the way.

I previously raised an issue about [usage clarifications for ACS](https://github.com/Azure/azure-sdk-for-go/issues/439). After [doing some digging](https://github.com/Azure/acs-engine/blob/master/pkg/api/v20160330/validate.go#L94) it looks as if the Windows Agents are limited to the Swarm provider only at this time?

Would it be possible to get some usage clarifications for Windows support on ACS please? Is the intention for them to be supported on all Orchestration Platforms in the mid-term? Given that the only information I can find is limited - which makes me think this is isn't ready for primetime at this point?

Thanks!

**Comment by colemickens** [comment]
Windows Swarm support is in private preview. DCOS and Kubernetes support
will come as those platforms evolve full Windows support and then we build
support for them.

I don't think we have timelines for either announced right now.

Cc: @rgardler

**Comment by colemickens** [comment]
cc: @Azure/acs

**Comment by tombuildsstuff** [comment]
thanks for the info @colemickens - is there any way I can get access to that preview?

**Comment by sauryadas** [comment]
Windows support with swarm on acs ? If yes , you need to sign up on azure advisors to get in if you are a partner . If you are a Microsoft employee then email me your subs Id.

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by tombuildsstuff** [comment]
@sauryadas great - I'll post in there then - thanks.

**Comment by brendandburns** [comment]
I think we can close this?

**Comment by amanohar** [comment]
Closing. Windows agents are supported with Kubernetes or Swarm orchestrator in ACS.

**Comment by tombuildsstuff** [comment]
@brendandburns I believe we can - is this GA/is there an expected GA date available for this? Thanks!
