### ISSUE TITLE
`Microsoft.PolicyInsights/remediations` returns every resource IDs in lower cases

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#8353]
Rest API URL:
```
PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test-resources/providers/Microsoft.PolicyInsights/remediations/test-remediation?api-version=2018-07-01-preview HTTP/1.1
```
Request body:
```
{
    "properties": {
        "policyAssignmentId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test-resources/providers/Microsoft.Authorization/policyAssignments/example-policy-assignment",
        "policyDefinitionReferenceId": ""
    }
}
```
A GET response after the creation finished:
```
{
    "properties": {
        "policyAssignmentId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/test-resources/providers/microsoft.authorization/policyassignments/example-policy-assignment",
        "provisioningState": "Succeeded",
        "createdOn": "2020-02-11T03:28:29.456352Z",
        "lastUpdatedOn": "2020-02-11T03:28:29.5344467Z",
        "deploymentStatus": {
            "totalDeployments": 0,
            "successfulDeployments": 0,
            "failedDeployments": 0
        },
        "resourceDiscoveryMode": "ExistingNonCompliant"
    },
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/test-resources/providers/microsoft.policyinsights/remediations/test-remediation",
    "name": "test-remediation",
    "type": "Microsoft.PolicyInsights/remediations"
}
```
Every IDs in the response is in lower cases, including the ID of the remediation itself.

**Comment by kenieva** [comment]
Hi @ArcturusZhang sorry for the delayed response. 

The ID being lowercased is by design. Thank you.

**Comment by tombuildsstuff** [comment]
@kenieva URI's, per the HTTP Specification are case sensitive.

Furthermore the ARM specification states they should be treated Case Insensitively at Request time and Case Sensitive in responses:

https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md
> The resource group names and resource names should be matched case insensitively. That means, for example, if a user creates a resource in resource group "rG1", and then calls a read operation on "RG1", the same resource should be returned even though the casing differs.
Additionally, the REST API MUST preserve the casing provided by the user. That means the API should return back the most recently specified casing to the client (and API MUST not normalize / return back a toupper/tolower form of the resource group or resource name, for example).

As such can this bug be reopened to track this bug in the API?

**Comment by kenieva** [comment]
We have created a work item for this bug; workitem 8448953. Thank you for your input.

**Comment by tombuildsstuff** [comment]
@kenieva is there a public issue tracking that we can direct people to for updates?

**Comment by tombuildsstuff** [comment]
ping @kenieva

**Comment by kenieva** [comment]
No updates at the current moment. We do not have a public issue tracking system at the moment.

**Comment by tombuildsstuff** [comment]
@kenieva ok thanks - is there an estimated ETA?

**Comment by tombuildsstuff** [comment]
@kenieva any update on when this'll be fixed?

**Comment by tombuildsstuff** [comment]
ping @kenieva

**Comment by kenieva** [comment]
Hi @tombuildsstuff, we do not have any updates on this work. It is still in the backlog and will go up for consideration and prioritization for the next semester.

**Comment by tombuildsstuff** [comment]
@kenieva thanks for the update - since this is still a bug, can we reopen this issue to ensure it's tracked?

**Comment by kenieva** [comment]
@tombuildsstuff we do not have a tracking system that we can share publicly. Since this request is accepted and in for consideration in the backlog, we are instructed to keep the item closed.

**Comment by katbyte** [comment]
@kenieva - why has this been closed when it is a valid, and open bug? should it not remain open until it has been solved so other people can find it? closed implies it has been fixed, as such could we please re-open it?

**Comment by tombuildsstuff** [comment]
ping @kenieva

**Comment by wuxu92** [comment]
Hi @kenieva is there any updates on this issue?

**Comment by tombuildsstuff** [comment]
ping @kenieva

**Comment by robinsk** [comment]
@kenieva I'm chiming in as a customer here. Because of this bug, we get diffs (and corresponding "updates") for all our terraform states that have policy remediations. It's confusing to our developers, because they didn't touch anything policy-related, and leads to time wasted troubleshooting this on a weekly basis.

While I am oblivious to the underlying complexity here, it _seems_ like it would be a fairly easy fix, and we would greatly appreciate if you could prioritize it.
