### ISSUE TITLE
Azure Container Service: `Custom` Orchestration Platforms

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#837]
:wave: hey

I'm aware I'm filing a ton of issues today (I've been meaning to open these for a while..) but this is the final one, so bear with me..

I've been using Container Service for a little while - and [added support for DCOS, Kubernetes and Swarm to Terraform](https://github.com/hashicorp/terraform/pull/10820). Whilst doing this I noticed that the field `Orchestration Platform` is an enum supporting the 3 values outlined above, plus a fourth which is undocumented `Custom` - which is available in both the Documentation and the SDK.

Whilst this is great - there's absolutely no documentation on what it is, or how it's intending to be used - it's also not available in the Portal currently - so I'm unable to work out what this is.

Would it be possible to get both some Documentation and some usage examples for how this is supposed to work please? :)

I've got an idea in mind for what this could be (Scale Sets but tuned for your Orchestration Platform of choice) - which could be really cool, but I've absolutely no idea. For the moment I've ignored it, but I'd like to add support :)

As usual - feel free to point me in another direction if this should be filed somewhere else.

Thanks!

**Comment by colemickens** [comment]
cc: @rgardler / @brendandburns: Not sure how we're wanting to handle this long/short-term.

@tombuildsstuff For now, there's no functionality to be gained by supporting it, if that helps.

**Comment by colemickens** [comment]
cc: @Azure/acs

**Comment by tombuildsstuff** [comment]
thanks @colemickens :)

**Comment by kirthik** [comment]
For microsoft folks - Right way of adding examples is following this approach -[using `x-ms-examples` extension](https://github.com/Azure/adx-documentation-pr/blob/master/tools/tools.md#swagger-model-validation)

**Comment by brendandburns** [comment]
This is intentionally left undocumented. We use this field for occasional testing that is Microsoft specific, we don't want users to use or rely on undocumented behaviors for this field.

We should perhaps document the fact that it is undocumented better :)

**Comment by salameer** [comment]
Closing based on @brendandburns comments, please feel free to reopen if you still have questions @tombuildsstuff :)
