### ISSUE TITLE
Search: Use endpoint for hostTemplate

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-rest-api-specs#8378]
Rather than `searchServiceName` and `searchDnsSuffix`, the `x-ms-parameterized-host` can be updated to a single endpoint param:

```
 "x-ms-parameterized-host": {
    "hostTemplate": "{Endpoint}",
    "useSchemePrefix": false,
    "parameters": [
      {
        "$ref": "#/parameters/Endpoint"
      }
    ]
  },
```

**Comment by xirzec** [comment]
This is based on https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Service/stable/2019-05-06/searchservice.json

**Comment by brjohnstmsft** [comment]
We will also need to make a similar change in searchindex.json, and ensure this gets propagated to the new 2019-05-06-preview spec when we create it.

**Comment by brjohnstmsft** [comment]
Since all Track 2 SDKs should target version 2019-05-06-Preview, I'm going to fix this issue there and freeze the Track 2 2019-05-06 spec as-is.
