### ISSUE TITLE
Search: mark required parameters as required

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-rest-api-specs#8379]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Data/stable/2019-05-06/searchindex.json

Several parameters are not marked as required, e.g. in `/docs/search.post.search`, the `SearchRequest` type doesn't have `search` marked as `required: true`.  There are similar problems with `SuggestRequest` (needs `search` and `suggesterName`) and `AutocompleteRequest`.

**Comment by brjohnstmsft** [comment]
Since all Track 2 SDKs should target version 2019-05-06-Preview, I'm going to fix this issue there and freeze the Track 2 2019-05-06 spec as-is.

**Comment by brjohnstmsft** [comment]
@xirzec I'm guessing these were left as optional because in Track 1, they were never meant to be exposed as part of the SDK surface area. However, since this spec is supposed to accurately document the REST API, I'll make the requested changes. Please let me know if you spot other similar issues.

**Comment by brjohnstmsft** [comment]
@xirzec I made the changes to `SuggestRequest` and `AutocompleteRequest`. However, the `search` parameter of `SearchRequest` is not required and defaults to `*` if not provided.

**Comment by xirzec** [comment]
@brjohnstmsft TIL, thanks for clarifying
