### ISSUE TITLE
Search: Add default responses for error cases

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-rest-api-specs#8380]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Data/stable/2019-05-06/searchindex.json

It's convention to specify a "default" error shape when "200" (or whatever specified success code) isn't matched.

For example:

```
  "default": {
    "description": "Error Response",
    "schema": {
      "$ref": "#/definitions/SearchError"
    }
  }
```

where `SearchError` has `code` and `message` properties would be a good start.

**Comment by brjohnstmsft** [comment]
Since all Track 2 SDKs should target version 2019-05-06-Preview, I'm going to fix this issue there and freeze the Track 2 2019-05-06 spec as-is.
