### ISSUE TITLE
PEM files should not be base64-encoded

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#8473]
The [`value`](https://github.com/Azure/azure-rest-api-specs/blob/f9af8f509ea13311d0c69d1dcc6170d6b8f61254/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L5137-L5141) property is described as:
> Base64 encoded representation of the certificate object to import. This certificate needs to contain the private key.

However, if sending a PEM file the content must not be base64 encoded or the server request fails. This is not clear from the docs or the recommended generated property name, `base64EncodedCertificate`.

Relates to https://github.com/Azure/azure-sdk-for-net/issues/9997, https://github.com/Azure/azure-sdk-for-java/issues/8226, https://github.com/Azure/azure-sdk-for-js/issues/7407, and https://github.com/Azure/azure-sdk-for-python/issues/9874 in the client SDKs.

**Comment by sebansal** [comment]
@heaths which document is being referred here?

**Comment by heaths** [comment]
It's part of the certificates swagger API, e.g. https://github.com/Azure/azure-rest-api-specs/blob/f9caf92527ccff06c5b66380e6f2b4f50f5e82b3/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.1/certificates.json.

**Comment by sebansal** [comment]
@jlichwa can you review this for repo update?

**Comment by jlichwa** [comment]
@sebansal work with Rashmi to see what should be an update for that value in certificate rest api and documentation. I can help you out with creating PR.

**Comment by sebansal** [comment]
![image](https://user-images.githubusercontent.com/62565144/88419180-8d262880-cd99-11ea-8f71-03da2a7d7e7e.png)

@heaths If i understand correctly, you seeking more clarity in the description

For context:
PEM files are base64 encoded. We support the following type of Import for PEM file format. A single PEM encoded certificate along with a PKCS#8 encoded, unencrypted key which has the following

-----BEGIN CERTIFICATE----- -----END CERTIFICATE-----

-----BEGIN PRIVATE KEY----- -----END PRIVATE KEY-----

Adding @rashmi-jha to correct me

**Comment by heaths** [comment]
I realize PEM *bodies* are already base64-encoded, but if the whole stream / buffer is (as the description suggestions), then the service fails. The description needs to clarify that PEM-encoded bodies should *not* be base64-encoded. Customers (we got issues) and even the SDK got this wrong because the documentation is not clear and makes it sound like all content should be base64-encoded regardless of the content type.

**Comment by RandalliLama** [comment]
@heaths this has been fixed.
