### ISSUE TITLE
[IOTHub] - Swagger Definition causing Ruby SDK generation to fail

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#856]
@rkmanda

The Nightly regen build for Ruby SDKs has failed today (Jan 10, 2016). On analysis, I found that the SDK generation has been failing for the [iothub.json](https://github.com/Azure/azure-rest-api-specs/blame/master/arm-iothub/2016-02-03/swagger/iothub.json). You can see the failure [here](http://azuresdkci.cloudapp.net/view/Ruby/job/Azure-sdk-for-ruby-regen-nightly/276/console ). The error is reproduced locally also. 

The root cause of the failure could be traced back to the following model [declaration](https://github.com/Azure/azure-rest-api-specs/blame/master/arm-iothub/2016-02-03/swagger/iothub.json#L1558). 

```
"EventHubConsumerGroupsListResult": {
      "description": "The JSON-serialized array of Event Hub-compatible consumer group names with a next link.",
  "type": "object",
  "properties": {
    "value": {
      "description": "The array of Event Hub-compatible consumer group names.",
      "type": "array",
      "items": {
          "type": "string"
      }
    },
    "nextLink": {
      "description": "The next link.",
      "type": "string",
      "readOnly": true
    }
  }
}
```

Here under "properties"/"value", the "type" is set to "array". But, under "items", the only available details is set to "type": "string". In the autorest, as a result, Model.ItemType is set to null and accessing Model.ItemType.Name gives a null exception. 

But, if you see a similar model - ["IotHubDescriptionListResult"](https://github.com/Azure/azure-rest-api-specs/blame/master/arm-iothub/2016-02-03/swagger/iothub.json#L1673), the definition is:

```
"IotHubDescriptionListResult": {
  "description": "The JSON-serialized array of IotHubDescription objects with a next link.",
  "type": "object",
  "properties": {
    "value": {
      "description": "The array of IotHubDescription objects.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/IotHubDescription"
      }
    },
    "nextLink": {
      "description": "The next link.",
      "type": "string",
      "readOnly": true
    }
  }
}
```
Here under "properties"/"value"/"items", the reference is set correctly to IotHubDescription. As a result, Model.ItemType is set correctly and no exception is thrown. 

So, definition of the EventHubConsumerGroupsListResult has to be fixed with the reference to the correct object (similar to the IotHubDescriptionListResult result). Since only the RP has the required knowledge on the expected object structure from the service, I am requesting you to make the necessary changes. 

CC: @amarzavery @veronicagg @vishrutshah @salameer

**Comment by lmazuel** [comment]
This is actually a list of string, and it's working great in Python:
- Our list wrapper (you can [str] <=> list of strings): https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-iothub/azure/mgmt/iothub/models/str_paged.py
- Our unit tests: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/test_mgmt_iothub.py#L147
- The record of this call: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt/tests/recordings/test_mgmt_iothub.test_iothub_consumer_group.yaml#L394

**Comment by lmazuel** [comment]
Full disclosure, just in case it's related somehow to this, we have a Python issue exactly at this point: https://github.com/Azure/autorest/issues/1685
So in Python, the code is generated, but with a tiny mistake on the class name. Maybe this is the same root issue in Ruby, but raise instead of generating bad code
FYI @fearthecowboy @annatisch

**Comment by sarangan12** [comment]
Update:

I have synched up with @fearthecowboy and confirmed the JSON is indeed correct. Based on our offline discussion, I have created a PR in the Ruby SDK generation part to handle the error. Link: https://github.com/Azure/autorest/pull/1711 

So, I am closing this issue.
