### ISSUE TITLE
[RecoveryServicesBackup] Inconsistent values for internalConstructors across composite swagger files

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-rest-api-specs#858]
The RecoveryServicesBackup has a compositeswaggerfile - [compositeRecoveryServicesBackupClient.json](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/compositeRecoveryServicesBackupClient.json). This refers to 2 files:

1. [recoveryservicesbackup.json](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/2016-06-01/swagger/recoveryservicesbackup.json)
2. [registeredIdentities.json](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/2016-06-01/swagger/registeredIdentities.json)

In these files you can see in the first file, the internalConstructors value is set to [false](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/2016-06-01/swagger/recoveryservicesbackup.json#L7). Whereas, in the second file, it is set to [true](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/2016-06-01/swagger/registeredIdentities.json#L7). 

This is inconsistent and causes the SDK generation process to break across all languages. Please fix this. 

@fearthecowboy @amarzavery @veronicagg @vishrutshah @salameer @markgalioto @dragonfly91

**Comment by lmazuel** [comment]
Duplicate with https://github.com/Azure/azure-rest-api-specs/issues/831. This proves that something must be done...
