### ISSUE TITLE
Missing docs for catalogapi.azure.com

### ISSUE THREAD

**Issue by ad-m** [Azure/azure-rest-api-specs#8590]
I have notice in panel that API ```catalogapi.azure.com``` is generally available. Documentation for that API is not available in this repository. Could you add missing documentation?

**Comment by ingave** [comment]
There's some info here: https://otx.alienvault.com/indicator/hostname/catalogapi.azure.com?utm_medium=InProduct&&utm_source=ThreatCrowd
But it's not an API that is owned by our team.
