### ISSUE TITLE
SQL DB create mode question

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#8616]
Hi, I use sql version 2017-10-01-preview.
1. In recovery mode database creation, as [recovery example](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-10-01-preview/examples/CreateDatabaseRecoveryMode.json),I could not get recoverable Databases, Is it available on 2017-10-01-preview? How to create a recoverable DB?:
{
    "error": {
        "code": "NoRegisteredProviderFound",
        "message": "No registered resource provider found for location 'eastus2' and API version '2017-10-01-preview' for type 'servers/recoverableDatabases'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview'. The supported locations are 'australiacentral, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2, francecentral, germanywestcentral, japaneast, japanwest, koreacentral, koreasouth, northcentralus, northeurope, norwayeast, southafricanorth, southcentralus, southindia, southeastasia, switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2'."
    }
}

2. In restore mode, the "sourceDatabaseDeletionDate" seems required instead of optional in [example restoremode2](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-10-01-preview/examples/CreateDatabaseRestoreMode2.json). I tried to restore a deleted DB. It always returns error.
![image](https://user-images.githubusercontent.com/56525716/76048346-7c1e7b80-5fa0-11ea-9cf7-0da3691fc880.png)
{
    "error": {
        "code": "InvalidDroppedDatabase",
        "message": "Source database 'dbPITR' dropped on '3/6/2020 1:52:00 AM' does not exist on server 'yupsqlserver' within the supported recovery period."
    }
}

Could you provide some help?

**Comment by yupwei68** [comment]
Another question is does this version support 'computer tier' in 'general purpose'? If yes, which field?
![image](https://user-images.githubusercontent.com/56525716/76195199-c2830d00-6222-11ea-9506-21ed76e6bc6d.png)

**Comment by azureSQLGitHub** [comment]
I can take a look at this
