### ISSUE TITLE
[Resources/resources] Consider adding cross referencing documenatation

### ISSUE THREAD

**Issue by marstr** [Azure/azure-rest-api-specs#862]
Original Issue: [Azure-SDK-for-Go 491](https://github.com/Azure/azure-sdk-for-go/issues/491)

At the moment there is no help for people to "See Also" in the documentation. At times this leads to confusion between similar functions with slightly different names or vice versa.

For this particular instance, it is suggested that we cross-reference the functions for retrieving all resource groups and retrieving the resources in a resource group.

**Comment by ravbhatnagar** [comment]
Wont fix. So far there is not much customer feedback on this. @kirthik - please close this.
