### ISSUE TITLE
Support for Saved Searches (functions) in Log Analytics workspaces

### ISSUE THREAD

**Issue by aristosvo** [Azure/azure-rest-api-specs#8683]
### Issue
I want to add Saved Searches (functions) in the [Azure TerraForm provider](https://github.com/terraform-providers/terraform-provider-azurerm), but due to the lack of fields in the REST API specs the [Go SDK](https://github.com/Azure/azure-sdk-for-go/blob/master/services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go) does not contain the property I want to use:
- functionAlias
### Query
```bash
curl --location --request PUT 'https://management.azure.com/subscriptions/<<SUBSCRIPTION>>/resourcegroups/<<RESOURCEGROUP>>/providers/Microsoft.OperationalInsights/workspaces/<<WORKSPACE>>/savedSearches/test-6?api-version=2015-03-20' \
--header 'Authorization: Bearer <<TOKEN>>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "properties": {
    "category": "Saved Search Test Category",
    "displayName": "Create or Update Saved Search Test",
    "query": "Heartbeat | summarize Count() by Computer",
    "version": 2,
    "functionAlias": "test-function-alias",
    "tags": [
      {
        "name": "Group",
        "value": "Computer"
      }
    ]
  }
}'
```
### Definition file 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2015-03-20/OperationalInsights.json

**Comment by shemers** [comment]
We are working to release a new SDK version.

**Comment by aristosvo** [comment]
@shemers Are you talking about the 2020-03-01 preview API? Or is there something else?

If there's something like a beta version: I'd love to give feedback

**Comment by shemers** [comment]
@yossi-y can you please follow up here.

**Comment by aristosvo** [comment]
There is an [implementation](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8253) for Terraform done based on the preview for Saved Searches.

Thanks a lot @shemers !
