### ISSUE TITLE
[Sql] Missing required parameters | Sql Server Firewall create operation

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#869]
Should parameters `startIpAddress` & `endIpAddress` be marked as required for creating or updating sql server firewall rules? @ [firewallRules.json#L182](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2014-04-01/swagger/firewallRules.json#L182)

Not Including `endIpAddress` is returning following server response: 
```
{
"code": "BadRequest",
"message": "Invalid value provided for parameter: endIpAddress",
"target": null,
"details": [],
"innererror": [],
}
```

@misosi-msft / @nathannfan / @mmacy Could you please take a look? Thanks

**Comment by jaredmoo** [comment]
Thanks for reporting this issue. Looks like @nathannfan fixed it in commit 229323f52 .
