### ISSUE TITLE
[Compute] New API for Disk Attachments

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#8693]
👋 

Currently to attach a Data Disk to a Virtual Machine requires submitting this as a part of the Virtual Machine payload (e.g. a appending to the list of data disks).

Whilst this works when you want to define the Virtual Machine definition in a single payload, unfortunately this makes it challenging when breaking this apart into multiple payloads to provide a better user experience - which means that we've had to fake this via calling the API sequentially using locks to ensure multiple disk attachments happen sequentially.

This functionality already exists for the DevTest Labs Service - which has an endpoint to [Attach](https://docs.microsoft.com/en-us/rest/api/dtl/virtualmachines/adddatadisk)/[Detach](https://docs.microsoft.com/en-us/rest/api/dtl/virtualmachines/detachdatadisk) Data Disks - in short we're looking for the same thing for regular Virtual Machines.

As such would it be possible to introduce an API for managing Data Disk Attachments, similar to the ones provided by [AWS](https://docs.aws.amazon.com/cli/latest/reference/ec2/attach-volume.html) and [Google](https://cloud.google.com/sdk/gcloud/reference/compute/instances/attach-disk)?

Thanks!

**Comment by Drewm3** [comment]
Thanks for the feedback. I have moved this over to UserVoice feedback channel so that it is captured along with the other feature requests. Please up vote this item: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/39952540-api-for-disk-attachments-that-does-not-require-upd

**Comment by jigold** [comment]
I'd also like to up vote this item. Unfortunately the link to the forum in the comment above is broken.

**Comment by broncofan** [comment]
https://feedback.azure.com/d365community/idea/97a67488-bf25-ec11-b6e6-000d3a4f0f1c
Link for anyone wanting to upvote.
