### ISSUE TITLE
`creationTime` in `timeseriesinsights` is in wrong format and is causing SDK malfunctions

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#8702]
[Original issue](https://github.com/Azure/azure-sdk-for-go/issues/7824)

The problematic field is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2018-08-15-preview/timeseriesinsights.json#L1199)

The default format of date-time is `RFC3339Nano` however the value being sent over-the-wire is `RFC1123`, see the `creationTime` field in the response below:
```
{
    "sku": {
        "name": "S1",
        "capacity": 1
    },
    "kind": "Standard",
    "location": "eastus2",
    "tags": {},
    "properties": {
        "dataRetentionTime": "P30D",
        "storageLimitExceededBehavior": "PurgeOldData",
        "creationTime": "Tue, 10 Mar 2020 22:21:46 GMT",
        "provisioningState": "Succeeded",
        "requestApiVersion": "2018-08-15-preview",
        "dataAccessId": "dataID",
        "dataAccessFqdn": "dataFQDN",
        "partitionKeyProperties": null
    },
    "id": "resourceId",
    "name": "resourceName",
    "type": "Microsoft.TimeSeriesInsights/Environments"
}
```

**Comment by jiasli** [comment]
This also causes problem in Python SDK.

In the rest spec of timeseriesinsights, `creationTime` is defined as 

https://github.com/Azure/azure-rest-api-specs/blob/b7a0dc7872810dc0659f16ceaf54c4205b7ba8b4/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2018-08-15-preview/timeseriesinsights.json#L1199

This makes Python SDK being generated as

https://github.com/Azure/azure-sdk-for-python/blob/7a1fdd3f52de6158a266895e461ebc3c96def60c/sdk/timeseriesinsights/azure-mgmt-timeseriesinsights/azure/mgmt/timeseriesinsights/models/_models_py3.py#L2129

```py
'creation_time': {'key': 'properties.creationTime', 'type': 'iso-8601'},
```

For GET API, the returned `creation_time` is actually in RFC 1123 which doesn't comply with the spec.

For PUT API, `creation_time` returned from the server differs depending on the status code:

- For a newly created environment (PUT request with response status code 201), `creationTime` is in ISO 8601:

    ```
    "creationTime":"2020-03-17T10:16:15+00:00"
    ```
    This is because (according to service team) the response is not being deserialized from storage so it isn’t going through the conversion.

- For an existing environment (PUT request with response status code 200), `creationTime` is in RFC 1123:

    ```
    "creationTime":"Tue, 17 Mar 2020 10:16:15 GMT"
    ```

 
The correct value for RFC 1123 datetime in rest spec should be:
```
"format": "date-time-rfc1123"
```

**Comment by katbyte** [comment]
@ArcturusZhang @akning-ms - any progress on this? we are blocked from implementing IOT time series in tf until this is fixed.

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang @akning-ms - any progress on this? we are blocked from implementing IOT time series in tf until this is fixed.

Hi @katbyte the service team told me that they have fixed this on the service side, now the returned creationTime could comply with ISO-8601 as expected.
Therefore this issue should have been fixed without any swagger changes or SDK upgrade. Could you please have a check if this issue remains?

**Comment by riserrad** [comment]
Hi @ArcturusZhang and @katbyte ,

The issue is now fixed on the service side. You may perform tests to validate it if you want.

We can close the issue.

**Comment by ArcturusZhang** [comment]
Closing this issue...
Hi @katbyte if this issue persist, please feel free to reopen, thanks!
