### ISSUE TITLE
Wrong property type in Portal

### ISSUE THREAD

**Issue by YalinLi0312** [Azure/azure-rest-api-specs#8724]
The dashboard [properties](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/portal/resource-manager/Microsoft.Portal/preview/2019-01-01-preview/portal.json#L414) are expected to be "integer" not "number".

**Comment by raych1** [comment]
@jjbfour , I saw you updated the portal swagger last time and can you please check if this is swagger defect?

**Comment by raych1** [comment]
@msHich , could you have a look at this issue?

**Comment by YalinLi0312** [comment]
This issue has fixed by pr: https://github.com/Azure/azure-rest-api-specs/pull/8829.
