### ISSUE TITLE
SecurityInsights REST API OData filter by labelName 

### ISSUE THREAD

**Issue by shueseman** [Azure/azure-rest-api-specs#8755]
I am trying to filter Sentinel Incidents via the labelName property.   I think I am doing the correct query but I am not getting any results.

Here is my rest query:

GET https://management.azure.com/subscriptions/{subID}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/incidents?api-version=2019-01-01-preview&$filter=properties/labels/any(d:d/labelName eq 'Test')

I have an incident with a tag (label/labelName) of "Test".    I see the label if I query that incident directly, but I cannot query for all incidents with this label.     I have a sense that the OData collection functions all() and any() are not fully implemented, but maybe I am just doing it wrong.

In addition to this query, is there a reference for what OData operations are available in the Azure APIs?  I can infer that $filter, $top, $skip and $orderBy are available via the SecurityInsights.json file, and when I tried $search, nothing happens.   However, an official reference would be helpful.

**Comment by Yaniv-Shasha** [comment]
Hi shueseman 
the sentinel team that own this endpoint had a bug on this endpoint that fixed in the beginning of April.
id you will use this Odata filter 

properties/labels/any(i: i/labelName eq 'yaniv')

its should work and return the relevant incidents.

**Comment by shemers** [comment]
@shueseman archiving as issue was resolved.
