### ISSUE TITLE
Do Azure Webjobs or Azure Functions Specs Exist?

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-rest-api-specs#880]
I know these services are built on top of Azure App Service, so I'm guessing the spec for App Service applies to some degree.  However, want to know if there's a plan to add a separate spec for them.

**Comment by kirthik** [comment]
@naveedaz : Could you please help answer the question?

**Comment by naveedaz** [comment]
We currently do not have separate specs for either. 
1. Azure WebJobs are KUDU functionality. We are currently evaluating either KUDU specific swagger spec or exposing first level APIs in the management surface. 
2. Azure functions are built on top of App Service so functions for the most part can be managed with the current management APIs. We do not have any solid plans of exposing functions specific swagger yet. 
I'll update as and when we have more concrete plans.

**Comment by kirthik** [comment]
closing this thread since @naveedaz provided answers. @solvingJ : If you are blocked by lack of swagger specs for these services, please file a separate tracking bug.
