### ISSUE TITLE
Model Validation Error for x-ms-examples with inline example

### ISSUE THREAD

**Issue by alexhcheng** [Azure/azure-rest-api-specs#8844]
I'm getting an error during model validation step which i can't tell from the log what is the issue.

using this spec: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md

https://dev.azure.com/azure-sdk/public/_build/results?buildId=333304&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

``` bash
fatal error: xmsExampleFunc is not a function, {}
##[error]Bash exited with code '1'.
```
I have the example inline with the rest of the swagger api.  Here is the full PR https://github.com/Azure/azure-rest-api-specs/pull/8810

``` json
        "x-ms-examples": {
          "Get Status": {
            "parameters": {
              "api-version": "v1.0-preview.1",
              "subscriptionId": "EA19050C-51FC-4B55-84E5-9EA7283601DA",
              "resourceGroupName": "TestResourceGroup",
              "jobId": "727BF148-F327-47A0-9481-ABAE6362F11E"
            },
            "responses": {
              "200": {
                "headers": {},
                "body": {
                  "jobId": "727bf148-f327-47a0-9481-abae6362f11e",
                  "createdDateTimeUtc": "2020-03-26T00:00:00Z",
                  "lastActionDateTimeUtc": "2020-03-26T01:00:00Z",
                  "jobStatus": {
                    "overallStatus": 2,
                    "totalDocuments": 10,
                    "failedDocuments": 1,
                    "succeedDocuments": 9,
                    "inProgressDocuments": 0,
                    "notYetStartedDocuments": 0
                  }
                }
              },
              "400": {
                "headers": {},
                "body": {
                  "error": {
                    "code": 0,
                    "message": "Some argument is incorrect"
                  }
                }
              },
              "404": {
                "headers": {},
                "body": {
                  "error": {
                    "code": 1,
                    "message": "Job id not found"
                  }
                }
              }
            }
          }
        }
```

**Comment by alexhcheng** [comment]
this is the latest build with that issue.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=334774&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&j=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742&t=43324f1f-6724-5d61-785f-f0ac9fd256a1

if i use $ref to the file with the exact content, it passes validation fine.

**Comment by alexhcheng** [comment]
[v1.0.zip](https://github.com/Azure/azure-rest-api-specs/files/4396548/v1.0.zip)

**Comment by raych1** [comment]
Thanks @alexhcheng for raising this. 
If using `x-ms-examples` extension, the example must be at separated JSON file and reference it in swagger. Please refer [Where do the examples live](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md#where-do-the-examples-live) for details.

If you want to define example inline of swagger file, please refer [example-object-in-response](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#example-object) for details.

The former way is recommended approach and almost all of current swagger specs use it.

**Comment by alexhcheng** [comment]
thank you.  missed that part in the spec.  Thanks for the clarification.
