### ISSUE TITLE
CustomImageSearch, invalid JSON pointer

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#8859]
Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@autorest/python' (5.0.0-dev.20200326.1->5.0.0-dev.20200326.1)
   Loading AutoRest extension '@autorest/modelerfour' (4.12.276->4.12.276)
  Error: Invalid JSON pointer: file:///C:/Users/lmazuel/Git/azure-rest-api-specs/specification/cognitiveservices/data-plane/Common/Parameters.json/parameters/GlobalEndpoint

**Comment by lmazuel** [comment]
Also CustomWebSearch

**Comment by daviwil** [comment]
This seems to be a bug in AutoRest Core, I believe the $ref is specified correctly in the Swagger. Working on a fix now.

**Comment by MiYanni** [comment]
I've added an issue to Azure/autorest for this issue:
https://github.com/Azure/autorest/issues/3498

I'm closing this issue since it is related to AutoRest Core and not the specs repo.
