### ISSUE TITLE
Face recognizer, invalid $ref

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#8860]
Error: $ref to original location 'file:///C:/Users/lmazuel/Git/azure-rest-api-specs/specification/cognitiveservices/data-plane/Common/Parameters.json#/components/parameters/ImageUrl' is not found in the new refs collection

**Comment by dipidoo** [comment]
this $ref is correct in Face.json, i.e. <path>#/parameters/ImageUrl. The refpath you mentioned is where it would have been in OASv3. perhaps this error is on the tooling side?
