### ISSUE TITLE
[Azure Monitor Management]  Missing required parameters on operation "AlertRules_CreateOrUpdate"

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#887]
As per the documentation https://msdn.microsoft.com/en-us/library/azure/dn933805.aspx operation of `CreateOrUpdate` also requires following parameters:

`condition`
`actions`

but they are not marked as "required" in the swagger definition at [arm-insights/2016-03-01/swagger/insightsManagementClient_AlertRules.json#L19](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-insights/2016-03-01/swagger/insightsManagementClient_AlertRules.json#L19)

@gucalder Could you please validate this?

**Comment by vishrutshah** [comment]
@gucalder Could you please verify?

**Comment by gucalder** [comment]
Actions is not required. It is possible to have an alert rule without actions.
Condition is required. I am fixing this in the monitor folder as we intend to deprecate the insights folder at some point in time.

**Comment by gucalder** [comment]
BTW: The referred documentation is the previous version, not the version auto generated from the spec. That documentation was manually created, it will probably have some bugs like the one in "required Actions."

**Comment by johnkemnetz** [comment]
@kirthik can you close this since it is being fixed in the new folder?

**Comment by kirthik** [comment]
@gucalder and @johnkemnetz : please link this bug in the commit id. That should automatically close the bug when commit is merged. If it is already merged, please provide it here, I will close the bug then.

**Comment by gucalder** [comment]
Actions is actually a very special case. I'll need to walk through the code with the devs to mark this as required.
I am marking only condition for the moment, and then I'll review actions later. In some cases calls with Actions = null work as we are doing in our PowerShell cmdlets.
