### ISSUE TITLE
Missing field in search/2020-03-13

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#8883]
In the latest api-version (2020-03-13) of search, a [nextLink](https://github.com/Azure/azure-rest-api-specs/blob/c1ffffc63cc67b1780b4e0a41d0ce28520d9208d/specification/search/resource-manager/Microsoft.Search/stable/2020-03-13/search.json#L234) is introduced to the `QueryKeys_ListBySearchService` operation, but the corresponding response model is not modified to possess a field named `nextLink` ([here](https://github.com/Azure/azure-rest-api-specs/blob/c1ffffc63cc67b1780b4e0a41d0ce28520d9208d/specification/search/resource-manager/Microsoft.Search/stable/2020-03-13/search.json#L1281)).

This issue is currently blocking the generation of go SDK.

**Comment by brjohnstmsft** [comment]
FYI @tjacobhi

**Comment by lrxtom2** [comment]
Hi, I am working blocked by this issue, could anyone could please fix that? Thanks for that!

**Comment by tjacobhi** [comment]
This was fixed in this PR https://github.com/Azure/azure-rest-api-specs/pull/9085. Please let me know if you are still having trouble.

**Comment by ArcturusZhang** [comment]
Closed since it should have been resolved.
