### ISSUE TITLE
Microsoft.Media 2019-05-01-preview folder contains 2018-07-01 API version

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-rest-api-specs#8894]
See https://github.com/Azure/azure-rest-api-specs/blob/6049cf3aaf88d57c587157f85d658a3782abe907/specification/mediaservices/resource-manager/Microsoft.Media/preview/2019-05-01-preview/Accounts.json#L9 for example

This is causing issues for schema autogeneration (see https://github.com/Azure/azure-resource-manager-schemas/pull/927#issuecomment-606484394)

**Comment by giakas** [comment]
This is one of the older preview releases where we have duplicate files, in the newer releases we are poitning those files from the correct location.

https://github.com/Azure/azure-rest-api-specs/tree/6049cf3aaf88d57c587157f85d658a3782abe907/specification/mediaservices/resource-manager/Microsoft.Media/preview/2019-09-01-preview

We have not touched it as its an older release? is this blocking you? need help from SDK team, what is the next steps, should we cleanup older releases, even though we will not have any new releases on that SDK?
