### ISSUE TITLE
Unable to compile the generated code

### ISSUE THREAD

**Issue by navaneeth** [Azure/azure-rest-api-specs#8904]
I am using API version `2019-07-01`.

```
▶ cat sample.yaml             
--- 
# it's the same options as command line options, just drop the double-dash!
input-file: compute.json
namespace: sdk
output-folder: output
```
I am running autorest like:

```
▶ autorest --go sample.yaml
```
When I compile the generated file, I am getting the following error:

```
cloud/lazure/sdk/availabilitysets.go:93:13: not enough arguments to return
cloud/lazure/sdk/availabilitysets.go:93:26: client.Send undefined (type AvailabilitySetsClient has no field or method Send)
cloud/lazure/sdk/availabilitysets.go:169:13: not enough arguments to return
cloud/lazure/sdk/availabilitysets.go:169:26: client.Send undefined (type AvailabilitySetsClient has no field or method Send)
```

**Comment by MyronFanQiu** [comment]
@navaneeth Hi. I think this issue should be filed in https://github.com/Azure/autorest.go. I invited go sdk owner to take a look.

**Comment by ArcturusZhang** [comment]
Hi @navaneeth if you are using `autorest.go` version greater than v2.1.142, you must use the corresponding go-autorest version greater than v13.4.0 or any equivalent module version (for instance `github.com/Azure/go-autorest/autorest v0.10.0`).

Please take this [issue](https://github.com/Azure/azure-sdk-for-go/issues/7757) as reference

**Comment by ArcturusZhang** [comment]
Closed since this should not be an issue
