### ISSUE TITLE
WindowsIot Swagger needs to update "Create" operation with required location parameter 

### ISSUE THREAD

**Issue by mozehgir** [Azure/azure-rest-api-specs#8945]
The property "location" defined in swagger is a required parameter for Create and Update. However not depicted in the swagger. 
If you try sending a request as per the swagger definition to create a service, the service responds with a 400 bad request and asks for "location" in request parameters.

**Comment by mozehgir** [comment]
As reported by @dw511214992

**Comment by dingmeng-xue** [comment]
Hi, is there any update?

**Comment by adithyaj** [comment]
@dingmeng-xue  I believe this [PR ](https://github.com/Azure/azure-rest-api-specs/pull/12094) that has been merged now takes care of this issue?

**Comment by dw511214992** [comment]
it's fixed.
