### ISSUE TITLE
Azure blob storage REST API error on invalid API version is misleading

### ISSUE THREAD

**Issue by toraritte** [Azure/azure-rest-api-specs#8947]
<sup>This probably doesn't belong here, but couldn't find a better place to report it.</sup>

Ran into the same issue as the poster of [this Stackoverflow question](https://stackoverflow.com/questions/51948786/azure-storage-rest-api-call-invalid-header-x-ms-version):

```xml
<Error>
    <Code>InvalidHeaderValue</Code>
    <Message>The value for one of the HTTP headers is not in the correct format.
RequestId:d39d2cad-301e-009e-1546-3940de000000
Time:2018-08-21T11:58:14.2369850Z</Message>
   <HeaderName>x-ms-version</HeaderName>
   <HeaderValue>2017-01-19</HeaderValue>
</Error>
```
It says that the `x-ms-version` header "_is not in the correct format_", but the actual problem is that not all API versions are supported. The [Versioning for the Azure Storage services](https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services) seems to always suggest the latest supported one.

Thank you!

**Comment by tasherif-msft** [comment]
Hi @toraritte we're very sorry that this got lost in our backlog. Is your issue still persisting?  I can look into it if it is.

**Comment by tasherif-msft** [comment]
Hi @toraritte, in most cases our services will support the most released version. In some rare instances do you need to set a previous api version. This happens due to delays in some of our rollouts. We can document this and recommend users to set api_version if this issue is encountered.
