### ISSUE TITLE
DataFactory incorrect enum definition

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#8958]
Enum should be a primary type:
https://github.com/Azure/azure-rest-api-specs/blob/3ae479ed7de039ecdd89d14c22a43fce5df75bfd/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Dataset.json#L475-L487

type lin 478 should be `string`, this will be refused by autorest now.

This pattern is seen in several places in this file. 

Side note: I'm doing a linter rule request as well

**Comment by lmy269** [comment]
@shawnxzq to take a look

**Comment by shawnxzq** [comment]
This is the current practice in ADF, we need to find way to keep backward compatibility in ADF, offline talking this with @RodgeFu now.

**Comment by RodgeFu** [comment]
@lmazuel , this property in ADF is special, it can accept an enum or an Expression object, do you know how we can achieve it in swagger? thanks.

**Comment by lmazuel** [comment]
Beware to not mixed-up two things:
- An enum should have a simple type (int, string, etc.)
- A property could be of type or enum, or type object

This is not exactly the same level of abstraction

**Comment by RodgeFu** [comment]
@Imazuel, thanks for the reply. Yes, that's my understanding too. 

@shawnxzq , could you confirm my question above? i remember i tried to use .net SDK and pass string there which still work

**Comment by shawnxzq** [comment]
@lmazuel We have a business requirement that we want to property to be a enum value. However, the enum value could be parameterized, and we use object to define parameterized expressions, is there a way with current swagger to support this requirement?

**Comment by lmazuel** [comment]
Hi @shawnxzq could you describe in JSON examples what do you mean? I have a hard time to visualize it in text. Thanks!

**Comment by shawnxzq** [comment]
@lmazuel In our app model, any property can be defined as follows

**Comment by lmazuel** [comment]
Hi @shawnxzq 
Sorry I still don't get it :(. Let me even more clear:
```json
    "DatasetZipDeflateCompression": {
      "x-ms-discriminator-value": "ZipDeflate",
      "description": "The ZipDeflate compression method used on a dataset.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/DatasetCompression"
        }
      ],
      "properties": {
        "level": {
          "description": "The ZipDeflate compression level.",
          "$ref": "#/definitions/CompressionLevel"
        }
      }
    },
    "CompressionLevel": {
      "title": "Microsoft.Azure.Management.DataFactories.Models.CompressionLevel",
      "description": "All available compression levels.",
      "type": "object",
      "enum": [
        "Optimal",
        "Fastest"
      ],
      "x-ms-enum": {
        "name": "DatasetCompressionLevel",
        "modelAsString": true
      }
    },
```

Can you give an example of JSON from the server that map `DatasetZipDeflateCompression`, where the level property is not a string?

**Comment by shawnxzq** [comment]
@lmazuel, the "level" property could be defined as follows in our app model, which means the "level" is an ADF expression, the the value resolved from the expression is the enum value defined, this is our current practice. However, it might not be straightforward to swagger since the it is not responsible for resolving ADF expression.

"level": {
"value": "@pipeline().levelValue",
"type": "Expression"
}

**Comment by shawnxzq** [comment]
@lmazuel Am I clear and anything else do you want? Thanks!

**Comment by shawnxzq** [comment]
@lmazuel Any thoughts? Thanks!
