### ISSUE TITLE
[Azure Monitor] UsageMetrics list throws 400 on resource uri

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#896]
list operation on the resource-uri `/subscriptions/xxxxx-xxxx-xxx-xxxx-xxxx/resourceGroups/vishrutrg/providers/microsoft.compute/virtualmachines/vmtests1` with api-version `2014-04-01` throws following errors:

**Error:**
```
No registered resource provider found for location 'eastus' and API version '2014-04-01' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.
```

While trying to use it with list `api-versions` on the error, I receive the following errors:

```
{
"error": {
"code": "BadRequest",
"message": "The request URL is not valid."
}
}
```

@gucalder Do we need to support new api version or document more what's supported via api-version "2014-04-01"? 

**cc:**
@lmazuel

**Comment by lmazuel** [comment]
@vishrutshah I already had this conversation with the Monitor team, VM does not support UsageMetrics currently. WebApp or DocDB does. It's why my example is using WebApp:
http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-monitor.html#quotas

So, it's not a Swagger issue, but a RestAPI sad error message.

**Comment by vishrutshah** [comment]
@lmazuel Thanks for letting me know. I tried with Web App and it works. 

I'll close this issue as not on swagger but still minor feedback for @gucalder regarding the error message. 

Thanks
