### ISSUE TITLE
Arm-Logic Swagger Resource Properties should be read-only

### ISSUE THREAD

**Issue by maxshao96** [Azure/azure-rest-api-specs#898]
azure-rest-api-specs/arm-logic/2016-06-01/swagger/logic.json
logic.json swagger #/definitions/Resource properties should have { "read-only": true } attributes

**Comment by amarzavery** [comment]
@pankajsn - Please resolve this issue.

**Comment by pankajsn** [comment]
@Amar Zavery<mailto:amzavery@microsoft.com>
JFYI This is logged by our team only for tracking purpose.

**Comment by amarzavery** [comment]
@pankajsn - Good to know that it is logged by your team. Please fix it in this PR.

**Comment by pankajsn** [comment]
fixed

**Comment by jhendrixMSFT** [comment]
Resolved in https://github.com/Azure/azure-rest-api-specs/pull/891.
