### ISSUE TITLE
[Compute API] Breaking Behavioural Change - Delta updates to Tags are not detected

### ISSUE THREAD

**Issue by tombuildsstuff** [Azure/azure-rest-api-specs#8982]
:wave:

It appears there's a Breaking Behavioural Change to the Compute API when performing a Delta update where Tags are now incorrectly processed.

When performing a Delta (e.g. PATCH) update on a Virtual Machine Scale Set (and potentially other Resources within this Resource Provider, I've not checked) - when tags differ in casing for only the keys, the API no longer updates the tags as it did previously.

This is in turn the root-cause of this API issue: https://github.com/Azure/azure-rest-api-specs/issues/8952 - to give an example using API Version `2019-07-01`.

When adding tags to an existing Virtual Machine Scale Set:

```
PATCH /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
  ...
	"tags": {
		"Hello": "World"
	}
}
```

and then retrieving those - we get the correct tag returned:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
  ...
	"tags": {
		"Hello": "World"
	},
  ...
}
```

---

At this point if we change the casing of the tag:

```
PATCH /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
	"tags": {
		"hello": "World"
	}
}
```

and then retrieve it:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
  ...
	"tags": {
		"Hello": "World"
	},
  ...
}
```

Note the incorrect casing for the Tag here.

---

When updating the value for this key:

```
PATCH /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
	"tags": {
		"hello": "World2"
	}
}
```

the API then detects & correctly performs these changes:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
  ...
	"tags": {
		"hello": "World2"
	},
  ...
}
```

The tags are also correctly updated when adding a secondary tag:

```
PATCH /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
  ...
	"tags": {
		"Hello": "World2",
		"Upper": "Case"
	}
}
```

and subsequently retrieving it:

```
GET /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-resources/providers/Microsoft.Compute/virtualMachineScaleSets/example-vmss?api-version=2019-07-01

{
	"tags": {
		"Hello": "World2",
		"Upper": "Case"
	},
}
```

---

This appears to be a bug regarding the Delta updates of Tags present in at least the Virtual Machine Scale Set API - but presumably this logic is shared across the Compute Resource Provider and so also is present in these other Resources.

Best we can tell this is a breaking behavioural change in the API - since we've used key-sensitivity for tag updates in the past - as many customers have case-sensitive scripts for tags.

Since this affects version `2019-07-01` of the Compute API - presumably this behaviour is present in every version of the API since too, and potentially in other Resources within this Resource Provider?

Thanks!

**Comment by Drewm3** [comment]
Let me loop in @vladimirjoanovic on this issue. I believe ARM handles the updating of the tags instead of the RPs. So if that is correct, then this needs to be investigated by the ARM team.

**Comment by hamidtirmizi** [comment]
Most of the time, ARM is responsible for informing the RP about changes to tags (so if ARM doesn’t see a change, the RP is unlikely to see a change), so ARM plays a key role.

Tag values are case sensitive.
Tag names are case insensitive, i.e. lookup does not care about the case. So,
-	When updating the case for just the tag name, ARM treats it as a no-op, and you see no effect.
-	When updating the tag name case AND the tag value, it is no longer a no-op, ARM replaces the pair in the dictionary.

**Comment by tombuildsstuff** [comment]
@hamidtirmizi unfortunately that differs from every Azure API I've used, taking Resource Groups as an example - when updating just the casing of the key of a Tag (e.g. `hello` -> `Hello`) this is detected and updated.

At this point in time every language I can think of (.net, Java, Objective-C, Swift, Golang, JS, Python..) has a map/dictionary implementation which is case-sensitive for keys (I can't think of one that isn't) - particularly given systems aren't generally written to account for dictionary's being case-insensitive.

As such I believe this wants updating to detect changes to casing on keys (as it detects changes to values)?

**Comment by Drewm3** [comment]
Moving this over to the ARM team as the discussion has moved to what is the expected behavior for tags in general for any resource under ARM.

**Comment by tombuildsstuff** [comment]
@drewm3 any update here?

**Comment by zalyoung** [comment]
Any update about this?

**Comment by jennyhunter-msft** [comment]
The behavior Hamid shared is the current expected behavior. 
However, we will track this as a feature request to update our handling of tags so that the tag name is case sensitive. We don't have a timeline yet for when this will be completed, but we are currently undertaking a larger tag modernization project and will investigate it as part of that effort.

**Comment by jennyhunter-msft** [comment]
We don't seem to have any open feature requests for this on UserVoice. If you would like to create a request there to try and gain traction/priority for this work, please visit our [UserVoice](https://feedback.azure.com/forums/281804-azure-resource-manager).

**Comment by rthorn17** [comment]
> This is still not fixed?

Hi @admincasper - As mentioned above, by @jennyhunter-msft, this is the current expected behavior.  The thing I would like to note this is not an issue with Tag keys only.  All properties keys on ARM Resources are case insensitive.  When a PATCH call is received by ARM that is only changing the casing on the property key, it is considered a no-op and is not forwarded to the Resource Provider.  At this time, there are no plans to change this behavior but suggest you add this to the Azure Feedback site for tracking.  [feedback.azure.com](https://feedback.azure.com/d365community/forum/9a0ece70-ff24-ec11-b6e6-000d3a4f07b8)
