### ISSUE TITLE
[Azure Monitor] list opration on TenantEvents throws permission errors / missing subscription arguments

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#899]
**Error:**

The client 'xxx@microsoft.com' with object id 'xxxx-xx-xxx-xxx-xxx' does not have authorization to perform action 'microsoft.insights/eventtypes/values/read' over scope '/providers/microsoft.insights/eventtypes/management'.

Jagadish Kulkarni from the Azure Monitor team would help in understanding the issue.

**Comment by gucalder** [comment]
The caller in in that operation (ListTenantEvents) must have tenant level permissions. This is something the caller must discuss with ARM.

**Comment by gucalder** [comment]
No change is needed in this case. This was a permissions issue.
This incident was referenced in PR #996, but it was not closed automatically.
It can be closed now.

**Comment by crisan7** [comment]
Hello

I've assigned the Global Administrator role to my service principal (created using Application Registration within AAD).

I'm using it's client secret to get the access token and I'm trying to list tenant activity logs using [this api.](https://learn.microsoft.com/en-us/python/api/azure-mgmt-monitor/azure.mgmt.monitor.v2015_04_01.operations.tenantactivitylogsoperations?view=azure-python#azure-mgmt-monitor-v2015-04-01-operations-tenantactivitylogsoperations-list)

I'm receiving the very same error:
`Message: The client .... with object id .... does not have authorization to perform action 'Microsoft.Insights/eventtypes/values/read' over scope '/providers/Microsoft.Insights/eventtypes/management' or the scope is invalid. If access was recently granted, please refresh your credentials.`

Do I have to use a different role? Do I have to create an custom role with 'Microsoft.Insights/eventtypes/values/read' as action and  '/providers/Microsoft.Insights/eventtypes/management' as the scope?

Thank you!

**Comment by crisan7** [comment]
> [crisan7](/crisan7)

I found out what was the problem. Please follow the accepted answer thread on this question if you want to see: https://learn.microsoft.com/en-us/answers/questions/1356911/what-is-the-difference-(if-any)-between-azure-acti
