### ISSUE TITLE
[Alerts Management] ErrorResponse is incorrectly defined

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-rest-api-specs#9004]
The [ErrorReponse](https://github.com/Azure/azure-rest-api-specs/blob/2e4c3c5ea916a05d731993a5e3db36b4c64d279b/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/stable/2019-06-01/SmartDetectorAlertRulesApi.json#L315) defined in SmartDetectorAlertRulesAPI.json does not match up with what's returned by the wire:
{"error":{"code":"ResourceGroupNotFound","message":"Resource group 'blah' could not be found."}}.

Suggested fix: ref the errorResponse defined in AlertsManagement.json

**Comment by simanor** [comment]
Thank you, we will fix the swagger.

**Comment by lilyjma** [comment]
Closing the issue as it appears to be resolved.
