### ISSUE TITLE
PUT call for creation / updation of availability set is not  synonymous

### ISSUE THREAD

**Issue by OmkarHirve** [Azure/azure-rest-api-specs#9014]
PUT call : 
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/availabilitySets/{availabilitySetName}?api-version=2019-07-01

Accepts payload while creating Availability set with proximity placement groups.

`{
  "location": "westus",
  "properties": {
    "platformFaultDomainCount": 2,
    "platformUpdateDomainCount": 20,
    "proximityPlacementGroup": {
         "id":"< ppgResourceID >"
      }
  }
}`

To remove availability set from PPG, following payload is accepted. But AVA set without PPG cannot be created with this same payload.

`{
  "location": "westus",
  "properties": {
    "platformFaultDomainCount": 2,
    "platformUpdateDomainCount": 20,
    "proximityPlacementGroup": {
         "id":""
      }
  }
}`

Accepts payload while creating Availability set without proximity placement groups.

`{
  "location": "westus",
  "properties": {
    "platformFaultDomainCount": 2,
    "platformUpdateDomainCount": 20,
    "proximityPlacementGroup": null
  }
}`

To remove availability set from PPG, following payload does not work. Deployment does not fail, but there is not affect on the PPG.

`{
  "location": "westus",
  "properties": {
    "platformFaultDomainCount": 2,
    "platformUpdateDomainCount": 20,
    "proximityPlacementGroup": null
  }
}`

The properties accepted should be synonymous while create and edit. The same behaviour is observed with Azure ARM templates as well.

**Comment by Drewm3** [comment]
@avirishuv, could you please look into the AvailabilitySet APIs to resolve this issue?

**Comment by mimckitt** [comment]
#assign: @mimckitt

**Comment by avirishuv** [comment]
@OmkarHirve thank you for bringing this up. The behavior outlined is exactly how the API calls are expected to work. 
For updating the availability sets using PUT call, a "null" value of a property (in this case PPG) means that there is no change to be made to that property. 
We are updating the API documentation and adding these details to clarify the expected behavior.
cc @mimckitt

**Comment by mimckitt** [comment]
I currently have a PR in progress for a new document explaining this behavior. Hoping to have it complete and published in the next week or so. Once it is live, we can link from the reference pages to that document to avoid further confusion.

**Comment by avirishuv** [comment]
quick update: the document is still in PR, tagging @mimckitt who is working on it.

**Comment by mimckitt** [comment]
Thanks @avirishuv. Been working on this with our engineering teams to ensure technical accuracy. I pushed a new version today and am waiting to hear back from a few people that are out until mid next week. Hoping to have this buttoned up and live in the next weeks. Apologies for the delay.

**Comment by mimckitt** [comment]
The new document will be live tomorrow by end of day.

**Comment by mimckitt** [comment]
Doc is now live: https://docs.microsoft.com/en-us/azure/virtual-machines/put-calls-create-or-update

**Comment by avirishuv** [comment]
Thanks @mimckitt . Given doc is updated, closing the issue now, but @OmkarHirve please feel free to reopen if you have any other question on this topic.
