### ISSUE TITLE
graphquerymiss location property

### ISSUE THREAD

**Issue by chenjianfei2017** [Azure/azure-rest-api-specs#9018]
RP graphquery missing location property
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview/graphquery.json

**Comment by chiragg4u** [comment]
We are working on this, and will update the ETA soon.

**Comment by chiragg4u** [comment]
This issue was resolved with the following PR https://github.com/Azure/azure-rest-api-specs/pull/9216
