### ISSUE TITLE
Explain caching options in Compute documentation

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-rest-api-specs#905]
The Compute documentation for the CachingType enum (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L3590) does not explain what the different caching types mean.  The options are explained in a blog post at https://blogs.msdn.microsoft.com/windowsazurestorage/2012/06/27/exploring-windows-azure-drives-disks-and-images/ but this is not readily discoverable.  A few words in the Swagger description to explain each caching option would be really useful!

Example: "A caching type of 'None' means there is no disk cache for this disk. 'ReadOnly' means a write-through cache - read operations use the disk cache, but writes are always to disk. 'ReadWrite' means a write-back cache, where both reads and writes go via the disk cache."

(Azure Batch plans to surface this type in our own API, where users may be less familiar with disk admin details, but as we don't know the semantics as well as the Compute team, we'd prefer to inherit their documentation...!)

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
