### ISSUE TITLE
graph: applicationTemplates - difference between UI & API

### ISSUE THREAD

**Issue by duduz** [Azure/azure-rest-api-specs#9122]
I did some comparison between the UI functionality and the API, seems like there's a lot of missing attributes that are being autogenerated by default when using the API.

I've used the Amazon Web Services (AWS Template)

Lets cover the API first
1. made POST to https://graph.microsoft.com/beta/applicationTemplates/8b1025e4-1dd2-430b-a150-2ef79cd700f5/instantiate
2. Got an application and a servicePrincipal objects
3. servicePrincipal:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#servicePrincipals/$entity",
    "accountEnabled": true,
    "addIns": [
    ],
    "alternativeNames": [
    ],
    "api": {
        "resourceSpecificApplicationPermissions": [
        ]
    },
    "appDisplayName": "Amazon Web Services (AWS) REST",
    "appId": "REMOVED",
    "applicationTemplateId": "8b1025e4-1dd2-430b-a150-2ef79cd700f5",
    "appOwnerOrganizationId": "REMOVED",
    "appRoleAssignmentRequired": true,
    "appRoles": [
        {
            "allowedMemberTypes": [
                "User"
            ],
            "description": "msiam_access",
            "displayName": "msiam_access",
            "id": "REMOVED",
            "isEnabled": true,
            "origin": "Application",
            "value": null
        }
    ],
    "deletedDateTime": null,
    "displayName": "Amazon Web Services (AWS) REST",
    "errorUrl": null,
    "homepage": "https://signin.aws.amazon.com/saml?metadata=aws|ISV9.1|primary|z",
    "id": "REMOVED",
    "info": {
        "logoUrl": null,
        "marketingUrl": null,
        "privacyStatementUrl": null,
        "supportUrl": null,
        "termsOfServiceUrl": null
    },
    "isAuthorizationServiceEnabled": false,
    "keyCredentials": [
    ],
    "loginUrl": null,
    "logoutUrl": null,
    "notificationEmailAddresses": [
    ],
    "passwordCredentials": [
    ],
    "preferredSingleSignOnMode": null,
    "preferredTokenSigningKeyEndDateTime": null,
    "preferredTokenSigningKeyThumbprint": null,
    "publishedPermissionScopes": [
        {
            "adminConsentDescription": "Allow the application to access Amazon Web Services (AWS) REST on behalf of the signed-in user.",
            "adminConsentDisplayName": "Access Amazon Web Services (AWS) REST",
            "id": "REMOVED",
            "isEnabled": true,
            "type": "User",
            "userConsentDescription": "Allow the application to access Amazon Web Services (AWS) REST on your behalf.",
            "userConsentDisplayName": "Access Amazon Web Services (AWS) REST",
            "value": "user_impersonation"
        }
    ],
    "publisherName": "test",
    "replyUrls": [
        "https://signin.aws.amazon.com/saml"
    ],
    "samlMetadataUrl": null,
    "samlSingleSignOnSettings": null,
    "servicePrincipalNames": [
        "2798e5d5-376e-4495-a38b-056730427a08"
    ],
    "servicePrincipalType": "Application",
    "signInAudience": "AzureADMyOrg",
    "tags": [
        "WindowsAzureActiveDirectoryIntegratedApp"
    ],
    "tokenEncryptionKeyId": null,
    "verifiedPublisher": {
        "addedDateTime": null,
        "displayName": null,
        "verifiedPublisherId": null
    }
}
```
applicationTemplateId is not null, thats good.
keyCredentials is empty, thats bad. no Rest API for creating one yet (or at least, i'm not aware of one)
preferredTokenSigningKeyEndDateTime is null
preferredTokenSigningKeyThumbprint is null
servicePrincipalNames": [ "2798e5d5-376e-4495-a38b-056730427a08"] - no unique generated identifier
tags - WindowsAzureActiveDirectoryGalleryApplicationNonPrimaryV1 tag is missing

Now, lets get to the UI provisioned app:
1. Got an application with the following properties already baked in
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#servicePrincipals/$entity",
    "accountEnabled": true,
    "addIns": [
    ],
    "alternativeNames": [
    ],
    "api": {
        "resourceSpecificApplicationPermissions": [
        ]
    },
    "appDisplayName": "Amazon Web Services (AWS) UI",
    "appId": "REMOVED",
    "applicationTemplateId": null,
    "appOwnerOrganizationId": "REMOVED",
    "appRoleAssignmentRequired": true,
    "appRoles": [
        {
            "allowedMemberTypes": [
                "User"
            ],
            "description": "msiam_access",
            "displayName": "msiam_access",
            "id": "REMOVED",
            "isEnabled": true,
            "origin": "Application",
            "value": null
        }
    ],
    "deletedDateTime": null,
    "displayName": "Amazon Web Services (AWS) UI",
    "errorUrl": null,
    "homepage": "https://signin.aws.amazon.com/saml?metadata=aws|ISV9.1|primary|z",
    "id": "REMOVED",
    "info": {
        "logoUrl": null,
        "marketingUrl": null,
        "privacyStatementUrl": null,
        "supportUrl": null,
        "termsOfServiceUrl": null
    },
    "isAuthorizationServiceEnabled": false,
    "keyCredentials": [
        {
            "customKeyIdentifier": "1Ko36fHWHNe68HsRW2e1KrkCtUAo410=",
            "displayName": "CN=Microsoft Azure Federated SSO Certificate",
            "endDateTime": "2023-04-17T20:24:39Z",
            "key": null,
            "keyId": "4238b216-552c",
            "startDateTime": "2020-04-17T20:24:39Z",
            "type": "AsymmetricX509Cert",
            "usage": "Verify"
        },
        {
            "customKeyIdentifier": "1Ko36fHW68HsRW2e1KrkCtUAo410=",
            "displayName": "CN=Microsoft Azure Federated SSO Certificate",
            "endDateTime": "2023-04-17T20:24:39Z",
            "key": null,
            "keyId": "39166e20-53aa",
            "startDateTime": "2020-04-17T20:24:39Z",
            "type": "AsymmetricX509Cert",
            "usage": "Sign"
        }
    ],
    "loginUrl": null,
    "logoutUrl": null,
    "notificationEmailAddresses": [
    ],
    "passwordCredentials": [
        {
            "customKeyIdentifier": "1Ko36fHWHRW2e1KrkCtUAo410=",
            "displayName": "CN=Microsoft Azure Federated SSO Certificate",
            "endDateTime": "2023-04-17T20:24:39Z",
            "hint": null,
            "keyId": "39166e20-53aa",
            "secretText": null,
            "startDateTime": "2020-04-17T20:24:39Z"
        }
    ],
    "preferredSingleSignOnMode": null,
    "preferredTokenSigningKeyEndDateTime": "2023-04-17T20:24:39Z",
    "preferredTokenSigningKeyThumbprint": "ABCB0B425117821A7C2490C0C",
    "publishedPermissionScopes": [
        {
            "adminConsentDescription": "Allow the application to access Amazon Web Services (AWS) UI on behalf of the signed-in user.",
            "adminConsentDisplayName": "Access Amazon Web Services (AWS) UI",
            "id": "REMOVED",
            "isEnabled": true,
            "type": "User",
            "userConsentDescription": "Allow the application to access Amazon Web Services (AWS) UI on your behalf.",
            "userConsentDisplayName": "Access Amazon Web Services (AWS) UI",
            "value": "user_impersonation"
        }
    ],
    "publisherName": "Default Directory",
    "replyUrls": [
        "https://signin.aws.amazon.com/saml"
    ],
    "samlMetadataUrl": null,
    "samlSingleSignOnSettings": null,
    "servicePrincipalNames": [
        "21fda5ce-a6cc",
        "http://aws/faadbf3e-d6d1-4b63"
    ],
    "servicePrincipalType": "Application",
    "signInAudience": "AzureADMyOrg",
    "tags": [
        "8b1025e4-1dd2-430b-a150-2ef79cd700f5",
        "WindowsAzureActiveDirectoryGalleryApplicationNonPrimaryV1",
        "WindowsAzureActiveDirectoryIntegratedApp"
    ],
    "tokenEncryptionKeyId": null,
    "verifiedPublisher": {
        "addedDateTime": null,
        "displayName": null,
        "verifiedPublisherId": null
    }
}
```

applicationTemplateId is empty but not that big of a deal
keyCredentials & passwordCredentials have certificates in them
servicePrincipalNames contains a unique identifier - http://aws/faadbf3e-d6d1-4b63
tags contain all the required information

Now, i would think this has something do to with permissions, however, the servicePrincipal i'm using has all the required permissions (Application.ReadWrite.OwnedBy, Application.ReadWrite.All) according to the documentation at https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-beta&tabs=http

**Comment by baywet** [comment]
@ArcturusZhang I'm not sure why I've been mentioned on this issue? If I'm a PM on Microsoft graph, I do not own this specific API.

**Comment by duduz** [comment]
maybe @lmazuel, @yugangw-msft, @amarzavery has an idea..

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang I'm not sure why I've been mentioned on this issue? If I'm a PM on Microsoft graph, I do not own this specific API.

Oh... sorry about that.... then maybe I should tagged this to AAD or graphrbac? I am always confused by these similar names...

**Comment by baywet** [comment]
The PM for this API is @sureshja AFAIK

**Comment by duduz** [comment]
Hi Everyone,

It's almost been a week, i appreciate if this case get some attention, this affects a lot of people looking to use Enterprise Applications in a programmatic way.

**Comment by lilyjma** [comment]
@KirillShchetinin, @edward-reus, and @sureshja, do we have any updates on this?

**Comment by lilyjma** [comment]
@luleonpla, please have a look at this issue. Thanks!

**Comment by luleonpla** [comment]
@duduz thanks for the feedback. We're going to release a doc to walk you through how to configure end-to-end a gallery app (applicationTemplate) using the APIs. We hope to publish it by the end of next week. Below some comments.

> keyCredentials is empty, thats bad. no Rest API for creating one yet (or at least, i'm not aware of one)

If you create the gallery app using the API, you need to use your own signing certificate. You will need to do a PATCH to keyCredential property of the servicePrincipal. https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0

> preferredTokenSigningKeyThumbprint is null
You will need to get the thumbprint of the signing certificate you add in keyCredentials and add the thumbprint there.

> servicePrincipalNames": [ "2798e5d5-376e-4495-a38b-056730427a08"] - no unique generated identifier

If you're using the APIs, we don't pre-populate those fields as we do in the UI. You will need to get those values and do a PATCH to application or servicePrincipal.

**Comment by duduz** [comment]
Hi @luleonpla,

Thank you feedback,

I understand that you're aiming on addressing this from the documentation perspective, however, I don't think there's a documentation or a walk through guide issue here but a lack of fundamental functionality that would be very much expected from a service of this scale and importance.
End users of this service are expecting to have an identical functionality to the UI whether they use the API.
**the ability to being your own certificate is a plus**, 

> If you create the gallery app using the API, you need to use your own signing certificate. You will need to do a PATCH to keyCredential property of the servicePrincipal. https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0

that exactly the thing, the UI allows you to manage the associated certificate. i don't want to own the infrastructure/services to manage certificates, i want to be able to utilize it as feature that is part of THIS service - aka, to have the ability to manage the certificates programmatically.

> You will need to get the thumbprint of the signing certificate you add in keyCredentials and add the thumbprint there.
same as above, i'm expecting to get the same functionality from the UI to the API as well.

> If you're using the APIs, we don't pre-populate those fields as we do in the UI. You will need to get those values and do a PATCH to application or servicePrincipal.
I don't mind issuing a PATCH for that, however, doesn't it miss the whole idea of using a template?
when using the API the current functionality really covers only the application icon and Application Name.
When using the UI, you're actually getting something. its great!

**Comment by duduz** [comment]
Hi @luleonpla,

Thank you feedback,

I understand that you're aiming on addressing this from the documentation perspective, however, I don't think there's a documentation or a walk through guide issue here but a lack of fundamental functionality that would be very much expected from a service of this scale and importance.
End users of this service are expecting to have an identical functionality to the UI whether they use the API.
**the ability to being your own certificate is a plus**, 

> If you create the gallery app using the API, you need to use your own signing certificate. You will need to do a PATCH to keyCredential property of the servicePrincipal. https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0

that exactly the thing, the UI allows you to manage the associated certificate. i don't want to own the infrastructure/services to manage certificates, i want to be able to utilize it as feature that is part of THIS service - aka, to have the ability to manage the certificates programmatically.

> You will need to get the thumbprint of the signing certificate you add in keyCredentials and add the thumbprint there.
same as above, i'm expecting to get the same functionality from the UI to the API as well.

> If you're using the APIs, we don't pre-populate those fields as we do in the UI. You will need to get those values and do a PATCH to application or servicePrincipal.

I don't mind issuing a PATCH for that, however, doesn't it miss the whole idea of using a template?
when using the API the current functionality really covers only the application icon and Application Name.
When using the UI, you're actually getting something. its great!

**Comment by duduz** [comment]
Hi @luleonpla,

Thank you feedback,

I understand that you're aiming on addressing this from the documentation perspective, however, I don't think there's a documentation or a walk through guide issue here but a lack of fundamental functionality that would be very much expected from a service of this scale and importance.
End users of this service are expecting to have an identical functionality to the UI whether they use the API.
**the ability to being your own certificate is a plus**, 

> If you create the gallery app using the API, you need to use your own signing certificate. You will need to do a PATCH to keyCredential property of the servicePrincipal. https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0

that exactly the thing, the UI allows you to manage the associated certificate. i don't want to own the infrastructure/services to manage certificates, i want to be able to utilize it as feature that is part of THIS service - aka, to have the ability to manage the certificates programmatically.

> You will need to get the thumbprint of the signing certificate you add in keyCredentials and add the thumbprint there.

same as above, i'm expecting to get the same functionality from the UI to the API as well.

> If you're using the APIs, we don't pre-populate those fields as we do in the UI. You will need to get those values and do a PATCH to application or servicePrincipal.
I don't mind issuing a PATCH for that, however, doesn't it miss the whole idea of using a template?
when using the API the current functionality really covers only the application icon and Application Name.
When using the UI, you're actually getting something. its great!

**Comment by luleonpla** [comment]
@duduz thank you for taking the time to share the feedback. I have shared this thread internally with my team, it has very good points we should consider and address.

This is the doc I mentioned earlier which doesn't address your concerns but it may help you to follow the end-to-end flow as it is now: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-saml-sso-configure-api

**Comment by lilyjma** [comment]
Hi, this issue seems to be resolved now, so I'm closing it. If you have more questions, please reopen.

**Comment by duduz** [comment]
@lilyjma can you please provide some reference to the solution here?
the arcticle mentioned by @luleonpla is not a solution, there's some parts missing, specifically when provisioned a managed certificate by Azure AD.
