### ISSUE TITLE
Availability Set documentation error

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-rest-api-specs#9130]
https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/listbysubscription

```
GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/availabilitySets?api-version=2019-07-01&$expand=virtualMachines\$ref
```
I suspect this example has mistakes. I try it and get an error:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "The request URL is not valid.",
    "target": "$expand"
  }
}
```
If I change "\\" to "/", it works.
```
GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/availabilitySets?api-version=2019-07-01&$expand=virtualMachines/$ref
```

**Comment by qwordy** [comment]
And it there any explanation of what should I fill in $expand?
Where is the format defined? What does $ref mean?
`virtualMachines\$ref`

**Comment by Drewm3** [comment]
@avirishuv, could you please take a look at this. It does look like there is a typo, and more details on why the expand needs to be "=virtualMachines/$ref"
