### ISSUE TITLE
Some issues in resource graph swaggers

### ISSUE THREAD

**Issue by dolauli** [Azure/azure-rest-api-specs#9136]
Found some issues in the swagger
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/stable/2019-04-01
1.	In line#292 and #411, no ‘type’ defined for the data property.
2.	‘tags’ fields are missing for the API, and the format of ‘operationId’ is incorrect, which should be <resource>-<verb>. See https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json#L39 for an example
[CG] Yes these are issues, we are fixing it in the new preview API being published @ https://github.com/Azure/azure-rest-api-specs/pull/9025/files#diff-200c67f8c6c835534cba4cc76b97cffc

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview
1.	From my testing, the property location is required for the put API, while it is not in the swagger. This is a block issue for me.
2.	‘tags’ fields are missing for the API
[CG] Yes we will be fixing it while publishing the next version for the swagger.

Just found some other issues. Following is the raw HTTP response when getting a specific query. Please see my comments start with //.
```
{
  "properties": {
    "resultKind": "UnKnown",
    "timeModified": "2020-04-17T10:47:44.3813391Z",
    "query": "where isnotnull(tags['Prod']) and properties.extensions[0].Name == 'dockers'"
  },
  "type": "microsoft.resourcegraph/queries",
  "location": "global",
  "subscriptionId": "9e223dbe-3399-4e19-88eb-0975f02ac87f", // subscriptionId is missing in the swagger
  "resourceGroup": "testgroup", // resourceGroup is missing in the swagger
  "name": "sq01",
  "id": "/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/testgroup/providers/microsoft.resourcegraph/queries/sq01",
  "etag": "\"00003200-0000-1800-0000-5e9989500000\"" // it should be etag, but in swagger it is eTag. BTW, I think the value of "etag" should be "00003200-0000-1800-0000-5e9989500000"
} 
```

**Comment by johnthcall** [comment]
@dolauli regarding 2019-04-01 comment #2, I see tags field in the two apis in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/stable/2019-04-01/resourcegraph.json can you help me understand what is missing?

**Comment by dolauli** [comment]
> @dolauli regarding 2019-04-01 comment #2, I see tags field in the two apis in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/stable/2019-04-01/resourcegraph.json can you help me understand what is missing?

My bad. Tags are only missing in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview/graphquery.json.
