### ISSUE TITLE
URL encoding give auth error when using azure blob rest api

### ISSUE THREAD

**Issue by m81092** [Azure/azure-rest-api-specs#9144]
I am using curl to upload file using [PUT Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) to azure blob storage. When I URL encode the path to where I want the file to be stored like "https://${endpoint}/${container_name}/a/b/c/te%20st.txt" (original file name is "te st.txt") and I put the same path in my canonical resource string like "/${account_name}/${container_name}/a/b/c/te%20st.txt", I get "AuthenticationFailed" error. I am using "Authorization: SharedKey ${account_name}:${signature}"

If I remove the % (and remove any spaces) it works like a charm. I tried escaping the `%` char with `%2520` but does not work.

I am using 
blob_type=x-ms-blob-type:BlockBlob
version=x-ms-version:2018-03-28 (also tried the version 2019-07-07)

Any leads will be highly appreciated, Thanks!

**Comment by m81092** [comment]
@xgithubtriage Hey just looking for an update. Thanks

**Comment by m81092** [comment]
Hi @raych1 no body has been assigned to this issue. Can you please make sure somebody addresses this. This is a critical issue for the company. Thanks!

**Comment by akning-ms** [comment]
Thanks @81092 for feedback. Normally our service team will help re-assign for this issue after add label 'service attention' after first triage.  Hi @zhusijia26, can you help assign to correct person in storage team? Thanks

**Comment by adreed-msft** [comment]
@m81092 what is the end goal here? To have a file in storage with a object name of "/a/b/c/te%20st.txt", or a file in storage with an object name of "/a/b/c/te st.txt"?

My _understanding_ is that the canonical name is ***not*** encoded, but the URL should be.

**Comment by m81092** [comment]
@adreed-msft The end goal is to store the file with space in the name like "/a/b/c/te st.txt". I tried putting /a/b/c/te st.txt in canonical resource string(un-encoded) and in the URL it is encoded like /a/b/c/te%20st.txt but still get 403. Below are the details-
https://stackoverflow.com/questions/61367473/url-encoding-give-auth-error-when-using-azure-blob-rest-api
Thanks!

**Comment by adreed-msft** [comment]
On the off chance I was misremembering, I created a SAS token in The Azure Blob Storage SDK. All in all, the URI looks like such, and the string to sign is below. (signature redacted)

https://adeledevtest1.blob.core.windows.net/spaceinblobname/te%20st.txt?se=2023-05-01T10%3A42%3A43Z&sig=REDACTED&sp=rd&spr=https&sr=b&st=2020-05-01T10%3A42%3A43Z&sv=2019-02-02

```
rd
2020-05-01T10:38:39Z
2023-05-01T10:38:39Z
/blob/adeledevtest1/spaceinblobname/te st.txt


https
2019-02-02
b





```

Note that the string to sign is ordered as below (for 2018-11-09): (code snippet from the Go SDK)

```go
stringToSign := strings.Join([]string{
		v.Permissions,
		startTime,
		expiryTime,
		getCanonicalName(credential.AccountName(), v.ContainerName, v.BlobName),
		signedIdentifier,
		v.IPRange.String(),
		string(v.Protocol),
		v.Version,
		resource,
		snapshotTime,         // signed timestamp
		v.CacheControl,       // rscc
		v.ContentDisposition, // rscd
		v.ContentEncoding,    // rsce
		v.ContentLanguage,    // rscl
		v.ContentType},       // rsct
		"\n")
```

**Comment by adreed-msft** [comment]
Service level SAS tokens _may_ grant more privileges than you're asking for-- But this page describes the SAS token format rather well in comparison to other parts of the documentation in my opinion:

https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas

**Comment by m81092** [comment]
Assuming you saw my SO post(link mentioned in the last comment) which details the issue, You are suggesting, I should use SAS instead of `SharedKey`?

**Comment by amishra-dev** [comment]
Hi @m81092 (Manpreet), do you still need help with this?
