### ISSUE TITLE
Most search enums are not documented

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9146]
Most enums in searchindex.json and searchservice.json are not documented, meaning that SDK source generators are just using the values as doc comments which does not benefit customers. These should all be documented like AnalyzerName, using the `x-ms-enum.values` array like AnalyzerName does. This will improve our docs across the entire client SDKs.

Part of Azure/azure-sdk-for-net#11457

**Comment by brjohnstmsft** [comment]
FYI @bleroy: The following indexer-related enums need some work:

- `DataSourceType`: missing descriptions
- `IndexerExecutionStatus`, `IndexerStatus`, `TextExtractionAlgorithm`, `TextSplitMode`, `VisualFeature`, `ImageDetail`, `EntityCategory`: missing `values` section

The rest are either fine, or I'm working on them. Once I've submitted my PR, I'll re-assign this issue to you.

**Comment by bleroy** [comment]
#9276
