### ISSUE TITLE
searchservice.json should define NativeBlobSoftDeleteDeletionDetectionPolicy

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9160]
As brought up in Azure/azure-sdk-for-net#11435, [documentation](https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage#native-blob-soft-delete-preview) shows an example of using `@odata.type` `#Microsoft.Azure.Search.NativeBlobSoftDeleteDeletionDetectionPolicy` that currently is not defined in swagger. We can define one manually, but if this really is a preview feature (is it still), it should be in swagger.

> Sorry, I see those classes should actually be `abstract` (see #9686) and I see that swagger does not actually define @odata.type "#Microsoft.Azure.Search.NativeBlobSoftDeleteDeletionDetectionPolicy". We can define one manually, but this should be in the Preview swagger as well if it's still supported.
> 
> _Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/issues/11435#issuecomment-617347493_

**Comment by brjohnstmsft** [comment]
FYI @bleroy @arv100kri

**Comment by brjohnstmsft** [comment]
@mattmsft Please confirm if this is still on your radar.

**Comment by Petermarcu** [comment]
Is there any update on this? I don't see any ack on progress or timelines.

**Comment by mattmsft** [comment]
We can add this by next week

**Comment by mattmsft** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/10308

**Comment by jennifermarsman** [comment]
@heaths it looks like this has been merged; can this issue be closed?  https://github.com/Azure/azure-rest-api-specs/pull/10308

**Comment by heaths** [comment]
Yes. Thanks for the reminder. I'll open a separate issue to make sure we re-generate the track 2 SDK.
