### ISSUE TITLE
[Cost Management] Miss type definition of QueryProperties.Row

### ISSUE THREAD

**Issue by wyunchi-ms** [Azure/azure-rest-api-specs#9173]
There is no type definition of the items in the array: https://github.com/Azure/azure-rest-api-specs/blob/98127bcfd62a92618a159936e7f05edb84aa9240/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L840. This will cause error when generating code for powershell.

**Comment by ms-premp** [comment]
working on it.

**Comment by ramaganesan-rg** [comment]
Corresponding type definitions have been updated. Please verify and reopen if needed.  thanks for your feedback!
