### ISSUE TITLE
Dataplane search is missing host

### ISSUE THREAD

**Issue by mcardosos** [Azure/azure-rest-api-specs#918]
From what I see in the documentation, `x-ms-parameterized-host` should do the trick.
@brjohnstmsft

**Comment by brjohnstmsft** [comment]
@mcardosos @jhendrixMSFT `x-ms-parameterized-host` didn't exist at the time the Search data plane SDK was developed. I'll take a look at it at some point, but if changing it will change the generated code in a way that breaks backward compatibility, then it will be some time before we make the change.

Please assign the issue to me.

Also, can you please elaborate on the effects of not making this change? Is it blocking some customer scenario?

**Comment by mcardosos** [comment]
SDK would be a little more difficult to use

**Comment by brjohnstmsft** [comment]
@mcardosos How so? Have you looked at the Search .NET SDK to evaluate its usability?

**Comment by mcardosos** [comment]
I mean the Go SDK. Currently we, the Go SDK team, are not generating search dataplane.
When we start generating it, the extension in the swagger would be useful :)

**Comment by brjohnstmsft** [comment]
@mcardosos Got it, thanks! Hopefully it will simplify the .NET SDK too. I'll try it out when I have the chance.
