### ISSUE TITLE
Some issues in migrateprojects swagger

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9209]
Issues:

1. remove acceptLanguage from client
2. tags definition error

I have created a pr to fix this two issues: https://github.com/Azure/azure-rest-api-specs/pull/9020/files.
I think migrate team can refer to this swagger to work on new swagger.

**Comment by dw511214992** [comment]
@RodgeFu

**Comment by RodgeFu** [comment]
@shijojoy, is there any update for this? thanks.
