### ISSUE TITLE
Can't purge secret, then can't disable purge protection

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-rest-api-specs#9222]
Hello
In the key vault, I had purge protection disabled and soft delete enabled.
I wanted to delete a Secret. In the portal I selected the secret and deleted it.

Then I needed to create it again with the same name (and not recover, this is because MSFT's team says KV in a VNet doesn't work when secrets are bind from app settings in portal). So I tried to create the secret this time in CLI:
PS /home/sergio> az keyvault secret set --vault-name "KVName" --name "SecretName" --value "MySecret"
Secret SecretName is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the secret can only be recovered or purged.

So I tried to purge:
PS /home/sergio> az keyvault secret purge --name SecretName --vault-name KVName
Operation is not allowed.
Operation: "purge"
Caller: appid=XXXX;oid=XXXX;numgroups=1;iss=https://sts.windows.net/ZZZ/
Vault: KVName;location=region

In desperation and not finding help on the internet or documentation, in Portal-Key Vault -Properties-Purge Protection I disabled it. Now I can't enable it back.

How can I purge the password I deleted  please?

**Comment by sebansal** [comment]
@sergiosolorzano 

'Operation not allowed' could mean the user may not have the access to purge. Can you eliminate that scenario?
Also, enabling purge protection is a one time operation. Once enabled, user would not be able to disable it.

**Comment by jlichwa** [comment]
@sergiosolorzano please check your access policies, purge permissions are different from delete https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-set-policy
