### ISSUE TITLE
[ImageBuilder] StatusCode of run operation doesn't define the statusCode of 200

### ISSUE THREAD

**Issue by wyunchi-ms** [Azure/azure-rest-api-specs#9233]
After the long running operation from path /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.VirtualMachineImages/imageTemplates/{imageTemplateName}/run, service response 200 not 204, but 200 is not defined in the swagger.

**Comment by feiyushi** [comment]
Service returns 202 for this operation. Does it work?

**Comment by Drewm3** [comment]
@danielsollondon, could you look into this issue.

**Comment by feiyushi** [comment]
@wyunchi-ms Please let us know if you are unblocked since last time we chatted.
