### ISSUE TITLE
DiskRP Swagger Spec

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-rest-api-specs#924]
Is there a Swagger spec for the DiskRP (Managed Disks)?

**Comment by amarzavery** [comment]
disk swagger - https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/disk.json
compute swagger - https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json with updated managed disk options (for ex: while creating a VM) Doing a diff with the previous api-version of compute.json will make things easy to identify.

**Comment by colemickens** [comment]
Aha, I thought I'd seen it go in, but I couldn't find it for the life of me with the search...

Thanks for the very fast response!
