### ISSUE TITLE
Bugs in cosmosdb rest api docs for replacing a collection

### ISSUE THREAD

**Issue by Mike-Ubezzi-MSFT** [Azure/azure-rest-api-specs#9253]
Moving an issue from Azure Docs REST APIs to this repository as issue was misdirected. Original customer issue: https://github.com/Azure/azure-docs-rest-apis/issues/2868

API Doc:
https://docs.microsoft.com/en-us/rest/api/cosmos-db/replace-a-collection

Issues:

1) Wrong description for `indexingPolicy`

https://user-images.githubusercontent.com/1306747/71560512-a5121580-2a1f-11ea-84fa-7817a32cf62a.png

2) In addition to `id` and `indexingPolicy`, the request body must have the partitionKey property, similar to creating a collection. Worth mentioning the value of partitionKey must match the current value as partition keys are immutable.

3) Status codes section mentions `201` status. Should be `200 OK`.

https://user-images.githubusercontent.com/1306747/71560548-397c7800-2a20-11ea-9634-de5beeef4e92.png

4) Status codes section should not include 409?

5) Examples use `lazy` indexing mode. Could be confusing as lazy is being deemphasized per @markjbrown in MicrosoftDocs/azure-docs#23875 (comment)

**Comment by shurd** [comment]
Thank you for opening this issue. I will look into making these changes in our swagger. ETA will be the end of May

**Comment by MehaKaushik** [comment]
Updated ETA end of July.

**Comment by rnagpal** [comment]
Sorry @Mike-Ubezzi-MSFT for the delay on this. We are updating this in our docs soon and post an update here once done.

**Comment by SnehaGunda** [comment]
The above PR fixes the doc.

**Comment by MehaKaushik** [comment]
Thanks Sneha for fixing this.
