### ISSUE TITLE
Support for API Management vnet join with multiple locations

### ISSUE THREAD

**Issue by sam-cogan** [Azure/azure-rest-api-specs#9255]
As far as I can tell it is not possible to create an APIM using the Rest API that supports both vNet Join and multiple locations. The API seems to only provide a way to join the primary location to a vNet, any additional locations cannot have a subnet ID provided for them to join.

Can this be added to the Rest API?

**Comment by ukphillips** [comment]
I just came across this as well trying to front multiple AKS clusters that are isolated in separate VNETs. I was hoping to have a region of APIM for each AKS region, but this seems to be a limitation.

**Comment by danbyrne-tal** [comment]
We are looking to replace our CI/CD IaC framework of currently more complex ARM template management of our APIM instances with Terraform, and this is a limitation / gap... very keen to get traction on this.

**Comment by solankisamir** [comment]
@sam-cogan @ukphillips @danbyrne-tal the REST API does support adding VNET into `additionalLocations`. Look at example [apimanagementservicegetmultiregioninternalvnet](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/get#apimanagementservicegetmultiregioninternalvnet)
