### ISSUE TITLE
[DataLake]: Update Swagger objects to have proper inheritance

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-rest-api-specs#928]
Need explicit inheritance for (flow is each lower object is "AllOf" the one above it, in the nested lists)
* JobInformation 
  * BaseJobInformation
  * SubmitJobResponse
  * JobInformation
  * SubmitJobParameters (maybe)

* Account (adla and adls)
  * ListAccount
  * Account

**Comment by begoldsm** [comment]
@amarzavery can you assign this to me, I can't modify assignees.

**Comment by kirthik** [comment]
@begoldsm - Could you provide an update on this issue? Is it fixed?

**Comment by begoldsm** [comment]
@kirthick this is not yet fixed. This is a nice to have clean up task that will result in a lot of breaking changes to subsequent releases of the sdk. This is requirement is only to make our strict swagger validation tests work so that an object that is returned doesn't have missing "required" properties.

I will sync with PM to prioritize this and reply back here with an eta

**Comment by begoldsm** [comment]
@veronicagg and @kirthik this should be resolved by PR #1429 can you confirm and close this if so?
