### ISSUE TITLE
Advisor generate recommendations doesn't work

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#9284]
POST https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Advisor/generateRecommendations?api-version=2020-01-01

1. Shall we get the asynchronous link in `Location` ? https://management.azure.com/subscriptions/85b3dbca-5974-4067-9669-67a141095a76/providers/Microsoft.Advisor/generateRecommendations/4ed52480-90dc-42ca-a041-853e2446ff3f?api-version=2020-01-01
![image](https://user-images.githubusercontent.com/56525716/80679524-99c71780-8aef-11ea-89e2-341dc0e0d5f8.png)

2. After I track  the asynchronous link, it shows 204 no content.

**Comment by Prasanna-Padmanabhan** [comment]
Yes, this is expected as per documentation at https://docs.microsoft.com/en-us/rest/api/advisor/recommendations/getgeneratestatus. After you get 204, you should call https://docs.microsoft.com/en-us/rest/api/advisor/recommendations/get to get the full list of recommendations.

**Comment by yupwei68** [comment]
hi @Prasanna-Padmanabhan Thanks for your reply. On fact, I'm now developing and testing this resource. I have created a `storage account` with disabled `Blob soft-delete` and disabled `Secure transfer required`. I want to create some recommendations.
![Annotation 2020-05-06 132455](https://user-images.githubusercontent.com/56525716/81140919-97583800-8f9d-11ea-8299-9ce673c66792.png)
![Annotation 2020-05-06 132420](https://user-images.githubusercontent.com/56525716/81140920-9921fb80-8f9d-11ea-9e3b-5de8d27e22df.png)

Then I generate the recommendations:
POST:https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Advisor/generateRecommendations?api-version=2020-01-01

Response 202 Accepted. 

Then I get the recommendations:
GET:https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Advisor/recommendations?api-version=2020-01-01&$filter=ResourceGroup eq 'acctestRG-advisor-200506131937159438'

Response:
{
    "value": []
}

I want to get recommendations like:
![Annotation 2020-05-06 132553](https://user-images.githubusercontent.com/56525716/81141103-29f8d700-8f9e-11ea-87ee-7379f2a8cddf.png)

Please help to continue to support me, do I correctly understand these apis>

**Comment by Prasanna-Padmanabhan** [comment]
Yes, you have the right understanding. Many of our recommendations are generated using telemetry from backend services and any changes you make will take a while (in certain cases, up to a day or more) to show up in the form of recommendations.

**Comment by yupwei68** [comment]
Hi @Prasanna-Padmanabhan Thanks for your support.
