### ISSUE TITLE
`VirtualMachineImages_List` returns ID of images in improper casing

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-rest-api-specs#9311]
First reported: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6745

The ID of the images retrieved by [this request](https://github.com/Azure/azure-rest-api-specs/blob/a07634d23ecb2b963ef456fd2d48ddfcf1cb4315/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json#L1624) is in inconsistent casing with all the segment starting with upper-case-lettered.

Usually we expect the ID of a resource returned from the service will have the same casing as the request URI, in this case, it should be 
```
/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/publishers/{publisherName}/artifacttypes/vmimage/offers/{offer}/skus/{skus}/versions/{versionName}
```
But instead, the service returns this:
```
/Subscriptions/{subscriptionId}/Providers/Microsoft.Compute/Locations/{location}/Publishers/{publisherName}/ArtifactTypes/VMImage/Offers/{offer}/Skus/{skus}/Versions/{versionName}
```

**Comment by Drewm3** [comment]
@Vaibhav-Agar, could you look into this?

**Comment by Vaibhav-Agar** [comment]
Investigating.

**Comment by Vaibhav-Agar** [comment]
Closing based on the offlien discussion with @ArcturusZhang.
