### ISSUE TITLE
next-api-version: Redis API PascalCases for 'Message' property name

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-rest-api-specs#935]
Tracking bug.
Redis swagger defines 'Message' property in PascalCase because the server api was implemented incorrectly. But fixing it in current api-version would be a breaking change.
This issue should be fixed as part of the next Microsoft.Cache/redis api-version, whenever that happens.

/cc @vishrutshah

**Comment by kirthik** [comment]
@TimLovellSmith - is this issue fixed?

**Comment by TimLovellSmith** [comment]
@kirthik AFAICR, no, we still don't have any newer api-version which returns message in camelCase.

**Comment by TimLovellSmith** [comment]
@kirthik Update: we actually fixed this in our 2017-10-01 api version.
