### ISSUE TITLE
Duplicate object schema with the same name

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9368]
In swagger https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/advisor/resource-manager/Microsoft.Advisor/stable/2020-01-01/advisor.json, there are two enums defined with the same name:
```
"category": {
  "description": "The category of the recommendation.",
  "enum": [
    "HighAvailability",
    "Security",
    "Performance",
    "Cost",
    "OperationalExcellence"
  ],
  "type": "string",
  "x-ms-enum": {
    "name": "category",
    "modelAsString": true
  },
}
```
```
"categories": {
  "description": "Categories to send digest for. If categories are not provided, then digest will be sent for all categories.",
  "type": "array",
  "items": {
    "enum": [
      "HighAvailability",
      "Security",
      "Performance",
      "Cost",
      "OperationalExcellence"
    ],
    "type": "string",
    "x-ms-enum": {
      "name": "Category",
      "modelAsString": true
    }
  }
},
```
The `name` of `x-ms-enum` are both `category` (ignore the case), which is not allowed. One of them should be changed. If they are supposed to be the same, then put it in definitions and ref it.

**Comment by Prasanna-Padmanabhan** [comment]
Thanks for the feedback. I have opened a bug in our internal work tracking system to address this.
