### ISSUE TITLE
Operations, which should be in the same operation group, are in different operation group

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9391]
In swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/addons/resource-manager/Microsoft.Addons/preview/2018-03-01/addons-swagger.json, there is a operation in group "default", and the operation should be in group "AddonDetails"

**Comment by RodgeFu** [comment]
@akning-ms , I didn't find Addon service label. do you know how we can include service team for this? thanks.

**Comment by erich-wang** [comment]
ping @akning-ms

**Comment by RodgeFu** [comment]
@akning-ms , how can we contact svc team? seems no label for add-on

**Comment by akning-ms** [comment]
Hi @rajshah11, as you have contributed Addons Swagger, so added you here for your comments who is right contact person for this issue in Addons service team as the PR has not been update for a long time.
