### ISSUE TITLE
Operation that returns paginated result should name operation id as ListXXX

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#940]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-cdn/2016-10-02/swagger/cdn.json#L1434 

swagger code.
```
    "/subscriptions/{subscriptionId}/providers/Microsoft.Cdn/checkResourceUsage": {
      "post": {
        "tags": [
          "CheckResourceUsage"
        ],
        "description": "Check the quota and actual usage of the CDN profiles under the given subscription.",
        "operationId": "CheckResourceUsage",
```

operation ID should be changed to ListResourceUsage.

**Comment by veronicagg** [comment]
Assigning to @hovsepm after chatting with him, since this issue should be closed once the referenced PR that he's reviewing gets merged.

**Comment by hovsepm** [comment]
Fixed and merged in swagger.
