### ISSUE TITLE
AzureStack swagger issue: required parameter is not marked as required

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9400]
In resource Registration, some required parameters are not marked required.
For example:
The request body is defined as:
```
token (required): {
  "properties"(optional): {
    "registrationToken" (required)
  },
  "location"(optional)
}
```
After test, I find both "properties" and "location" are required, but they are not marked required in swagger.

**Comment by bganapa** [comment]
PR - https://github.com/Azure/azure-rest-api-specs/pull/9777

**Comment by bganapa** [comment]
We have a PR to address the issue @dw511214992 Could you please let us know how found this issue? What are you trying to do with this spec? Thanks!

**Comment by bganapa** [comment]
PR is merged
