### ISSUE TITLE
SecurityInsights Alert Rule Action Asymmetric API

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#9424]
The Action API is asymmetric, the [response](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2020-01-01/SecurityInsights.json#L831) of `GET` has no `triggerUrl` returned, while the [request](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2020-01-01/SecurityInsights.json#L796) of `PUT` asks users to specify it. This non-idempotent behavior makes IaC client hard to implement.

**Comment by magodo** [comment]
Hi @lirenhe any progress on this one?

**Comment by tombuildsstuff** [comment]
ping @lirenhe

**Comment by magodo** [comment]
ping @lirenhe again

**Comment by dperez-safefleet** [comment]
Hey @lirenhe , any update on this?

**Comment by kaovd** [comment]
Excited about such a feature, would be a tipping point for a lot of people's IaC/Detection as Code implementations. Another ping for luck - @lirenhe

**Comment by q-uu-rt** [comment]
Bump. Is there no way to implement this through PR adding the few lines to put the triggerUri as a reponse property? Can understand why theres been no action if its more complicated. Although notice the issue was unassigned so not sure if anyones currently going to action on this. Some closure would be reassuring.

**Comment by magodo** [comment]
Confirmed with service team, this is a known issue and they are working on the automation rule, which will eventually deprecate the alert rule action in the future. Also, there is no plan to fix this issue due to some reason.

As therer is an alternative to trigger an action on an alert rule by using the automation rule, I'm going to close this issue for now.
