### ISSUE TITLE
[key vault] vaultUri in resource manager spec must be readonly

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-rest-api-specs#9432]
For context, a client opened an issue here: https://github.com/Azure/azure-sdk-for-python/issues/11333.

The [swagger](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1107) has vaultUri defined as just a string. In order to make it readonly, a line like [this](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1160) needs to be added to its swagger definition

Seeing this for at least API version 2019-09-01.

**Comment by jlichwa** [comment]
@RandalliLama is it ok to make it readonly?

**Comment by jeking3** [comment]
Friendly ping. :)  Seems to have stalled.

**Comment by jeking3** [comment]
Note this issue will not be resolved fully by the linked update; the documentation will be updated however the swagger definition will still be wrong.

**Comment by sebansal** [comment]
Hi @jlichwa 
I was triaging this list, can you share if it has been resolved and can be closed?
Thanks

**Comment by sebansal** [comment]
@jlichwa for review

**Comment by jlichwa** [comment]
@sebansal  merge is still in progress.

**Comment by thomas11** [comment]
This issue is **not** fixed. The PR only updated the docs, but a `readonly: true` line needs to be added to the spec.

**Comment by EronWright** [comment]
@thomas11 is correct, there was some pushback on setting `readonly`:
https://github.com/Azure/azure-rest-api-specs/pull/11040#issuecomment-703969199
