### ISSUE TITLE
Unable to start datafactory tumbling windows trigger 

### ISSUE THREAD

**Issue by JohPa8696** [Azure/azure-rest-api-specs#9437]
I'm building a Azure Devops Release pipeline which deploys a datafactory using ARM template. I have azure powershell task which start the tumbling windows triggers in the datafactory. The powershell command being used:
Start-AzDataFactoryV2Trigger -ResourceGroupName "rgn" -DataFactoryName  "dn" -Name "tn" -Force 

I then tested with the api, and found the same issue as shown below.
[Docs](https://docs.microsoft.com/en-us/rest/api/datafactory/triggers/start#code-try-0)
# Expected Behavior
Powershell: returns True
API: returns 200 response
# Current Behavior
Powershell:
```
Start-AzDataFactoryV2Trigger : HTTP Status Code: BadRequest
Error Code: BadRequest
Error Message: Missing or invalid pipeline references for trigger CopyPipeline_TagIndex_Delta_PDM_Connector_Trigger
Request Id: ebc98641-cfed-4b56-9898-a95a4aaca73a
Timestamp (Utc):05/13/2020 01:17:49
At line:14 char:5
+     Start-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupNam ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzDataFactoryV2Trigger], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.StartAzureDataFactoryTriggerCommand
```

API:
![image](https://user-images.githubusercontent.com/14051565/81760637-e7924580-951b-11ea-9564-893f873adb0a.png)

**Comment by lmy269** [comment]
Duplicate with https://github.com/Azure/azure-powershell/issues/11893#issuecomment-628915379
