### ISSUE TITLE
Kusto: Wrong type of ReadWriteDatabaseProperties#isFollowed

### ISSUE THREAD

**Issue by jrauschenbusch** [Azure/azure-rest-api-specs#9450]
ReadWriteDatabaseProperties#isFollowed must be of type `bool`, but is  of type `string`.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json#L2879

This leads to a unmarshal error within the Go library.

Bug reference: https://github.com/Azure/azure-sdk-for-go/issues/9339

**Comment by NullMDR** [comment]
@ArcturusZhang Could you help on this go sdk issue?

**Comment by jrauschenbusch** [comment]
I think this should be a valid fix for the issue:
```diff
diff --git a/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json b/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json
index 9f6452aaa..de503c5dc 100644
--- a/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json
+++ b/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2020-02-15/kusto.json
@@ -2877,7 +2877,7 @@
           "description": "The statistics of the database."
         },
         "isFollowed": {
-          "type": "string",
+          "type": "boolean",
           "readOnly": true,
           "description": "Indicates whether the database is followed."
         }
-- 
```

It seems that the real API returns a Boolean value, but the model indicates that it is a string.

**Comment by docohe** [comment]
Hi, I'm Dor for Kusto team.
@jrauschenbusch your fix should work. Do you need us to make the change or can you do it ?

**Comment by jrauschenbusch** [comment]
I'll open an PR. The question would be, if this should also be applied to the API 2019-11-09, as the property was also already available there, but also of type string. I don't know if this was intended there, or if it's also a bug within the spec. 

see https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2019-11-09/kusto.json#L2711

I also have to scan the Examples, if this property was used and also had to update it.

Some feedback would be really good.

**Comment by docohe** [comment]
Both versions need this fix. I've checked and we don't use this property in the examples.

**Comment by jrauschenbusch** [comment]
PR is created. The rest is up to you now 😄

**Comment by docohe** [comment]
Sorry I mistakenly though you are a Microsoft employee, I will handle the PR.

**Comment by jrauschenbusch** [comment]
Hey @docohe,

> Sorry I mistakenly though you are a Microsoft employee

not yet ;-) alright, just ping back as soon as the fix is out.

Thanks

**Comment by docohe** [comment]
Hi @jrauschenbusch a new GO SDK version is now available.
