### ISSUE TITLE
Miss consumes and produces section

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9456]
in swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/marketplace/resource-manager/Microsoft.Marketplace/stable/2020-01-01/Marketplace.json, consumes and produces section are missed.

**Comment by yungezz** [comment]
cc @olrakovs  from commit history to look at the issue

**Comment by olrakovs** [comment]
@yungezz , consumes and produces are implemented inside every path
