### ISSUE TITLE
Event hubs cluster should support passing parameters with “sku” and “location”

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#9525]
Per the [example ](https://github.com/Azure/azure-rest-api-specs/blob/7eeef3ce97572bf15bbf3865fdfd17e78b1e760b/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/examples/Clusters/ClusterPut.json#L7)of rest apis spec, seems passing “parameters” with “sku” and “location” is supported by “Clusters_Put" API. However, after I also checked [rest api](https://github.com/Azure/azure-rest-api-specs/blob/7eeef3ce97572bf15bbf3865fdfd17e78b1e760b/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/Clusters-preview.json#L124), seems event hubs cluster actually doesn’t support passing parameters with “sku” and “location” as http request body. So I am confused. If it doesn’t support to send http request body, then I cannot specify “sku” and “location” while creating event hub cluster. So I suppose passing http request body should be supported.

**Comment by serkantkaraca** [comment]
It seems the sample should use  a different name for SKU as below.

`            "sku": {
                "name": "Dedicated",
                "capacity": 1
            }`

**Comment by neil-yechenwei** [comment]
@serkantkaraca , and seems Clusters_Put doesn't support to pass parameters as request body.

**Comment by serkantkaraca** [comment]
@neil-yechenwei I don't understand what you mean by not supporting request body. Entire JSON object is the body and you provide those in the JSON object.

**Comment by serkantkaraca** [comment]
OK, just informed the API is being fixed right now. Sorry for misunderstanding.

**Comment by neil-yechenwei** [comment]
@serkantkaraca , I think `[parameters](https://github.com/Azure/azure-rest-api-specs/blob/91294a48037aab7aec079d96f9b91e3140033000/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/Clusters-preview.json#L194)` (I called it request body) is missing in `[Cluster_PUT](https://github.com/Azure/azure-rest-api-specs/blob/91294a48037aab7aec079d96f9b91e3140033000/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2018-01-01-preview/Clusters-preview.json#L143)`, right? After checked latest code,  seems this bug still hasn't been fixed. Could you help to fix it asap since we're blocked now? Thanks.

**Comment by serkantkaraca** [comment]
Here is the PR for fix - https://github.com/Azure/azure-rest-api-specs/pull/9596

**Comment by neil-yechenwei** [comment]
Seems the issue has been fixed. So closed it. THanks so much.
