### ISSUE TITLE
Omit ResourceGroup when creating firewall rules for MySQL/MariaDB/PostgreSQL server

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-rest-api-specs#9538]
When using Azure Powershell  MySQL module, a customer request to omit ResourceGroup parameter when creating a firewall rule since server name is globally unique.

This requirement call for a new url to create firewall rules for MySQL server, which is something like
```
"/subscriptions/{subscriptionId}/providers/Microsoft.DBforMySQL/servers/{serverName}/firewallRules/{firewallRuleName}"
```
The current url is here
https://github.com/Azure/azure-rest-api-specs/blob/3a0b1d534cec25b41b5278015bc56e1ee989281a/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json#L371

There should be the same for MariaDB
https://github.com/Azure/azure-rest-api-specs/blob/3a0b1d534cec25b41b5278015bc56e1ee989281a/specification/mariadb/resource-manager/Microsoft.DBforMariaDB/stable/2018-06-01/mariadb.json#L507

PostgreSQL
https://github.com/Azure/azure-rest-api-specs/blob/3a0b1d534cec25b41b5278015bc56e1ee989281a/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L507

**Comment by ajlam** [comment]
Looking into this.

**Comment by ajlam** [comment]
@msJinLei - this is a restriction we have today in ARM. Other than this request for PowerShell, are there any customer requesting this?

**Comment by ajlam** [comment]
Closing this issue as won't fix.
