### ISSUE TITLE
Incorrect description in SQL Database REST API?

### ISSUE THREAD

**Issue by wely** [Azure/azure-rest-api-specs#9557]
Hi folks,

I am trying to execute a failover REST request following: https://docs.microsoft.com/en-us/rest/api/sql/failovergroups/failover?source=docs

From the doc, it shows that:

image
I originally created the issue [here](https://github.com/MicrosoftDocs/azure-docs/issues/55323), but was asked to create one here since it's REST related.

---
Apparently during my testing (via postman), this isn’t not correct.
It’s supposed to be the secondary (target) server name which we’d like to failover.

FYI, this is the error that I am getting if I define “serverName” which containing the failover group.

{
"error": {
"code": "FailoverGroupFailoverRequestOnPrimary",
"message": "The failover request should be initiated on the secondary server of failover group."
}
}

Unfortunately there’s no way for me to edit / submit a pull request on the doc.
So, raising this here.

For the owner of the doc, feel free to reach out to me to verify / clarification.

**Comment by ericshape** [comment]
Hi! @wely Thanks for your feedback!
for the MSFT internal user, please directly create a Sev 3 IcM CRI to unblock you from any SQL DB issue. Github issues are not monitored for a long time. 
I will close this issue.
