### ISSUE TITLE
HTTP 500 - Cost Management API query usage 

### ISSUE THREAD

**Issue by epomatti** [Azure/azure-rest-api-specs#9561]
I am running the query usage example from this link:

https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage

With the following URL:

```
https://management.azure.com/subscriptions/{subscription}/resourceGroups/{group}/providers/Microsoft.CostManagement/query?api-version=2019-11-01
```

And this body payload:

```
{
	timeframe: "MonthToDate"
	type: "Usage"
}
```

But I'm getting HTTP 500 error:

```
{
  "error": {
    "code": "500",
    "message": "An error occurred during processing this request. Use this request id '2e416ae7-fbc0-4dd8-a8e5-4ea0ad843c11' for follow-up."
  }
}
```

Would it be anything wrong that I'm doing?

![image](https://user-images.githubusercontent.com/6530769/82713806-b247cf00-9c62-11ea-9280-fa259f5ff4d9.png)

**Comment by ms-premp** [comment]
The post payload needs additional info on aggregation and granularity.
Here is the simple payload

{
  "type": "Usage",
  "timeframe": "MonthToDate",
    "dataset": {
    "granularity": "None",
    "aggregation": {
      "PreTaxCost": {
        "name": "PreTaxCost",
        "function": "Sum"
      }
    }
  }
}

**Comment by ramaganesan-rg** [comment]
closing as per Prem's inputs.
