### ISSUE TITLE
Inconsistent interfaces for different List methods

### ISSUE THREAD

**Issue by logachev** [Azure/azure-rest-api-specs#9563]
There is no consistent interface for different mgmt libraries `List` operations.

Vast majority of libraries return iterator-like instance of an object of some sort.

costmanagement library returns an object without an iterator, instead it has only `value` of type `list`.

The problem is it is harder to write a generic function to return a list of objects, like this:

```
op = <some sdk List function>
params = <params for List operation>
data = [r.serialize(True) for r in op(**params)]
```

Example of different list operation: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/costmanagement/azure-mgmt-costmanagement/azure/mgmt/costmanagement/operations/exports_operations.py#L39

Proposed solution: 
Update autorest generator to generate object with required iterator methods for objects of type 'array' (instead of existing dict with single property `value`)

**Comment by RodgeFu** [comment]
Good point. transfer the issue to azure-rest-api-specs repo. thanks.

**Comment by ramaganesan-rg** [comment]
Swagger will be updated.

**Comment by melmullen** [comment]
We have released a new version of the API and swagger: 2020-06-01. Please retry.
