### ISSUE TITLE
PostgreSQL Server create fails when infrastructureEncryption enabled

### ISSUE THREAD

**Issue by yupwei68** [Azure/azure-rest-api-specs#9571]
It seems that `infrastructureEncryption` is no longer supported. 

1. create a postgresql server in `default` mode with `"infrastructureEncryption": "Enabled"` :
Request: 
PUT /subscriptions/85b3dbca-5974-4067-9669-67a141095a76/resourceGroups/rg-wlynx/providers/Microsoft.DBforPostgreSQL/servers/psql-wlynx?api-version=2017-12-01 HTTP/1.1
```
{
    "location": "eastus",
    "properties": {
        "administratorLogin": "psqladmin",
        "administratorLoginPassword": "LNg1gDLB4pUIUhO7",
        "createMode": "Default",
        "infrastructureEncryption": "Enabled",
        "minimalTlsVersion": "TLS1_2",
        "publicNetworkAccess": "Enabled",
        "sslEnforcement": "Enabled",
        "storageProfile": {
            "backupRetentionDays": 30,
            "geoRedundantBackup": "Enabled",
            "storageMB": 640000,
            "storageAutogrow": "Enabled"
        },
        "version": "11"
    },
    "sku": {
        "name": "GP_Gen5_2",
        "tier": "GeneralPurpose",
        "capacity": 2,
        "family": "Gen5"
    },
    "tags": {}
}
```
Response:
202 Accepted
get the async operation link:
https://management.azure.com/subscriptions/85b3dbca-5974-4067-9669-67a141095a76/providers/Microsoft.DBforPostgreSQL/locations/eastus/azureAsyncOperation/a0b9c97f-8183-4319-9ec9-a7aa93af0959?api-version=2017-12-01
{
    "name": "9a02c714-6cfb-4673-b0a0-7ce54f2c976e",
    "status": "Failed",
    "startTime": "2020-05-25T06:40:03.113Z",
    "error": {
        "code": "OperationTimedOut",
        "message": "The operation timed out and automatically rolled back. Please retry the operation."
    }
}

2. create a postgresql server in `default` mode with `"infrastructureEncryption": "Disabled"` , success

**Comment by rachel-msft** [comment]
Thanks for reaching out. `infrastructureEncryption` is a server property that is still in development and hasn't been officially released. We apologize for the inconvenience it causes.

**Comment by lebenitza** [comment]
Ended up here because of a similar issue and I just want to note this: in what messed up world is okay to release something which is "still in development" to the clients?
