### ISSUE TITLE
Azure SQL - extended database/server auditing policy -  'too many 500 error responses'

### ISSUE THREAD

**Issue by aurimasjsonar** [Azure/azure-rest-api-specs#9575]
I'm using Azure Python SDK to call these actions:
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.extendedserverblobauditingpoliciesoperations?view=azure-python
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.extendeddatabaseblobauditingpoliciesoperations?view=azure-python

extendedserverblobauditingpoliciesoperations fails like this:
`msrestazure.azure_exceptions.CloudError: Azure Error: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: '9fe001b1-0b87-445a-a791-c18443ada179'
`

extendeddatabaseblobauditingpoliciesoperations fails like this:
`msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/62badbd6-2e25-46d0-abb9-b63d6ab2bbd7/resourceGroups/Eran_Test_W_US/providers/Microsoft.Sql/servers/cbebek-server/databases/cbebek-aurimas-sql-db/extendedAuditingSettings/default?api-version=2017-03-01-preview (Caused by ResponseError('too many 500 error responses',))`

Error file (some parts redacted out):
`{
    "level": "Error",
    "operationId": "c3dd3af5-d800-4908-aa5f-86df933610d4",
    "operationName": {
        "value": "Microsoft.Sql/servers/databases/extendedAuditingSettings/write",
        "localizedValue": "Set extended database blob auditing policy"
    },
    "resourceProviderName": {
        "value": "Microsoft.Sql",
        "localizedValue": "Microsoft SQL"
    },
    "resourceType": {
        "value": "Microsoft.Sql/servers/databases/extendedAuditingSettings",
        "localizedValue": "Microsoft.Sql/servers/databases/extendedAuditingSettings"
    },
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "InternalServerError",
        "localizedValue": "Internal Server Error (HTTP Status Code: 500)"
    },
    "submissionTimestamp": "2020-05-25T12:49:50.1947159Z",
    "properties": {
        "statusCode": "InternalServerError",
        "serviceRequestId": "11c753f4-9c6e-4f96-90f9-e1306ff47e13",
        "statusMessage": "{\"error\":{\"code\":\"InternalServerError\",\"message\":\"An unexpected error occured while processing the request. Tracking ID: '11c753f4-9c6e-4f96-90f9-e1306ff47e13'\"}}"
    }
}`

Non-extended audit enabling calls work without a problem.

**Comment by Oleza1972** [comment]
Unfortunately we no longer have logs for this to investigate it.

From my experience server returns such error if, for example, predicate_expression or audit_actions_and_groups fields of the extended policy object have invalid format\values.
