### ISSUE TITLE
"Resource" definition under common types.json should have systemData under properties

### ISSUE THREAD

**Issue by microsoft-rin** [Azure/azure-rest-api-specs#9598]
![image](https://user-images.githubusercontent.com/19398051/82985961-ce70a680-9fa9-11ea-9850-5b6120f67677.png)
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json

systemData should be added to Resources/properties

**Comment by NullMDR** [comment]
@jianyexi @raych1 Could you help on this issue?

**Comment by jianyexi** [comment]
As I know,    the `systemData`  need to be added to the `ResourceModelWithAllowedPropertySet`  [types.json]( https://github.com/Azure/azure-rest-api-specs/blob/master/specification/common-types/resource-management/v1/types.json#L86)
not sure if it need to be added to the `Resource` . @microsoft-rin could you give more context ?

**Comment by microsoft-rin** [comment]
Thank you @jianyexi . So the [ARM entity of our service](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/mediaservices/resource-manager/Microsoft.Media/preview/2020-02-01-preview/MediaGraphs.json#L359-L373) takes a reference (allOf) to the common resource for the top level properties. If systemData is added to the common resource, we don't need to change on our side, otherwise we need to manually add references to each top level property.

**Comment by jennyhunter-msft** [comment]
Thanks for your patience. It seems like this never got properly routed. 

SystemData is a top-level property and was designed this way since it is common across the various resource types. This is why it's not in the lower "properties" bag which is individual to the varying resource types.

**Comment by NullMDR** [comment]
@jianyexi Any update on this?

**Comment by jianyexi** [comment]
This change will produce huge impact, needs @akning-ms  to confirm .

**Comment by jianyexi** [comment]
we've  updated it in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v3/types.json
