### ISSUE TITLE
CostManagement: Resource does't have eTag property

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-rest-api-specs#9614]
https://github.com/Azure/azure-rest-api-specs/blob/98127bcfd62a92618a159936e7f05edb84aa9240/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L1163

1.  The update operation need an eTag value but the base class of Export is Resource who doesn't have an eTag property but ProxyResource does.
2.  The example costmanagement provide for CreateOrUpdate are invalid,
2.1  For create, the example might succeed but the return output indicate the aggregation property is not set.
2.2  For update, the example is not working at all because missing eTag.

**Comment by ramaganesan-rg** [comment]
thank you for the feedback! team has investigated the issue. Export swagger and code change is needed. Team will provide an update.

**Comment by melmullen** [comment]
Fixed in Exports ver 2020-06-01

**Comment by melmullen** [comment]
Fixed in latest version
