### ISSUE TITLE
Service Bus swagger errors

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#962]
as mentioned here - https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md

/arm-servicebus/2015-08-01/swagger/servicebus.json#L44 
•	Operation should be named List and not ListBySubscription

Body parameter and the response MUST be the same for a PUT operation
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L109 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L335 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L639 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L847 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L1179 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L1390 
•	/arm-servicebus/2015-08-01/swagger/servicebus.json#L1736 

/arm-servicebus/2015-08-01/swagger/servicebus.json#L562 
•	Should be named Queues_ListByNamspace (instead of Queues_ListAll)

/arm-servicebus/2015-08-01/swagger/servicebus.json#L1102 
•	Should be named Topics_ListByNamspace (instead of Topics_ListAll)

/arm-servicebus/2015-08-01/swagger/servicebus.json#L1645 
•	Should be named Subscriptions_ListByTopic (instead of Subscriptions_ListAll)

description missing for:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2015-08-01/swagger/servicebus.json#L2253 
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2015-08-01/swagger/servicebus.json#L2392 
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2015-08-01/swagger/servicebus.json#L2516

**Comment by anuchandy** [comment]
* Does service supports "text/json" payload ? if not please remove it from consumes and produces section.

* The following properties are declared as "String", from the documentation it seems they should be numeric types.

    QueueProperties::lockDuration
    QueueProperties::autoDeleteOnIdle
    QueueProperties::defaultMessageTimeToLive
    QueueProperties::duplicateDetectionHistoryTimeWindow
    TopicResourceInner::autoDeleteOnIdle
    TopicResourceInner::defaultMessageTimeToLive
    TopicResourceInner::duplicateDetectionHistoryTimeWindow

* The 'unit' of following properties are not indicated in the property name or in the property description. It will be helpful if we can reflect unit in names and update description accordingly.

   QueueProperties::lockDuration
   QueueProperties::autoDeleteOnIdle
   QueueProperties::defaultMessageTimeToLive
   QueueProperties::duplicateDetectionHistoryTimeWindow
   TopicResourceInner::autoDeleteOnIdle
   TopicResourceInner::defaultMessageTimeToLive
   TopicResourceInner::duplicateDetectionHistoryTimeWindow
   Two questions about the property - QueueProperties::autoDeleteOnIdle

* There are two properties 'queueProperties::duplicateDetectionHistoryTimeWindow' and 'queueProperties::requiresDuplicateDetection'. The description of 'duplicateDetectionHistoryTimeWindow' says - "TimeSpan structure that defines the duration of the duplicate detection history"

    What exactly it is meant by 'TimeSpan structure'?
    Does server use 'duplicateDetectionHistoryTimeWindow' value as history length for duplicate detection only if 'requiresDuplicateDetection' is true?

Can we add these information to the description?

* Two questions about the property - QueueProperties::autoDeleteOnIdle. The description says "The TimeSpan idle interval after which the queue is automatically deleted"

    Suppose user want to disable auto delete of queue then what should be the value set to this property? (-1, 0 ?)
   What is the unit of timespan (e.g. seconds, minutes, days) ?

Can we add these information to the description?
Can we fix same this for TopicProperties::autoDeleteOnIdle, subscriptionProperties:: autoDeleteOnIdle as well?

**Comment by anuchandy** [comment]
Could you confirm that DELETE on Queue and Topic resource are instant action (non-LRO)? Namespace DELETE is defined as LRO, but same operation on Queue and Topic is defined as non-LRO, would like to ensure this is really the behavior.

**Comment by sazeesha** [comment]
Yes, DELETE on Queue and Topic resource are instant action unlike namespace.

**Comment by sazeesha** [comment]
@v-Ajnava we should remove "service supports "text/json" payload " from consumes and produces section.

**Comment by sazeesha** [comment]
@anuchandy about questions related to TimeSpan our service supports [C#  Standard TimeSpan Format](https://msdn.microsoft.com/en-us/library/ee372286(v=vs.110).aspx) while Swagger supports only ISO8601 format. We had rolled out a change in our service to support ISO8601 but have had a major incident and we had to roll out that change.We will be supporting that with a newer API version, we plan to do that some time next month.

**Comment by sazeesha** [comment]
@anuchandy Does SB RP return an error response with properties more than code and message? 
No, so we do not need to define a new response object.

**Comment by anuchandy** [comment]
@sazeesha Thank you for the clarification. 

1. Can we include the TimeSpan wire format in the properties description?

2. If the user wants to disable auto delete of queue then what should be the value set to the property QueueProperties.autoDeleteOnIdle? TimeSpan.MaxValue [10675199.02:48:05.4775807], TimeSpan.Zero [00:00:00], TimeSpan.MinValue [-10675199.02:48:05.4775808] or anything else? Can we include this information in the description?

**Comment by sazeesha** [comment]
@anuchandy yes, @v-Ajnava lets put a link to [C# Standard TimeSpan Format ](https://msdn.microsoft.com/en-us/library/ee372286(v=vs.110).aspx)in the description wherever we use the TimeSpan format in the service and on the wire it can still be a string.

**Comment by v-Ajnava** [comment]
@anuchandy, added a link in description as suggested by Zeeshan.

**Comment by anuchandy** [comment]
thanks @v-Ajnava @sazeesha!. @hovsepm are you fine with closing this issue?
