### ISSUE TITLE
CostManagement: property key dataset is inconsistent with what HTTP response content.

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-rest-api-specs#9637]
https://github.com/Azure/azure-rest-api-specs/blob/98127bcfd62a92618a159936e7f05edb84aa9240/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01/costmanagement.json#L943-L948

The property key in Swagger is  all lowercase "dataset", however, the HTTP response content is “dataSet” with capital “S”. So the deserialization won’t work as expected.
  
![image](https://user-images.githubusercontent.com/14357159/83285618-1b09eb00-a211-11ea-9c9a-b1e0090c4a90.png)

So, the deserilization won't work for those properties under their parent dataset property: configuration, filter, grouping, aggregation.

Please fix it.

**Comment by ramaganesan-rg** [comment]
Team is investigating.

**Comment by ramaganesan-rg** [comment]
Team will circle back on an ETA. For this issue, Swagger needs an update.

**Comment by jochav** [comment]
Expected ETA for this update is Jan 2021.

**Comment by jochav** [comment]
Hello, can you please let us know if we can go ahead to close this issue?
You are welcome to reopen if you don't see the changes after Jan.
