### ISSUE TITLE
[Task] Clean up Microsoft.SQL's swagger files

### ISSUE THREAD

**Issue by allenjzhang** [Azure/azure-rest-api-specs#9640]
I have noticed a few issues with existing SQL swaggers:
1. Parameter and definitions are duplicated across resource JSONs in the same folder. Most of them are not even used in the current file.
2. Standard Parameters are not referencing common-types.
3. nit: Seems not following general layouts (such as standard parameters are scattered with body parameter, auth section is at the very bottom)

We should track this and work with each RP to refactor/cleanup their swaggers.

**Comment by ericshape** [comment]
they have been resolve in 2020-08-01-preview and later version.
