### ISSUE TITLE
[Compute] Missing support for 'Standard_Fx' VM sizes

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-rest-api-specs#965]
The following VM size types from class 'VirtualMachineSizeTypes':
"Standard_F1"
"Standard_F2"
"Standard_F4"
"Standard_F8"
"Standard_F16"
"Standard_F1s"
"Standard_F2s"
"Standard_F4s"
"Standard_F8s"
"Standard_F16s"
"Standard_H8"
"Standard_H16"
"Standard_H8m"
"Standard_H16m"
"Standard_H16r"
"Standard_H16mr"
"Standard_L4s"
"Standard_L8s"
"Standard_L16s"
"Standard_L32s"
"Standard_NV6"
"Standard_NV12"
"Standard_NV24"
"Standard_NC6"
"Standard_NC12"
"Standard_NC24"
"Standard_NC24r"

This causes a deserialization error when user queries VMs that use one of these sizes, as there is no known enum value for it.

See https://github.com/Azure/azure-sdk-for-python/issues/1007

**Comment by hyonholee** [comment]
Resolved: https://github.com/Azure/azure-rest-api-specs/pull/1238
