### ISSUE TITLE
[Need clarification] Constraints for global parameters in spec

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-rest-api-specs#971]
There are few swagger specs where constraints for global parameters are defined

e.g. [event-hub](https://github.com/v-Ajnava/azure-rest-api-specs/blob/59ed43fc1e362a79bdf7a304178f25b9640000a9/arm-eventhub/2015-08-01/swagger/EventHub.json#L1394)

```
    "resourceGroupNameParameter": {
      "name": "resourceGroupName",
      "in": "path",
      "required": true,
      "type": "string",
      "minLength": 1,
      "maxLength": 90,
      "x-ms-parameter-location": "method",
      "description": "Name of the Resource group within the Azure subscription."
    },
```

Whats our take on this? since this is not a service specific param but ARM level, shouldn't we recommend not to specify constraints for ARM level params in each swagger?

**Comment by amarzavery** [comment]
This will be solved very soon with common-definitions. @ravbhatnagar has a [PR in the private repo](https://github.com/Azure/azure-rest-api-specs-pr/pull/40) that solves some aspects of it. Gaurav, this is a prime reason why we should describe common parameters like subscriptionId, resourceGroupName, tenantId, etc. in the common-definitions json file.

**Comment by anuchandy** [comment]
Thanks @amarzavery.

For others going through this issue, refer Amar's comment here https://github.com/Azure/azure-rest-api-specs-pr/pull/40/files/0ba36a87da01f90d9009aa4c36558647901f6b23#diff-6d2e562c0905180644866bfe3dcbccca about including resource group, subscription global params in common-types.

**Comment by amarzavery** [comment]
@anuchandy - This is not ready for prime-time yet. It will be ready soon. Just wanted to let you know that something like this is being designed :).

**Comment by anuchandy** [comment]
closing this.
