### ISSUE TITLE
Restoring deleted database from the tagged LTR backup is not working

### ISSUE THREAD

**Issue by unagaraju88** [Azure/azure-rest-api-specs#9748]
Hi Team,

We have tagged all the resources in Azure using terraform. Followed terraform-providers/terraform-provider-azurerm#1802 (comment) to add LTR backup policy to the tagged resources like azure database.

There is no option to add tags in azure portal or using Powershell commands to restore the deleted databases.So I am looking for ARM template as mentioned in above link to restore the deleted databases from LTR backup.

Here are the references for the issue: 

https://github.com/MicrosoftDocs/azure-docs/issues/54838
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1802

Can you please let me know when can this feature be made available?

Thanks!!

**Comment by shkale-msft** [comment]
@unagaraju88, Thank you for your feedbac! This feature is not available yet and unfortunately, I do not have a timeline to share with you for this. We have added this to our backlog. Please feel free to leave us feedback about the same on User Voice: https://feedback.azure.com/forums/217321-sql-database.
