### ISSUE TITLE
the json files under entityType folder should also be included explicitly in the input-file configuration

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-rest-api-specs#9764]
In datafactory.
 the Trigger https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L9 is the polymorphic base class.
And MutipliePipelineTrigger https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L55 is the subclass of Trigger which has x-ms-discriminator-value 
And BlobTrigger https://github.com/Azure/azure-rest-api-specs/blob/codegen-datafactory-onboard-cli/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Trigger.json#L248 is the subclass of MutipliePipelineTrigger. Which doesn't have the x-ms-discriminator-value.
It will cause modelerfour left the BlobTrigger model definition. As the issue descriptioned here. https://github.com/Azure/autorest.modelerfour/issues/220

Currently I include all the model definition json file explictly in readme.az.md to avoid this error. https://github.com/Azure/azure-rest-api-specs/pull/8531#discussion_r436468214

For further consideration, it's better to add x-ms-discriminator-value in all the subclass to fix it in the swagger.

**Comment by lmy269** [comment]
@spagarwa to fix this particular issue. @shawnxzq, shall we check x-ms-discriminator-value is set for other cases?

**Comment by shawnxzq** [comment]
We understand its value will be the same as the type name if it is not set. So in our current practice, we may not set it if we want to use the type name as the value.

**Comment by spagarwa** [comment]
Schedule trigger is also derived from MultiplePipelineTrigger. Based on Shawn's comment we do not need this change. Closing the thread

**Comment by qiaozha** [comment]
@shawnxzq  @spagarwa After I talked with @daviwil, Because all the json files under entityTypes folder are not explicitly include in the input file, it's considered to be a supporting file. And for those definition in the supporting file the code model will only keep it unless it's explicitly referenced by like $ref and x-ms-discriminator-value is also considered as explicitly reference, otherwise those definition will be discard. 

The recommanded solution to this issue is to add those json file under entityTypes folder into the input-file configuration of readme.md like this one  https://github.com/Azure/azure-rest-api-specs/pull/8531/files#diff-7da5d24e50361d2d2ee4cc8cedde44f6R14-R19

cc @daviwil

**Comment by daviwil** [comment]
@qiaozha is correct, the optimal solution here is to add any files with schemas that _must_ appear in the generated code to the `input-files` list so that they are not discarded.

**Comment by shawnxzq** [comment]
@qiaozha I am not sure understand you correctly, I will schedule an offline discussion with you to understand more details, thanks a lot!

**Comment by shawnxzq** [comment]
Offline discussed this with @qiaozha, we will add these files as input files, thanks!

**Comment by shawnxzq** [comment]
@qiaozha This is fixed, please help close this one, thanks!
