### ISSUE TITLE
`email` in security center don't support multiple address

### ISSUE THREAD

**Issue by lrxtom2** [Azure/azure-rest-api-specs#9772]
Hi Team,
Seems that `email` field in [Microsoft.Security/preview/2017-08-01-preview/SecurityContacts](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/securityContacts.json) don't support multiple addresses that don't match the behavior at portal. Please have check.
![image](https://user-images.githubusercontent.com/20538091/84035822-e6472200-a9ce-11ea-884e-ce6c17e04726.png)

**Comment by erich-wang** [comment]
Routing to security center team to follow up, thanks.

**Comment by lrxtom2** [comment]
Have anyone following up the issue? 
Thanks for that.

**Comment by tarosler** [comment]
@lrxtom2 - each security contact supporting one item, but you can have multiple security contacts.

**Comment by gjtaylor** [comment]
The [2020-01-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/security/resource-manager/Microsoft.Security/preview/2020-01-01-preview/securityContacts.json) version supports a semi-colon delimited list in the renamed "emails" property

**Comment by AddySanto** [comment]
Can anyone confirm that gjtaylor's response addresses the issue?  Does this require further followup or is it safe to close this?
