### ISSUE TITLE
Service return a number but the swagger defines it as enum

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-rest-api-specs#9781]
in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2019-11-01-preview/kubernetesconfiguration.json#L377, the `messageLevel` is defined as enum, but the service side returns a number.

Also, there are other similar issue. The `EnableHelmOperator` is defined as string, but the service side returns boolean.

**Comment by ruowan** [comment]
We also detect the issue in live validation. Pls see link: https://portal.azure-devex-tools.com/amekpis/correctness/detail?errorId=896c479d-3120-414c-b70f-06da958a5880
