### ISSUE TITLE
Microsoft.DBforPostgreSQL - serversv2

### ISSUE THREAD

**Issue by aszykm** [Azure/azure-rest-api-specs#9795]
Hello,

I could not find any documents about the resource of type **serversv2**. 
The resource is used for the deployment Citus cluster.
In Azure Portal is possible to deploy Citus Cluster but I could not find any information about for example ARM template. I can only download a template from the portal but I did not see all properties.

Documents for resource **servers**, which is used for deployment single host PostgreSQL:
https://docs.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/allversions

Regards,
Mateusz Aszyk

**Comment by rachel-msft** [comment]
Hi @aszykm. Thanks for reaching out. At this time we only support creating Hyperscale Citus clusters via the Azure portal.

**Comment by evertonmc** [comment]
@rachel-msft Thank you for confirming that. Do you have an ETA for the API (even if it is in preview)? We need to include this in our ci/cd asap

**Comment by niklarin** [comment]
Hello @evertonmc. Thank you for your interest in our product! We expect Hyperscale (Citus) APIs to be available in coming months. Unfortunately we don't have specific date at this time. If it's blocking your Hyperscale (Citus) adoption, please don't hesitate to contact us at AskAzureDBforPostgreSQL@service.microsoft.com to discuss your situation and options.

**Comment by cenipe** [comment]
Hello @niklarin I've been following this up for several months now, is there any updates?
Thanks!

**Comment by KoomeKiriinya** [comment]
@niklarin any updates on this?

**Comment by flemminglundgls** [comment]
@niklarin Updates? I want to grab the FQDN in bicep, to create the connection string for webapp.
Still preview i see.

**Comment by niklarin** [comment]
> [@niklarin](https://github.com/niklarin) Updates? I want to grab the FQDN in bicep, to create the connection string for webapp. Still preview i see.

@flemminglundgls the REST API specs are published here: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/postgresqlhsc/resource-manager/Microsoft.DBforPostgreSQL

If you're looking for a GA version, 2022-11-08 is the one. 
If you need all latest features support, use the latest preview version 2023-03-02-preview
