### ISSUE TITLE
Full vault backup and restore should probably be marked as a long-running operation

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9806]
This operation should probably be marked with `x-ms-long-running-operation` since it documents an async operation and has a "pending" endpoint. See https://github.com/Azure/autorest/blob/8f3ccbd67460816a2085f947ddc7026899f4b1a2/docs/extensions/readme.md#x-ms-long-running-operation for details.

https://github.com/Azure/azure-rest-api-specs/blob/e691ceee865ab60d1f2dca5b35488aeb784da221/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/backuprestore.json#L149

**Comment by christothes** [comment]
I believe this is true for both backup and restore.
https://github.com/Azure/azure-rest-api-specs/blob/e691ceee865ab60d1f2dca5b35488aeb784da221/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/backuprestore.json#L58

**Comment by sebansal** [comment]
Key Vault doesn't currently provide a way to back up an entire key vault in a single operation. 
User can backup individual key vault objects https://docs.microsoft.com/en-us/azure/key-vault/general/backup

@heaths can you mark this as feature request

**Comment by jlichwa** [comment]
@heaths @sebansal entire key vault backup requires work on service side. This feature did not make it in this semester, hopefully next one.

**Comment by jlichwa** [comment]
@amitbapat from what I remember MHSM would have full backup and AKV would return not supported. I believe that marking it as long running should be valid?

**Comment by heaths** [comment]
Is this the right document for MHSM data plane operations?

**Comment by amitbapat** [comment]
@vasanthrajams and @vickm to address.

**Comment by sebansal** [comment]
Ping @vasanthrajams

**Comment by sebansal** [comment]
Ping @vickm

**Comment by vasanthraja** [comment]
Yes heath, https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/backuprestore.json is for the MHSM dataplane operation.

**Comment by heaths** [comment]
Thank you. /cc @christothes
