### ISSUE TITLE
Full vault restore swagger some types missing descriptions or with ambiguous names

### ISSUE THREAD

**Issue by christothes** [Azure/azure-rest-api-specs#9812]
### Missing descriptions
https://github.com/Azure/azure-rest-api-specs/blob/9a54fc6b253e65affca9ba35d4c25052e5bcc12c/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/backuprestore.json#L274

https://github.com/Azure/azure-rest-api-specs/blob/9a54fc6b253e65affca9ba35d4c25052e5bcc12c/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/backuprestore.json#L289

### Ambiguous names
The common Error type gets flagged by some generators as being too generic. Could we possibly rename it to something like `KeyValuOperationError` or `KeyVaultServiceError`?

https://github.com/Azure/azure-rest-api-specs/blob/9a54fc6b253e65affca9ba35d4c25052e5bcc12c/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/common.json#L52

**Comment by jlichwa** [comment]
@amitbapat is that related to full backup?

**Comment by amitbapat** [comment]
@vasanthrajams and @vickm to address.

**Comment by sebansal** [comment]
Ping @vasanthrajams

**Comment by sebansal** [comment]
Ping @vickm

**Comment by sebansal** [comment]
Is there an internal ADO work item open to track @vasanthrajams @vickm

**Comment by sebansal** [comment]
Ping @vasanthrajams

**Comment by vasanthrajams** [comment]
The first part of the changes for this issue already been merged. https://github.com/Azure/azure-rest-api-specs/pull/11772
The second part of this issue(Ambiguous Names) was discussed in an email titled "AKV - github issues #ServiceAttention" and the consensus was to ignore for now.

**Comment by sebansal** [comment]
Thank you @vasanthrajams, will close the issue for now.
