### ISSUE TITLE
Provide x-ms-examples for filter usage in alert_rules and autoscale_settings

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-rest-api-specs#982]
I see that we have some x-ms-examples but It’d be great if you can provide x-ms-examples with use of “filter” for [AutoscaleSettings_ListByResourceGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/2015-04-01/swagger/autoscale_API.json#L24) & [AlertRules_ListByResourceGroup](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/2016-03-01/swagger/alertRules_API.json#L215). That way I can reverse engineer the usage and we have better examples for filter usage in the documentation as well. 

Let me know your thoughts on this.

**Comment by gucalder** [comment]
This incident does not apply any longer due to the incident #1017 
I am removing the filter parameter from both calls, they are not supported anyway and any call with these values will fail.
