### ISSUE TITLE
Error creating a billing role assignment

### ISSUE THREAD

**Issue by jf781** [Azure/azure-rest-api-specs#9852]
When attempting to create a billing role assignment I get the following error. 

```json
{
    "errors": {
        "properties.PrincipalId": [
            "PrincipalId or UserEmailAddress/UserAuthenticationType must be specified."
        ],
        "properties.RoleDefinitionId": [
            "The RoleDefinitionId field is required."
        ],
        "properties.UserEmailAddress": [
            "PrincipalId or UserEmailAddress/UserAuthenticationType must be specified."
        ],
        "properties.UserAuthenticationType": [
            "PrincipalId or UserEmailAddress/UserAuthenticationType must be specified."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|4282ee38-43a4536608001b1d."
}
```

The request I'm using is:

```bash
curl --location --request POST 'https://management.azure.com/providers/Microsoft.Billing/billingAccounts/xxx/createBillingRoleAssignment?api-version=2019-10-01-preview' \
--header 'Authorization: Bearer xxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "principalId": "xxx",
    "billingRoleDefinitionId": "/providers/Microsoft.Billing/billingAccounts/xxx/providers/Microsoft.Billing/billingRoleDefinition/10000000-aaaa-bbbb-cccc-100000000000"
}'
```

I've tried to tweak the body a number of different ways but with the same error.  

I'm able to successfully query the current billing role assignments but am not able to create a new one. 

Any thoughts on what I should be trying different?

**Comment by wilcobmsft** [comment]
For --data-raw, can you try passing in the following value?

```
--data-raw '{
  "properties": {
    "principalId": "xxx",
    "roleDefinitionId": "/providers/Microsoft.Billing/billingAccounts/xxx/providers/Microsoft.Billing/billingRoleDefinition/10000000-aaaa-bbbb-cccc-100000000000"
  }
}'
```

Note how the properties are wrapped inside a "properties" property, and instead of billingRoleDefinitionId we're using roleDefinitionId.

**Comment by jf781** [comment]
Thanks Wilco for taking a look.   I tried using the code you provided as shown below but I am getting an error that the resource Id is not valid.  (Though guessing this is cause I had the wrong ID in my example.   

```json
{
    "properties": {
        "principalId": "xxx",
        "roleDefinitionId": "/providers/Microsoft.Billing/billingAccounts/xxx/providers/Microsoft.Billing/billingRoleDefinition/10000000-aaaa-bbbb-cccc-100000000000"
    }
}
```

This is the output:
```json
{
    "code": "BadRequest",
    "message": "InvalidRoleId: Input Role Ids (10000000-aaaa-bbbb-cccc-100000000000) are not valid for the given Commerce Object Type(Organization)."
}
```

I did some more digging and found the following role IDs.

50000000-aaaa-bbbb-cccc-100000000002 = "Reader"
50000000-aaaa-bbbb-cccc-100000000001 = "Contributor"
50000000-aaaa-bbbb-cccc-100000000000 = "Owner"

Here is my final message body

```json
--data-raw '{
    "properties": {
        "principalId": "xxx",
        "RoleDefinitionId": "/providers/Microsoft.Billing/billingAccounts/xxx/providers/Microsoft.Billing/billingRoleDefinition/50000000-aaaa-bbbb-cccc-100000000002"
    }
}'
```

Going to submit a request to update the documentation to reflect the roleID and also add the ID's for the various roles since I couldn't find them anywhere else.  

Again, Appreciate the help @wilcobmsft Got me pointed in the write direction!!
