### ISSUE TITLE
Document includeSanitizedConnectionString query parameter data sources

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9876]
There is an `includeSanitizedConnectionString` query parameter that is not documented for data source APIs like [this one](https://docs.microsoft.com/rest/api/searchservice/update-data-source) that will send back a sanitized connection string, which is normally omitted for security reasons. Customers may want to see what non-PII they can, so it might be helpful to document this for any APIs that support it; however, it's important to warn users that sending it back sanitized will be destructive.

**Comment by brjohnstmsft** [comment]
FYI @bleroy -- Please route to the right owner

**Comment by brjohnstmsft** [comment]
@mattmsft, please confirm that this is still on your radar.

**Comment by mattmsft** [comment]
Confirmed. I'll take a look at this soon.
