### ISSUE TITLE
Mark backuprestore.json operations as long-running operations

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#9885]
Back and restore operations in backuprestore.json appear to be implemented as long-running operations (LROs). It would help our generators for the Azure SDK for Key Vault if those were properly authored as LROs like in [securitydomain.json](https://github.com/Azure/azure-rest-api-specs/pull/9647/files#diff-f68bf6cc6d3ee4a9588c1f7b8c1aa190R113).

**Comment by jlichwa** [comment]
@amitbapat I think it is related to full backup, can you get help from engineering team ?

**Comment by amitbapat** [comment]
@vasanthrajams and @vickm to address this.

**Comment by vickm** [comment]
@vasanthrajams will close this by end of month.

**Comment by heaths** [comment]
@catalinaperalta can you use a README transform instead? At least right now, this could be disruptive for some partners about to ship with these model names.

**Comment by vasanthrajams** [comment]
We already have made the required changes for marking LRO https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/backuprestore.json

Verified this with heaths.
