### ISSUE TITLE
billing: x-ms-pageable is missing in BillingAccount_List of 2019-10-01-preview

### ISSUE THREAD

**Issue by yaegashi** [Azure/azure-rest-api-specs#9890]
The `x-ms-pageable` attribute is missing in BillingAccounts_List  of 2019-10-01-preview version:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/billing/resource-manager/Microsoft.Billing/preview/2019-10-01-preview/billing.json#L20-L63

while it exists in BillingAccount_List of 2018-11-01-preview version:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/billing/resource-manager/Microsoft.Billing/preview/2018-11-01-preview/billing.json#L20-L66

Is it intended, or just forgotten to include?

**Comment by amberbhargava** [comment]
@yaegashi it indeed is a miss in the 2019-10-01-preview version. We're working on the GA version of the API, which should be available in the next couple of months. x-ms-pageable will be added to the GA version.

**Comment by yaegashi** [comment]
@amberbhargava Thanks for the clarification.  I was a bit confused, 2020-05-01 stable version was indeed present in billing, but it's actually 2020-05-01-preview in the Go SDK for which I was going to generate by myself.  Can I expect it to become 2020-05-01 stable when it's GA?

**Comment by asarkar84** [comment]
@yaegashi Please expect the stable version 2020-05-01 to be available very soon with the x-ms-pageable attribute. Please do not refer the 2020-05-01-preview version. Thank you!

**Comment by ramaganesan-rg** [comment]
closing this issue as its now fixed. Please feel free to reopen this as needed.
