### ISSUE TITLE
Undocumented API - Microsoft.Security/securitySolutions

### ISSUE THREAD

**Issue by krise86** [Azure/azure-rest-api-specs#9901]
The api is mentioned in the powershell script 
https://github.com/Azure/Azure-Security-Center/tree/master/Powershell%20scripts/Vulnerability%20Solution

But there is no spec on this so i am unable to add a new solution to an existing one like we can trough the webui

**Comment by ronari2** [comment]
Creating the VA solution
Fetch subscription home region (location)

GET https://management.azure.com/subscriptions/{SubscriptionId}/providers/Microsoft.Security/locations?{apiVersion}
Fetch the value in "homeRegionName"
Alternatively run "Get-AzSecurityLocation" when relevant subscription is set.
Prepare license code and public key

Qualys license code is provided by Qualys
Rapid7 License code is the base64 representation of the config zip file provided by Rapid7
Public key is provided by Qualys/Rapid7

Create the VA Security Solution:

PUT https://management.azure.com/subscriptions/{SubscriptionId}/resourceGroups/{SelectedResourceGroup}/providers/Microsoft.Security/locations/{subscriptionLocation}/securitySolutions/{SelectedSolutionName}?{apiVersion} (Current: api-version=2015-06-01-preview)
		With body:
			{
			Properties:{
			Location: "$($loc)",
			Template: "rapid7.insightplatform",
			ProvisioningParameters:
			"{\"Licensecode\":\"{ConfigZipFileInBase64}\",\"publicKey\":\"{publicKey}\",\"autoUpdate\":{true/false}}"
			}
		Or:
			{
			Properties:{
			Location: "$($loc)",
			Template: "qualys.qualysAgent",
			ProvisioningParameters:
			"{\"Licensecode\":\"{QualysLicense}\",\"publicKey\":\"{QualysPublicKey}\",\"autoUpdate\":{true/false}}"
			}

Make sure you see the solution in the UI.

**Comment by AddySanto** [comment]
My understanding is that ronari2's response demonstrates how to add a new solution to an existing one, which was krise86's question.  I'm closing this ticket.
