### ISSUE TITLE
monitor: activityLogAlerts_API.json (2017-04-01) missing property: `containsAny`

### ISSUE THREAD

**Issue by magodo** [Azure/azure-rest-api-specs#9906]
The model [`ActivityLogAlertLeafCondition`](https://github.com/Azure/azure-rest-api-specs/blob/80784443eefe04bf6f4d253f9f210044e6d432b1/specification/monitor/resource-manager/Microsoft.Insights/stable/2017-04-01/activityLogAlerts_API.json#L408) defined in Swagger only contains properties: `field` and `equals`. While in the response json, it contains `containsAny` field, which for example could be used to indicate the regions criteria as below:

```json
{
    "field": "properties.impactedServices[*].ImpactedRegions[*].RegionName",
    "equals": null,
    "containsAny": [
        "Australia Central",
        "Australia Central 2",
    ],
    "odata.type": null
}
```
Lack of the declaration in Swagger impacts the models generated by SDK.

**Comment by TamRuas** [comment]
@magodo  - Thanks for reaching out. 
We are aware of this, and have Bug[7359079 ]( https://msazure.visualstudio.com/DefaultCollection/One/_workitems/edit/7359079) to fix it in July.

**Comment by ricohomewood** [comment]
@TamRuas did this bug, 7359079, get fixed in July? I don't see the fix in the latest stable version of the API?
Thanks

**Comment by jhauray** [comment]
I agree With @ricohomewood, the issue seems not to be fixed. Why it has been closed ?

**Comment by magodo** [comment]
@TamRuas Would you please double confirm whether this is fixed? If not, please reopen this issue to track it. Thanks!
