### ISSUE TITLE
[Logic] AutoRest Linter validation errors for ARM resource properties bag

### ISSUE THREAD

**Issue by daviburg** [Azure/azure-rest-api-specs#995]
We need guidance at to what's the proper way to specify the ARM resource properties bag in the logic app swagger.

Multiple instances of:
{
    "type": "Error",
    "code": "ArmResourcePropertiesBag",
    "message": "Top level property names should not be repeated inside the properties bag for ARM resource \"WorkflowVersion\". Properties [properties] conflict with ARM top level properties. Please rename these.",
    "jsonref": "arm-logic/2016-06-01/swagger/logic.json#/definitions",
    "json-path": "arm-logic/2016-06-01/swagger/logic.json#/definitions",
    "id": "M3019",
    "validationCategory": "RPCViolation",
    "providerNamespace": null,
    "resourceType": null
  },

**Comment by fearthecowboy** [comment]
I'm pretty sure that this is not a correct validation message. 

I filed an autorest bug https://github.com/Azure/autorest/issues/1906 on this. 

IFAIK you can ignore this, right @amarzavery ?

**Comment by amarzavery** [comment]
@sarangan12, @veronicagg - I was talking about this rule in the meeting today morning. "WorkflowVersion" is supposed to have a property named "properties". Inside this properties there will be a reference to another complex object and there will be an "x-ms-client-flatten" extension.

So, flagging "properties" IMO, is not the right thing to do.

**Comment by veronicagg** [comment]
We're tracking the rule issue with https://github.com/Azure/autorest/issues/1967

**Comment by kirthik** [comment]
Closing this since this is being tracked in AutoRest repository.
