### ISSUE TITLE
Default status code handling is missing in the Monitor specs 

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-rest-api-specs#998]
according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#naming---swagger-checklist 

 M2049: Every operation MUST have a "default" status code in the "responses" section. The "default" corresponds to the error returned by the operation.

please fix in all the specs.

**Comment by sarangan12** [comment]
@hovsepm 

Having a default response code is recommended. Usually, when a swagger file comes for a PR and when we do not find a default response code, we normally request to add a default response code. But, even in cases where there is no default response code, autorest will handle the sceario by adding the cloud exception as default error response code. So, we are enforcing this rule on a case-by-case basis on PRs and it is not required to add them ourselves at one shot (Actually, for some service you cannot add the default response as we cannot model their error hierarchy now). 

So, I do no see any further action items on this issue. Closing this now
